### ISSUE TITLE
[Add] Patrick Collins Yt Channel

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#1001]
### Site URL

https://www.youtube.com/@PatrickAlphaC

### Description of the above provided site

This channel offers comprehensive videos for individuals interested in beginning their journey and acquiring expertise in web3 development and blockchain, covering both beginner and advanced levels.

### Category

Youtube

### Sub Category

Web3

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Shiva-Sai-ssb any updates please?

**Comment by rupali-codes** [comment]
@Shiva-Sai-ssb are you still working on this issue?

**Comment by k-deepak04** [comment]
Closing as no response from a long time
