### ISSUE TITLE
[Style] Sync overlay transition with sidebar transition in mobile view

### ISSUE THREAD

**Issue by bose-aritra2003** [rupali-codes/LinksHub#1007]
### What would you like to share or ask?

When in mobile view, one has to click the hamburger to open the sidebar. And when the sidebar is open, there is dark background overlay. But the transitioning of this overlay is not in sync with the transitioning of the sidebar, and it kind of feels sudden. So I think it would slightly enhance the UI if the background overlay properly transitions-in in sync with the transitioning of the sidebar.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @bose-aritra2003! :) I'm struggling to understand the issue. Can you add a screenshot for clarification please?

**Comment by bose-aritra2003** [comment]
> Hi @bose-aritra2003! :) I'm struggling to understand the issue. Can you add a screenshot for clarification please?

See dark overlay behind when the sidebar is open. That doesn't transition smoothly with sidebar, it just suddenly appears when the sidebar is opened.
<img width="398" alt="Screenshot 2023-06-11 at 19 49 34" src="https://github.com/rupali-codes/LinksHub/assets/77151837/cdb99631-826c-4155-bbcb-41ba21f2a5ae">

**Comment by rupali-codes** [comment]
> > Hi @bose-aritra2003! :) I'm struggling to understand the issue. Can you add a screenshot for clarification please?
> 
> @CBID2 See dark overlay behind when the sidebar is open. That doesn't transition smoothly with sidebar, it just suddenly appears when the sidebar is opened. <img alt="Screenshot 2023-06-11 at 19 49 34" width="398" src="https://user-images.githubusercontent.com/77151837/244943325-cdb99631-826c-4155-bbcb-41ba21f2a5ae.png">

Whoops, thanks. You may start working on the issue

**Comment by rupali-codes** [comment]
@bose-aritra2003 are you still working on this issue?

**Comment by bose-aritra2003** [comment]
> @bose-aritra2003 are you still working on this issue?

I'm sorry, but I'm unable to fix the issue because the overlay is created in a very different way compared to the known way. I think you should assign this to someone more competent to handle this issue.

**Comment by JakubChorzepa** [comment]
Hey, I could try to solve that issue if no one is working currently on it.

**Comment by CBID2** [comment]
> Hey, I could try to solve that issue if no one is working currently on it.

Let's see what @bose-aritra2003 says first @JakubChorzepa.

**Comment by bose-aritra2003** [comment]
> Hey, I could try to solve that issue if no one is working currently on it.

Yea sure.

**Comment by CBID2** [comment]
> > Hey, I could try to solve that issue if no one is working currently on it.
> 
> Yea sure.

Thanks @bose-aritra2003. @JakubChorzepa, go on ahead
