### ISSUE TITLE
[DOCS] remove grammatically error & spelling mistakes from code

### ISSUE THREAD

**Issue by gulshanjakhon** [rupali-codes/LinksHub#1009]
### Issue Description

Hi, I want to work on the documentation related to grammatical error, and spelling mistakes, and also work on some changes that increase the build quality of the project. 
please assign me under gssoc23 label. 
Thank You

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @gulshanjakhon! I have two questions:
1. Can you share a screenshot of the grammar errors you see?
2. Are you participating in GSSOC'23(Just double checking)?

**Comment by gulshanjakhon** [comment]
> Hi @gulshanjakhon! I have two questions:
> 
> 1. Can you share a screenshot of the grammar errors you see?
> 2. Are you participating in GSSOC'23(Just double checking)?

**yes I am participating in GSSOC'23**

**Comment by CBID2** [comment]
> > Hi @gulshanjakhon! I have two questions:
> > 
> > 1. Can you share a screenshot of the grammar errors you see?
> > 2. Are you participating in GSSOC'23(Just double checking)?
> 
> **yes I am participating in GSSOC'23**

Great! Can you answer question 1 too @gulshanjakhon?
