### ISSUE TITLE
[ADD] add new section:  Student Partner program

### ISSUE THREAD

**Issue by gulshanjakhon** [rupali-codes/LinksHub#1010]
### Category Name

OTHERS

### Subcategory Name

Student Partner program

### Additional Context

I want to add a new section under the 'OTHERS" Category, that contains all the  Campus Ambassador programs. that are initiatives taken by some big tech companies like Amazon, Google, Flipkart, GFG, Microsoft and many more.

**- Some programs are:**

- GitHub Campus Expert
- Microsoft Learn Student Ambassador program
- Developer Student Club
- and many more.

Please assign me under the gssoc23 label.

**Thank you
GSSOC23 Contributor**

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @gulshanjakhon! :) You just raised this[issue](https://github.com/rupali-codes/LinksHub/issues/1009), so focus on that one for now.

**Comment by gulshanjakhon** [comment]
Hi @CBID2 please assign me this issue

**Comment by gulshanjakhon** [comment]
also please suggest where I can place **_Student Partner program_** under which category. or make a new section.

**Comment by CBID2** [comment]
> also please suggest where I can place **_Student Partner program_** under which category. or make a new section.

I think you can add them to the open source category. @rupali-codes and @ujjawaltyagii what do you think?

**Comment by ujjawaltyagii** [comment]
> > also please suggest where I can place **_Student Partner program_** under which category. or make a new section.
> 
> I think you can add them to the open source category. @rupali-codes and @ujjawaltyagii what do you think?

Ig we should add it in Other-Resource or Community sub-category in `Other` ?

**Comment by gulshanjakhon** [comment]
fine, I will add it under the Other-> Community sub-category 
@CBID2 @ujjawaltyagii @rupali-codes

**Comment by CBID2** [comment]
> fine, I will add it under the Other-> Community sub-category 
> 
> @CBID2 @ujjawaltyagii @rupali-codes 

Great! :)
