### ISSUE TITLE
[ADD] <Videos to Open Source Category>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1015]
### Category Name

Open Source

### Subcategory Name

videos 

### Additional Context

Hi, @rupali-codes and @ujjawaltyagii! :) I want to add a video to the Open Source section(see #1014 for context), but I noticed that it did not have "Videos" as a subcategory, so I suggest that we add this section.  

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
I guess we do have it, i rememeber i've reviewed a PR for this once before

**Comment by rupali-codes** [comment]
@CBID2 are you still working on this issue?

**Comment by CBID2** [comment]
> @CBID2 are you still working on this issue?

Yeah, I was just waiting on your opinion about it.

**Comment by rupali-codes** [comment]
> > @CBID2 are you still working on this issue?
> 
> Yeah, I was just waiting on your opinion about it.

i guess that would be awesome, we can go for it

**Comment by ujjawaltyagii** [comment]
That would be great !! You can go ahead with that

**Comment by rupali-codes** [comment]
@CBID2 👀

**Comment by CBID2** [comment]
> @CBID2 👀

Sorry been busy with other stuff. I'll do it later @rupali-codes
