### ISSUE TITLE
[Add] Javascript30

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#1016]
### Site URL

https://javascript30.com/

### Description of the above provided site

JavaScript30 is an online educational platform that offers a free 30-day JavaScript coding challenge. It was created by Wes Bos, a well-known web developer and educator.

### Category

Languages

### Sub Category

javascript

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by krishstwt** [comment]
This is an amazing website +1
