### ISSUE TITLE
[Feature] Adding keyboard shortcut to directly search 

### ISSUE THREAD

**Issue by milan-lakhani** [rupali-codes/LinksHub#1024]
### Description

As our resources are getting bigger, I feel the need to include a keyboard shortcut dedicated to start searching instantly. It is a small improvement of life. [Tailwind](https://tailwindcss.com) has CTRL+K as the quick way to search the documentation. And they also encourage it by mentioning it in the frontend.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
This sounds promising @milan-lakhani! :) What do you think @rupali-codes? @ujjawaltyagii?

**Comment by ujjawaltyagii** [comment]
Couldn't agree more with this idea !!
I think we should go ahead with this feature.

**Comment by CBID2** [comment]
> Couldn't agree more with this idea !! I think we should go ahead with this feature.

Great @ujjawaltyagii! :) @milan-lakhani, I just assigned you! :)

**Comment by milan-lakhani** [comment]
@ujjawaltyagii @rupali-codes @CBID2 What do you guys think of using algolia search? it has a free plan for [open source projects](https://www.algolia.com/for-open-source/)

**Comment by rupali-codes** [comment]
> This is what an algolia FAQ says about the plan we get after we get algolia approval.
> 
> > Standard PAYG plan and to include 200 units for free which translates to 200,000 records and 200,000 search requests (and up to 2,000,000 indexing operations) per month (a $180/month value).

Oh, sounds great

**Comment by k-deepak04** [comment]
@milan-lakhani any updates?

**Comment by rupali-codes** [comment]
We're closing this issue as not activity was shown, if you still want to work on this issue, please ping us on our discord server
