### ISSUE TITLE
[OTHER] Updating READEM.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [rupali-codes/LinksHub#103]
### What would you like to share or ask?

I think adding a logo and a slogan before the welcome message would look better
and if the idea sounds good I would like to work on it!

### Additional information

For example one of my earlier contributions :
![image](https://user-images.githubusercontent.com/121221252/214815059-42707185-51c0-4d55-9f33-b9bb54426311.png)

**Comment by rupali-codes** [comment]
@the-amazing-atharva heya, are you sure you opened the issue in right repo?

**Comment by the-amazing-atharva** [comment]
yes
the above pic is just an example

my idea is to add the logo of linkshub to the README

**Comment by rupali-codes** [comment]
okay, thanks, you rise PR

**Comment by the-amazing-atharva** [comment]
can you paste the logo of your project here?
I couldnt find it in the code section

**Comment by rupali-codes** [comment]
@the-amazing-atharva we don't have any specific logo yet, but you can use this:
![image](https://user-images.githubusercontent.com/78981177/215044431-2d124fde-f04e-4168-8f90-c97f51892678.png)

**Comment by the-amazing-atharva** [comment]
Ok !

**Comment by rupali-codes** [comment]
hi @the-amazing-atharva, are you still working on this?

**Comment by the-amazing-atharva** [comment]
Extremely sorry for not sending a PR, the changes are done

**Comment by rupali-codes** [comment]
@the-amazing-atharva thank you :)

**Comment by imabhi241** [comment]
Hi, contributing guideline link is not working in the Readme. I would like to solve this issue.

**Comment by rupali-codes** [comment]
> Hi, contributing guideline link is not working in the Readme. I would like to solve this issue.

Hi, could you please create a new issue [here](https://github.com/rupali-codes/LinksHub/issues)

**Comment by imabhi241** [comment]
Ya sure
