### ISSUE TITLE
[Add] UI GENERATORS RESOURCE

### ISSUE THREAD

**Issue by Ameya02** [rupali-codes/LinksHub#1030]
### Site URL

https://chakra-ui.com/

### Description of the above provided site

Chakra UI is a simple, modular and accessible component library that gives you the building blocks you need to build your React applications.

### Category

Frontend

### Sub Category

ui generators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Bhanuteja01** [comment]
assign me
I'm gssoc contributor

**Comment by rupali-codes** [comment]
> assign me I'm gssoc contributor

do you still want to work on this issue?

**Comment by Ameya02** [comment]
No, you can assign it to someone

**Comment by k-deepak04** [comment]
@Ameya02 @Bhanuteja01 who is willing to work?

**Comment by Bhanuteja01** [comment]
@rupali-codes
I'm willing to work on this
Assign me

**Comment by k-deepak04** [comment]
done, please finish it as soon as possible
