### ISSUE TITLE
[Feature] <Add search suggestion in search bar >

### ISSUE THREAD

**Issue by Bhanuteja01** [rupali-codes/LinksHub#1031]
### Description

Add search suggestion in search bar
## Example
When we want to search "codewar"
If we enter "code" in search bar
It should suggest like this 
1.codewar
                                       2.codechef
                                 3. Related keyword start with code 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
This sounds interesting @Bhanuteja01. This could be helpful for users to find their desired sources quickly.

**Comment by Bhanuteja01** [comment]
@CBID2  add labels to this issue

**Comment by Bhanuteja01** [comment]
@vishnu9865
I'm not the person to assign this issue
Ask @rupali-codes  @CBID2  to assign this issue

**Comment by CBID2** [comment]
> @vishnu9865
> 
> I'm not the person to assign this issue
> 
> Ask @rupali-codes  @CBID2  to assign this issue

You're assigned @vishnu9865

**Comment by rupali-codes** [comment]
This issue is duplicate of #769
