### ISSUE TITLE
[Add] Canva Color

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#1032]
### Site URL

https://www.canva.com/colors/

### Description of the above provided site

A vibrant online platform offering a curated palette of inspiring colors to elevate your designs effortlessly.

### Category

Frontend

### Sub Category

colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@Oyebolade closing this as no responses received , if you still want to work and deliver the things quick  i will reopen it again, just tag me :)
