### ISSUE TITLE
[Add] Paletton

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#1039]
### Site URL

https://paletton.com/

### Description of the above provided site

This is a go-to platform for developers and designers, offering an intuitive interface to effortlessly explore, generate, and visualize stunning color schemes for your projects.

### Category

Frontend

### Sub Category

colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Oyebolade** [comment]
Yes, my PR has not been merged. I can't continue

**Comment by CBID2** [comment]
> Yes, my PR has not been merged. I can't continue

Ohh ok.

**Comment by rupali-codes** [comment]
@Oyebolade please don't create this much issues for just adding links, you create a single issue using Other template, then describe name, url and description of the site in there, and also, if you want to work on all the issues, raise a single PR

**Comment by Oyebolade** [comment]
All right, thanks

**Comment by rupali-codes** [comment]
> All right, thanks

are you working on these issues?

**Comment by Oyebolade** [comment]
> > All right, thanks
> 
> are you working on these issues?

Yes

**Comment by Oyebolade** [comment]
@CBID2 How should I go about it, my previous PR has not been merged.
Should I make another PR together with it?

**Comment by CBID2** [comment]
> @CBID2 How should I go about it, my previous PR has not been merged.
> 
> Should I make another PR together with it?

Can you link the other PR you're referring to @Oyebolade?

**Comment by Oyebolade** [comment]
> > @CBID2 How should I go about it, my previous PR has not been merged.
> > Should I make another PR together with it?
> 
> Can you link the other PR you're referring to @Oyebolade?

#942

**Comment by CBID2** [comment]
> > > @CBID2 How should I go about it, my previous PR has not been merged.
> 
> > > Should I make another PR together with it?
> 
> > 
> 
> > Can you link the other PR you're referring to @Oyebolade?
> 
> 
> 
> #942

@rupali-codes, you have to give an approval in PR #942.

**Comment by rupali-codes** [comment]
@Oyebolade your PR was merged, you may start working on this issue :)

**Comment by Oyebolade** [comment]
All right
