### ISSUE TITLE
[OTHER] add hover effect on Github and theme icons

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#104]
### What would you like to share or ask?

Having hover effect on icons in a website makes it more interactive for user, as of now we don't have any hover effect on Github and Theme icons. 

### Specific requirements
Add `text-violet-500` this  color when hovered on Github or theme icons. 

### Screenshots
![image](https://user-images.githubusercontent.com/78981177/215047969-c7398f78-2d61-4954-b03d-94f079112552.png)

**Comment by srujith-reddy** [comment]
is the issue still open? If it is open can you assign it to me

**Comment by haldaranup** [comment]
@srujith-reddy Sorry🙂 PR is already raised, you can look onto other open issues
