### ISSUE TITLE
[BUG] Categories not showing when the search  is empty

### ISSUE THREAD

**Issue by Ameya02** [rupali-codes/LinksHub#1042]
### Description

The Categories should be displayed when the search is empty or search is not in used

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/65841021/3c6c50c0-c44e-4d25-a171-26c1d90a207a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Ameya02 thanks for pointing this out, assigning to you!

**Comment by Ameya02** [comment]
I just had a query if you answer that then I will be working according to that
is the Search Button needed?
There is no dedicated search page so we can use search input directly for search queries instead of using the button and enter key

**Comment by Ameya02** [comment]
@rupali-codes mam also I have another issue #1030 which i made before  can you assign that too please

**Comment by CBID2** [comment]
> @rupali-codes mam also I have another issue #1030 which i made before can you assign that too please

Hi @Ameya02. You have to work on one issue at a time. Finish this one first and then I'll assign you to #1030 if it's still available(someone has expressed interest in doing it).

**Comment by rupali-codes** [comment]
@Ameya02 please add the respective issue in the description of this PR. (use _closes #issuenumber_)
