### ISSUE TITLE
[BUG]: display log messages on browser's console

### ISSUE THREAD

**Issue by harmeetsingh11** [rupali-codes/LinksHub#1043]
### Description

When a menu link is clicked, it displays/log object on the browser's console. Generally, its not a great idea to expose log messages in your production code.

### Screenshots

[LinksHub.webm](https://github.com/rupali-codes/LinksHub/assets/130365071/1d8a1a4c-144a-4893-a3e5-fd39f00e6e46)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Interesting observation @harmeetsingh11! :) @rupali-codes, what do you think?

**Comment by rupali-codes** [comment]
> Interesting observation @harmeetsingh11! :) @rupali-codes, what do you think?

Yeah, it should be removed

**Comment by harmeetsingh11** [comment]
Can I work on this issue under gssoc23?

**Comment by CBID2** [comment]
> Can I work on this issue under gssoc23?

Yeah sure @harmeetsingh11
