### ISSUE TITLE
[Add] <c programming respurces >

### ISSUE THREAD

**Issue by AravindAkuthota** [rupali-codes/LinksHub#1044]
### Site URL

https://youtube.com/playlist?list=PLdo5W4Nhv31a8UcMN9-35ghv8qyFWD9_S

### Description of the above provided site

The above video series or playlist is about c programming language by jennis lectures who teach the concept easy and understandard way 

### Category

Frontend

### Sub Category

Languages/ c programming 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@AravindAkuthota are you still working on this issue?

**Comment by k-deepak04** [comment]
@AravindAkuthota closing this as no responses received , if you still want to work and deliver the things quick i will reopen it again, just tag me :)
