### ISSUE TITLE
[BUG] Extra space in right side

### ISSUE THREAD

**Issue by kartikayasija** [rupali-codes/LinksHub#1047]
### Description

There is an extra space in the right side which is not looking good.

### Screenshots

<img width="344" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/115306535/ea11c816-6584-4429-8663-920df58baa5a">
<img width="960" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/115306535/cc4d0e9c-5f5c-4525-b14d-3cd8e7044ae8">

### Any additional information?

The space can be utilised and the UI can be improved.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
I guess you have raised the PR for it? could you please reference it properly?

**Comment by kartikayasija** [comment]
No, I have not raised the PR for this issue, I was waiting for the issue to get assigned.

**Comment by rupali-codes** [comment]
> No, I have not raised the PR for this issue, I was waiting for the issue to get assigned.

Okay, you may start working on this issue
