### ISSUE TITLE
[Add] Color Resource

### ISSUE THREAD

**Issue by Sriparno08** [rupali-codes/LinksHub#1048]
### Site URL

https://colorpalettes.net/

### Description of the above provided site

Color Palettes provide a free collection of color palette ideas for all occasions.

### Category

Frontend

### Sub Category

colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Sriparno08 thanks, you may go-ahead and rise the PR :)
