### ISSUE TITLE
[BUG] Incorrect positioning of 'Copy' 

### ISSUE THREAD

**Issue by kartikayasija** [rupali-codes/LinksHub#1049]
### Description

The copy word on hover has incorrect position.

### Screenshots

<img width="268" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/115306535/1caab322-1359-4fc3-a850-242b63817b68">

### Any additional information?

It will look better on top, not on left side.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@kartikayasija thanks, i guess that would be much better if we can the tooltip instead of this static button? You can use [react-tooltip](https://www.npmjs.com/package/react-tooltip. Please let us know if you need any kinda help :)

**Comment by kartikayasija** [comment]
Sure @rupali-codes , Tooltip would be better than the static button.
