### ISSUE TITLE
[BUG] Fix letter spacing for resource content

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1050]
### Description

The letter spacing on the content of resources is very high, which makes it appear weird.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/7d016091-d738-428c-b57e-b20dc410522f)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @Anmol-Baranwal
