### ISSUE TITLE
[ADD] Java in subcategory of Language

### ISSUE THREAD

**Issue by devWonderkind** [rupali-codes/LinksHub#1051]
### Category Name

Language

### Subcategory Name

JAVA

### Additional Context

Hey @CBID2 I want to Add Java language as subcategory of Language category and add link in this subcategory. Please assign this issue to me under GSSoC'23 label.

example:
![linkshb](https://github.com/rupali-codes/LinksHub/assets/110322061/75cdf6a5-81ff-4789-981f-bd43bb9dcfeb)

 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Before I do that, does this category already exist? You didn't click on the third checkbox @devWonderkind.

**Comment by devWonderkind** [comment]
Done! @CBID2

**Comment by rupali-codes** [comment]
@devWonderkind are you still working on this issue?

**Comment by devWonderkind** [comment]
I've completed it and my PR also got merged.
close it!
