### ISSUE TITLE
[ADD] Kotlin in subcategory of Language

### ISSUE THREAD

**Issue by Souvik-223** [rupali-codes/LinksHub#1053]
### Category Name

Language

### Subcategory Name

Kotlin

### Additional Context

Hey @CBID2 I want to Add Kotlin language as subcategory of Language category and add link in this subcategory. Please assign this issue to me under GSSoC'23 label.

example:- 

![Kotlin](https://github.com/rupali-codes/LinksHub/assets/107457931/185c8d45-7009-4e99-92b3-b79102d0321d)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Souvik-223** [comment]
@CBID2 please assign this issue to me

**Comment by CBID2** [comment]
> @CBID2 please assign this issue to me 

Done

**Comment by Souvik-223** [comment]
@CBID2 I have created a pull request regarding this. Kindly, review the changes.

**Comment by CBID2** [comment]
> @CBID2 I have created a pull request regarding this. Kindly, review the changes.
I made my review.
