### ISSUE TITLE
[Feature] Docs workflow for main codebase code and conditions 

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1056]
## Related Issue
#966 

Hi @ujjawaltyagii 
Since I am planning to add another workflow, I would like to provide it to you first, considering that I have already submitted a pull request for this issue. Please let me know if you plan to add this workflow, as it will undoubtedly be great for the project.

This workflow will be an automated PR labeling system that will greatly simplify the pull request management process. By analyzing the titles of PRs, it will automatically assign appropriate labels based on predefined criteria such as status, goals, and aspects. It will use `regexs`, `events`, `targets`. Since I haven't come across this workflow before, it will be a significant contribution, and I encourage you to discuss it further with @CBID2 and @rupali-codes.

To implement this workflow, you will need to use two separate workflows: one for the main code and another for defining the conditions or values of different criteria. By dividing the workflow into these two parts, it allows for better organization and maintainability of the codebase. 

Originally posted by @Anmol-Baranwal in his https://github.com/rupali-codes/LinksHub/pull/1023#issuecomment-1587853563_

## Disclaimer 
This part of the docs workflow only needs **1** pull request.

### Checklist

- [ ] I have checked the existing issues
- [ ] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@CBID2 yeah, that would be so helpful

**Comment by CBID2** [comment]
> @CBID2 yeah, that would be so helpful

Great! :) @Anmol-Baranwal, the floor is yours

**Comment by Anmol-Baranwal** [comment]
> > @CBID2 yeah, that would be so helpful
> 
> Great! :) @Anmol-Baranwal, the floor is yours

Is @ujjawaltyagii not eager to work on this?

**Comment by CBID2** [comment]
> > > @CBID2 yeah, that would be so helpful
> > 
> > Great! :) @Anmol-Baranwal, the floor is yours
> 
> Is @ujjawaltyagii not eager to work on this? 

He seems busy at the moment

**Comment by Anmol-Baranwal** [comment]
> > > > @CBID2 yeah, that would be so helpful
> > > 
> > > 
> > > Great! :) @Anmol-Baranwal, the floor is yours
> > 
> > 
> > Is @ujjawaltyagii not eager to work on this?
> 
> He seems busy at the moment

Sure, I will complete this after completing all of the PRs.

**Comment by CBID2** [comment]
> > > > > @CBID2 yeah, that would be so helpful
> > > > 
> > > > 
> > > > Great! :) @Anmol-Baranwal, the floor is yours
> > > 
> > > 
> > > Is @ujjawaltyagii not eager to work on this?
> > 
> > 
> > He seems busy at the moment
> 
> Sure, I will complete this after completing all of the PRs.

**Comment by CBID2** [comment]
> > > > > > @CBID2 yeah, that would be so helpful
> > > > > 
> > > > > 
> > > > > Great! :) @Anmol-Baranwal, the floor is yours
> > > > 
> > > > 
> > > > Is @ujjawaltyagii not eager to work on this?
> > > 
> > > 
> > > He seems busy at the moment
> > 
> > 
> > Sure, I will complete this after completing all of the PRs.

Ok

**Comment by CBID2** [comment]
@Anmol-Baranwal, is this issue solved?

**Comment by rupali-codes** [comment]
Any updates guys?

**Comment by Anmol-Baranwal** [comment]
> Any updates guys?

Sorry, I was busy so I was not aware of the message of @CBID2.
 
 I will inform you tomorrow about the things that I would need to complete this, and suggestions.

**Comment by rupali-codes** [comment]
> > Any updates guys?
> 
> Sorry, I was busy so I was not aware of the message of @CBID2.
> 
> I will inform you tomorrow about the things that I would need to complete this, and suggestions.

okay, no probs

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I am ready to work on this. I will make a PR in 2 days after properly analyzing all the factors.
