### ISSUE TITLE
[Feature] Docs workflow for main code

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1057]
## Related Issue(s)
#966 and #1056

Hi @ujjawaltyagii 
Since I am planning to add another workflow, I would like to provide it to you first, considering that I have already submitted a pull request for this issue. Please let me know if you plan to add this workflow, as it will undoubtedly be great for the project.

This workflow will be an automated PR labeling system that will greatly simplify the pull request management process. By analyzing the titles of PRs, it will automatically assign appropriate labels based on predefined criteria such as status, goals, and aspects. It will use `regexs`, `events`, `targets`. Since I haven't come across this workflow before, it will be a significant contribution, and I encourage you to discuss it further with @CBID2 and @rupali-codes.

To implement this workflow, you will need to use two separate workflows: one for the main code and another for defining the conditions or values of different criteria. By dividing the workflow into these two parts, it allows for better organization and maintainability of the codebase. 

_Originally posted by @Anmol-Baranwal in https://github.com/rupali-codes/LinksHub/pull/1023#issuecomment-1587853563_

### Checklist

- [ ] I have checked the existing issues
- [ ] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Why are there two duplicate issues: `#1056` and `#1057`? 

Please close one of them, as both workflows will be included in a single PR to ensure complete functionality.

**Comment by CBID2** [comment]
> @CBID2 
> 
> Why are there two duplicate issues: `#1056` and `#1057`? 
> 
> 
> 
> Please close one of them, as both workflows will be included in a single PR to ensure complete functionality.

That was to divide up the work @Anmol-Baranwal like you suggested.

**Comment by Anmol-Baranwal** [comment]
> > @CBID2 
> > 
> > Why are there two duplicate issues: `#1056` and `#1057`? 
> > 
> > 
> > 
> > Please close one of them, as both workflows will be included in a single PR to ensure complete functionality.
> 
> It’s to point out the different flows  @Anmol-Baranwal. Just like you suggested. Maybe I could put a disclaimer to address both with one PR?

Yeah, that would be better.
