### ISSUE TITLE
[BUG] <No way to route back to the Menu after searching for a query in the search panel>

### ISSUE THREAD

**Issue by xmayukx** [rupali-codes/LinksHub#1061]
### Description

The problem occurs when I'm **searching** for a **Keyword** in the search panel, if the **keyword matches** with the index it renders the corresponding sub-menu for it by **clearing the entire Menu** which leads to a **bad user experience** hence any user using it will not be able to explore other sub-groups as there is **no option to route back to the Menu** other than **refreshing the entire website** or by searching keyword which is quite tedious.

@rupali-codes @CBID2 
I want to work on this issue.
Could you please assign me this issue under GSSoC '23

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/89103181/4ba233c6-59ad-4699-b2d7-61ac45fbf1c3

### What browser are you seeing the problem on?

Firefox, Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @xmayukx

**Comment by Ameya02** [comment]
Hi @CBID2 @xmayukx  the issue already exist #1042

**Comment by CBID2** [comment]
> Hi @CBID2 @xmayukx  the issue already exist #1042

Ooh thanks for pointing this out @Ameya02! :) @xmayukx, I'm going to close this issue since it's already being addressed. I highly recommend reviewing Ameya's pull request once they create it. It's a great way to develop your collaboration and written communication skills. 😊

**Comment by xmayukx** [comment]
@CBID2 Got it! And I think the PR made by @Ameya02 looks good to me.
