### ISSUE TITLE
fix: naming of subcategories

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1063]
### What would you like to share or ask?

> wrong name with subcategory name as testing
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/cad04d37-1442-4fae-b9bf-c73a82f4aeab)

> Instead of using the abbreviation "ML," it would be better to write it as "machine learning" to ensure clarity for those who may not be familiar with the term. It can seem strange when the title in the popup of the modal description (yet to merge)
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/31a446aa-b566-43e1-b31b-bb4a544dfcc1)

> Inconsistency of Data Structure with dsa, same reason as above
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a6787469-5167-47a2-b3aa-2c564cc2dbd4)

I will fix the naming of all the subcategories to maintain consistency

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
I will complete this task once #1062 and #1072 have been completed, as changing the name in multiple places is necessary to avoid any bugs.

**Comment by CBID2** [comment]
Ok

**Comment by rupali-codes** [comment]
> I will complete this task once #1062 and #1072 have been completed, as changing the name in multiple places is necessary to avoid any bugs.

Sure, thanks
