### ISSUE TITLE
[ADD] <Add C programming video resources>

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1066]
### Category Name

LANGUAGES

### Subcategory Name

C programming

### Additional Context

I would like to add a valuable resource for learning C programming to the LinkHub section of the website. The resource is a YouTube video tutorial titled "C Programming Tutorial for Beginners" by freeCodeCamp, available at the following link: [C Programming Tutorial for Beginners](https://www.youtube.com/watch?v=KJgsSFOSQv0).

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey there @Nishitbaria! :) Just to confirm, are you in GSSOC’23?

**Comment by Nishitbaria** [comment]
Yes I am from GSSOC23, I want to add new Resource in C Programming

**Comment by CBID2** [comment]
> **@CBID2**  Yes I am from GSSOC23, I want to add new Resource in C Programming 

Done
