### ISSUE TITLE
[Feature] Footer Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [rupali-codes/LinksHub#1067]
### Description

There is no proper Footer Section on the website. As we know how important is Footer Section for an website. So there should be a Footer Section that will contain Social media links, Quick links, and many other things.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by parthpathakpp1** [comment]
Could you please assign this issue to me under GSSOC'23.

**Comment by CBID2** [comment]
Hi @parthpathakpp1! :) I just checked the code and it seems that we do have [a footer](https://github.com/rupali-codes/LinksHub/blob/main/components/Footer/Footer.tsx). We placed the social links on top to make them more visible to viewers. So, I don't think a traditional footer structure would help. What do you think @ujjawaltyagii? @rupali-codes?

**Comment by rupali-codes** [comment]
> Hi @parthpathakpp1! :) I just checked the code and it seems that we do have [a footer](https://github.com/rupali-codes/LinksHub/blob/main/components/Footer/Footer.tsx). We placed the social links on top to make them more visible to viewers. So, I don't think a traditional footer structure would help. What do you think @ujjawaltyagii? @rupali-codes?

Yes i agree, as we don't have any special links or info to add there, we don't need it i guess, the icons looks more accessible where they are placed currently :)

**Comment by CBID2** [comment]
> > Hi @parthpathakpp1! :) I just checked the code and it seems that we do have [a footer](https://github.com/rupali-codes/LinksHub/blob/main/components/Footer/Footer.tsx). We placed the social links on top to make them more visible to viewers. So, I don't think a traditional footer structure would help. What do you think @ujjawaltyagii? @rupali-codes?
> 
> 
> 
> Yes i agree, as we don't have any special links or info to add there, we don't need it i guess, the icons looks more accessible where they are placed currently :)

On that note, I'm closing this issue.
