### ISSUE TITLE
[Add] Add New Links for React Router 6

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1069]
### Site URL

https://youtu.be/nDGA3km5He4

### Description of the above provided site

We will add a new category to the LinkHub section for React Router 6 under React . This category will provide valuable resources , to help users learn and navigate the latest version of React Router effectively. Since this React Router Version 6 is introduced recently and help to get  introduced in React Router 6.

### Category

Frontend

### Sub Category

ReactJs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Please work on one issue at a time.

**Comment by Nishitbaria** [comment]
Hi @CBID2,

I wanted to thank you, Christine, for your assistance. However, I noticed that we have already submitted a pull issue for the previous matter. Could you kindly merge that so that we can continue working on it further?

**Comment by CBID2** [comment]
> Hi @CBID2,
> 
> 
> 
> I wanted to thank you, Christine, for your assistance. However, I noticed that we have already submitted a pull issue for the previous matter. Could you kindly merge that so that we can continue working on it further?

You're welcome @Nishitbaria. PRs require two reviews based on the automated tests.

**Comment by rupali-codes** [comment]
@Nishitbaria you still want to work on this issue??

**Comment by Nishitbaria** [comment]
Yes Working on it . I will Update in some time @rupali-codes

**Comment by rupali-codes** [comment]
> Yes Working on it . I will Update in some time @rupali-codes

sure, thanks

**Comment by Nishitbaria** [comment]
Hey @rupali-codes,

Just wanted to let you know that my previous pull request is still pending review. Once it's merged, I'll make the necessary updates for this one too.

Thanks!
@Nishitbaria

**Comment by rupali-codes** [comment]
> Hey @rupali-codes,
> 
> Just wanted to let you know that my previous pull request is still pending review. Once it's merged, I'll make the necessary updates for this one too.
> 
> Thanks! @Nishitbaria

It was merged i guess, you can start working on this
