### ISSUE TITLE
[Add] Add Official Docs for Django

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1070]
### Site URL

https://docs.djangoproject.com/en/4.2/

### Description of the above provided site

I would like to add a valuable resource for Learning Django as its famous framework for Python to the LinkHub section of the Official Documentation. The Documentation is a Official Documentation of Django

### Category

Resources

### Sub Category

Official Docs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Nishitbaria** [comment]
@rupali-codes  Can i know why you unassigned this issue ,I was working on it?

**Comment by rupali-codes** [comment]
> @rupali-codes Can i know why you unassigned this issue ,I was going to create my pull request on it?

you have been assigned another issue

**Comment by Nishitbaria** [comment]
Hey @rupali-codes  Its Already completed please assign to me this issue

**Comment by CBID2** [comment]
> Hey @rupali-codes Its Already completed please assign to me this issue

Hi @Nishitbaria. I can't find your name in the PR tab. Can you link the PR you made here as evidence, please?

**Comment by Nishitbaria** [comment]
@CBID2  : https://github.com/rupali-codes/LinksHub/pull/1068

**Comment by CBID2** [comment]
> @CBID2  : https://github.com/rupali-codes/LinksHub/pull/1068

You've been assigned @Nishitbaria
