### ISSUE TITLE
[DOCS] Update contributing guidelines

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1073]
### Issue Description

- Once #1062 is merged, we need to ensure the following:
  - Ask anyone adding a new subcategory to also include a description for it in `CategoryDescriptions.ts`
  - Update the appropriate subcategory name in the `types` file.

> I'm noting these points down to ensure I don't forget, and I will complete this task later.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Good idea @Anmol-Baranwal
