### ISSUE TITLE
[Feature] add theme styling to footer in light mode

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1074]
### Description

We can highlight the links with a theme color (purple) to make them accessible and distinct in light mode.

### Screenshots

> Dark mode
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/2f0e2501-e03a-4ef5-b799-110db0e496ca)

> Light mode
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5862014f-2826-4d50-8e1a-ce063ee9eb32)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by KHADIJA-09** [comment]
Hello ...please assign me this task.

**Comment by CBID2** [comment]
> Hello ...please assign me this task.

Sorry @KHADIJA-09. It was assigned to @Anmol-Baranwal. Feel free to review their pull request once they create it. Check out the Code Review article in the  Remarks section of the [Contributing Guide](https://github.com/rupali-codes/linkshub/blob/main/CONTRIBUTING.md#remarks-).
