### ISSUE TITLE
[Add hover effect on Fork button] <I want to add hover effect on fork button>

### ISSUE THREAD

**Issue by akshaysoni10** [rupali-codes/LinksHub#1075]
### Description

I want to add hover effect on Fork button. Please assign me task under GSSOC'23.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by KHADIJA-09** [comment]
I want to solve this problem please assign me this task.

**Comment by CBID2** [comment]
> I want to solve this problem please assign me this task.

@KHADIJA-09, @akshaysoni10 wants to work on this issue. Let's see if they still want to before we move any further. 😄

**Comment by rupali-codes** [comment]
I'm closing this issue as it was already resolved in #1029
