### ISSUE TITLE
[BUG] Update site title when clicked on Side navbar elements

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#108]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, site title is being replaced with the URL when clicked on sidebar element. It would be nice if could be changed to Site name plus the selected element, for example `LinksHub - Images`.

### Screenshots

Current:
![image](https://user-images.githubusercontent.com/78981177/215253207-104b21f3-fb7a-4caa-9ea8-fa43897e1396.png)

To be changed:
![image](https://user-images.githubusercontent.com/78981177/215253318-a6ee19c4-add2-4012-8d8c-0fecef0bbeaa.png)

**Comment by ConradQQ** [comment]
I would like to handle this issue if it's not already assigned

**Comment by rupali-codes** [comment]
@ConradQQ thank you for taking interest, assigning to you!

**Comment by ConradQQ** [comment]
Issue fixed. Opened a pull request
