### ISSUE TITLE
[Feature] GitHub Action to catch spelling errors

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1080]
## Problem 
Throughout my experience reviewing the sources contributors want to add to LinksHub, there has been something that's been recurring: misspellings in the descriptions section. 
## Possible Solution
Easier one: Creating a workflow based on this [GitHub action](https://github.com/marketplace/actions/check-spelling) <--- This is what I'm leaning towards. 
Possibly hard: Adding this [spell checker](https://www.npmjs.com/package/spelling).

## Additional information
I'm willing to collaborate with any contributor on this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@rupali-codes why repoend this did we need to complete anything esle?

**Comment by CBID2** [comment]
> @rupali-codes why repoend this did we need to complete anything esle?

An issue occurred

**Comment by k-deepak04** [comment]
> > @rupali-codes why repoend this did we need to complete anything esle?
> 
> An issue occurred

oh.... :(

**Comment by CBID2** [comment]
> > > @rupali-codes why repoend this did we need to complete anything esle?
> 
> > 
> 
> > An issue occurred
> 
> 
> 
> oh.... :(

For some odd reason,[this happened](https://github.com/rupali-codes/LinksHub/actions/runs/5457197100) when I worked on a one of the GSSOC PR.

**Comment by rupali-codes** [comment]
> > > > @rupali-codes why repoend this did we need to complete anything esle?
> > 
> > 
> > > 
> > 
> > 
> > > An issue occurred
> > 
> > 
> > oh.... :(
> 
> For some odd reason,[this happened](https://github.com/rupali-codes/LinksHub/actions/runs/5457197100) when I worked on a one of the GSSOC PR. Apparently, I have to this step: "
> 
> If you're seeing this message and your PR is from a branch that doesn't have check-spelling, please merge to your PR's base branch to get the version configured for your repository", but I'm not sure how to do it though

it wasn't configured correctly ig, @CBID2 can you a new branch in the main repo and push the code in there? then we can test with sample PRs of issues i guess

**Comment by CBID2** [comment]
> > > > > @rupali-codes why repoend this did we need to complete anything esle?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > An issue occurred
> 
> > > 
> 
> > > 
> 
> > > oh.... :(
> 
> > 
> 
> > For some odd reason,[this happened](https://github.com/rupali-codes/LinksHub/actions/runs/5457197100) when I worked on a one of the GSSOC PR. Apparently, I have to this step: "
> 
> > 
> 
> > If you're seeing this message and your PR is from a branch that doesn't have check-spelling, please merge to your PR's base branch to get the version configured for your repository", but I'm not sure how to do it though
> 
> 
> 
> it wasn't configured correctly ig, @CBID2 can you a new branch in the main repo and push the code in there? then we can test with sample PRs of issues i guess

Sure I can try

**Comment by CBID2** [comment]
@Anmol-Baranwal, can you help me with GH action?

**Comment by k-deepak04** [comment]
> > @Anmol-Baranwal, can you help me with GH action?
> 
> I have arrived for a job fair. So, it might take some time. I can definitely help you till 6th.

bhaiya jo bhi loge 2 lena 😂
ek job mere liye bhi :)

**Comment by CBID2** [comment]
> > @Anmol-Baranwal, can you help me with GH action? 
> 
> I have arrived for a job fair. So, it might take some time. I can definitely help you till 6th.

Ok then :)

**Comment by Anmol-Baranwal** [comment]
> > bhaiya jo bhi loge 2 lena 😂
> > ek job mere liye bhi :)
> 
> Lol उन्हें ज्यादा मत छेड़ो. उनके पास कमाने के लिए पैसा है :)

😅 Lol, you are typing in Hindi

**Comment by k-deepak04** [comment]
> > bhaiya jo bhi loge 2 lena 😂
> > ek job mere liye bhi :)
> 
> Lol उन्हें ज्यादा मत छेड़ो. उनके पास कमाने के लिए पैसा है :)

   😂😂😂😂

**Comment by CBID2** [comment]
> > > bhaiya jo bhi loge 2 lena 😂
> 
> > > ek job mere liye bhi :)
> 
> > 
> 
> > Lol उन्हें ज्यादा मत छेड़ो. उनके पास कमाने के लिए पैसा है :)
> 
> 
> 
>    😂😂😂😂

Lol, I had to use Google Translate in order to respond 😂

**Comment by k-deepak04** [comment]
> > > > bhaiya jo bhi loge 2 lena 😂
> > 
> > 
> > > > ek job mere liye bhi :)
> > 
> > 
> > > 
> > 
> > 
> > > Lol उन्हें ज्यादा मत छेड़ो. उनके पास कमाने के लिए पैसा है :)
> > 
> > 
> > 😂😂😂😂
> 
> Lol, I had to use Google Translate in order to respond 😂

A few weeks more or maybe till next gssoc we will teach you hindi :)  😂
