### ISSUE TITLE
Add some more languages

### ISSUE THREAD

**Issue by vedikapatidar** [rupali-codes/LinksHub#1082]
### What would you like to share or ask?

want to add some more programming languages in languages section.....
so , Assign me this issue as soon as possible

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@vedikapatidar which languages do you want to add specifically?

**Comment by rupali-codes** [comment]
@vedikapatidar any updates please?
