### ISSUE TITLE
[DOCS]  Update README.md

### ISSUE THREAD

**Issue by IfeoluwaAroboto** [rupali-codes/LinksHub#1083]
### Issue Description

There are a few grammatical and spelling errors. 
1. In the sentence "Before getting into it, it make you sure you have pnpm installed," it should be "make sure" instead of "it make sure."
2. In the sentence "Push your changes into your branch," it should be "Push your changes to your branch."

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
sounds good, you may start working it
