### ISSUE TITLE
[Feature] Add some more icon generator

### ISSUE THREAD

**Issue by Parmesh119** [rupali-codes/LinksHub#1085]
### Description

Add some more icon generator for free.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi @Parmesh119, please don't start working on any issue until you get assigned to it
