### ISSUE TITLE
[BUG] Not enough space for footer in mobile view

### ISSUE THREAD

**Issue by Mani-mk-mk** [rupali-codes/LinksHub#1088]
### Description

In the mobile mode of the application, the footer does not gets enough space and it goes out of the main container which makes it look like this
![image](https://github.com/rupali-codes/LinksHub/assets/72310576/47e447f0-1cdd-4a7b-8dc9-94302da7e9a7)

### What browser are you seeing the problem on?

Firefox, Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
It does look pretty crowded. @rupali-codes and @ujjawaltyagii, I think a change to the footer's size would be helpful. What do you think?

**Comment by ujjawaltyagii** [comment]
@CBID2 yep ! Ig we should go for new footer design.

**Comment by rupali-codes** [comment]
> @CBID2 yep ! Ig we should go for new footer design.

Someone is already working on footer i guess

**Comment by CBID2** [comment]
> > @CBID2 yep ! Ig we should go for new footer design.
> 
> 
> 
> Someone is already working on footer i guess

I think it's @Anmol-Baranwal

**Comment by rupali-codes** [comment]
@Mani-mk-mk you can start working on this issue :) and i guess you would need to reduce font-size

**Comment by Anmol-Baranwal** [comment]
> > > @CBID2 yep ! Ig we should go for new footer design.
> > 
> > 
> > Someone is already working on footer i guess
> 
> I think it's @Anmol-Baranwal

I was not working on this.

**Comment by CBID2** [comment]
> > > > @CBID2 yep ! Ig we should go for new footer design.
> 
> > > 
> 
> > > 
> 
> > > Someone is already working on footer i guess
> 
> > 
> 
> > I think it's @Anmol-Baranwal
> 
> 
> 
> I was not working on this.

Thanks for clarifying
