### ISSUE TITLE
[Add] | FontAwesome Website Link

### ISSUE THREAD

**Issue by YashkShrivas4491** [rupali-codes/LinksHub#1089]
### Site URL

https://fontawesome.com/

### Description of the above provided site

Font Awesome is the Internet's icon library and toolkit, used by millions of designers, developers, and content creators.

![image](https://github.com/rupali-codes/LinksHub/assets/87111197/5a087ac3-646c-4dff-96e0-e6f2e492c80a)

### Category

Frontend

### Sub Category

"fonts"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@YashkShrivas4491 it has been already added.
