### ISSUE TITLE
[Feature] Navbar's Buttons Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [rupali-codes/LinksHub#1097]
### Description

The current design of the buttons is nice but it can be improved by making some design adjustments. Through some styling changes, I can make it look even better which will ultimately improve the overall website design.

### Screenshots

**Current Design**
![linkhub (2)](https://github.com/rupali-codes/LinksHub/assets/115794049/85e82f8e-e28c-42c9-864a-da2471edc8bb)

**Expected Updated Design**
![linkhub (1)](https://github.com/rupali-codes/LinksHub/assets/115794049/d93f0024-cb7b-49d6-abed-cf5c6bd48e99)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@CBID2 & @ujjawaltyagii what do you think about this?

**Comment by rupali-codes** [comment]
> > @CBID2 & @ujjawaltyagii what do you think about this?
> 
> I don't really notice the changes @rupali-codes

See the corners XD

**Comment by CBID2** [comment]
> > > @CBID2 & @ujjawaltyagii what do you think about this?
> 
> > 
> 
> > I don't really notice the changes @rupali-codes
> 
> 
> 
> See the corners XD

Still don't see it

**Comment by ujjawaltyagii** [comment]
> > > > @CBID2 & @ujjawaltyagii what do you think about this?
> > 
> > 
> > > 
> > 
> > 
> > > I don't really notice the changes @rupali-codes
> > 
> > 
> > See the corners XD
> 
> Still don't see it

Corners of `Fork` and `Star` buttons are curved (bro literally used border-radius XD )

**Comment by CBID2** [comment]
> > > > > @CBID2 & @ujjawaltyagii what do you think about this?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > I don't really notice the changes @rupali-codes
> > > 
> > > 
> > > See the corners XD
> > 
> > 
> > Still don't see it
> 
> Corners of `Fork` and `Star` buttons are curved (bro literally used border-radius XD )

Ohh now I see it @ujjawaltyagii lol! 😆 I don't necessarily see a need to change the buttons. They look alright. What about you @rupali-codes?

**Comment by ujjawaltyagii** [comment]
i think they look fine as of now, no need to change the design of buttons !

**Comment by rupali-codes** [comment]
> i think they look fine as of now, no need to change the design of buttons !

cool, then i'm closing this issue as its not required. @iamRabia-N please feel free to open any new issue. We appreciate your time and willingness to contribute in LinksHub.
