### ISSUE TITLE
[Add]  CSS Scan website to the LinksHub

### ISSUE THREAD

**Issue by Prajwal0225** [rupali-codes/LinksHub#1099]
### Site URL

https://getcssscan.com/css-box-shadow-examples

### Description of the above provided site

I would like to suggest adding the getcssscan website to the Animation section of the front end of LinksHub. This website provides a collection of 93 box shadow examples along with their corresponding source code. Including this resource in the LinksHub would greatly benefit developers who are looking for inspiration or examples for creating box shadows in CSS.

**Website Screenshot :**
![box shadow](https://github.com/rupali-codes/LinksHub/assets/103810119/b6197d3d-662d-468e-adf9-bb8356e11ef8)

### Category

Frontend

### Sub Category

animations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @Prajwal0225. Just to confirm, you’re in GSSOC’25?

**Comment by rupali-codes** [comment]
@Prajwal0225 Thanks for contributing, you can start working on the issue :)
