### ISSUE TITLE
[Add] <Adding MYSQL docs>

### ISSUE THREAD

**Issue by saikiranreddy201** [rupali-codes/LinksHub#1103]
### Site URL

https://docs.oracle.com/en-us/iaas/mysql-database/doc/getting-started.html

### Description of the above provided site

In the Backend/Database section, I have observed that there are no docs for the famous MySQL database, as it is widely used by most of the developers I believe that adding MySQL docs would be a perfect addition for this page.

### Category

Backend

### Sub Category

Database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@saikiranreddy201 thanks you can start working on this, assigning to you!
