### ISSUE TITLE
[Add] Add youtube playlist link for android development 

### ISSUE THREAD

**Issue by madhurafulkar** [rupali-codes/LinksHub#1104]
### Site URL

https://www.youtube.com/@CodeWithHarry/playlists

### Description of the above provided site

This android tutorials in Hindi explains how android applications are built using Android studio. In this Android Java Course one can learn how android applications are built using programming in java and XML. This android course will teach you everything you need to learn to create your first Android Application!

### Category

Youtube

### Sub Category

Youtube

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@madhurafulkar Thanks for contributing, you can start working in the issue :)
