### ISSUE TITLE
[Add] Python tutorial site 

### ISSUE THREAD

**Issue by Pro-18** [rupali-codes/LinksHub#1106]
### Site URL

https://www.w3schools.com/python/

### Description of the above provided site

W3Schools' Python Tutorial: Learn Python programming from scratch with W3Schools' comprehensive online tutorial. Gain practical knowledge and hands-on experience in Python's syntax, data structures, control flow, and more through interactive examples and exercises.
![iss8](https://github.com/rupali-codes/LinksHub/assets/92087279/4dd6238b-b3e8-4dcd-9946-24b30556d5e0)

### Category

Languages

### Sub Category

Python

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Pro-18 thanks for contributing, you can start working on the issue
