### ISSUE TITLE
[Add] the new resources from YouTube for react.js

### ISSUE THREAD

**Issue by Parmesh119** [rupali-codes/LinksHub#1107]
### Site URL

https://youtu.be/4UZrsTqkcW4

### Description of the above provided site

This is the FreeCodeCamp react course on YouTube. This is the most viewed and also I learn the react from it.
In this video, all the basic topics of react has been covered and also helpful to the beginner to get started in the world of react.

### Category

Frontend

### Sub Category

React.js

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Parmesh119 Are you still working on the issue?

**Comment by k-deepak04** [comment]
@Parmesh119 closing this as no responses received , if you still want to work and deliver the things quick i will reopen it again, just tag me :)
