### ISSUE TITLE
[Add] Font Resource

### ISSUE THREAD

**Issue by Sriparno08** [rupali-codes/LinksHub#1108]
### Site URL

https://fontawesome.com/

### Description of the above provided site

Font Awesome is the Internet's icon library and toolkit, used by millions of designers, developers, and content creators.

### Category

Frontend

### Sub Category

fonts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Sriparno08! :) Just to confirm, are you participating in GSSOC'23?

**Comment by rupali-codes** [comment]
@Sriparno08 thanks for your patience, you can start working on the issue

**Comment by Sriparno08** [comment]
Thanks, @rupali-codes 👍

**Comment by Sriparno08** [comment]
Hey @rupali-codes, since this issue is closed, can I now get assigned in #1140?
