### ISSUE TITLE
[BUG] Extra Spacing near home description in mobile view

### ISSUE THREAD

**Issue by Ameya02** [rupali-codes/LinksHub#1109]
### Description

There is extra spacing on the 1st line of the website description on the home page when opening on mobile device

### Screenshots

![WhatsApp Image 2023-06-21 at 16 15 12](https://github.com/rupali-codes/LinksHub/assets/65841021/d4f0ecb8-fe3b-4c45-bb74-7c7b97135bd6)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
I guess it looks fine, @CBID2 & @ujjawaltyagii what you guys think about this?
