### ISSUE TITLE
[BUG] add full with to components in mobile view

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#111]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

I just noticed, the deign is breaking for `some` of the components in mobile view, which is not looking good at all. 

### specific requirements
It should take full width of the screen.

### Screenshots

current: 
![image](https://user-images.githubusercontent.com/78981177/215266388-18ab4931-f56b-4d1c-a330-21c2650f3ae4.png)

it should be like: 
![image](https://user-images.githubusercontent.com/78981177/215266456-ae4904ff-b282-4e6e-8ad9-56ae387095ed.png)

**Comment by ConradQQ** [comment]
I'd be happy to tackle this issue if it's not already assigned.

**Comment by rupali-codes** [comment]
thank you for taking interest in, yes you can start working :)

**Comment by ConradQQ** [comment]
Issue is fixed & can be closed.
