### ISSUE TITLE
[Add] new links under UI Generator 

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [rupali-codes/LinksHub#1110]
### Site URL

https://www.cssfilters.co/

### Description of the above provided site

It is a site which gennerates image filter css for webpages

### Category

Frontend

### Sub Category

UI Generator

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @Swapnil-Singh-99! :) Just to confirm, you're in GSSOC right?

**Comment by rupali-codes** [comment]
> Hey @Swapnil-Singh-99! :) Just to confirm, you're in GSSOC right?

How could they reply in locked convo. 😅😅

**Comment by rupali-codes** [comment]
@Swapnil-Singh-99 thanks for your patience, you can start working on the issue :)
