### ISSUE TITLE
[Add] CSS Pattern Generator

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [rupali-codes/LinksHub#1111]
### Site URL

https://patternizer.com/

### Description of the above provided site

This website will generate CSS code for Patterns

### Category

Frontend

### Sub Category

UI Generators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Swapnil-Singh-99 thanks, please work on one issue at a time, we will assign you this issue once you're done with your assigned issues :)

**Comment by Killer2OP** [comment]
@rupali-codes Can you assign me this Issue

**Comment by Kushagra102** [comment]
@rupali-codes I am interested in working on this issue.

**Comment by CBID2** [comment]
> @rupali-codes Can you assign me this Issue

Hi @Killer2OP! :) Are you currently working on any other issues?

**Comment by Killer2OP** [comment]
> > @rupali-codes Can you assign me this Issue
> 
> Hi @Killer2OP! :) Are you currently working on any other issues?

Nope

**Comment by CBID2** [comment]
> > > @rupali-codes Can you assign me this Issue
> > 
> > 
> > Hi @Killer2OP! :) Are you currently working on any other issues?
> 
> Nope

Assigned
