### ISSUE TITLE
[Add] Crazy color palletes on Color Hunt

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [rupali-codes/LinksHub#1112]
### Site URL

https://colorhunt.co/

### Description of the above provided site

This site generates crazy color palletes for you to use

### Category

Frontend

### Sub Category

Colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@Swapnil-Singh-99 any updates?
