### ISSUE TITLE
[Add] youtube playlist for blockchain & Web 3

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [rupali-codes/LinksHub#1113]
### Site URL

https://www.youtube.com/playlist?list=PLsyeobzWxl7oY6tZmnZ5S7yTDxyu4zDW-

### Description of the above provided site

This is course by Telusko for Web3 and Blockchain

### Category

Youtube

### Sub Category

Web3 & Metaverse

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@Swapnil-Singh-99 any updates?

**Comment by Swapnil-Singh-99** [comment]
> @Swapnil-Singh-99 any updates?

Yes I will be pushing the PR today itself
