### ISSUE TITLE
[ADD] SQL in the database section [GSSOC'23]

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [rupali-codes/LinksHub#1117]
### Category Name

backend development

### Subcategory Name

database

### Additional Context

there are so many NoSQL databases in the linkhub but sql is not there. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @shivaniyuvrajyadav! :) just to confirm, you’re in GSSOC right?

**Comment by rupali-codes** [comment]
Hey, this issue is duplicate of #1103. Please consider checking all the issues before creating any new issues. Also, don't forget to checkout our contributing guidelines.
