### ISSUE TITLE
[Add] <OneCompiler in Frontend/Online code editor>

### ISSUE THREAD

**Issue by Jay9874** [rupali-codes/LinksHub#1118]
### Site URL

https://onecompiler.com

### Description of the above provided site

I found it hard to make a frontend disign and implement it (in html, css and js) on the go. I tried many websites and plateforms but the problem I faced was irresponsiveness of the plateform with mobile devices and on few the pasting code was not working. Aside being fully **optimised editor and responsive UI**, it also has compatibility with other frameworks and programming languages like **React, Angular, Python, Java** to name a few. It will be one stop editor for anylanguage, anywhere, anydevice. I would love to hear your thoughts on it.

### Category

Frontend

### Sub Category

Online code editor

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Just to confirm, are you in GSSoC @Jay9874?
