### ISSUE TITLE
[Feature] Add search bar in sidebar

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#112]
### Description

The more elements we are adding in sidebar, the more it's getting difficult to search between components. 

### Specific requirements
1. Add a input bar (search bar) at top of sidebar
2. Background color should be transparent
3. Should start searching as user starts typing
4. Should render search results in sidebar itself

**Comment by ConradQQ** [comment]
Happy to handle this one if it's still available.

**Comment by rupali-codes** [comment]
@ConradQQ thank you for being interested, but you're already working on 2 issues, kindly fix them, and if this issue doesn't get assigned to anybody, then we will definitely assign it to you.

**Comment by ConradQQ** [comment]
For sure! I'd be happy to work on this.

**Comment by rupali-codes** [comment]
@ConradQQ Thank you, assigning to you :)

**Comment by rupali-codes** [comment]
@ConradQQ any updates?

**Comment by fracergu** [comment]
Hi!, I just opened a PR that solves this issue 😀

I have also separated the search functionality into two hooks, one general and one specific, to be able to reuse it in the future if necessary.

https://github.com/rupali-codes/LinksHub/pull/133

**Comment by rupali-codes** [comment]
> Hi!, I just opened a PR that solves this issue 😀
> 
> I have also separated the search functionality into two hooks, one general and one specific, to be able to reuse it in the future if necessary.
> 
> #133

yeah, thank you so much, i have suggested some changes, please fix them :)
