### ISSUE TITLE
[Feature] Resource recommendation 

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1120]
### Description

I wanna a tag on resources about recommendation that this in particular is recommended by _Tam LinksHub_ so that would be easy for users to save their time and efforts for searching good enough resources in the hub.

Overview:

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/80826361-b9e9-485b-b0b7-93a42557ef64)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Glad to see we're on the same page @rupali-codes! :) I thought about this feature too! 😄

**Comment by rupali-codes** [comment]
> Glad to see we're on the same page @rupali-codes! :) I thought about this feature too! 😄

Great, but its gonna take time, as we will have to visit all the links and choose among them, also let put new resource addition on hold,

**Comment by rupali-codes** [comment]
@CBID2 & @ujjawaltyagii also, i have some ideas, we can display something like a list in top-right corner with a heading **Recommended** and put this all links i there along with the description in a dropdown. What do you think

**Comment by CBID2** [comment]
> @CBID2 & @ujjawaltyagii also, i have some ideas, we can display something like a list in top-right corner with a heading **Recommended** and put this all links i there along with the description in a dropdown. What do you think

Ooh I like it but how about Maintainers' recommendations? Like the "Chef of the day" orders that restaurants do @rupali-codes?

**Comment by ujjawaltyagii** [comment]
> @CBID2 & @ujjawaltyagii also, i have some ideas, we can display something like a list in top-right corner with a heading **Recommended** and put this all links i there along with the description in a dropdown. What do you think

Sounds nice to me ! But are we gonna decide which resource to be labelled as recommended or can we automate this on the basis :
1. User's impression or visit on a particular resource will determine which resource to be labelled
2. Should we add some kind of rating or feedback by users ?

**Comment by CBID2** [comment]
> > @CBID2 & @ujjawaltyagii also, i have some ideas, we can display something like a list in top-right corner with a heading **Recommended** and put this all links i there along with the description in a dropdown. What do you think
> 
> 
> 
> Sounds nice to me ! But are we gonna decide which resource to be labelled as recommended or can we automate this on the basis :
> 
> 1. User's impression or visit on a particular resource will determine which resource to be labelled
> 
> 2. Should we add some kind of rating or feedback by users ?

I like the automation and choice 1

**Comment by rupali-codes** [comment]
> > @CBID2 & @ujjawaltyagii also, i have some ideas, we can display something like a list in top-right corner with a heading **Recommended** and put this all links i there along with the description in a dropdown. What do you think
> 
> Sounds nice to me ! But are we gonna decide which resource to be labelled as recommended or can we automate this on the basis :
> 
> 1. User's impression or visit on a particular resource will determine which resource to be labelled
> 2. Should we add some kind of rating or feedback by users ?

we can go for the first one, but its gonna be a bit difficult, so how we going to measure activity of the user? and for the second one, we were actually thinking of that before, but its kinda long process, as we would want to establish database and all, so i thought to stick with this recommendation feature for now.

**Comment by CBID2** [comment]
> > > @CBID2 & @ujjawaltyagii also, i have some ideas, we can display something like a list in top-right corner with a heading **Recommended** and put this all links i there along with the description in a dropdown. What do you think
> 
> > 
> 
> > Sounds nice to me ! But are we gonna decide which resource to be labelled as recommended or can we automate this on the basis :
> 
> > 
> 
> > 1. User's impression or visit on a particular resource will determine which resource to be labelled
> 
> > 2. Should we add some kind of rating or feedback by users ?
> 
> 
> 
> we can go for the first one, but its gonna be a bit difficult, so how we going to measure activity of the user? and for the second one, we were actually thinking of that before, but its kinda long process, as we would want to establish database and all, so i thought to stick with this recommendation feature for now. 
> 
> 
> 
> 

Ooh good point.

**Comment by CBID2** [comment]
> > > @CBID2 & @ujjawaltyagii also, i have some ideas, we can display something like a list in top-right corner with a heading **Recommended** and put this all links i there along with the description in a dropdown. What do you think
> 
> > 
> 
> > Sounds nice to me ! But are we gonna decide which resource to be labelled as recommended or can we automate this on the basis :
> 
> > 
> 
> > 1. User's impression or visit on a particular resource will determine which resource to be labelled
> 
> > 2. Should we add some kind of rating or feedback by users ?
> 
> 
> 
> we can go for the first one, but its gonna be a bit difficult, so how we going to measure activity of the user? and for the second one, we were actually thinking of that before, but its kinda long process, as we would want to establish database and all, so i thought to stick with this recommendation feature for now. 
> 
> 
> 
> 

@Anmol-Baranwal, any suggestions?

**Comment by rupali-codes** [comment]
@Anmol-Baranwal.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal.

I will share my opinion till the end of the day.

**Comment by k-deepak04** [comment]
@rupali-codes shall we work on this i think we can add the design and recommend things, but the problem is that who ever has the codebase access can add recommend tags so shall we proceed with this or try to research more and brainstorm about adding managing by certain given persons.

![image](https://github.com/rupali-codes/LinksHub/assets/96341431/41e7a76b-0a66-45d0-9fcd-96f4701b738a)

we can proceed with same as flipkart like he uses fassured things.

**Comment by rupali-codes** [comment]
> @rupali-codes shall we work on this i think we can add the design and recommend things, but the problem is that who ever has the codebase access can add recommend tags so shall we proceed with this or try to research more and brainstorm about adding managing by certain given persons.
> 
> ![image](https://user-images.githubusercontent.com/96341431/252452843-41e7a76b-0a66-45d0-9fcd-96f4701b738a.png)
> 
> we can proceed with same as flipkart like he uses fassured things.

its gonna be hard ig, i'm thinking of something else, lets have a discussion on discord :)

**Comment by k-deepak04** [comment]
> > @rupali-codes shall we work on this i think we can add the design and recommend things, but the problem is that who ever has the codebase access can add recommend tags so shall we proceed with this or try to research more and brainstorm about adding managing by certain given persons.
> > ![image](https://user-images.githubusercontent.com/96341431/252452843-41e7a76b-0a66-45d0-9fcd-96f4701b738a.png)
> > we can proceed with same as flipkart like he uses fassured things.
> 
> its gonna be hard ig, i'm thinking of something else, lets have a discussion on discord :)

okay :)

**Comment by rupali-codes** [comment]
we can close this issue for now
