### ISSUE TITLE
[BUG] Fix hover effect on the social links to the top left of the screen

### ISSUE THREAD

**Issue by karthiknadar1204** [rupali-codes/LinksHub#1121]
### Description

Currently on hovering the social icons, they turn purple , I was thinking of making it more attractive by making the discord icon on hovering into purple, the github icon to greyish black on hovering and the twitter icon to blue on hovering.
As in we make the colour turn into the color of the original logo, I think it is unique and attractive.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hmm...we're trying to use more accessible colors @karthiknadar1204, so I'm not quite sure using black would help with this. What do you think @rupali-codes? @EmmaDawsonDev?

**Comment by rupali-codes** [comment]
> Hmm...we're trying to use more accessible colors @karthiknadar1204, so I'm not quite sure using black would help with this. What do you think @rupali-codes? @EmmaDawsonDev?

I guess that would look fine, as @karthiknadar1204 wants to add logo's initial color on hover, just like its going to be skyblue for twitter. @CBID2 What do you think?

**Comment by CBID2** [comment]
> > Hmm...we're trying to use more accessible colors @karthiknadar1204, so I'm not quite sure using black would help with this. What do you think @rupali-codes? @EmmaDawsonDev?
> 
> 
> 
> I guess that would look fine, as @karthiknadar1204 wants to add logo's initial color on hover, just like its going to be skyblue for twitter. @CBID2 What do you think? 

Ohh. In that case, go ahead @karthiknadar1204

**Comment by karthiknadar1204** [comment]
Thank you, will get working
