### ISSUE TITLE
[Add] Tailwind Awesome

### ISSUE THREAD

**Issue by kirtiraj22** [rupali-codes/LinksHub#1122]
### Site URL

https://www.tailwindawesome.com/?technology=3

### Description of the above provided site

Tailwind Awesome is a curated list of the best Tailwind templates & UI kits in the internet.

### Category

Frontend

### Sub Category

UI Generators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @kirtiraj22! 😀 Just to confirm, are you in GSSOC?
