### ISSUE TITLE
[Add] | New ONLINE CODE EDITOR 

### ISSUE THREAD

**Issue by YashkShrivas4491** [rupali-codes/LinksHub#1123]
### Site URL

https://www.hackerearth.com/

### Description of the above provided site

It provides Hackathons, Programming Challenges, And Coding Competitions.
![image](https://github.com/rupali-codes/LinksHub/assets/87111197/71d43928-0f8e-4676-b5ca-38821f6399e0)

### Category

Frontend

### Sub Category

"online code editor"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hey @YashkShrivas4491, is it a _code editor_ or blog website?

**Comment by YashkShrivas4491** [comment]
> Hey @YashkShrivas4491, is it a _code editor_ or _blog_ website?

Code editor, where you can solve DSA problem and hiring assessment also conducted by companies similar like leetcode listed in this category

**Comment by navharsh** [comment]
@rupali-codes @YashkShrivas4491 Its more of a problem solving and hiring site assessment rather than an actual code editor like replit or codepen, Better to add it in other / Dev Tools Category.

**Comment by YashkShrivas4491** [comment]
> @rupali-codes @YashkShrivas4491 Its more of a problem solving and hiring site assessment rather than an actual code editor like replit or codepen, Better to add it in other / Dev Tools Category.

Can you tell why there is leetcode website under this category, it should also be under dev tool

**Comment by navharsh** [comment]
> > @rupali-codes @YashkShrivas4491 Its more of a problem solving and hiring site assessment rather than an actual code editor like replit or codepen, Better to add it in other / Dev Tools Category.
> 
> Can you tell why there is leetcode website under this category, it should also be under dev tool

I just saw that after you mentioned, to be honest leet code and hackerrank shouldn't be in this category as well , It would be better if they all these coding competion/ problem solving sites get an altogether different category. What do you think on this @rupali-codes @CBID2

**Comment by YashkShrivas4491** [comment]
> > > @rupali-codes @YashkShrivas4491 Its more of a problem solving and hiring site assessment rather than an actual code editor like replit or codepen, Better to add it in other / Dev Tools Category.
> > 
> > 
> > Can you tell why there is leetcode website under this category, it should also be under dev tool
> 
> I just saw that after you mentioned, to be honest leet code and hackerrank shouldn't be in this category as well , It would be better if they all these coding competion/ problem solving sites get an altogether different category. What do you think on this @rupali-codes @CBID2

Same Brother i think same as you , but when I saw leetcode under category i think let me add hackerEarth that's why👍

**Comment by rupali-codes** [comment]
I see, lets create a new category, what should we name it? @navharsh @YashkShrivas4491 & @CBID2

**Comment by CBID2** [comment]
Online IDEs

**Comment by navharsh** [comment]
> I see, lets create a new category, what should we name it? @navharsh @YashkShrivas4491 & @CBID2

Well, we are talking about separating competitive programming sites like leetcode from online IDEs, so let's name it Competitive programming and learning.

**Comment by rupali-codes** [comment]
> > I see, lets create a new category, what should we name it? @navharsh @YashkShrivas4491 & @CBID2
> 
> Well, we are talking about separating competitive programming sites like leetcode from online IDEs, so let's name it Competitive programming and learning.

ok, lets name it _competitive programming_

**Comment by navharsh** [comment]
Should we make it a new category or a sub category under resources ? @rupali-codes

**Comment by rupali-codes** [comment]
> Should we make it a new category or a sub category under resources ? @rupali-codes

its a huge topic, i guess making category would be better

**Comment by rupali-codes** [comment]
any updates guys?

**Comment by navharsh** [comment]
> any updates guys?

Should I start working on making a new category or @YashkShrivas4491 would you like to do that ?

**Comment by YashkShrivas4491** [comment]
> > any updates guys?
> 
> Should I start working on making a new category or @YashkShrivas4491 would you like to do that ?

Yaa Sure you can start adding new category and let me check is there any other category which have some wrong tools added ok

**Comment by navharsh** [comment]
> > > any updates guys?
> > 
> > 
> > Should I start working on making a new category or @YashkShrivas4491 would you like to do that ?
> 
> Yaa Sure you can start adding new category and let me check is there any other category which have some wrong tools added ok

Great! @rupali-codes should I make a seperate issue on it or continue with this one ?

**Comment by CBID2** [comment]
> > > > any updates guys?
> > > 
> > > 
> > > Should I start working on making a new category or @YashkShrivas4491 would you like to do that ?
> > 
> > 
> > Yaa Sure you can start adding new category and let me check is there any other category which have some wrong tools added ok
> 
> Great! @rupali-codes should I make a seperate issue on it or continue with this one ?

I suggest making a new one @rupali-codes

**Comment by navharsh** [comment]
@CBID2 can you unlock #1250 as I need to discuss some problems I'm facing

**Comment by rupali-codes** [comment]
Since the new issue was created, im closing this one
