### ISSUE TITLE
[Feature] Add Pagination to the Resources Cards

### ISSUE THREAD

**Issue by siddarthdayala** [rupali-codes/LinksHub#1125]
### Description

- Pagination could look better on the resources' cards.
- We could show no more than 9 cards on the page and load the others when user wants to switch it.
- Pagination could make it more professional and user friendly. 

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/97626996/613a0218-d2d0-4ca6-ad89-a851eb4a2532)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@siddarthdayala Sounds cool, you may start working on this. Assigning to you!

**Comment by siddarthdayala** [comment]
Sure !

**Comment by siddarthdayala** [comment]
![image](https://github.com/rupali-codes/LinksHub/assets/97626996/71bf6426-1bb5-4176-8bec-a09523a5bc6c)

![image](https://github.com/rupali-codes/LinksHub/assets/97626996/55aa4458-a0ee-477c-b060-b9777b473ad8)

<br><br>
Hey @rupali-codes could you review this design? 
I'll make a PR once you review this

**Comment by CBID2** [comment]
@chris-nowicki and I are going to work on this
