### ISSUE TITLE
[Add]: 100+ Java projects

### ISSUE THREAD

**Issue by Killer2OP** [rupali-codes/LinksHub#1126]
### Site URL

https://copyassignment.com/100-java-projects-for-beginners-2023/

### Description of the above provided site

Are you looking for interesting Java Projects ideas and 100+ Java Projects for beginners with source code? If yes, the you have come to right place because in this article we will show you best 100+ Java project ideas and topics for beginners with source code.

### Category

Resources

### Sub Category

Project Ideas

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Killer2OP i have recently assigned you an issue, please finish that, then you may start working on this issue :)

**Comment by Killer2OP** [comment]
> @Killer2OP i have recently assigned you an issue, please finish that, then you may start working on this issue :)

ok

**Comment by Killer2OP** [comment]
> @Killer2OP i have recently assigned you an issue, please finish that, then you may start working on this issue :)

Can you assign me this issue now @rupali-codes

**Comment by Kushagra102** [comment]
Hey @rupali-codes I would like to work on this issue.

**Comment by Killer2OP** [comment]
@CBID2 Can you assign me this issue.

**Comment by CBID2** [comment]
> @CBID2 Can you assign me this issue.

Let me review your PR for the other issue you're assigned to first :)

**Comment by Killer2OP** [comment]
> > @CBID2 Can you assign me this issue.
> 
> Let me review your PR for the other issue you're assigned to first :)

Can you assign me this issue now.

**Comment by rupali-codes** [comment]
@CBID2 don't forget to remove _up-for-grabs_ when you assign the issue 😊
