### ISSUE TITLE
[Add]: Game Design 101 Youtube Playlist Link

### ISSUE THREAD

**Issue by Killer2OP** [rupali-codes/LinksHub#1127]
### Site URL

https://youtube.com/playlist?list=PLc38fcMFcV_vToz9Nvc_YQTNH8hkIQ2uC

### Description of the above provided site

Videos that look at the fundamental lessons of game design, applicable to pretty much every type of game.
It is playlist created by Mark Brown a well know game developer

### Category

Youtube

### Sub Category

Game Development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ojasaklechayt** [comment]
Can I work on this ?

**Comment by rupali-codes** [comment]
> @rupali-codes Can I work on this ?

Please don't start working before you get assigned

**Comment by rupali-codes** [comment]
@ojasaklechayt are you a gssoc'23 participant?

**Comment by ojasaklechayt** [comment]
> @ojasaklechayt are you a gssoc'23 participant? 

Yes ma'am
