### ISSUE TITLE
[Add] <I would like to add a youtube channel to learn web development>

### ISSUE THREAD

**Issue by iqrafirdose** [rupali-codes/LinksHub#1128]
### Site URL

https://www.youtube.com/@ApoorvGoyalMain

### Description of the above provided site

This youtube will help us to learn web development in a most interesting and understandable way.

### Category

Youtube

### Sub Category

Youtube

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey nice to see you here @iqrafirdose! :) Are you participating in GSSOC?

**Comment by rupali-codes** [comment]
@iqrafirdose you may start working on the issue, just let us know if you're participating in gssoc'23 so we can add labels :)

**Comment by iqrafirdose** [comment]
> Hey nice to see you here @iqrafirdose! :) Are you participating in GSSOC?

yeah, I am participating in Gssoc, before I can't be able to reply as it is locked.

**Comment by iqrafirdose** [comment]
> @iqrafirdose you may start working on the issue, just let us know if you're participating in gssoc'23 so we can add labels :)

Thank you @rupali-codes , I am participating in Gssoc before i can't be able to reply as it is locked.
