### ISSUE TITLE
[ADD]: Swift Language

### ISSUE THREAD

**Issue by Killer2OP** [rupali-codes/LinksHub#1129]
### Category Name

Languages

### Subcategory Name

none

### Additional Context

Swift is a language used to do IOS Development.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Killer2OP you may start working on thi issue

**Comment by k-deepak04** [comment]
closing as no response received from a long time
