### ISSUE TITLE
[Add]  PostgreSQL to backend/database

### ISSUE THREAD

**Issue by Parmesh119** [rupali-codes/LinksHub#1132]
### Description

PostgreSQL is an open-source relational database and is used as a database management system in many applications.
You have to add how this database is working and how to use it.

### Screenshots

![PostgreSQL](https://www.interdb.jp/pg/img/fig-2-01.png)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Parmesh119! :) Just to confirm, are you participating in GSSOC'23?

**Comment by rupali-codes** [comment]
@Parmesh119 thanks, please make sure to use [this](https://github.com/rupali-codes/LinksHub/issues/new?assignees=&labels=chore%2Cgoal%3A+new-link&projects=&template=add_link.yml&title=%5BAdd%5D+%3Cwrite+what+you+want+to+add%3E) template for adding new resources

**Comment by Parmesh119** [comment]
@CBID2 

> Hi @Parmesh119! :) Just to confirm, are you participating in GSSOC'23?

Yes, I am a GSSoC'23 contributor.
