### ISSUE TITLE
[FEATURE] To Use src Directory For Improved Code Organization

### ISSUE THREAD

**Issue by s2sharpit** [rupali-codes/LinksHub#1134]
### Description

I hope this message finds you well. I am writing to raise an issue and propose an enhancement. After careful consideration, I believe that incorporating the feature of Next.js 13, which allows for the addition of an "src" folder, could significantly improve the code organization within our project.

The primary objective of this enhancement is to separate the application code from the project configuration files, which typically reside in the root directory of the project. By adopting this practice, we can achieve better code clarity, maintainability, and ease of collaboration.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@rupali-codes @Anmol-Baranwal what you guys think?
i guess it's right to maintain a separate src folder for all the code base.

**Comment by rupali-codes** [comment]
> @rupali-codes @Anmol-Baranwal what you guys think? i guess it's right to maintain a separate src folder for all the code base.

The way it is looks fine to me,  what do you think @k-deepak04 ?

**Comment by k-deepak04** [comment]
> > @rupali-codes @Anmol-Baranwal what you guys think? i guess it's right to maintain a separate src folder for all the code base.
> 
> The way it is looks fine to me, what do you think @k-deepak04 ?

okay then no worries.

**Comment by rupali-codes** [comment]
> > > @rupali-codes @Anmol-Baranwal what you guys think? i guess it's right to maintain a separate src folder for all the code base.
> > 
> > 
> > The way it is looks fine to me, what do you think @k-deepak04 ?
> 
> okay then no worries.

alright then, closing the issue. @s2sharpit feel free to raise any other issues :)
