### ISSUE TITLE
[ADD] take U forward

### ISSUE THREAD

**Issue by medhavisahgal** [rupali-codes/LinksHub#1135]
### Site URL

https://www.youtube.com/@takeUforward

### Description of the above provided site

"Take U Forward" is an excellent YouTube channel specializing in competitive programming and DSA. With its well-curated content, including tutorials, problem-solving techniques, and explanations, it's a valuable resource for both beginners and those looking to enhance their skills.

### Category

Youtube

### Sub Category

Competitive Programming

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
This resource is already added.
