### ISSUE TITLE
[Refactor] Card component

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1136]
### File Name

components/Cards/Card.tsx

### Reason for Refactoring the Code

- The prop type using an interface, to explicitly specify the expected props for the `Card` component.
- declares `descriptionRef` as a reference to an HTML paragraph element, ensuring type safety and accurate type inference for the `descriptionRef` throughout the code
- The null check before accessing `scrollHeight` and `offsetHeight` properties to avoid potential errors.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal sounds cool, you may start working on it :D
