### ISSUE TITLE
[BUG] Vertical overflow on Design-inspiration subcategory in mobile view

### ISSUE THREAD

**Issue by ConradQQ** [rupali-codes/LinksHub#114]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

There is some vertical overflow in the design-inspiration subcategory on mobile view

### Screenshots

![Screen Shot 2023-01-29 at 16 52 40](https://user-images.githubusercontent.com/70613517/215340810-5ecc1956-581a-471f-970c-2d2410d7394b.png)

### What browser are you seeing the problem on?

Firefox

**Comment by rupali-codes** [comment]
@ConradQQ thank you noticing :)

**Comment by zvolcsey** [comment]
Hi! Can I work on this issue?

**Comment by rupali-codes** [comment]
@zvolcsey sure, assigning to you
