### ISSUE TITLE
[Add] I want to add Nextjs Doc

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1141]
### Site URL

https://nextjs.org/

### Description of the above provided site

**The Next.js Documentation Website: Your comprehensive resource for building modern, server-rendered React applications with blazing-fast performance and a rich ecosystem.**

### Category

Frontend

### Sub Category

N/A

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Nishitbaria! :) Just to confirm, are you participating in GSSOC'23?

**Comment by Nishitbaria** [comment]
@rupali-codes  I have raised Pull request ,Please reviwe it
