### ISSUE TITLE
[OTHER] Unable to write comment being issue as "ready"

### ISSUE THREAD

**Issue by Jay9874** [rupali-codes/LinksHub#1142]
### What would you like to share or ask?

@CBID2  I'm unable to write comment for issue #1118. though the labe is "ready"
![Screenshot_20230623-130412_Chrome](https://github.com/rupali-codes/LinksHub/assets/89871918/e9acd3c0-fe91-41cc-ade1-38889218a3bc)
The answer to your question is "Yes, I'm a GSSOC contributor"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned now @Jay9874
