### ISSUE TITLE
[Feature] Dockerized version of LinksHub for developer ease

### ISSUE THREAD

**Issue by The-Debarghya** [rupali-codes/LinksHub#1159]
### Description

- Developers/Contributers might have problems setting up the environment for development purposes, hence a dockerized version of this repo with changes instantly reflecting the deployment can be very easy as well as faster to setup for development.
- `Proposed solution`: Dockerized version of the application, that can be setup with only one command: 
 - `docker compose up`

*P.S- It wont be a production based docker deployment, instead a development setup.*

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@The-Debarghya its nice idea, you may start working on this :)

**Comment by The-Debarghya** [comment]
No need to start I had done it before even I raised the issue!!😅😅 @rupali-codes

**Comment by CBID2** [comment]
> No need to start I had done it before even I raised the issue!!😅😅 @rupali-codes 

In the future @The-Debarghya, please raise an issue before doing the PR. It'll allow us to determine if it suits LinksHub.

**Comment by The-Debarghya** [comment]
Please check the dates of PR and the Issue...would ya?

**Comment by CBID2** [comment]
> In the future @CBID2 please check the dates of the PR and the Issue linked to it!! It'll allow me to focus on what I'm doing!

Ok
