### ISSUE TITLE
[Feature] update menu navigation design

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1166]
### Description

The design of the menu on small screens is not optimal for user experience. If you would like me to update the design, please assign the issue and let me know where specific elements should be placed.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/2cec992c-c0e7-4380-b071-0318f6885a7b)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal i guess we can go for it

**Comment by CBID2** [comment]
> @Anmol-Baranwal i guess we can go for it

I experience the same problem too, so go ahead @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 
Is it necessary to show both the fork and star info at this screen size? Hiding one of them would undoubtedly resolve the issue and improve the user experience. Other than this, I would adjust the total width accordingly.

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 
> 
> Is it necessary to show both the fork and star info at this screen size? Hiding one of them would undoubtedly resolve the issue and improve the user experience. Other than this, I would adjust the total width accordingly.
> 
> 
> 
> Or we can put the social links at the top, then the buttons, and so on. What do you think?

I like the other idea more @Anmol-Baranwal. Hiding the fork button would make it difficult for new contributors to make their contributions.
