### ISSUE TITLE
[Refactor] Change Noraml functions to Arrow functions

### ISSUE THREAD

**Issue by saikiranreddy201** [rupali-codes/LinksHub#1167]
### File Name

Entire codebase whereever requires

### Reason for Refactoring the Code

Changing the entire codebase form **Normal functions** to **Arrow functions** is because
-> less code
-> Easy to understand
-> Implicit run
-> No prototyping

For example, 
**Changing this function** 
```
function handleCopy(e: React.MouseEvent<SVGElement, MouseEvent>) {
    e.stopPropagation()
    copyToClipboard(url)
  }
```
**To this function**
```
const handleCopy = (e: React.MouseEvent<SVGElement, MouseEvent>) => {
    e.stopPropagation();
    copyToClipboard(url);
  };
```

Doing this way the entire codebase where ever required, 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

**Comment by rupali-codes** [comment]
@k-deepak04 & @ujjawaltyagii what do you think about this?

**Comment by k-deepak04** [comment]
@rupali-codes usually using arrow function is a good practice when working with callbacks or nested functions. in rest cases in rest other cases it won't be good

below are the disadvantages of using arrow function in every scenario.

No arguments object: Arrow functions do not have their own arguments object, which means you can't access the arguments passed to the function using arguments. Instead, you would need to use rest parameters (...args) to achieve a similar effect.

Cannot be used as constructors: Arrow functions do not have a prototype property and cannot be used as constructors to create new objects. If your function needs to be used with the new keyword or requires a prototype for inheritance, you should stick with a normal function.

No dynamic this binding: As mentioned earlier, arrow functions inherit the this value from the surrounding scope. This means that the value of this is determined when the arrow function is defined, not when it is called. If you require dynamic this binding, such as when using the function as a method or with the bind() method, a normal function might be more appropriate.

**Comment by k-deepak04** [comment]
so @saikiranreddy201 i want you to rethink about this and change it to certain functions where necessary not the entire project.

**Comment by ujjawaltyagii** [comment]
> @k-deepak04 & @ujjawaltyagii what do you think about this?

I think we shouldn't change all functions to arrow functions but at the same time it would be difficult for him to determine which one to change into arrow function 0_0

**Comment by k-deepak04** [comment]
oaky @saikiranreddy201 please look into something else, thanks :)
