### ISSUE TITLE
[Feature] add footer at bottom of the site

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#117]
### Description

Hi, currently we don't have any footer in our project, and the looks incomplete without footer.

#### Specific Requirements

* should be sticky at `bottom`
* should not affect other components
* should also contain `GitHub` icon and it should point to this URL `https://github.com/rupali-codes/LinksHub/`

**Comment by rupali-codes** [comment]
Can we change background color to dark gray or something like that?
Also, replace copyright text  with **Open source | [MIT License](https://github.com/rupali-codes/LinksHub/blob/main/LICENSE) 2023 LinksHub**

**Comment by Aadarsh805** [comment]
> Can we change background color to dark gray or something like that? Also, replace copyright text with **Open source | [MIT License](https://github.com/rupali-codes/LinksHub/blob/main/LICENSE) 2023 LinksHub**

something like this?

![108 (1)](https://user-images.githubusercontent.com/95094057/215572484-ad02d3ba-4269-45e0-a9e8-1497033200cf.png)

**Comment by rupali-codes** [comment]
Ahh, thank you for the changes, let's have a transparent background, and remove FAQ and github for now, then make a PR. Bingo!

**Comment by Aadarsh805** [comment]
> 

I was just submitting the design though, If this doesn't get picked in the next week, I'll do it

here's how it looks with the requested changes
![108 (2)](https://user-images.githubusercontent.com/95094057/215575937-c8cd4844-8579-4850-9c63-677ab10dc12b.png)

**Comment by Aadarsh805** [comment]
Btw we can't have a transparent background because when there are more cards then the footer will overlap

Or we can have the above cards container size to be fixed till just above the footer and have overflow scroll on it

**Comment by rupali-codes** [comment]
> Btw we can't have a transparent background because when there are more cards then the footer will overlap
> 
> Or we can have the above cards container size to be fixed till just above the footer and have overflow scroll on it

Ahh, okay @Aadarsh805, you can create PR

**Comment by Aadarsh805** [comment]
Alright, as I said if no one picks it in a week, I'll do it and now that I'm finally free
I'll make a pr today

**Comment by Aadarsh805** [comment]
Here's a problem I'm facing with setting footer as `fixed`, the problem with fixed position is it doesn't relate to parent div
so it's not possible to set it up like I showed in the figma screenshot above
either we keep the footer to the whole window width or will have to set it to a fixed width for each size of screen


![image](https://user-images.githubusercontent.com/95094057/217720197-e2a1ad01-d80a-4e10-8155-74d572c8e990.png)


how it looks in entire screen width: 

![image](https://user-images.githubusercontent.com/95094057/217721875-62a9748d-f188-415d-8eae-05e7ea610677.png)

**Comment by Aadarsh805** [comment]
Keep it like this or any suggestions?
