### ISSUE TITLE
[DOCS] Adding sitemap.xml

### ISSUE THREAD

**Issue by saikiranreddy201** [rupali-codes/LinksHub#1171]
### Issue Description

A sitemap is a file that lists all the pages of a website, helping search engines understand its structure and content. It enhances search engine optimization (SEO) efforts by improving website visibility and indexing. I believe adding sitemap would be a perfect addition to this project.

### Additional Context

Adding the sitemap.xml file in the public folder section.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
This is an interesting idea @saikiranreddy201, but Since LinksHub's focus is providing developers with all tools needed to learn and/or improve their skills, I'm having trouble understanding how the sitemap fits into the project. Can you elaborate please?

**Comment by rupali-codes** [comment]
@saikiranreddy201 you may now respond here :)

**Comment by saikiranreddy201** [comment]
Hey @rupali-codes, So as I have mentioned this website had many endpoints and adding those links to site map can improve SEO. Sitemaps are files that provide information about the structure and organization of a website to search engines. They list all the important URLs of a site, helping search engines understand its content and navigate it more effectively. Search engines use sitemaps to discover and index web pages, improving the chances of a website's content appearing in search results.

**Comment by saikiranreddy201** [comment]
Hey @rupali-codes and @CBID2, please do check the other issues I have rasied 
#1186 
#1167

**Comment by CBID2** [comment]
Let's focus on this one first @saikiranreddy201

**Comment by CBID2** [comment]
> Hey @rupali-codes, So as I have mentioned this website had many endpoints and adding those links to site map can improve SEO. Sitemaps are files that provide information about the structure and organization of a website to search engines. They list all the important URLs of a site, helping search engines understand its content and navigate it more effectively. Search engines use sitemaps to discover and index web pages, improving the chances of a website's content appearing in search results.

Hmm...now you're on to something

**Comment by rupali-codes** [comment]
> > Hey @rupali-codes, So as I have mentioned this website had many endpoints and adding those links to site map can improve SEO. Sitemaps are files that provide information about the structure and organization of a website to search engines. They list all the important URLs of a site, helping search engines understand its content and navigate it more effectively. Search engines use sitemaps to discover and index web pages, improving the chances of a website's content appearing in search results.
> 
> Hmm...now you're on to something @saikiranreddy201. @rupali-codes, I think this could work. What do you think?

Yeah i think so 👀

@ujjawaltyagii what are your takes

**Comment by ujjawaltyagii** [comment]
> > > Hey @rupali-codes, So as I have mentioned this website had many endpoints and adding those links to site map can improve SEO. Sitemaps are files that provide information about the structure and organization of a website to search engines. They list all the important URLs of a site, helping search engines understand its content and navigate it more effectively. Search engines use sitemaps to discover and index web pages, improving the chances of a website's content appearing in search results.
> > 
> > 
> > Hmm...now you're on to something @saikiranreddy201. @rupali-codes, I think this could work. What do you think?
> 
> Yeah i think so 👀
> 
> @ujjawaltyagii what are your takes

It will help in Seo but Ig we'll have to update this sitemap file every time when new endpoints/components are added

**Comment by CBID2** [comment]
Alright then! :) @saikiranreddy201, go right on ahead on make this PR! :)

**Comment by saikiranreddy201** [comment]
hey @ujjawaltyagii, yes that is true, but it doesn’t make a difference adding one or two more endpoints frequently. when the application grows bigger with more endpoints, add couple of them at a time.

**Comment by saikiranreddy201** [comment]
Hey @CBID2 I have already raised the pr, please check :)

**Comment by CBID2** [comment]
> > > > Hey @rupali-codes, So as I have mentioned this website had many endpoints and adding those links to site map can improve SEO. Sitemaps are files that provide information about the structure and organization of a website to search engines. They list all the important URLs of a site, helping search engines understand its content and navigate it more effectively. Search engines use sitemaps to discover and index web pages, improving the chances of a website's content appearing in search results.
> 
> > > 
> 
> > > 
> 
> > > Hmm...now you're on to something @saikiranreddy201. @rupali-codes, I think this could work. What do you think?
> 
> > 
> 
> > Yeah i think so 👀
> 
> > 
> 
> > @ujjawaltyagii what are your takes
> 
> 
> 
> It will help in Seo but Ig we'll have to update this sitemap file every time when new endpoints/components are added  

Here it[is](https://github.com/rupali-codes/LinksHub/pull/1196) @ujjawaltyagii.

**Comment by saikiranreddy201** [comment]
Hey @CBID2 now please check the other issues I have raised :)
#1186
#1167

**Comment by CBID2** [comment]
> Hey @CBID2 now please check the other issues I have raised :)
> 
> #1186
> 
> #1167

Will do once the site map PR is merged
