### ISSUE TITLE
[Feature] Bookmark Feature

### ISSUE THREAD

**Issue by smty2018** [rupali-codes/LinksHub#1172]
### Description

Want to add a bookmark feature so that user can revisit their favourites.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
That seems interesting @smty2018. :) @rupali-codes, you think this could go alongside the feature we discussed on Discord?

**Comment by rupali-codes** [comment]
@smty2018 How you going to approach this?

**Comment by k-deepak04** [comment]
No response from a long time so closing this
