### ISSUE TITLE
[ADD] DevOps

### ISSUE THREAD

**Issue by saikiranreddy201** [rupali-codes/LinksHub#1175]
### Category Name

DevOps

### Subcategory Name

CI, CD, Containerization, Orchestration

### Additional Context

DevOps is widely used in the present Software Industry for faster and more reliable software development and deployment through improved collaboration, automation, and efficient processes. I believe adding a DevOps category in Linkshub would be a perfect fit
Subcategories would be

**CI/CD** - Jenkins, GitLab, Azure pipelines
**Containerization** - Docker, Kubernetes, Google Cloud
**Orchestration** - Kubernetes, Docker Swarm, Mesos, Nomad

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@saikiranreddy201 assigned to you, you may start working on it now
