### ISSUE TITLE
Readme Update [OTHER]

### ISSUE THREAD

**Issue by imabhi241** [rupali-codes/LinksHub#118]
### Description

Contributing Guideline link is not working in Readme. 
 
### Screenshot

![Screenshot_20230131_104446](https://user-images.githubusercontent.com/104147456/215671760-f9b168a5-14f7-4afa-9cc8-b6418739cc26.png)

**Comment by rupali-codes** [comment]
@imabhi241 would you like to fix this?

**Comment by imabhi241** [comment]
Yes sure if you assign this issue.

**Comment by rupali-codes** [comment]
thank you, go-ahead

> Yes sure if you assign this issue.

okay, go-ahead, assigning to you
