### ISSUE TITLE
[Add] Django Projects

### ISSUE THREAD

**Issue by SargamPuram** [rupali-codes/LinksHub#1182]
### Site URL

https://www.interviewbit.com/blog/django-projects/

### Description of the above provided site

This website provides free beginner-advanced level Django projects with source code.

### Category

Resources

### Sub Category

Project Ideas

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@SargamPuram assigned to you, you may start working on it now
