### ISSUE TITLE
[ADD] Devops cateogry 

### ISSUE THREAD

**Issue by creator79** [rupali-codes/LinksHub#1186]
### Category Name

Devops

### Subcategory Name

Source Code Repository,   Build Server, Build Artifacts,Testing Environment,Monitor and loggingInfrastructure as Code

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
This issue is duplicate of #1175
