### ISSUE TITLE
[Add] Quine Resources

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [rupali-codes/LinksHub#1188]
### Site URL

https://www.youtube.com/playlist?list=PLnCV5fTAsUgpaLMY_Z8FqPxZ89v-_pcfY

### Description of the above provided site

- Quine is a open source platform where user can add project and rank your project by getting likes and comments.
- Quine provide a platform where any newbie contributor can go for the `good first issue` and enter into the open source world.
- This playlist will help to those contributor who want to explore quine or new on the quine platform.
- Having a best content with best guidance.

### Category

Open Source

### Sub Category

Videos

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Assigned to you! you may now start working on this issue
