### ISSUE TITLE
[Add] Create games using Vanilla JavaScript

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [rupali-codes/LinksHub#1189]
### Site URL

https://www.youtube.com/playlist?list=PLYElE_rzEw_sowQGjRdvwh9eAEt62d_Eu

### Description of the above provided site

- Learn to create frontend games.
- Beginner friendly projects using vanilla Javascript.
- Learn Vanilla JS by creating the games.
- This will makes the learner more energetic and makes them creative.

### Category

Youtube

### Sub Category

Game Development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@Avdhesh-Varshney go for it
