### ISSUE TITLE
[Add] NPTEL- Introduction to AI by - mausam sir

### ISSUE THREAD

**Issue by PriyansuMaurya** [rupali-codes/LinksHub#1190]
### Site URL

https://archive.nptel.ac.in/courses/106/102/106102220/

### Description of the above provided site

I have been enrolled in this course for over two months and have successfully completed up to Module 4. Despite being recorded in 2019, the course remains highly relevant and offers comprehensive and insightful content. One aspect that I particularly appreciate is the instructor's approach, which I like to refer to as "starting with basic building blocks" and then gradually building upon the concepts. It allows for a solid foundation and a smooth progression throughout the course. It's worth mentioning that this course primarily focuses on theoretical aspects.

### Category

ML, AI & Data

### Sub Category

AI Course

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks @PriyansuMaurya you may start working on this issue

**Comment by CBID2** [comment]
Just to clarify @PriyansuMaurya. Are you in GSSOC’23? I see the labels for it but you have not clicked on the GSSOC checkbox.

**Comment by PriyansuMaurya** [comment]
What does it mean to be a GSSOC'23? 

PS: I know the full form

**Comment by rupali-codes** [comment]
> What does it mean to be a GSSOC'23?
> 
> PS: I know the full form

Its an open-source program hosted by girl script foundation, you can get different open source projects to contribute in and also get swags based on their criteria :)

**Comment by PriyansuMaurya** [comment]
> > What does it mean to be a GSSOC'23?
> > PS: I know the full form
> 
> Its an open-source program hosted by girl script foundation, you can get different open source projects to contribute in and also get swags based on their criteria :)

Thanks, Rupali. I will surely check it out.
