### ISSUE TITLE
[OTHER] Font Color 

### ISSUE THREAD

**Issue by PriyansuMaurya** [rupali-codes/LinksHub#1191]
### What would you like to share or ask?

![image](https://github.com/rupali-codes/LinksHub/assets/101447544/091e22df-c950-4313-94d8-56509294680a)

In the provided image, there are inconsistencies in the text colors that need to be addressed. Although these inconsistencies may be subtle and minute to observe, I would like to fix them to ensure a cohesive visual experience.

Light Mode:
Header: 111827
Footer: 000000

Dark Mode : 
Header : F3F4F6
Footer : E5E7EB

Suggestion: To ensure consistency across the UI, it would be beneficial to create a variable that represents all the colors used.

I have even check your style guide
![image](https://github.com/rupali-codes/LinksHub/assets/101447544/ff8038e8-2d4d-4ef9-b5e3-2b827ee92087)
![image](https://github.com/rupali-codes/LinksHub/assets/101447544/2b7a4ad7-b251-428a-b71d-5471a372ccd3)

If I have overlooked or omitted anything, please feel free to correct me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Great observation @PriyansuMaurya, assigning to you!

**Comment by PriyansuMaurya** [comment]
Hey, I was just wondering, for which colors should I create variables and how many of them?

**Comment by k-deepak04** [comment]
@PriyansuMaurya still on this?
need any help?

**Comment by CBID2** [comment]
Are you still working on this @PriyansuMaurya?

**Comment by PriyansuMaurya** [comment]
I'm on it and Thanks @CBID2, for reminder.

**Comment by hona9** [comment]
@CBID2 what might be the issue here? can you elaborate more?

**Comment by CBID2** [comment]
> @CBID2 what might be the issue here? can you elaborate more?

Hey @hona9. Someone started a PR for this issue already. Right now, I'm trying to find a way to make the colors more accessible and adding them to said PR.

**Comment by HimanshuMahto** [comment]
Hey @CBID2 is someone still working on this issue if not could you please assign me this issue to work on?

**Comment by Anmol-Baranwal** [comment]
> Hey @CBID2 is someone still working on this issue if not could you please assign me this issue to work on?

@CBID2 
Priyanshu is not assigned so maybe we can go forward. If you have the colors, please let him know.

**Comment by CBID2** [comment]
Go right ahead @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@CBID2 

Not me. It's @HimanshuMahto 😅

I've assigned him.

**Comment by Anmol-Baranwal** [comment]
> Hey @CBID2 is someone still working on this issue if not could you please assign me this issue to work on?

@HimanshuMahto 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
