### ISSUE TITLE
[Feature] close button

### ISSUE THREAD

**Issue by mandliyarajendra11** [rupali-codes/LinksHub#1192]
### Description

When we click on the read more, a pop-up box appears with  some information , but there is no close button. I know that clicking on the background will close it, but having a close button would be better and more visually appealing.

### Screenshots

![Screenshot (159)](https://github.com/rupali-codes/LinksHub/assets/119125519/e74b165d-ddbc-4ecc-ad96-103674b061f5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
I guess that would be nice. @mandliyarajendra11 where are you going to place the button?
