### ISSUE TITLE
[Add]  web developer youtuber

### ISSUE THREAD

**Issue by mandliyarajendra11** [rupali-codes/LinksHub#1193]
### Site URL

https://www.youtube.com/@TechnicalSuneja

### Description of the above provided site

Technical Suneja is a YouTuber who creates videos related to web development

### Category

Youtube

### Sub Category

web developer

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@mandliyarajendra11 assigned to you, you may start working on it now
