### ISSUE TITLE
[Feature] About us page

### ISSUE THREAD

**Issue by mandliyarajendra11** [rupali-codes/LinksHub#1194]
### Description

i can create about us page with section - 
some info about linkhub 
admin info ( social media handle )
our contributor section 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @mandliyarajendra11! :) Just to confirm, are you participating in GSSOC'23?

Also, we already have a contributor section, so I'm not sure if we need another one. What do you think @rupali-codes?
