### ISSUE TITLE
[Feature] animated scroll to top button 

### ISSUE THREAD

**Issue by harshita-2003** [rupali-codes/LinksHub#1197]
### Description

the scroll to top button would be animating up-down when visible .

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
thanks @harshita-2003, you may start working this issue :)
