### ISSUE TITLE
[ADD] <Languages/C++ Programming>

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [rupali-codes/LinksHub#1199]
### Category Name

Languages

### Subcategory Name

C++ Programming

### Additional Context

I will be creating a C++ programming subcategory and will also be adding some resources under it 

Please assign me this issue under GSSOC'23

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Swapnil-Singh-99 assigned to you, you may start working on it now
