### ISSUE TITLE
[Add] add new community - campus ambassador program geeksforgeeks

### ISSUE THREAD

**Issue by gulshanjakhon** [rupali-codes/LinksHub#1201]
### Site URL

https://www.geeksforgeeks.org/campus-ambassador-program-by-geeksforgeeks/

### Description of the above provided site

Wants to add a new program that will help students while they are in college.

### Category

Frontend

### Sub Category

COMMUNITIES

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@gulshanjakhon is it something like an event? could you please elaborate a bit more onto this?

**Comment by gulshanjakhon** [comment]
- Work Experience Certificate as a Campus Ambassador at GeeksforGeeks on successful completion of one year program

- LinkedIn recommendation after completion of the program

- Add Geeksforgeeks Campus Ambassador Program experience to your resume

- You can credit yourself as a Campus Ambassador in your email signatures, LinkedIn profile, blogs, Facebook pages, personal pages etc

- Eligible for Paid internship opportunities with GeeksforGeeks

- Interact with new people from your college, university, country and all over the world

- You may Exclusively Invite team Geeksforgeeks for technical sessions, tech fests and placement preparation guidance talk to your campus

**Comment by rupali-codes** [comment]
@gulshanjakhon thanks, i guess we can place it under _other/other-resources_
