### ISSUE TITLE
[Refactor] popupCategoryDesc Component

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1202]
### File Name

components\popup\popupCategoryDesc.tsx

### Reason for Refactoring the Code

- Handling non-null assertion error
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a5754edb-5fb0-4d29-be95-0a7413ce8ce2)

The refactored code will address this by checking if `overlayRoot` is null and returning early to handle the case when the element is not found.

- The code uses an additional condition `!currentCategory` in the if statement before returning `null`. Since the `showElement` variable already checks for the existence of `currentCategory`, this condition is redundant.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal ready to go!
