### ISSUE TITLE
[Add] I want to add Nuxtjs Docs📄

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1203]
### Site URL

https://nuxt.com/docs

### Description of the above provided site

Nuxt.js: The elegant Vue framework for building fast, scalable, and SEO-friendly applications.

### Category

Frontend

### Sub Category

Official Docs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Nishitbaria assigned to you, you may start working on it now
