### ISSUE TITLE
[Add] <DaFont to the font category>

### ISSUE THREAD

**Issue by AhorIsaac** [rupali-codes/LinksHub#1204]
### Site URL

https://www.dafont.com/

### Description of the above provided site

DaFont is a platform that allows users to download and share fonts. DaFont offers a wide variety of fonts, including both free and commercial fonts.

### Category

Frontend

### Sub Category

fonts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@AhorIsaac assigned to you, you may start working on it now
