### ISSUE TITLE
[BUG] Need of Queue

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1205]
### Description

Error encountered while running it locally. Thought of creating an issue to reference the bug, so we can address it quickly.

> I will make a quick PR to solve this.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/eaa5b13a-47f0-47e7-bae7-81dc246a41bb)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal are you still working on it

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal are you still working on it

Yes, will complete all the pending issues by today.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I don't think this is an issue anymore because once we apply it to the queue, the problem arises at line
```typescript
setSearchResults(results) // this is a problem
```
I attempted to refactor it and separate it to improve understandability. You can review the PR and let me know if the refactored code meets the requirements. If it doesn't meet the expectations, I suggest closing it accordingly.
