### ISSUE TITLE
[Add] a good deep learning website

### ISSUE THREAD

**Issue by Anantashayana** [rupali-codes/LinksHub#1206]
### Site URL

https://aman.ai/

### Description of the above provided site

A good resource for students preparing for a job interview in the domain of deep learning or folks who are looking for a concise summary of DL topics.

### Category

ML, AI & Data

### Sub Category

Deep Learning

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anantashayana assigned to you, you may start working on it now
