### ISSUE TITLE
[Add]  A good Machine Learning Website

### ISSUE THREAD

**Issue by Anantashayana** [rupali-codes/LinksHub#1207]
### Site URL

https://www.enjoyalgorithms.com/machine-learning/

### Description of the above provided site

Project-based ML course by Enjoy Algorithms to master machine learning algorithms and prepare for tech interview. Very good to understand the basic topics. 

### Category

ML, AI & Data

### Sub Category

Machine Learning

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anantashayana you may work on one issue at a time
