### ISSUE TITLE
[Feature] Create a new Contributor page

### ISSUE THREAD

**Issue by karthiknadar1204** [rupali-codes/LinksHub#1209]
### Description

I was thinking of adding a contributors page routed from the navbar itself, this page shall have data of all the contributors like their name, their github avatar and the number of commits made to the project, these data of the contributors will be made into individual cards and will be placed in descending order of the number of commits.

The cards will be styled according to the existing UI of the project.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @karthiknadar1204! :) Thanks for your suggestion, but this is already being addressed with this [pull request](https://github.com/rupali-codes/LinksHub/pull/1152#issuecomment-1616020849), so I'm closing this issue. Feel free to add your thoughts to the PR via [the code review article posted in this section of the Contributing guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#remarks-).
