### ISSUE TITLE
[Feature] Add Future Fonts to the font section of frontend.

### ISSUE THREAD

**Issue by Akanksha-202** [rupali-codes/LinksHub#1210]
### Description

Future Fonts is a unique platform that focuses on showcasing and supporting fonts that are still in development. It offers a glimpse into the creative process behind typeface design and allows designers to share their experimental and innovative work with the public.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Akanksha-202 hi, do you still want to work on this?

**Comment by Akanksha-202** [comment]
Actually it's a new link that I wanted to add and I have created the issue in the wrong template

**Comment by rupali-codes** [comment]
> Actually it's a new link that I wanted to add and I have created the issue in the wrong template

oh, okay thanks
