### ISSUE TITLE
[Feature] Adding hover.css resource in animation section

### ISSUE THREAD

**Issue by Akanksha-202** [rupali-codes/LinksHub#1211]
### Description

Hover.css is a collection of CSS3 transitions and animations that can be applied to various elements, including buttons and links. It provides a wide range of unique hover effects that can add flair to your user interface.

### Screenshots

Few glimpses of the resource :

https://github.com/rupali-codes/LinksHub/assets/100708686/78ae8b60-f468-47b8-ba45-fcd118f7740c

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Akanksha-202! :) Just to confirm, are you participating in GSSOC'23?

**Comment by Akanksha-202** [comment]
> Hi @Akanksha-202! :) Just to confirm, are you participating in GSSOC'23?

Yes!

**Comment by CBID2** [comment]
Also, is this meant to be a resource or a link to a resource @Akanksha-202?

**Comment by Akanksha-202** [comment]
It meant to be link to the resource, i misunderstood the issue templates at first :(

**Comment by CBID2** [comment]
> It meant to be link to the resource, i misunderstood the issue templates at first :(

Ahh ok. Well, I’m going to close this one, so you can raise the issue with its corresponding form
