### ISSUE TITLE
[Add] Picular site to colors section

### ISSUE THREAD

**Issue by Akanksha-202** [rupali-codes/LinksHub#1212]
### Site URL

https://picular.co/

### Description of the above provided site

Picular is a color search engine that generates color palettes based on keywords. You can enter a specific term, and it will generate a set of colors associated with that keyword, offering a creative way to explore color possibilities.

### Category

Frontend

### Sub Category

Colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Akanksha-202 do you want to work on this?

**Comment by Akanksha-202** [comment]
Yes

**Comment by CBID2** [comment]
Go ahead @Akanksha-202

**Comment by Anmol-Baranwal** [comment]
@Akanksha-202 
Are you interested in working on this? Let me know so that I can close this.

**Comment by rupali-codes** [comment]
@Akanksha-202 are you still willing to work on this issue?
