### ISSUE TITLE
[Bug] Text overlap in search result.

### ISSUE THREAD

**Issue by prem-code-github** [rupali-codes/LinksHub#1218]
### Site URL

https://www.linkshub.dev/search?query=front+end+video+with+css+and+javascript

### Issues:
if we search something with long String like this "_front end video with css and javascript"_, it overlaps to all other elements.
 ### Suggestions 

1. if any searches doesn't meet from database, it should write only **no data found**.
2. another is remove that line cause it doesn't looks good when we search like _frame_ . Text appears on screen `SEARCH?QUERY=FRAME` . it seems weird on screen.
 
### Screenshot:
![image](https://github.com/rupali-codes/LinksHub/assets/66858655/ed5ca07d-aff0-4744-9c1b-de2069ab426c)
![image](https://github.com/rupali-codes/LinksHub/assets/66858655/10e30331-848b-43d8-9618-e2d6c4fc7345)

### Category

Frontend

### Sub Category

Search Result

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hey, thanks :)

**Comment by harmeetsingh11** [comment]
Can I work on this issue under GSSoC'23?
I am a GSSoC'23 contributor.

**Comment by rupali-codes** [comment]
> @rupali-codes Can I work on this issue under GSSoC'23? I am a GSSoC'23 contributor.

Sure! assigning to you!
