### ISSUE TITLE
[Add]  Appwrite for database and authentication

### ISSUE THREAD

**Issue by Mihan786Chistie** [rupali-codes/LinksHub#1219]
### Site URL

https://appwrite.io/docs/authentication

### Description of the above provided site

Appwrite: The open-source backend server that simplifies application development with features like authentication, database management, and file storage.

### Category

Backend

### Sub Category

authentication, database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Just to confirm, are you in GSSOC @Mihan786Chistie?

**Comment by Mihan786Chistie** [comment]
> Just to confirm, are you in GSSOC @Mihan786Chistie?

@CBID2 I'm in GSSOC'23
