### ISSUE TITLE
[Add] Adding hover.css resource in animation section 

### ISSUE THREAD

**Issue by Akanksha-202** [rupali-codes/LinksHub#1222]
### Site URL

https://ianlunn.github.io/Hover/

### Description of the above provided site

Hover.css is a collection of CSS3 transitions and animations that can be applied to various elements, including buttons and links. It provides a wide range of unique hover effects that can add flair to your user interface.

Some glimpses of the resource.

https://github.com/rupali-codes/LinksHub/assets/100708686/64ef4cdd-538c-40da-9508-66ec27e47215

### Category

Frontend

### Sub Category

anaimations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Akanksha-202  assigned to you, you may start working on it now
