### ISSUE TITLE
Data Structures playlist with c++

### ISSUE THREAD

**Issue by anshulsoni4** [rupali-codes/LinksHub#1229]
### Site URL

https://www.youtube.com/playlist?list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA

### Description of the above provided site

Complete C++ Placement DSA Course, I followed for preparing Data Structures, covers all topic in depth and has questions and tasks as well, you can also track other students performance.

### Category

Youtube

### Sub Category

Data Structures

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
You may work on it now
