### ISSUE TITLE
[Add] Game Dev course video

### ISSUE THREAD

**Issue by anshulsoni4** [rupali-codes/LinksHub#1230]
### Site URL

https://www.youtube.com/watch?v=S8lMTwSRoRg

### Description of the above provided site

Learn how to use the Godot game engine to create your own platformer game. Throughout the course, you'll learn everything from setting up your first 2D scene and animating the player, to designing enemies, incorporating UI elements, and implementing game-saving features.

### Category

Youtube

### Sub Category

game-development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@anshulsoni4 assigned to you, you may start working on it now

**Comment by anshulsoni4** [comment]
thanks @rupali-codes
