### ISSUE TITLE
Add youtube resource for game development 

### ISSUE THREAD

**Issue by madhurafulkar** [rupali-codes/LinksHub#1232]
### Site URL

https://www.youtube.com/playlist?list=PLdOT12odxrUrUExBUuM5KoN0fAnOdzH1L

### Description of the above provided site

This tutorial helps you to learn Game Development and make your own game. Learn how to code for games.

### Category

Youtube

### Sub Category

Youtube

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @madhurafulkar! :) Just to confirm, are you in GSSOC'23?

**Comment by madhurafulkar** [comment]
> Hey @madhurafulkar! :) Just to confirm, are you in GSSOC'23?

yes

**Comment by rupali-codes** [comment]
> > Hey @madhurafulkar! :) Just to confirm, are you in GSSOC'23?
> 
> yes

Thanks, you may start working on it now
