### ISSUE TITLE
[Add]  Tailwind Official Docs

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1237]
### Site URL

https://tailwindcss.com/docs/installation

### Description of the above provided site

The Tailwind CSS documentation is a comprehensive resource that provides clear and concise explanations, examples, and guidelines for using and customizing the powerful utility-first CSS framework.

### Category

Frontend

### Sub Category

docs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Nishitbaria you can start working on this issue
