### ISSUE TITLE
[BUG] Fix github link invisibility

### ISSUE THREAD

**Issue by karthiknadar1204** [rupali-codes/LinksHub#1238]
### Description

I worked on this issue to add a hover effect to the navbar links but the GitHub link is going invisible on hovering, I would like to fix it by making it prominently visible on hovering.
<img width="587" alt="Screenshot 2023-07-07 at 2 41 04 PM" src="https://github.com/rupali-codes/LinksHub/assets/95973644/15d0f8a0-a329-47fe-963c-d6afeb4a8848">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@karthiknadar1204 you may start working on this
