### ISSUE TITLE
[Add] Add reesource for react js

### ISSUE THREAD

**Issue by karthiknadar1204** [rupali-codes/LinksHub#1239]
### Site URL

https://www.youtube.com/watch?v=tiLWCNFzThE&list=PLwGdqUZWnOp3aROg4wypcRhZqJG3ajZWJ&ab_channel=ThapaTechnical

### Description of the above provided site

I personally have used this series to learn react and think would be a good addition to the site,Have checked the other links, none of them have this link.

### Category

Frontend

### Sub Category

designing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks, you may start working on this

**Comment by karthiknadar1204** [comment]
Thank you
