### ISSUE TITLE
[Add] official docs of Svelte 📃

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1240]
### Site URL

https://svelte.dev/docs/introduction

### Category

Frontend

### Sub Category

docs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
You may work on it now
