### ISSUE TITLE
[Description] Add a category for Cloud and devops

### ISSUE THREAD

**Issue by karthiknadar1204** [rupali-codes/LinksHub#1241]
### Category Name

Devops

### Subcategory Name

DOCKER

### New or updated description of above subcategory

The following section will comprise of multiple sub categories to learn various tools used in devops using various tutorials.
like for linux we can have people add new resources, same for git and github and docker, kubernetes and resources to learn cloud.

### Status of Description

- [X] Adding new description
- [X] Updating existing description

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@karthiknadar1204 DevOps is a subcategory itself 👀 would you like to update the description :)

**Comment by karthiknadar1204** [comment]
Cloud🤔

**Comment by karthiknadar1204** [comment]
Will do in a bit @rupali-codes

**Comment by karthiknadar1204** [comment]
works?

**Comment by karthiknadar1204** [comment]
@rupali-codes Can I get this issue assigned to me, I have already completed the other two issues assigned to me, the pr's are yet to be reviewed, till then can I add some resources for the same?

**Comment by karthiknadar1204** [comment]
@CBID2 @rupali-codes Can i get this issue assigned now

**Comment by rupali-codes** [comment]
yes you can start working on it and thanks for your patience !!
