### ISSUE TITLE
[DOCS] Add gssoc'23 timeline and pointer system

### ISSUE THREAD

**Issue by karthiknadar1204** [rupali-codes/LinksHub#1242]
### Issue Description

Here i propose to add the pointer system used in gssoc'23 to the readme file for the new visitors to have a better understanding of the project and the program.

### Additional Context

For reference, please refer the following readme link, I tailored the same for another project I am involved with:
https://github.com/akshitagupta15june/Moksh

Refer to the part below moderators, That is what I wish to incorporate to the readme.md file of the project.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @karthiknadar1204! :) Just to confirm, are you in GSSOC?

**Comment by karthiknadar1204** [comment]
yes

**Comment by CBID2** [comment]
> yes

Great! You're assigned

**Comment by karthiknadar1204** [comment]
@CBID2 Could you once share your opinion on #1236  #1238  and #1241

**Comment by CBID2** [comment]
> @CBID2 Could you once share your opinion on #1236  #1238  and #1241 

Let's focus on finishing this one first @karthiknadar1204
