### ISSUE TITLE
[ADD] Competitive Programming Category

### ISSUE THREAD

**Issue by navharsh** [rupali-codes/LinksHub#1250]
### Category Name

Competitive Programming

### Subcategory Name

sites

### Additional Context

Creating a new category for sites like Leetcode and Hackerrank after discussion in #1123 .

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
What’s wrong @navharsh?

**Comment by navharsh** [comment]
> What’s wrong @navharsh?

There's already a subtopic with same name in youtube and it's content were getting mixed with competitive programming topic.

**Comment by navharsh** [comment]
@CBID2 @rupali-codes

**Comment by rupali-codes** [comment]
@navharsh what do you wanna do with it now?

**Comment by navharsh** [comment]
> @navharsh what do you wanna do with it now?

I'm sorry, I got busy with some things and totally forgot about this one. It would be great if someone else can pick it up as I will be busy for another week.
I am still willing to work on it after that though

**Comment by rupali-codes** [comment]
> > @navharsh what do you wanna do with it now?
> 
> I'm sorry, I got busy with some things and totally forgot about this one. It would be great if someone else can pick it up as I will be busy for another week. I am still willing to work on it after that though

do you still want to work on this? or should we close the issue?

**Comment by navharsh** [comment]
@rupali-codes I will start working on it asap. will add a pr tomorrow to ask for some feedback.
