### ISSUE TITLE
[Add] Fossbytes 

### ISSUE THREAD

**Issue by Shreya111111** [rupali-codes/LinksHub#1255]
### Site URL

https://fossbytes.com/

### Description of the above provided site

Adding Fossbytes blogs which contains the diversified info related tech

### Category

Resources

### Sub Category

blogs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Shreya111111! :) Just to confirm, are you participating in GSSOC'23?

**Comment by Shreya111111** [comment]
yes @CBID2 I am a GSSOC'23 contributor

**Comment by Shreya111111** [comment]
@CBID2  can i proceed further

**Comment by Shreya111111** [comment]
@CBID2 I have also created another issue #1252 for Youtube resources with diversified and latest tech related AIML for Tensorflow. can I proceed further with that too.

**Comment by CBID2** [comment]
> @CBID2 I have also created another issue #1252 for Youtube resources with diversified and latest tech related AIML for Tensorflow. can I proceed further with that too. 

Finish solving this issue first.

**Comment by Shreya111111** [comment]
@CBID2 but I have already linked the PR for both the issues. kindly check PR #1265 and #1268
