### ISSUE TITLE
[Add] AWS Amplify for  database and authentication

### ISSUE THREAD

**Issue by Mihan786Chistie** [rupali-codes/LinksHub#1259]
### Site URL

https://aws.amazon.com/amplify/

### Description of the above provided site

AWS Amplify is a comprehensive development platform that simplifies building scalable and secure web and mobile applications with AWS services.

### Category

Backend

### Sub Category

authentication, database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
You may work on it now
