### ISSUE TITLE
[Refactor]  Code Refactoring - Search bar Component 

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1260]
### File Name

components/Searchbar/Searchbar.tsx

### Reason for Refactoring the Code

Description:
The Searchbar component (located at components/Searchbar/Searchbar.tsx) currently has some areas that can be improved for better readability and maintainability. This issue proposes refactoring the code in the Searchbar.tsx file to address these concerns.

Areas of improvement:
1. Remove commented out code: There is commented out code for the SearchIcon component in the Searchbar component file. This code can be safely removed to improve code cleanliness.

2. Simplify initial state assignment: The initial state assignment for the searchQuery state variable in the Searchbar component can be simplified. Instead of using the nullish coalescing operator (`??`), we can directly use the query value since it is guaranteed to be a string or undefined.

3. Improve naming and formatting: Some variable names and formatting could be improved for better readability. For example, renaming the event parameter in the handleSearchChange function from `e` to `event` and formatting the code consistently.

4. Optimize SearchIcon placement: The SearchIcon component is currently placed outside the input element in the Searchbar component file. Moving it inside the input element will help maintain consistency and improve the layout of the component.

5. Provide explicit types: It is beneficial to provide explicit types for the useState hooks used in the Searchbar component. Specifically, adding types for the searchQuery and errorMessage variables will enhance code clarity.

The proposed changes will enhance the code quality of the Searchbar component in the Searchbar.tsx file, making it more readable, maintainable, and aligned with best practices.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

**Comment by rupali-codes** [comment]
thanks You may work on it now
