### ISSUE TITLE
[Add] add code editor

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1263]
### Site URL

https://ide.geeksforgeeks.org/

### Description of the above provided site

This code editor is provided by geeksforgeeks which supports many languages.

### Category

Frontend

### Sub Category

code editor

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@S-ishita thanks You may work on it now
