### ISSUE TITLE
[Add] MDN web docs

### ISSUE THREAD

**Issue by Illaf** [rupali-codes/LinksHub#1266]
### Site URL

https://developer.mozilla.org/en-US/

### Description of the above provided site

The MDN Web Docs site provides information about Open Web technologies including HTML, CSS, and APIs for both Web sites and progressive web apps.MDN Web Docs has the most up-to-date and accurate information and the content is presented in an easy-to-understand manner. It is also  available in many languages 

### Category

Frontend

### Sub Category

tutorials , illustration and information

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
MDN has already been added
