### ISSUE TITLE
[ADD] Adding a full stack category in the website

### ISSUE THREAD

**Issue by Illaf** [rupali-codes/LinksHub#1267]
### Category Name

backend

### Subcategory Name

informative

### Additional Context

There are certain documents and resources that are useful for both frontend and backend . Hence we naaed a category for full stack in the website

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Illaf hi, you may start working on this issue

**Comment by Illaf** [comment]
> @Illaf hi, you may start working on this issue

Okay 👍

**Comment by Anmol-Baranwal** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen it if you'd like to contribute or have further discussions.
