### ISSUE TITLE
[Feature] Add back-to-top button

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#127]
### Description

Currently, we don't have any scroll-to-top button and it becomes hard when we have so many cards and we want to scroll to top. 

#### Specific requirements

* It should be fixed at bottom-right corner
* Should only display when content is overflowing the screen
* Background color should be violet as per our theme

**Comment by zvolcsey** [comment]
@rupali-codes Hi! Can I work on this issue?

**Comment by rupali-codes** [comment]
@zvolcsey yes go-ahead :)
