### ISSUE TITLE
[Add] Wanted to add Wes Bos YouTube channel in web development section 

### ISSUE THREAD

**Issue by Prajwal0225** [rupali-codes/LinksHub#1270]
### Site URL

https://www.youtube.com/@WesBos

### Description of the above provided site

He created the most popular JavaScript course javascript30 where you build 30 JS projects in 30 days

### Category

Youtube

### Sub Category

web development 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
You may work on it now
