### ISSUE TITLE
[Add] Kaggle a data science related site

### ISSUE THREAD

**Issue by Pro-18** [rupali-codes/LinksHub#1273]
### Site URL

https://www.kaggle.com/

### Description of the above provided site

Adding Kaggle, a popular data science and machine learning platform, to the list of approved websites in an organization's network can be a matter of debate

![kaggle](https://github.com/rupali-codes/LinksHub/assets/92087279/d450c2c4-f520-42b3-b5d2-91dd5851d336)

### Category

ML, AI & Data

### Sub Category

Data Science

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks, you add this in machine-learning/data-science
