### ISSUE TITLE
[Feature]: ADD WORKFLOW SCRIPT TO PREVENT MULTIPLE ISSUES 🔐

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#1274]
### Description

- We want to add a workflow script regarding closing the issues.
-  This script will look into the contributor created issue and checks if he already created an issue, If an issue exists the new issue will be closed.
-  According the GSSoC Contributing guidelines, A contributor must want to finish one issue before creating another issue.
- But in this repository the contributors are spamming multiple issues, This is strictly against the contributing guidelines.
- After adding this script you don't want to state that `please create one issue at a time` for every contributor who creates more than one issue at a time. This script will automate the process and closes the new one if already an existing one is found.
- Please assign this issue to me @rupali-codes, @CBID2 to make the work done.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Why did you close this PR @0xabdulkhalid?
