### ISSUE TITLE
[BUG] Want to modify the text as "You have searched for " which shows when we search

### ISSUE THREAD

**Issue by soubhik-111** [rupali-codes/LinksHub#1276]
### Description

We need to replace the text "SEARCH?QUERY=" with "You have searched for ".

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/90599826/1b04c3dd-de0a-4106-be07-53ced18de338)

### Any additional information?

@rupali-codes Kindly assign me under GSSOC'23

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
This issue being resolved in #1297. Thanks for your concern. Feel free to raise any other issues you want to :)
