### ISSUE TITLE
[Feature] Auto Suggestion

### ISSUE THREAD

**Issue by soubhik-111** [rupali-codes/LinksHub#1277]
### Description

I want to add an autosuggestion in the search button.
Now,
Until we hit enter button we didn't get any results.
As an user, they never know which subcategory is present and which is not present.

Solution adding autosuggestion which suggests even for little wrong search kind of youtube

If you search for "Javasvript" You still get a suggestion of Javascript. 

 

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/90599826/3facbc15-92d9-431b-b6b6-a3cfa2171ea8)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by soubhik-111** [comment]
Hello @CBID2 , Can you please verify as I have checked it and didn't found any same issue or PR

**Comment by CBID2** [comment]
> Hello @CBID2 , Can you please verify as I have checked it and didn't found any same issue or PR

Here it is [search pull request ](https://github.com/rupali-codes/LinksHub/pull/1257)

**Comment by soubhik-111** [comment]
Thank You @CBID2 For letting me know about it.
![image](https://github.com/rupali-codes/LinksHub/assets/90599826/bb539074-8f17-48b4-9739-0588b158d436)
It's not recommending  C and C sharp
I will wait once it merge, I will fix the rest.

Can I work on the same issue or shall I left it for now.

**Comment by CBID2** [comment]
Leave it for now

**Comment by soubhik-111** [comment]
Okay
