### ISSUE TITLE
[ADD] Whole new category cloud computing.

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1279]
### Category Name

Cloud

### Subcategory Name

Microsoft Azure, AWS, GCP.

### Additional Context

i will add whole new category with three subcategories under it , as cloud computing is in boom nowadays and people often search for this which cloud to go with and proceed with certifications.
so i will add category cloud, and 3 subcategories under it , follwed by adding resources in all of them.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes what's your idea regarding this?

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes what's your idea regarding this?

Sounds good 👍🏾

**Comment by rupali-codes** [comment]
we can go for it
