### ISSUE TITLE
No description of categories provided in i button.

### ISSUE THREAD

**Issue by PiyushK79** [rupali-codes/LinksHub#1284]
### Description

When we click on the i button we only see the category name but not its description.

So I would like to add category description for every category in 2-3 lines.

@rupali-codes Please assign this issue to me under Gssoc23.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/100259650/a44c5d3b-3365-4c7d-8bba-6ec2cf1dab26)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @PiyushK79! :) This would super helpful! :) Before I assign this issue to you, are you in GSSOC'23?

**Comment by PiyushK79** [comment]
Thanks I will start working on it.
