### ISSUE TITLE
[Add] <devhints.io/react to the React category>

### ISSUE THREAD

**Issue by AhorIsaac** [rupali-codes/LinksHub#1285]
### Site URL

https://devhints.io/react

### Description of the above provided site

[devhints.io/react](https://devhints.io/react) is a React.js cheatsheet that gives a comprehensive guide on the most fundamental concepts of React.js, and it offers a knowledge management approach to help remember those concepts easily.

### Category

Frontend

### Sub Category

React

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks, you may start working on this
