### ISSUE TITLE
[Add] Data Structures & Algorithms playlist with Java.

### ISSUE THREAD

**Issue by aadityadike** [rupali-codes/LinksHub#1287]
### Site URL

https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ

### Description of the above provided site

The Complete Java Placement DSA Course is the best course I know for preparing for Data Structures & Algorithms interviews. The course covers all topics in depth, with clear explanations and plenty of practice questions and tasks. The instructor, who has a wealth of experience in the field, is also very knowledgeable and engaging.

### Category

Youtube

### Sub Category

Data Structures

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@aadityadike thanks you may work on it
