### ISSUE TITLE
[ADD] new category of communities 

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1292]
### Category Name

Telegram and twitter communities

### Subcategory Name

telegram

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@S-ishita you may work on this, thanks :)
