### ISSUE TITLE
[OTHER]: Revamp hover states for Header icons  🪄

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#1299]
### What would you like to share or ask?

- There is so much of inconsistency on current hover states for icons
- I would like to revamp the hover states so that every icon's hover would be the same pattern as site's primary color `#8B5CF6`

### Current behaviour

https://github.com/rupali-codes/LinksHub/assets/92252895/d6dfdb2a-7b9a-4d11-acae-3ee40e1bf476

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@0xabdulkhalid thanks, you may start working on this
