### ISSUE TITLE
[Add]: Add Edabit Website for Learn Programming with Interactive Challenges in Different Languages

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1302]
### Site URL

https://edabit.com/

### Description of the above provided site

- Add Edabit website for Learn Programming with 10,000+ Interactive challenges
- This Challenges List has Vey Easy Level to Expert Level.
- This website has Interactive Console Editor for Practicing Challenges

### Category

Frontend

### Sub Category

online-code-editors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
I am opening all your issues for others to contribute.

Feel free to let me know, if you want to solve the issues.

**Comment by Vijaykv5** [comment]
I would like to work on this issue..May you can assign me

**Comment by Anmol-Baranwal** [comment]
Sure @Vijaykv5 

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
