### ISSUE TITLE
[Add]: Add CodingGame Website Link for Practice & Learn Programming with Interactive Challenges

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1303]
### Site URL

https://www.codingame.com/start

### Description of the above provided site

- Add Codingame website for Learn and Practice Programming with Interactive Challenges in different Programming Languages

### Category

Frontend

### Sub Category

online-code-editors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Vijaykv5** [comment]
I would love to work on it :)

**Comment by Anmol-Baranwal** [comment]
Comment here so that I can assign you the issue.
