### ISSUE TITLE
[Add] : Add Interviewbit for Learn and Practice Programming with Online Code editor

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1305]
### Site URL

https://www.interviewbit.com/

### Description of the above provided site

- Add Interviewbit Website for Learn and Practice Programming with Online Code Editor

### Category

Frontend

### Sub Category

online-code-editors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @NarendraKoya999! :) Just to confirm, are you participating in GSSOC'23?

**Comment by NarendraKoya999** [comment]
> Hi @NarendraKoya999! :) Just to confirm, are you participating in GSSOC'23?

Yes @CBID2 . I am Participating in GSSOC'23
