### ISSUE TITLE
[Feature] Add internationalization i18n

### ISSUE THREAD

**Issue by nujovich** [rupali-codes/LinksHub#131]
### Description

Currently, the application supports the English language. It could be appealing to support other languages like Spanish

### Screenshots

![image](https://user-images.githubusercontent.com/48018975/216807908-e80b074a-4a3f-41f8-9a34-f9f03f5a15fe.png)

**Comment by rupali-codes** [comment]
@nujovich It's a great idea, but we'll keep it to English by default. 

Would you like to work on this?

**Comment by nujovich** [comment]
@rupali-codes sure! I've already started

**Comment by nujovich** [comment]
@rupali-codes could you please assign me this issue ?

**Comment by rupali-codes** [comment]
> @rupali-codes could you please assign me this issue ?

sure
