### ISSUE TITLE
[Feature] want to add new java script tutorial 

### ISSUE THREAD

**Issue by Sushilverma002** [rupali-codes/LinksHub#1329]
### Description

tutorialTpoint
https://www.javatpoint.com/reactjs-tutorial
here the link
![image](https://github.com/rupali-codes/LinksHub/assets/114687502/db699f12-5b6b-4624-902b-67c5a0023090)

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/114687502/2d90c0b4-e318-4ba6-a1d5-916e0e5f9c2a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Sushilverma002! :) Just to confirm, are you participating in GSSOC'23?

**Comment by Sushilverma002** [comment]
Yess

**Comment by CBID2** [comment]
You're assigned @Sushilverma002
