### ISSUE TITLE
[Add] Add good first issues link to the open source tools

### ISSUE THREAD

**Issue by tayyab-ilyas** [rupali-codes/LinksHub#1330]
### Site URL

https://goodfirstissues.com/

### Description of the above provided site

This website helps you filter out good first issues according to your tech stack.

### Category

Open Source

### Sub Category

issue tracker

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi @tayyab-ilyas, you may add this in _open_source/tools.json_ file :)
