### ISSUE TITLE
[ADD] <Languages/Dart>

### ISSUE THREAD

**Issue by tayyab-ilyas** [rupali-codes/LinksHub#1331]
### Category Name

Languages

### Subcategory Name

Dart

### Additional Context

I'd like to add a subcategory for the Dart programming language under the Languages category.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @tayyab-ilyas! :) Just to confirm, are you participating in GSSOC'23?

**Comment by tayyab-ilyas** [comment]
> Hi @tayyab-ilyas! :) Just to confirm, are you participating in GSSOC'23?

Hi ! yes I am.

**Comment by tayyab-ilyas** [comment]
can you assign this to me?

**Comment by CBID2** [comment]
> can you assign this to me?
> 
> 

You're assigned @tayyab-ilyas
