### ISSUE TITLE
[Add] Passport.js

### ISSUE THREAD

**Issue by AlfiyaSiddique** [rupali-codes/LinksHub#1333]
### Site URL

https://www.passportjs.org/

### Description of the above provided site

**Passport.js**

Passport.js is an authentication middleware that is used with nodejs application to add various authentication ways like sign in with Google or sign in in with GitHub etc on websites.

### Category

Backend

### Sub Category

Authentication

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @AlfiyaSiddique! :) Just to confirm, are you participating in GSSOC'23?

**Comment by AlfiyaSiddique** [comment]
> Hi @AlfiyaSiddique! :) Just to confirm, are you participating in GSSOC'23?

Yes, I'm participating in GSSOC'23

**Comment by CBID2** [comment]
> > Hi @AlfiyaSiddique! :) Just to confirm, are you participating in GSSOC'23?
> 
> Yes, I'm participating in GSSOC'23 

You're assigned @AlfiyaSiddique
