### ISSUE TITLE
[Add] : Add Notion Website in Blogs Sub-Category in Resources Section

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1339]
### Site URL

https://www.notion.so/

### Description of the above provided site

- This Notion Website Bunch of Options List like Blogs, Guides &Tutorials, Webinars and Much More.
- Interactivity with Developers At One Place using Community Option in Notion Website

### Category

Resources

### Sub Category

blogs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned now @NarendraKoya999

**Comment by NarendraKoya999** [comment]
Hi @CBID2 . Please Look at once Unassigned Issues raised by Me. If Possible, Assign that Issues as soon as Possible

**Comment by NarendraKoya999** [comment]
@rupali-codes . Why you can removed level Label?

**Comment by NarendraKoya999** [comment]
@rupali-codes  . Please close this Issue . This Issue related PR Already Merged

**Comment by NarendraKoya999** [comment]
@CBID2 . Please Close this PR. It's Already Merged and Added Labels Also
