### ISSUE TITLE
[OTHER]: Fix typos and refactor of components folders.

### ISSUE THREAD

**Issue by fracergu** [rupali-codes/LinksHub#134]
### What would you like to share or ask?

I see some typos and components folder having several index.html when there is no need of them so I suggest to refactor them to improve structure clarity.

**Comment by rupali-codes** [comment]
Hi, @fracergu are you still working on this?

**Comment by fracergu** [comment]
Hello Rupali
Due to the changes on the app the issue was going to need more time and right now I don't have it.
I will try to take a look at it in the next few days, but feel free to assign it to someone else if you see it convenient.

**Comment by Noothan-am** [comment]
hey @rupali-codes is this issue from  documentation?

**Comment by rupali-codes** [comment]
> hey @rupali-codes is this issue from documentation?

Yes. And the folder structure

**Comment by Noothan-am** [comment]
please assign it to me

**Comment by rupali-codes** [comment]
> please assign it to me

We have assigned you another issue, please fix that first, then you can work on this one :)
