### ISSUE TITLE
[Add] : Add SIMPLILEARN YouTube Channel for Learning Full Stack Web Development Course

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1342]
### Site URL

https://www.youtube.com/watch?v=R6RX2Zx96fE

### Description of the above provided site

- Add SimpliLearn YouTube Channel Link for Learning Full Stack Web Development .
- This is Recently Updated Course and It's useful for Who can start to Learning Full Stack Web Development   as a Beginners Level

### Category

Youtube

### Sub Category

web-development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Vijaykv5** [comment]
Can You assign me ? I'm interested to work on it

**Comment by Vijaykv5** [comment]
This issue has already been Fixed by @NarendraKoya999

**Comment by NarendraKoya999** [comment]
> This issue has already been Fixed by @NarendraKoya999 

This Issue is already merged and linked to One Of My PR. Please Check Properly!!

**Comment by CBID2** [comment]
> > This issue has already been Fixed by @NarendraKoya999 
> 
> This Issue is already merged and linked to One Of My PR. Please Check Properly!!

Can you link it here @NarendraKoya999? I can't find it in the PR section.

**Comment by NarendraKoya999** [comment]
> > > This issue has already been Fixed by @NarendraKoya999 
> > 
> > This Issue is already merged and linked to One Of My PR. Please Check Properly!!
> 
> Can you link it here @NarendraKoya999? I can't find it in the PR section. 

That PR No is : #1389

**Comment by CBID2** [comment]
Done. Thanks for clarifying @NarendraKoya999
