### ISSUE TITLE
[Add] : Add Intellipaat YouTube Channel for Learning Full Stack web Development 

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1343]
### Site URL

https://www.youtube.com/results?search_query=intellipaat+web+development&sp=EgIIBQ%253D%253D

### Description of the above provided site

- Add Intellipaat YouTube Channel for Learning Full Stack Web Development as a Beginner's Level
- This Channel has Different Full stack Web Development Courses provided by Different Instructors

### Category

Youtube

### Sub Category

web-development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@NarendraKoya999 are you still willing to work on your issues regards to add new resources
