### ISSUE TITLE
[Add] : Add SuperSimpleDev Channel for Learning Frontend Development Course in Simplify Way

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1344]
### Site URL

https://www.youtube.com/@SuperSimpleDev/videos

### Description of the above provided site

- Add SuperSimpleDev Channel for Learning Frontend Development Course in Simplify Way.
- Tech Stacks included in this Course is likely HTML, CSS, JavaScript and Other Basic Backend Course Videos
- This Youtuber recently uploaded JavaScript Course is Really Awesome and His Teaching Style is Just Outstanding

### Category

Youtube

### Sub Category

web-development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi, @NarendraKoya999 are you working on this issues?

**Comment by NarendraKoya999** [comment]
> Hi, @NarendraKoya999 are you working on this issues?

This Issue is Already Merge in One PR. Please Closed.

**Comment by rupali-codes** [comment]
> > Hi, @NarendraKoya999 are you working on this issues?
> 
> This Issue is Already Merge in One PR. Please Closed. Only 3 Issues are Pending Unassigned No : #1384 #1385 and #1458

Please read contributing guidelines. When your PR is merged or closed then its YOUR responsibility to close the issue

**Comment by NarendraKoya999** [comment]
@rupali-codes. It's Tough Activity from My Side. Because of Issues are Locked. Not Possibility to Close that Issues. I have Mentioned Here #1340 #1341 #1342 #1343 #1344 #1345 #1346 #1347. I am Sure these All Issues are Linked to 2 PR's No : #1388 #1389

**Comment by rupali-codes** [comment]
> @rupali-codes. It's Tough Activity from My Side. Because of Issues are Locked. Not Possibility to Close that Issues. I have Mentioned Here #1340 #1341 #1342 #1343 #1344 #1345 #1346 #1347. I am Sure these All Issues are Linked to 2 PR's No : #1388 #1389 are Merged already.

can u please close all those issues?
