### ISSUE TITLE
[Add] : Add "Software Testing Mentor" YouTube channel for Learning Full Stack Testing Courses

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1347]
### Site URL

https://www.youtube.com/@softwaretestingmentor/videos

### Description of the above provided site

-  Add "Software Testing Mentor" YouTube channel for Learning Full Stack Testing Courses.
- This channel one of the Most Underrated YouTube Channel for Learning Testing Courses.

### Category

Youtube

### Sub Category

testing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi @NarendraKoya999, we appreciate your willingness to contribute in LinksHub but can you please summarize all this Resource addition resources in one issue and close all other? also, as i can see you are willing to work on each of them, could you please consider raising a single PR?

**Comment by NarendraKoya999** [comment]
Ok. I can Understand @rupali-codes . I can Follow your Guidelines. If I have posted some Resources related to Same category .Then, I will Create a Single PR. Not Individual  PR's. Am I Right?

**Comment by NarendraKoya999** [comment]
> Ok. I can Understand @rupali-codes . I can Follow your Guidelines. If I have posted some Resources related to Same category .Then, I will Create a Single Issue and along with Create a Single PR on Particular That. Not to Create Individual Issues and PR's. Am I Right?. This time ,Please Considered Present assign pending Issues If Useful and Also I combine similar issues group them into a Single PR. Next time onwards, What we are discussed on guidelines, I strongly Follow them.

Hi @rupali-codes . Any update on my Quote?

**Comment by rupali-codes** [comment]
> Ok. I can Understand @rupali-codes . I can Follow your Guidelines. If I have posted some Resources related to Same category .Then, I will Create a Single Issue and along with Create a Single PR on Particular That. Not to Create Individual Issues and PR's. Am I Right?. This time ,Please Considered Present assign pending Issues If Useful and Also I combine similar issues group them into a Single PR. Next time onwards, What we are discussed on guidelines, I strongly Follow them.

Sure, thanks

**Comment by NarendraKoya999** [comment]
@rupali-codes  .Who can Assigned my pending Issues. Because of in last week I created 7 to 10 Issues only related to YouTube Videos on Both Web Development and Testing Courses. If assigned, I create only two Individual PR's . One PR is on Web Development and Other one is Testing Related? . Kindly taken my Request into Consideration?

**Comment by rupali-codes** [comment]
> @rupali-codes .Who can Assigned my pending Issues. Because of in last week I created 7 to 10 Issues only related to YouTube Videos on Both Web Development and Testing Courses. If assigned, I create only two Individual PR's . One PR is on Web Development and Other one is Testing Related? . Kindly taken my Request into Consideration?

Yes you can go ahead with that

**Comment by NarendraKoya999** [comment]
> > @rupali-codes .Who can Assigned my pending Issues. Because of in last week I created 7 to 10 Issues only related to YouTube Videos on Both Web Development and Testing Courses. If assigned, I create only two Individual PR's . One PR is on Web Development and Other one is Testing Related? . Kindly taken my Request into Consideration?
> 
> Yes you can go ahead with that

Thank You @rupali-codes
