### ISSUE TITLE
[Feature] Add search bar in Main Container

### ISSUE THREAD

**Issue by AlfiyaSiddique** [rupali-codes/LinksHub#1354]
### Description

There is no search bar in the main container, so if there are too many resources and tools present in a category as in the case of the Images, Design, and Fonts category of the frontend, then it might get difficult to find a particular resource. 

So to make the finding process easier we should add a search bar in the main container that should search through the resources present in the main container at the time of searching.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@AlfiyaSiddique thanks, i would like to know how are you going to approach this?

**Comment by AlfiyaSiddique** [comment]
Sure @rupali-codes , Here's how I'm gonna achieve it!

First I'll add a search input in the main section that could be in the GeneralLayout component.
Then I'll implement the logic to pass the search input value to the  CardList component
Then using that value I'll filter the card's prop which will render the actual card in the end.

Hence only those tool cards will appear on the screen whose name matches the character entered in the search bar.

Please provide your suggestions if you have any.

**Comment by rupali-codes** [comment]
@AlfiyaSiddique thanks.

**Comment by rupali-codes** [comment]
@k-deepak04 @CBID2 and @Anmol-Baranwal what do you guys about this?

**Comment by k-deepak04** [comment]
yeah, we can go for this

**Comment by Anmol-Baranwal** [comment]
Yeah, the idea is good from what I can understand.

> However, I would like to see the final implementation before suggesting anything.

So, we can definitely go for this.

**Comment by rupali-codes** [comment]
> Yeah, the idea is good from what I can understand.
> 
> > However, I would like to see the final implementation before suggesting anything.
> 
> So, we can definitely go for this.

in the current sidebar, we are searching globally, do we still need it?

**Comment by rupali-codes** [comment]
closing the issue bcz' of inactivity :)
