### ISSUE TITLE
[BUG] Invisible icon

### ISSUE THREAD

**Issue by akanksha984** [rupali-codes/LinksHub#1355]
### Description

![image](https://github.com/rupali-codes/LinksHub/assets/97845909/bc739e5e-903a-41c3-89fd-27c19819f11a)

The icon vanishes on hover. I want to fix this. Please assign this to me under gssoc'23

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
This issue has already been resolved
