### ISSUE TITLE
[Add] data structures video resources   

### ISSUE THREAD

**Issue by anshulsoni4** [rupali-codes/LinksHub#1356]
### Site URL

https://www.youtube.com/playlist?list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA

### Description of the above provided site

whole playlist for learning dsa in c++, here you can learn and solve questions of complex problems  

### Category

Youtube

### Sub Category

Data Structures

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@anshulsoni4 you may start working on it, thanks

**Comment by anshulsoni4** [comment]
thanks

**Comment by anshulsoni4** [comment]
thanks
