### ISSUE TITLE
[ADD] add ui/ux and its resources 

### ISSUE THREAD

**Issue by anshulsoni4** [rupali-codes/LinksHub#1357]
### Category Name

Youtube

### Subcategory Name

UI / UX

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @anshulsoni4! :) Just to confirm, are you participating in GSSOC'23?

**Comment by anshulsoni4** [comment]
> Hi @anshulsoni4! :) Just to confirm, are you participating in GSSOC'23?

hey @CBID2 , yes i am

**Comment by anshulsoni4** [comment]
pls assign !!

**Comment by rupali-codes** [comment]
@anshulsoni4 there you go!

**Comment by anshulsoni4** [comment]
> @anshulsoni4 there you go!

thanks working on this now
