### ISSUE TITLE
[BUG] Searchbar doesn't give unique suggestions and other bugs

### ISSUE THREAD

**Issue by abhijithmuthyala** [rupali-codes/LinksHub#1358]
### Description

1. Searchbar doesn't give unique suggestions.

    Different categories can have common sub-categories (backend/testing and youtube/testing for example). The filtering code here doesn't consider that: https://github.com/rupali-codes/LinksHub/blob/4311806e85b86f935124cb29a1ca1df0e90a8ccc/components/Searchbar/Searchbar.tsx#L37-L40
    As a result, for a given search query, same suggestions are rendered more than once.

    https://github.com/rupali-codes/LinksHub/assets/73361366/c6627f39-61ab-4833-997a-7511fc6118b3

    This also results in the `key`s not being unique, and that reflects in the number of suggestions rendered. There are only 2 'testing' sub-categories, but 5 are rendered in the video.
    https://github.com/rupali-codes/LinksHub/blob/4311806e85b86f935124cb29a1ca1df0e90a8ccc/components/Searchbar/Searchbar.tsx#L101-L109
    
2. Hitting `Enter` doesn't close the suggestions. It is just not handled in the form submit handler. Clicking the search icon works though because of the 'mousedown' handler.
    https://github.com/rupali-codes/LinksHub/blob/4311806e85b86f935124cb29a1ca1df0e90a8ccc/components/Searchbar/Searchbar.tsx#L50-L67

3. The error message rendered when the form is submitted with an empty query isn't removed when the user starts typing a query. I think this is an example of 'impossible state' and should be avoided.

    https://github.com/rupali-codes/LinksHub/assets/73361366/7078f99c-2c54-40b8-a654-f77512e9b13f

4. Closing and re-opening the `SideNavbar` momentarily displays the entire `SideNavbarCategoryList`, not just the ones related to the search query.

    https://github.com/rupali-codes/LinksHub/assets/73361366/d3228b41-652c-4b97-91d8-56f70a7ee331

I'd like work on this. 

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi thanks for catching this up, you may start working on it
