### ISSUE TITLE
you tube link to <data structures>

### ISSUE THREAD

**Issue by dikshapandey08** [rupali-codes/LinksHub#1359]
### Site URL

https://www.youtube.com/watch?v=AT14lCXuMKI&list=PLdo5W4Nhv31bbKJzrsKfMpo_grxuLl8LU&pp=iAQB

### Description of the above provided site

This is a free YouTube Playlist, beginner friendly. Having 112 videos covering almost every topic in DSA.

### Category

Youtube

### Sub Category

YouTube links 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@dikshapandey08 you may start working on this :)

**Comment by Anmol-Baranwal** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen it if you'd like to contribute or have further discussions.
