### ISSUE TITLE
[Add] <name> DSA playlist in Python

### ISSUE THREAD

**Issue by Pro-18** [rupali-codes/LinksHub#1367]
### Site URL

https://www.youtube.com/playlist?list=PLrk5tgtnMN6TYBW0-U4YhIRyYEVpqVEnJ

### Description of the above provided site

Data Structures and Algorithms form the backbone of computer science and software development. These topics are vital for any programmer aiming to excel in the industry. As Python is a widely used language in the tech industry a dedicated playlist on these topics in Python would be a valuable addition.

### Category

Youtube

### Sub Category

Data Structures

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
You may start working on it
