### ISSUE TITLE
[Add] want to create new section of BOOTSTRAP

### ISSUE THREAD

**Issue by Sushilverma002** [rupali-codes/LinksHub#1370]
### Description

I would like to add new section of BOOTSTRAP in frontend  one . 
where it contain information with there links.
@CBID2 have a look.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/114687502/6916f7fb-828b-4e18-b0de-95eb6f45271a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @Sushilverma002
