### ISSUE TITLE
[ADD] Add DevOps and its Resources

### ISSUE THREAD

**Issue by ighoshsubho** [rupali-codes/LinksHub#1371]
### Category Name

DevOps

### Subcategory Name

DevOps

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@ighoshsubho thanks, you may start  working on it :)

**Comment by CBID2** [comment]
Any updates @ighoshsubho?

**Comment by ighoshsubho** [comment]
Working on it! Curating lot of DevOps content. @CBID2

**Comment by CBID2** [comment]
> Working on it! Curating lot of DevOps content. @CBID2 

Great @ighoshsubho, but not too much though. It can get overwhelming for us maintainers when we review the PRs.

**Comment by ighoshsubho** [comment]
> > Working on it! Curating lot of DevOps content. @CBID2
> 
> Great @ighoshsubho, but not too much though. It can get overwhelming for us maintainers when we review the PRs.

Ok sure @CBID2. Will make a PR by today or tomorrow. Thanks.
