### ISSUE TITLE
Making Background Colors Accessible Part 2

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1372]
I'm thinking to configure all the colors in tailwing.config file, it would be so helpful for us. then you can change it directly. So, should i work on that, bcz its gonna be a bit difficult for you to find where the components are located. @k-deepak04 or @CBID2 you guys can create an issue for it, and assign to me, i'll work on that :)
> 

_Originally posted by @rupali-codes in https://github.com/rupali-codes/LinksHub/issues/1045#issuecomment-1646640103_

**Comment by rupali-codes** [comment]
Thanks Chrissy!
