### ISSUE TITLE
[Add] <write what you want to add>

### ISSUE THREAD

**Issue by karthiknadar1204** [rupali-codes/LinksHub#1374]
### Site URL

https://www.youtube.com/watch?v=v02P0AsTm2o&list=PLt5mNkGuWcuWSUHxSzWP74IU9U4BTVLt0&ab_channel=6PackProgrammer

### Description of the above provided site

Add more resources for react js by 6 pack programmer

### Category

Frontend

### Sub Category

designing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @karthiknadar1204
