### ISSUE TITLE
[Add] Add resources for data structures and algorithms

### ISSUE THREAD

**Issue by karthiknadar1204** [rupali-codes/LinksHub#1375]
### Site URL

https://www.youtube.com/watch?v=rZ41y93P2Qo&list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ&ab_channel=KunalKushwaha

### Description of the above provided site

Want to add dsa playlist by kunal kushwaha

### Category

Youtube

### Sub Category

Data structures

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@karthiknadar1204 you may start working on it, thanks
