### ISSUE TITLE
[Feature] using useSWR (react hook) to fetch data

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1376]
### Description

Use of useSWR:

We can consider using useSWR for fetching the data in this case. useSWR is a React hook for data fetching that simplifies the process and handles caching, revalidation, and error handling out of the box. It can improve the performance by caching the data on the client-side and automatically updating it when needed.

Reference: https://swr.vercel.app/

> To use in `contributors.tsx`

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal why we would use it exactly?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal why we would use it exactly?

The primary goal of `useSWR` is to provide a better user experience by optimizing the way data is fetched, cached, and updated in the application through sophisticated built-in techniques. I have also provided a reference.

**Comment by rupali-codes** [comment]
@k-deepak04 what do you think about it?

**Comment by Anmol-Baranwal** [comment]
Closing this. Present one works fine, and we will use this when there is a proper backend.
