### ISSUE TITLE
[Feature] remove autofill in search query field

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1378]
### Description

As shown in the image, the suggestions are already visible, making it unnecessary and resulting in a bad user experience due to the overlap.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/6f501cd4-348d-4d0c-ac3c-c137a9cff44a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal that would be nice!
