### ISSUE TITLE
[Feature] update styling of social icons

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1379]
### Description

There are two changes that I think are necessary:

1. The GitHub Icon hover color is clearly not suitable for the dark mode, and in the light mode, it doesn't change at all.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/dd2723f9-7920-4821-ba36-22d6deca6caf)

2. Since there is already a tooltip, we can make hover effects according to the theme.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/42d53cf4-cf11-44e8-b6bb-cda0ba8e6800)

> Let me know which change you believe is good.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
This issue was fixed ig, as we have changed back the hover color to _violet_

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/9d6653f4-6689-4536-929d-602f56a9f717)
