### ISSUE TITLE
[Add] <Free3Dicon to the Frontend/Icons category>

### ISSUE THREAD

**Issue by AhorIsaac** [rupali-codes/LinksHub#1382]
### Site URL

https://free3dicon.com/

### Description of the above provided site

We need to add Free3Dicon to the frontend/icons category. Free3Dicon offers a collection of free, beautiful, trending 3D icons, that you can use in your website, app or in any project.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@AhorIsaac you may start working on this
