### ISSUE TITLE
[Add] : Add "Sublime  Text" Online Code Editor in online-code-editors.astro File in Frontend Category

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1383]
### Site URL

https://www.sublimetext.com/

### Description of the above provided site

- Add "Sublime Text"  Online Code Editor in online-code-editors.astro File in Frontend Category.
- Sublime Text supports various languages such as C, C++, Java, JavaScript, HTML, CSS, Python, Ruby, and more. It also provides syntax highlighting and code completion for multiple languages

### Category

Frontend

### Sub Category

online-code-editors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned now @NarendraKoya999
