### ISSUE TITLE
[Add]: Add GraphQL Website Details Link in Database Sub Category in Backend Main Category

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1384]
### Site URL

https://graphql.org/

### Description of the above provided site

- Add GraphQL Website Details Link in Database Sub Category in Backend Main Category
- GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data.
-  GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more, makes it easier to evolve APIs over time, and enables powerful developer tools.

### Category

Backend

### Sub Category

database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @NarendraKoya999
