### ISSUE TITLE
[Add] : Add Python Official Docs in Official Docs Sub Category in Resources Main Category

### ISSUE THREAD

**Issue by NarendraKoya999** [rupali-codes/LinksHub#1385]
### Site URL

https://www.python.org/doc/

### Description of the above provided site

- Add Python Official Docs in Official Docs Sub Category in Resources Main Category

### Category

Resources

### Sub Category

official-docs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @NarendraKoya999
