### ISSUE TITLE
[ADD] Roadmaps

### ISSUE THREAD

**Issue by AbhishekPSingh07** [rupali-codes/LinksHub#1387]
### Category Name

RoadMaps

### Subcategory Name

For Frontend Developer ,Backend Developer,Devops,Android Developer

### Additional Context

It would be a great start for people confused on how to get started if they want to become a certain type of developer a proper roadmap would be a good way to guide them. You can check [roadmap.sh it ](https://roadmap.sh/).

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @AbhishekPSingh07! :) Just to confirm, are you participating in GSSOC'23?

**Comment by AbhishekPSingh07** [comment]
Yes

**Comment by AbhishekPSingh07** [comment]
Yes

**Comment by CBID2** [comment]
You're assigned @AbhishekPSingh07

**Comment by rupali-codes** [comment]
@AbhishekPSingh07 any updates?

**Comment by AbhishekPSingh07** [comment]
Will file a pr tommorow

**Comment by rupali-codes** [comment]
> Will file a pr tommorow

Alright, thanks

**Comment by Anmol-Baranwal** [comment]
@AbhishekPSingh07 
Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

**Comment by Suraj-kumar00** [comment]
Hi @Anmol-Baranwal, My name is Suraj and I'm learning Frontend development and worked with an e-commerce brand there I created some pages that use tech stack like HTML, CSS, js, react, git, and GitHub, and I'm also a DevOps enthusiast.
So I have knowledge in frontend development and learning DevOps practices.
I write technical blogs at Hashnode on what I learn.
Can I contribute to this issue?

**Comment by Anmol-Baranwal** [comment]
@Suraj-kumar00 
You don't need to provide any specific details to get assigned to an issue. 😅 Just ask, and we'll take care of it.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by Suraj-kumar00** [comment]
thanks for Assigning it to me, I'll definitely ask you questions whenever I get stuck.

**Comment by rupali-codes** [comment]
> thanks for Assigning it to me, @Anmol-Baranwal I want to add roadmaps for frontend and DevOps with the best resources. So can like guide me on how to do so I have forked the repo and did all the steps now I have to add roadmaps for these two domains , and now I have to make changes but where in the file? you said that ask without hesitation !!!

Hi, it would be great if you can rise a draft PR so we can guide you further more efficiently.

**Comment by Anmol-Baranwal** [comment]
> thanks for Assigning it to me, @Anmol-Baranwal I want to add roadmaps for frontend and DevOps with the best resources. So can like guide me on how to do so I have forked the repo and did all the steps now I have to add roadmaps for these two domains , and now I have to make changes but where in the file? you said that ask without hesitation !!!

Of course! Feel free to tag me whenever you face any problem. 

First of all, if you are new to Git & GitHub. Go through this flow: https://docs.github.com/en/get-started/quickstart/github-flow

Follow this to fork and setup codebase locally: https://github.com/rupali-codes/LinksHub#lets-jump-right-in

Then read contributing guidelines in the repository: https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md

> The contributing guidelines guide contributors on how they can contribute to the repository.

You would have to add a category of Roadmaps, and then just add it as per the JSON data. 

@rupali-codes 
What do you think?

Do you want to add something.

**Comment by Suraj-kumar00** [comment]
Hi @Anmol-Baranwal yeah, I've gone through all the steps that you talked about here.
And okay I'll create a separate category of roadmaps like there is a DevOps category in the database folder right?
And @rupali-codes I'm creating a draft PR.

**Comment by Anmol-Baranwal** [comment]
I will check it soon.

**Comment by rupali-codes** [comment]
> Hi @Anmol-Baranwal yeah, I've gone through all the steps that you talked about here. And okay I'll create a separate category of roadmaps like there is a DevOps category in the database folder right? And @rupali-codes I'm creating a draft PR.

alright, thanks. Please let us know if you need any kinda help :)
