### ISSUE TITLE
Visit site buttons

### ISSUE THREAD

**Issue by KarolSongin** [rupali-codes/LinksHub#14]
Hello,

Visit site buttons are not working and they are also an HTML button element but should be as best practice should be a tags.

![image](https://user-images.githubusercontent.com/88238022/212534107-30937f58-e4de-4a57-9863-b6f4f0ed9079.png)

**Comment by hparashar27** [comment]
hey , can you please assign it to me

**Comment by KarolSongin** [comment]
@hparashar27  FYI there is a PR related to this issue #15

**Comment by rupali-codes** [comment]
Hi @hparashar27, i'm glad to see you wanting to contribute. you can create issue(s) related to suggestions, feedbacks, bugs or any improments you need in site, and also feel free to rise PR. I'd love to have you

**Comment by AdekeyeAdeniyi** [comment]
Am available.
