### ISSUE TITLE
[CHORE] add new category YouTube

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#140]
### What would you like to share or ask?

Now we are going add one more `category` which is `YouTube` and in there we will having different `subcategories` such as `web developement` `DSA` `Machine Learning` etc.

#### changes needs to be done
1. add new `Category` called `youtube` in `types/index.ts` file
2. add at least 2 subcategories in `SubCategory` in `types/index.ts` file
3. update `database/data.ts` to add route/s pointing to `subcategory`
4. (optional) add Links to channels for testing

**Comment by Radiant690** [comment]
Hello, @rupali-codes  is this issue still open. If so could you provide more information I would love to try it out?

**Comment by rupali-codes** [comment]
> Hello, @rupali-codes is this issue still open. If so could you provide more information I would love to try it out?

Yes, you can start working on this
