### ISSUE TITLE
[Feature] remove search bar from scrollable area

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1418]
### Description

> For better clarity of the idea, see [here](https://jam.dev/c/96a311aa-681c-42d7-b9e7-335c24e3faeb)

Avoiding this would have several benefits including the emphasis of easy searching.

> Search bar is scrollable
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/dcdb4572-5592-4787-b9dd-f79997086ca7)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@CBID2 it should be `level 2`

**Comment by Anmol-Baranwal** [comment]
This could be considered as level 3 if you gauge it based on the impact it has, rather than the amount of code. Just to be clear, I am not arguing😅
