### ISSUE TITLE
[Feature] update contributing guidelines

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1419]
### Description

- Update the guidelines to ask contributors to add descriptions while adding new subcategories.
- As shown in the image below, it is vacant, which seems strange. Adding a small description at the same time of adding a new subcategory would save us the hassle of adding remaining descriptions.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/04593924-41f9-4317-b701-7bf29c8fe397)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Good idea @Anmol-Baranwal! :)
