### ISSUE TITLE
[BUG] improve sidebar to make elements visually accessible

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1420]
### Description

@rupali-codes @CBID2 

I believe this issue is important, so I am going to submit a PR by tomorrow. Let me know what you think.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/236578b0-4e94-48d8-b553-079fa415f3b2)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
I agree. Go right ahead @Anmol-Baranwal
