### ISSUE TITLE
[BUG] update share link with appropriate route URL

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1421]
### Description

The current share link gives us this link: https://gdg.community.dev/, which is not appropriate. 

I would like to update it with the proper URL from the route that the user is currently on.

> I don't understand why this is being given as a shared link.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Go ahead @Anmol-Baranwal
