### ISSUE TITLE
[Feature] improve visual distinction between top bar and cards

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1422]
### Description

As shown in the image, there is no clear distinction between cards and top bar in large devices.

What do you think?

### Screenshots

> Large Devices

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/d9f75cbc-b36f-479e-b575-658de65a66e4)

> Medium Devices
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/7bd91f63-3f6d-414b-a55a-3ee1fd5414a1)

> Small Devices
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5ec6aa75-e293-4d89-b63d-c25f4ef7e32e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
lgtm, you can start working on this

**Comment by chris-nowicki** [comment]
I'd love to take this issue if nobody is working it?

**Comment by Anmol-Baranwal** [comment]
Hi @chris-nowicki,

Certainly, I had planned to address this issue in the future. However, it would be greatly appreciated if you could contribute to resolving this issue.

I have assigned the issue to you. Kindly proceed with it, and don't hesitate to tag me if you need any assistance.

**Comment by chris-nowicki** [comment]
Thank You, @Anmol-Baranwal! I'll for sure reach out if I need anything.
