### ISSUE TITLE
[Add] codrops in animation section

### ISSUE THREAD

**Issue by Akanksha-202** [rupali-codes/LinksHub#1429]
### Site URL

https://tympanus.net/codrops/

### Description of the above provided site

A web design and development blog with tutorials and examples of creative animations and interactions.

### Category

Frontend

### Sub Category

animations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi @Akanksha-202 you may work on this :)

**Comment by Anmol-Baranwal** [comment]
@Akanksha-202 
Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

**Comment by Akanksha-202** [comment]
Created PR! @Anmol-Baranwal
