### ISSUE TITLE
[Add] colorSpace to colors category

### ISSUE THREAD

**Issue by Akanksha-202** [rupali-codes/LinksHub#1430]
### Site URL

https://mycolor.space/

### Description of the above provided site

Explore various color palettes and gradients for web design and other creative projects.

### Category

Frontend

### Sub Category

Colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @Akanksha-202
