### ISSUE TITLE
[Add] zuno community link

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1435]
### Site URL

https://t.me/zunobyfoundit

### Description of the above provided site

Official Channel

Your go-to place for internships & fresher jobs that are verified and pay well

Be a community leader.  

### Category

Other

### Sub Category

communitites

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Done @S-ishita
