### ISSUE TITLE
[Add] KNOWLEDGE GATE  Youtube channel for computer-science

### ISSUE THREAD

**Issue by deveshgoyal1000** [rupali-codes/LinksHub#1436]
### Site URL

https://www.youtube.com/@KNOWLEDGEGATE_kg/about

### Description of the above provided site

KNOWLEDGE GATE is YouTube channel for core computer-science subjects and helps CS/IT students to prepare for University/semester and also for GATE Exams  

### Category

Youtube

### Sub Category

computer-science

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @deveshgoyal1000! :) In the future, please don't create a PR before the issue has been approved. We want to make sure that it fits in with LinksHub.

**Comment by deveshgoyal1000** [comment]
@CBID2 
ohky :)

**Comment by CBID2** [comment]
> @CBID2 
> 
> ohky :)
> 
> 

You're in GSSOC right?

**Comment by deveshgoyal1000** [comment]
@CBID2 yeah
