### ISSUE TITLE
[Add] open source blog link

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1439]
### Site URL

https://sulagnaduttaro.hashnode.dev/open-source-a-beginner-guide-2022

### Description of the above provided site

Learn about open source. A complete guide to beginner's open source journey...

### Category

Open Source

### Sub Category

blogs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Done @S-ishita
