### ISSUE TITLE
[Add] AI Student community link

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1441]
### Site URL

https://aistudent.community/

### Description of the above provided site

An online community for students from all across the country, providing a platform for learning, sharing experiences and leveraging their knowledge to create AI-enabled social impact solutions along with spreading AI awareness in an inclusive way.

### Category

Other

### Sub Category

communitites

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
