### ISSUE TITLE
[Add] codenewbie podcast

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1443]
### Site URL

https://www.codenewbie.org/podcast

### Description of the above provided site

The CodeNewbie Podcast is for — you guessed it — people new to coding! Host Saron Yitbarek interviews a new guest every week, and they talk about their coding journey, how they landed their first coding job, and more.

### Category

Other

### Sub Category

podcast

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
