### ISSUE TITLE
[Feature] Want to add Fully Functional Next Auth Authentication using Prisma & MongoDB 

### ISSUE THREAD

**Issue by crocmons** [rupali-codes/LinksHub#1445]
### Description

Hello! I would like to request to be assigned the task of adding Fully Functional Next Auth Authentication using Prisma & MongoDB. I am eager to contribute to GSSOC23 as a contributor. Thank you!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned now @crocmons

**Comment by CBID2** [comment]
Just to clarify, this is a resource link you want to add to LinksHub?

**Comment by crocmons** [comment]
> Just to clarify @crocmons, this is a resource link you want to add to LinksHub?
Actually, I would like to integrate a sign-up and login page into your website using Next Auth.

**Comment by CBID2** [comment]
Ah ok @crocmons! How can this feature enhance LinksHub?

**Comment by crocmons** [comment]
> Ah ok @crocmons! How can this feature enhance LinksHub?

NextAuth.js is a powerful authentication library that provides easy integration with various authentication providers and makes it convenient to implement authentication in a web application. By integrating NextAuth.js into LinksHub, you can enhance the platform in several ways:

1. Secure User Authentication: NextAuth.js provides a secure and reliable way to handle user authentication. It supports authentication with various providers like Google, Facebook, GitHub, etc., ensuring that users can log in using their preferred accounts without having to create new credentials for LinksHub.

2. Social Logins: With NextAuth.js, you can enable social logins, allowing users to sign in using their existing social media accounts. This simplifies the registration process for new users and encourages them to join the platform.

3. Single Sign-On (SSO): NextAuth.js allows you to implement Single Sign-On, enabling users to access multiple applications or services within your ecosystem with a single set of login credentials. This improves user experience and reduces the hassle of remembering multiple passwords.

4. Access to User Data: NextAuth.js provides access to user data, such as their name, email, and profile picture, obtained from the authentication provider. This data can be used to personalize the user experience and display relevant information on their dashboard.

5. Secure Sessions and Tokens: NextAuth.js handles session management and provides secure tokens for authentication, ensuring that user sessions are protected against common security threats like CSRF attacks.

6. Scalability and Performance: By delegating the authentication process to NextAuth.js, you offload the authentication load from your server, making it more scalable and improving overall application performance.

7. Flexibility: NextAuth.js supports multiple authentication providers and allows you to choose the ones that best fit your user base. This flexibility makes it easier to cater to the preferences of different users.

8. Passwordless Authentication: NextAuth.js supports passwordless authentication methods like Magic Links, making it easier and more secure for users to log in without having to remember passwords.

Overall, integrating NextAuth.js into LinksHub can enhance the user experience, improve security, and provide a seamless authentication process, which is crucial for any web platform aiming to attract and retain users.

**Comment by CBID2** [comment]
> > Ah ok @crocmons! How can this feature enhance LinksHub?
> 
> @CBID2 
> 
> 
> 
> NextAuth.js is a powerful authentication library that provides easy integration with various authentication providers and makes it convenient to implement authentication in a web application. By integrating NextAuth.js into LinksHub, we can enhance the platform in several ways:
> 
> 
> 
> 1. Secure User Authentication: NextAuth.js provides a secure and reliable way to handle user authentication. It supports authentication with various providers like Google, Facebook, GitHub, etc., ensuring that users can log in using their preferred accounts without having to create new credentials for LinksHub.
> 
> 
> 
> 2. Social Logins: With NextAuth.js, you can enable social logins, allowing users to sign in using their existing social media accounts. This simplifies the registration process for new users and encourages them to join the platform.
> 
> 
> 
> 3. Single Sign-On (SSO): NextAuth.js allows you to implement Single Sign-On, enabling users to access multiple applications or services within your ecosystem with a single set of login credentials. This improves user experience and reduces the hassle of remembering multiple passwords.
> 
> 
> 
> 4. Access to User Data: NextAuth.js provides access to user data, such as their name, email, and profile picture, obtained from the authentication provider. This data can be used to personalize the user experience and display relevant information on their dashboard.
> 
> 
> 
> 5. Secure Sessions and Tokens: NextAuth.js handles session management and provides secure tokens for authentication, ensuring that user sessions are protected against common security threats like CSRF attacks.
> 
> 
> 
> 6. Scalability and Performance: By delegating the authentication process to NextAuth.js, you offload the authentication load from your server, making it more scalable and improving overall application performance.
> 
> 
> 
> 7. Flexibility: NextAuth.js supports multiple authentication providers and allows you to choose the ones that best fit your user base. This flexibility makes it easier to cater to the preferences of different users.
> 
> 
> 
> 8. Passwordless Authentication: NextAuth.js supports passwordless authentication methods like Magic Links, making it easier and more secure for users to log in without having to remember passwords.
> 
> 
> 
> Overall, integrating NextAuth.js into LinksHub can enhance the user experience, improve security, and provide a seamless authentication process, which is crucial for any web platform aiming to attract and retain users.

Interesting. @rupali-codes, do you think this idea can fit in the forms feature you've been working on?

**Comment by rupali-codes** [comment]
Sorry for seeing it too late. @crocmons Are u still willing to contribute?

**Comment by crocmons** [comment]
yeap

**Comment by rupali-codes** [comment]
@k-deepak04 and @Anmol-Baranwal what do you think about this?

**Comment by Anmol-Baranwal** [comment]
It totally depends on how you want the project to grow. So, it's up to you, @rupali-codes . Either option is fine, and this has better future potential.

**Comment by rupali-codes** [comment]
> It totally depends on how you want the project to grow. So, it's up to you, @rupali-codes . Either option is fine, and this has better future potential.

what are we going to do with authentication exactly?

**Comment by Anmol-Baranwal** [comment]
I don't know, you would have to handle stuff. Or maybe create detailed issues, and add label `help wanted`. It will directly display in various filter websites, that can maybe attract a worthy contributor.

**Comment by crocmons** [comment]
Ah well, I guess you didn't need it & right now I don't have enough time to contribute on this issue...so I just closed @rupali-codes

**Comment by Anmol-Baranwal** [comment]
@crocmons,

You haven't made any commits in the past month. It would have been helpful to know earlier if you didn't plan to complete the work during this time. Someone else might have been able to take over. It's not considered good etiquette, in my opinion, to solely work for GSSoC'23.

Thank you for informing us regardless.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/23179910-e846-48b6-899c-46a75ebb86f4)


@rupali-codes,

Let's make sure to check and open inactive issues after one week for others to grab.

**Comment by crocmons** [comment]
@Anmol-Baranwal, could you please repeat what you said? This is my first issue on Linkshub and it seems like no one is interested in adding authentication. Please refer to the previous messages for a better understanding of what I'm saying.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal, sorry but I didn't understand what you said. This is my first issue on Linkshub and it seems like no one is interested in adding authentication. Please refer to the previous messages for a better understanding of what I'm saying. and one last thing I never work for only GSSOC points..I only make meaningful contributions...thanks

I'm sorry if you were hurt by any of my statements. I'm not here to argue, so let's not continue the discussion. 

I'm opening the issue for others to take on. Thank you for your valuable time, @crocmons.
