### ISSUE TITLE
How about adding Animations to the project 

### ISSUE THREAD

**Issue by Souravvmishra** [rupali-codes/LinksHub#1446]
### Description

- Animation can **attract and retain** the attention of your visitors, making them more likely to explore your site and learn about your products or services
- Animation can **enhance your brand identity** and create a memorable impression on your audience. 
- Animation can **increase user engagement** and interaction. 
- Animation can **improve user experience** and navigation. 
- Animation can **boost conversion rates** and sales. 
- Animation can **increase social media shares** and viral potential. 
- Animation can **educate and inform** your audience. 
- Animation can **entertain and delight** your audience. 
- Animation can **set you apart from the competition** and make you stand out. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi, thanks, what kind of animations do you want to add?

**Comment by Souravvmishra** [comment]
Using Framer Motion To Let The Texts & Images Come In An Animated way. Can share a demo if assigned.


Animated Sites create a better user experience by adding sort of Interactivity.

**Comment by Souravvmishra** [comment]
https://projectshut.vercel.app/ 

This is one of the site I have animated.
please check @rupali-codes

**Comment by rupali-codes** [comment]
> https://projectshut.vercel.app/
> 
> This is one of the site I have animated. please check @rupali-codes

I see, we don't have this kind of pages, so how you gonna animations in there?

**Comment by Anmol-Baranwal** [comment]
@Souravvmishra 
Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

**Comment by Anmol-Baranwal** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen it if you'd like to contribute or have further discussions.
