### ISSUE TITLE
Adding A CTA Button & Making The Sidebar Take Full Space 

### ISSUE THREAD

**Issue by Souravvmishra** [rupali-codes/LinksHub#1448]
### Description

So, If we add a CTA button in the landing page, We can enforce user to click it and thereafter make the sidebar takes full space So it appears as the main component and not just a side bar. 

Instead we can also create a new page to display categories. 

We need this as because of human psychology, we have been trained to take sidebar as a non important component but our project's main focus is the sidebar. 

A refactoring is necessary 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Sounds interesting @Souravvmishra. @rupali-codes, what do you think of this?

**Comment by Souravvmishra** [comment]
@CBID2 @rupali-codes Should I Start Working In This?

**Comment by rupali-codes** [comment]
> @CBID2 @rupali-codes Should I Start Working In This?

Sorry for taking too long, yes you can start working on this issue :)
