### ISSUE TITLE
[Refactor]: search bar typescript code with best practices 🪄✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#1450]
### File Name

hooks/useSidebarSearch.ts

### Reason for Refactoring the Code

- This issue aims to refactor the `useSidebarSearch.ts` script to improve code maintainability, readability, and type safety.
- We want to provide Descriptive variable names, Destructuring and Simplifiying the Code, Etc.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

**Comment by 0xabdulkhalid** [comment]
Hey there @rupali-codes, @CBID2, @ujjawaltyagii, @Anmol-Baranwal 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank you!

**Comment by CBID2** [comment]
You're assigned @0xabdulkhalid
