### ISSUE TITLE
[Add] Add Official Docs for Ember.js

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1452]
### Site URL

https://guides.emberjs.com/release/

### Description of the above provided site

Ember.js is a productive, battle-tested JavaScript framework for building modern web applications. It includes everything you need to build rich UIs that work on any device.

### Category

Frontend

### Sub Category

Offcial Docs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Nishitbaria you can start working on this issue :)
