### ISSUE TITLE
[Add] Add Official Docs for Laravel

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1453]
### Site URL

https://laravel.com/

### Description of the above provided site

Laravel is a web application framework with expressive, elegant syntax. We’ve already laid the foundation — freeing you to create without sweating the small things.

### Category

Backend

### Sub Category

official backend 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Nishitbaria you can work on this too, as the gssoc'23 endline is close, but please make sure that commits remains spareted
