### ISSUE TITLE
[Add] GATE Wallah YouTube channel for computer-science

### ISSUE THREAD

**Issue by deveshgoyal1000** [rupali-codes/LinksHub#1455]
### Site URL

https://www.youtube.com/@GATEWallah_EE_EC_CS

### Description of the above provided site

GATE Wallah YouTube channel for computer-science core subjects. This channel is helpful for students who are preparing for gate exam.

### Category

Youtube

### Sub Category

computer-science

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @deveshgoyal1000
