### ISSUE TITLE
[DOCS] Adding a "Table on content" in the readme to make it easier to navigate

### ISSUE THREAD

**Issue by 1Shubham7** [rupali-codes/LinksHub#1459]
### Issue Description

We must add a "Table of content" in the readme of the project to make it easier to navigate and more professional.

An example would be ->

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/116020663/5128f19d-30f0-4c61-accb-8656cdfbb841)

### Additional Context

Please assign me this issue under GSSoC'23

### Screenshots or Examples (if applicable)

added above

### Proposed Solution (optional)

Creating a table of content

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
That would be helpful @1Shubham7! :) You're officially assigned
