### ISSUE TITLE
[OTHER] <Padding issue in card>

### ISSUE THREAD

**Issue by SoniBasant** [rupali-codes/LinksHub#146]
### What would you like to share or ask?

The padding of card in COLORS section is not good in "Color Contract Checker".  The button "Visit Site" is downwards. Need to correct. My Browser:-  Chrome
![Screenshot 2023-02-06 201253](https://user-images.githubusercontent.com/94775800/217042438-1673b598-9205-4e73-86cb-617a6f9cb93b.jpg)

### Additional information

This is my first issue. Hope this is going to be accepted and get resolved. : )

**Comment by rupali-codes** [comment]
@SoniBasant Thank you so much. Are you willing to work on this?

**Comment by SoniBasant** [comment]
Yes I am willing to work on this. As this is my first time on open source, so may be I will take some time but I will resolve this issue.

**Comment by pramodreddypandiri** [comment]
Hello, as "Color Contrast Checker" is taking up more space "Visit Site" button moved down. Can we just use "overflow" on card or card title to fix this.
I do not know if we can have uniform card size and not use 'overflow'.

**Comment by rupali-codes** [comment]
@SoniBasant any updates?

**Comment by pramodreddypandiri** [comment]
I think I asked a question and expecting a answer.

**Comment by rupali-codes** [comment]
> I think I asked a question and expecting a answer.

@pramodreddypandiri yeah, just noticed it was fixed the way you said
![image](https://user-images.githubusercontent.com/78981177/218243181-18845197-a75b-4153-8537-6f8c9a01e0c6.png)

Or do you have any suggestions for this?

**Comment by pramodreddypandiri** [comment]
Ok,they used class "truncate". Looks good for now .
No suggestions from my side.

**Comment by rupali-codes** [comment]
Alright, thanks
