### ISSUE TITLE
[Add] <Icons-Icons>

### ISSUE THREAD

**Issue by AhorIsaac** [rupali-codes/LinksHub#1460]
### Site URL

https://icon-icons.com/

### Description of the above provided site

Icon-Icons is an online platform or website that provides a collection of icons for use in web design, graphic design, and other digital projects.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @AhorIsaac
