### ISSUE TITLE
[Refactor] fix warning error as per official docs

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1461]
### File Name

pages/_document.tsx

### Reason for Refactoring the Code

> Warning
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/1903a0fb-9cc6-448f-b7d2-02194f959bb8)

Docs Reference: https://nextjs.org/docs/messages/no-title-in-document-head

I will refactor other parts of `document.tsx`.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

**Comment by CBID2** [comment]
You're assigned @Anmol-Baranwal
