### ISSUE TITLE
[BUG] Correct styling for consistent gap in popup description

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1468]
### Description

It may not be visible, but I think there is inconsistent gaps between the texts. Let me know if this is a issue. I have checked few others, which seem alright.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/4814732f-8171-4456-9671-6104d618a9ce)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @Anmol-Baranwal. I don't see this as a significant problem since the content looks legible. What do you think @rupali-codes?

**Comment by Anmol-Baranwal** [comment]
> Hey @Anmol-Baranwal. I don't see this as a significant problem since the content looks legible. What do you think @rupali-codes? 

Yeah, change won't impact much. I even checked at different locations, and it was okay.
