### ISSUE TITLE
[OTHER] Improve folder/files structure

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1470]
### What would you like to share or ask?

Hi, i want to improve the folder and files structure. It seems a little inconsistent that some components have an _index.tsx_ file and some doesn't. I wanna remove the _index.tsx_ for each folder so that would make the structure more clear.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
That's a good idea @rupali-codes! :) Let me know when you're ready so I can help you! :)

**Comment by rupali-codes** [comment]
@CBID2, i'll be working on this today, let me know when u are available on discord

**Comment by CBID2** [comment]
> @CBID2, i'll be working on this today, let me know when u are available on discord

Ok
