### ISSUE TITLE
[BUG] Static generation only generates a `Spinner`, not the actual content

### ISSUE THREAD

**Issue by abhijithmuthyala** [rupali-codes/LinksHub#1477]
### Description

Initial load of the pages at  `/` and `/[category]` routes render just the `Spinner` component, not the actual content of that page. This defeats the purpose of using the framework Next.js in the first place and is bad for SEO.

Here is the issue. Since we are only returning the `Spinner` on initial load, the content doesn't show up in the statically generated pages.

https://github.com/rupali-codes/LinksHub/blob/0830451643de35579d7998c6d147da355b1f42cc/components/Loader/Preloader.tsx#L14-L22

This should fix it.
```js
const { showLoader} = useLoader() 

return (
  <>
    {children}
    {showLoader && (
      <div
        className={`loader ${backgroundColor} fixed top-0 left-0 w-full h-screen flex justify-center items-center`}
      >
        <Spinner {...rest} />
      </div>
    )}
  </>
)
```

Also, to statically generate the dynamic `/[category]` routes, `getStaticPaths` and `getStaticProps` will have to be used. 

I'd like to implement this.

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/73361366/24d65f44-c17f-4151-96cb-4e4db9c297d6

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You are assigned @abhijithmuthyala
