### ISSUE TITLE
[Feature]: Implement "Prefers Reduced Motion" Media Feature for Enhanced Accessibility 🪄✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#1478]
### Description

- We have a fantastic opportunity to enhance the accessibility of our project by implementing the "Prefers Reduced Motion" media feature. 
- This feature caters to users who experience motion sensitivity or discomfort, ensuring a more comfortable and inclusive user experience.

### What is "Prefers Reduced Motion"?

- "Prefers Reduced Motion" is a media feature in CSS that detects users' preferences for reduced animations and motion effects. When enabled, it informs the website that the user prefers a more static and less animated interface.

### Why Implement "Prefers Reduced Motion"?

- **Enhanced User Comfort**: By respecting users' motion preferences, we create a more enjoyable experience for those who may find motion-heavy interfaces uncomfortable or disorienting.

- **Improved Accessibility**: Supporting "Prefers Reduced Motion" aligns with our commitment to inclusivity, making our project more accessible to users with diverse needs.

- **Compliance with Best Practices**: Implementing this feature demonstrates our dedication to following web accessibility standards, fostering a positive and inclusive digital environment.

### How Does It Work?

- The media feature is used in CSS to apply specific styles when a user prefers reduced motion. This may involve reducing animation durations, disabling certain transitions, or creating static backgrounds.

### Let's Prioritize Accessibility
- At the heart of our project is a commitment to accessibility. By adding the "Prefers Reduced Motion" feature, we can create an environment where everyone can engage with our content comfortably.

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/92252895/bbbc9d78-a1ad-4b9b-a162-de9c62a1817a

[Sample working video to demonstrate the motion reducing feature]

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @rupali-codes, @CBID2, @k-deepak04, @Anmol-Baranwal 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank you!

**Comment by CBID2** [comment]
This seems convincing. @rupali-codes, what do you think?

**Comment by 0xabdulkhalid** [comment]
@CBID2 this feature is important for the user's who experience motion sensitivity or discomfort, This will adapt to the user's preference.

If the user disabled the animations on their settings then the site also play animations.

This will improve inclusively improve the User's experience, because they want to decide to enable and disable the animations. By adding this feature the user can able to decide that part of their own.

Otherwise the animations, transitions all effects will play for user who experience discomfort for it.

Let me know you thoughts!

**Comment by CBID2** [comment]
> @CBID2 this feature is important for the user's who experience motion sensitivity or discomfort, This will adapt to the user's preference.
> 
> 
> 
> If the user disabled the animations on their settings then the site also won't play animations.
> 
> 
> 
> This will inclusively improve the User's experience, because they want to decide to enable and disable the animations. By adding this feature the user can able to decide that part of their own.
> 
> 
> 
> Otherwise the animations, transitions all effects will play for user who experience discomfort for it.
> 
> 
> 
> Let me know you thoughts!

Well, accessibility is important 🤔. Ok...let's do it
