### ISSUE TITLE
[Refactor]: Share and Copy Button Components for Improved Accessibility ⚒️✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#1479]
### File Name

components/Share/Share.tsx & components/CopyToClipboard/CopyToClipboard.tsx

### Reason for Refactoring the Code

- Let's take the accessibility of our project to the next level by refactoring both the Share and Copy buttons used in the same component. 
- This refactoring aims to improve the user experience for all users, including those with disabilities, by enhancing accessibility and simplifying the implementation. Here are the improvements we plan to make:

1. Remove unnecessary elements and bloatware from both buttons.
2. Add `role="button"` and `aria-label` attributes for proper semantics and labeling.
3. Simplify the code while ensuring full functionality for both buttons.

### Why Refactor?

Refactoring the Share and Copy buttons will bring the following benefits:

1. **Enhanced Accessibility**: By adding proper attributes and semantics, we ensure that both buttons are accessible to all users, including those using screen readers and assistive technologies.

2. **Cleaner Code**: Removing unnecessary elements will result in cleaner and more maintainable code for the buttons.

3. **Improved User Experience**: A more streamlined and accessible Share and Copy buttons will enhance the overall user experience.

### Scope of Work 

1. Review the existing Share and Copy button implementations.
2. Remove the tooltip `div`, unnecessary event handlers, and any other bloatware.
3. Add `role="button"` and `aria-label` attributes to both button elements.
4. Test the Share and Copy buttons thoroughly for accessibility and functionality.

### Screenshots (Current State)
|COPY|SHARE|
|:---:|:---:|
|![image](https://github.com/rupali-codes/LinksHub/assets/92252895/b83a431a-d15c-4556-aa2c-a6182107a85a)|![image](https://github.com/rupali-codes/LinksHub/assets/92252895/ab4337cd-3b8a-46c3-a912-794c869da9de)|

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

**Comment by 0xabdulkhalid** [comment]
Hey there @rupali-codes, @CBID2 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by CBID2** [comment]
> 
> 
> Hey there @rupali-codes, @CBID2 👋🏻 
> 
> 
> 
> Please make sure to assign this issue to me to make the work done, Thank You!

Hey @0xabdulkhalid. Let's focus on finishing the animation issue first
