### ISSUE TITLE
[Add] AWS Educate Cloud Ambassador Program

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1481]
### Site URL

https://aws.amazon.com/education/awseducate/

### Description of the above provided site

The AWS Educate Cloud Ambassador Program recognizes individuals for their innovation and contributions that prepare students for careers in the modern technology workforce.

### Category

Other

### Sub Category

communities

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
> Please assign this issue to me @CBID2 @rupali-codes 

Please be patient @S-ishita. The maintainers are working diligently to review and ensure that the issue that are presented fit into LinksHub. In the meantime, I highly recommend reviewing other contributors' code in the pull requests section. It's a great way to develop your communication skills! :)

**Comment by CBID2** [comment]
You're assigned @S-ishita
