### ISSUE TITLE
[BUG] Update the maintainers data

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1488]
### Description

Update the maintainers database, and add my github there

![image](https://github.com/rupali-codes/LinksHub/assets/96341431/a3992d71-c0d1-44eb-8fff-1a187247488b)

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/96341431/8ed9fa5a-588a-41bc-893d-f8fbba101046)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
> @CBID2 please look into this and assign , so that i can start working on it.

You're assigned @k-deepak04
