### ISSUE TITLE
[Add] bookboon 

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1491]
### Site URL

www.bookboon.com

### Description of the above provided site

With a mission to provide everyone access to helpful and practical personal development content on an easy-to-use platform, a “boon” is exactly what we hope to deliver.

### Category

Resources

### Sub Category

ebook

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
