### ISSUE TITLE
[Add] free ebooks

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1499]
### Site URL

http://freecomputerbooks.com

### Description of the above provided site

Links to Free Computer, Mathematics, Technical Books all over the World

### Category

Resources

### Sub Category

ebook

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
