### ISSUE TITLE
[Feature] Add external link icon to the 'Visit site' link

### ISSUE THREAD

**Issue by zvolcsey** [rupali-codes/LinksHub#150]
### Description

Hi! The 'Visit site' links are external links, maybe would be a better UI/UX, if we add an external link icon to this links.

**Comment by rupali-codes** [comment]
> @rupali-codes Can I work on this? I think on hover the external link icon should appear, what do you think?

Yes, that would be awesome. You can rise Pull request.

**Comment by zvolcsey** [comment]
> @rupali-codes Can I work on this? I think on hover the external link icon should appear, what do you think?

Good, but I think that the icon should also appear by default before the 'Visit site' text. The user can see immediately that it is an external link.

**Comment by rupali-codes** [comment]
> > @rupali-codes Can I work on this? I think on hover the external link icon should appear, what do you think?
> 
> Good, but I think that the icon should also appear by default before the 'Visit site' text. The user can see immediately that it is an external link.

Let them rise the PR and let's see.
