### ISSUE TITLE
[Add] Add caching resources in the website

### ISSUE THREAD

**Issue by Sahilll15** [rupali-codes/LinksHub#1505]
### Site URL

https://aws.amazon.com/caching/

### Description of the above provided site

It is an resource and a blog by the official website of AWS 

### Category

Resources

### Sub Category

caching

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned now @Sahilll15

**Comment by Sahilll15** [comment]
okay!!
