### ISSUE TITLE
feat: Implement Browser Bar Theme Feature for Enhanced PWA Experience 🚀🔥 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#1506]
## Description
- I'm excited to announce a new feature for LinksHub - the Browser Bar Theme! 
- This addition aims to further enhance the Progressive Web App (PWA) experience by dynamically adapting the browser's address bar color to match the selected theme (dark or light). 
- The bar color can be switched dynamically during Dark/Light Toggling, Which looks immersive for Mobile Devices.

## Advantages of Browser Bar Theme:
1. Immersive User Experience: With the Browser Bar Theme, users will enjoy a more immersive and visually appealing experience when using LinksHub as a PWA. The seamless transition between the app's theme and the browser's address bar creates a cohesive and integrated user interface.

2. Consistency Across Platforms: The Browser Bar Theme ensures consistency across different devices and platforms. Whether users access LinksHub through their desktop browser or as an installed PWA on their mobile devices, the browser bar will adapt to match the selected theme.

3. Aesthetically Pleasing: The dynamic change in the browser's address bar color based on the chosen theme adds a touch of elegance to LinksHub. It elevates the overall design and visual aesthetics of the app, leaving a positive impression on users.

## Browser Bar Theme Feature & PWAs:
- Progressive Web Apps (PWAs) are designed to deliver a native app-like experience on the web. By incorporating the Browser Bar Theme feature, LinksHub aligns with the core principles of PWAs, creating a smoother and more enjoyable user journey. When users install LinksHub as a PWA on their devices, the Browser Bar Theme adds an extra layer of professionalism and authenticity to the application.

- The implementation of Dark/Light Adaptable Browser Bar Theme requires careful consideration of design and user experience. Our development team will work diligently to ensure compatibility across various browsers and devices, providing a consistent and delightful experience for all LinksHub users.

## Example Screenshots
![image](https://github.com/rupali-codes/LinksHub/assets/92252895/cfef7149-94d9-417c-88fb-d7e524c870cf)

**Comment by 0xabdulkhalid** [comment]
Hey there @rupali-codes, @CBID2 👋🏻 

Let's embrace this new feature and continue to make LinksHub an outstanding platform for managing and sharing links, with a delightful PWA experience that stands out from the rest!

**Comment by CBID2** [comment]
It looks interesting @0xabdulkhalid! :) What do you think @rupali-codes?

**Comment by 0xabdulkhalid** [comment]
@CBID2 Can you assign this issue to me ?

Because I'm ready to push changes, So that you and `rupali-codes` can test this feature.

**Comment by CBID2** [comment]
> @CBID2 Can you assign this issue to me ?
> 
> 
> 
> Because I'm ready to push changes, So that you and `rupali-codes` can test this feature.

I understand that @0xabdulkhalid but I want to  get @rupali-codes' viewpoint on this.

**Comment by 0xabdulkhalid** [comment]
As you wish @CBID2 👍🏻

**Comment by 0xabdulkhalid** [comment]
@rupali-codes your thoughts regarding this issue are greatly appreciated.

**Comment by 0xabdulkhalid** [comment]
@rupali-codes your thoughts regarding this issue are greatly appreciated.

**Comment by CBID2** [comment]
Go ahead @0xabdulkhalid
