### ISSUE TITLE
Add Comprehensive Guide to Conventional Commits for Contributors.md ✨

### ISSUE THREAD

**Issue by Nishitbaria** [rupali-codes/LinksHub#1508]
**Description:**
As a project that values clear and consistent commit messages, we should adopt the Conventional Commits guideline to enhance our development workflow and improve collaboration among contributors. Conventional Commits provide a well-defined specification for writing commit messages, making it easier to understand the purpose and impact of each commit.

**Current Situation:**
Currently, our project lacks specific guidelines for writing commit messages, leading to inconsistent and unclear commit messages. This can make it challenging for contributors and maintainers to review changes and understand the context of each commit.

**Proposed Solution:**
We propose adding a section in the `CONTRIBUTION.md` file that outlines the Conventional Commits guideline. This section should cover the basic structure and rules for writing commit messages following the Conventional Commits standard.

**Benefits:**
By implementing the Conventional Commits guideline, our project will enjoy the following benefits:
1. **Clear and Meaningful Commit Messages**: Contributors will be encouraged to provide descriptive commit messages that explain the purpose and changes introduced in each commit, making it easier for everyone to follow the development history.
2. **Automated Release Notes**: Conventional Commits can be utilized to generate automated release notes, making the release process more efficient and less error-prone.
3. **Improved Collaboration**: The standardized commit messages will enhance communication and collaboration among contributors and maintainers, fostering a healthier development community.
4. **Easier Changelog Generation**: Following the Conventional Commits specification will simplify the generation of changelogs, which is crucial for users and stakeholders to track project changes.

**Proposed Changes:**
1. Add a new section titled "Conventional Commits Guideline" in the `CONTRIBUTION.md` file.
2. Provide a brief overview of Conventional Commits and its importance in our project.
3. Outline the standard commit message format following the Conventional Commits rules.
4. Provide examples of well-formatted commit messages for various types of changes (e.g., feature addition, bug fix, documentation update, etc.).
5. Mention any additional project-specific guidelines or conventions related to commit messages, if applicable.

**Comment by CBID2** [comment]
That's a great idea @Nishitbaria! :)
