### ISSUE TITLE
[DOCS] UPDATE README,SECURITY,AND CONTRIBUTING PAGE

### ISSUE THREAD

**Issue by abhisar-yadav** [rupali-codes/LinksHub#1509]
### Issue Description

There are a lot of grammatical errors in the README, SECURITY,AND CONTRIBUTING PAGE

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @abhisar-yadav. Can you do a screenshot of these errors?

**Comment by CBID2** [comment]
Any updates @abhisar-yadav?

**Comment by abhisar-yadav** [comment]
Kindly review my PR

**Comment by CBID2** [comment]
> Kindly review my PR @CBID2 
> 
> 

Done
