### ISSUE TITLE
[Add] Icon Resource

### ISSUE THREAD

**Issue by Sriparno08** [rupali-codes/LinksHub#1510]
### Site URL

https://thenounproject.com/

### Description of the above provided site

The Noun Project offers the world's most diverse collection of free icons and vector images.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @Sriparno08
