### ISSUE TITLE
[Add] neso academy

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1515]
### Site URL

https://www.youtube.com/@nesoacademy

### Description of the above provided site

Covers various topics related to field of computer science
 ► Engineering Lectures
 ► School Syllabus
 ► Competitive Exams

### Category

Youtube

### Sub Category

computer science

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
