### ISSUE TITLE
[Feature] Provide Smoothness while Scrolling

### ISSUE THREAD

**Issue by kalashvasaniya** [rupali-codes/LinksHub#1516]
### Description

Provide Smoothness while Scrolling with the help of using CSS

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @kalashvasaniya. Can you elaborate on your suggestion please? What can provide smooth scrolling

**Comment by rupali-codes** [comment]
@kalashvasaniya are u still willing to work on this?

**Comment by Anmol-Baranwal** [comment]
@kalashvasaniya 
Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

**Comment by vishalsingh2972** [comment]
In case this issue is available, please assign it to me!

**Comment by CBID2** [comment]
> In case this issue is available, please assign it to me!

You're assigned @vishalsingh2972

**Comment by Anmol-Baranwal** [comment]
@vishalsingh2972 
Please proceed with it, and don't hesitate to tag us if you require any assistance.

**Comment by vishalsingh2972** [comment]
Hi @Anmol-Baranwal. I have never worked with react or typescript before. I have only worked in Javascript where I used to run the html file and check for changes that are being made, could you help me with how to check for changes that are being made in the frontend part as we make changes in the css?

**Comment by vishalsingh2972** [comment]
Hi @Anmol-Baranwal. I have never worked with react or typescript before. I have only worked in Javascript where I used to run the html file and check for changes that are being made, could you help me with how to check for changes that are being made in the frontend part here as we make changes in the css?

**Comment by Anmol-Baranwal** [comment]
> Hi @Anmol-Baranwal. I have never worked with react or typescript before. I have only worked in Javascript where I used to run the html file and check for changes that are being made, could you help me with how to check for changes that are being made in the frontend part here as we make changes in the css?

You should follow articles and read official documentation of Next.js, and TypeScript.

If you know JS, then you can just see examples in other directories, and you will get an idea of TypeScript, or you can use online tutorials.

You must know next.js or at least the layout and file structure.

**Comment by jainendra001** [comment]
Hi @CBID2 , @rupali-codes   I am really interested to work on this issue, I am currently a fullstack developer pursuing undergrad at IIT's , Could you please assign me this issue.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Why noone tags me🤣.

@jainendra001 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by jainendra001** [comment]
@Anmol-Baranwal from next time I will tag you...😅

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal from next time I will tag you...😅and Thanks for giving me the chance.

I was kidding.😅 Feel free to tag anyone, we will do whenever we get time.

**Comment by sujithyadav998** [comment]
@Anmol-Baranwal I want to work on this issue . Assign it to me

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal I want to work on this issue . Assign it to me

@jainendra001 
Are you interested in contributing?
If not, please let me know so that I can open this for others to contribute.

@sujithyadav998 
If he doesn't respond in 24 hrs, I will assign you the issue.

**Comment by ikaushiksharma** [comment]
@Anmol-Baranwal I want to work on this issue too, I am really comfortable working on TS and NextJs.

**Comment by Raj100679** [comment]
@Anmol-Baranwal @CBID2 Can you assign this issue to me?

**Comment by Anmol-Baranwal** [comment]
I totally forgot about this issue. LOL!

@CBID2 @rupali-codes 
Decide and assign this.

**Comment by CBID2** [comment]
> I totally forgot about this issue. LOL!
> 
> 
> 
> @CBID2 @rupali-codes 
> 
> Decide and assign this.

@Anmol-Baranwal, it's assigned to @kalashvasaniya already.

**Comment by Anmol-Baranwal** [comment]
> > I totally forgot about this issue. LOL!
> > 
> > 
> > 
> > @CBID2 @rupali-codes 
> > 
> > Decide and assign this.
> 
> @Anmol-Baranwal, it's assigned to @kalashvasaniya already. 

He isn't interested. So feel free to assign whoever seems to fit according to you.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
You should've assigned to someone. 😅
No worries.
