### ISSUE TITLE
[BUG] dropdown issue

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1519]
### Description

All the categories dropped when we clear the search result from the search query making it look bad.

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/96341431/2f661f21-89ae-424d-ac7a-c544b04563bd

check this on reloading again the iot comes even if i clear it and also all dropdown open up and that looks bad

### Any additional information?

till now after 2 hrs i'm able to resolve the reloading query issue, but still stuck in this one and will try to figure it out quick.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@rupali-codes @CBID2 please assign me with this issues

**Comment by CBID2** [comment]
Go ahead @k-deepak04

**Comment by abhijithmuthyala** [comment]
> All the categories dropped when we clear the search result from the search query

This is fixed in #1398 

> check this on reloading again the iot comes even if i clear it

That's the expected behaviour though? Loading the page with `?query=iot` is equivalent to *submitting* the form with `iot`

**Comment by CBID2** [comment]
@k-deepak04, are you still working on this issue?

**Comment by k-deepak04** [comment]
@CBID2 no, i'm not working at this issue

**Comment by rupali-codes** [comment]
@k-deepak04 thanks for clarifying

**Comment by rupali-codes** [comment]
Closing this issue cz' it looks fine to me :)
