### ISSUE TITLE
[CHORE] add LinksHub gif in README.md

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#152]
### What would you like to share or ask?

Having a gif in README.md file which describes the functionality as well as how to use the site in a proper manner, leads to a great user experience. 

#### Specific requirements
* Add GIF which includes
 * Use of searchbar
 * How to open links (Visit Site buttons)
 * Changing theme

**Comment by PiseAtharva** [comment]
Hi Rupali, loved the Work and I was wondering if i can take this Issue ?

**Comment by rupali-codes** [comment]
> Hi Rupali, loved the Work and I was wondering if i can take this Issue ?
Yes sure! Assigning to you

**Comment by AnushaSP07** [comment]
Hi @rupali-codes ,

It would be great if you could assign this issue to me, which I can take it up.

**Comment by PiseAtharva** [comment]
Hi Rupali, i have created this video [file](https://drive.google.com/file/d/1sV0xhhjdcO6U3jxITO9Oun7OFZPdPbRd/view?usp=sharing) (later to be converted into gif) could you check this out and tell if it needs any more changes/updates.

**Comment by PiseAtharva** [comment]
Also if Anusha wants to work on the same, maybe I can send the canva link straight up

**Comment by rupali-codes** [comment]
> Also if Anusha wants to work on the same, maybe I can send the canva link straight up, that is if she's also assigned 😅

It's fine, you can go-ahead and make PR

**Comment by PiseAtharva** [comment]
Hey Rupali, I had issues with the GIF format (primarily because of the fps and duration tradeoffs). I have managed to put the GIF in this [branch](https://github.com/PiseAtharva/LinksHub/blob/feat/add-LinksHub-GIF/README.md). Additionally I have created another [branch ](https://github.com/PiseAtharva/LinksHub/blob/feat/add-LinksHub-VIDEO/README.md) with video format for LinksHub.
I can't exactly make a PR cause of the Quality of GIF, but let me know about your thoughts.

**Comment by rupali-codes** [comment]
> Hey Rupali, I had issues with the GIF format (primarily because of the fps and duration tradeoffs). I have managed to put the GIF in this [branch](https://github.com/PiseAtharva/LinksHub/blob/feat/add-LinksHub-GIF/README.md). Additionally I have created another [branch ](https://github.com/PiseAtharva/LinksHub/blob/feat/add-LinksHub-VIDEO/README.md) with video format for LinksHub. I can't exactly make a PR cause of the Quality of GIF, but let me know about your thoughts.

It looks fine tho, but can we auto-play it? just like a GIF?

**Comment by PiseAtharva** [comment]
i will search for that tomorrow and let ya know about it

**Comment by PiseAtharva** [comment]
> i will search for that tomorrow and let ya know about it

sorry it will take a while (got irl work to do 😭 )

**Comment by rupali-codes** [comment]
> > i will search for that tomorrow and let ya know about it
> 
> sorry it will take a while (got irl work to do 😭 )

it's fine. you can take ur time

**Comment by PiseAtharva** [comment]
Hi Rupali , seems like Github will not allow autoplay feature on videos for security reasons. how do you want me to proceed, if the GIF is good to go then I can start a PR (incase its not please let me know how would you like it to be), same goes for the Video as well 😄

**Comment by rupali-codes** [comment]
> Hi Rupali , seems like Github will not allow autoplay feature on videos for security reasons. how do you want me to proceed, if the GIF is good to go then I can start a PR (incase its not please let me know how would you like it to be), same goes for the Video as well 😄

I've asked for GIF right? not video XD

**Comment by rupali-codes** [comment]
@PiseAtharva any updates?

**Comment by PiseAtharva** [comment]
omg Am so sorry, been busy with irl work. I will start a PR for you to review off the GIF. Should take couple of hours to reflect here (8-9PM)
