### ISSUE TITLE
[BUG] Wrong URL of Express.js

### ISSUE THREAD

**Issue by abhijithmuthyala** [rupali-codes/LinksHub#1523]
### Description

https://github.com/rupali-codes/LinksHub/blob/c2af4cbcd36f1dbf6710a44cdca5bdf1192264c9/database/resources/official-docs.json#L80-L82

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @abhijithmuthyala
