### ISSUE TITLE
[ADD] Add Nextjs & Three js

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1524]
### Category Name

Frontend

### Subcategory Name

Nextjs, three js

### Additional Context

Nextjs is and lightweight javascript framework and more seo friendly than react js, so it's more in use for building new websites generally new startups prefer this. 
three js is the 3d design and modeeling framework use by 3d artist and game developer, also to make creative 3d webpages

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes please look and assign me this

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes please look and assign me this

I assigned you @k-deepak04, but please do the one on Microsoft Learn first
