### ISSUE TITLE
[Add] Microsoft learn and certified

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1526]
### Site URL

https://learn.microsoft.com/en-us/certifications/

### Description of the above provided site

Add microsoft learn and certified course that will help as certificate carry an immense value in showcasing your skill.
i have done 2 certificate from this AZ-900 & DP-900

### Category

Cloud Computing

### Sub Category

Microsoft Azure

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes please assign me this, so that i can start working

**Comment by CBID2** [comment]
Done

**Comment by k-deepak04** [comment]
Thanks i'll add a PR by the end of the day
Make sure to review and merge that
Thanks :)
