### ISSUE TITLE
[Add] the coder coder

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1530]
### Site URL

https://www.youtube.com/c/TheCoderCoder

### Description of the above provided site

Practical tips for the beginner web developer.

### Category

Youtube

### Sub Category

web development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You’re assigned @S-ishita
