### ISSUE TITLE
[Add] book yards

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1531]
### Site URL

www.bookyards.com

### Description of the above provided site

'The Library to the World', in which books, education materials, information, reference materials, documents, and content will be provided freely 

### Category

Resources

### Sub Category

ebook

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You are assigned @S-ishita
