### ISSUE TITLE
[Add] Oracle University free cloud certifications

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1545]
### Site URL

https://education.oracle.com/home

### Description of the above provided site

oracle is providing free certifications for students for OCI - oracle cloud infrastructure

### Category

Cloud Computing

### Sub Category

oracle

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@rupali-codes @CBID2 please see this issue, it's very much helpful for those who wish to grow towards cloud computing field.

**Comment by CBID2** [comment]
Done @k-deepak04
