### ISSUE TITLE
[Add] Add gfg & coding Ninja to the CP

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1547]
### Site URL

https://www.codingninjas.com/studio/home

### Description of the above provided site

Geek for Geeks and coding Ninja are the best two platform where one can get quality content and also practice cp

![image](https://github.com/rupali-codes/LinksHub/assets/96341431/239574f5-5a29-467e-b9d5-4a87d24f9af8)

### Category

Open Source

### Sub Category

competitive programming

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned
