### ISSUE TITLE
[BUG] Competitive programming dropdown icon not visible

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1548]
### Description

as the Competitive programming name is too large for the sidebar it's name has covered quite a lot space and the dropdown is not visible  in large screens in small one it is visible.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/96341431/45acc82b-c95e-4b71-b1cf-fa3d1779ace0)

![image](https://github.com/rupali-codes/LinksHub/assets/96341431/4f436f14-a0a5-4c58-9b15-4d9c04c908fe)

### Any additional information?

solutions - Competitive programming is also known as "CP" so we can replace that.
or find a similar word or we can use "CP - competitive pro......" like this

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes please assign me this

**Comment by CBID2** [comment]
Done @k-deepak04

**Comment by k-deepak04** [comment]
> Done @k-deepak04

@CBID2 tell me which one i should keep....
read the additional information part

**Comment by CBID2** [comment]
CP - competitive pro sounds good
