### ISSUE TITLE
[BUG] <Title>Fix text Alignment in Mobile View of Home Section

### ISSUE THREAD

**Issue by Mani-mk-mk** [rupali-codes/LinksHub#155]
### Is there any existing issue for this?

- [x] I have searched the existing issues

### Description

The text in the "**# Home**" section appears to be unevenly spaced, which is probably due to incorrect padding for the container. This is only noticeable on mobile devices and does not affect the appearance of the other sections on the site.  

### Screenshots

![image](https://user-images.githubusercontent.com/72310576/217330181-8f2ab22b-16bb-44b3-bc27-c442192ec050.png)

### What browser are you seeing the problem on?

Firefox, Chrome

**Comment by Aadarsh805** [comment]
it's because the icons have separate padding on them, what we can do is remove the padding from icons and give padding to the entire div instead
@Mani-mk-mk you wanna work on this?
or should I go ahead and make a pr

**Comment by Mani-mk-mk** [comment]
I'm currently working on adding a section on hosting so I'll fix this one in the same PR.

**Comment by Aadarsh805** [comment]
> I'm currently working on adding a section on hosting so I'll fix this one in the same PR.

cool

**Comment by rupali-codes** [comment]
this issue was fixed
