### ISSUE TITLE
[Add] codeforces

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1562]
### Site URL

https://codeforces.com/

### Description of the above provided site

Codeforces is a website for practising competitive programming 

### Category

Other

### Sub Category

platforms

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
