### ISSUE TITLE
[Add] atcoder

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1563]
### Site URL

https://atcoder.jp/

### Description of the above provided site

AtCoder is a programming contest site for anyone from beginners to experts. 

### Category

Frontend

### Sub Category

platforms

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
