### ISSUE TITLE
[Add] SPOJ

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1564]
### Site URL

https://www.spoj.com/

### Description of the above provided site

SPOJ is an online judge system with over 315,000 registered users and over 20,000 problems.

### Category

Frontend

### Sub Category

platforms

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
