### ISSUE TITLE
[Add] ideone

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1565]
### Site URL

https://ideone.com/

### Description of the above provided site

Ideone is an online compiler and debugging tool which allows you to compile source code and execute it online in more than 60 programming languages.

### Category

Frontend

### Sub Category

code editor

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
> Please assign this issue to me @CBID2

Done @S-ishita
