### ISSUE TITLE
[Add] Coding Blocks IDE

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1566]
### Site URL

https://ide.codingblocks.com/

### Description of the above provided site

In addition to the IDE with code completion, you can also create an account to save your code on the server, and also share it with others.

### Category

Frontend

### Sub Category

code editor

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
