### ISSUE TITLE
[Add] Rextester IDE

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1567]
### Site URL

https://rextester.com/

### Description of the above provided site

On Rextester, you can create a execution command for the program along with code compilation and execution

### Category

Frontend

### Sub Category

code editor

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Go ahead @S-ishita
