### ISSUE TITLE
[Add] Font Resource

### ISSUE THREAD

**Issue by Sriparno08** [rupali-codes/LinksHub#1568]
### Site URL

https://fonts.adobe.com/

### Description of the above provided site

Adobe Fonts partners with the world's leading type foundries to bring thousands of beautiful fonts to designers every day.

### Category

Frontend

### Sub Category

fonts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Go ahead @Sriparno08
