### ISSUE TITLE
[Feature] Adding a section on Hosting

### ISSUE THREAD

**Issue by Mani-mk-mk** [rupali-codes/LinksHub#157]
### Description

A hosting section could be added to the current sections, which would cover well-known hosting websites such as GitHub Pages and Vercel. If it is okay to include this section, I would like to work on it.

**Comment by rupali-codes** [comment]
Thanks, it's a great idea. would you like to work on this?

**Comment by Mani-mk-mk** [comment]
Yeah, sure I would love to work on this one.

**Comment by rupali-codes** [comment]
> Yeah, sure I would love to work on this one.
Go-ahead!
