### ISSUE TITLE
[Add] cs academy IDE

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#1583]
### Site URL

https://csacademy.com/workspace/

### Description of the above provided site

In addition to code compilation and execution, it consists of workspaces 

### Category

Frontend

### Sub Category

code editor

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @S-ishita
