### ISSUE TITLE
[Feature] Automatic setup the workspace in codespaces

### ISSUE THREAD

**Issue by PriyansuMaurya** [rupali-codes/LinksHub#1585]
### Description

I would love to add `.devcontainer/devcontainer.json`

- A `devcontainer.json` file can **install tools and runtimes**, and **perform other setup tasks** that the project requires. 
- It installs all the dependencies and runs the project automatically, allowing the developer to concentrate on coding.
- A `devcontainer.json` file can be used to configure the development container for both codespaces and local development using Visual Studio Code.

### Screenshots

I have already implemented this feature on my Fork.

You can check, how it works by creating a codespace on `codespaces-auto-setup`

![image](https://github.com/rupali-codes/LinksHub/assets/101447544/bf77fa98-9c4f-4d7e-ae8d-cedfefd86266)

Here is the link to my fork : https://github.com/PriyansuMaurya/LinksHub

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@PriyansuMaurya 
Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

**Comment by CBID2** [comment]
> @PriyansuMaurya 
> 
> Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

If they don't respond, I'll create a draft PR for it and you can edit it @Anmol-Baranwal

**Comment by PriyansuMaurya** [comment]
> > Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

Since you haven't assigned me a task, how can I get started?

**Comment by Anmol-Baranwal** [comment]
> > > Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.
> 
> Since you haven't assigned me a task, how can I get started?

Sure, no worries.😅

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
