### ISSUE TITLE
[BUG] showing multiple scrollbars in sidebar

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1590]
### Description

I have just noticed that its showing two scrollbars on sidebar which kinda weird

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/a6b7380e-e04d-4756-9b2f-ddc254dc8941)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by dev-phantom** [comment]
I'd love to work on this issue

**Comment by rupali-codes** [comment]
> I'd love to work on this issue

Sure, thanks. Assigning to you!

**Comment by rupali-codes** [comment]
> I'd love to work on this issue

Are you a gssoc contributor?

**Comment by dev-phantom** [comment]
> > I'd love to work on this issue
> 
> Are you a gssoc contributor?

Nope

But I've contributed to linkshub repo before

**Comment by dev-phantom** [comment]
> ### Description
> I have just noticed that its showing two scrollbars on sidebar which kinda weird
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/78981177/260053338-a6b7380e-e04d-4756-9b2f-ddc254dc8941.png)
> 
> ### Any additional information?
> _No response_
> 
> ### What browser are you seeing the problem on?
> _No response_
> 
> ### Checklist
> * [x]  I have checked the existing issues
> * [x]  I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
> * [ ]  I am willing to work on this issue (optional)
> * [ ]  I am a GSSoC'23 contributor

I am unable to reproduce this error (looks like it has been fixed in another PR)

kindly refresh your browser and close this issue as this issue no longer exist
![image](https://github.com/rupali-codes/LinksHub/assets/72051159/af7743f0-cd1f-4afb-be65-b3d897a991cf)

**Comment by rupali-codes** [comment]
I see, thanks
