### ISSUE TITLE
[Add] SDET- QA Automation Techie

### ISSUE THREAD

**Issue by shreedhar37** [rupali-codes/LinksHub#1594]
### Site URL

https://www.youtube.com/@sdetpavan

### Description of the above provided site

This channel has educational videos on software testing & automation tools to help beginners and experienced professionals.

### Category

Youtube

### Sub Category

testing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@shreedhar37 
Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

**Comment by shreedhar37** [comment]
@Anmol-Baranwal  I'm interested, I'll contribute

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal I'm interested, I'll contribute

Please proceed with it, and don't hesitate to tag me if you require any assistance.
