### ISSUE TITLE
[Add] <fontmirror to frontend/fonts category>

### ISSUE THREAD

**Issue by AhorIsaac** [rupali-codes/LinksHub#1598]
### Site URL

https://www.fontmirror.com/

### Description of the above provided site

FontMirror is a tool that allows you to preview fonts on your website before you commit to using them. It has a large library of fonts to choose from and you can compare fonts side-by-side to see which one you like best before you can download it.

### Category

Frontend

### Sub Category

fonts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@AhorIsaac 
Are you still interested in working on this issue? If not, please let me know so that I can open it for others to contribute.

**Comment by AhorIsaac** [comment]
![Screenshot 2023-08-19 20 47 00](https://github.com/rupali-codes/LinksHub/assets/78865708/db31db2a-d444-4794-a0e2-1b3c12de27b0)

**Comment by Anmol-Baranwal** [comment]
> ![Screenshot 2023-08-19 20 47 00](https://user-images.githubusercontent.com/78865708/261817116-db31db2a-d444-4794-a0e2-1b3c12de27b0.png)

Sorry, I was just confirming it. Please proceed with it, and tag me if you need any assistance.
