### ISSUE TITLE
[Feature] Adding automated releases and release notes

### ISSUE THREAD

**Issue by tamalCodes** [rupali-codes/LinksHub#1601]
### Description

I saw that previously we closed #833 which was meant to add this feature up, and we also do have #866 which is also almost the same though having a changelog is somewhat different than having semantic releases scheduled with time.

Here's what I offer. We can use [Release Drafter](https://github.com/release-drafter/release-drafter), a popular Opensource action that automatically creates Draft releases for you, along with proper semantic versioning.

&nbsp;

### How it works ?

- We can add up a `.github/workflows/release-drafter.yml` which will be responsible for drafting your releases based on the branches. 
- Then if you want "well-formatted" releases you can have `.github/release-drafter.yml` which will contain a template file and it will decide how the versioning is based upon labels `bug`, `feature` and so on.
- Also it will help to format the labels with custom titles as per your choice.
&nbsp;

### Workflow and Demo

If you wish for a demo, head over to [Milan's Releases](https://github.com/MilanCommunity/Milan/releases) where we draft a release along with proper release notes as soon as we squash-merge a change to the `beta` branch. We do publish a release every week when we merge our `beta` branch to the `main` branch.

It is fully based on the labels I add to the PR. If I add a `bug` it will be considered a `patch`, for `feature` it goes under the `minor` changes, and so on. Learn more about Semantic versioning [here](https://www.geeksforgeeks.org/introduction-semantic-versioning/)

### Screenshots

This is how draft changes looks like 👇🏻

![image](https://github.com/rupali-codes/LinksHub/assets/72851613/c3e7ff56-4cef-4370-9e2a-9026bbd8b2c4)

This is how published changes looks like 👇🏻

![image](https://github.com/rupali-codes/LinksHub/assets/72851613/956aedcd-5e38-45a6-a29d-d6b1f9c7e950)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi @tamalCodes, you may start working on this?

**Comment by CBID2** [comment]
> Hi @tamalCodes, you may start working on this?

@tamalCodes, check this out: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
