### ISSUE TITLE
[BUG] There is no resources present for "Testing" due to wrong configs

### ISSUE THREAD

**Issue by shreedhar37** [rupali-codes/LinksHub#1607]
### Description

- There is no data present for the "Testing" while we have data inside database.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/55444468/9b1da8f1-8ec4-438e-9b28-63c38083ab57)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Can you elaborate on this @shreedhar37

**Comment by shreedhar37** [comment]
Yes @CBID2. I am ready to contribute

**Comment by shreedhar37** [comment]
Sure @CBID2 . We have data inside https://github.com/rupali-codes/LinksHub/blob/main/database/youtube/testing.json for testing resources, but due to wrong config in `data.ts`

**Comment by CBID2** [comment]
I see @shreedhar37. Go ahead
