### ISSUE TITLE
[chore] change state of Anmol to maintainer in contributors section

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1608]
### File Name

data/maintainersData.ts

### Reason for Refactoring the Code

![4D30F213-20AD-4CDB-8F95-F25494B38B69](https://github.com/rupali-codes/LinksHub/assets/105683440/49db8c88-f039-44f7-b460-83edbc205340)

As shown above, @Anmol-Baranwal still has the C label. To let new and consistent contributors know that they are in a new role now, the label should be M

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [x] I am willing to work on this issue (optional).
- [ ] I am a GSSoC23 contributor.

**Comment by Anmol-Baranwal** [comment]
Thanks. @CBID2 

Just adding this would do the work: 
```
{ login: 'Anmol-Baranwal', name: 'Anmol Baranwal' },
```

**Comment by CBID2** [comment]
> Thanks. @CBID2
> 
> Just adding this would do the work:
> 
> ```
> { login: 'Anmol-Baranwal', name: 'Anmol Baranwal' },
> ```

Noted

**Comment by rupali-codes** [comment]
@CBID2 👀
