### ISSUE TITLE
[BUG] vertiacal overflow issue in the home page

### ISSUE THREAD

**Issue by Aadarsh805** [rupali-codes/LinksHub#161]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The home page has a scroll due to which the top bar is getting out of screen after scrolled

### Screenshots

![image](https://user-images.githubusercontent.com/95094057/217723316-ccc8cd70-3a9c-47eb-9ff9-c0cea6871d52.png)

### Any additional information?

I suggest we make the TopBar fixed
Because this will be an issue on every page when there will be more cards 

![Screenshot from 2023-02-09 10-40-29](https://user-images.githubusercontent.com/95094057/217723636-9493cc2d-b483-4c80-ba50-b271c64a5c60.png)

**Comment by rupali-codes** [comment]
Thank you

**Comment by dev-phantom** [comment]
please has this issue been assigned 

i'd love to fix this

**Comment by rupali-codes** [comment]
> please has this issue been assigned
> 
> i'd love to fix this

Hi, yes you can start working on this.

**Comment by dev-phantom** [comment]
> > please has this issue been assigned
> > i'd love to fix this
> 
> Hi, yes you can start working on this.

can i work on this without getting assigned to it
