### ISSUE TITLE
Adding new golang tutorial by freecodecamp.org

### ISSUE THREAD

**Issue by subhadeepbanerjee2003** [rupali-codes/LinksHub#1610]
### Site URL

https://www.youtube.com/watch?v=un6ZyFkqFKo&t=33431s

### Description of the above provided site

Learn the Go programming language in this full course for beginners. You'll practice writing performant, idiomatic Go with these hands-on lessons and challenges.

### Category

Languages

### Sub Category

Go

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @subhadeepbanerjee2003

**Comment by subhadeepbanerjee2003** [comment]
thanks i'm on it to add a new tutorial

**Comment by subhadeepbanerjee2003** [comment]
@CBID2 @rupali-codes please check my pr

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes please check my pr

I just gave some feedback @subhadeepbanerjee2003. In the future, please be patient. The maintainers are working diligently to review pull requests in a timely manner.

**Comment by subhadeepbanerjee2003** [comment]
@Anmol-Baranwal please check my pr

**Comment by subhadeepbanerjee2003** [comment]
@CBID2 ok thanks
