### ISSUE TITLE
[DOCS] <adding number chart>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1612]
### Issue Description

I was thinking of implementing a chart that describes the level system. It’ll give contributors an idea of how to contribute to LinksHub, especially if they struggle with proposing ideas. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@CBID2 are you working on it?

**Comment by CBID2** [comment]
> @CBID2 are you working on it?

Yeah. I just wanted your opinion on it first @rupali-codes

**Comment by rupali-codes** [comment]
> > @CBID2 are you working on it?
> 
> Yeah. I just wanted your opinion on it first @rupali-codes

can u show me any examples how it actually looks like?

**Comment by CBID2** [comment]
> > > @CBID2 are you working on it?
> 
> > 
> 
> > Yeah. I just wanted your opinion on it first @rupali-codes
> 
> 
> 
> can u show me any examples how it actually looks like?

Something like [this](https://linkfree.io/docs/contributing/labels)

**Comment by rupali-codes** [comment]
> > > > @CBID2 are you working on it?
> > 
> > 
> > > 
> > 
> > 
> > > Yeah. I just wanted your opinion on it first @rupali-codes
> > 
> > 
> > can u show me any examples how it actually looks like?
> 
> Something like [this](https://linkfree.io/docs/contributing/labels)

Ohh, gotcha, it looks fine to me :)
