### ISSUE TITLE
[Description] < **Learn Go Programming** description should be changed>

### ISSUE THREAD

**Issue by subhadeepbanerjee2003** [rupali-codes/LinksHub#1613]
### Category Name

LANGUAGES

### Subcategory Name

Go

### New or updated description of above subcategory

- In both **`Hitesh Choudhary`** and **`Learn Go Programming`** the description is same .

- The description which is currently there in both the learning resources ,  is perfect for **`Hitesh Choudhary`** but not perfect for 
**`Learn Go Programming`** as it is giving wrong information about the **`Learn Go Programming`** course.

![Screenshot from 2023-08-21 02-04-28](https://github.com/rupali-codes/LinksHub/assets/116381157/1dce4cb0-7102-4fdc-88c3-54b3c11becd9)

> *Admins please checkout this issue as i think it is important.*

### Status of Description

- [X] Adding new description
- [X] Updating existing description

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by subhadeepbanerjee2003** [comment]
@rupali-codes can I send pr now?

**Comment by Anmol-Baranwal** [comment]
@subhadeepbanerjee2003 
Sure.
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal thank you i am ready to merge.

We have other works as well. We maintain the repository in our free time. Be patient and let others review this properly.

**Comment by subhadeepbanerjee2003** [comment]
Yes no problem at all

**Comment by rupali-codes** [comment]
> Yes no problem at all

Thanks for understanding :)

**Comment by subhadeepbanerjee2003** [comment]
I have closed this issue as #1622 is merged

**Comment by Anmol-Baranwal** [comment]
> I have closed this issue as #1622 is merged @Anmol-Baranwal

Thanks. Be sure to link the issue to PR, it will automatically close when the PR is merged.
