### ISSUE TITLE
[Refactor] Remove the underline from the copyright section

### ISSUE THREAD

**Issue by Sahilll15** [rupali-codes/LinksHub#1615]
### File Name

components/Footer/Footer.tsx

### Reason for Refactoring the Code

<img width="696" alt="Screenshot 2023-08-22 at 9 38 35 AM" src="https://github.com/rupali-codes/LinksHub/assets/109215419/2e63e8d1-00b5-4883-9c33-7df88941e56d">

This does not look goof

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

**Comment by CBID2** [comment]
Hi @Sahilll15. Where do you recommend we move it?

**Comment by CBID2** [comment]
> @CBID2  Everything looks fine that white underline under Rupali Haldiya and Open Source Community does not look good!!

Oh ok thanks for clarifying.

**Comment by Sahilll15** [comment]
Thanks ill revert back with an PR Soon
