### ISSUE TITLE
[BUG]: Tooltip description are missing for some languages.

### ISSUE THREAD

**Issue by the-shivam-gupta** [rupali-codes/LinksHub#1617]
### Description

When we click on the **info-tooltip** button in the language section it pops up with a description, but for some languages, the description is missing. I would like to add it. 

### Screenshots

This is how it looks for C programming:

![image](https://github.com/rupali-codes/LinksHub/assets/109647722/d41df072-a4c6-45df-9aeb-3ecb2ee19f98)

This is for C++ and likewise, there are more sections for which the descriptions are missing such as Dart, Java, Kotlin, and Rust:

![image](https://github.com/rupali-codes/LinksHub/assets/109647722/e7158efe-c765-4ca3-977a-be47d566585a)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
@Anmol-Baranwal, what do you think?

**Comment by Anmol-Baranwal** [comment]
Yeah, it would be great. This happened because initially, there were no contributing guidelines that enforced contributors to write descriptions when adding subcategories. So, please go ahead, @the-shivam-gupta.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by CBID2** [comment]
> Yeah, it would be great. This happened because initially, there were no contributing guidelines that enforced contributors to write descriptions when adding subcategories. So, please go ahead, @the-shivam-gupta.
> 
> I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

Do you think we should add that requirement @Anmol-Baranwal?

**Comment by Anmol-Baranwal** [comment]
> > Yeah, it would be great. This happened because initially, there were no contributing guidelines that enforced contributors to write descriptions when adding subcategories. So, please go ahead, @the-shivam-gupta.
> > I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
> 
> Do you think we should add that requirement @Anmol-Baranwal?

Already did with #1427

**Comment by CBID2** [comment]
> > > Yeah, it would be great. This happened because initially, there were no contributing guidelines that enforced contributors to write descriptions when adding subcategories. So, please go ahead, @the-shivam-gupta.
> 
> > > I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
> 
> > 
> 
> > Do you think we should add that requirement @Anmol-Baranwal?
> 
> 
> 
> Already did with #1427 

Oh yeah 😂
