### ISSUE TITLE
[BUG]  Mobile Sidebar Scrolling Behavior Issue

### ISSUE THREAD

**Issue by DevarajuAlugolu** [rupali-codes/LinksHub#1619]
### Description

**Expected Behavior**:  When the sidebar is open in mobile view, I expect the main content behind the sidebar to remain fixed and not scroll.

**Current Behavior:**  However, when the sidebar is open, the hidden content behind it is still scrollable, which leads to an unexpected user experience.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
@Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal

Thanks for the tag.

@DevarajuAlugolu 
Yeah, I just checked it. 

So, what will you do? Scroll only when sidebar is closed?

**Comment by DevarajuAlugolu** [comment]
@Anmol-Baranwal 

Yes.

I'm currently  working on implementing this solution.

**Comment by Anmol-Baranwal** [comment]
@DevarajuAlugolu 
Sure, go ahead.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by DevarajuAlugolu** [comment]
@Anmol-Baranwal 

Thank you for assigning the issue. I'm actively addressing the bug and will keep you updated on my progress.

**Comment by OpherM** [comment]
Please has this issue been rectified and the issue closed?

**Comment by DevarajuAlugolu** [comment]
> Please has this issue been rectified and the issue closed?

The issue has not been rectified or closed; we are still in the process of working on it.

**Comment by Anmol-Baranwal** [comment]
> Please has this issue been rectified and the issue closed?

Do you want to work on open issues? I can refer you to that.

**Comment by rupali-codes** [comment]
> Please has this issue been rectified and the issue closed?

yep, this issue has been assigned, please check out the other opened issues :)
