### ISSUE TITLE
[BUG] rounded border bottom in NavLinks

### ISSUE THREAD

**Issue by Aadarsh805** [rupali-codes/LinksHub#162]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The borders under each navLinks are rounded due to their active state and look a little odd

### Screenshots

![image](https://user-images.githubusercontent.com/95094057/217729095-00f6ec9b-1a3b-4e89-b6cc-73bb75f8fa46.png)

### Any additional information?

can be fixed by adding the border to the inner child instead of parent
I can work on this, if approved

**Comment by rupali-codes** [comment]
go-ahead Aadarsh!
