### ISSUE TITLE
[OTHER] add category name to the url

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1620]
### What would you like to share or ask?

Hi, I want to add the category name in the URL when the dropdown button gets clicked. For example, when user would visit https://linkshub.dev/languages then it should redirect to the **open source section** and open the open-source dropdown by default

Currently: 
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/c8650a0c-482f-4742-a88d-b5ce88cdeb69)

Should be like this: 
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/ca657ffd-0c54-4f5e-99c0-11ad0ea1b155)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
There can be two ways.

1. The user doesn't want this to open, so he directly goes to the respective URL (which he/she already knows). In this case, it would be bad UX.

2. It opens up, and the user can navigate to other sections by seeing the subcategories within that section. This is more general and I would believe would increase UX.

> I prefers second option.

**Comment by rupali-codes** [comment]
> There can be two ways.
> 
> 1. The user doesn't want this to open, so he directly goes to the respective URL (which he/she already knows). In this case, it would be bad UX.
> 2. It opens up, and the user can navigate to other sections by seeing the subcategories within that section. This is more general and I believe this would increase UX.
> 
> > I prefer second option.

the first one is how it looks like currently, and the second one is about what i wanna do in there

**Comment by CBID2** [comment]
> There can be two ways.
> 
> 
> 
> 1. The user doesn't want this to open, so he directly goes to the respective URL (which he/she already knows). In this case, it would be bad UX.
> 
> 
> 
> 2. It opens up, and the user can navigate to other sections by seeing the subcategories within that section. This is more general and I believe this would increase UX.
> 
> 
> 
> > I prefer second option.

I prefer the second option too @Anmol-Baranwal and @rupali-codes.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal could you please elaborate more on the second option?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal could you please elaborate more on the second option?

Imagine you're navigating a website with a sidebar. This sidebar serves as a navigational hub, providing you with quick access to various sections of the website. Now, let's focus on a specific scenario: you want to explore the "Icons" section of the website.

> Scenario A: Sidebar Stays Closed
In this case, if the sidebar remains closed even when you access the "/icons" route:

- You would need to manually open the sidebar, which adds an extra step in your navigation process. This can be frustrating, especially if you're not familiar with the site's layout.

> Scenario B: Sidebar Automatically Opens to Subcategory
Now, let's consider the enhanced scenario where the sidebar automatically opens to the "Icons" subcategory when you visit the "/icons" route:

- By automatically expanding the sidebar to the relevant subcategory, you're saving users time and effort. They can immediately see the available options related to icons without the need to manually interact with the sidebar.

-  Opening to the "Icons" subcategory visually guides users, showing them where they are and how to proceed. It's like walking into a store and finding the section you're interested in immediately visible.

- Users don't need to remember to open the sidebar or figure out which section they're in. The website proactively supports their journey, reducing cognitive load and improving the overall user experience.

Incorporating this behavior aligns with the UX principle of reducing friction and making navigation as seamless as possible. It's a small change that can make a big impact on user satisfaction and usability!

**Comment by rupali-codes** [comment]
@Anmol-Baranwal i see, thats exactly what i was saying :)
