### ISSUE TITLE
[Add] <The Odin Project to Frontend category>

### ISSUE THREAD

**Issue by mrigank590** [rupali-codes/LinksHub#1623]
### Site URL

https://www.theodinproject.com/

### Description of the above provided site

It is a free, open-source online coding curriculum. It offers courses covering web development basics, JavaScript, and Ruby on Rails. The curriculum is supported by an open-source community and maintains a Discord community of nearly 718,000 learners.

### Category

Frontend

### Sub Category

fonts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@mrigank590 you may start working on it

**Comment by mrigank590** [comment]
@rupali-codes btw I selected the wrong subcategory, it should be React Js
and I am done I will make a pull request

**Comment by rupali-codes** [comment]
> @rupali-codes btw I selected the wrong subcategory, it should be React Js and I am done I will make a pull request

alright
