### ISSUE TITLE
[OTHER] Reduce copyright font-size for small screens

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1625]
### What would you like to share or ask?

The font-size of copyright text in footer doesn't look good. It would be better if we can add some spacing and styling to it

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/ac8104d3-eb86-4f36-b05d-ac0d0d66b1ad)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by the-shivam-gupta** [comment]
can u plz elaborate the issue

**Comment by rupali-codes** [comment]
> can u plz elaborate the issue

Hi, you basically have to reduce the font-size of copyright text that would fit to the screen :)

**Comment by the-shivam-gupta** [comment]
Okay, I would be delighted if you could assign it to me.

**Comment by CBID2** [comment]
> Okay, I would be delighted if you could assign it to me.

You're assigned @the-shivam-gupta

**Comment by pankajdharmik4** [comment]
Is the issue solved already?

**Comment by CBID2** [comment]
> Is the issue solved already?

I think so @pankajdharmik4

**Comment by pankajdharmik4** [comment]
Yes

**Comment by SandeepGumaste** [comment]
@CBID2 is this issue fixed?

**Comment by CBID2** [comment]
> @CBID2 is this issue fixed?
No @SandeepGumaste. You want to work on it?

**Comment by hona9** [comment]
Can I work on it?

**Comment by SandeepGumaste** [comment]
@CBID2 I'll work on it

**Comment by CBID2** [comment]
> Yes, I'll work on it @CBID2 

You're assigned @SandeepGumaste
