### ISSUE TITLE
[Bug] place OTHER category at the end in the sidebar

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1627]
### Issue Description

As per the order, OTHER supposed to be placed at the end, but its appearing at last second. 

### Screenshots or Examples (if applicable)

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/c43fe06e-8454-4578-a387-d03206274ead)

### Proposed Solution (optional)

Place OTHER category at the end

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by vishalsingh2972** [comment]
Hi I would like to work on this, could you assign it to me!

**Comment by CBID2** [comment]
> Hi I would like to work on this, could you assign it to me!

Hi @vishalsingh2972! :) You're assigned

**Comment by vishalsingh2972** [comment]
> > Hi I would like to work on this, could you assign it to me!
> 
> Hi @vishalsingh2972! :) You're assigned

Hi @CBID2 , I think the issue has already been solved as we have an existing PR

**Comment by CBID2** [comment]
> > > Hi I would like to work on this, could you assign it to me!
> > 
> > Hi @vishalsingh2972! :) You're assigned
> 
> Hi @CBID2 , I think the issue has already been solved as we have an existing PR

Ooh sorry @vishalsingh2972. Hey you can give a code review of it as a way to start.
