### ISSUE TITLE
[ADD] Placement Prep category

### ISSUE THREAD

**Issue by viveknapit** [rupali-codes/LinksHub#1631]
### Category Name

Placement prep

### Subcategory Name

Aptitude , Reasoning, verbal, versant , DSA, Interview prep , notes

### Additional Context

It is very useful if the final or pre final year student got the link at one point for their placement preparation and their are lot of content is available for placement prep. and also their should be notes content link that should be help for placement.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hi, which resources do you want to add specifically?

**Comment by URVESH1121** [comment]
### -Aptitude,Reasoning & Verbal

1. Freshersworld.
2. PuzzleFry.
3. Testpot.
4. IndiaBIX.
5. AmbitionBox.
6. Fresherslive.
7. Sawaal.

### -DSA

1. HackerRank
2. GeeksforGeeks
3. leetcode
4. codechef
5. codeforces

### -Interview prep

1. preplaced
2. pramp
3. interviewbit
4. InterviewBuddy
5. Exponent

### -Notes
### -Coding and Programming

**Comment by CBID2** [comment]
I see @viveknapit. You're assigned

**Comment by viveknapit** [comment]
> Hi, which resources do you want to add specifically?

hey , I want to add those resources that are helpful for final year or pre final year students to prepare for their placements , for example their are lot resources available for aptitude and DSA and Interview prep as someone already menstioned.

**Comment by viveknapit** [comment]
> I see @viveknapit. You're assigned

sure , I have started working on.     and  very soon I'll finish

**Comment by CBID2** [comment]
Hey @viveknapit. How are things going?

**Comment by rupali-codes** [comment]
> ### -Aptitude,Reasoning & Verbal
> 1. Freshersworld.
> 2. PuzzleFry.
> 3. Testpot.
> 4. IndiaBIX.
> 5. AmbitionBox.
> 6. Fresherslive.
> 7. Sawaal.
> 
> ### -DSA
> 1. HackerRank
> 2. GeeksforGeeks
> 3. leetcode
> 4. codechef
> 5. codeforces
> 
> ### -Interview prep
> 1. preplaced
> 2. pramp
> 3. interviewbit
> 4. InterviewBuddy
> 5. Exponent
> 
> ### -Notes
> ### -Coding and Programming

We don't have to add all this, just filter out the good ones :)

**Comment by SandeepGumaste** [comment]
Can I work on this? @rupali-codes @CBID2

**Comment by rupali-codes** [comment]
> Can I work on this? @rupali-codes @CBID2

Yeah, sure
assigning to you

**Comment by Anmol-Baranwal** [comment]
@SandeepGumaste 
Are you interested in contributing?
If not, please let me know so that I can open this issue for others to take.

**Comment by Anmol-Baranwal** [comment]
> Hey @Anmol-Baranwal,
> 
> If @SandeepGumaste is unwilling to work or does not respond for an extended period, could you please reassign this issue to me? Additionally, please inform me about the proper category and subcategory names for the issue since they haven't been finalized yet.
> 
> Thank you in advance.

Sure, let's wait until tomorrow evening. If he doesn't respond, then I will assign you and let you know the tasks to complete this issue.

**Comment by Anmol-Baranwal** [comment]
@Shiva-Sai-ssb 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

There could be hundreds of resources. But we should only add most important ones.

Maybe raise a draft PR, or suggest some subcategories. 

@CBID2 
Do you have anything specific in mind.

**Comment by Shiva-Sai-ssb** [comment]
> @Shiva-Sai-ssb I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
> 
> There could be hundreds of resources. But we should only add most important ones.
> 
> Maybe raise a draft PR, or suggest some subcategories.
> 
> @CBID2 Do you have anything specific in mind.

Thanks. I'm not sure how to create a draft PR, but I can provide a list of subcategories, and you can advise me on which ones to include in the project. After that, I'll proceed with creating the PR.

**Comment by Anmol-Baranwal** [comment]
> > @Shiva-Sai-ssb I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
> > There could be hundreds of resources. But we should only add most important ones.
> > Maybe raise a draft PR, or suggest some subcategories.
> > @CBID2 Do you have anything specific in mind.
> 
> Thanks. I'm not sure how to create a draft PR, but I can provide a list of subcategories, and you can advise me on which ones to include in the project. After that, I'll proceed with creating the PR.

I would say, create a PR with the subcategories you have in mind. We will request the changes in the PR itself.

**Comment by Shiva-Sai-ssb** [comment]
> > > @Shiva-Sai-ssb I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
> > > There could be hundreds of resources. But we should only add most important ones.
> > > Maybe raise a draft PR, or suggest some subcategories.
> > > @CBID2 Do you have anything specific in mind.
> > 
> > 
> > Thanks. I'm not sure how to create a draft PR, but I can provide a list of subcategories, and you can advise me on which ones to include in the project. After that, I'll proceed with creating the PR.
> 
> I would say, create a PR with the subcategories you have in mind. We will request the changes in the PR itself.

Sure, I'll create the PR and include the subcategories I have in mind.
