### ISSUE TITLE
[OTHER]  Description needed 

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1639]
### What would you like to share or ask?

When you click on the icon near the "Contributors" title, it only shows the title's name.
   
### Proof of issue

https://github.com/rupali-codes/LinksHub/assets/105683440/3f98bcb1-cc36-4100-9cee-8357cea7616f

### Solution
I think it would be best to add a brief description of this section. Here's an example:
`These are the people that have helped LinksHub come to life! Thank you for your support! Note: M = Maintainer C= Contributors ` 
I'm open to your suggestions @Anmol-Baranwal, @k-deepak04, and @rupali-codes 
### Benefit
People who come to LinksHub's website can gain a better understanding of our roles in the project. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
This would definitely be helpful.
