### ISSUE TITLE
[Feature] Debounce `SearchbarSuggestions`

### ISSUE THREAD

**Issue by abhijithmuthyala** [rupali-codes/LinksHub#1644]
### Description

Re-iterating https://github.com/rupali-codes/LinksHub/pull/1398#issuecomment-1665328831

Before #1398, there was this debouncing logic meant for `SidebarSuggestions`.
https://github.com/rupali-codes/LinksHub/blob/3ed22dfcb82eb8361075ef6265048462f328bb01/hooks/useSearch.ts#L4-L20

But it was actually only delaying the _search results_ instead of debouncing the `SidebarSuggestions`. In the video below, you can see that the suggestions are updated on every key stroke. When the timeout threshold is increased to say 3 seconds, the search results appear 3 seconds after submitting the form. As part of the refactoring done in #1398, I removed debouncing as it wasn't functional anyway. 

I'd like to re-implement debouncing feature for the `SidebarSuggestions`.

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/73361366/d47399b3-23e9-4ea5-a6e0-8b1e3620cf87

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@abhijithmuthyala 
Elaborate the problem and the solution you propose, so that I can have a better idea about it.

**Comment by rupali-codes** [comment]
@abhijithmuthyala can you please elaborate?

**Comment by abhijithmuthyala** [comment]
I've updated the description, please check @Anmol-Baranwal @rupali-codes

**Comment by abhijithmuthyala** [comment]
I've updated the description, please check @Anmol-Baranwal @rupali-codes.

**Comment by Anmol-Baranwal** [comment]
@abhijithmuthyala 
Don't you think delaying search results by 500ms is like a fraction which is not even noticeable.

I think I get the point, but still the current version seems fast enough.

@rupali-codes 
Please assign him the issue, if you approve. This might be useful for future variations, but I'm not sure.

**Comment by abhijithmuthyala** [comment]
> Don't you think delaying search results by 500ms is like a fraction which is not even noticeable.

@Anmol-Baranwal The main reason I wanted to add this is because I thought it is my responsibility to add back a feature (albeit non-functional) that _I  removed_ in a PR.

This sure isn't a performance bottleneck for now. I personally prefer implementing the optimizations wherever there is an opportunity. I'll leave the decision of "_why not optimize and prevent too many renders when we can_", vs "_stop pre-mature optimizations_" to you guys 😅.

**Comment by Anmol-Baranwal** [comment]
Sure, @rupali-codes will let you know. 

In my opinion, it's not needed.

**Comment by abhijithmuthyala** [comment]
Sure, closing the issue.
