### ISSUE TITLE
[BUG] Cards are not displaying in ui-generator,Next js , Three js Sub categories

### ISSUE THREAD

**Issue by pankajdharmik4** [rupali-codes/LinksHub#1652]
### Description

JSON File have data but cards are not displaying.
For example : next.json file:-
[
    {
      "name": "NextJS",
      "description": "Used by some of the world's largest companies, Next.js enables you to create full-stack Web applications by extending the latest React features and integrating powerful Rust-based JavaScript tooling for the fastest builds.",
      "url": "https://nextjs.org/",
      "category": "frontend",
      "subcategory": "next-js"
    }
]

### Screenshots

![Capture](https://github.com/rupali-codes/LinksHub/assets/113082834/96c23f89-e0a3-4385-b929-927664ec3bc5)

### Any additional information?

I am willing to work on this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Hey @pankajdharmik4. Can you fix the format of your code snippets & show screenshots of the problem? It'll make it easier for us to visualize the problem.

**Comment by pankajdharmik4** [comment]
https://www.linkshub.dev/next 
https://www.linkshub.dev/three
https://www.linkshub.dev/ui-generator

Please visit this link you will find out that the card is not displaying here. Even after the data is present.
