### ISSUE TITLE
[BUG] Back to top button hoverable even at the top

### ISSUE THREAD

**Issue by harsh11101** [rupali-codes/LinksHub#1656]
### Description

The "Back to the top" button exhibits hover behavior even when the page is already at the top. This hover effect can be misleading, as it suggests interaction when no action is needed. I think the button and its components should only be visible after user has scrolled past SCROLL_LIMIT (200px).

### Screenshots

[screen-capture.webm](https://github.com/rupali-codes/LinksHub/assets/93988200/884c4c58-7204-4555-af63-99887617ddef)

### Any additional information?

I am willing to work on this issue.

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@harsh11101 assigned to you! you can start working on this issue

**Comment by harsh11101** [comment]
> @harsh11101 assigned to you! you can start working on this issue

Thanks, started working on this. Will finish this soon.
