### ISSUE TITLE
Add a link in "youtube-machine leaning" section

### ISSUE THREAD

**Issue by the-shivam-gupta** [rupali-codes/LinksHub#1657]
### Site URL

https://www.youtube.com/@programmingwithmosh

### Description of the above provided site

A beginner's guide to machine learning with Python, covering basics to advanced topics.

### Category

Machine Learning

### Sub Category

core concepts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You’re assigned @the-shivam-gupta
