### ISSUE TITLE
[Feature] animate the to-top button

### ISSUE THREAD

**Issue by Lourvens** [rupali-codes/LinksHub#166]
### Description

Jus add a fade animation when the button appear/disappear on scrolling will be more user friendly.

### Screenshots

![Capture d’écran 2023-02-09 164023](https://user-images.githubusercontent.com/63268101/217869811-9925041c-5f32-4f55-8772-e23da7602b24.png)

**Comment by rupali-codes** [comment]
@Lourvens Thank you, would you like to fix this?

**Comment by Lourvens** [comment]
Yes you can assign it to me

**Comment by rupali-codes** [comment]
> Yes you can assign it to me

okay, thank you
