### ISSUE TITLE
[DOCS] Replace linkshub.vercel.app with linkshub.dev in SECURITY.md file

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1667]
### Issue Description

I just noticed that `secutity.md`  have `https://linkshub.vercel.app` instead of `https://linkshub.dev`. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Hi @rupali-codes. Someone went ahead and [made a PR](https://github.com/rupali-codes/LinksHub/pull/1670) for this issue. It looks pretty good, but I want to make sure we want to assign this person and accept it since you wanted to do it.
