### ISSUE TITLE
[NEW LINKS] Add new category & subcategory

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#167]
### What would you like to share or ask?

Add new `category ` named `Resources` and a `subcategory` named  `Blogs` and add the following Links in there:
1. https://medium.com
2. https://geeksforgeeks.com
3. https://javatpoint.com
4. https://w3schools.com
5. https://logrocket.com
6. https://tutorialspoint.com
7. https://dev.to
8. https://freecodecamp.com

### Additional information

You can write a brief description if you familiar with the site, else just take it from homepage of the site (but make sure to keep it short and concise).

**Comment by imbeshat** [comment]
Hi @rupali-codes I would like to work on this. If it is not picked by anyone then you can assign me this issue.

**Comment by rupali-codes** [comment]
> Hi @rupali-codes I would like to work on this. If it is not picked by anyone then you can assign me this issue.

yes sure, thank you

**Comment by imbeshat** [comment]
For GFG, I think the link should be [https://www.geeksforgeeks.org](https://www.geeksforgeeks.org).
And can I add link for hashnode also?

**Comment by rupali-codes** [comment]
> For GFG, I think the link should be https://www.geeksforgeeks.org. And can I add link for hashnode also?

Yeah, thanks for correcting.
And yes, you can add Hashnode as well
