### ISSUE TITLE
[DOCS] Add codespaces description in the Readme file

### ISSUE THREAD

**Issue by Ameya02** [rupali-codes/LinksHub#1672]
### Issue Description

I saw that codespaces in the repository and there was no mention in readme file So i want to add that

### Screenshots or Examples (if applicable)

Here is the preview
![image](https://github.com/rupali-codes/LinksHub/assets/65841021/037339fe-e940-43d1-87ef-4056cdd232d3)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@Ameya02 what description do you want to add exactly?

**Comment by Ameya02** [comment]
I want to add a link to to the codespaces repo
Like this https://codespaces.new/rupali-codes/LinksHub
It will open this menu for creating the codespaces
![image](https://github.com/rupali-codes/LinksHub/assets/65841021/f9a9a3fe-1fa5-40c7-9d7e-b2309c37ddac)

**Comment by rupali-codes** [comment]
> I want to add a link to to the codespaces repo Like this https://codespaces.new/rupali-codes/LinksHub It will open this menu for creating the codespaces ![image](https://user-images.githubusercontent.com/65841021/268507606-f9a9a3fe-1fa5-40c7-9d7e-b2309c37ddac.png)

I see, thanks. 

You can start working on it. Assigning to you.
