### ISSUE TITLE
In light mode the tags won't appear on hover

### ISSUE THREAD

**Issue by the-shivam-gupta** [rupali-codes/LinksHub#1673]
In light mode, the centre tags do not appear when hovered over because they are white.

![image](https://github.com/rupali-codes/LinksHub/assets/109647722/5bb7b6ca-3f06-421c-b74e-dfdbbeaa19c3)

**Comment by rupali-codes** [comment]
Thanks for noticing @the-shivam-gupta. Do you want to work on this?

**Comment by the-shivam-gupta** [comment]
Ya plz assign it to me

**Comment by rupali-codes** [comment]
> Ya plz assign it to me

Alright, thanks
