### ISSUE TITLE
[DOCS] Add project-setup steps in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1678]
### Issue Description

Currently, the README file looks so long, it would be better if we can add the project-setup steps into COTNRIBUTING.md file instead. It would make the README.md file shorter and more readable. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
I'll make that edit @rupali-codes

**Comment by rupali-codes** [comment]
> I'll make that edit @rupali-codes

I'm done with this, just out of home, i'll raise the PR soon :)
