### ISSUE TITLE
[BUG] Incorrect alignment of github stats & social media handles

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1680]
### Description

Comment on this issue, if anyone wants to work on this issue.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/1fa3bc2a-ec92-44b3-9a63-a67199bca755)

### Any additional information?

You will have to achieve this structure:

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/3d3c1839-2755-4a80-ad39-79bc752e5e89)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by sohaibsalman** [comment]
Good day @Anmol-Baranwal and @rupali-codes 

I would like to work on this bug, can you please assign this issue to me?

**Comment by CBID2** [comment]
> Good day @Anmol-Baranwal and @rupali-codes 
> 
> 
> 
> I would like to work on this bug, can you please assign this issue to me?

Go right ahead @sohaibsalman! 😊
