### ISSUE TITLE
[BUG] : Contributors Cards doesn't looks right

### ISSUE THREAD

**Issue by PriyansuMaurya** [rupali-codes/LinksHub#1683]
### Description

Upon closer inspection, the presence of the badge has caused a leftward shift in the profile, suggesting room for improvement in the design.

![image](https://github.com/rupali-codes/LinksHub/assets/101447544/6e747221-7bb1-44c0-9cac-7e456444a1dc)

This represents my vision for the card layout. You need not concern yourself with the styling; I will ensure that it harmonizes seamlessly with the overall theme and aesthetic of the website.

![image](https://github.com/rupali-codes/LinksHub/assets/101447544/e7113f27-3253-4164-8a2f-211e989d99a8)

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Based on the mock visual you presented, where would the badges be placed @PriyansuMaurya? I'm struggling with visualizing the new layout.

**Comment by PriyansuMaurya** [comment]
Instead of plus button we will place badges.

![image](https://github.com/rupali-codes/LinksHub/assets/101447544/5378438a-da23-46d9-819a-78abc5cd9944)

**Comment by CBID2** [comment]
> Instead of plus button we will place badges.
> 
> ![image](https://user-images.githubusercontent.com/101447544/269395784-5378438a-da23-46d9-819a-78abc5cd9944.png)

Hmm... I don't know if they could fit well in this layout @PriyansuMaurya. What do you think @Anmol-Baranwal? @rupali-codes?

**Comment by CBID2** [comment]
> I can give it a try, and if it works fine merge it else, request changes at last if it doesn't work out as expected you can close both this issue and the corresponding pull request.

I understand that @PriyansuMaurya, but I think would be best to get @rupali-codes' and @Anmol-Baranwal's perspective on this idea. That way it saves you from wasting time and energy if we end up rejecting the suggestion.   I hope you understand :)

**Comment by rupali-codes** [comment]
> > I can give it a try, and if it works fine merge it else, request changes at last if it doesn't work out as expected you can close both this issue and the corresponding pull request.
> 
> I appreciate your eagerness @PriyansuMaurya, but I think would be best to get @rupali-codes' and @Anmol-Baranwal's perspectives on this idea. That way it saves you from wasting time and energy if we end up rejecting the suggestion. I hope you understand :)

It looks fine to me the way it is, but if @PriyansuMaurya wants to improve than i guess it worth a try. 

But i'm wondering, what @PriyansuMaurya would you be adding in those 3 lines? Like can you draw an example?

**Comment by Anmol-Baranwal** [comment]
`the presence of the badge has caused a leftward shift in the profile`

In the PR that I made for this, it was perfectly aligned but later changed due to preference.

And there will definitely be distractions in the suggested image, but you can definitely work on it.

> I know you would adjust the style
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/941b435b-3c8b-49d0-90e0-e1a76f45b4ed)

@CBID2 @rupali-codes 
I think we should go ahead. Because it maybe worth a try to experiment a new design, it may even be better than what we expect.

There could be one more case, you can directly submit the initial design here that you came up with from localhost, and then we can go ahead if we can improve or change it to something with better UX.

**Comment by CBID2** [comment]
Done @Anmol-Baranwal. Go right ahead @PriyansuMaurya

**Comment by PriyansuMaurya** [comment]
I have made this 2 designs, lets see which one gets more votes and accordingly, I will start implementing it.

![Rectangle 9](https://github.com/rupali-codes/LinksHub/assets/101447544/bb607602-19df-4a5e-934f-7f3ce38165ed)

**Note:** if you don't like either of them, or want some improvements, tell me right away, I am up for it.

**Comment by Anmol-Baranwal** [comment]
> **Note:** if you don't like either of them, or want some improvements, tell me right away, I am up for it.

First one is slightly better, but I don't think this is an efficient way to use negative space.

| Yours | Current |
|:---------:|:------:|
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/3b4653bd-3a5a-4068-915a-17be9db29699) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/3462412b-4993-4bd5-a8dc-59b835dd8602) |

@rupali-codes @CBID2 
What do you think?

**Comment by PriyansuMaurya** [comment]
so, what do you want me to change about negative spacing?

**Comment by Anmol-Baranwal** [comment]
> so, what do you want me to change about negative spacing?

What can you change?

You don't need to develop the whole design, rather open a figma and just design it. Don't waste your time trying different variations. You will automatically know which one is better.

**Comment by PriyansuMaurya** [comment]
> You don't need to develop the whole design, rather open a figma and just design it. Don't waste your time trying to code different variations. You will automatically know which one is better even from the final design.

![Rectangle 9](https://github.com/rupali-codes/LinksHub/assets/101447544/bb607602-19df-4a5e-934f-7f3ce38165ed)

Yeah, you are correct, the design you see above is not a code implementation. I have made it using figma

**Comment by PriyansuMaurya** [comment]
@Anmol-Baranwal should start working on this?

**Comment by rupali-codes** [comment]
@PriyansuMaurya it looks kinda empty, the spacing. I guess it looks better as it as right now

**Comment by PriyansuMaurya** [comment]
> @PriyansuMaurya it looks kinda empty, the spacing. I guess it looks better as it is right now

Your observation is accurate; it appears empty, yet simultaneously it looks clean and elegant. Don't take me wrong, but I would say, "Let's have a vote on this?"

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 
Closing this!

@PriyansuMaurya 
Please take on some other issues, or reopen this if you want to work and make a PR for this.
