### ISSUE TITLE
[BUG] Twitter logo

### ISSUE THREAD

**Issue by rahulpandey70** [rupali-codes/LinksHub#1684]
### Description

Change the `Twitter Logo`.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You're assigned @rahulpandey70! :)
