### ISSUE TITLE
CodeBeauty

### ISSUE THREAD

**Issue by brodante** [rupali-codes/LinksHub#1685]
### Site URL

https://www.youtube.com/@CodeBeauty

### Description of the above provided site

Welcome to **Saldina Nurak**'s channel! With a decade of software engineering expertise, Saldina shares programming tutorials for all levels, answers your tech queries, and adds a touch of fun to the developer's life. Whether you're coding for a career, exams, or pure enjoyment, join us on this knowledge-packed journey!

### Category

Languages

### Sub Category

C++ Programming

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You’re assigned @brodante
