### ISSUE TITLE
[BUG] Show selected subcategory in the sidebar

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1687]
### What would you like to share or ask?

I noticed currently its not showing selected subcategory on the sidebar. Please change the color of selected subcategory to violet, as on hovered and add a left-border to it.

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/d65b9ba6-ef9e-43ba-bb17-0aa4086d1b58)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Vijaykv5** [comment]
I would love to work on this issue :)

**Comment by Vijaykv5** [comment]
This has been working fine in local ..I guess some issues in deployment

**Comment by CBID2** [comment]
> This has been working fine in local ..I guess some issues in deployment

You're assigned @Vijaykv5

**Comment by Vijaykv5** [comment]
> This has been working fine in local ..I guess some issues in deployment

@CBID2  In mine its working fine as expected 

<img width="1433" alt="Screenshot 2023-09-23 at 10 36 26 AM" src="https://github.com/rupali-codes/LinksHub/assets/94985341/faeefc94-7e1c-463c-aaf9-af5354e16286">

**Comment by rupali-codes** [comment]
> > This has been working fine in local ..I guess some issues in deployment
> 
> @CBID2 In mine its working fine as expected
> 
> <img alt="Screenshot 2023-09-23 at 10 36 26 AM" width="1433" src="https://user-images.githubusercontent.com/94985341/270088231-faeefc94-7e1c-463c-aaf9-af5354e16286.png">

Looks great, please raise the PR :)

**Comment by Anmol-Baranwal** [comment]
@Vijaykv5 
Are you interested in contributing?
If not, please let me know so that I can open this up for others to take.

**Comment by Vijaykv5** [comment]
@Anmol-Baranwal will add it today

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal will add it today

Okay, sure.

**Comment by Vijaykv5** [comment]
@Anmol-Baranwal Done a PR. Please check it :)

**Comment by Vijaykv5** [comment]
@Anmol-Baranwal can you add hacktoberfest label in it please

**Comment by rupali-codes** [comment]
this issue was resovled
