### ISSUE TITLE
[BUG] Not showing description of the subcategory

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1688]
### Description

When clicking on the `i` button right to subcategory name, its not showing any description in the popup, its showing the category name. 

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/9b42a1c7-617c-47fd-a2ab-208aac74849c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Vijaykv5** [comment]
Hey @rupali-codes  I would love to work on this issue

**Comment by Vijaykv5** [comment]
@rupali-codes The thing has been working fine in local. The issue is in deployment

**Comment by rahulpandey70** [comment]
> @rupali-codes The thing has been working fine in local. The issue is in deployment

The issue is in local development as well, You can see on screenshot.

![Screenshot from 2023-09-23 09-04-58](https://github.com/rupali-codes/LinksHub/assets/34403988/bffcecd7-1495-45c5-b55e-171841607fcb)

**Comment by rahulpandey70** [comment]
@rupali-codes can i try?

**Comment by rupali-codes** [comment]
> @rupali-codes can i try?

Yeah sure!

**Comment by kumarvivekpandey** [comment]
if you tell i will do it
