### ISSUE TITLE
[BUG] - Section header not having proper horizontal spacing

### ISSUE THREAD

**Issue by JunDevHarsh** [rupali-codes/LinksHub#169]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The header present in different sections not having proper horizontal spacing.

### Screenshots

![home](https://user-images.githubusercontent.com/94737463/218028624-22759a57-0869-4971-b34e-5659eecd3fb1.png)

![other](https://user-images.githubusercontent.com/94737463/218029418-7e4210d9-b599-4ce6-bc39-f95dff8d071f.png)

### What browser are you seeing the problem on?

Chrome

**Comment by JunDevHarsh** [comment]
Can I work on this issue?

**Comment by Mani-mk-mk** [comment]
I have created a PR on this one.

**Comment by rupali-codes** [comment]
@JunDevHarsh This is duplicate. Sorry
