### ISSUE TITLE
[ADD] <Technical Writing/Tools>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1693]
### Category Name

Technical Writing

### Subcategory Name

Tools 

### Additional Context

This issue will be addressed in #1692 too. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
I guess we already have it as `Official Docs`

**Comment by CBID2** [comment]
> I guess we already have it as `Official Docs` 

To clarify @rupali-codes, I mean like technical writing when I say documentation.

**Comment by rupali-codes** [comment]
> > I guess we already have it as `Official Docs`
> 
> To clarify @rupali-codes, I mean like technical writing when I say documentation.

Gotcha, you can start working on it
