### ISSUE TITLE
[Add] <Top 100+ Machine Learning Projects for 2023 [with Source Code]>

### ISSUE THREAD

**Issue by digpatel123** [rupali-codes/LinksHub#1700]
### Site URL

https://www.geeksforgeeks.org/machine-learning-projects/

### Description of the above provided site

In this article, you’ll find the top 100+ latest projects and Ideas on Machine Learning which are beneficial for both beginners as well experienced professionals. These projects are specially made for the students that start their journey in Machine Learning and Data Science.

### Category

Artificial Intelligence

### Sub Category

Machine learning

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Go ahead @digpatel123! :)
