### ISSUE TITLE
[Feature] <Spam PR Prevention workflow>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1702]
### Description

I've heard from other maintainers that spam PRs often occur during Hacktoberfest. I found this [GitHub Action](https://github.com/marketplace/actions/spamtoberfest-pull-request-spam-checker) that aids with this.  

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Hey @Anmol-Baranwal! :) You want to take this on?

**Comment by Anmol-Baranwal** [comment]
Sure, why not.

Thanks for the tag.
