### ISSUE TITLE
[DOCS] <add Hacktoberfest logo to outreach section> 

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1703]
### Issue Description

Since we're participating in this year's Hacktoberfest, let's add it to the [Outreach section](https://github.com/rupali-codes/LinksHub/blob/main/README.md#outreach). 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@CBID2 

Let us do this ourselves. You can take up on this, or assign me if you don't have time and I will complete this on urgent basis.

**Comment by Anmol-Baranwal** [comment]
Also, make sure to add label `up for grabs` and unlock conversations, so that people can comment to take the issues.

**Comment by CBID2** [comment]
Good idea @Anmol-Baranwal!

**Comment by CBID2** [comment]
You're assigned @Anmol-Baranwal
