### ISSUE TITLE
[OTHER] Codecademy : Rectify Typo Error

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#1705]
### What would you like to share or ask?

A typo is present in Open Source projects, specifically in "Codeacademy Docs," where it should be "Codecademy" instead of "Codeacademy."  I have attached a screenshot for your reference.

![Screenshot (38)](https://github.com/rupali-codes/LinksHub/assets/112751524/489fdbff-a78e-42e4-8197-d5ec436d9414)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You're assigned @Shiva-Sai-ssb
