### ISSUE TITLE
[Add] Hugo 

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1709]
### Site URL

https://gohugo.io/

### Description of the above provided site

If you're looking for a framework to help you build your documentation site quickly, check out Hugo.  It allows you to output your content in multiple formats, including JSON or AMP as well as provides shortcodes to simplify your Markdown files. 

### Category

Other

### Sub Category

Tools 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@R055A 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
