### ISSUE TITLE
[OTHER] Missing Category

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1710]
### What would you like to share or ask?

The Technical Writing category is not listed in the dropdown menu of the Add a New Link Issue template. 

Note: I tried doing this PR myself, but decided to close my PR in an effort to give other contributors a chance. This can be done for Hacktoberfest.

## Screenshot
<img width="922" alt="Screenshot of technical writing not appearing" src="https://github.com/rupali-codes/LinksHub/assets/105683440/0284cd7d-348e-4e99-92dc-c2dcb1ddf5de">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@CBID2 
We need to open this up for others to comment, so that we can know. Limiting the conversations to collaborators would not be correct, I think.

**Comment by CBID2** [comment]
> @CBID2 
> 
> We need to open this up for others to comment, so that we can know. Limiting the conversations to collaborators would not be correct, I think.

You're right 😄

**Comment by barkhaaroraa** [comment]
I’d like to work on this

**Comment by AmanB-2003** [comment]
Please assign the issue to me

**Comment by CBID2** [comment]
Hey @barkhaaroraa. Any updates on this?

**Comment by barkhaaroraa** [comment]
hi, i'm currently swamped with exams until October 12th, so I won't be able to tackle the issue right away.

**Comment by Anmol-Baranwal** [comment]
@barkhaaroraa 
It won't take long, just do it whenever you are free. It will merely take 3 minutes to make the changes.

**Comment by barkhaaroraa** [comment]
hi, i've made the necessary changes.
