### ISSUE TITLE
RocketChat Repo to opensource projects link

### ISSUE THREAD

**Issue by dfordp** [rupali-codes/LinksHub#1715]
### Site URL

https://github.com/RocketChat/Rocket.Chat

### Description of the above provided site

Rocket.Chat is an open-source fully customizable communications platform developed in JavaScript for organizations with high standards of data protection.

### Category

Open Source

### Sub Category

Project

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@dfordp you can raise the PR now!

**Comment by dfordp** [comment]
hi @rupali-codes the pull request is already on #1738

**Comment by dfordp** [comment]
I deleted that branch thinking it may cause merge conflicts and made them into separte isseus

**Comment by rupali-codes** [comment]
@dfordp please make sure to close the issue once your gets merged. Thanks
