### ISSUE TITLE
[DOCS] Add featured on hacktober fest in Readme.md

### ISSUE THREAD

**Issue by dfordp** [rupali-codes/LinksHub#1716]
### Issue Description

I believe it would be better if we wrote that this project was featured on hacktober fest allowing more users to join and make contributions to the projects. I mean post hacktober fest

### Screenshots or Examples (if applicable)

![t](https://github.com/rupali-codes/LinksHub/assets/92905896/feeb5ab8-e278-45ea-a5ef-8816d1d8c8c1)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Hi @dfordp. We're way ahead of you on that. This is addressed in another issue and PR

**Comment by CBID2** [comment]
This has been addressed in this [pull request](https://github.com/rupali-codes/LinksHub/pull/1717) @dfordp, so I'm closing this issue.
