### ISSUE TITLE
[CHORE] Make Searchbar fixed at top

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#172]
### What would you like to share or ask?

Current behaviour of searchbar is it's getting scrolled when scrolling the SideNavbar.

#### Specific Requirements

* Make it fixed at top
* Should not overlap any existing element
* Must have the same functionality in mobile/tablet view

**Comment by JunDevHarsh** [comment]
Can I work on this issue?

**Comment by loki1205** [comment]
Hi, I would love to work on this issue. Please, assign this to me.

**Comment by rupali-codes** [comment]
> Can I work on this issue?

Yes, you can go ahead and make PR

**Comment by rupali-codes** [comment]
> Hi, I would love to work on this issue. Please, assign this to me.

Hi, thanks for taking interest in, could you take an eye on other issues, would love to have you

**Comment by JunDevHarsh** [comment]
Thank you for assigning me this task. I am working on it.
