### ISSUE TITLE
[Add] Added Negative Space

### ISSUE THREAD

**Issue by dfordp** [rupali-codes/LinksHub#1723]
### Site URL

https://negativespace.co/

### Description of the above provided site

Beautiful free images for personal and commercial use.

### Category

Frontend

### Sub Category

images

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You’ve been assigned @dfordp. I’m going to reopen your PR now. Remember, your issue must be approved by the maintainers and assigned to you before you create a PR. Happy Hacktoberfest! 😊
