### ISSUE TITLE
[BUG] CSS bug in tooltip hover centering

### ISSUE THREAD

**Issue by yashnirmal** [rupali-codes/LinksHub#1725]
### Description

When hovering on tooltip icon, the description is slightly off centered 

### Screenshots

<img width="400" alt="Screenshot 2023-10-01 at 4 09 34 PM" src="https://github.com/rupali-codes/LinksHub/assets/78169683/5c53f8f4-78fc-43dc-bad2-f1c9697f5c09">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@yashnirmal 
We are neglecting this now, but in the future, you need to allow us to assign you the issue before you start working and submit a PR. Not following this process will require us to close your pull request.

This is outlined in the contributing guidelines.
![image](https://user-images.githubusercontent.com/74038190/271955538-4a4cf1b9-0dae-4fea-8b2e-1f57423c741f.png)
