### ISSUE TITLE
[Add] Add Rocket Chat

### ISSUE THREAD

**Issue by dfordp** [rupali-codes/LinksHub#1729]
### Site URL

https://github.com/RocketChat/Rocket.Chat

### Description of the above provided site

[Rocket.Chat](https://rocket.chat/) is an open-source fully customizable communications platform developed in JavaScript for organizations with high standards of data protection.

### Category

Frontend

### Sub Category

open source project

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Hi @dfordp. Do you still want to work on this issue?

**Comment by dfordp** [comment]
Yup

**Comment by CBID2** [comment]
You're assigned @dfordp
