### ISSUE TITLE
[OTHER] Mandatory Changes

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1730]
### What would you like to share or ask?

I will do everything in this PR so that only 1 needs to be merged, and let me know if there are any more requirements.

- [ ] Add a workflow to close PRs that have unassigned issues and bot leaves a message
- [x] Add labels on the issue forms for the `priority ones`
- [x] Update workflow to add priority labels in pr which add labels based on keywords like `feat` or `chore`, it will help us avoid adding labels manually.
- [ ] Update PR template to ask if they are participating in hacktoberfest, and if the option is yes. Then the bot will automatically add the `hacktoberfest-accepted` label on merged PR.
- [x] Removing the limit to fetch all contributors, since every contribution matters.

@CBID2 
> Just edit this description, whatever you want to add.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
> ### What would you like to share or ask?
> 
> 
> 
> I will do everything in this PR so that only 1 needs to be merged, and let me know if there are any more requirements.
> 
> 
> 
> - [ ] Add a workflow to close PRs that have unassigned issues and bot leaves a message
> 
> - [ ] Add labels on the issue forms for the `priority ones`
> 
> - [ ] Update workflow to add priority labels in pr which add labels based on keywords like `feat` or `chore`, it will help us avoid adding labels manually.
> 
> - [ ] Update PR template to ask if they are participating in hacktoberfest, and if the option is yes. Then the bot will automatically add the `hacktoberfest-accepted` label on merged PR.
> 
> 
> 
> @CBID2 
> 
> > Just edit this description, whatever you want to add.
> 
> 
> 
> 
> 
> ### Checklist
> 
> 
> 
> - [X] I have checked the existing issues
> 
> - [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
> 
> - [X] I am willing to work on this issue (optional)

Good idea

**Comment by rupali-codes** [comment]
@Anmol-Baranwal go for it
