### ISSUE TITLE
[Add] Getting Started with open source tutorial

### ISSUE THREAD

**Issue by dfordp** [rupali-codes/LinksHub#1731]
### Site URL

https://www.youtube.com/watch?v=yzeVMecydCE&t=1792s&ab_channel=freeCodeCamp.org

### Description of the above provided site

Description of the above provided site
Learn why and how to contribute to open source software. You will learn about how to find projects to contribute to, how to make issues and PRs, how to make money from open source, and more.

Category
Resources

### Category

Resources

### Sub Category

youtube video

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
Not needed. This is already included to the LinksHub for the respective categories.
