### ISSUE TITLE
[OTHER] add Maintainers Info in readme

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1732]
### What would you like to share or ask?

- With usernames and clear instructions on how to tag the moderators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@CBID2 
If you face any problem, let me know.

**Comment by CBID2** [comment]
> @CBID2 
> 
> If you face any problem, let me know.

Sure will @Anmol-Baranwal

**Comment by CBID2** [comment]
> @CBID2 If you face any problem, let me know.

I decided to unassign myself. Someone else can do it for Hacktoberfest

**Comment by Anmol-Baranwal** [comment]
> > @CBID2 If you face any problem, let me know.
> 
> I decided to unassign myself. Someone else can do it for Hacktoberfest

I think, it would be better if we can do this ourselves. We have a better understanding, and explaining things to new contributors just take more time. I will do this properly

@CBID2 
I'm assigning this to myself. If you want to work on this, feel free to unassign me.

**Comment by CBID2** [comment]
> > > @CBID2 If you face any problem, let me know.
> > 
> > 
> > I decided to unassign myself. Someone else can do it for Hacktoberfest
> 
> I think, it would be better if we can do this ourselves. We have a better understanding, and explaining things to new contributors just take more time. I will do this properly
> 
> @CBID2 I'm assigning this to myself. If you want to work on this, feel free to unassign me.

Ok :)

**Comment by Anmol-Baranwal** [comment]
@CBID2 
I'm trying something different.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/10f53fca-83da-4e5c-ad67-5aa0ad6ee4a6)

or 

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/c1ee33ca-ca42-400c-ad9e-754c488267b5)

Which do you like?

I prefer the first one, even if the name isn't as prominent as the username, because the main idea is to help contributors find the maintainer's username for us to tag.

The design looks cool right😅

**Comment by CBID2** [comment]
> @CBID2 
> 
> I'm trying something different.
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/10f53fca-83da-4e5c-ad67-5aa0ad6ee4a6)
> 
> 
> 
> or 
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/c1ee33ca-ca42-400c-ad9e-754c488267b5)
> 
> 
> 
> Which do you like?
> 
> 
> 
> I prefer the first one, even if the name isn't as prominent as the username, because the main idea is to help contributors find the maintainer's username for us to tag.
> 
> 
> 
> The design looks cool right😅

I like number 1 as well @
