### ISSUE TITLE
[Feature] redirect to the corresponding section based on options in empty page screen

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1735]
### Description

So, these options would be clickable such as `Online Code Editors` and would redirect the users to the corresponding section.

I wanted to contribute this, but I would open issues for others to grab.

@rupali-codes @CBID2 
What do you think?

If you agree, then add `up for grabs`, and `hacktoberfest` labels.

### Screenshots

> I hope you get the idea
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/94f7194a-fe58-4af8-aca3-4d9c5ac3421d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
I think this could be a `Hacktoberfest` issue @Anmol-Baranwal. We should probably focus on more on reviewing contributions and adding PRs for `priority: high` issues. Does that make sense?

**Comment by Anmol-Baranwal** [comment]
> I think this could be a `Hacktoberfest` issue @Anmol-Baranwal. We should probably focus on more on reviewing contributions and adding PRs for `priority: high` issues. Does that make sense?

I don't think, we will receive high priority PRs. We will review all of them.

Yeah, just opening up PRs so that people can directly pick up.

Because LinksHub is very strict, and people would have to think hard if they want to add a feature. This may be suitable for beginners.

**Comment by CBID2** [comment]
> > I think this could be a `Hacktoberfest` issue @Anmol-Baranwal. We should probably focus on more on reviewing contributions and adding PRs for `priority: high` issues. Does that make sense?
> 
> 
> 
> I don't think, we will receive high priority PRs. We will review all of them.
> 
> 
> 
> Yeah, just opening up PRs so that people can directly pick up.
> 
> 
> 
> Because LinksHub is very strict, and people would have to think hard if they want to add a feature. This may be suitable for beginners.

Sorry. I meant to say high priority issues that we want to work on @Anmol-Baranwal.

**Comment by Anmol-Baranwal** [comment]
> Sorry. I meant to say high priority issues that we want to work on @Anmol-Baranwal. 

Got that.

**Comment by Ameya02** [comment]
Can I Work on this?

**Comment by CBID2** [comment]
> Can I Work on this?

Are you doing Hacktoberfest @Ameya02?

**Comment by Ameya02** [comment]
Yes

**Comment by CBID2** [comment]
> Yes

You're assigned @Ameya02

**Comment by Ameya02** [comment]
![linkshub](https://github.com/rupali-codes/LinksHub/assets/65841021/97eb8a23-5793-40d0-8e49-cd101fe3eaff)
Here is my solution

**Comment by Anmol-Baranwal** [comment]
@Ameya02 
Raise a PR.
