### ISSUE TITLE
[Add] Remote job finding resouce 

### ISSUE THREAD

**Issue by dfordp** [rupali-codes/LinksHub#1739]
### Site URL

https://remoteintech.company

### Description of the above provided site

A list of semi to fully remote-friendly companies in or around tech.

### Category

Resources

### Sub Category

website

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
As mentioned in the contributing guidelines
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/e5ff31fa-350b-45e7-9ae9-7afa1d82bdb0)

I'm opening this up for others to grab.

You already have issues assigned to you.

**Comment by dfordp** [comment]
My pull requests have been created and require a second review the pull requests are #1738 and #1728 can you please review them so I can work on this issue then

**Comment by Anmol-Baranwal** [comment]
@dfordp 
Please be patient, and don't tag us repeatedly.

It takes time, and we will do it accordingly.

> I don't know why you all are in such a rush, you will get your point.

**Comment by dfordp** [comment]
Sorry I will try and be more patient now. It was just a lil overwhelming

**Comment by CBID2** [comment]
> Sorry I will try and be more patient now. It was just a lil overwhelming

I get it @dfordp. Just take a deep breath, it'll all be fine. 😄  I was pretty overwhelmed when I first started in open source, but what calmed me down is that things will be looked at eventually and to just think of making a pull request like cooking. If you cook it at the right temperature and give a balanced amount of seasoning, you get something beautiful everyone will enjoy! 😄

**Comment by Anmol-Baranwal** [comment]
> > Sorry I will try and be more patient now. It was just a lil overwhelming
> 
> I get it @dfordp. I was pretty overwhelmed when I first started in open source, but what calmed me down is that things will be looked at eventually and to just think of making a pull request like cooking. If you cook it at the right temperature and give a balanced amount of seasoning, you get something beautiful everyone will enjoy! 😄

WOW! 😁

**Comment by CBID2** [comment]
> > > Sorry I will try and be more patient now. It was just a lil overwhelming
> 
> > 
> 
> > I get it @dfordp. I was pretty overwhelmed when I first started in open source, but what calmed me down is that things will be looked at eventually and to just think of making a pull request like cooking. If you cook it at the right temperature and give a balanced amount of seasoning, you get something beautiful everyone will enjoy! 😄
> 
> 
> 
> WOW! 😅

lol, I just had to spread some wisdom you know :)

**Comment by Anmol-Baranwal** [comment]
@dfordp 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by CBID2** [comment]
> @dfordp 
> 
> I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance. 

And me too lol

**Comment by Anmol-Baranwal** [comment]
> > @dfordp
> > I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
> 
> And me too lol

Let me update the saved reply. !
