### ISSUE TITLE
[Add] <add Killercoda>

### ISSUE THREAD

**Issue by Ayaan49** [rupali-codes/LinksHub#1740]
### Site URL

https://killercoda.com/

### Description of the above provided site

Killercoda is an interactive learning platform which allows everyone to access Linux|Kubernetes based environments just in their browser.

### Category

Other

### Sub Category

Dev Tools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You're assigned now @Ayaan49! :)

**Comment by Ayaan49** [comment]
Hey @CBID2, thank you. May I get the hacktoberfest tag if possible?

**Comment by CBID2** [comment]
> Hey @CBID2, thank you. May I get the hacktoberfest tag if possible? 

Absolutely @Ayaan49! :)
