### ISSUE TITLE
[ADD] Mamba UI on Frontend/UI generators

### ISSUE THREAD

**Issue by mahfuzurrahman01** [rupali-codes/LinksHub#1741]
### Category Name

Frontend

### Subcategory Name

UI Generators

### Additional Context

I want to add Mamba UI to the Frontend sub-category UI generators list.
**Mamba UI is a free, open-source collection of UI components and templates based on Tailwind CSS.**
[Mamba UI](https://www.mambaui.com/)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You're assigned @mahfuzurrahman01! :) Are you partaking in Hacktoberfest?

**Comment by mahfuzurrahman01** [comment]
Thank you for assigning this issue to me! I'm excited to contribute to the project.
And "Yes" I'm participating in Hacktoberfest.

**Comment by mahfuzurrahman01** [comment]
I've gone through your suggested changes and changed the description and committed my changes. is that OK now?
