### ISSUE TITLE
[BUG] Search bar suggestion inputs the wrong name in the query

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1746]
### Description

- You can watch the tutorial, and read more about the issue here:

https://jam.dev/c/05715bdb-fa75-4af0-a98f-fb020f3f643c

- We need to accomplish these two things:
   - When clicking the suggestion, it should redirect to that subcategory
   - When we click on the suggestion, it should pull the name of subcategory rather than the file name

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Olaleye-Blessing** [comment]
Could assign this to me under `hacktoberfest`?

**Comment by rahulpandey70** [comment]
@Anmol-Baranwal can I try?

**Comment by Anmol-Baranwal** [comment]
@rahulpandey70 
Since Olaleye asked earlier, I'm assigning this issue to him.

Feel free to check other issues with `up for grabs`, or you can create a new issue.
