### ISSUE TITLE
[Add] C# Projects

### ISSUE THREAD

**Issue by SargamPuram** [rupali-codes/LinksHub#1748]
### Site URL

https://www.interviewbit.com/blog/c-sharp-projects/

### Description of the above provided site

This website provides free fifteen beginner to advanced level C# projects with source code.
Kindly can I please get the hactoberfest label.

### Category

Resources

### Sub Category

Project Ideas

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@SargamPuram 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by SargamPuram** [comment]
@Anmol-Baranwal  thanks for assigning me this issue! I'll start working on it.
