### ISSUE TITLE
[BUG] : Remove `-/` before category name

### ISSUE THREAD

**Issue by rahulpandey70** [rupali-codes/LinksHub#1749]
### Description

Remove `-/` before category name

### Screenshots

![Screenshot from 2023-10-02 16-47-09](https://github.com/rupali-codes/LinksHub/assets/34403988/44f29d90-75d7-46b0-9590-3dd3a9e3ce39)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@rahulpandey70,
This is not a bug; it's a design choice. It's intended, and for any changes, please consult with @rupali-codes. If she agrees, you can proceed.

However, I believe the current design is quite good, and it gives off a strong tech vibe.

**Comment by rahulpandey70** [comment]
@rupali-codes what you think about removing `-/` before category name.

**Comment by CBID2** [comment]
I agree with @Anmol-Baranwal here @rahulpandey70. Having `/` as a design makes the subcategory look more interesting.
