### ISSUE TITLE
[Feature] All Contributors and Remove Labels 

### ISSUE THREAD

**Issue by Vijaykv5** [rupali-codes/LinksHub#1753]
### Description

Add all contributors [here](https://www.linkshub.dev/contributors)
As it will retain the image of Open source.
 also I think is it mandatory to add a label as maintainer and contributors there?

### Screenshots

<img width="1438" alt="Screenshot 2023-10-02 at 6 07 13 PM" src="https://github.com/rupali-codes/LinksHub/assets/94985341/2b4ad2c4-aa13-4bcb-9493-3e045c9bfff8">

What if we remove the tags and add all people who have contributed to this project.
I think that will be really a gem for contributors!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Hi @Vijaykv5! 😃 Thanks for your suggestion. The purpose of the labels is to help people who come to LinksHub know who will help them in the contribution process, so I don't think we should remove them. What do you think @Anmol-Baranwal & @rupali-codes?

**Comment by Anmol-Baranwal** [comment]
Yeah! We shouldn't.

They can get the list of usernames to tag if they face any problem. 

Plus, I have already done the task of fetching all contributors in #1734

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/1092efea-eb63-4438-94d8-0a6b258d9cf5)

> I'm closing this, as discussed.
