### ISSUE TITLE
[Feature] Make menu auto closing

### ISSUE THREAD

**Issue by Palakkgoyal** [rupali-codes/LinksHub#1757]
### Description

On small devices when a user choose an option from the menu, the menu doesn't close automatically. The user has to manually do it. I want to fix that.

### Screenshots

![Screenshot 2023-10-02 225607](https://github.com/rupali-codes/LinksHub/assets/116902573/9301bd41-dd46-4e5b-81bd-2e583e8ff565)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
> Sounds interesting @Palakkgoyal. Will this feature be accessible though? We want to make sure that _all_ people can use LinksHub.

Yeah, according to him. Whenever a user clicks on a option in menu, it will automatically redirect to the corresponding section.

@Palakkgoyal 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Palakkgoyal** [comment]
> Sounds interesting @Palakkgoyal. Will this feature be accessible though? We want to make sure that _all_ people can use LinksHub.

Yes, sure it will be
