### ISSUE TITLE
[Bugs] : Content not found 

### ISSUE THREAD

**Issue by rahulpandey70** [rupali-codes/LinksHub#1758]
### Site URL

https://www.linkshub.dev/languages/cpp

### Description of the above provided site

No content found in `languages > c ++ programming` 

### Category

Languages

### Sub Category

c++ 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You've been assigned @rahulpandey70

**Comment by Anmol-Baranwal** [comment]
It is a bug @rahulpandey70 . As you can see, there are resources present in this subcategory,

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/94177dea-3872-4bd5-984f-4bd6b2e601b4)

Don't add a new resource, there must be a issue while referencing the category name. Refer to contributing guidelines.
