### ISSUE TITLE
[Add] NextUI within NextJs sub-category

### ISSUE THREAD

**Issue by DylanP97** [rupali-codes/LinksHub#1762]
### Site URL

https://nextui.org/

### Description of the above provided site

Beautiful, fast and modern React UI library.
NextUI provides a custom TailwindCSS plugin that allows you to customize the default themes or create your own.
NextUI components are built on top of [React Aria](https://react-spectrum.adobe.com/react-aria/) ensuring exceptional accessibility support as a top priority.

### Category

Frontend

### Sub Category

Next Js

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [x] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@DylanP97 you're assigned

**Comment by coderKrysio** [comment]
Please assign me this issue.
