### ISSUE TITLE
[Feature] Add auth and databasing [special rewards]

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1766]
### Description

> We will closely work with you and complete these. Go to respective issues, read the instructions and if you can complete them, then comment and we will discuss further.

> These features would be available on completing Auth.

- [x] #1852

   - We basically just need a GitHub Auth, as people who want to contribute must have their GitHub, so that they can directly create issues from the dashboard.
   - We will follow proper conventions like middleware.ts based on the logic

- [x] #1853 

   - Create `upvoting` system for resources so that LinksHub user's can filter out the resources and use LinksHub more effortlessly 

      - We will follow proper logic and it will be synced from firestore database
      - We will focus on two main things:
         - A authenticated user can only upvote a resource once
         - Keep count of how many times a resource has been updated
         - Keep count of upvoted resources by a user (not necessary depending upon the logic)

- [ ] #1854 

   - Take `feedback`, taking feedback from LinksHub user's and other people would help making it more better, we can use something a like a form and store the feedbacks in database, then create a sperate page and display all the feedbacks in there

   - There will be a simple CTA, to submit the quick feedback. We can either store it in the database, or we can use this to create a comment in a discussion based on the data.

- [x] #1853 
    
   - Add `database`, we would need database to store `user's data`, the `resources` and feedbacks in different documents
   
   - We will use Firestore with security rules.

- [x] #1852
   
   - We will include a header, with a simple popup to show the data and the basic profile info.

For reference: 
![Screenshot 2023-10-05 100017](https://github.com/rupali-codes/LinksHub/assets/74038190/29f5063c-260c-4e06-a86e-c90ccee4a0fa)

> For more, reference you can read here: https://github.com/rupali-codes/LinksHub/issues/731#issuecomment-1566209719. It may not be what we are trying to achieve, but we can get the idea.

> There are many more possibilities like creating issues from dashboard after Auth. But it will be handled later on.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
I would do this tomorrow. Then we can move forward step-by-step.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes,

I have removed the dashboard part and added brief descriptions. We will expand on this properly when we create individual issues.

Should we proceed? You need to create Firebase credentials. Also, create a Discord channel for this purpose; we will invite these contributors there to address any doubts they may have, which I'm sure there will be many of.

Additionally, perhaps we should consider creating a new channel permanently so that these contributors can stay in touch with us. These are complex features and they should definitely be rewarded for this.

Please create Firebase credentials, and I will create separate issues. Just let me know one thing: how will they get access to the database?

We must handle these tasks thoroughly, and we'll need to update everything from scratch.

**Comment by rupali-codes** [comment]
> @rupali-codes,
> 
> I have removed the dashboard part and added brief descriptions. We will expand on this properly when we create individual issues.
> 
> Should we proceed? You need to create Firebase credentials. Also, create a Discord channel for this purpose; we will invite these contributors there to address any doubts they may have, which I'm sure there will be many of.
> 
> Additionally, perhaps we should consider creating a new channel permanently so that these contributors can stay in touch with us. These are complex features and they should definitely be rewarded for this.
> 
> Please create Firebase credentials, and I will create separate issues. Just let me know one thing: how will they get access to the database?
> 
> We must handle these tasks thoroughly, and we'll need to update everything from scratch.

@Anmol-Baranwal please create sperate issues for this :)

**Comment by rupali-codes** [comment]
@Anmol-Baranwal there you go! I have created this [this](https://discord.gg/tMAJBqAq) channel. should i make it private as well?

**Comment by Anmol-Baranwal** [comment]
> > @rupali-codes,
> > I have removed the dashboard part and added brief descriptions. We will expand on this properly when we create individual issues.
> > Should we proceed? You need to create Firebase credentials. Also, create a Discord channel for this purpose; we will invite these contributors there to address any doubts they may have, which I'm sure there will be many of.
> > Additionally, perhaps we should consider creating a new channel permanently so that these contributors can stay in touch with us. These are complex features and they should definitely be rewarded for this.
> > Please create Firebase credentials, and I will create separate issues. Just let me know one thing: how will they get access to the database?
> > We must handle these tasks thoroughly, and we'll need to update everything from scratch.
> 
> @Anmol-Baranwal please create sperate issues for this :)

Sure. I will do it till the evening.

**Comment by rupali-codes** [comment]
> > > @rupali-codes,
> > > I have removed the dashboard part and added brief descriptions. We will expand on this properly when we create individual issues.
> > > Should we proceed? You need to create Firebase credentials. Also, create a Discord channel for this purpose; we will invite these contributors there to address any doubts they may have, which I'm sure there will be many of.
> > > Additionally, perhaps we should consider creating a new channel permanently so that these contributors can stay in touch with us. These are complex features and they should definitely be rewarded for this.
> > > Please create Firebase credentials, and I will create separate issues. Just let me know one thing: how will they get access to the database?
> > > We must handle these tasks thoroughly, and we'll need to update everything from scratch.
> > 
> > 
> > @Anmol-Baranwal please create sperate issues for this :)
> 
> Sure. I will do it till the evening.

Alright, thanks
