### ISSUE TITLE
[BUG] Pagination Button in dark mode

### ISSUE THREAD

**Issue by rahulpandey70** [rupali-codes/LinksHub#1767]
### Description

In Dark mode pagination button background should be dark but it's white, in light mode it looks good.

### Screenshots

![Screenshot from 2023-10-03 14-21-38](https://github.com/rupali-codes/LinksHub/assets/34403988/22344284-7bef-4da6-82eb-e39834f21409)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@CBID2 
What do you think? 

Current one seems good, but it can be changed if other moderators agree.

**Comment by CBID2** [comment]
> @CBID2 
> 
> What do you think? 
> 
> 
> 
> Current one seems good, but it can be changed if other moderators agree.

I like the current design too

**Comment by Anmol-Baranwal** [comment]
> > @CBID2
> > What do you think?
> > Current one seems good, but it can be changed if other moderators agree.
> 
> I like the current design too

Closing this issue! 

@rahulpandey70 
Thanks for opening the issue for the suggestion. You can take issues with `up for grabs` or create new ones.
