### ISSUE TITLE
[Add] AAmini's YouTube channel

### ISSUE THREAD

**Issue by darshbaxi** [rupali-codes/LinksHub#1768]
### Site URL

https://www.youtube.com/@AAmini/featured

### Description of the above provided site

AAmini's YouTube channel is a valuable resource for anyone interested in diving deep into the world of TensorFlow. With a focus on machine learning, artificial intelligence, and TensorFlow tutorials, this channel offers a wealth of knowledge and practical insights.
From beginner-friendly introductions to advanced techniques, AAmini covers a wide range of topics within the TensorFlow framework. You'll find tutorials, demos, and hands-on examples that will help you understand and implement machine learning models using TensorFlow.

### Category

Youtube

### Sub Category

TensorFlow

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@darshbaxi 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
