### ISSUE TITLE
[BUG] Position of PageNo -1,2 is floating

### ISSUE THREAD

**Issue by Vidip-Ghosh** [rupali-codes/LinksHub#1769]
### Description

<img width="1680" alt="Screenshot 2023-10-03 at 16 20 17" src="https://github.com/rupali-codes/LinksHub/assets/91741581/9e0776ea-1770-455c-a955-2e740e8fbbca">
The position of page no thing should be fixed & constant. But it appears to be floating. I've highlighted that thing. 

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/91741581/5a71469a-2133-4683-964b-d2382cc3dce4

### Any additional information?

Please assign this issue to me under Hacktoberfest 2023

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Vidip-Ghosh 
I don't understand, could you tell me more about what you want to change in the pagination.

**Comment by Vidip-Ghosh** [comment]
@Anmol-Baranwal the pagination thing position should be fixed at bottom but the problem occuring is that, it is floating and changing its position with scroll

**Comment by Anmol-Baranwal** [comment]
@Vidip-Ghosh 
I have checked, and it is fixed according to the window and the postion doesn't change on scroll.

On what device are you checking, it seems okay on Large devices (desktop)

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh I have checked, and it is fixed according to the window and the postion doesn't change on scroll.
> 
> On what device are you checking, it seems okay on Large devices (desktop)

Yeah I'm also checking in desktop

**Comment by Vidip-Ghosh** [comment]
<img width="1676" alt="Screenshot 2023-10-04 at 12 01 25" src="https://github.com/rupali-codes/LinksHub/assets/91741581/879a6f77-1b06-46b4-a632-5e0dfd09398b">
But see this. 
It's in between the contents. It looks odd.

**Comment by Anmol-Baranwal** [comment]
Yeah, it looks odd. But it isn't changing the position on scroll.

We are looking into it as part of internal team. So, I would say just pick up other issues. We may not change it or remove it altogether depending upon the views of the team.

@rupali-codes @CBID2 
What do you think?

**Comment by CBID2** [comment]
> Yeah, it looks odd. But it isn't changing the position on scroll.
> 
> 
> 
> We are looking into it as part of internal team. So, I would say just pick up other issues. We may not change it or remove it altogether depending upon the views of the team.
> 
> 
> 
> @rupali-codes @CBID2 
> 
> What do you think?

I really like the navigation page. It makes things easier to scroll

**Comment by Anmol-Baranwal** [comment]
Closing this!

As discussed. @Vidip-Ghosh Please look for other issues with `up for grabs` or create new ones.
