### ISSUE TITLE
[ADD] Including Solidity as a subcategory within the Language category

### ISSUE THREAD

**Issue by Yash9276** [rupali-codes/LinksHub#1771]
### Category Name

Language

### Subcategory Name

Solidity

### Additional Context

There is no subcategory for language solidity which is neccasary for someone who wants to step in blockchain field. To make 
learning process of web3 easier , I want to add some recoureses like some  docs, youtube channel and some web-tutorials  which
will cover solidity from basic to advanced.  

<h2>Resources</h2>
<option>
<ul></ul>
<ul></ul>
</option>

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Yash9276 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Shiva-Sai-ssb** [comment]
> @Yash9276 I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

Hey, if @Yash9276 doesn't want to work, can you please assign this issue to me? I'll submit the Pull request ASAP. Thanks.

**Comment by TIDYMOUSE** [comment]
@Anmol-Baranwal  I've already made the PR. This is my first ever open source contribution. I'm open to any further additions to my PR if any. Thank You.
