### ISSUE TITLE
[BUG] Pagination BTN not centred

### ISSUE THREAD

**Issue by TreciaKS** [rupali-codes/LinksHub#1780]
### Description

I use Chrome 
- Pagination UI is not centred on devices iPad Mini and Kindle Fire HDX
- The problem is the parent that holds the btn (child) is set to absolute position, remove it, the button will be centred throughout different resolutions

### Screenshots

<img width="785" alt="Screenshot 2023-10-03 at 17 24 03" src="https://github.com/rupali-codes/LinksHub/assets/82657928/9b3e2be8-534a-4ac4-9286-5ad1370ba111">
<img width="778" alt="Screenshot 2023-10-03 at 17 24 18" src="https://github.com/rupali-codes/LinksHub/assets/82657928/314bb392-7098-4689-8127-f0f6f5bd8700">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@TreciaKS 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
