### ISSUE TITLE
[Feature] Adding a quicksearch shortcut.

### ISSUE THREAD

**Issue by raghav1030** [rupali-codes/LinksHub#1781]
### Description

It feels difficult for a user to click on the search bar every time. So I suggest adding a shortcut key like '/' to navigate to search bar whenever pressed.

ps : I am willing to contribute this under hacktoberfest ' 23

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
> Sounds interesting @raghav1030. What do you think @Anmol-Baranwal?

Yeah, it will improve the user experience. Just one thing, we would need to showcase shortcuts. 

@CBID2 @rupali-codes 
Let's do something crazy.

Let's make LinksHub with a command search feature like GitHub. I will complete this future feature myself if approved.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/32f297e5-7796-40a4-ab20-7418e5c344f2)

**Comment by Anmol-Baranwal** [comment]
@raghav1030 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Anmol-Baranwal** [comment]
> What's the benefit of that feature @Anmol-Baranwal?

It improves accessibility; we can navigate directly through the keyboard, which might be helpful for someone who cannot navigate using a mouse.

Suppose I have the option to search various categories just by pressing `Ctrl + K`, and we can copy the URL, visit, and do everything without touching the mouse.
