### ISSUE TITLE
[ADD] Offensive security resourcses

### ISSUE THREAD

**Issue by Gobinath-B** [rupali-codes/LinksHub#1785]
### Category Name

Offensive security

### Subcategory Name

books,paltforms,events,communities

### Additional Context

offensive security category has very limited open source resources so it is essential to provide it in a organized web app

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Gobinath-B 
What do you mean by Offensive security? I don't even think this as a relevant category, unless it's related to cybersecurity.

**Comment by Gobinath-B** [comment]
@Anmol-Baranwal In cybersecurity there are many categories like threat analysis, malware analysis, Blue Team defensive security and offensive security. In offensive security , security researchers finds security bugs and report to the organizations. There is limited resources for this domain.

**Comment by Gobinath-B** [comment]
I have experience in this domain

**Comment by Anmol-Baranwal** [comment]
> I have experience in this domain, **@Anmol-Baranwal**   Okay i will collect and update the whole resources for all the subdomains of cybersecurity.
> 

We certainly don't expect you to add lots of resources. 

I will let you know tomorrow evening. I need to be sure, if this category is relevant.

**Comment by Anmol-Baranwal** [comment]
@Gobinath-B 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

Make a different category -> `Cybersecurity` then maybe add 2-3 high priority subcategories.

If you have doubt, you can of course raise a draft PR.

**Comment by Gobinath-B** [comment]
@Anmol-Baranwal I implemented the module and raised a PR. please review and merge the code.
