### ISSUE TITLE
[Add] Add rustlings to Rust

### ISSUE THREAD

**Issue by bencinn** [rupali-codes/LinksHub#1788]
### Site URL

https://rustlings.cool/

### Description of the above provided site

This project contains small exercises to get you used to reading and writing Rust code.

### Category

Languages

### Sub Category

Rust

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @bencinn! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely.
