### ISSUE TITLE
[Add] Remix Icon

### ISSUE THREAD

**Issue by akshayitzme** [rupali-codes/LinksHub#1791]
### Site URL

https://remixicon.com/

### Description of the above provided site

Remix Icon is a website that provides Simply Delightful Icons free for both personal and commercial use.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @akshayitzme! :) Now keep these in mind as we continue your contribution:

Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
