### ISSUE TITLE
[Add] Eva Icons

### ISSUE THREAD

**Issue by akshayitzme** [rupali-codes/LinksHub#1792]
### Site URL

https://akveo.github.io/eva-icons/

### Description of the above provided site

Eva Icons is a pack of more than 480 beautifully crafted Open Source icons for common actions and items.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@akshayitzme 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
