### ISSUE TITLE
[Add] Iconoir Icons

### ISSUE THREAD

**Issue by akshayitzme** [rupali-codes/LinksHub#1793]
### Site URL

https://iconoir.com/

### Description of the above provided site

A high-quality selection of free icons. Has over 1,368 icons ready to use for your projects.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [x] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@akshayitzme 
#1792 is already assigned to you.

It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.

**Comment by akshayitzme** [comment]
> @akshayitzme #1792 is already assigned to you.
> 
> It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.

#### Okay, I'm leaving this for others to grab!

**Comment by Anmol-Baranwal** [comment]
@C0dewordSky 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
