### ISSUE TITLE
[Add] <Add new youtube tutorial link for competitive programming>

### ISSUE THREAD

**Issue by sravangorati2001** [rupali-codes/LinksHub#1794]
### Site URL

https://www.youtube.com/@codencode

### Description of the above provided site

This channel offers one of the best playlists for competitive programming, covering topics from beginner-level number theory to advanced topics like dynamic programming, graph theory, bit manipulations, and segment trees. The videos are explained in a very clear and easy-to-understand way.

### Category

Competitive Programming

### Sub Category

Tutorials

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @sravangorati2001! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
