### ISSUE TITLE
Add clerk

### ISSUE THREAD

**Issue by Toyin5** [rupali-codes/LinksHub#1796]
### Site URL

https://clerk.com/

### Description of the above provided site
From the website: 
Clerk is more than a "sign-in box." Integrate complete user management UIs and APIs, purpose-built for React, Next.js, and the Modern Web.

### Category

Backend

### Sub Category

Authentication 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Toyin5 
Update the description section of the issue, then I will assign you accordingly.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/349fab16-a9ee-46e8-b5bc-a0c003760372)

**Comment by Toyin5** [comment]
@Anmol-Baranwal done

**Comment by Anmol-Baranwal** [comment]
> @Toyin5 thanks.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Manmit124** [comment]
@Anmol-Baranwal  please assign me this issue

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal please assign me this issue

This is already assigned to `Toyin5`. Pick up other issues with tag: `up for grabs` or create new ones.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal please assign me this issue

This is already assigned to `Toyin5`. Pick up other issues with tag: `up for grabs` or create new ones.

**Comment by Toyin5** [comment]
Pls, @Anmol-Baranwal don't forget the hacktoberfest tag

**Comment by Anmol-Baranwal** [comment]
> Pls, @Anmol-Baranwal don't forget the hacktoberfest tag

LOL! At least check before asking us. It is already added, no need to worry.
