### ISSUE TITLE
[Add] jsitor to online code editors

### ISSUE THREAD

**Issue by akshayitzme** [rupali-codes/LinksHub#1797]
### Site URL

https://jsitor.com/

### Description of the above provided site

An advanced editor to write, test, and share JavaScript, CSS, and HTML snippets. Supports TypeScript and libraries too. 

### Category

Frontend

### Sub Category

online code editors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@akshayitzme 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 

> #1792 is already assigned to you.

**Comment by akshayitzme** [comment]
> @akshayitzme It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.
> 
> > #1792 is already assigned to you.

![image]()

Okay.. leave this issue for others to grab

**Comment by akshayitzme** [comment]
> @akshayitzme It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.
> 
> > #1792 is already assigned to you.
<img src="https://media3.giphy.com/media/l0MYM3IHYHaeQwfdu/giphy.gif" width="250"/>

#### Okay. Leaving this for others to grab!

**Comment by raghav1030** [comment]
Please assign it to me under hacktober fest?

**Comment by Anmol-Baranwal** [comment]
@raghav1030 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
