### ISSUE TITLE
Link Addition for the subcategory named Roadmaps

### ISSUE THREAD

**Issue by AlfiyaSiddique** [rupali-codes/LinksHub#1801]
### Site URL

https://roadmap.sh/

### Description of the above provided site

It is a website that provides a clear raodmap for different skills through the means of diagrams.

### Category

Other

### Sub Category

Roadmaps

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@AlfiyaSiddique 

As you can see, roadmap.sh is already present. `Developer Roadmaps`

> Image
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/2d2761a8-065f-4b8a-89fc-788afb4e40e1)

If you want, you can create a new issue or edit the resource title, url and description and then tag me again.

**Comment by rupali-codes** [comment]
@AlfiyaSiddique closing this issue because the resource is already available. Please feel free to raise any other issue :)
