### ISSUE TITLE
[OTHER] Overuse of transition effect on hovering over Sub-category links.

### ISSUE THREAD

**Issue by raghav1030** [rupali-codes/LinksHub#1803]
### What would you like to share or ask?

There seems to be over usage of transitional effect on the sub category links. The transition tends to leave a delay to the user when hovered resulting in bad User experience.

##Proposed Changes

**Actual behavior**

https://github.com/rupali-codes/LinksHub/assets/94848646/99a7d0cb-e6db-4309-9de3-a53321802829

**Proposed behavior**

https://github.com/rupali-codes/LinksHub/assets/94848646/bc2e7515-2439-406a-a04f-e91985320494

I am willing to contribute this under hacktober fest :)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
I'm closing this, because proposed behavior is not that accurate. Any person will have difficulty in knowing that minor change.

I'm not going to move forward with this. Please look for other issues with tag: `up for grabs` or create new ones.
