### ISSUE TITLE
[DOCS] fix error in codeowners

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1805]
### Issue Description

`@ujjawaltyagii` doesn't have write access, so the CODEOWNERS is throwing errors.

@rupali-codes 
It would be better, if we can include my username. It will automatically give me a notification to review the PR.

So, will you do this or shall I?

### Screenshots or Examples (if applicable)

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/debb69ee-d3b8-4796-8b25-2163d1e6d2ae)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Yeah that's been weighing on my mind @Anmol-Baranwal

**Comment by CBID2** [comment]
Maybe I could do it @Anmol-Baranwal?

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Sure.

**Comment by CBID2** [comment]
> @CBID2 
> 
> Sure.
> 
> 

So replace that's person's name with yours?

**Comment by Anmol-Baranwal** [comment]
Yeah, I will suggest the changes.

That would do the work

> Collaborator

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Just let me know, if you face any problem.

My username is: @Anmol-Baranwal 🤣 if you don't remember

**Comment by rupali-codes** [comment]
@Anmol-Baranwal i didn't notice this 🎃

**Comment by Anmol-Baranwal** [comment]
No worries, I was using the LinksHub codeowners file as a reference and noticed this.
