### ISSUE TITLE
[BUG] Side navigation bar is not responsive for Samsung Galaxy fold

### ISSUE THREAD

**Issue by yashnirmal** [rupali-codes/LinksHub#1806]
### Description

Sidebar is not responsive for not responsive for samsung galaxy fold and other folding devices

### Screenshots

<img width="327" alt="Screenshot 2023-10-04 at 11 02 09 PM" src="https://github.com/rupali-codes/LinksHub/assets/78169683/308650e4-f0ed-4310-9dba-9937c24b4dd2">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@yashnirmal thanks for pointing this out. Assigned to you, you can start working on it.
