### ISSUE TITLE
[BUG] The pagination bar is fixed

### ISSUE THREAD

**Issue by Akanksha-202** [rupali-codes/LinksHub#1808]
### Description

The pagination bar is fixed and overlaps other elements on the screen.

### Screenshots

![Screenshot 2023-10-05 114616](https://github.com/rupali-codes/LinksHub/assets/100708686/14cbfdc7-08f2-4df9-ada9-ec501bf2bb59)

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@Akanksha-202 can you please elaborate on how are you going to fix this?

**Comment by Akanksha-202** [comment]
I have two solutions for this, you can choose either:
1. Sticking it to the bottom, just above the footer.
2.  Putting Navigation arrows to extremes of the cards.
ex: 
![copy](https://github.com/rupali-codes/LinksHub/assets/100708686/e482d1e5-9893-43a6-a94d-9e78781718b4)

**Comment by rupali-codes** [comment]
> I have two solutions for this, you can choose either:
> 
> 1. Sticking it to the bottom, just above the footer.
> 2. Putting Navigation arrows to extremes of the cards.
>    ex:
>    ![copy](https://user-images.githubusercontent.com/100708686/272823452-e482d1e5-9893-43a6-a94d-9e78781718b4.png)

Arrows won't look nice. 

@Akanksha-202 we've decided that we'd remove this pagination and add lazy-loading instead. So please let us know if you want to work on this issue #1833 and close this one.

**Comment by Akanksha-202** [comment]
Yes sure, I'm interested and can implement lazy loading, assign that issue and close this.
