### ISSUE TITLE
Kinde Auth

### ISSUE THREAD

**Issue by Toyin5** [rupali-codes/LinksHub#1811]
### Site URL

https://kinde.com/

### Description of the above provided site

Everything you need for authentication in one platform
Reduce friction with passwordless authentication
Free your users from passwords and remove the hassle of password resets with one click sign up and sign in.

### Category

Backend

### Sub Category

Authen

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@Toyin5 go ahead!
