### ISSUE TITLE
[OTHER] Put icons on the left-side in the sidebar for small screens

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1812]
### What would you like to share or ask?

Placing these icons at the center makes it look weird. Place these icons to the left-side along with GitHub forks and star count

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/52a71194-67e2-49b8-9692-174c0cb4c422)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Toyin5** [comment]
Can I get assigned to this? @rupali-codes

**Comment by rupali-codes** [comment]
> Can I get assigned to this? @rupali-codes

Sure, thanks.

**Comment by Toyin5** [comment]
So about the icons, are they to be aligned vertically or horizontally?

**Comment by khushalmajoka** [comment]
Hi @rupali-codes, Is the below UI looks good?

<img width="565" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/56840292/be4c3cad-b83a-47b5-9a7b-f56763fb0593">

**Comment by khushalmajoka** [comment]
Should i raise a PR?

**Comment by rupali-codes** [comment]
> So about the icons, are they to be aligned vertically or horizontally?

It should be as it is, just align it to left

**Comment by khushalmajoka** [comment]
So please can i get assigned to this?

**Comment by CBID2** [comment]
> So please can i get assigned to this?

Sorry @khushalmajoka. @Toyin5 has been assigned to this issue. You can always review their pull request once it's raise. :) It's a great way to practice your feedback giving skills. Check out [my 
FreeCodeCamp article](https://www.freecodecamp.org/news/code-review-tips/) to help you.
