### ISSUE TITLE
[Add] <add new youtube url to AI category>

### ISSUE THREAD

**Issue by kimmypracha** [rupali-codes/LinksHub#1813]
### Site URL

https://www.youtube.com/@YannicKilcher

### Description of the above provided site

This channel provides consistent update on the machine learning related news and papers, and also dive deep into the specific paper. There is also a paper reading activity on the discord of this channel as well. Best suited for someone who would like to learn more about the in-depth research in machine learning.  

### Category

Artificial Intelligence

### Sub Category

Machine Learning

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@kimmypracha go-ahead!

**Comment by kimmypracha** [comment]
Can I reopen this issue? I would like to continue what I'm planning to add.  Or do I need to create a new issue

**Comment by Anmol-Baranwal** [comment]
> Can I reopen this issue? I would like to continue what I'm planning to add. Or do I need to create a new issue

This is already open. It was never closed.
