### ISSUE TITLE
[Add] <CryptpCurrecy APi >

### ISSUE THREAD

**Issue by Manmit124** [rupali-codes/LinksHub#1815]
### Site URL

https://www.coingecko.com/en/api

### Description of the above provided site

CoinGecko provides a free API that offers comprehensive cryptocurrency data, including real-time and historical prices, market capitalization, trading volume, and more. Developers can use this API to access cryptocurrency information programmatically, allowing for integration into websites, applications, and trading tools. It's a valuable resource for anyone interested in tracking and analyzing cryptocurrency market data. To use the CoinGecko API, you can refer to their official documentation for details on endpoints and data retrieval.

### Category

Backend

### Sub Category

APIs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by aditya7302** [comment]
I would like to work on this issue. Can you assign it to me ?

**Comment by Anmol-Baranwal** [comment]
@aditya7302 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by aditya7302** [comment]
I have a made a pull request regarding this issue please take a look .
