### ISSUE TITLE
[Add] <Recipe Search API>

### ISSUE THREAD

**Issue by whitebeard10** [rupali-codes/LinksHub#1816]
### Site URL

https://developer.edamam.com/edamam-recipe-api

### Description of the above provided site

Edamam's Recipe Search API lets you integrate a recipe database and faceted recipe search into your websites or mobile applications.

### Category

Backend

### Sub Category

API

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@whitebeard10 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
