### ISSUE TITLE
[Add] <Add Redis database>

### ISSUE THREAD

**Issue by Manmit124** [rupali-codes/LinksHub#1817]
### Site URL

https://redis.io/

### Description of the above provided site

The open source, in-memory data store used by millions of developers as a database, cache, streaming engine, and message broker.

### Category

Backend

### Sub Category

Database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@Manmit124 you're assigned.
