### ISSUE TITLE
[Add] <Auth0 to the authentication>

### ISSUE THREAD

**Issue by Manmit124** [rupali-codes/LinksHub#1818]
### Site URL

https://auth0.com/

### Description of the above provided site

Auth0 is a flexible, drop-in solution to add authentication and authorization services to your applications. Your team and organization can avoid the cost, time, and risk that come with building your own solution to authenticate and authorize users.

### Category

Backend

### Sub Category

Authentication

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Welcome back @Manmit124! :) You've been assigned to this issue! :) Just a reminder:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
