### ISSUE TITLE
[Description] no descriptions in the Frontends subcategories, ThreeJs and UI generators 

### ISSUE THREAD

**Issue by mahfuzurrahman01** [rupali-codes/LinksHub#1820]
### Category Name

Frontend

### Subcategory Name

Three js & UI generators

### New or updated description of above subcategory

Every **subcategory** has its own description for the user to know about those stacks/tools. However, I noticed that the Frontends subcategory  **ThreeJs and UI generators** don't have any description. **Need to update both descriptions.**

![Screenshot](https://i.ibb.co/dM5WNwn/05-10-2023-20-33-34-REC.png)
![Screenshot](https://i.ibb.co/wW0ddrj/05-10-2023-20-33-49-REC.png)

### Status of Description

- [X] Adding new description
- [ ] Updating existing description

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @mahfuzurrahman01! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
