### ISSUE TITLE
[Add] Women Who Code in the communities sub category

### ISSUE THREAD

**Issue by SargamPuram** [rupali-codes/LinksHub#1821]
### Site URL

https://www.womenwhocode.com/communities/

### Description of the above provided site

Women Who Code is a global non-profit organization dedicated to change the industry experience for women engineers. It is an active community that aims to provide an avenue into the technology world by evaluating and assisting women in developing technical skills.

### Category

Other

### Sub Category

Communities

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @SargamPuram! :) Just as a friendly reminder:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
