### ISSUE TITLE
[Add] lucide.dev to icons in frontend

### ISSUE THREAD

**Issue by itaim18** [rupali-codes/LinksHub#1822]
### Site URL

https://lucide.dev/

### Description of the above provided site

A lightweight icons made by their community, customizable and available on a huge amount of frameworks and copyable as SVGs and able to be pre-configured.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @itaim18! :)
