### ISSUE TITLE
[Add]  Adding a link in, category- `frontend`, sub-category - `Icons`

### ISSUE THREAD

**Issue by Prakhar-Shankar** [rupali-codes/LinksHub#1824]
### Site URL

https://evil-icons.io/

### Description of the above provided site

Simple and clean SVG icon pack with the code to support Rails, Sprockets, Node.js, Gulp, Grunt and CDN.

### Category

Frontend

### Sub Category

Icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @Prakhar-Shankar! :)
