### ISSUE TITLE
[Feature] Remove pagination and implement lazy-loading

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#1833]
### Description

Currently, the pagination looks kinda distracting from user's view also it hides the content which needs to be shown. It would be better if we add lazy-loading instead of pagination. Lazy-loading will only load the content as per the need. 

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/b26a9e0d-b283-4f77-ac73-10305828cc82)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
I don’t know. I’m still pretty hesitant about this. @Anmol-Baranwal, what do you think?

**Comment by Akanksha-202** [comment]
Yes please assign it to me, I'm interested :)

**Comment by Anmol-Baranwal** [comment]
> I don’t know. I’m still pretty hesitant about this. @Anmol-Baranwal, what do you think?

@rupali-codes 
I agree it is stuck in between and distorts the whole thing. I even said it in the original PR.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/dbe892de-cd5f-47f5-b5c9-9dbd5183fc76)

But implementing lazy loading would be very critical, so if someone wants to check out the last resource then they would have to keep scrolling to bottom and they don't know how many resources are there, of which you suggest we can add a number.

So, do you think if you scroll to the bottom, you would remember the number of resources you passed which ultimately depends on the speed of scrolling. 

We can do this in two ways: from my perspective

1. Dynamically changing the number based on how many resources are available from the row (after the last row that is visible on screen) to the end.

2. We could implement a pagination at the RHS. Floating widget same as pagination in a column wise.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/1596ffc6-90b8-4aab-b0f6-4b8d4de1d4a5)

It will solve both problems, it's up to you.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal i agree with you, and i think the 2nd one would be more better

**Comment by Anmol-Baranwal** [comment]
@Akanksha-202 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) or [@rupali-codes](https://github.com/rupali-codes) if you require any assistance.

**Comment by alienishi** [comment]
@Anmol-Baranwal @CBID2 @rupali-codes 
Am new to open source and this issue seems solvable to me 
I would like to resolve this issue
Please assign it to me

**Comment by CBID2** [comment]
Hi @alienishi. Thanks for showing your interest in this issue, but it's been assigned already. Feel free to raise an issue and/or review @Akanksha-202's PR once it's up.

**Comment by Akanksha-202** [comment]
Hey @Anmol-Baranwal @rupali-codes @CBID2 !
https://www.loom.com/share/d0dfd234dd4849289fb00e1e0765feca?sid=6b323530-f4b2-417f-a56b-a68e2c6de630

This is what it looks like with vertical pagination as you said to move it RHS, there is very less space for small screens, can we shift to just arrows?
https://www.loom.com/share/2a8bcd71db9b42869ec8ac6c1414a1ad?sid=cba21f9a-c181-43e7-913c-39fc5443a876
Demo


Or maybe suggest me some other changes

**Comment by Anmol-Baranwal** [comment]
> Hey @Anmol-Baranwal @rupali-codes @CBID2 ! https://www.loom.com/share/d0dfd234dd4849289fb00e1e0765feca?sid=6b323530-f4b2-417f-a56b-a68e2c6de630
> 
> This is what it looks like with vertical pagination as you said to move it RHS, there is very less space for small screens, can we shift to just arrows? https://www.loom.com/share/2a8bcd71db9b42869ec8ac6c1414a1ad?sid=cba21f9a-c181-43e7-913c-39fc5443a876 Demo
> 
> Or maybe suggest me some other changes

You can also use: https://jam.dev/

A much easier way to showcase browser bugs or suggestions. 

Pagination seems fine for lg devices. The issue will be for small devices.

Let others share their opinions.

**Comment by CBID2** [comment]
I share a similar sentiment @Anmol-Baranwal. It looks great on large screens but not so good on small ones

**Comment by Anmol-Baranwal** [comment]
@Akanksha-202 
You can raise a PR. This needs to be done, so we will work together on the PR.

**Comment by Akanksha-202** [comment]
Can you please tell which one should I include in PR, the numbers one or the one with just arrows ?

**Comment by Anmol-Baranwal** [comment]
According to me, it will be numbers with at least 3 options (if there are sufficient pages).

You can raise a PR, you have done both so if others disagree, then we will be going forward with arrows nav.

But most probably, it will be using numbers.

**Comment by Akanksha-202** [comment]
Sorry for the delay, made the PR

**Comment by rupali-codes** [comment]
this issue was resolved
