### ISSUE TITLE
[Add] Brimble deployment

### ISSUE THREAD

**Issue by Toyin5** [rupali-codes/LinksHub#1834]
### Site URL

https://brimble.io/

### Description of the above provided site

Spend little to no time on DevOps and more time building. Super efficient way to host & scale your web app.

### Category

Resources

### Sub Category

Hosting

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Toyin5 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 

#1811 assigned to you.

**Comment by Toyin5** [comment]
I closed #1811 already
Can I take this? @Anmol-Baranwal

**Comment by Toyin5** [comment]
It's closed now @Anmol-Baranwal

**Comment by Toyin5** [comment]
@CBID2 get this assigned to me pls
I need to work on other things

**Comment by Anmol-Baranwal** [comment]
@Toyin5 
Sorry, my health was great yesterday. So, I wasn't be to respond yesterday.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
