### ISSUE TITLE
[Add] The Tor Project

### ISSUE THREAD

**Issue by singodiyashubham87** [rupali-codes/LinksHub#1835]
### Site URL

https://github.com/TheTorProject

### Description of the above provided site

The Tor Project is an Open-Source project for the famous Tor service offered for being anonymous on the Internet.

Kindly assign me this under Hacktoberfest'23

### Category

Open Source

### Sub Category

projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@singodiyashubham87 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.

**Comment by singodiyashubham87** [comment]
@Anmol-Baranwal Kindly assign me this issue as I have completed the assigned one.

**Comment by CBID2** [comment]
> @Anmol-Baranwal Kindly assign me this issue as I have completed the assigned one.

Please be patient @singodiyashubham87. :)

**Comment by singodiyashubham87** [comment]
> > @Anmol-Baranwal Kindly assign me this issue as I have completed the assigned one.
> 
> Please be patient @singodiyashubham87. :)

My last PR is merged, if it's good now then kindly assign me the issue.

**Comment by Anmol-Baranwal** [comment]
@singodiyashubham87 
Sorry, my health was great yesterday. So, I wasn't be to respond yesterday.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
