### ISSUE TITLE
[Add] Hugging Face

### ISSUE THREAD

**Issue by singodiyashubham87** [rupali-codes/LinksHub#1836]
### Site URL

https://huggingface.co/models

### Description of the above provided site

It's an Ai community platform where the machine learning community collaborates on models, datasets, and applications.

Kindly assign me this issue under Hacktoberfest'23

### Category

Artificial Intelligence

### Sub Category

Artificial Intelligence

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@singodiyashubham87 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
