### ISSUE TITLE
[Feature] Add firebase authentication

### ISSUE THREAD

**Issue by Palakkgoyal** [rupali-codes/LinksHub#1841]
### Description

I want to firebase authentication. I am good with using firebase. I read about this in a issue opened by the maintainers. I want to work on it. Please assign it to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
I've tag your name in the issue I will create: @Palakkgoyal 

For now, I'm closing this. We will do it with proper procedures.

**Comment by Palakkgoyal** [comment]
Ok @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@Palakkgoyal 
I've tagged you in the issue. If you want to work, comment there.
