### ISSUE TITLE
[Add] Add codechef, one of the major cp platform

### ISSUE THREAD

**Issue by THE-AryanKumar** [rupali-codes/LinksHub#1842]
### Site URL

https://www.codechef.com/

### Description of the above provided site

Can i add codechef in competitive programming platform section, as it is one of the major and starting platform for cp journey.

### Category

Competitive Programming

### Sub Category

link, color, fonts, themes & templates, animation

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@THE-AryanKumar 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.

**Comment by THE-AryanKumar** [comment]
Oh sorry, i forgot to uncheck the "willing to work on this issue" option

**Comment by THE-AryanKumar** [comment]
@Anmol-Baranwal After reviewing the previous PR, can you now assign this issue to be me

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal After reviewing the previous PR, can you now assign this issue to be me

Nope, this will be assigned when the PR is merged. There is no exception.

**Comment by 404Nikhil** [comment]
Hi @Anmol-Baranwal can I work on this issue?

**Comment by CBID2** [comment]
> Hi @Anmol-Baranwal can I work on this issue?

Hi @404Nikhil.  @404Nikhil has already created a PR for this issue in #1850. I highly recommend reviewing it. This is a great way to practice your communication skills. If you need tips, I linked an article in the [Remarks section of our Contributing Guide(go where it says, "do a code review of the person’s PR)](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#remarks-)

**Comment by 404Nikhil** [comment]
My bad didn't see that a PR was already made for this issue though this hasn't been assigned to anyone yet and was under "up for grabs" tag so I thought of working on it.

**Comment by rahul0x00** [comment]
@rahul0x00

**Comment by Anmol-Baranwal** [comment]
> Hi @Anmol-Baranwal can I work on this issue?

Yeah, maybe I forgot to remove the up for grabs. My bad. You can create new ones, or look for other issues. There are so many issues, that it is getting difficult to manage.
