### ISSUE TITLE
[Feature] workflow to prevent multiple issues from the same author

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1844]
### Description

- It is getting difficult to check, if the author has multiple issues so we need to add this workflow on a priority basis.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [x] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
I found this one @Anmol-Baranwal: https://github.com/spyder-ide/action-close-duplicate-issues

**Comment by Anmol-Baranwal** [comment]
Okay, I will check.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 
I think it's ready to use.

https://github.com/Anmol-Baranwal/handle-multiple-issues

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 
> 
> I think it's ready to use.
> 
> 
> 
> https://github.com/Anmol-Baranwal/handle-multiple-issues

Ok @Anmol-Baranwal
