### ISSUE TITLE
[BUG] Side Bar Menu should be closed

### ISSUE THREAD

**Issue by rahul0x00** [rupali-codes/LinksHub#1851]
### Description

On mobile devices, when clicking on any links of the sidebar menu should close the sidebar menu automatically.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/104289350/1a957973-3b26-44d1-819c-bee7f4544efc)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@rahul0x00 
Sorry for noticing this too late. 

A PR with the same issue was merged recently, so this is covered. You can check at linkshub deployed link.

Closing this!
