### ISSUE TITLE
feat: add GitHub Auth using Firebase & display minor info on dashboard

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1852]
1. Add firebase auth with GitHub to make it effective

   - We basically just need a GitHub Auth, as people who want to contribute must have their GitHub, so that they can directly create issues from the dashboard.
   - We will follow proper conventions like middleware.ts based on the logic
   
- We need to use middleware.ts for the logic part.

For reference: 
![Screenshot 2023-10-05 100017](https://github.com/rupali-codes/LinksHub/assets/74038190/29f5063c-260c-4e06-a86e-c90ccee4a0fa)
2. We will include a header, with a simple popup to show the data and the basic profile info.

**Comment by Anmol-Baranwal** [comment]
@Palakkgoyal

Are you willing to work on this?

**Comment by raghav1030** [comment]
I'd like to work on this issue under hacktober fest.

Can you please provide a little context regarding the prior development in this issue and what is the exact task to be performed?

**Comment by raghav1030** [comment]
I'd like to contribute in this issue.

Can you please provide some context of the prior development regarding this issue in database setup and all and what task is to be performed from our side?

**Comment by CBID2** [comment]
> I'd like to contribute in this issue.
> 
> Can you please provide some context of the prior development regarding this issue in database setup and all and what task is to be performed from our side?

Hi @raghav1030. This is one of the many features we want to add to LinksHub. To learn more, check out issue #1766

**Comment by Anmol-Baranwal** [comment]
@raghav1030 
We will invite you to the discord private channel, where we can discuss more things properly.

Don't make a PR before that. Please join the LinksHub discord channel, and let me know there if you have arrived.

**Comment by Palakkgoyal** [comment]
> @Palakkgoyal
> 
> Are you willing to work on this?

Yes, I want to work on this issue

**Comment by Anmol-Baranwal** [comment]
> > @Palakkgoyal
> > Are you willing to work on this?
> 
> Yes, I want to work on this issue

This doesn't works. I'm really sorry, but the issue is assigned. I even tagged you on the closed issue. We waited for couple of hours then assigned raghav.

No worries, you can work on other issues if you want.

**Comment by Palakkgoyal** [comment]
Okay sure, Can I work on the database part?

**Comment by Anmol-Baranwal** [comment]
> Okay sure, Can I work on the database part?

Every issue is already assigned. Just join the discord server. I will ask others if they wanna collaborate, then you can directly push into his branch and he can make a PR. It is often done in various good organizations.

**Comment by Anmol-Baranwal** [comment]
@Vidip-Ghosh 
You're assigned.

**Comment by Vidip-Ghosh** [comment]
Yes I would like to work on this.
