### ISSUE TITLE
feat: add upvoting system for resources & create firestore db

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1853]
1. Add `database`, we would need database to store `user's data`, the `resources` and feedbacks in different documents

   - We will use Firestore with security rules.

2. Create `upvoting` system for resources so that LinksHub user's can filter out the resources and use LinksHub more effortlessly 

   - We will follow proper logic and it will be synced from firestore database
   - We will focus on two main things:
      - A authenticated user can only upvote a resource once
      - Keep count of how many times a resource has been updated
      - Keep count of upvoted resources by a user (not necessary depending upon the logic)

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue

**Comment by Anmol-Baranwal** [comment]
@Vidip-Ghosh 

I'm assigning you.

We will invite you to the discord private channel, where we can discuss more things properly.

Don't make a PR before that. Please join the LinksHub discord channel, and let me know there if you have arrived.

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh
> 
> I'm assigning you.
> 
> We will invite you to the discord private channel, where we can discuss more things properly.
> 
> Don't make a PR before that. Please join the LinksHub discord channel, and let me know there if you have arrived.

Yes sure. 
I've joined the discord.

**Comment by Anmol-Baranwal** [comment]
I know, you are there. LOL! 

I just copied and paste the message. 

I will tag you, once the channel is created.
