### ISSUE TITLE
feat: add feedback CTA to collect feedback and store it in the db & make a discussion using github API

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1854]
Take `feedback`, taking feedback from LinksHub user's and other people would help making it more better, we can use something a like a form and store the feedbacks in database, then create a sperate page and display all the feedbacks in there.

This will be done after #1852 & #1853 is completed.

**Comment by heysagnik** [comment]
I want to work on this issue.

**Comment by CBID2** [comment]
> I want to work on this issue.

You've been assigned @heysagnik! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)

**Comment by Anmol-Baranwal** [comment]
@heysagnik 
We will invite you to the discord private channel, where we can discuss more things properly.

Don't make a PR before that. Please join the LinksHub discord channel, and let me know there if you have arrived.

**Comment by CBID2** [comment]
Should we close this issue @Anmol-Baranwal? It seems that https://github.com/rupali-codes/LinksHub/issues/1852 & https://github.com/rupali-codes/LinksHub/issues/1853 solved it.

**Comment by Anmol-Baranwal** [comment]
> Should we close this issue @Anmol-Baranwal? It seems that #1852 & #1853 solved it.

Yeah! I'm closing this for now.
Let's cover this as a later version.
