### ISSUE TITLE
[ADD] Email Sending Services for applications (new category in backend)

### ISSUE THREAD

**Issue by Abhishek19-dev** [rupali-codes/LinksHub#1860]
### Category Name

BACKEND

### Subcategory Name

Email service 

### Additional Context

Discover the best email sending services for seamless user notifications. From transactional to marketing emails, find the perfect fit for your needs. Compare features and reviews to stay connected with your audience effectively. Boost engagement with our curated email service category.
For eg :- Nodemailer (https://nodemailer.com)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned to this issue @Abhishek19-dev! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
