### ISSUE TITLE
[BUG] There are some spelling mistakes 

### ISSUE THREAD

**Issue by AbhineshJha** [rupali-codes/LinksHub#1861]
### Description

Some spelling mistakes in https://www.linkshub.dev/frontend/ui-generators
and https://www.linkshub.dev/frontend/design-inspiration

### Screenshots

![Screenshot 2023-10-06 235311](https://github.com/rupali-codes/LinksHub/assets/142514166/bd7bf14d-130c-40a1-a186-abd14c74e562)
![Screenshot 2023-10-06 235227](https://github.com/rupali-codes/LinksHub/assets/142514166/016de91e-ebb6-49e6-ad7b-a0a19d2e7ec2)

### Any additional information?

I wanna fix this issue .
can u assign me with this issue with hacktoberfest label

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by AbhineshJha** [comment]
hey @CBID2 fixed this issue from draft's pr

**Comment by CBID2** [comment]
You've been assigned @AbhineshJha! :) Now, I'll get to your PR.

**Comment by AbhineshJha** [comment]
Hey @CBID2 can u review my draft's PR

**Comment by rahulmangla28** [comment]
Please assign this issue to me.

**Comment by CBID2** [comment]
> Please assign this issue to me.

Hi @rahulmangla28! :) Thanks for showing interest, but this issue has been assigned to @AbhineshJha. You can review their PR if you want. Check out [this section of our Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#remarks-) to learn how.
