### ISSUE TITLE
[DOCS] adding hacktober fest participation in the readme file

### ISSUE THREAD

**Issue by barkhaaroraa** [rupali-codes/LinksHub#1863]
### Issue Description

i'd like to add hacktober fest in the readme file (with girlscript summer of code)

### Screenshots or Examples (if applicable)

<img width="768" alt="image" src="https://github.com/rupali-codes/LinksHub/assets/115429121/5b0f18fc-df42-48fd-860c-4cd8254488a1">

### Proposed Solution (optional)

the repo participated in both open source programs so i'd like to add hacktober fest 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Hi @barkhaaroraa! :) Thanks for pointing this out, but I commented on this problem in this issue #1703 and one of the maintainers did a pull request for it already.
