### ISSUE TITLE
[Add] Adding link of Keycloak

### ISSUE THREAD

**Issue by Prakhar-Shankar** [rupali-codes/LinksHub#1864]
### Site URL

https://www.keycloak.org/

### Description of the above provided site

Add authentication to applications and secure services with minimum effort. There is no need to deal with storing or authenticating users. Keycloak provides user federation, strong authentication, user management, fine-grained authorization, and more.

### Category

Backend

### Sub Category

Authentication

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @Prakhar-Shankar. Now, let's review your pull request! :)
