### ISSUE TITLE
[Add] Flask Project Ideas

### ISSUE THREAD

**Issue by aditya9277** [rupali-codes/LinksHub#1868]
### Site URL

https://www.geeksforgeeks.org/flask-projects/

### Description of the above provided site

This website contains, Beginner to Advanced FLASK projects with source code. One can get idea from where they can start making projects being a rookie and thereby progressing to advanced level projects also. This site would be a valuable addition to the site resources

### Category

Resources

### Sub Category

project ideas

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @aditya9277! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)

**Comment by aditya9277** [comment]
Thanks @CBID2 for assigning me. I hope you are well and doing good , btw i am a old contributor, contributed during GssoC`23 too, and now in hacktoberfest :)

**Comment by CBID2** [comment]
> Thanks @CBID2 for assigning me. I hope you are well and doing good , btw i am a old contributor, contributed during GssoC`23 too, and now in hacktoberfest :)

You're welcome, and oh cool! :) I was a PA in this year's GsSOC and doing my first hacktoberfest as a contributor and maintainer.
