### ISSUE TITLE
[Add]: add upvoting system for resources & create firestore db 

### ISSUE THREAD

**Issue by xlo-u** [rupali-codes/LinksHub#1869]
### Site URL

https://www.fireeye.com/services/freeware/flare.html

### Description of the above provided site

Add one of the most value websites for analysis malware

### Category

Other

### Sub Category

 malware analysis

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Hi @xlo-u. Thanks for raising this issue but it was already mention in #1766.
