### ISSUE TITLE
[Add] Postman and Cypress in subcategory testing / backend

### ISSUE THREAD

**Issue by Abhishek19-dev** [rupali-codes/LinksHub#1873]
### Site URL

https://www.postman.com/ , https://www.cypress.io/

### Description of the above provided site

Postman :- Postman is a popular API testing tool that simplifies the process of sending HTTP requests to test and analyze web services. It allows developers to create, organize, and automate API tests, making it a valuable tool for ensuring the functionality and reliability of web applications.

cypress :- Cypress is an end-to-end testing framework for JavaScript applications. It runs in the browser and provides a simple, yet powerful API for writing and running tests. Cypress is a good choice for teams that need to test their JavaScript applications quickly and easily.

### Category

Backend

### Sub Category

testing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Hi @Abhishek19-dev. I've assigned you this issue, but please do not make a pull request before it is approved.
