### ISSUE TITLE
[Add] Important Technical Writing Tool

### ISSUE THREAD

**Issue by nobunagaaa** [rupali-codes/LinksHub#1877]
### Site URL

https://app.grammarly.com/

### Description of the above provided site

Grammarly is a popular grammar and spell-checking tool that also provides suggestions for improving writing clarity and style. It can be used as a browser extension or standalone application.

### Category

TECHNICAL WRITING

### Sub Category

Technical Writing Tools
### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@nobunagaaa 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
