### ISSUE TITLE
[Add] Editor tool for Technical Writing Tools

### ISSUE THREAD

**Issue by rahul0x00** [rupali-codes/LinksHub#1878]
### Site URL

https://hemingwayapp.com/

### Description of the above provided site

Hemingway Editor is a writing tool that focuses on improving the readability of your text. It highlights complex sentences, excessive adverbs, and passive voice to help you create clear and concise content.

### Category

Technical Writing

### Sub Category

Technical Writing Tools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@rahul0x00 

We should add this in `Technical writing tools` subcategory.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/8815d302-bf90-4226-8af8-5e8cd5f90f35)

Update the description, and tag me again.

**Comment by rahul0x00** [comment]
@Anmol-Baranwal updated as requested

**Comment by Anmol-Baranwal** [comment]
@rahul0x00 
Why are you in such a rush? You just updated subcategory, and tagged me without even updating the category. I have done it for you. Next time, I will simply ignore. Kindly do things in a proper way.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by rahul0x00** [comment]
I'm sorry about that

**Comment by Anmol-Baranwal** [comment]
> I'm sorry about that

No need to apologize. I'm sorry if it seemed rude. Don't worry, everything's fine. Let me know if you need anything.

**Comment by rahul0x00** [comment]
no worries at all

> > I'm sorry about that
> 
> No need to apologize. I'm sorry if it seemed rude. Don't worry, everything's fine. Let me know if you need anything.
