### ISSUE TITLE
[Add] Freefrontend to Themes and Templates (subcategory) and  IconsScout to Illustrations(subcategory)

### ISSUE THREAD

**Issue by Abhishek19-dev** [rupali-codes/LinksHub#1879]
### Site URL

https://freefrontend.com/ , https://iconscout.com/

### Description of the above provided site

 Freefrontend :- It is a free and open-source collection of high-quality, responsive, and accessible front-end components and templates. It is a great resource for designers and developers who want to create beautiful and user-friendly websites and applications.

iconscout :- Get millions of 3Ds, icons, illustrations, Lottie animations, and best-in-class search tools for your website, mobile app or project with the IconScout API.

### Category

Frontend

### Sub Category

themes & templates , illustrations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Abhishek19-dev 
I'm stunned by freefrontend. Crazy resource!

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
