### ISSUE TITLE
[Add] <Add Docker documentation to learn docker>

### ISSUE THREAD

**Issue by ayushrakesh** [rupali-codes/LinksHub#1888]
### Site URL

https://docs.docker.com/

### Description of the above provided site

Docker is a popular platform for developing, shipping, and running applications in containers. The official Docker documentation serves as a comprehensive resource for users, offering detailed information, guidance, and best practices for effectively using Docker and its related tools.

### Category

DevOps

### Sub Category

Docker

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@ayushrakesh
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.

https://github.com/rupali-codes/LinksHub/issues/1890 is assigned to you

**Comment by Lokendrakushwah12** [comment]
Please assign me @Anmol-Baranwal

**Comment by Neel-07** [comment]
Hello @Anmol-Baranwal can this issue be assigned to me.

**Comment by Anmol-Baranwal** [comment]
> Hello @Anmol-Baranwal can this issue be assigned to me.

Since @Lokendrakushwah12 commented first. So, I'm assigning this to him.

@Lokendrakushwah12 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
