### ISSUE TITLE
[Add] <Add youtube link for complete Kubernetes tutorial>

### ISSUE THREAD

**Issue by ayushrakesh** [rupali-codes/LinksHub#1889]
### Site URL

https://www.youtube.com/watch?v=y3WTwzx5ABk

### Description of the above provided site

Edureka's Kubernetes YouTube tutorial offers a comprehensive and beginner-friendly guide to understanding and mastering Kubernetes, a powerful container orchestration platform.

### Category

Youtube

### Sub Category

Kubernetes

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@ayushrakesh 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 

#1890 is assigned to you

**Comment by Anmol-Baranwal** [comment]
@alienishi

Wanna work on this?

**Comment by alienishi** [comment]
@Anmol-Baranwal ya sure would love to :)
Please assign it to me

**Comment by Anmol-Baranwal** [comment]
@alienishi 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
