### ISSUE TITLE
[Add] <Want to add DSA articles under subcategory "Articles">

### ISSUE THREAD

**Issue by ayushrakesh** [rupali-codes/LinksHub#1890]
### Site URL

https://medium.com/@mukhopadhyaypushan42/best-way-to-solve-dsa-problems-become-a-pro-ccba897469c1

### Description of the above provided site

Solving Data Structures and Algorithms (DSA) problems on platforms like LeetCode, InterviewBit, and GeeksforGeeks can indeed pose a considerable challenge. These platforms are renowned for refining your coding skills and preparing you for technical interviews. 

### Category

Other

### Sub Category

DSA

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @ayushrakesh! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)

**Comment by KESHAV4R3** [comment]
hii @CBID2 please assign this issue to me as it seems to be a perfect match for the domain in which i am working right now

**Comment by CBID2** [comment]
> hii @CBID2 please assign this issue to me as it seems to be a perfect match for the domain in which i am working right now 

Thanks for your interest @KESHAV4R3! 😊 The issue has been assigned to @ayushrakesh.
