### ISSUE TITLE
[DOCS] add social media icons in readme for visual appeal

### ISSUE THREAD

**Issue by shelar1423** [rupali-codes/LinksHub#1894]
### Issue Description

Socials section in README.md is not very appealing without any emojis or icons.

### Screenshots or Examples (if applicable)

![image](https://github.com/rupali-codes/LinksHub/assets/82649533/79a003aa-d70e-43bd-9531-f9d3d074ba8a)

### Proposed Solution (optional)

To add social media icons of respective social media links ahead of them ,making it look more appealing.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You're assigned! 😀

**Comment by Anmol-Baranwal** [comment]
@shelar1423 
From next time, please add title and other things.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/faa3d553-e9a2-4a8a-a3e3-3d36f5624703)

I'm doing it for you this time, just make sure to do it from next time.
