### ISSUE TITLE
[BUG] No border of separation for sidebar in light mode

### ISSUE THREAD

**Issue by singodiyashubham87** [rupali-codes/LinksHub#1898]
### Description

When I switched to light mode I noticed that the sidebar was becoming mixed with the main content and there was no separation between the aside and main section.
I want to fix this by adding a border to the sidebar.

I've added the screenshots for reference.

### Screenshots

# Bug

![Screenshot from 2023-10-08 12-53-48](https://github.com/rupali-codes/LinksHub/assets/93720428/5ba1b197-6ec8-4e50-8137-a849253eca5e)

# Resolved
![image](https://github.com/rupali-codes/LinksHub/assets/93720428/6a185894-a0a0-4665-ac6b-1c518e154193)

### Any additional information?

Kindly assign me this issue under Hacktoberfest'23

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@singodiyashubham87 
Doesn't look that good.

**Comment by singodiyashubham87** [comment]
> @singodiyashubham87 Doesn't look that good.
> 
> Maybe a slight shadow at RHS.

That's also a good option, I can add a shadow on the RHS, Kindly assign me the issue so that I can work on it and show you the result and whenever satisfied I'll make the PR

**Comment by Anmol-Baranwal** [comment]
@singodiyashubham87 

As shown in the image, I don't think there is need of any.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/e77880de-1614-42e5-a53f-2ab3ed72395c)

Why the colors are different for you, and there is clear distinction of sidebar. Closing this!
