### ISSUE TITLE
[FEATURE] Add loading spinner

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#19]
The website currently does not have any indication that it is loading or processing data. This can make it difficult for users to know when the page is done loading and ready for interaction.

### Specific requirements 
- Display the spinner in the center of the page while the page is loading.
- Make sure the spinner is only visible while the page is loading and disappears when the page is fully loaded.

### Hints
- [React spinners library ](https://github.com/davidhu2000/react-spinners)
- [Material Design spinner](https://material.io/design/components/progress-indicators/spinners.html)
- [DaisyUI](https://daisyui.com)

**Comment by AdekeyeAdeniyi** [comment]
If this is still open am available.

**Comment by AdekeyeAdeniyi** [comment]
Can I work on this?

**Comment by rupali-codes** [comment]
sure, thanks for taking interest in, assigning to you

**Comment by AdekeyeAdeniyi** [comment]
On it. Thanks
