### ISSUE TITLE
HOME PAGE

### ISSUE THREAD

**Issue by pramodreddypandiri** [rupali-codes/LinksHub#190]
### What would you like to share or ask?

Currently we have only LinksHub Logo in Home page. 
<img width="1012" alt="Screenshot 2023-02-11 at 8 20 04 PM" src="https://user-images.githubusercontent.com/98374193/218264463-a848de82-2c0c-4760-ad1c-faec7e34b17c.png">

I think we can have some text/picture telling what can you get here(in this site) and guiding them to use sidebar for going to different sections (in all screen sizes).
 I think this can be taken as  **improving accessibility** for user in **UX** point of view.

**Comment by rupali-codes** [comment]
Yeah, that would a great idea if we can add something like a GIF. Are you willing to work on this?

**Comment by pramodreddypandiri** [comment]
yes, but is there any thing like deadline? (sorry for newbie questions).

**Comment by rupali-codes** [comment]
> yes, but is there any thing like deadline? (sorry for newbie questions).
There's no need to be sorry, it's fine. 
We don't have any deadlines, but it's better if you do it asap. But yeah, take your take :)

**Comment by pramodreddypandiri** [comment]
I will pick this then.

**Comment by pramodreddypandiri** [comment]
can i install a package needed for implementation?

**Comment by rupali-codes** [comment]
> can i install a package needed for implementation?

Yes you can,

**Comment by pramodreddypandiri** [comment]
Hi  @rupali-codes ,as you have asked i close PR for this issue.  But i really do not know how to commit `index.tsx` and `package.json` for new PR.
I need help , I am new to open source this is my first project.

**Comment by pramodreddypandiri** [comment]
Waiting for you guidance @rupali-codes

**Comment by rupali-codes** [comment]
> Waiting for you guidance @rupali-codes

You can add specific file/s by using this commands
**To add file/s**
```sh
 git add <file_name>
```

**To commit file**
```sh
git commit -m "<commit_message>"
```

**Comment by pramodreddypandiri** [comment]
merger issue #212
