### ISSUE TITLE
[BUG] Empty page

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#1902]
### Description

I noticed that the Open Source Community page on the website is empty. This can create confusion to users

### Screenshots

![Empty page](https://github.com/rupali-codes/LinksHub/assets/105683440/7577eec6-827b-4b59-ab30-6d9b585b090f)

### Any additional information?

I have two possible solutions 
1. Remove the page
2. Use it to highlight specific contributions.

@Anmol-Baranwal and @rupali-codes, what do you think?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@CBID2 @rupali-codes 
Where did it go?

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Don't worry, working on it.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
It is due to limit exceeded. We will see what we can do.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a318baca-e06e-44c7-ad0e-94f254582087)

**Comment by CBID2** [comment]
> @CBID2 
> 
> It is due to limit exceeded. We will see what we can do.
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a318baca-e06e-44c7-ad0e-94f254582087)
> 
> 

Thanks

**Comment by rupali-codes** [comment]
Its nothing we can do about, so closing the issue :)
