### ISSUE TITLE
[Add] <Add a new typescript tutorial>

### ISSUE THREAD

**Issue by Romit77** [rupali-codes/LinksHub#1907]
### Site URL

https://www.youtube.com/watch?v=j89BvWz8Eag&list=PLRAV69dS1uWRPSfKzwZsIm-Axxq-LxqhW

### Description of the above provided site

This is a youtube tutorial to learn Typescript from scratch

### Category

Resources

### Sub Category

Typescript

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Romit77 
Please raise issues with good resources, the channel is multi-purpose and the tutorial is of 6 minutes long. 

Closing this! If you feel otherwise, just comment.

**Comment by Romit77** [comment]
It is a comprehensive tutorial series which consists of 26 videos. I have learnt from it and found it to be really informative and helpful and also the development related nature of the channel would be a suitable fit. If you feel otherwise then no problem :)

**Comment by Anmol-Baranwal** [comment]
@Romit77 
Then do it for playlist, how would I know if that has 26 videos.

Change the description, I'm assigning.
https://www.youtube.com/playlist?list=PLRAV69dS1uWRPSfKzwZsIm-Axxq-LxqhW
