### ISSUE TITLE
[Add] Neetcode in Competitive Programming Category

### ISSUE THREAD

**Issue by singodiyashubham87** [rupali-codes/LinksHub#1918]
### Site URL

https://www.youtube.com/@NeetCode

### Description of the above provided site

This is a youtube channel which help students and professional to become better in Competitive Programming and Tech Interviews

### Category

Competitive Programming

### Sub Category

tutorials

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@singodiyashubham87 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
