### ISSUE TITLE
[ADD] <AI/Natural Language Processing>

### ISSUE THREAD

**Issue by Arnabhit** [rupali-codes/LinksHub#1919]
### Category Name

AI

### Subcategory Name

Natual Language Processing

### Additional Context

In the AI category a subcategory must be there of Natural Language processing which is missing. I want to add it. Please assign it to me.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Arnabhit 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

Shouldn't it be more related to ML?

**Comment by CBID2** [comment]
> @Arnabhit I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
> 
> Shouldn't it be more related to ML?

I think so @Anmol-Baranwal.

**Comment by Anmol-Baranwal** [comment]
@Arnabhit 
You can raise a PR, we will ask for any changes in the PR.

Also, you can comment now. I have unlocked the conversation.
