### ISSUE TITLE
[DOCS] <Update README.md - Twitter Handle link is showing old id>

### ISSUE THREAD

**Issue by AaadityaG** [rupali-codes/LinksHub#1920]
### Issue Description

Twitter id link is not updated for new twitter handle in README.md

### Screenshots or Examples (if applicable)

Current link - https://twitter.com/the_linkshub

![wrong twitter id](https://github.com/rupali-codes/LinksHub/assets/114663382/a7132172-ddc1-4638-9507-8009f1dfc221)

### Proposed Solution (optional)

Must needs to update to - https://twitter.com/linkshubdotdev 

![right twitter id](https://github.com/rupali-codes/LinksHub/assets/114663382/d3c2bafd-1cf9-4fd9-bd0d-f02d98bcc08d)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @AaadityaG! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
