### ISSUE TITLE
[Add] Realtime Colors to Colors subcategory of frontend

### ISSUE THREAD

**Issue by Abhishek19-dev** [rupali-codes/LinksHub#1924]
### Site URL

https://www.realtimecolors.com

### Description of the above provided site

Realtime Colors :- It is a web-based tool that allows you to visualize and test color palettes for your websites and applications. It provides a variety of features, such as live previews, color contrast checking, and code export. RealtimeColors is a great tool for designers and developers who want to create beautiful and user-friendly websites and applications.

Subcategory of colors: Color visualization and testing

RealtimeColors allows you to visualize your color palettes on a real website and test them for contrast. This helps to ensure that your color palettes are accessible to all users. RealtimeColors also allows you to export your color palettes to a variety of formats, such as CSS, SCSS, and JSON.

### Category

Frontend

### Sub Category

colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Abhishek19-dev 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
