### ISSUE TITLE
[Remove] Unnecessary Page

### ISSUE THREAD

**Issue by aftabrehan** [rupali-codes/LinksHub#1925]
### Description

I've discovered that this page serves no practical purpose.

Upon expanding any item from the sidebar, it redirects to a page that merely duplicates the options available in the expanded content. This redirection can be distracting for users. For instance, if a user is browsing Icons resources and wishes to expand the Backend sidebar item, clicking it redirects them to a page displaying the expanded content for the Backend item. Consequently, if they want to return to Icons resources, they must first re-expand the Frontend item and then navigate to Icons resources.

I recommend removing this page entirely, as it appears to be redundant and unnecessarily complicates user navigation. This action would not only streamline the code but also enhance simplicity for users.

### Screenshots

![Screenshot 2023-10-09 at 12 45 1](https://github.com/rupali-codes/LinksHub/assets/93012310/e6944ff1-82be-4a5b-bbbb-40f890d6b540)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Hi @aftabrehan. Thank you for your suggestion. Personally, I think its worth keeping for the following reasons:
1. It contains a search bar feature, which allows users to look up a specific resource
2. We used to have our social links on the top-right-side of the website, and it made the layout cluttered. Placing it in the sidebar made the site look more visually appealing. 

What do you think @Anmol-Baranwal and @rupali-codes?

**Comment by aftabrehan** [comment]
@CBID2, I meant to remove this section only.

<div align="center">
 <img src="https://github.com/rupali-codes/LinksHub/assets/93012310/f361badc-9e54-4c86-83d9-5cb286ee2604" />
</div>

<hr />

The content here is identical to what we find in the expanded sidebar item.

>1. It contains a search bar feature, which allows users to look up a specific resource.

In such a scenario, we can retain this route but refrain from redirecting users to the (e.g., `/frontend`) route when they expand the "Frontend" resources from the sidebar. As previously mentioned, this approach enables users to expand the sidebar items while remaining on the current page. If you require examples from other websites to illustrate this concept, please feel free to let me know.

>2. We used to have our social links on the top-right-side of the website, and it made the layout cluttered. Placing it in the sidebar made the site look more visually appealing.

I still observe the presence of the social links in the top-right corner. It seems you might be referring to the main branch rather than the deployed version. Nevertheless, I'm a bit unclear about your statement regarding "Placing it in the sidebar made the site look more visually appealing." Could you kindly provide a screenshot to illustrate this point?

I've replicated the header UI in [Figma](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=26-1591&mode=design&t=u0tOjxbK1pswJsXt-0). Could you please review it? I believe I have arranged the social links correctly within the header.

**Comment by Anmol-Baranwal** [comment]
I was very busy since yesterday. I will share my opinion tomorrow. I will also try to reference the original issues where these were discussed.

**Comment by rupali-codes** [comment]
I personally like the current version. @Anmol-Baranwal What do you think??

**Comment by Anmol-Baranwal** [comment]
> I personally like the current version. @Anmol-Baranwal What do you think??

Yeah, me as well.

**Comment by Anmol-Baranwal** [comment]
I can't find the original comment, but it actually helps rather than going through all the subcategories top to bottom.

**Comment by Anmol-Baranwal** [comment]
Closing the issue as mentioned!
