### ISSUE TITLE
[Feature]: Enhance "Visit Site" Button in Card UI for Improved Link Type Indication

### ISSUE THREAD

**Issue by harmeetsingh11** [rupali-codes/LinksHub#1926]
### Issue Description

**Current Behavior:**
In the card UI, there is a "Visit Site" button ("Uplink arrow" icon next to it) that can lead users to various destinations, such as YouTube videos or articles/blogs/documentation. However, there is no visual indication to inform users of the type of content they will access when clicking the link.

**Proposed Improvement:**
We propose enhancing the card UI to provide a clear and intuitive indication of the link type before users click it. Specifically, we suggest adding small icons next to the "Visit Site" button to signify the destination type:

- Display a YouTube logo icon if the link redirects to YouTube (for users who prefer video tutorials).
- Show a "book read" or "document" icon if the link redirects to an article, blog, or documentation website (for users who prefer reading).

**Expected Behavior**
When users view a card with a "Visit Link" button, they should see an appropriate icon (YouTube logo or "book read" icon) next to the button, indicating the content type they will access upon clicking.

### Benefits

- **Enhanced User Experience:** This improvement will help users differentiate between links leading to YouTube videos and those leading to articles, blogs, or documentation. It will reduce the chances of users unintentionally opening a YouTube video when they expected an article or vice versa.

- **Clarity and Transparency:** Clear icons provide visual cues that improve the overall clarity and transparency of the user interface.

### Screenshots

![LinksHub-Languages-c-programming](https://github.com/rupali-codes/LinksHub/assets/130365071/d64971be-7384-4d82-88b9-16e67e72b10d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Hi @harmeetsingh11. This is a good idea. In addition to your points adding small icons next to the "Visit Site" button to signify the destination type, could make it more accessible for screen readers. Let's see what @Anmol-Baranwal and @rupali-codes has to say.

**Comment by viditagrawal56** [comment]
Hey  I would like to work on this issue

**Comment by luv2027** [comment]
hey @CBID2, I would like to work on this issue

**Comment by CBID2** [comment]
Hi @luv2027. I think @harmeetsingh11 wants to work on it

**Comment by Anmol-Baranwal** [comment]
@harmeetsingh11 
That's a great idea. You can proceed once @rupali-codes agrees.

**Comment by harmeetsingh11** [comment]
Hi @rupali-codes , Can I proceed to work on this issue?

**Comment by Anmol-Baranwal** [comment]
@harmeetsingh11 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

Go ahead. This is definitely useful.

**Comment by Anmol-Baranwal** [comment]
Sorry, closed by mistake.
