### ISSUE TITLE
[ADD] <FRONTEND/UIcomponents>

### ISSUE THREAD

**Issue by hritikbhattacharya** [rupali-codes/LinksHub#1927]
### Category Name

Frontend

### Subcategory Name

UI Libraries

### Additional Context

Links for different websites which provides pre built UIcomponents.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [x] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@hritikbhattacharya 
I don't understand, can you elaborate what you wish to add in LinksHub?

**Comment by Anmol-Baranwal** [comment]
@hritikbhattacharya 
UI Libraries huh!

Looks good, what will you create? A subcategory?

**Comment by Anmol-Baranwal** [comment]
@hritikbhattacharya 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

Make a subcategory for `UI Libraries`. And also add these links if possible.

**Comment by hritikbhattacharya** [comment]
yes I have done that.

**Comment by Anmol-Baranwal** [comment]
Sure. Thanks for letting me know.
