### ISSUE TITLE
[Add] Css Course

### ISSUE THREAD

**Issue by huzaifaalmesbah** [rupali-codes/LinksHub#1929]
### Site URL

https://www.youtube.com/playlist?list=PLDyQo7g0_nsUjf046cCHKJ16U1SoXrElZ

### Description of the above provided site

This channel has a wide variety of educational videos on technologies like HTML,CSS,Javascript,Tailwind CSS and React

### Category

Youtube

### Sub Category

web development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@huzaifaalmesbah 
I have updated the description for you. You can add this under web development subcategory.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/cae721b9-103b-4b89-816f-e1804fe05bd0)

**Comment by Anmol-Baranwal** [comment]
@huzaifaalmesbah 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
