### ISSUE TITLE
[BUG] visit site btn overflow his container

### ISSUE THREAD

**Issue by Lourvens** [rupali-codes/LinksHub#193]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

this issue appear on card when his title take two or mare line which makes the button overflow his container

### Screenshots

![image](https://user-images.githubusercontent.com/63268101/218269112-370e2d0e-c0cb-4ab1-83ba-acc00aeea313.png)

**Comment by pramodreddypandiri** [comment]
This has been fixed i think.

**Comment by rupali-codes** [comment]
@Lourvens This issue was fixed.
