### ISSUE TITLE
[Add] Want to add Jenkins documentation.

### ISSUE THREAD

**Issue by ayushrakesh** [rupali-codes/LinksHub#1931]
### Site URL

https://www.jenkins.io/doc/

### Description of the above provided site

Jenkins is an open-source automation server that is widely used for building, deploying, and automating software development pipelines. Its documentation is a crucial resource for users, administrators, and developers who want to understand, install, configure, and utilize Jenkins effectively. The most effective and structured documentation I have ever gone is Jenkin's documentation.

### Category

DevOps

### Sub Category

Jenkins

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@ayushrakesh 
#1890 is already assigned to you.

It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.

**Comment by goobric** [comment]
hi @Anmol-Baranwal 
can I please be assigned to work on this issue #1931

**Comment by Anmol-Baranwal** [comment]
@goobric 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by goobric** [comment]
hi @Anmol-Baranwal and @CBID2 I hope that you are both well :-)
I forgot to update the data.ts with the Jenkins information
I updated my local cloned repo, and tried to push the changes to my forked repo on my github account; Git kept on giving me errors!
I deleted the local cloned repo from my computer
I deleted the forked repo from my github account
I started again from the beginning. I do not know if this is the correct method! Sorry.
I have now updated all of the required sections: index.ts, data.ts, CategoryDescription.js, and added jenkins.json to the directory database/devops
I saved all the files, added the files, staged the files, and pushed the files to my new branch `jenkins` all successful.
"Branch 'jenkins' set up to track remote branch 'jenkins' from 'origin' "
But... on my forked repo for LinksHub, I do not have the option to "Compare & Pull Request"
What have I done wrong? Please help.
 https://github.com/goobric/LinksHub/tree/jenkins
![231013_LinksHub_jenkins](https://github.com/rupali-codes/LinksHub/assets/23141638/35d3e81b-7b63-4877-a6e6-ccc6ceeff523)

**Comment by Anmol-Baranwal** [comment]
@goobric 
Let me check it once.

**Comment by Anmol-Baranwal** [comment]
@goobric 
What was the problem? It was raised as usual, when I did it.

**Comment by goobric** [comment]
Git kept on giving me error messages whenever I used the command
`git push -u jenkins`

it kept stating 'fast-forward' pull the repo
I used the 'pull' cmd on the forked repo to update the cloned repo on the computer; yet another error!
Quite frustrating!
So I thought (maybe incorrectly) just start again.

Now I can't "Compare & Merge" 😕

Please explain what I have done wrong.
Thanks

**Comment by goobric** [comment]
I meant to say
`git push -u origin jenkins`

**Comment by Anmol-Baranwal** [comment]
@goobric 
I am not sure. But, I'm assigning the issue to you as well.

We will do it as a co-authored commit.

**Comment by Anmol-Baranwal** [comment]
@goobric 
Can you comment on the PR.
