### ISSUE TITLE
[Add] WellFound (Formerly AngelList Talent) site link to Placement Prep > sub category "Job Portals" 

### ISSUE THREAD

**Issue by original-subbaman** [rupali-codes/LinksHub#1933]
### Site URL

https://wellfound.com/

### Description of the above provided site

WellFound is a job board website where startup founders and talents (seeking to work in a startup environment) can connect to provide or find jobs. Unlike LinkedIn the pay is mentioned and remote options are a plenty. 

### Category

Other

### Sub Category

Placement Prep > Job Portals

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@original-subbaman 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

Wellfound is a great platform.
