### ISSUE TITLE
[BUG] RaspberryPi Resource not rendered in the subcategory

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#1934]
### Description

I discovered that even though there's a resource for Raspberry Pi in a JSON file, it's not appearing on the website.

### Screenshots

JSON file :
![Screenshot (51)](https://github.com/rupali-codes/LinksHub/assets/112751524/868e3d2d-f07e-4ad6-9db4-56af8e487e1b)

Website: 
![Screenshot (52)](https://github.com/rupali-codes/LinksHub/assets/112751524/5fa7a3a5-772c-43c6-8329-d2616b68f892)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Shiva-Sai-ssb 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

You are very quick at making issues. LOL!
