### ISSUE TITLE
[Add] <Want to add YouTube Playlist link for the CSS tutorial in Hindi>

### ISSUE THREAD

**Issue by JoyelJohny** [rupali-codes/LinksHub#1935]
### Site URL

https://www.youtube.com/playlist?list=PL0b6OzIxLPbzDsI5YXUa01QzxOWyqmrWw

### Description of the above provided site

This playlist is valuable resource for understanding the concepts of CSS in Hindi language

### Category

Youtube

### Sub Category

CSS

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Hi @JoyelJohny! :) Welcome to LinksHub!:) We're so glad to have you here. Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
