### ISSUE TITLE
[Add] add dsa roadmap in category other under roadmaps

### ISSUE THREAD

**Issue by psqaure11** [rupali-codes/LinksHub#1939]
### Site URL

https://www.guvi.in/blog/dsa-roadmap-beginners-should-know/

### Description of the above provided site

GUVI offers free and paid learning courses on various IT and tech domains in Indian vernacular languages .GUVI's mission is "to make technical education available to all in their native languages" .This EdTech company provides diverse professional and certificate tech courses to students, graduates, and working professionals who wish to upskill themselves.

### Category

Other

### Sub Category

roadmaps

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@psqaure11 

Make sure to keep the title concise and convenient.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
