### ISSUE TITLE
Want to add a new  Sub category  AI Chatbots under AI for Chat GPT Prompt Engineering 

### ISSUE THREAD

**Issue by Sanyam-2026** [rupali-codes/LinksHub#1941]
### Category Name

AI

### Subcategory Name

AI Chatbots

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Sanyam-2026 
What is the category and subcategory?

I don't understand, where do you want to add.

**Comment by Sanyam-2026** [comment]
> @Sanyam-2026 What is the category and subcategory?
> 
> I don't understand, where do you want to add.

The category will be Prompt Engineering and about Sub category I am bit confused can you suggest one

**Comment by CBID2** [comment]
> > @Sanyam-2026 What is the category and subcategory?
> > I don't understand, where do you want to add.
> > @Anmol-Baranwal
> > The category will be Prompt Engineering and about Sub category I am bit confused can you suggest one  or you can suggest the category where I can add it . Its my first time to contribute so I am not aware very much about it

Hi @Sanyam-2026. We have subcategories for each resource to make it more organized. [The Appending Categories section of The Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#appending-new-categories-) elaborates on this a bit more. If you need more help, tag me, @Anmol-Baranwal, or @rupali-codes.
