### ISSUE TITLE
[Add] <Want to add youtube playlist of Javascript in hindi>

### ISSUE THREAD

**Issue by Atul72** [rupali-codes/LinksHub#1942]
### Site URL

https://youtube.com/playlist?list=PLwgFb6VsUj_n15Cg_y2ULKfsOR1XiQqPx&si=UJyXUgEH0_94SpYj

### Description of the above provided site

Complete javascript from beginner to mastery.

### Category

Languages

### Sub Category

JavascriptInHindi

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Atul72** [comment]
@Anmol-Baranwal  ,  As i see there is no sub category in youtube for javascript. Would i create one and then update it in the data.ts and index.ts or add it in language category.

**Comment by Anmol-Baranwal** [comment]
@Atul72 
It's here.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/e0795a00-b66a-48be-850c-9a1faf20df70)


revise the description of the issue and raise PR accordingly.
