### ISSUE TITLE
[Add] <Want to add Redux Toolkit playlist in English >

### ISSUE THREAD

**Issue by Tusharrgrg** [rupali-codes/LinksHub#1944]
### Site URL

https://www.youtube.com/playlist?list=PLC3y8-rFHvwiaOAuTtVXittwybYIorRB3

### Description of the above provided site

In this tutorial series on Redux Toolkit for beginners, they dive into the what, why and the how.

### Category

Frontend

### Sub Category

"react"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Tusharrgrg 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
