### ISSUE TITLE
[BUG] Remove description revealing popup (and show it in a tooltip)

### ISSUE THREAD

**Issue by aftabrehan** [rupali-codes/LinksHub#1945]
### Description

Why display a popup upon clicking it? Simply hovering over it should reveal the description, and opening a popup on click seems like unnecessary complexity.

### Screenshots

<img width="2056" alt="Screenshot 2023-10-11 at 2 45 49 PM" src="https://github.com/rupali-codes/LinksHub/assets/93012310/598b698c-38db-417b-8760-8f61d68042d5">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@aftabrehan 
Where are you seeing this?

It is visible on hover, you dont need to click on it.

**Comment by Anmol-Baranwal** [comment]
Oh! I understand. Yeah, it does simplify the user experience. Definitely worth proceeding.

**Comment by aftabrehan** [comment]
@CBID2, can I work on this issue?

cc @Anmol-Baranwal

**Comment by CBID2** [comment]
> @CBID2, can I work on this issue?
> 
> 
> 
> cc @Anmol-Baranwal 

Let's focus on the other issue you raised

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Let him work on this. No issue has been assigned to him, and he is working closely on discord.

@aftabrehan 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
