### ISSUE TITLE
[ADD] Addition of web dev learning resources

### ISSUE THREAD

**Issue by Sanchitbajaj02** [rupali-codes/LinksHub#1951]
### Category Name

Learning resources

### Subcategory Name

Didn't think yet

### Additional Context

Hi 👋
I want to add a category with the name `Learning resources` because I couldn't find that. If it is already there, let me know and if it isn't then please assign me this issue.

I am thinking of adding web dev learning resources so if there is any sub-category under the frontend or backend category, please let me know as well.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Hi @Sanchitbajaj02. We don't have learning resources section in Web Dev. we just place courses in their respective categories. For example, if you have a course on JavaScript, you'd put in [the JavaScript subcategory](https://www.linkshub.dev/languages/javascript).

**Comment by Sanchitbajaj02** [comment]
> Hi @Sanchitbajaj02. We don't have learning resources section in Web Dev. we just place courses in their respective categories. For example, if you have a course on JavaScript, you'd put in [the JavaScript subcategory](https://www.linkshub.dev/languages/javascript).

Ok, I will create a new issue related to that
