### ISSUE TITLE
[Add] <Want to add links for Online Code Editors>

### ISSUE THREAD

**Issue by Kritika30032002** [rupali-codes/LinksHub#1954]
### Site URL

https://www.programiz.com/cpp-programming/online-compiler/

### Description of the above provided site

The user friendly online compiler that allows you to Write code and run it online. The text editor also supports taking input from the user, process and display output.

### Category

Frontend

### Sub Category

Online Code Editors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Kritika30032002 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by rupali-codes** [comment]
@Kritika30032002 & @Anmol-Baranwal this site has already been added

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/dcf33f53-b046-460c-919d-df95e4a3d606)

As the reason being mentioned, i'm closing this issue, though @Kritika30032002 you can work on #1958 :)

**Comment by Anmol-Baranwal** [comment]
Okay, I forgot to check this one I think.

@Kritika30032002 
Sorry, I usually check resources.
