### ISSUE TITLE
[BUG] <From Font category , Remove Icon library(Font Awesome) link>

### ISSUE THREAD

**Issue by Kritika30032002** [rupali-codes/LinksHub#1955]
### Description

https://fontawesome.com/

This is icon library and not font library thus needs to be removed from front category.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/83400697/1144b7fa-ed20-46ef-94a5-668e01d4b6fa)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Kritika30032002 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.

**Comment by Lavesh1208** [comment]
@Anmol-Baranwal 
I've identified the issue and have already resolved it. May I proceed to create a pull request for this?

**Comment by Kritika30032002** [comment]
> @Anmol-Baranwal I've identified the issue and have already resolved it. May I proceed to create a pull request for this?

As I have identified this bug, so plz let me do this issue.
You can look for another issue from website.

**Comment by Lavesh1208** [comment]
@Kritika30032002 go ahead, it's all yours

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal I have raised the PR for the assigned issue. After merging that PR, you can now assign me this.

It is always preferred to read contributing guidelines: https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/1f20a879-640e-4c7d-a4f8-efe2aaf1d873)

So, make new issues once you get the PR merged for the existing ones. There are always other issues from which you can contribute.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal I've identified the issue and have already resolved it. May I proceed to create a pull request for this?

@Lavesh1208 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Kritika30032002** [comment]
I read it later. Sorry for my mistake 
Will never do it again

**Comment by Kritika30032002** [comment]
But now can you assign me this after merging my pr ?

**Comment by Anmol-Baranwal** [comment]
> "But now, can you assign this to me after merging my PR? 

It can't be. Once someone comments, I'm obligated to assign the issue to them.
We have a strict system, which helps others contribute effectively.

![label](https://github.com/rupali-codes/LinksHub/assets/74038190/17d6044a-f674-4d4d-ab44-f444daec0e8a)

We're also working on creating a custom workflow where this process will be automated. It will help people avoid making the same mistake.

Once you've submitted some PRs, or if we know you can work on high-priority issues, you can be assigned multiple issues. However, it's challenging when someone opens three issues simultaneously.

I hope you understand.

**Comment by Kritika30032002** [comment]
Ya okay
