### ISSUE TITLE
[Add] <Adding CPP Video Tutorial link>

### ISSUE THREAD

**Issue by Kritika30032002** [rupali-codes/LinksHub#1958]
### Site URL

https://www.youtube.com/watch?v=z9bZufPHFLU&list=PLfqMhTWNBTe0b2nM6JHVCnAkhQRGiZMSJ

### Description of the above provided site

Exclusive C++ Programming playlist by Apna College. Beginner to Advanced

### Category

Languages

### Sub Category

c++ programming

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Kritika30032002 

#1954 is assigned to you.

It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.
