### ISSUE TITLE
[ADD] <DSA Subcategory>

### ISSUE THREAD

**Issue by aditya9277** [rupali-codes/LinksHub#1959]
### Category Name

Resources

### Subcategory Name

DSA

### Additional Context

Adding 'Data Structures and Algorithms' Subcategory under 'Resources' category.

This section will contain various resources like DSA cheatsheets, DSA roadmaps, DSA problem sheets and much more everything related to Data Structures and Algorithms.

This subcategory will definitely be a great addition to the website and the resources. 

I have already worked before in adding a subcategory, so please assign me with this.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@aditya9277 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
