### ISSUE TITLE
[Feature] Add New Logo for LinksHub

### ISSUE THREAD

**Issue by aftabrehan** [rupali-codes/LinksHub#1960]
### Description

This issue is opened to Update LinksHub Logo and [README.md](https://github.com/rupali-codes/LinksHub/blob/main/README.md) banner.

#### Logo

<div align="center">
 <img src="https://github.com/rupali-codes/LinksHub/assets/93012310/228854a9-09be-46ac-af8b-26843cf7d3c0" alt="logo" />
</div>

<hr />

#### Favicon

<div align="center">

Light | Dark
-- | --
<img src='https://github.com/rupali-codes/LinksHub/assets/93012310/65aea49b-8dfa-47b6-9667-9e66a7c63d07' alt=“light-favicon”> | <img src='https://github.com/rupali-codes/LinksHub/assets/93012310/c7215aae-3add-4f3f-8da7-c80e85789c31' alt=“dark-favicon”>

</div>

<hr />

#### Discord

<div align="center">
 <img src="https://github.com/rupali-codes/LinksHub/assets/93012310/960b7609-3612-48ce-8caf-0d0c67bc415e" alt="logo" />
</div>

<hr />

#### Discord

<div align="center">
 <img src="https://github.com/rupali-codes/LinksHub/assets/93012310/9bb90a4d-1f81-4f06-abb4-46f2f0bf3314" alt="logo" />
</div>

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@CBID2 @rupali-codes 
What do you think?

**Comment by rupali-codes** [comment]
they looks great, @aftabrehan can we make the background transparent for favicon? then we can use the same for Discord and other socials as well

**Comment by rupali-codes** [comment]
it's the coolest one

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/615a7a8e-bc4b-42de-a9e2-d943806c7f63)

**Comment by rupali-codes** [comment]
@aftabrehan @Anmol-Baranwal any updates guys?

**Comment by rupali-codes** [comment]
> I don't know, maybe he is busy.
> 
> Maybe if you want to add it internally, then ask him.

let's do it in the new design

**Comment by aftabrehan** [comment]
Yeah, could be covered in the new header.

**Comment by Anmol-Baranwal** [comment]
Closing this, as discussed.
