### ISSUE TITLE
[DOCS] <Adding github stats icons to the Readme.md file>

### ISSUE THREAD

**Issue by Kalyanimhala** [rupali-codes/LinksHub#1962]
### Issue Description

There is no GitHub stats icon in the readme.md file. we want to add it because, adding GitHub stats icons in a readme file enhances your project's appeal and communicates key statistics, like stars, forks, and issues, at a glance. This boosts credibility, attracts contributors, and fosters community engagement, but they should complement, not replace, comprehensive project documentation.

### Screenshots or Examples (if applicable)

![github stats](https://github.com/rupali-codes/LinksHub/assets/147402107/351c2a0b-2a9c-4684-99af-6ba98c14df48)

### Proposed Solution (optional)

Adding gitHub stats icons to the Readme.md file by updating the readme file!

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Kalyanimhala 

We are very strict towards the theme, and these are not necessary.

Someone who wants to know, can check it out directly. 

@CBID2 @rupali-codes 
What do you think? For me, it's not worth it.

> I have used this in the past
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/4f4f5fbb-09ef-4203-b58c-26f693225ca8)

**Comment by rupali-codes** [comment]
@Anmol-Baranwal i agree with you, all these details have already been provided by Github, so it's not necessary to include in README. 

@Kalyanimhala we appreciate your willingness to contribute in LinksHub, but we don't really need it. Please feel free to contribute to other open issues or raise the new ones. 

Thanks

**Comment by Kalyanimhala** [comment]
okay 👍

**Comment by CBID2** [comment]
I share this sentiment
