### ISSUE TITLE
[DOCS] Indentation of code block and image in Contributions.md files

### ISSUE THREAD

**Issue by SusheelThapa** [rupali-codes/LinksHub#1964]
### Issue Description

I and very excited to contribute to this repository by adding Github Readme badge as shown in screenshot.

### Screenshots or Examples (if applicable)

![Screenshot from 2023-10-11 21-05-12](https://github.com/rupali-codes/LinksHub/assets/83917129/3c324331-395e-453a-b736-2a6a2e4647b0)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Kalyanimhala 

We are very strict towards the theme, and these are not necessary.

Someone who wants to know, can check it out directly. 

For me, it's not worth it.

> I have used this in the past
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/4f4f5fbb-09ef-4203-b58c-26f693225ca8)

You can read more in here: #1962 

Closing this.
