### ISSUE TITLE
[Add] Exercism CP Platform

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#1969]
### Site URL

https://exercism.org

### Description of the above provided site

Exercism is an online, open-source, free coding platform that offers code practice and mentorship on 66 different programming languages.

### Category

Competitive Programming

### Sub Category

Platforms

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/15a7389a-9e7a-46ed-b954-99ccb5852261)

Exercism is already included, but since the subcategory is different, I think we can move forward with this, considering the variety of questions specific to these programming languages for competitive programming.

@Shiva-Sai-ssb 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Anmol-Baranwal** [comment]
You are not participating in hacktoberfest, so I'm not adding the labels.

Also, please tick the boxes if you are willing to work on this, else I will make it open for others to grab.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/70139db7-f413-4eb4-9c7d-d6875eaac595)

**Comment by Shiva-Sai-ssb** [comment]
> You are not participating in hacktoberfest, so I'm not adding the labels.
> 
> Also, please tick the boxes if you are willing to work on this, else I will make it open for others to grab.
> 
> ![image](https://user-images.githubusercontent.com/74038190/274697258-70139db7-f413-4eb4-9c7d-d6875eaac595.png)

I have another Pull Request that is still open. I didn't tick the boxes for this issue because I don't want to work on it. Please assign it to someone else. Thanks

**Comment by Anmol-Baranwal** [comment]
@Shiva-Sai-ssb 
Thanks for letting me know.

**Comment by Hrithik0112** [comment]
Hi @Anmol-Baranwal I've read the above issue, I am willing to work on this issue . 
I'm also participating in hacktoberfest 2023. 
Could You Assign the Issue to Me?

**Comment by Anmol-Baranwal** [comment]
@Hrithik0112 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Hrithik0112** [comment]
@Anmol-Baranwal ok thanks, I will surely contact you guys if I need any assistance.
