### ISSUE TITLE
[Feature] Enhanced Accessibility Features for Improved User Experience

### ISSUE THREAD

**Issue by supunsathsara** [rupali-codes/LinksHub#1978]
### Description

This issue is raised to propose enhancements regarding the website's accessibility, ensuring an inclusive experience for all users, including those with disabilities. Key areas of improvement may include implementing keyboard navigation, enhancing screen reader compatibility, optimizing color contrast, and ensuring proper focus management. 

_Note: I am eager to contribute to this issue and would appreciate it if you could assign it to me for Hacktoberfest 2023._

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@supunsathsara 
What do you suggest?

**Comment by supunsathsara** [comment]
> @supunsathsara What do you suggest?

Would like to work on below small Suggestions from https://pagespeed.web.dev

![image](https://github.com/rupali-codes/LinksHub/assets/67389877/2f23652f-ba4e-4f63-b402-15f6b6aa4549)

Also it shows that Background and foreground colors do not have a sufficient contrast ratio. If it is ok to change the color contrast, will fix those too.

**Comment by Anmol-Baranwal** [comment]
@supunsathsara 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

Don't change the contrast, the new accessible color palette is handled in another PR.
