### ISSUE TITLE
[OTHER] chore: enhance LICENSE section in README 

### ISSUE THREAD

**Issue by malivinayak** [rupali-codes/LinksHub#1979]
### Changes proposed
- Update the LICENSE section in the README file to enhance the presentation. Added a MIT logo, license badge and updated text with a cleaner format, including a hyperlink to the LICENSE file.
- I have already created PR #1977 

### Screenshots
- Current:
![image](https://github.com/rupali-codes/LinksHub/assets/66154908/a0c705e6-a4f3-4bca-8815-cc23967e4c49)
- Updates:
![image](https://github.com/rupali-codes/LinksHub/assets/66154908/07701e47-a766-4751-a7ce-305250accd39)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 

What do you think?

**Comment by CBID2** [comment]
> @rupali-codes @CBID2
> 
> What do you think?

It could help. What do you think @rupali-codes?

**Comment by CBID2** [comment]
> @CBID2 any updates
> 
> 

@Anmol-Baranwal, should we just go ahead assign the issue?

**Comment by Anmol-Baranwal** [comment]
> > @CBID2 any updates
> > 
> > 
> 
> @Anmol-Baranwal, should we just go ahead assign the issue? I don't want to frustrate @malivinayak waiting putting them on hold. 

I have done it.

**Comment by Anmol-Baranwal** [comment]
@malivinayak 
I have assigned you the issue. Please move forward with this.
