### ISSUE TITLE
[BUG] Some Category Descriptions isn't visible even after hovering

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#1982]
### Description

There are several subcategories for which tooltip is not visible even when hovering over the icon.

Even for deployed link, Online code editors description isn't visible on hover.

I checked it locally, and it is working properly.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/4f3c96ea-30c7-4053-84f3-02eac6f93b6f)

### Any additional information?

It is running fine locally, but there seems to be problems in the deployed link I wonder what's causing the issue.

@CBID2 @rupali-codes 

You noticed it right.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Yeah I noticed this too @Anmol-Baranwal.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal there's a bug actually, when scroll to bottom and then click on the `i` button, then it shows the desc not when you're on the top.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Check for articles under open source. The bug doesn't follow this pattern.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal  & @CBID2 are you still facing this issue?

**Comment by CBID2** [comment]
> @Anmol-Baranwal  & @CBID2 are you still facing this issue?

Hold on

**Comment by CBID2** [comment]
> @Anmol-Baranwal  & @CBID2 are you still facing this issue?

Yes @rupali-codes. I think Aftan's PR solves this problem

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal  & @CBID2 are you still facing this issue?
> 
> Yes @rupali-codes. I think Aftan's PR solves this problem

oh, alright then, please link this issue to that PR :)

**Comment by CBID2** [comment]
> > > @Anmol-Baranwal  & @CBID2 are you still facing this issue?
> 
> > 
> 
> > Yes @rupali-codes. I think Aftan's PR solves this problem
> 
> 
> 
> oh, alright then, please link this issue to that PR :)

Done
