### ISSUE TITLE
[Add] GSAP animation library

### ISSUE THREAD

**Issue by psykat1116** [rupali-codes/LinksHub#1983]
### Site URL

https://gsap.com/

### Description of the above provided site

**[GSAP](https://gsap.com/)** is a robust industry standard **JavaScript** animation library from GreenSock that lets you craft high-performance animations that work in every major browser. Animate CSS, SVG, canvas, React, Vue, WebGL, colors, strings, motion paths, generic objects...anything JavaScript can touch!

### Category

Frontend

### Sub Category

animations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@psykat1116 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
