### ISSUE TITLE
[Add]  System Design Primer Github Repo

### ISSUE THREAD

**Issue by Akib-Vijapura** [rupali-codes/LinksHub#1984]
### Site URL

https://github.com/donnemartin/system-design-primer

### Description of the above provided site

The System Design Primer stands out as one of the most widely embraced GitHub repositories for acquiring knowledge in the realm of system design

### Category

Backend

### Sub Category

system design

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Akib-Vijapura 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
