### ISSUE TITLE
[Feature] Add Like functionality.

### ISSUE THREAD

**Issue by Akib-Vijapura** [rupali-codes/LinksHub#1985]
### Description

Implement a "Like" feature that allows users to express their appreciation for specific resources. This functionality will facilitate the identification of popular content within distinct categories for everyone's benefit.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
Hi @Akib-Vijapura

We are working on this in #1766 

So, I am closing this. Thanks for opening it.
