### ISSUE TITLE
[Add] <Adding C programming playlist link>

### ISSUE THREAD

**Issue by Kritika30032002** [rupali-codes/LinksHub#1986]
### Site URL

https://www.youtube.com/watch?v=irqbmMNs2Bo&t=18393s

### Description of the above provided site

C Language Tutorial for Beginners (with Notes & Practice Questions)

### Category

Languages

### Sub Category

c programming

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Kritika30032002 
Please improve the description as well as the title of PR. It seems generic.

I will deal with this.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/ee2ea457-4841-4cff-a0a4-02d895d10fc8)

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Kritika30032002** [comment]
> @Kritika30032002 Please improve the description as well as the title of PR. It seems generic.
> 
> I will deal with this.
> 
> ![image](https://user-images.githubusercontent.com/74038190/275287875-ee2ea457-4841-4cff-a0a4-02d895d10fc8.png)
> 
> I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

this is not my pr

**Comment by Anmol-Baranwal** [comment]
> this is not my pr

Yeah, I am aware of that. We handled it properly.

**Comment by Kritika30032002** [comment]
My pr is also done now #1996
