### ISSUE TITLE
[BUG] FOOTER 

### ISSUE THREAD

**Issue by pramodreddypandiri** [rupali-codes/LinksHub#199]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Footer is not clearly visible in light mode

### Screenshots

<img width="872" alt="image" src="https://user-images.githubusercontent.com/98374193/218817561-a3e706e6-18ea-40e3-9b48-3c00ba35fc04.png">

### Any additional information?

If you observe keenly then only you can see footer.

**Comment by rupali-codes** [comment]
would you like to work on this?

**Comment by hparashar27** [comment]
hey @rupali-codes i want to work on this

**Comment by rupali-codes** [comment]
> hey @rupali-codes i want to work on this

Yes you can
