### ISSUE TITLE
[DOCS] fix discord icon broken link in readme

### ISSUE THREAD

**Issue by oyepriyansh** [rupali-codes/LinksHub#1990]
### Issue Description

The issue involved replacing a broken link in the README with a new icon source to maintain the documentation's integrity and functionality.

### Screenshots or Examples (if applicable)

![linkshub](https://github.com/rupali-codes/LinksHub/assets/83062406/02ad6f72-2004-4d64-9af2-29800cd3c8ae)

### Proposed Solution (optional)

I have fixed it. Once I am assigned, I will open a PR.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Welcome to LinksHub, @oyepriyansh! :) You've been assigned to this issue. Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
