### ISSUE TITLE
[ADD] free domains category

### ISSUE THREAD

**Issue by oyepriyansh** [rupali-codes/LinksHub#1992]
### Category Name

none

### Subcategory Name

Domains

### Additional Context

a category to list free domains/subdomains service 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Can you elaborate on this more @oyepriyansh?

**Comment by oyepriyansh** [comment]
I know some free services which provides free subdomains for developers some of I owned are
- [priyansh.is-a.dev](https://priyansh.is-a.dev) from [is-a.dev](https://is-a.dev)
- [priyan.sh.gg](https://priyan.sh.gg) from [willin](https://github.com/willin/domain)

I know about some more similar services

**Comment by oyepriyansh** [comment]
can you assign this to me?

**Comment by Anmol-Baranwal** [comment]
@oyepriyansh 
If you want to add a domain name buying platforms, otherwise this issue doesn't make any sense.

**Comment by oyepriyansh** [comment]
these are free subdomains provider

**Comment by oyepriyansh** [comment]
> these are free subdomains provider

@Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@oyepriyansh 
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/3bebebf6-82e6-47d6-b61a-4d246ad694b4)

You can add a subcategory in Other for domain name service.

Just don't add these providers, I'm not sure if these are the quality ones.

Also, don't create multiple issues as we have a rule that enforced you only work on 1 issue at a time. I would have made this open for others to grab.

No worries. I have assigned you.
