### ISSUE TITLE
[ADD] Freepic Icons  recourse link

### ISSUE THREAD

**Issue by Hemant-Lohar** [rupali-codes/LinksHub#1993]
### Site URL

https://www.freepik.com/icons

### Description of the above provided site

This provides a 10M+ free PNG and SVG icons, including the one you have in mind.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 

Freepik is already included in images, and illustrations. Should we add it here too?

**Comment by CBID2** [comment]
> @rupali-codes 
> 
> 
> 
> Freepik is already included in images, and illustrations. Should we add it here too?

Probably not @Anmol-Baranwal. It'll create duplication.

**Comment by Hemant-Lohar** [comment]
we can add freepic's icons section and other illustration and images sections different from the icons section. So, we can add it separately in frontend/icons section. It's for icons only. @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Below one might work to avoid duplication.

@Hemant-Lohar 
Just make sure to put Freepik Icons in the title, at least it will be distinctive.

**Comment by Anmol-Baranwal** [comment]
@Hemant-Lohar 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

But please write the title and description properly, so that it says about icons.
