### ISSUE TITLE
[ADD] free-programming-books of open_source/projects

### ISSUE THREAD

**Issue by codeOraaange** [rupali-codes/LinksHub#1997]
### Category Name

open_source

### Subcategory Name

projects

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
What do you want to do?

@codeOraaange 
There is already a subcategory for this.

**Comment by codeOraaange** [comment]
@Anmol-Baranwal I want add url free-programming-books of category open_source and subcategory projects.

**Comment by CBID2** [comment]
@Anmol-Baranwal, they want to put this OSS project in the Open Source category. 
@codeOraaange, you’ve been assigned to this issue. Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out this article, [How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions that are <!—- —-!> in the PR template to fill it out effectively. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
