### ISSUE TITLE
Add: uicolors

### ISSUE THREAD

**Issue by haseebyousuf** [rupali-codes/LinksHub#2003]
### Site URL

https://uicolors.app/

### Description of the above provided site

uicolors is a interactive Tailwind CSS Color Palette Generator with real examples. Here we can create our own palette or edit anything from the library. It also allows us to import the palette directly to Figma file.

### Category

Frontend

### Sub Category

"colors","themes & templates"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@haseebyousuf you are assigned!

**Comment by Souradeephazra123** [comment]
hey @rupali-codes, Can you assign this issue to me ?

**Comment by Anmol-Baranwal** [comment]
@Souradeephazra123 
It is already assigned, you can look for issues with label: `up for grabs` or create new ones.
