### ISSUE TITLE
[ADD] open source programs subcategory

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2004]
### Category Name

Open Source

### Subcategory Name

Open Source Programs

### Additional Context

Events like Google Summer of Code, and several notable ones should be added.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@goobric 
Comment here to get assigned.

**Comment by Akib-Vijapura** [comment]
I want to work on this issue

**Comment by Vijaykv5** [comment]
would like to work on it

**Comment by Kritika30032002** [comment]
assign this to me

**Comment by Anmol-Baranwal** [comment]
This is not open to others. I made this for goobric. If he is not willing to work on this. Then I will assign the first comment.

**Comment by Kritika30032002** [comment]
Okay

**Comment by Anmol-Baranwal** [comment]
> hi @Anmol-Baranwal please assign me this issue, thank you I am so sorry that I did not see this; does github notify a user if an issue or pr has been assigned to them?

Yes, you can watch the repositories, and normally you will get the notifications.
