### ISSUE TITLE
[Add] <C++ Standard Template Library (STL) Video Link>

### ISSUE THREAD

**Issue by YashSalunke12** [rupali-codes/LinksHub#2006]
### Site URL

https://www.youtube.com/watch?v=RRVYpIET_RU

### Video Link Details:
**Title:**   Add C++ Standard Template Library (STL) Video Link
**URL:**   https://www.youtube.com/watch?v=RRVYpIET_RU

### Description:
LinksHub is a valuable resource for developers seeking to expand their knowledge on various programming topics. In line with this mission, I propose adding a video link related to the C++ Standard Template Library (STL) to enhance the project's content.

### Why This Addition Is Beneficial:

- The C++ STL is a fundamental component of the language, and developers often seek resources to improve their understanding.
- The video covers important topics or concepts not currently addressed in the project.
- It enhances the project's comprehensiveness and value to the developer community.

### Request for Feedback:
I welcome feedback and suggestions from maintainers and contributors regarding this proposed addition. Let's collaborate to ensure that this enhancement aligns with the project's goals and standards.

Please let me know if there are any specific guidelines or requirements I should follow while creating this PR. I look forward to your feedback and guidance on this matter.

### Category

Languages

### Sub Category

C++ Programming

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@YashSalunke12 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by YashSalunke12** [comment]
@Anmol-Baranwal take a look on this PR
