### ISSUE TITLE
[ADD] DSA Resources subcategory

### ISSUE THREAD

**Issue by Kritika30032002** [rupali-codes/LinksHub#2007]
### Category Name

DSA

### Subcategory Name

DSA Resources

### Additional Context

Like any website dsa course, youtube playlist of dsa

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Kritika30032002 
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/9d3cc8ad-6aae-41a5-8dd5-89c689e1ec72)

The category does exist, and you need to define the subcategory.

I don't think resources would work, maybe tutorials, courses would be better.

What do you think?

**Comment by Kritika30032002** [comment]
Category is DSA
sub category is DSA resources

**Comment by Anmol-Baranwal** [comment]
@Kritika30032002 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

I'm not sure about the subcategory, do whatever you prefer. I would like to be separate.
Still, if there are changes required then we will request it in the PR.

**Comment by Kritika30032002** [comment]
@Anmol-Baranwal You can assign this to anyone else. I have some prior work so won't be able to take this now.

**Comment by Anmol-Baranwal** [comment]
@Kritika30032002 
No worries, thanks for letting me know :)

**Comment by thatdamncoder** [comment]
Hello @Anmol-Baranwal @rupali-codes @CBID2 
I have made some changes to this issue
Maybe this was what @Kritika30032002 meant to add in the DSA section
Kindly check for any changes and please do let me know about other corrections
This is just for a demo, I will surely add more courses if you permit



<img width="960" alt="Screenshot 2023-10-20 234833" src="https://github.com/rupali-codes/LinksHub/assets/144144009/4ad47cd8-6841-41ea-9688-a3256de50c63">


 P.S. Though this is my first time working on a big project like this, I'll make sure I complete what is assigned to me. 
Please do check this out

**Comment by Anmol-Baranwal** [comment]
@thatdamncoder 
You can create a PR. We will review it.

**Comment by Anmol-Baranwal** [comment]
@thatdamncoder 
It is necessary that you ask us to assign you the issue, so let me know if you will contribute this?

I will assign you the issue.

**Comment by thatdamncoder** [comment]
@Anmol-Baranwal thankyou for letting me contribute
sure, you can assign me the issue

**Comment by thatdamncoder** [comment]
Hello @rupali-codes 
Can you please assign me the issue so that I can create the PR

**Comment by thatdamncoder** [comment]
@Anmol-Baranwal 
@rupali-codes 
@CBID2 
Can anybody please help
Why is this showing up when I'm trying to run the site on my local host?

<img width="772" alt="Screenshot 2023-10-22 004544" src="https://github.com/rupali-codes/LinksHub/assets/144144009/ca61fd75-a597-493c-9a51-2b3bcfd069cd">

**Comment by thatdamncoder** [comment]
I am ready with my PR
Do let me know when shall i create a request
Please do assign so that I can proceed further
@Anmol-Baranwal
@rupali-codes
@CBID2

**Comment by CBID2** [comment]
> I am ready with my PR
> 
> Do let me know when shall i create a request
> 
> Please do assign so that I can proceed further
> 
> @Anmol-Baranwal
> 
> @rupali-codes
> 
> @CBID2
> 
> 

Hi @thatdamncoder. @Kritika30032002, has expressed interest in doing this issue, so let's see if they still want to.

**Comment by Anmol-Baranwal** [comment]
@thatdamncoder 
Please check it locally and then raise a PR.
