### ISSUE TITLE
[CHORE] add discord link in README & website

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#201]
### What would you like to share or ask?

I just created this Discord for real time collaboration and to help people.

* Add this discord link [https://discord.gg/NvK67YnJX5](https://discord.gg/NvK67YnJX5) in README.md file 
* Also add this in our website [https://linkshub.vercel.app](https://linkshub.vercel.app) 
  _beside github icon_

![image](https://user-images.githubusercontent.com/78981177/218958378-e5ad05e4-986c-4fc3-ae43-89234973112b.png)

**Comment by zvolcsey** [comment]
@rupali-codes Hi! Can I work on this issue?

**Comment by rupali-codes** [comment]
> @rupali-codes Hi! Can I work on this issue?

Yes sure

**Comment by sobczyk-m** [comment]
Hi, I sent a pull request.
