### ISSUE TITLE
[Add] zSecurity website link under cyber security category

### ISSUE THREAD

**Issue by singodiyashubham87** [rupali-codes/LinksHub#2017]
### Site URL

https://zsecurity.org/
### Description of the above provided site

zSecurity is a leading provider of ethical hacking and cyber security training, we teach hacking and security to help people become ethical hackers so they can test and secure systems from black-hat hackers.

### Category

Cyber Security

### Sub Category

Offensive Security

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@singodiyashubham87 
Please update the site url. It should be the website you wish to add.

I need to see it before assigning you the issue.

**Comment by singodiyashubham87** [comment]
@Anmol-Baranwal https://zsecurity.org/

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal Hey Anmol, there is no directory for cyber-security but there are still resources for cyber security on the website, How? Should I create a new category or add my resource to somewhere else?
> 
> ![image](https://user-images.githubusercontent.com/93720428/275898165-8adac679-6895-4696-bc3f-159d2ab9ff89.png) ![image](https://user-images.githubusercontent.com/93720428/275898245-d019e7e9-014c-4a88-a4a4-4efc87afc7ef.png)

Woah! Let me see and get back to you. It shouldn't happen LOL!

**Comment by KrishavRajSingh** [comment]
is this open?

**Comment by Anmol-Baranwal** [comment]
> is this open?

You can find open issues with label: `up for grabs`

Comment there, and I will assign you the issue unless someone has asked first.
