### ISSUE TITLE
[Add] Chai aur Code Youtube Channel

### ISSUE THREAD

**Issue by pratikkumar399** [rupali-codes/LinksHub#2018]
### Site URL

https://www.youtube.com/@chaiaurcode

### Description of the above provided site

This is an underrated youtube channel mainly focussed on full stack development.

### Category

Youtube

### Sub Category

web-development

### Checklist

- [x] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@pratikkumar399 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by pratikkumar399** [comment]
Hi, @Anmol-Baranwal I have opened a pr. Please check if it fine.
