### ISSUE TITLE
[Add] New Link to Themes in Front-End.

### ISSUE THREAD

**Issue by surya-mu** [rupali-codes/LinksHub#2027]
### Site URL

https://themesberg.com/

### Description of the above provided site

It is a website for free and premium Bootstrap based Templates, Themes and built-in UI Tool kits.
**Free and Premium** themes, templates, admin dashboards and UI kits built in Bootstrap, React, Laravel, and Figma used by many popular web developers and software companies

### Category

Frontend

### Sub Category

"themes & templates"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@surya-mu 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
