### ISSUE TITLE
[BUG] Optimize Dockerfile for Efficient Image Building

### ISSUE THREAD

**Issue by Saurav-Pant** [rupali-codes/LinksHub#2028]
### Description

Currently, the Dockerfile includes multiple COPY instructions, leading to a larger number of image layers and a potentially less efficient build process.
This issue suggests optimizing the Dockerfile by combining related COPY instructions into a single step. This can improve image build times and reduce the number of layers, indirectly enhancing the efficiency of image creation.

### Screenshots

![Rupali](https://github.com/rupali-codes/LinksHub/assets/103263909/b99a22da-4104-4cd9-8916-ebc45c1240f5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@Anmol-Baranwal i guess it would be better this way.

@Saurav-Pant you can start working on this issue
