### ISSUE TITLE
[ADD] new link for git learning resources

### ISSUE THREAD

**Issue by Sanchitbajaj02** [rupali-codes/LinksHub#2030]
### Category Name

Other

### Subcategory Name

Git

### Additional Context

Aim to introduce a new sub-category called Git which contains the resources to learn git commands. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Sanchitbajaj02 
I'm not sure if this idea fits well considering the scale of resources.

No worries.
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by chinmay7016** [comment]
@Anmol-Baranwal can you pls assign this issue to me

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal can you pls assign this issue to me

This is already assigned, you can look for issues with label: `up for grabs` or create new ones using template.
