### ISSUE TITLE
[OTHER] add Bootstrap , semantic UI and SeamlessUI to UI libraries 

### ISSUE THREAD

**Issue by hritikbhattacharya** [rupali-codes/LinksHub#2035]
Location : Frontend/UI libraries

add Bootstrap , Semantic UI and Seamless UI links .

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@hritikbhattacharya 
We don't want every resource on LinksHub. Most of which you mentioned is not even a UI Library.

> A good example of a UI library would be Bootstrap, Material-UI, or Semantic UI.

**Comment by hritikbhattacharya** [comment]
Then should I add Bootstrap , semantic UI , seamless UI links to the Ui library.

**Comment by Anmol-Baranwal** [comment]
@hritikbhattacharya 
Revise the description, title and tag me again. Do only one, and check if it exists already on the LinksHub.

**Comment by hritikbhattacharya** [comment]
@Anmol-Baranwal now check

**Comment by Anmol-Baranwal** [comment]
@hritikbhattacharya 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

Don't create duplicate ones.
