### ISSUE TITLE
Added a YouTube playlist for learning DSA.

### ISSUE THREAD

**Issue by TaeMochi12** [rupali-codes/LinksHub#2037]
### Site URL

https://www.youtube.com/playlist?list=PLIY8eNdw5tW_zX3OCzX7NJ8bL1p6pWfgG

### Description of the above provided site

A YouTube playlist for learning Data Structures and Algorithms with C++ practical implementation (Full Course for Beginners).

### Category

Youtube

### Sub Category

data-structures

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@TaeMochi12 
There is a category for DSA. Make a new subcategory for youtube and add this there.

We are going to merge subcategory under youtube for dsa into this one later.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
