### ISSUE TITLE
[Add]: New ML Learning Course Playlist

### ISSUE THREAD

**Issue by Bratajit-03** [rupali-codes/LinksHub#2039]
### Site URL

https://www.youtube.com/@IndianAIProduction

### Description of the above provided site

This is one of the greatest Machine Learning learning course for beginners to start learning Machine Learning from scratch.

### Category

Youtube

### Sub Category

Machine Learning

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Bratajit-03 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
