### ISSUE TITLE
[ADD] New link for internet_of_things

### ISSUE THREAD

**Issue by subhayudutta** [rupali-codes/LinksHub#2042]
### Category Name

internet_of_things

### Subcategory Name

arduino

### Additional Context

# Description 
The subcategory contains link to Introduction to IOT with Arduino course for beginners by freecodecamp which is helpful for the beginners to start their career in field of IOT.

# Link to the course
https://www.freecodecamp.org/news/create-your-own-electronics-with-arduino-full-course

# Category
internet_of_things

# Sub Category
arduino

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@subhayudutta 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
