### ISSUE TITLE
[ADD] <Free Course Section>

### ISSUE THREAD

**Issue by chinmay7016** [rupali-codes/LinksHub#2043]
### Category Name

Free Course Section

### Subcategory Name

free certificate

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@chinmay7016 
There are millions of free certifications. Make it something specific.

**Comment by rupali-codes** [comment]
@chinmay7016 can you please elaborate more on what do you wanna add?

**Comment by chinmay7016** [comment]
> @chinmay7016 can you please elaborate more on what do you wanna add?

Means I wanna add a section where you can do free courses for example java or c++ and get free certificate not paid

**Comment by Anmol-Baranwal** [comment]
I am closing this since it is not required.
