### ISSUE TITLE
Add NASA's API in api.json

### ISSUE THREAD

**Issue by SoulNikhar** [rupali-codes/LinksHub#2048]
### Category Name
Backend

### Subcategory Name
API

### Additional Context

The NASA API falls under the "backend" category, specifically in the "API" subcategory. This API is a valuable tool for developers, researchers, and space enthusiasts who want to access NASA's vast repository of space-related data and content programmatically. Whether you're building a space-themed app, conducting research, or simply exploring the wonders of the universe, the NASA API offers a wide array of resources and information to assist you.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [x] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@SoulNikhar what do we use this API for? also, can you provide a short description?

**Comment by Anmol-Baranwal** [comment]
@SoulNikhar 
Properly update the description of the issue and share the url of api docs.

Tag me when it's done.

**Comment by SoulNikhar** [comment]
> @SoulNikhar what do we use this API for? also, can you provide a short description?

@rupali-codes  here is your Ans

Q) What do we use the NASA API for?

The NASA API is used to access various data, images, and information related to space, astronomy, and space missions. It provides a way to programmatically retrieve a wide range of information and resources related to NASA's activities and discoveries in space and astronomy.

Q) Short Description:

NASA's API provides access to a wealth of data, images, and information about space, astronomy, and space missions. Whether you're interested in exploring images of distant galaxies, tracking the International Space Station, or accessing information about NASA's research and missions, this API is a valuable resource.

**Comment by SoulNikhar** [comment]
> @SoulNikhar Properly update the description of the issue and share the url of api docs.
> 
> Tag me when it's done.

hii  @Anmol-Baranwal 

API Documentation URL:
You can find the API documentation at [NASA API Documentation](https://api.nasa.gov/).

and I updated description too. Please have a look

**Comment by Rohxn16** [comment]
i wanna work on this one
