### ISSUE TITLE
[BUG]: unwanted bottom margin for footer 🙅🏻 🚫 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#2051]
### Description

- Footer element consists of unwanted margin values for bottom, which makes bad impression about UI.
- This bug is applied for both Mobile & Desktop Layouts

### Screenshots

|MOBILE|DESKTOP|
|:---:|:---:|
| ![MOBILE](https://github.com/rupali-codes/LinksHub/assets/92252895/a6851f5c-796e-4f85-b447-db9a435b17ff) |![DESKTOP](https://github.com/rupali-codes/LinksHub/assets/92252895/bc0a1bb4-07a5-4b42-952f-0dcf40037161) |

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by 0xabdulkhalid** [comment]
Hey there @rupali-codes, @CBID2 👋🏻

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by CBID2** [comment]
It does look quite unattractive. What do you think @Anmol-Baranwal? @rupali-codes?

**Comment by rupali-codes** [comment]
> It does look quite unattractive. What do you think @Anmol-Baranwal? @rupali-codes?

Yeah and also kinda distracting,

@0xabdulkhalid you can start working on it, assigning to you!

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I cannot see this issue, I mean it isn't even scrollable in vertical direction.

Where are you seeing this?

**Comment by 0xabdulkhalid** [comment]
@Anmol-Baranwal Can i know what browser you're using? Because i found this bug on Firefox.

**Comment by Anmol-Baranwal** [comment]
@0xabdulkhalid 
Then why did you fill chrome in the issue description?

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/748a1695-b72b-415f-aac9-2ec239e16764)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I've checked, it exists on firefox.

**Comment by 0xabdulkhalid** [comment]
> @0xabdulkhalid Then why did you fill chrome in the issue description?
> 
> ![image](https://user-images.githubusercontent.com/74038190/277155481-748a1695-b72b-415f-aac9-2ec239e16764.png)

I used Chromium, the issue with that is i didn't updated it for months.
After updating it i can't this see this bug there.

I'm extremely sorry for that, It's my fault to test bug at older version of browser.

**Comment by Anmol-Baranwal** [comment]
> > @0xabdulkhalid Then why did you fill chrome in the issue description?
> > ![image](https://user-images.githubusercontent.com/74038190/277155481-748a1695-b72b-415f-aac9-2ec239e16764.png)
> 
> I used Chromium, the issue with that is i didn't updated it for months. After updating it i can't see this bug there.
> 
> I'm extremely sorry for that, It's my fault to test bug at older version of browser.

No need to say sorry. You are experienced contributor, so that is why I asked. 😅 Will review the PR soon.
