### ISSUE TITLE
Update database.json

### ISSUE THREAD

**Issue by SoulNikhar** [rupali-codes/LinksHub#2053]
### Category Name

none

### Subcategory Name

adding more free elements on databse.json

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
I'm closing this issue cz' it doesn't make any sense. Make sure you our Contributing guidelines before starting to contribute.
