### ISSUE TITLE
[Add] new youtube channel link for web3 technologies

### ISSUE THREAD

**Issue by AmanPathan** [rupali-codes/LinksHub#2054]
### Site URL

https://www.youtube.com/@web3mantra

### Description of the above provided site

This YouTube channel has 114 educational videos based on web3 technologies like blockchain, solidity, hardhat, smart contracts, etc. It is the best resource for web3.

### Category

Youtube

### Sub Category

web3

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@AmanPathan you are assigned!
