### ISSUE TITLE
[Add] New link to Open source tutorial

### ISSUE THREAD

**Issue by ankush-w17** [rupali-codes/LinksHub#2055]
### Site URL

https://youtu.be/yzeVMecydCE?si=LaiHo7-CWhxPbwjD

### Description of the above provided site

Learn why and how to contribute to open source software. You will learn about how to find projects to contribute to, how to make issues and PRs, how to make money from open source, and more.

### Category

Open Source

### Sub Category

Tutorials

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment]
@ankush-w17 you are assigned
