### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by RS-labhub** [rupali-codes/LinksHub#2064]
### Issue Description

The [CONTRIBUTING.md](https://github.com/rupali-codes/LinksHub/pull/2063#top) file has some grammatical issues. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @RS-labhub! :) I'll open your PR now
