### ISSUE TITLE
[BUG] Sidebar not scrolling upto bottom in mobile devices 

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2069]
### Description

I'm not able see `other` category because it's not scrolling upto bottom in my phone 

### Screenshots

![IMG_20231022_172159](https://github.com/rupali-codes/LinksHub/assets/78981177/01e73c32-3231-4d72-a4ad-06fb1aea7607)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by KriteshTimsina** [comment]
/attempt #2069
I will try fixing this.

**Comment by Killer2OP** [comment]
@Anmol-Baranwal Can You assign me this issue.

**Comment by Anmol-Baranwal** [comment]
@Killer2OP 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Anmol-Baranwal** [comment]
@KriteshTimsina 
Why did you raise a PR without being assigned? Did you read contributing guidelines.

**Comment by KriteshTimsina** [comment]
I'm sorry I didn't notice. You can reject if it goes against the guidelines

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal Hey , Can I start the working on this issue now?

Sure. I never stopped you from working on this. If you're assigned, you can work.😄

**Comment by Killer2OP** [comment]
> > @Anmol-Baranwal Hey , Can I start the working on this issue now?
> 
> Sure. I never stopped you from working on this. If you're assigned, you can work.😄

I thought there is no ready tag , that's why😅

**Comment by Anmol-Baranwal** [comment]
> I thought there is no ready tag , that's why😅

That is just a formality, the main thing is getting assigned. Forgot to add the label. LOL!🤣
