### ISSUE TITLE
Add new database category

### ISSUE THREAD

**Issue by SoulNikhar** [rupali-codes/LinksHub#2076]
### Category Name

PouchDB, RethinkDB Database

### Subcategory Name

NoSQL Database

### Additional Context

RethinkDB is an open-source, distributed NoSQL database designed for real-time web applications. It's suitable for applications that require real-time data updates and dynamic queries.

 PouchDB is an open-source JavaScript database that's designed for building offline-first web and mobile applications. It allows developers to create applications that can work both online and offline while syncing data seamlessly.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@SoulNikhar 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by SoulNikhar** [comment]
@Anmol-Baranwal  PR #2120  done
