### ISSUE TITLE
[Feature] <write a small description here>

### ISSUE THREAD

**Issue by Alisha-786** [rupali-codes/LinksHub#2077]
### Description

I think there we can add a new file in JSON for PHP language. It can be very help full.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Alisha-786 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

It should be in languages category, and also update the title of this issue.
