### ISSUE TITLE
[Add] JavaScript Tutorials for Beginners in Hindi

### ISSUE THREAD

**Issue by ankush-w17** [rupali-codes/LinksHub#2078]
### Site URL

https://youtube.com/playlist?list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR&si=3AIK7JXdN_PGw9dV

### Description of the above provided site

JavaScript Course in Hindi: This Javascript tutorial in Hindi course is designed for beginners with an aim to take JavaScript/ES6 and its concepts to an advanced level.

### Category

Languages

### Sub Category

JavaScript

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@ankush-w17
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. https://github.com/rupali-codes/LinksHub/issues/2040

**Comment by Anmol-Baranwal** [comment]
@ankush-w17 
Done!
