### ISSUE TITLE
[Add] Strivers 79 Last Moment DSA Sheet

### ISSUE THREAD

**Issue by ankush-w17** [rupali-codes/LinksHub#2079]
### Site URL

https://takeuforward.org/interview-sheets/strivers-79-last-moment-dsa-sheet-ace-interviews/

### Description of the above provided site

The Striver’s 79 Sheet contains very handily crafted and picked top coding interview questions from different topics of Data Structures & Algorithms.

### Category

Resources

### Sub Category

Dsa

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@ankush-w17 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones.

**Comment by ankush-w17** [comment]
@Anmol-Baranwal, I have completed #2040 , and I have been assigned #2078 by @CBID2 but it's conversation is not open, can you look into that.

**Comment by CBID2** [comment]
> @Anmol-Baranwal, I have completed #2040 , and I have been assigned #2078 by @CBID2 but it's conversation is not open, can you look into that.
> 
> 

Hi @ankush-w17. The conversation in #2078 is unlocked

**Comment by ankush-w17** [comment]
Hi @CBID2 , sorry but it's showing as unlocked for me
![issue 2078](https://github.com/rupali-codes/LinksHub/assets/142745393/6b0c0500-9a9c-489e-8a84-3e235e5f955c)

**Comment by ankush-w17** [comment]
@Anmol-Baranwal can you assign this issue to me? I have completed all the other issues assigned to me.

**Comment by Anmol-Baranwal** [comment]
@ankush-w17 
Done!
