### ISSUE TITLE
Font-family

### ISSUE THREAD

**Issue by Eugene44-hub** [rupali-codes/LinksHub#208]
### Description

Linkshub does not have a specific font family, linkshub needs a font family to make it look nice on all devices.

**Comment by Jittojoyes98** [comment]
anyone working on this

**Comment by rupali-codes** [comment]
> anyone working on this

No, would you like to take this?

**Comment by Jittojoyes98** [comment]
Yeah, but what font family?

**Comment by rupali-codes** [comment]
> Yeah, but what font family?

You can suggest us font you like

**Comment by Jittojoyes98** [comment]
https://fonts.google.com/specimen/Source+Code+Pro

**Comment by Eugene44-hub** [comment]
https://fonts.google.com/specimen/JetBrains+Mono?query=jet

Use this font.

**Comment by Jittojoyes98** [comment]
Fine
