### ISSUE TITLE
[Add] Python for Data Science and Machine Learning Bootcamp (Udemy)

### ISSUE THREAD

**Issue by AnshMeshram** [rupali-codes/LinksHub#2081]
### Site URL

https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/

### Description of the above provided site

Python for Data Science and Machine Learning Bootcamp:

In this course, you will learn complete data science and machine learning using Python language.
This comprehensive course will be your guide to learning how to use the power of Python to analyze data, create beautiful visualizations, and use powerful machine-learning algorithms!

### Category

Languages

### Sub Category

Python for data Science

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@AnshMeshram 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
