### ISSUE TITLE
[Add] <Kubernetes Youtube tutorial>

### ISSUE THREAD

**Issue by rover07** [rupali-codes/LinksHub#2086]
### Site URL

https://youtu.be/X48VuDVv0do?si=VUaShrqe0PuMrfl4

### Description of the above provided site

This link contains a comprehensive and beginner-friendly resource for Kubernetes by a well-known tutor Nana.

### Category

DevOps

### Sub Category

Kubernetes

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @rover07! :) Now, I will reopen the PR you created for this issue
