### ISSUE TITLE
[ADD] <Web Development Project>

### ISSUE THREAD

**Issue by rover07** [rupali-codes/LinksHub#2088]
### Category Name

Resources

### Subcategory Name

Projest-Ideas

### Additional Context

The link I provided contains guided Web-Development projects which are free.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@rover07 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 
#2086 assigned to you.

**Comment by the-shivam-gupta** [comment]
assign it to me @Anmol-Baranwal 
I would like to include this under the web development category: [GreatLearning](https://www.mygreatlearning.com/blog/web-development-project-ideas/)

**Comment by Anmol-Baranwal** [comment]
@the-shivam-gupta 
Do you wanna add this?

Let me know, otherwise I will close this.

**Comment by the-shivam-gupta** [comment]
Ya assign it to me

**Comment by Anmol-Baranwal** [comment]
> Ya assign it to me

Done!
