### ISSUE TITLE
Want to a Youtube channelin Web Devolepment  field

### ISSUE THREAD

**Issue by Darkrider0007** [rupali-codes/LinksHub#2096]
### Site URL

https://www.youtube.com/@HiteshChoudharydotcom

### Description of the above provided site

It is an underrated channel for web development, android development, DevOps and a lot

### Category

Youtube

### Sub Category

Web Development 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Darkrider0007 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
