### ISSUE TITLE
[Add] i want to add a cpp youtube course 

### ISSUE THREAD

**Issue by ayush-singh08** [rupali-codes/LinksHub#2097]
### Site URL

https://www.youtube.com/playlist?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL

### Description of the above provided site

it is a cpp course for beginners in hindi by a youtube channel CodeWithHarry. This cpp course for beginners will teach all the cpp concepts from the very starting to the end.

### Category

Languages

### Sub Category

cpp.json

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
It's already there.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/bc7470cc-26ea-4466-9f93-db1f89d80373)

Closing this.
