### ISSUE TITLE
[BUG] Fix unDraw link

### ISSUE THREAD

**Issue by Aadarsh805** [rupali-codes/LinksHub#21]
The unDraw link in the `data.ts` file is wrong, it should be `https://undraw.co/illustrations`

![image](https://user-images.githubusercontent.com/95094057/212761024-902ee1de-f9b1-471c-a041-d2ca17a71256.png)

**Comment by rupali-codes** [comment]
Thanks for noticing. Would you like to correct this?

**Comment by haldaranup** [comment]
@rupali-codes please assign it to me if possible
