### ISSUE TITLE
[CHORE] add twitter link in README and website

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#210]
### What would you like to share or ask?

I have created a twitter account for LinksHub so people can tag us and share their experience. 

Add this link [https://twitter.com/the_linkshub](https://twitter.com/the_linkshub) in the README.md file as well in the site with twitter icon (You can also give us a follow ;)

**Comment by yashnirmal** [comment]
Can I take this one?

**Comment by rupali-codes** [comment]
> Can I take this one?

Yes,

**Comment by raghav1030** [comment]
has the issue been resolved or is it still open? if yes, then I am interested in contributing to it...

**Comment by rupali-codes** [comment]
> has the issue been resolved or is it still open? if yes, then I am interested in contributing to it...

Yes, this was assigned to @yashnirmal. Could you please look for some other issues, i'd love to see contributing :)
