### ISSUE TITLE
[Add] <Blockchain roadmap>

### ISSUE THREAD

**Issue by rover07** [rupali-codes/LinksHub#2101]
### Site URL

https://roadmap.sh/blockchain

### Description of the above provided site

This roadmap is open-sourced and contains a comprehensive roadmap on how to proceed

### Category

Other

### Sub Category

roadmap

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@rover07 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 
#2086 assigned to you.

**Comment by Anmol-Baranwal** [comment]
@shraddha761 

Please add it here.
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/771adbb5-f5d3-42ff-9334-46bd3d3c505a)


I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
