### ISSUE TITLE
[Add] <Tech community for students>

### ISSUE THREAD

**Issue by rover07** [rupali-codes/LinksHub#2102]
### Site URL

https://devkul.in/

### Description of the above provided site

This site enables students to connect with each other and learn together.

### Category

Other

### Sub Category

Communities

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@rover07 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 
#2086 assigned to you.

**Comment by Anmol-Baranwal** [comment]
@Ranjana761 
It already exists. If you want to add a new community resource, then let me know. I will assign you the issue.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/dddba4af-0c68-43dc-9bd7-002f8135e3c8)
