### ISSUE TITLE
[Add] <HackSquad>

### ISSUE THREAD

**Issue by rover07** [rupali-codes/LinksHub#2103]
### Site URL

https://www.hacksquad.dev/
### Description of the above provided site
Conceding with Hacktoberfest, Hacksquad is a month-long event where you submit contributions to open source projects, interact with other contributions, and win prizes.

### Category

Open Source

### Sub Category

Open Source Programs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@rover07 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 
#2086 assigned to you.

**Comment by Ruhi14** [comment]
> @Ruhi14 It already exists, if you want to add a new program then let me know. I will assign you.
> 
> ![image](https://user-images.githubusercontent.com/74038190/278092840-2125bb2a-2484-4756-80ea-7b95d058ae3a.png)

Ya sure i can add about Hacksquad OpenSource Program.

**Comment by CBID2** [comment]
> > @Ruhi14 It already exists, if you want to add a new program then let me know. I will assign you.
> > ![image](https://user-images.githubusercontent.com/74038190/278092840-2125bb2a-2484-4756-80ea-7b95d058ae3a.png)
> 
> Ya sure i can add about Hacksquad OpenSource Program. @Anmol-Baranwal

Hey @Ruhi14, I updated your issue a bit so your PR corresponds to the new idea.  Please keep the following in mind as you work on it:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9) 
If you need help with anything, tag me, @Anmol-Baranwal, or @rupali-codes

**Comment by JatinPhogat** [comment]
Hi , can i work on this issue , 3 days have also have passed from last asignee. @CBID2 I have done this work before also

**Comment by CBID2** [comment]
> Hi , can i work on this issue , 3 days have also have passed from last asignee. @CBID2 I have done this work before also 

Go ahead @JatinPhogat

**Comment by JatinPhogat** [comment]
Thanks

**Comment by JatinPhogat** [comment]
Hi , @CBID2 i have opened a PR please review it .
