### ISSUE TITLE
[FIX] <Grammatical-errors-fix-CONTRIBUTING.md>

### ISSUE THREAD

**Issue by rover07** [rupali-codes/LinksHub#2104]
### Issue Description

CONTRIBUTING.md has some grammatical errors that can be fixed making the website look more professional.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Can you mention the errors that you see @rover07?

**Comment by rover07** [comment]
![Screenshot from 2023-10-25 01-31-43](https://github.com/rupali-codes/LinksHub/assets/95951482/f3731e14-cc18-4463-9e4a-370be8bcae1b)

**Comment by ivikashgorai** [comment]
Please Assign me this issue.

**Comment by CBID2** [comment]
> Please Assign me this issue.

@rover07, we can't assign you the issue unless you provide more context. It'll help us gain a better understanding of your proposed contribution. 
@Anmol-Baranwal

**Comment by rover07** [comment]
So sorry about the issue, I mistakenly made some bogus changes which I thought were relevant. Eg. Changed 'Commitlint' to 'Commit'. This won't happen again.

**Comment by CBID2** [comment]
All is forgiven @rover07

**Comment by Anmol-Baranwal** [comment]
Closing this!
