### ISSUE TITLE
[Self Paced Courses],  New Sub category in Resources

### ISSUE THREAD

**Issue by Amanmawar17** [rupali-codes/LinksHub#2107]
### Category Name

Practice Website

### Subcategory Name

Freecodecamp

### Additional Context

There are lots of useful websites that let you code with in-browser IDEs such as FreecodeCamp and many more!! which can help beginners with industrial practices.

And can you suggest any good category name for this?
Thank You

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
It's already there.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/593e2357-8d8c-4ea2-a930-efd36a42e70e)

**Comment by Anmol-Baranwal** [comment]
Do you want to add a new resource here.

I may be getting the wrong idea, so do correct me.

**Comment by Amanmawar17** [comment]
Ohh! What I meant is that FreeCodeCamp has project-based learning, and Codedamn, Exercism is also similar to it.

**Comment by Anmol-Baranwal** [comment]
@Amanmawar17 
As you can see these already exists for various subcategories.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/90efeb27-ee23-4cce-b1a6-d82465b7b6b6)

What do you suggest, making a new subcategory?

It might be a good idea, let me know the subcategory name and which type of platforms will be there.

**Comment by Amanmawar17** [comment]
Can I add a certification sub-category as project-based learning in resources, and I also saw that certification in placement prep is empty.
We can also moves online code editor from frontend to resources.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 
What do you think? I'm kinda confused. But the options like codecademy, exercism, freecodecamp can be in 1 category due to learning by solving step wise questions from instructions.

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 
> 
> What do you think? I'm kinda confused. But the options like codecademy, exercism, freecodecamp can be in 1 category due to learning by solving step wise questions from instructions.

Self-paced courses maybe @Anmol-Baranwal?

**Comment by Amanmawar17** [comment]
So, should I add self-paced courses as a sub-category in resources?

**Comment by Anmol-Baranwal** [comment]
> Self-paced courses maybe @Anmol-Baranwal?

Yeah, great suggestion.

**Comment by Anmol-Baranwal** [comment]
> So, should I add self-paced courses as a sub-category in resources?

@Amanmawar17 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Anmol-Baranwal** [comment]
@Amanmawar17 
Please update the description of this issue to reflect what you need to add. It will be in resources as you suggested.

**Comment by Amanmawar17** [comment]
![Screenshot 2023-10-27 125930](https://github.com/rupali-codes/LinksHub/assets/88235531/e6a794fd-7cf3-4baa-8330-f3c1d12c39ac)

Is it look good? @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
> Is it look good? @Anmol-Baranwal

Looks great. Please raise a PR 😄
