### ISSUE TITLE
[Add] New YugabyteDB Database

### ISSUE THREAD

**Issue by psykatsamanta** [rupali-codes/LinksHub#2109]
### Site URL

https://www.yugabyte.com/

### Description of the above provided site

YugabyteDB is the 100% open source cloud native database for mission critical applications. YugabyteDB runs in any public or hybrid cloud.

### Category

Backend

### Sub Category

database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@psykatsamanta 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
