### ISSUE TITLE
[Add] <Novu>

### ISSUE THREAD

**Issue by lcrojano** [rupali-codes/LinksHub#2110]
### Site URL

https://novu.co/

### Description of the above provided site

Novu is a backend notification infrastructure, open-source notification infrastructure that allows developers to send notifications to their users through multiple channels, including in-app, push email, SMS, and chat. Novu is open-source and free to use. You can use it to send unlimited notifications to your users, for free.

### Category

Backend

### Sub Category

Email Providers

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Hey @lcrojano! :) You've been assigned to this issue. If you need more help, ping me, @Anmol-Baranwal, or @rupali-codes.
