### ISSUE TITLE
[DOCS] <formatting issues>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#2111]
### Issue Description

I was scrolling through the [Examples of Valid Commit Messages subsection of the Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#%EF%B8%8F-examples-of-valid-commit-messages)and noticed that some of the examples are missing backticks(see screenshot for reference). This causes contributors, especially those who are new to open source, to be confused.  

### Screenshots or Examples (if applicable)

![docs issue](https://github.com/rupali-codes/LinksHub/assets/105683440/2440771d-2fc4-4718-809f-e80e5062f699)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Vamsieth** [comment]
Can I work on this? @Anmol-Baranwal @CBID2

**Comment by Anmol-Baranwal** [comment]
> Can I work on this? @Anmol-Baranwal @CBID2

I would have assigned you, but 0scvr has already created a PR for this. I've asked him to comment to get assigned.

If he doesn't reply within next six hours, then I will assign you.

**Comment by Vamsieth** [comment]
alright

**Comment by 0scvr** [comment]
Please assign me 😀

**Comment by CBID2** [comment]
> Please assign me 😀

You're assigned @0scvr

**Comment by shivam200446** [comment]
I want to work on it assign me!

**Comment by CBID2** [comment]
> I want to work on it assign me!

Sorry @shivam200446. It's already assigned
