### ISSUE TITLE
[Add] new fonts resource

### ISSUE THREAD

**Issue by Vamsieth** [rupali-codes/LinksHub#2113]
### Site URL

https://www.fontspace.com/

### Description of the above provided site

FontSpace is a font directory with more than 100,000 available fonts. It takes a visual approach to displaying fonts. Along with the usual editable font preview, you'll also find an image from the designer that showcases the font.

### Category

Frontend

### Sub Category

fonts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Vamsieth 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
