### ISSUE TITLE
[Add] <Python Roadmap>

### ISSUE THREAD

**Issue by Ranjana761** [rupali-codes/LinksHub#2118]
### Site URL

https://copyassignment.com/complete-python-roadmap-for-beginners-in-2024/

### Description of the above provided site

we will see what should be the complete Python Roadmap for beginners in 2024. In this Python Roadmap for beginners, we will see what a Python Beginner should learn and how many days he should learn. Also, you can not get a job by just learning Python, you need to learn more like web development using Python or something else. There are many fields in the IT industry, after learning Python you should learn advanced Python skills for the IT industry in specific fields like web development or machine learning.

### Category

Other

### Sub Category

Roadmaps

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You've been assigned @Ranjana761! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
