### ISSUE TITLE
[Add] NextUI in frontend ui-libraries

### ISSUE THREAD

**Issue by tanpreetjolly** [rupali-codes/LinksHub#2126]
### Site URL

https://nextui.org/

### Description of the above provided site

NextUI is a UI library for React that combines the power of TailwindCSS with React Aria to provide a complete components (logic and styles) for building accessible and customizable user interfaces. Since NextUI uses TailwindCSS as its style engine, you can use all TailwindCSS classes within your NextUI components, ensuring optimal compiled CSS size.

### Category

Frontend

### Sub Category

UI Libraries

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@tanpreetjolly 
Reference this issue in the PR description. `fixes: #issueNumber` without enclosed ticks.
