### ISSUE TITLE
[Feature] Missing of a run command in readme.md file 

### ISSUE THREAD

**Issue by hparashar27** [rupali-codes/LinksHub#213]
### Description

Hey , i found that after following the steps of fork and npm install , there is missing of the command **npm run dev** to run the project on localhost in the readme.md file 

should i fix this one ?

### Screenshots
![chrome_6JcTkQqkhu](https://user-images.githubusercontent.com/96375055/219600836-d3a26831-4b10-4efe-a871-8b47d2a4d32d.png)

**Comment by rupali-codes** [comment]
@hparashar27 Thanks for noticing. Yeah that would be awesome. You can add this right after `5. create your branch`

**Comment by hparashar27** [comment]
Sure

**Comment by rupali-codes** [comment]
@hparashar27 Hi, are you still working on it?

**Comment by hparashar27** [comment]
Oh sorry I forgot about this one , ok surely  i will complete it by today itself 👍
