### ISSUE TITLE
[BUG] commit message guidelines link done not work in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Xzm27** [rupali-codes/LinksHub#2130]
### Description

commit message guidelines link leads to nowhere in CONTRIBUTING.md in the [making pull request](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#making-pull-requests-) section

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
It's just `#commits-message-guidelines` to `#commits-message-guidelines-`

Are you eager to contribute? I mean, it's such a small issue. 

@CBID2 @rupali-codes 
What do you think? A PR for `-`

**Comment by CBID2** [comment]
> It's just `#commits-message-guidelines` to `#commits-message-guidelines-`
> 
> 
> 
> Are you eager to contribute? I mean, it's such a small issue. 
> 
> 
> 
> @CBID2 @rupali-codes 
> 
> What do you think? A PR for `-`

If this wasn't for Hacktoberfest, @Anmol-Baranwal I'd be on board.

**Comment by Anmol-Baranwal** [comment]
> > It's just `#commits-message-guidelines` to `#commits-message-guidelines-`
> > Are you eager to contribute? I mean, it's such a small issue.
> > @CBID2 @rupali-codes
> > What do you think? A PR for `-`
> 
> @Anmol-Baranwal, I asked the person who is doing [PR 2119](https://github.com/rupali-codes/LinksHub/pull/2119#pullrequestreview-1700721268) to address this problem so having a seperate PR for this is not needed.

Thanks :) 

Locking the conversation. @Xzm27 Please create other issues, or comment on issue with label: `up for grabs` to get assigned.
