### ISSUE TITLE
[Add] Shadcn/ui to frontend ui-generators

### ISSUE THREAD

**Issue by Hrithik0112** [rupali-codes/LinksHub#2131]
### Site URL

https://ui.shadcn.com/

### Description of the above provided site

It provides you beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source. Built using Radix UI and Tailwind CSS.

### Category

Frontend

### Sub Category

Ui Generators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Hrithik0112 
I don't think it is a library.

**Comment by Hrithik0112** [comment]
@Anmol-Baranwal it's reusable component library to be specific.

**Comment by Hrithik0112** [comment]
@Anmol-Baranwal but it's getting popular day by day, many experienced Dev's address this as a UI library.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal but it's getting popular day by day, many experienced Dev's address this as a UI library.

I've used it, and I'm aware. 

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/3778d2db-8e65-4163-9723-49113f466514)

Let me check where it fits.

**Comment by Anmol-Baranwal** [comment]
@Hrithik0112 
Since Mamba UI is added in UI Generators. 

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/bd48f1a6-39a1-41e7-8c97-91299407826f)

You can add this in UI Generators. Update the description and I'm assigning.

**Comment by Hrithik0112** [comment]
@Anmol-Baranwal thank you for guiding me.
