### ISSUE TITLE
[Add] MLH Link under open source programs

### ISSUE THREAD

**Issue by vg300** [rupali-codes/LinksHub#2134]
### Site URL

https://fellowship.mlh.io/

### Description of the above provided site

Major League Hacking is a popular mentorship program that allows you to contribute to widely-used open source projects.

### Category

Open Source

### Sub Category

open-source

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@vg300 
I've assigned. We will reopen the PR.

**Comment by vg300** [comment]
Thank you, @Anmol-Baranwal
