### ISSUE TITLE
[Add] <Tech Podcast>

### ISSUE THREAD

**Issue by HVbajoria** [rupali-codes/LinksHub#2136]
### Site URL

https://www.youtube.com/@AI.Overpowered

### Description of the above provided site

In this podcast, the hosts Varun Mayya & Tanmay Bhat talk about everything that we can think of about AI helping us understand the use cases of AI in different domains. 

### Category

Other

### Sub Category

podcast

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
The issue is assigned, we will reopen the PR.

**Comment by HVbajoria** [comment]
Thank you @Anmol-Baranwal
