### ISSUE TITLE
[Add] <add React js>

### ISSUE THREAD

**Issue by Srish-ty** [rupali-codes/LinksHub#2137]
### Site URL

https://react-tutorial.app/

### Description of the above provided site

# React Tutorial app
- It's a website which documents react-js and helps students learn in an interactive way
- It has many modules which help students learn step by step
- The most important feature is that It is interactive
- Where learners need to write and submit the code 

### Category

Frontend

### Sub Category

"reactjs"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You're assigned @Srish-ty. In the future, please wait until your issue is approved and assigned to you before submitting a PR.
