### ISSUE TITLE
[BUG] showing resources without sidebar subcategories getting displayed

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2139]
### Description

This might be caused due to capitalization of each word in the search query.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/01db560d-66da-4230-b3ec-77bfeb34bc23)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Luckydhingra** [comment]
Description
Would like to work in this plz Assign me @Anmol-Baranwal 


Any additional information?
i want to work on this issue

What browser are you seeing the problem on?
Chrome

Checklist
 

- [x] I have checked the existing issues
- [x]  I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x]   I am willing to work on this issue (optional)
- [x]  I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@Luckydhingra 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.

**Comment by Anmol-Baranwal** [comment]
@Luckydhingra 
As I said, this maybe happening due to each word in search query having the 1st letter as uppercase. You need to debug and find the appropriate file, and then fix this.

You don't have to add resources or category, you just need to display subcategories whenever we are searching in the searchbar.

**Comment by Luckydhingra** [comment]
@Anmol-Baranwal I have created a PR #2161  which you can review and merge, you can ask me if there are any doubts regarding my pull request

**Comment by Luckydhingra** [comment]
@Anmol-Baranwal how long does it take? coz hacktoberfest is about to end...
pls make it fast

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal how long does it take? coz hacktoberfest is about to end... pls make it fast

It takes about 1 week to merge a PR. I will see what I can do.

**Comment by Luckydhingra** [comment]
> > @Anmol-Baranwal how long does it take? coz hacktoberfest is about to end... pls make it fast
> 
> It takes about 1 week to merge a PR. I will see what I can do.

yea pls... i waana to count this contribution in my hacktober..
all Help Help will be Appericiabke @Anmol-Baranwal :)
