### ISSUE TITLE
[Add] Add Material Tailwind Library to frontend

### ISSUE THREAD

**Issue by aslezar** [rupali-codes/LinksHub#2144]
### Site URL

https://www.material-tailwind.com/

### Description of the above provided site

Material Tailwind is an open-source library that uses the power of Tailwind CSS and React to help you build unique web projects faster and easier. The stunning design inspired by Material Design is a bonus!

### Category

Frontend

### Sub Category

CSS Framework

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@aslezar 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

This is different from material UI right? Because this is already there on LinksHub.

**Comment by aslezar** [comment]
> @aslezar I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
> 
> This is different from material UI right? Because this is already there on LinksHub.

Yes, Material Tailwind combines Material Design with Tailwind CSS, its a different thing from Material UI.
