### ISSUE TITLE
[Add] <Official doc of Swift Programming Language>

### ISSUE THREAD

**Issue by dalvishruti14** [rupali-codes/LinksHub#2148]
### Site URL

https://www.swift.org/documentation/

### Description of the above provided site

The official documentation of Swift Programming Language provides comprehensive information, guides, and resources for developers using Swift for iOS, macOS, watchOS, and tvOS application development. It covers the language syntax, standard library, and various features of Swift.

### Category

Resources

### Sub Category

documents

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 

#2140 & #2147 already assigned to you.

**Comment by ketanbaitule** [comment]
I want to work on this issue, pls assign it to me

**Comment by Anmol-Baranwal** [comment]
@ketanbaitule 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
