### ISSUE TITLE
[BUG] [fix]: Update Date to Dynamically Display Current Year

### ISSUE THREAD

**Issue by purnasth** [rupali-codes/LinksHub#2151]
### Description

The current copyright section of the website reflects the year "2023". To avoid the need to manually update this section every year, I propose implementing a JavaScript solution. The goal is to have the year dynamically displayed, ensuring it automatically updates to the current year.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/107195487/f3b40438-6e10-407c-a3d2-a634e27e4e89)

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
Sounds interesting @purnasth. Can you elaborate on how this feature would enhance the project?

**Comment by purnasth** [comment]
The website no longer has to hardcode the year after resolving this issue with a straightforward dynamic updating approach, which will undoubtedly enhance this project.

**Comment by purnasth** [comment]
Should I begin working on this issue, @CBID2?

**Comment by Anmol-Baranwal** [comment]
@purnasth 
You should see it in the codebase to actually verify.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5101a650-d869-44e4-b5cd-f8f074f21d1d)

This might not be the best way to use inspect in next.js project.

Closing this as it already exists!
