### ISSUE TITLE
[Add] <Add new DSA tutorial>

### ISSUE THREAD

**Issue by prashansa9583** [rupali-codes/LinksHub#2152]
### Site URL

https://youtube.com/playlist?list=PL8p2I9GklV47TMMnPzqnkCtSOS3ebr4O7&si=3SM4gEIXEaY6ZD3w

### Description of the above provided site

DSA Tutorial playlist

### Category

Frontend

### Sub Category

DSA

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@prashansa9583 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
