### ISSUE TITLE
[BUG] <Div overlap>

### ISSUE THREAD

**Issue by prashansa9583** [rupali-codes/LinksHub#2153]
### Description

Div is overlapping 

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/84851183/1330e295-3e07-4035-a7b2-3afd9b92658c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@prashansa9583 
It is clearly mentioned in the contributing guidelines that you can only work on one issue at a time. I'm opening this one for others to grab. Feel free to work on other issues once you have completed the assigned ones. 

`#2152 already assigned to you`

**Comment by prashansa9583** [comment]
Please assign this issue to me as i've completed the previous issue. 
thank you.

**Comment by OverRevvv** [comment]
Hello everyone, can I get assigned for this issue?

**Comment by Anmol-Baranwal** [comment]
@OverRevvv 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance. 

> @prashansa9583 The PR should be merged, then it is termed as completed.

**Comment by OverRevvv** [comment]
> @OverRevvv I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
> 
> > @prashansa9583 The PR should be merged, then it is termed as completed.

Thank you.
