### ISSUE TITLE
[Add] flowbite react in UI Libraries under frontend category

### ISSUE THREAD

**Issue by Alvis07** [rupali-codes/LinksHub#2156]
### Site URL

https://www.flowbite-react.com/

### Description of the above provided site

Flowbite React is an open-source UI component library built on top of Tailwind CSS with React components and based on the Flowbite Design System.

### Category

Frontend

### Sub Category

UI Library

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by CBID2** [comment]
You're assigned @Alvis07
