### ISSUE TITLE
[Add] TailwindUI in UI Libraries

### ISSUE THREAD

**Issue by mrical** [rupali-codes/LinksHub#2163]
### Site URL

https://tailwindui.com/

### Description of the above provided site

This UI Library is by the makers of **TailwindCSS**
Beautifully designed, expertly crafted components and templates, built by the makers of Tailwind CSS.
Easy to use and components can be customized with the help of utility-based CSS classes of TailwindCSS

### Category

Frontend

### Sub Category

ui-libraries

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
@mrical 
This is a paid resource.

**Comment by mrical** [comment]
### Site URL

https://easings.net/

### Description of the above provided site

This site consists of Easing Functions with detailed implementation which are useful for web animation enthusiasts

### Category

Frontend

### Sub Category

animations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by mrical** [comment]
> @mrical This is a paid resource. I am really sorry for inconvenience

**Comment by Anmol-Baranwal** [comment]
@mrical 
Are you eager to contribute? Hacktoberfest is over.

**Comment by mrical** [comment]
Yes,i am looking forward to contribute in this repo

**Comment by Anmol-Baranwal** [comment]
@mrical 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me [@Anmol-Baranwal](https://github.com/Anmol-Baranwal) or [@CBID2](https://github.com/CBID2) if you require any assistance.
