### ISSUE TITLE
[Feature] Create Aftab's profile

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#2165]
### Description

To celebrate this moment, we need to add Aftab to the Maintainer section of LinksHub's website

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment]
Also in the codeowners file

**Comment by CBID2** [comment]
> Also in the codeowners file

That too @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@aftab
Please do this in the header PR. I'm closing this.
