### ISSUE TITLE
feat: add new design for welcome screen

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2173]
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/d7372fcd-2c5d-4ee3-aa8e-cc69440a4fe9)

> The design should be responsive. 

---

ℹ️ We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You have to implement dropdown menu (to hide and show the section)

- Welcome section
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/9fc99d45-cf99-4197-a791-74e22f05130f)

- Community section
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/8a53a6d1-7e9d-47bc-a82d-0e7b18715a64)

- Resources section
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/69b407e3-75c1-4b26-b8a1-552fcab9ec8d)

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---
### ⚠️ Make sure to push all the changes into `dev` branch

**Comment by JoshiUtsav** [comment]
Hi, @Anmol-Baranwal could you please assign this issue to me?

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Will you work on this?

Please assign him, if you're not planning to do it.

**Comment by rupali-codes** [comment]
@JoshiUtsav any updates?

**Comment by JoshiUtsav** [comment]
Hello @rupali-codes, I've got an exam tomorrow, but right after that, I'll make the quick changes and send in the PR.

**Comment by rupali-codes** [comment]
> Hello @rupali-codes, I've got an exam tomorrow, but right after that, I'll make the quick changes and send in the PR.

okay, thanks
