### ISSUE TITLE
feat: add new design for saved resources

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2174]
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/80837d75-58e7-4e87-a2df-39ed5cce626b)

> The design should be responsive. 

---

ℹ️ We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You have to design the resources page as shown above.
- You also have to design the page in case no resources have been saved.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/685a6349-023e-4b90-b9fa-33f031194026)

- You need to implement the functionality of `remove all`

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/ad07fcf8-fe8c-45d9-909e-c241f3395ecb)

- You need to redesign the card component

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/f1d527e7-9514-4579-bac4-a79dadb57dff)

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---

**Comment by Vidip-Ghosh** [comment]
I would like to work on this.

**Comment by rupali-codes** [comment]
> I would like to work on this.

Sure, assigning to you!

**Comment by rupali-codes** [comment]
@Vidip-Ghosh any updates? Are you still willing to work on this?

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh any updates? Are you still willing to work on this?

@rupali-codes actually I have been assigned the firebase auth issue so even working on that + I was busy in my academics this week so I wasn't able to start this issue. But I am willing to work on this issue.

**Comment by Anmol-Baranwal** [comment]
But bookmark was not going to be there, right? Or will it be.

**Comment by Vidip-Ghosh** [comment]
> But bookmark was not going to be there, right? Or will it be.

Even confused of this. I think we should save the resources on the basis of resource upvoted. Will that be feasible?

**Comment by rupali-codes** [comment]
> > But bookmark was not going to be there, right? Or will it be.
> 
> Even confused of this. I think we should save the resources on the basis of resource upvoted and display in saved resources. Will that be feasible?

yep, sounds good though

**Comment by abed-obaah** [comment]
Has anyone worked on it? I would like to!

**Comment by Anmol-Baranwal** [comment]
> Has anyone worked on it? I would like to!

This is assigned to vidip. Please create new issue or comment with issues having label: `up for grabs`
