### ISSUE TITLE
feat: add new design for search results page (no results found)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2175]
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/329008b8-1f0c-42e5-9ffe-0b7725c12c4e)

> The design should be responsive. 

---

ℹ️ We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You need to implement the above design. 

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---

**Comment by SandeepGumaste** [comment]
Can I work on this and? @rupali-codes @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@SandeepGumaste 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag maintainers if you require any assistance. 

Also, remember to switch to dev mode. It will be easier for development.

> Top right corner in figma file
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/e24da7b2-5a39-4a00-884e-f141ce405314)

**Comment by SandeepGumaste** [comment]
Didn't find the search icon in react-icons and also couldn't download the icon from figma because export is enabled only for editors. Are the icons used in the new ui are from some icon pack that I can install? @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
> Didn't find the search icon in react-icons which is already used in the project and also couldn't download the icon from figma because export is enabled only for editors. Are the icons used in the new ui are from some icon pack that I can install? @Anmol-Baranwal @rupali-codes

Wait, giving you the icon. The icon pack used is react-icons.

**Comment by Anmol-Baranwal** [comment]
@SandeepGumaste 
You can now export the icons and use it. It's properly working.

**Comment by rupali-codes** [comment]
@SandeepGumaste any updates? Are you still willing to work on this?

**Comment by SandeepGumaste** [comment]
Will submit a pull request in some time today. @rupali-codes

**Comment by rupali-codes** [comment]
> Will submit a pull request in some time today. @rupali-codes

@SandeepGumaste ?

**Comment by heysolomon** [comment]
Hey @rupali-codes can I jump on this?

**Comment by CBID2** [comment]
> Hey @rupali-codes can I jump on this?

You're assigned @heysolomon! :)

**Comment by heysolomon** [comment]
> > Hey @rupali-codes can I jump on this?
> 
> You're assigned @heysolomon! :)

okay thank you!

**Comment by Anmol-Baranwal** [comment]
Completed with #2224.
