### ISSUE TITLE
feat: add new design for categories page

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2177]
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/6ed2dbe6-67ec-422f-970d-1e505cd0722e)

> The design should be responsive. 

---

ℹ️ We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You also need to implement breadcrumbs based on the current category we are currently on.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/081d4d65-f757-49d1-a82c-435efb802910)

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---

**Comment by CBID2** [comment]
Go ahead @gakshita

**Comment by Anmol-Baranwal** [comment]
@gakshita 
Please tag any of the maintainers, if you face any problem. We will help you properly.

**Comment by rupali-codes** [comment]
@gakshita any updates?

**Comment by gakshita** [comment]
Yes, I will submit the PR today.

**Comment by Anmol-Baranwal** [comment]
> Yes, I will submit the PR today.

Please remember to push the changes to dev branch.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/aeba6423-c1bf-4d90-b6f4-3fd4eeadba9b)

**Comment by gakshita** [comment]
I don't have the access to push to dev branch

**Comment by Anmol-Baranwal** [comment]
> I don't have the access to push to dev branch

@rupali-codes 
Do we need to access to push to dev?
