### ISSUE TITLE
feat: add new design for subcategories page

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2178]
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/9e3222bd-1160-47fb-a274-130d5301c44b)

> The design should be responsive. 

---

ℹ️ We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You also need to implement breadcrumbs based on the current category and subcategory we are currently on.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/c54f8666-d42d-400a-8f3b-1f2a66198460)

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---

**Comment by Raj100679** [comment]
@rupali-codes Can you assign this issue to me?

**Comment by Anmol-Baranwal** [comment]
@Raj100679 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance. 

Also, remember to switch to dev mode. It will be easier for development.

> Top right corner in figma file
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/e24da7b2-5a39-4a00-884e-f141ce405314)

**Comment by Raj100679** [comment]
Sorry , I totally forgot about it,You can unassign me , I am stuck in end semester exams.

**Comment by Mohsin-mw** [comment]
## Assistance Needed - "feat: add new design for subcategories page" Issue

Hi Ammol,

I saw the Figma designs for _"feat: add new design for subcategories page."_ Exciting stuff! I'm ready to implement these changes.
Thanks,
MWW

**Comment by Anmol-Baranwal** [comment]
@Mohsin-mw 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

**Comment by rupali-codes** [comment]
@Raj100679 are you still working on it?

**Comment by Raj100679** [comment]
@rupali-codes Mohsin is working on it , i am busy with some other work, If i get free I will pick different issue

**Comment by rupali-codes** [comment]
@Mohsin-mw are you working on this issue?

**Comment by Mohsin-mw** [comment]
> @Mohsin-mw are you working on this issue?

@rupali-codes  yup, i'll push the code tomorrow

**Comment by rupali-codes** [comment]
> > @Mohsin-mw are you working on this issue?
> 
> @rupali-codes yup, i'll make the pull request tomorrow

@Mohsin-mw you working on it?
