### ISSUE TITLE
[Feature] Add Vercel analytics

### ISSUE THREAD

**Issue by Aadarsh805** [rupali-codes/LinksHub#218]
### Description

Vercel analytics provides many services like these and much more: 

- web vitals
-  user experience score
- visitors count
- page views

**Comment by rupali-codes** [comment]
> ### Description
> Vercel analytics provides many services like these and much more:
> 
> * web vitals
> * user experience score
> * visitors count
> * page views
> 
> ### Screenshots
> _No response_
> 
> ### Additional Information
> _No response_

Looking forward to it

**Comment by rupali-codes** [comment]
Added!
