### ISSUE TITLE
[Add]: A Card in the Resume Building.

### ISSUE THREAD

**Issue by the-shivam-gupta** [rupali-codes/LinksHub#2191]
### Site URL

https://www.overleaf.com/latex/templates/tagged/cv

### Description of the above provided site

A resume or CV is like a fancy paper that tells others about your work and skills. The website provides tools and templates to make this process easier. So, if you're looking for a job or applying to school, Overleaf can help you make a professional-looking resume or CV.

Few sample templates:

![image](https://github.com/rupali-codes/LinksHub/assets/109647722/f4aad973-e7a9-47b3-acdf-c7ec2472c595)

### Category

Other

### Sub Category

Resume Building

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@the-shivam-gupta 
Go ahead. You're assigned!

**Comment by Anmol-Baranwal** [comment]
@the-shivam-gupta 
Please add it here!

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/6dda8f75-cc25-440a-ae67-6f345a961148)
