### ISSUE TITLE
feat: add new design of nav menu in mobile devices

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2196]
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/86fe1559-0101-4dd3-bb49-39c95b30e891)

> The design should be responsive.

---

ℹ️ We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You can get icons from [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?node-id=312%3A5847&mode=dev)
- You need to implement the active state and navigating to correct route based on selected nav icon.

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---
### ⚠️ Make sure to push all the changes into `dev` branch

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I'm creating this because the header design PR is merged, and since there's no sidebar option, I assume we're going with bottom navigation.

**Comment by MAXASSASSINS** [comment]
Hi @Anmol-Baranwal could you please assign this issue to me.

**Comment by Anmol-Baranwal** [comment]
@MAXASSASSINS 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.
