### ISSUE TITLE
[Add] <A Card in Text Formatting>

### ISSUE THREAD

**Issue by nelsonuprety1** [rupali-codes/LinksHub#2197]
### Site URL

https://text-tune.netlify.app/

### Description of the above provided site

Text tune is the ultimate solution for all the text 📖 formatting needs 🚀! The website provides text formatting features like UPPERCASE, lowercase, Title Case, Reverse Text, Remove WhiteSpace and another feature of this website is to provide with synonyms and antonyms for the word given by the user. If you are looking to format your text or get synonyms and antonyms for given words quickly, this website can be helpful 😀.  

Some images of the website:

<img width="1440" alt="Screenshot 2023-11-29 at 22 44 02" src="https://github.com/rupali-codes/LinksHub/assets/25173636/84fc7b71-d97f-4a40-8cc3-922ee7a70e3b">
<img width="1440" alt="Screenshot 2023-11-29 at 22 44 10" src="https://github.com/rupali-codes/LinksHub/assets/25173636/d3009f47-30c5-4e92-bccd-9df4d589e985">
<img width="1440" alt="Screenshot 2023-11-29 at 22 44 18" src="https://github.com/rupali-codes/LinksHub/assets/25173636/ece486d5-90c6-4ca3-8c7a-81eefae6de06">
<img width="1440" alt="Screenshot 2023-11-29 at 22 44 34" src="https://github.com/rupali-codes/LinksHub/assets/25173636/50113166-1b8b-4f72-9b8c-4a9b8f779409">

### Category

Other

### Sub Category

Text Formatting

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You're assigned @nelsonuprety1
