### ISSUE TITLE
[ADD] devops/IaC

### ISSUE THREAD

**Issue by EstebanBAR0N** [rupali-codes/LinksHub#2203]
### Category Name

devops

### Subcategory Name

'terraform'

### Additional Context

I'd like to add a [Terraform](https://github.com/hashicorp/terraform) to the devops category.
The purpose of this category is to add references to learn Terraform, an infrastructure-as-code tool that allows you to build, change and version infrastructure securely and efficiently.

This tool is currently one of the most popular in its field.

I'd like to add two links: the official [official documentation](https://developer.hashicorp.com/terraform/docs) and a popular [YouTube playlist](https://www.youtube.com/watch?v=vwn77cUarTs&list=PL8HowI-L-3_9bkocmR3JahQ4Y-Pbqs2Nt&index=1) for learning it.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@EstebanBAR0N 
Make a new subcategory: `Infrastructure as Code (IaC)` and add it in that. This would be appropriate, right?

I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

**Comment by EstebanBAR0N** [comment]
@Anmol-Baranwal 
I agree with you. I think IaC will be a better sub-category. I would include Terraform in it.
