### ISSUE TITLE
docs: Updates needed

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#2205]
### Issue Description

Here are two issues that I noticed in the docs:
### README
I noticed that the [Maintainers section does not mention Aftan](https://github.com/rupali-codes/LinksHub#maintainers-). This can cause new contributors to be confused.

### CONTRIBUTING Guide 
While the examples in the steps to adding categories/subcategories are descriptive, it could be improved.

### Readme

- Add Aftan to the Maintainer’s section 

### Contributing Guide

- Add code snippets that describe the examples. Something similar to the [Appending Links](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#follow-these-steps-to-add-your-links-to-the-hub) section.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
Oh! I never noticed 1st one.

What do you mean by this?
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/90530a30-26fd-4acb-87ba-ddac133e6ead)

**Comment by CBID2** [comment]
> Oh! I never noticed 1st one.
> 
> What do you mean by this? ![image](https://private-user-images.githubusercontent.com/74038190/290992064-90530a30-26fd-4acb-87ba-ddac133e6ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzAxNTAsIm5iZiI6MTcwMjcyOTg1MCwicGF0aCI6Ii83NDAzODE5MC8yOTA5OTIwNjQtOTA1MzBhMzAtMjZmZC00YWNiLTg3YmEtZGRhYzEzM2U2ZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDEyMzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOTRkN2I0ZjFhM2E3MDg1MjgwYzZiODk2MjE1OTQ1N2E3NjU2MjZlZTFiNmM0NDc4YTRiMmEzMWFkMzE4ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.USU1sWjEcdAOsIMby3YnRzxHINj_48AGL6IXCReu4YQ)
 
 You know how we have the full code snippet for adding links @Anmol-Baranwal?

  ```
name:'',
  description:'',
  url:'',
  category:'',
  subcategory:''
```
I was thinking of doing the same for the examples mentioned in the Adding to subcategory section. Does that make more sense?

**Comment by Anmol-Baranwal** [comment]
@CBID2 
But it's already there.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/e2264f63-52b9-4fbd-b365-bf16bfc47264)

Maybe we need to change it.

**Comment by CBID2** [comment]
> @CBID2 
> 
> But it's already there.
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/e2264f63-52b9-4fbd-b365-bf16bfc47264)
> 
> 
> 
> Maybe we need to change it.

Yes that's exactly what I mean @Anmol-Baranwal. Add the full snippet in context. Something like this:

``//open source`
blogs:
'description'
`

**Comment by Anmol-Baranwal** [comment]
Yep, got the idea :)
