### ISSUE TITLE
[Add] Digitomize

### ISSUE THREAD

**Issue by pranshugupta54** [rupali-codes/LinksHub#2206]
### Site URL

https://www.digitomize.com/

### Description of the above provided site

A platform for CP enthusiasts to explore coding contests (LeetCode, Codeforces, CodeChef, etc.) and showcase skills through dynamic portfolios, displaying updated ratings, achievements, and coding history.

### Category

Competitive Programming

### Sub Category

cp-helper

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
You’re assigned @pranshugupta54! :)

**Comment by CBID2** [comment]
Are you still working on this @pranshugupta54?

**Comment by pranshugupta54** [comment]
Apologies, I'm currently occupied with exams and forgot to inform you. Perhaps you could assign the task to someone else. If no one else volunteers, I'll be able to handle it in about 10 days after my exams.

**Comment by sarava338** [comment]
Hi @CBID2, If no one is available for this issue, May I get assigned ? 🙂🙃

**Comment by Anmol-Baranwal** [comment]
> Hi @CBID2, If no one is available for this issue, May I get assigned ? 🙂🙃
> 
> Hi @pranshugupta54, Please let us know about your availability

You're allowed to work on only 1 issue at a time. Do complete the existing one, then we can assign you this.

**Comment by Anmol-Baranwal** [comment]
@pranshugupta54 
I've unassigned you, since it has been a long time.
I guess anyone can add your project. I hope you understand.

**Comment by CBID2** [comment]
> > Hi @CBID2, If no one is available for this issue, May I get assigned ? 🙂🙃
> > Hi @pranshugupta54, Please let us know about your availability
> 
> You're allowed to work on only 1 issue at a time. Do complete the existing one, then we can assign you this.

@Anmol-Baranwal, I'm planning on assigning @pranshugupta54  to this [issue](https://github.com/rupali-codes/LinksHub/issues/2242) since they made an unassigned PR to it.

**Comment by sarava338** [comment]
Hi @CBID2 / @Anmol-Baranwal May I get assigned for this? 🙂🙃

**Comment by CBID2** [comment]
> Hi @CBID2 / @Anmol-Baranwal May I get assigned for this? 🙂🙃

Sure @sarava338! :)
