### ISSUE TITLE
[Add] <Docusaurus>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#2212]
### Site URL

https://docusaurus.io/

### Description of the above provided site

If you need a static generator to help you build your product’s documentation site, Docusaurus is your tool! :) Not only does it provide you with fast-side client navigation that takes interactivity to new heights, but also out-of-the-box documentation features that can help make your site stand out from the others.

### Category

Technical Writing

### Sub Category

“Tools”

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
Yep :)

I've used it, and it's even recommended by experienced devs.
