### ISSUE TITLE
Add Mantine to Frontend UI Libraries

### ISSUE THREAD

**Issue by Avas77** [rupali-codes/LinksHub#2221]
### Site URL

https://mantine.dev/

### Description of the above provided site

Add the popular Mantine React component Library to Frontend UI Libraries. People will find this UI LIbrary resource to be more helpful and resourceful because it has many UI components built in 

### Category

Frontend

### Sub Category

UI Libraries

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@Avas77 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me any of the maintainers if you require any assistance.

**Comment by Avas77** [comment]
Sure, thanks
