### ISSUE TITLE
Feature: add GitHub Action for Repo-Rater

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#2225]
### Description

Krish recently created this GitHub Action in connection with Eddie Jaoude’s new project, Repo-Rater: https://github.com/marketplace/actions/repo-rater-action
This can help LinksHub gain more contributors.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Are you working on this :)

**Comment by CBID2** [comment]
> @CBID2 
> 
> Are you working on this :)

Yeah @Anmol-Baranwal. Just waited for the new Welcome design to be merged

**Comment by CBID2** [comment]
> > > @CBID2
> > > Are you working on this :)
> > 
> > 
> > Yeah @Anmol-Baranwal. Just waited for the new Welcome design to be merged
> 
> Okay! Got it.

Yeah, and then my PR #2217 can be merged.
