### ISSUE TITLE
Modal UI Improvement: Add Space Between Title and Copy Button

### ISSUE THREAD

**Issue by lokeshvasnik** [rupali-codes/LinksHub#2230]
### Description

Issue:
The current modal layout displays the title and copy button without proper spacing, causing them to stick together.

### Screenshots

![Screenshot from 2024-01-05 17-06-58](https://github.com/rupali-codes/LinksHub/assets/91425128/8025da40-e4fe-4d05-a7f6-14f34160cec0)
![Untitled design](https://github.com/rupali-codes/LinksHub/assets/91425128/af60dc3f-8f46-422d-a3b4-4923c3e17460)

### Any additional information?

Contributor Guidelines:

Ensure that the changes do not affect the responsiveness of the modal.
Test the modifications across different screen sizes to guarantee a consistent user experience.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 @aftabrehan 
What do you think?

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 @aftabrehan 
> 
> What do you think?

I think the change would be ok @Anmol-Baranwal. How about you @aftabrehan and @rupali-codes?

**Comment by aftabrehan** [comment]
> > @rupali-codes @CBID2 @aftabrehan 
> > 
> > What do you think?
> 
> I think the change would be ok @Anmol-Baranwal. How about you @aftabrehan and @rupali-codes? 

Of course, there should be a gap between title and copy button.

**Comment by Anmol-Baranwal** [comment]
@lokeshvasnik 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

**Comment by lokeshvasnik** [comment]
Looks good 🚀
![Screenshot from 2024-01-07 19-21-19](https://github.com/rupali-codes/LinksHub/assets/91425128/83a6bc87-95c6-4811-9cbc-89a0d2e41a3c)
![Screenshot from 2024-01-07 19-23-16](https://github.com/rupali-codes/LinksHub/assets/91425128/b96515c4-4c89-4d68-b8da-6efc986c3b5a)
