### ISSUE TITLE
[OTHER] Fix minor issues in 'dev' branch

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2234]
## Sidebar
- [x] Sidebar responsiveness
- [x] Link [contributors](https://linkshub-git-dev-rupalihaldiya.vercel.app/contributors) page in `Our Team` section
- [x] Link `saved` page URL in `saved` page section
- [x] Change **Font** in sidebar subcategories
- [x] Remove this gap
  ![image](https://github.com/rupali-codes/LinksHub/assets/78981177/b3985bff-eb81-43a0-b40f-a303f000fe0b)

## Footer
- [x] Change text color and font as per the design
- [x] Update pagination button's color
- [x] Footer isn't fixed and scroll upon searching

> 
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/44256bff-de93-4eca-9c43-f8d5ee6405bc)

## Subcategory page
- [x] Category description Popup isn't aligning well 
- [x] Add `Pop-up` when clicked on the _Card_ or _Read More_ as in the previous design 
- [x] `Visit site` should be placed on the right side
- [x] `Read more` in the card isn't working correctly
- [x] Add popup when clicked on **Read More** button to show the full description for `category & resource card`
- [x] Missing descriptions 
>  
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/9af66905-f778-420d-86fd-8f514a905cc3)

## Other

- [x] copy link styling in popup
- [x] same styling issue of long title in popup
- [x] clicking frontend & subcategory (accessibiliy) goes to frontend menu.
- [x] `wanna add something` opens a range of issue templates (maybe we can go deeper for like category addition (less confusion))
- [x] same for `give a feedback`
- [x] query problem in breadcrumbs
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/17d41dc7-8f1c-460d-aa53-0662f747feeb)
- [x] styling issue for cards
- [x] redesign popup

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I've added all the bugs that I can found.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Should we start this?

**Comment by rupali-codes** [comment]
> @rupali-codes Should we start this?

Yeah
