### ISSUE TITLE
[Feature] Add Repo-rater badge

### ISSUE THREAD

**Issue by amanr-dev** [rupali-codes/LinksHub#2235]
### Description

Add Repo-rater badge to README.md

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@CBID2 
You know better about the repo rater. Please see this issue.

**Comment by rupali-codes** [comment]
Hey @amanr-dev what badge are you talking about

**Comment by amanr-dev** [comment]
> Hey @amanr-dev what badge are you talking about

Repo-rater badge from https://repo-rater.eddiehub.io/

**Comment by CBID2** [comment]
Why was this closed?
