### ISSUE TITLE
[BUG] Align pagination buttons to bottom

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2238]
### Description

The pagination isn't aligned well when the last page have a few resources (less than 6)

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/2c00d2ab-485a-4ac8-8a9f-2bbffaed64fe)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by mfrezghi** [comment]
Hi! I'm new to open source contribution but would love to give this issue a shot.

**Comment by Anmol-Baranwal** [comment]
> Hi! I'm new to open source contribution but would love to give this issue a shot.

@mfrezghi 
Sure, go ahead!

I've assigned you the issue.

Please fork and check if you can do the changes, then raise the PR.

If you need any help, please let us know :)

**Comment by mfrezghi** [comment]
Awesome! Sounds great, thanks.
