### ISSUE TITLE
[DOCS] Improve the Support Section

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#2242]
### Issue Description

While the Support Section does mention ways people can support the project, raising issues is already that people typically support OSS projects. It'd be more benefical to narrow down more actionable methods of support. 

### Proposed Solution (optional)

- [ ] Go to this line in the README file: https://github.com/rupali-codes/LinksHub/blob/229077d114cd699d0e09fbecbcfc353564cf857e/README.md?plain=1#L161
- [ ] Replace it with the following statement:
```Want to support LinksHub? Consider doing the following:
- 💰 Become our [Sponsor](https://github.com/sponsors/rupali-codes)!
- ⭐ Star our Repo 
- 🥇  Rate us on [Repo Rater](https://repo-rater.eddiehub.io/)
Together, we can continue to improve and expand this resource hub for people worldwide
```

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by sarava338** [comment]
@sarava338

**Comment by Anmol-Baranwal** [comment]
@sarava338 
Go ahead! I've assigned you.

In the future, you need to create an issue and allow us to assign you the issue before you start working and submit a PR.

This is outlined in the contributing guidelines.
![image](https://user-images.githubusercontent.com/74038190/271955538-4a4cf1b9-0dae-4fea-8b2e-1f57423c741f.png)

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this.

**Comment by sarava338** [comment]
> @sarava338 
> Go ahead! I've assigned you.
> 
> In the future, you need to create an issue and allow us to assign you the issue before you start working and submit a PR.
> 
> This is outlined in the contributing guidelines.
> ![image](https://user-images.githubusercontent.com/74038190/271955538-4a4cf1b9-0dae-4fea-8b2e-1f57423c741f.png)
> 
> You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this.

Yes sure, I read those rules. Thanks for letting me know 🙂
