### ISSUE TITLE
[BUG] search query value in breadcrumbs

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2246]
### Description

It will only happen when the search query matches the complete subcategory name, in this case, `colors`.

It will be as soon as someone enters the search query without clicking the subcategory name in the sidebar.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/87ee0b3a-ba79-47e6-b68b-6bc29afd3051)

### Any additional information?

It won't happen if the search query doesn't match the name.
For instance, `color` would show us no breadcrumbs, since there is no subcategory of `color`. 
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a7ca8b91-76e9-4589-90cd-2b06219f3e79)

The desired result would be.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/4e7ccb24-ed20-4d44-8f0d-241992d40567)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by sanjeevkumar321** [comment]
@Anmol-Baranwal hi can you assign this bug to me ?

**Comment by fpsphonebook** [comment]
hi
