### ISSUE TITLE
[Feature] improvements in light and dark theme

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2247]
### Description

@rupali-codes
I'm creating this issue, where we can further improve the light theme.

Feel free to update this issue, or the points.

---

1. A bit of a border and small shadow box.

| White (to improve) | Dark (inspiration) |
|:---------------------:|:--------------------:|
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/d747c140-056c-4f70-9180-57b497c1c78b) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/4f1725d5-9354-40f8-8505-9b3b22ba2f9c) |

2. Hover color changes on selected links. 

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/c8919cfe-566f-4ac3-bc36-5f96e69cd739)

3. A bit of a border and small shadow box.

| White (to improve) | Dark (inspiration) |
|:---------------------:|:--------------------:|
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/bd59599f-eaa3-4672-a486-b52e1e6573a4) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/f883d587-ad72-4cea-b2c7-25c42ac5b53c) |

4. Improve breadcrumbs.

| White (to improve) | Dark (inspiration) |
|:---------------------:|:--------------------:|
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/aca91c0d-8dab-41df-80d3-be8c877dfb96) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/2eca3c40-e46f-41da-99de-1f0bcc095b2d) |

5. A border on the searchbar

| White (to improve) | Dark (inspiration) |
|:---------------------:|:--------------------:|
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/8a162cfe-8e7e-479a-88a5-3f33466f6944) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/41449758-f3af-41d6-b034-f7b301b971ee) |

6. A border and shadow box.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/91f43857-c41b-4d38-965f-4792fe65eff2)

---

@aftabrehan @CBID2 
Feel free to suggest whatever you think!

### Screenshots

> Next time :)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
I think a black border would make it more bearable to view @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
> I think a black border would make it more bearable to view @Anmol-Baranwal

Yeah, I second that :)

**Comment by CBID2** [comment]
> > I think a black border would make it more bearable to view @Anmol-Baranwal
> 
> 
> 
> Yeah, I second that :)

What do you think @aftabrehan?

**Comment by aftabrehan** [comment]
Yeah, the border would improve visibility.

**Comment by CBID2** [comment]
Great! :) I'll give this a shot @Anmol-Baranwal! :)

**Comment by Anmol-Baranwal** [comment]
> Great! :) I'll give this a shot @Anmol-Baranwal! :)

Sure. Go ahead :)
