### ISSUE TITLE
[Feature] clean breadcrumbs by removing hyphens '-' in category name

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2248]
### Description

When we have category name of two words or more. It has `-` in the breadcrumbs which should be removed to improve UX.

### Screenshots

| example1 | example2 |
|--------|--------|
| ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/7d534815-6c15-4777-b8c9-99bdbfb8bfd1) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/22ccb5f3-cfc3-4bfe-bdb8-414bd7160db0) | 

| example3 | example4 | example 5 |
|--------|--------|-----|
 ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/55ab9d60-7b91-49e4-8055-f73d9b4fe157) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a78b4add-ce47-49bb-8d7b-800f4cc6ab52) | ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/d99a9df9-eabf-422e-87e2-2d5878206563) |

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
> I'll do this @Anmol-Baranwal

LOL! I was thinking of assigning contributors because there are no major issues. Maybe you can drop this. 🙌

In case no one picks it in 2 days, then it's all yours. What do you say?

**Comment by sanjeevkumar321** [comment]
Hello, @Anmol-Baranwal  can you please assign this issue ?

**Comment by rupali-codes** [comment]
This issue has been already resolved.
