### ISSUE TITLE
Javascript<DOM>

### ISSUE THREAD

**Issue by YOGINIMAHIMA1** [rupali-codes/LinksHub#2250]
### Category Name

DOM-Manipulation

### Subcategory Name

HTML DOM METHODS

### HTML DOM methods are actions you can perform (on HTML Elements).

HTML DOM properties are values (of HTML Elements) that you can set or change.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@YOGINIMAHIMA1 
I don't think this would be a good category.

So, a category is something which can include lots of similar subcategories.

e.g. The subcategories under frontend.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/451d4581-4076-43e2-a358-2eb50c30ff27)

@rupali-codes @aftabrehan @CBID2 
What do you think?

**Comment by YOGINIMAHIMA1** [comment]
ok thanks for informing.
