### ISSUE TITLE
Important Topics for Interview

### ISSUE THREAD

**Issue by YOGINIMAHIMA1** [rupali-codes/LinksHub#2251]
### Category Name

Data Structure

### Subcategory Name

Imp Topics

### Additional Context

Arrays
Linked List
Trees
HashMaps
sorting
graphs

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@YOGINIMAHIMA1 
You can work on only 1 issue at a time, you can decide which issue you want to contribute out of both two.

Again, these can be covered in any channel.
So, I don't think this is a valid subcategory.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/ee03f119-d250-43b2-ba87-24584fed359d)

Suppose, you include `IMP Topics` which is a personal preference so it will be very difficult to identify which resources should be under this.

Let's see what others think :)
