### ISSUE TITLE
[Refactor] Breadcrumbs Component

### ISSUE THREAD

**Issue by aftabrehan** [rupali-codes/LinksHub#2254]
### File Name

components/breadcrumbs

### Reason for Refactoring the Code

It seems we're using different components or icons for breadcrumb navigation. Also, the component name and path should be fixed. It should be `breadcrumbs` instead of `breadcrumps`.

<img width="625" alt="Screenshot 2024-02-02 at 12 32 24 PM" src="https://github.com/rupali-codes/LinksHub/assets/93012310/b6618059-545a-4be5-9284-620bc15c7fd4">

<img width="753" alt="Screenshot 2024-02-02 at 12 33 34 PM" src="https://github.com/rupali-codes/LinksHub/assets/93012310/655444f8-69ea-45d7-af4e-4c1fd7311ad9">

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [ ] I am willing to work on this issue (optional).

**Comment by sarava338** [comment]
Hey, Please assign this to me

**Comment by Anmol-Baranwal** [comment]
@sarava338 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag us if you require any assistance.

**Comment by Pritirekha23** [comment]
I want to contribute in this project, free to assign some work to me.

**Comment by Anmol-Baranwal** [comment]
> I want to contribute in this project, free to assign some work to me.

This issue is already assigned to Saravanan.
So, you would have to look for new issues.

You can join the discord server of LinksHub and I will let you know whenever we have open issues to work on.
