### ISSUE TITLE
 Add CSS Games subcategory under Frontend category

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2258]
### Category Name

Frontend

### Subcategory Name

CSS Games

### Learn CSS Grid, Flex and more by **Playing Games**

- [css grid garden](https://cssgridgarden.com/)
- [flex box froggy](https://flexboxfroggy.com/)
- [flukeout](https://flukeout.github.io/)
- [coding fantasy](https://codingfantasy.com/)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
Hi Juan!

You're only allowed to make one issue at a time.
So, we will keep this locked and assign you as soon the other PR is merged.

> Work on 1 issue at a time :)

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
Feel free to edit it. I will assign you then.
