### ISSUE TITLE
ADD - New Links to multiple Databases

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2259]
### What would you like to share or ask?

I already forked the project, add new links and worked on the issue. I have a variety of new links that I would like LinksHub to display.

##Here is the list of New Links:

### Icons

- [twemoji](https://twemoji.twitter.com/)
- [zondicons](http://www.zondicons.com/)
- [octicons](https://primer.style/octicons/)
- [radix](https://www.radix-ui.com/icons)

### Blogs

- [SitePoint](https://www.sitepoint.com/)
- [chat.zulip](https://chat.zulip.org/)
- [a list apart](https://alistapart.com/)
- [speckyboy](https://speckyboy.com/)

### Colors

- [colorwave](https://colorwave.dev/)

### Favicons

- [realfavicongenerator](https://realfavicongenerator.net/)

### GitHub

- [gitHub-profile-badges](https://home.aveek.io/GitHub-Profile-Badges/)

### Images

- [compress jpeg](https://compressjpeg.com/)
- [picresize](https://picresize.com/)
- [tinypng](https://tinypng.com/)
- [imagecompressor](https://www.imagecompressor.com/)

### Tools

- [compress jpg](https://compressjpg.net/)
- [free convert](https://www.freeconvert.com/)
- [Material Design](https://m3.material.io/)
- [Figma](https://www.figma.com/)
- [Sketch](https://www.sketch.com/)

### CSS Games

- [css grid garden](https://cssgridgarden.com/)
- [flex box froggy](https://flexboxfroggy.com/)
- [flukeout](https://flukeout.github.io/)
- [coding fantasy](https://codingfantasy.com/)

### UI Components

- [merakiui](https://merakiui.com/)
- [tailwind components](https://tailwindcomponents.com/)
- [tuk](https://tuk.dev/)
- [tailwind toolbox](https://www.tailwindtoolbox.com/)
- [tailwind ui](https://tailwindui.com/)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 @aftabrehan 
See if every resource is correctly in the respective category.
And let him know.
