### ISSUE TITLE
[CHORE] add prettier 

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#226]
### What would you like to share or ask?

As of now, we don't have prettier initialized and it's hard to tell people to format their code before they push it. Your task is to add `prettier` in this project so the code will be formatted.

**Comment by Abbeyafolaby** [comment]
Hi, I read this [blog](https://paulintrognon.fr/blog/typescript-prettier-eslint-next-js) and would love to try it, or you have an another article or blog?

**Comment by rupali-codes** [comment]
> Hi, I read this [blog](https://paulintrognon.fr/blog/typescript-prettier-eslint-next-js) and would love to try it, or you have an another article or blog?
You can go-ahead and try. Wishing u luck

**Comment by Abbeyafolaby** [comment]
Alright, thanks. Do you have any specific preferences you'd like to see in the `.prettierrc.json` file?

**Comment by rupali-codes** [comment]
> Alright, thanks. Do you have any specific preferences you'd like to see in the `.prettierrc.json` file?

No, not anything specifically

**Comment by Abbeyafolaby** [comment]
Alright, I would try it.

**Comment by rupali-codes** [comment]
> Alright, I would try it.

are you still working on this?

**Comment by Abbeyafolaby** [comment]
Ohhh, Yes I am. I should send a PR soon.
Sorry for the delay.
