### ISSUE TITLE
[Refactor] Extra space in between Breadcrumb and Content Components

### ISSUE THREAD

**Issue by sanjeevkumar321** [rupali-codes/LinksHub#2262]
### File Name

LinksHub\pages\[category]\[...subcategory].tsx

### Reason for Refactoring the Code

![Screenshot 2024-02-12 154245](https://github.com/rupali-codes/LinksHub/assets/46792207/b7181ecf-70a0-44f4-8550-80ac1d9646e4)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

**Comment by Anmol-Baranwal** [comment]
I checked and it's in full screen.

@sanjeevkumar321 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

**Comment by JuanPabloDiaz** [comment]
Great job @sanjeevkumar321 
I was going to add that this is something that was happening in multiple pages but your solution fit it everywhere since it;s in the layout
