### ISSUE TITLE
[BUG] category name in the breadcrumbs

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2263]
### Description

The category name having two words adds extra space in the name when clicking on the category name, thus, it redirects to an error page.

### Solution
Add a dash (-) in between the words, for example: for `competitive programming` it should be `competitive-programming`. Remember, you only have to do this in the link not the heading showing in breadcrumbs.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/636d5857-a738-4fc4-843b-cd3a4d76d0ee)

It's redirecting to `https://www.linkshub.dev/competitive programming`

### Any additional information?

Please let us know if you need any kinda help.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by heysolomon** [comment]
Has this been assigned to anyone? I would like to work on it

**Comment by Anmol-Baranwal** [comment]
@heysolomon 
I've assigned you. Go ahead!

**Comment by heysolomon** [comment]
Hi @rupali-codes, I couldn't find the bug in the `dev ` branch. For some reason, the bug was only visible in the `main ` branch.

**Comment by Anmol-Baranwal** [comment]
> Hi @rupali-codes, I couldn't find the bug in the `dev ` branch. For some reason, the bug was only visible in the `main ` branch. Could you help me check? And how do I go forward?

You have to fix it for `main` branch. You don't have to focus if it exists in `dev` branch or not.

**Comment by heysolomon** [comment]
> > Hi @rupali-codes, I couldn't find the bug in the `dev ` branch. For some reason, the bug was only visible in the `main ` branch. Could you help me check? And how do I go forward?
> 
> You have to fix it for `main` branch. You don't have to focus if it exists in `dev` branch or not.

Oh! That means I'm creating a PR to merge to `main`; I thought I would have to create a PR to the `dev` branch first. I will work on it then

**Comment by Anmol-Baranwal** [comment]
> > > Hi @rupali-codes, I couldn't find the bug in the `dev ` branch. For some reason, the bug was only visible in the `main ` branch. Could you help me check? And how do I go forward?
> > 
> > 
> > You have to fix it for `main` branch. You don't have to focus if it exists in `dev` branch or not.
> 
> Oh! That means I'm creating a PR to merge to `main`; I thought I would have to create a PR to the `dev` branch first. I will work on it then

Yeah. `dev` branch was for rebranding which is not needed anymore. This is caused due to a recent PR.

**Comment by heysolomon** [comment]
> > > > Hi @rupali-codes, I couldn't find the bug in the `dev ` branch. For some reason, the bug was only visible in the `main ` branch. Could you help me check? And how do I go forward?
> > > 
> > > 
> > > You have to fix it for `main` branch. You don't have to focus if it exists in `dev` branch or not.
> > 
> > 
> > Oh! That means I'm creating a PR to merge to `main`; I thought I would have to create a PR to the `dev` branch first. I will work on it then
> 
> Yeah. `dev` branch was for rebranding which is not needed anymore. This is caused due to a recent PR.

Okay
