### ISSUE TITLE
[BUG] Sidebar not scrolling properly

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2266]
### Description

I've just noticed that sidebar isn't scrolling upto the bottom, its sticky

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/fcd0802e-3104-4ef2-86d9-5530bd0f6980)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by heysolomon** [comment]
I would like to work on this

**Comment by rupali-codes** [comment]
> I would like to work on this

Sure, assigning to you
