### ISSUE TITLE
Add Float UI

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2268]
### Site URL

https://floatui.com/

### Description of the above provided site

Add [Float UI](https://floatui.com/) to frontend category, [Ui Libraries](https://www.linkshub.dev/frontend/ui-libraries) subcategory.

### Category

Frontend

### Sub Category

Ui Libraries

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
You're assigned. Please go ahead.

**Comment by JuanPabloDiaz** [comment]
I notice that the subcategory for **Material Tailwind** is incorrect. I will be fixing that as well

![image](https://github.com/rupali-codes/LinksHub/assets/25883220/0af83a8c-2b0a-4c7b-9213-79639c42dcf6)
