### ISSUE TITLE
Change threeJS subcategory name to 3d libraries and add resource links

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2270]
### Category Name

Frontend

### Subcategory Name

Three JS      =>     3D libraries

### New or updated description of above subcategory

Rename the _`Three JS`_ subcategory to _**`3D libraries`**_ 

I would like to add additional content to the _**`3D libraries`**_ , such as:

- [Babylon.js](https://www.babylonjs.com/)
- [Play Canvas](https://playcanvas.com/)
- [A-Frame](https://aframe.io/)
- [p5.js](https://p5js.org/)

### Status of Description

- [ ] Adding new description
- [ ] Updating existing description

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
Please create only 1 issue at a time. For now, do this and then we will assign you #2268 (just tag me in the discord later on).

Please add a clear title of the issue from next time. I've done it this time :D

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/f8217b4b-40de-4908-94e3-b8419e18fe6c)

**Comment by Anmol-Baranwal** [comment]
I've assigned you. Please go ahead!
