### ISSUE TITLE
[Add] Naukri 

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#2271]
### Site URL

https://www.naukri.com/

### Description of the above provided site

It's a platform that helps you get the job and place the job

### Category

Other

### Sub Category

Cat - Placement_prep , Subcat - jobportals

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@parma1111 
I've assigned you. Go ahead!

**Comment by parma1111** [comment]
> @parma1111 I've assigned you. Go ahead!

> @Anmol-Baranwal ok I will make the PR for it.

**Comment by parma1111** [comment]
why this error is coming @Anmol-Baranwal 
git push origin naukri1
remote: Permission to rupali-codes/LinksHub.git denied to parma1111.
fatal: unable to access 'https://github.com/rupali-codes/LinksHub.git/': The requested URL returned error: 403

**Comment by Anmol-Baranwal** [comment]
> why this error is coming @Anmol-Baranwal git push origin naukri1 remote: Permission to rupali-codes/LinksHub.git denied to parma1111. fatal: unable to access 'https://github.com/rupali-codes/LinksHub.git/': The requested URL returned error: 403

You're directly pushing it to linkshub repo. You should push it to your fork. The error is shown because you don't have enough permissions to push directly to this repo.

**Comment by parma1111** [comment]
how can I push it in my own fork repository. Can you explain me step by step @Anmol-Baranwal ?

**Comment by parma1111** [comment]
I clone the fork and make a branch and
git add filename
git commit -m "commits"
git push origin mybranchname 
then I am getting same error remote: Permission to rupali-codes/LinksHub.git denied to parma1111.
fatal: unable to access 'https://github.com/rupali-codes/LinksHub.git/': The requested URL returned error: 403
@Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
> I clone the fork and make a branch and git add filename git commit -m "commits" git push origin mybranchname then I am getting same error remote: Permission to rupali-codes/LinksHub.git denied to parma1111. fatal: unable to access 'https://github.com/rupali-codes/LinksHub.git/': The requested URL returned error: 403 @Anmol-Baranwal

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/ac7f5ac2-8030-4ae6-b01f-b7e45538dfb3)

You have to use this: https://github.com/parma1111/LinksHub.git

**Comment by parma1111** [comment]
I clone my own fork repo but I am getting this same error , then where to change myself.

**Comment by Anmol-Baranwal** [comment]
> I clone my own fork repo but I am getting this same error , then where to change myself @Anmol-Baranwal 
> 

Have you searched everywhere? 
Did you see stackoverflow. 
Maybe you haven't set up the git.

**Comment by parma1111** [comment]
earlier I used to contribute in this project that time it was ok. @Anmol-Baranwal
