### ISSUE TITLE
[Add] Build Your Own X under project-ideas

### ISSUE THREAD

**Issue by vamsi4845** [rupali-codes/LinksHub#2275]
### Site URL

https://build-your-own-x.vercel.app/#how-to-contribute

### Description of the above provided site

Master programming by recreating your favorite technologies from scratch

### Category

Resources

### Sub Category

Project Ideas

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
Hi @vamsi4845 
Are you adding a forked project?

Can you explain a bit more.

**Comment by vamsi4845** [comment]
yeah sure,
This is a curated collection of projects in almost all languages. It would be a great resource for the project-ideas 
![msedge_4jyWKLGQZy](https://github.com/rupali-codes/LinksHub/assets/39260099/0740fab6-fa9b-405c-95ca-85b20def30aa)
![msedge_FNNWUeJR0k](https://github.com/rupali-codes/LinksHub/assets/39260099/bfee0aaa-4efb-4875-a3c2-9cad5d38f4c2)

**Comment by vamsi4845** [comment]
I have added the related info in above comment,let me know if there is a issue
