### ISSUE TITLE
[BUG] Footer merging with the content cards

### ISSUE THREAD

**Issue by Sanchitbajaj02** [rupali-codes/LinksHub#2276]
### Description

When I was searching for the stuff on Linkshub, I found this issue. I think the footer is fixed on the search routes.

### Steps to replicate

Search for anything in the search box. If the card contents are more than the screen height, the scrollbar will appear and then the footer will be fixed appear behind the content cards.

## Sample 1
![image](https://github.com/rupali-codes/LinksHub/assets/55249639/b69261d2-1f34-40ad-abb4-6d1503600846)

## Sample 2
![image](https://github.com/rupali-codes/LinksHub/assets/55249639/c0d6441e-a30d-4756-aa90-15aff3a091df)

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@Sanchitbajaj02 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

**Comment by Sanchitbajaj02** [comment]
Hi @Anmol-Baranwal 

After debugging the codebase, I've found that a min-height and height is applied on the search page.

![issue](https://github.com/rupali-codes/LinksHub/assets/55249639/cdd873e7-e199-48d7-8444-901bcd00a221)

Do we need this? After removing them, I got something like this:
![after issue fix](https://github.com/rupali-codes/LinksHub/assets/55249639/d106a5c8-af1b-41fb-b7b0-e5bc8fdd7764)

do let me know whether we need the height property on a page or not

**Comment by Anmol-Baranwal** [comment]
@Sanchitbajaj02 
You can raise a PR and then I can test it properly.

Normally height ensures that the total height is used even if there are no cards.
