### ISSUE TITLE
[Add] Link checker

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2277]
### Site URL

https://www.drlinkcheck.com

### Description of the above provided site

[Dr. Link Check](https://www.drlinkcheck.com/) is a valuable web-based service designed to help website owners and administrators identify and address broken links on their websites.

it is a freemium service.

### Category

Other

### Sub Category

devtools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
You're assigned! Please go ahead.
