### ISSUE TITLE
[ADD] Subcategory: JavaScript Chart Libraries

### ISSUE THREAD

**Issue by Wambaforestin** [rupali-codes/LinksHub#2278]
### Category Name

JavaScript Chart Libraries.

### Subcategory Name

https://www.chartjs.org/, https://d3js.org/, https://www.highcharts.com/, https://plotly.com/javascript/, https://www.amcharts.com/, https://developers.google.com/chart/, https://nivo.rocks/, 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [x] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@Wambaforestin 
Are you willing to contribute this or can I assign this to someone else?

**Comment by Wambaforestin** [comment]
Yes, i'm willing

**Comment by Anmol-Baranwal** [comment]
> Yes, i'm willing

Please fill this option from next time. This is when you're going to contribute the issue.
I've done it this time.

I've also assigned you the issue, please proceed and don't forget to tag me if you need any help :)

**Comment by Wambaforestin** [comment]
Alright thanks

**Comment by JuanPabloDiaz** [comment]
I was just reading this awesome contribution and came accross [Recharts](https://recharts.org/en-US/) which is pretty similar to those libraries.
The only diference is that Recharts is a composable charting library built on React components. Redefined chart library built with React and D3.
I was wondering if this could be included as well or where should it be placed?

[Tremor](https://www.tremor.so/) is another great resource but is for React components to build charts and dashboards.

**Comment by Anmol-Baranwal** [comment]
> I was just reading this awesome contribution and came accross [Recharts](https://recharts.org/en-US/) which is pretty similar to those libraries. The only diference is that Recharts is a composable charting library built on React components. Redefined chart library built with React and D3. I was wondering if this could be included as well or where should it be placed?
> 
> [Tremor](https://www.tremor.so/) is another great resource but is for React components to build charts and dashboards.

Thanks for the recommendations Juan!
Tremor seems to be very useful :)

You can definitely open a new issue to add these or if @Wambaforestin wants to add these. Feel free to do so.

**Comment by JuanPabloDiaz** [comment]
Great!
I have multiple issues open already lol.
Let me know if you want to add both of them @Wambaforestin

**Comment by Wambaforestin** [comment]
@JuanPabloDiaz feel free to add them all 😊

**Comment by JuanPabloDiaz** [comment]
Did you add [nivo](https://nivo.rocks/) @Wambaforestin?
