### ISSUE TITLE
[Bug] Broken Links

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2284]
### Broken Links

I found 7 broken links by using a [broken link checker](https://www.brokenlinkcheck.com/broken-links.php#status)

![broken-links](https://github.com/JuanPabloDiaz/LinksHub/assets/25883220/08e7556e-2c36-4735-88ea-95124686c208)

1
https://www.cssportal.com/ui-generators.php
url src 404

2
https://uiverse.io/all
url src 404

3
https://owasp.org/www-project-appsec/
url src 404

4
https://www.sans.org/cyber-security-skills-roadmap/defensive-security
url src 404

5
https://cuckoosandbox.org/
url src timeout

6
https://www.fireeye.com/services/freeware/flare.html
url src 530

7
https://www.mile2.com/web-application-penetration-tester-cwapt.html
url src 404

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@JuanPabloDiaz do you like work on this?

**Comment by JuanPabloDiaz** [comment]
Absolutely, I can help.

Should I look for the correct link? And if there is any just delete it or what should I do @rupali-codes ?

**Comment by CBID2** [comment]
> @JuanPabloDiaz do you like work on this?

@JuanPabloDiaz has multiple issues open already according to the bot, so I think it's best for them to focus on one for now.

**Comment by JuanPabloDiaz** [comment]
> > @JuanPabloDiaz do you like work on this?
> 
> @JuanPabloDiaz has multiple issues open already according to the bot, so I think it's best for them to focus on one for now.

Hey @CBID2, thanks for your comment. I'm happy to work on this issue, but I don't mind if someone else wants to take it. I've been creating issues, but that does not mean that I want to hold them for myself. anyone can claim them.

Please feel free to grab any of them.

That's the spirit of open source. Collaboration!

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @JuanPabloDiaz  I would love to work on this issue.

**Comment by Anmol-Baranwal** [comment]
> Hey @JuanPabloDiaz I would love to work on this issue.

@JuanPabloDiaz 
Thanks for the collaborative spirit. That is the spirit that helps in the longer run.

@Muhammad-Owais-Warsi 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

**Comment by CBID2** [comment]
> > > @JuanPabloDiaz do you like work on this?
> 
> > 
> 
> > @JuanPabloDiaz has multiple issues open already according to the bot, so I think it's best for them to focus on one for now.
> 
> 
> 
> Hey @CBID2, thanks for your comment. I'm happy to work on this issue, but I don't mind if someone else wants to take it. I've been creating issues, but that does not mean that I want to hold them for myself. anyone can claim them.
> 
> 
> 
> Please feel free to grab any of them.
> 
> 
> 
> That's the spirit of open source. Collaboration!

Ahh I see. That's the spirit! 😊

**Comment by Muhammad-Owais-Warsi** [comment]
> > Hey @JuanPabloDiaz I would love to work on this issue.
> 
> @JuanPabloDiaz Thanks for the collaborative spirit. That is the spirit that helps in the longer run.
> 
> @Muhammad-Owais-Warsi I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

Sure 😄
