### ISSUE TITLE
[Add] Tremor & Recharts

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2289]
### Site URL

tremor.so & recharts.org

### Description of the above provided site

Opening this issue to complement the great work of issue #2278

- [Recharts](https://recharts.org) is a composable charting library built on React components. Redefined chart library built with React and D3.
- [Tremor](https://www.tremor.so/) is a React components to build charts and dashboards.

 I don't mind if someone else wants to take it and work on it. 

### Category

Frontend

### Sub Category

JavaScript Chart Libraries

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@JuanPabloDiaz You're assigned, you can start working on this :)

**Comment by JuanPabloDiaz** [comment]
I am wondering if this is a better classification for these resources since they will be no longer JS libraries only - it will be React but still JS...

    "category": "backend",
    "subcategory": "data-processing"
