### ISSUE TITLE
[Add] Freshersworld

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#2290]
### Site URL

https://www.freshersworld.com/

### Description of the above provided site

It is the best platform to get the job and preparation for job interview.

### Category

Frontend

### Sub Category

Cat - Placement_prep , Subcat - jobportals

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@parma1111 assigned to you
