### ISSUE TITLE
[BUG] Light and dark theme switching.

### ISSUE THREAD

**Issue by Sahil-106** [rupali-codes/LinksHub#2294]
### Description

The switching between light and dark themes works fine on the home page. However, as soon as we navigate through sub-categories and try to switch the theme, the body theme takes more time to load than its div, resulting in asynchronous visuals. 

https://github.com/rupali-codes/LinksHub/assets/139853292/5d1dfba9-e436-4ddb-ae62-ac89b7efc93f
the sub-categories.mp4 demonstrates the asynchronous switching.

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@Sahil-106 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you need any help.
