### ISSUE TITLE
[Add] Work-At-Startup in job portals

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2295]
### Site URL

https://www.workatastartup.com/

### Description of the above provided site

Work-At-Startup is a job portal to find Remote, On-site and Full-time remote jobs

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/95090816-dd6d-4af8-ba1e-936efc4a3aba)

### Category

Placement Prep

### Sub Category

Job-Portals

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by sarava338** [comment]
hey @rupali-codes, may I get assigned?

**Comment by rupali-codes** [comment]
> hey @rupali-codes, may I get assigned?

Sure, assigning to you! Please let us know if you need any help
