### ISSUE TITLE
[Add] Remotely in Job-portals

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2296]
### Site URL

https://www.remotely.jobs/

### Description of the above provided site

Remotely  is platform that helps you find full-time and part-time remote jobs. They have tech and as well as non-tech jobs

### Category

Placement Prep.

### Sub Category

Job-Portals

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by sarava338** [comment]
hey @rupali-codes, may I get assigned?

**Comment by Anmol-Baranwal** [comment]
@sarava338 
Done! Please proceed with it.

**Comment by sarava338** [comment]
Hey @rupali-codes and @Anmol-Baranwal, wellfound link was already there, I think we are good to close it.

![wellfound_already_there](https://github.com/rupali-codes/LinksHub/assets/93024887/1cd45297-a68e-4e33-a558-d68518d5ae82)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
It would be better to replace the content with something not mentioned -> maybe Untapped.

Then saravanan can complete it.

**Comment by rupali-codes** [comment]
> @rupali-codes It would be better to replace the content with something not mentioned -> maybe Untapped.
> 
> Then saravanan can complete it.

@sarava338 thanks for noticing.

@Anmol-Baranwal updated.
