### ISSUE TITLE
[Add] Himalays in Job Portals

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2297]
### Site URL

https://himalayas.app/

### Description of the above provided site

Himayalas is platform made for specifically to find Remote (work from home) jobs at too remote companies

### Category

Placement Prep.

### Sub Category

Job-Portals

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by misochenk0** [comment]
Hi i want to be a contributer here!
can you assign this issue to me?

**Comment by Anmol-Baranwal** [comment]
@misochenk0 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you need any help.
