### ISSUE TITLE
[Feature] Add issue and pr templates

### ISSUE THREAD

**Issue by Aadarsh805** [rupali-codes/LinksHub#23]
it'll make managing bugs and new feature requests a lot easier!

![image](https://user-images.githubusercontent.com/95094057/212761184-89e88b63-8682-4d32-901d-b0d7c1f234fb.png)

**Comment by rupali-codes** [comment]
Hi, @Aadarsh805 
would you like to work on this?

**Comment by Aadarsh805** [comment]
> Hi, @Aadarsh805 would you like to work on this?

Sure assign me
