### ISSUE TITLE
[Feature] Menu opening logics change

### ISSUE THREAD

**Issue by misochenk0** [rupali-codes/LinksHub#2301]
### Description

Currently when clicking on an expand arrow next to the category
![image](https://github.com/rupali-codes/LinksHub/assets/78084319/79ba9f72-8b1a-42b5-8af2-b2ee64ea4899)
 It opens not only list of subcategories but also redirects you to that page
 Maybe a better solution would be preventing that behaviour and not pushing user to a specific category after clicking on arrow nearby and only opening subcategories list?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@misochenk0 
The current behavior is such that people can learn more about the subcategories through the descriptions, which, in my experience, provides a better user experience.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/0dc67d0b-621f-4379-abf1-a62a76582440)

**Comment by misochenk0** [comment]
Yes, you can get that info if you click on the category itself.
But when I click directly on an arrow, maybe I don't want to change my current route?

That's just my opinion as a user; we can leave it as it is working now)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @aftabrehan @CBID2 
What do you think?

**Comment by rupali-codes** [comment]
> @rupali-codes @aftabrehan @CBID2 What do you think?

I think @misochenk0 is right, we should only change the route when user is clicking on the category name, and only show the dropdown/list when user clicks on the icon. For this, we can highlight the icon.

**Comment by JoshiUtsav** [comment]
@Anmol-Baranwal  Assign me this issue.

**Comment by Dev-Arhaan** [comment]
close this if it needs no change or is not an issue

**Comment by Anmol-Baranwal** [comment]
@misochenk0 
You have a couple of issues assigned, so I'm assigning this to @JoshiUtsav
