### ISSUE TITLE
[BUG] Pagination usage 

### ISSUE THREAD

**Issue by misochenk0** [rupali-codes/LinksHub#2302]
### Description

Changing pages using pagination inside categories doesn't scroll you back to the top of a list
you need manually scroll page to the very top
Maybe that behaviour could be a little bit annoying for mobile users

I can help you to fix this problem)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@misochenk0 
will you work on this issue? 
Another one is also assigned to you. If you have no problem, then I will assign this one as well. Just let me know.

**Comment by misochenk0** [comment]
Yes, sure. I can get this one as well

**Comment by Anmol-Baranwal** [comment]
@misochenk0 
I have assigned you the issue. Please proceed with it.
