### ISSUE TITLE
[Add] Weird Hover Animation in Sidebar and Team Section

### ISSUE THREAD

**Issue by saurabhdhull1** [rupali-codes/LinksHub#2303]
### What would you like to share or ask?

I noticed a strange hover animation behavior in the sidebar and the team section of the project. When hovering over certain elements, the animation appears to be glitchy. This affects the user experience negatively.
The hover animation should be smooth and visually appealing, enhancing the user experience without any unexpected behavior.
I can help you to fix this problem)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@saurabhdhull1 
Please attach a small video of the glitch to the issue so that we can understand it better.
