### ISSUE TITLE
[Feature] Sort category name in Alphabetical order

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2308]
### Description

Kindly sort the category names in sidebar in Alphabetical order

### Screenshots

![edited](https://github.com/rupali-codes/LinksHub/assets/78981177/a62da3fe-7686-4ca9-9213-15a6a070e55f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by sarava338** [comment]
Hey @rupali-codes / @Anmol-Baranwal, May I try ?

**Comment by rupali-codes** [comment]
> Hey @rupali-codes / @Anmol-Baranwal, May I try ?

Do you wanna work on #2307 or this one? We can assign you any of them

**Comment by Ranjana761** [comment]
> > Hey @rupali-codes / @Anmol-Baranwal, May I try ?
> 
> Do you wanna work on #2307 or this one? We can assign you any of them

Can you assign me this issue.
