### ISSUE TITLE
[BUG] Favicon is not showing

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2309]
### Description

The favicon is not showing on the main site, kindly use these icons:

[favicon_io.zip](https://github.com/rupali-codes/LinksHub/files/14633308/favicon_io.zip)

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/fe0f55d6-8ba6-4588-9d20-61f367b49316)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by bottlewook** [comment]
Can i work on this issue? kindly assign it to me!

**Comment by rupali-codes** [comment]
> Can i work on this issue? kindly assign it to me!

Sure, assigning this to you, please start working on this and let us know if you need any help :)
