### ISSUE TITLE
[BUG] < on light mode text is hard to read>

### ISSUE THREAD

**Issue by codezol** [rupali-codes/LinksHub#2316]
### Description

on light mode the text is a little bit hard to read due to very low contrast, I check it out using wave and i got like 129 accessiblity errors.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@codezol please drop some screenshots so we can see what you're talking about.

**Comment by codezol** [comment]
ok sorry for not providing enough context.
 
WAVE is a free tool for testing the web accessibility, the problem can be solved just by making the text color a bit darker when its in light mode.

 
![Screenshot 2024-03-22 at 02-16-37 LinksHub A hub of ready-to-use tech resources](https://github.com/rupali-codes/LinksHub/assets/130334787/f24b65b6-d7b6-46e2-ae75-fbc37e97b236)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes

**Comment by rupali-codes** [comment]
> @rupali-codes

Create new issue..
