### ISSUE TITLE
[DOCS]: Improve README.md

### ISSUE THREAD

**Issue by money8203** [rupali-codes/LinksHub#232]
### Description

We can improve our readme by putting everything under a section like putting the last sentence under support section! 

### Additional Information

We can also add a discord icon in the community joining section and linked it to our discord server as it looks really cool :)

**Comment by rupali-codes** [comment]
Thank you @money8203. are you willing to do it?

**Comment by the-amazing-atharva** [comment]
Sorry to interrupt the convo but if its ok, I would like to work on the Discord Icon issue
I have added Discord icons to multiple repos before so It'll take me just a few seconds

**Comment by rupali-codes** [comment]
@the-amazing-atharva yes you can start working and rise PR

**Comment by money8203** [comment]
Definitely you can take this @the-amazing-atharva 

If you need any help in raising issues and other stuff you can always ping me up @rupali-codes

**Comment by the-amazing-atharva** [comment]
Thanks guys!
Working on it soon
