### ISSUE TITLE
[Add] Beecrowd

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2322]
### Site URL

judge.beecrowd.com

### Description of the above provided site

Beecrowd is a platform for competitive programming.

"We are a global community of developers committed to keep evolving as students and professionals. Train algorithms and programming challenges and become the expert you always dreamed to be."

### Category

Competitive Programming

### Sub Category

platforms

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by KKaged** [comment]
Is it cool to take this issue and try it out?
