### ISSUE TITLE
[ADD] Tech News

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2323]
### Category Name

Resources

### Subcategory Name

Tech News

### Additional Context

- [Hacker Tab](https://hackertab.dev/) is a handy extension designed to help developers stay up-to-date with the latest tech happenings. Whether you’re a frontend wizard, a backend sorcerer, a full-stack magician, a mobile app conjurer, or a data scientist spellcaster, Hackertab has got you covered! 🧙‍♂️🔮
- [Reddit Programming](https://www.reddit.com/r/programming/)
- [TLDR Newsletter](https://tldr.tech/)
- [GitHub trending](https://github.com/trending)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hey @JuanPabloDiaz you already have plenty of issues assigned to you so we're opening this issue for others to work on :)

**Comment by KKaged** [comment]
I'll take this one if no one has.

**Comment by Anmol-Baranwal** [comment]
Hi @cbid2
I'm reopening this issue because the PR associated with this is still open.
