### ISSUE TITLE
[ADD] <languages/Rust>

### ISSUE THREAD

**Issue by Mouh1b** [rupali-codes/LinksHub#2324]
### Category Name

Languages

### Subcategory Name

Rust

### Additional Context

Rust is a systems programming language that focuses on safety, speed, and concurrency. It is designed to be memory-safe, thread-safe, and free of data races.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@Mouh1b assigning to you, please feel free to tag any of the maintainers if you need any help :)
