### ISSUE TITLE
missing email in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2325]
### What would you like to share or ask?

I suggest that in the **Enforcement** section the `[INSERT CONTACT METHOD]` will be replaced with @rupali-codes email address. or an email address.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@JuanPabloDiaz you're assigned!
