### ISSUE TITLE
[OTHER] Installing packages

### ISSUE THREAD

**Issue by JasonDsouza212** [rupali-codes/LinksHub#233]
### What would you like to share or ask?

- Switching from `npm install` to `npm ci` or `npm clean-install` would be best.
- Because **npm install** might change the Package.json by installing the latest package version thus by changing Package.json file data and it is not what we want to happen
- On the other hand, **npm ci or npm clean-install** only install the packages mentioned in the package.json file.

**Comment by rupali-codes** [comment]
> ### What would you like to share or ask?
> * Switching from `npm install` to `npm ci` or `npm clean-install` would be best.
> * Because **npm install** might change the Package.json by installing the latest package version thus by changing Package.json file data and it is not what we want to happen
> * On the other hand, **npm ci or npm clean-install** only install the packages mentioned in the package.json file.
> 
> ### Additional information
> _No response_

Good catch. Would you like to work on this?
