### ISSUE TITLE
[BUG] <link gives 404 page not found >

### ISSUE THREAD

**Issue by Mouh1b** [rupali-codes/LinksHub#2331]
### Description

a link destination is not working ,the page is not found in Cybersecurity/DefenciveSecurity

### Screenshots

clicking the second link 
![image](https://github.com/rupali-codes/LinksHub/assets/134493935/e60d7a80-fa93-450f-89c4-26c9b3a900c5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
Hi @Mouh1b 
Please find the correct link and let me know if it's available.
I will assign the PR then.

> This is the resource we're talking about.
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/60613eff-2e89-4d98-b54f-ad622cd3203b)

**Comment by Mouh1b** [comment]
Hey @Anmol-Baranwal I've found the correct link and it is available

**Comment by rupali-codes** [comment]
> Hey @Anmol-Baranwal I've found the correct link and it is available

do you still want to work on this issue?

**Comment by Mouh1b** [comment]
yes, assign it to me when you can

**Comment by Anmol-Baranwal** [comment]
@Mouh1b 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.
