### ISSUE TITLE
[Add] Free For Geeks

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2333]
### Site URL

https://freeforgeeks.com

### Description of the above provided site

Free For Geeks is your curated toolbox for building better software. Free resources for all your dev needs.

### Category

Open Source

### Sub Category

projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
You're assigned!
