### ISSUE TITLE
[BUG] missing DevTweet - Delete?

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2334]
### Description

You cannot view the project.

`This repository has been archived by the owner on Mar 5, 2024. It is now read-only.`

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/25883220/6a1f0f48-c40f-4d86-925d-6d20d16946ac)

### Any additional information?

Should we delete it?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
It's actually in the main branch, but still it's not deployed.

**Comment by JuanPabloDiaz** [comment]
Gotcha
