### ISSUE TITLE
[Add] Surge

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2338]
### Site URL

surge.sh

### Description of the above provided site

- [Surge](https://surge.sh/) is a static web publishing for Front-End Developers. 

### Category

Resources

### Sub Category

housting

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by JuanPabloDiaz** [comment]
I can do this one if nobody wants it.

**Comment by Anmol-Baranwal** [comment]
> I can do this one if nobody wants it.

Assigned you, Juan!
