### ISSUE TITLE
[fix] linkshub color theme - tailwind config with codebase

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2341]
### What would you like to share or ask?

Hi @rupali-codes @aftabrehan @CBID2 

As you can see, there are a lot of colors involved and most of them aren't even used. 
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/93127799-c587-4565-8990-e866ffc2a21b)

I think we should redefine on what theme option should be used where which will make it easier and clean the codebase in terms of using colors. 

In the current codebase, `slate` is used which is not even in the template.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 @aftabrehan 
Let me know what you think otherwise we can close this one.

**Comment by CBID2** [comment]
I second your idea @Anmol-Baranwal
