### ISSUE TITLE
[BUG] Overflow sub-category

### ISSUE THREAD

**Issue by JoshiUtsav** [rupali-codes/LinksHub#2343]
### Description

The subcategory at the bottom of the frontend category in the sidebar is not displaying properly.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/98454866/3e9c811b-ff05-4180-b1ce-029833fb4a42)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@JoshiUtsav 
In my case, it does works.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/0f22297f-5734-4152-ad20-f37d88005a16)

@rupali-codes @aftabrehan @CBID2 
Can any of you confirm whether you can see the bug?

**Comment by JoshiUtsav** [comment]
Don't know if this is a bug or not.




https://github.com/rupali-codes/LinksHub/assets/98454866/bd459d15-b1cb-4260-91bb-4975a220453a

**Comment by Anmol-Baranwal** [comment]
@JoshiUtsav 
I see! I thought that was all the subcategories; there are definitely some missing.

I've assigned you the issue. Please proceed.

**Comment by Aadityagoel15** [comment]
Hey @Anmol-Baranwal can you please assign this issue to me. I can help with this.

**Comment by Anmol-Baranwal** [comment]
@JoshiUtsav 
Are you working on this or should I assign Aaditya?

**Comment by JoshiUtsav** [comment]
@Anmol-Baranwal I am working on this.

**Comment by Aadityagoel15** [comment]
> @Anmol-Baranwal can you also assign this to me please?

**Comment by Anmol-Baranwal** [comment]
@JoshiUtsav 
Till when will you make a PR?

**Comment by JoshiUtsav** [comment]
@Anmol-Baranwal assign this task to @Aadityagoel15.

**Comment by Anmol-Baranwal** [comment]
@Aadityagoel15 
I've assigned you the issue.

**Comment by Aadityagoel15** [comment]
Hey @Anmol-Baranwal 
Can you please assign me this under GSSOC 2024?

**Comment by Anmol-Baranwal** [comment]
> Hey @Anmol-Baranwal Can you please assign me this under GSSOC 2024?

Based on my information, LinksHub isn't participating in GSSoC '24.

Please make the PR as soon as possible, maybe within a week.

**Comment by rupali-codes** [comment]
@Aadityagoel15 are you working on this?

**Comment by Aadityagoel15** [comment]
> @Aadityagoel15 are you working on this?

I made the changes but I am not able to make a pull request. It is showing me error.
