### ISSUE TITLE
[ADD] Include Ansible in DevOps

### ISSUE THREAD

**Issue by mdazfar2** [rupali-codes/LinksHub#2345]
### Site URL

https://www.redhat.com/en/blog/ansible-101-ansible-beginners

## Description of the above provided site
Ansible is a popular automation tool known for its simplicity and versatility in infrastructure management and application deployment.

As a DevOps professional, Ansible is a powerful tool. Check the link above for detailed Ansible playbook tutorials, ideal for practicing and preparing for the RH-EX294 exam.

## Why Add Ansible?
- Provides educational value on modern DevOps practices.
- Showcases practical use cases for automation and orchestration.
- Engages DevOps professionals and enthusiasts.

### Category

DevOps

### Sub Category

Automation Tool

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@mdazfar2 
I think it's better to add the website link of ansible: https://www.ansible.com/ since it has link to necessary info. 
What do you think?

You would have to create a subcategory since `Automation Tool` doesn't exists.

**Comment by mdazfar2** [comment]
> @mdazfar2 I think it's better to add the website link of ansible: https://www.ansible.com/ since it has link to necessary info. What do you think?

Yes, that is a very good link to learn Ansible; each and every topic is covered through this link.

**Comment by Anmol-Baranwal** [comment]
@mdazfar2 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me or any of the maintainers if you require any assistance. 

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/f84c2270-9399-4b9a-bc9e-4c4bf4d5381f)

Please remember to mark that checkbox next time, so I can assign it more quickly. I've done it this time :)
