### ISSUE TITLE
[ADD] Solana in Blockchain 

### ISSUE THREAD

**Issue by devhimanshuu** [rupali-codes/LinksHub#2346]
### Category Name

Blockchain

### Subcategory Name

Blockchain Platform

### Additional Context

Solana is a high-performance blockchain platform designed for decentralized applications and crypto-native projects, known for its fast transaction processing and low fees. It aims to provide scalability without sacrificing security or decentralization.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@devhimanshuu 
LinksHub already has a category named `BlockChain`. You can create a subcategory named `Platforms` and add it there.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/8ade45b6-f4ab-4b01-8c20-1f65e392081a)

I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

**Comment by CBID2** [comment]
Hey @devhimanshuu! :) Are you still working on this issue?

**Comment by devhimanshuu** [comment]
No i am not working you can go ahead

**Comment by rupali-codes** [comment]
Closing due to inactiveness.
