### ISSUE TITLE
[DOCS] Update directions on adding resources to the website 

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#2348]
### Issue Description

When people come to add resources to the website, they might be confused by [the steps in the Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#appending-new-categories-) because it does not mention the click on the "Wanna Add Something?" button.  

### Button

![Wanna Add Something Button](https://github.com/rupali-codes/LinksHub/assets/105683440/7f760d1d-1244-4c00-b4e4-ca8504565238)

### Section in Contributing Guide

![Section in Contributing Guide](https://github.com/rupali-codes/LinksHub/assets/105683440/0c2326d0-26f8-4fcc-883a-4660132b8947)

### Proposed Solution (optional)

Go to [line 107 in the Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/bb98806320c7108566f4af6a08436b226b7f1b21/CONTRIBUTING.md?plain=1#L107C1-L108C1) and make the following adjustment:

```markdown
You can suggest new categories by going to of the current categories on [our website and click on the "Wanna Share Something?" button](https://www.linkshub.dev/).

```

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
It's the same thing i think, like going back to the website from github issues then visiting the page over again.

@Anmol-Baranwal what do you think?

**Comment by Anmol-Baranwal** [comment]
> It's the same thing i think, like going back to the website from github issues then visiting the page over again.
> 
> @Anmol-Baranwal what do you think?

Yes! Kind of. But maybe we can explicitly mention it in the contributing guidelines directly rather than doing as in proposed solution. Providing a bit of context for that purpose. It's up to all of you to decide.

**Comment by CBID2** [comment]
> > It's the same thing i think, like going back to the website from github issues then visiting the page over again.
> > @Anmol-Baranwal what do you think?
> 
> Yes! Kind of. But maybe we can explicitly mention it in the contributing guidelines directly rather than doing as in proposed solution. Providing a bit of context for that purpose. It's up to all of you to decide.

Good point @Anmol-Baranwal. I revised my solution a bit. Check it out. You too @rupali-codes
