### ISSUE TITLE
[ADD] Static Site Generator

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2349]
### Category Name

resources

### Subcategory Name

Static Site Generator

### Additional Context

1. move [Hugo](https://gohugo.io/) is the world’s fastest framework for building modern static site websites written in Go. ⭐ [72k stars](https://github.com/gohugoio/hugo)
2. [Nuxt](https://nuxtjs.org/) is a higher-level framework built on top of Vue.js. ⭐ [52k stars](https://github.com/nuxt/nuxt)
3. [Jekyll](https://jekyllrb.com/) is a simple, blog-aware, static site generator perfect for personal, project, or organization sites. ⭐ [48k stars](https://github.com/jekyll/jekyll)
4. [Gatsby](https://www.gatsbyjs.com/) is a free and open source framework based on React that helps developers build blazing fast websites and apps. ⭐ [42k stars](https://github.com/gatsbyjs/gatsby)
5. [Hexo](https://hexo.io/) is a fast, simple, and powerful blog framework. ⭐ [39k stars](https://github.com/hexojs/hexo)
6. move [VuePress](https://vuepress.vuejs.org/) is a **minimalistic static site generator** with a Vue-powered theming system. ⭐ [22k stars](https://github.com/vuejs/vuepress)
7. [SvelteKit](https://kit.svelte.dev/) is a framework for building web applications of all sizes, with a beautiful development experience and flexible filesystem-based routing. ⭐ [18k stars](https://github.com/sveltejs/kit)
8. [Eleventy](https://www.11ty.dev/) is a simpler static site generator. An alternative to Jekyll. Written in JavaScript. ⭐ [16k stars](https://github.com/11ty/eleventy)
9. [Zola](https://www.getzola.org/) is a fast static site generator in a single binary with everything built-in. ⭐ [12.5k stars](https://github.com/getzola/zola)
10. [Pelican](https://blog.getpelican.com/) is a static site generator, written in Python. ⭐ [12k stars](https://github.com/getpelican/pelican)
11. [Gridsome](https://gridsome.org/) is a Vue.js-powered static site generator for building CDN-ready websites for any headless CMS, local files, or APIs. ⭐ [8.5k stars](https://github.com/gridsome/gridsome)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by JuanPabloDiaz** [comment]
[Hugo](https://gohugo.io/) and [VuePress](https://vuepress.vuejs.org/) are in another category and I am planning on moving them to this new category @Anmol-Baranwal.
Please let me know what do you think?

**Comment by Anmol-Baranwal** [comment]
> [Hugo](https://gohugo.io/) and [VuePress](https://vuepress.vuejs.org/) are in another category and I am planning on moving them to this new category @Anmol-Baranwal. Please let me know what do you think?

@rupali-codes can let you know about the same.

I'm not sure because those are very specific and appropriate subcategories.

**Comment by JuanPabloDiaz** [comment]
> > [Hugo](https://gohugo.io/) and [VuePress](https://vuepress.vuejs.org/) are in another category and I am planning on moving them to this new category @Anmol-Baranwal. Please let me know what do you think?
> 
> @rupali-codes can let you know about the same.
> 
> I'm not sure because those are very specific and appropriate subcategories.

Can I just do the PR without moving those items previously mentioned in https://github.com/rupali-codes/LinksHub/pull/2350 ?

**Comment by JuanPabloDiaz** [comment]
Please advise...

**Comment by Anmol-Baranwal** [comment]
> > > [Hugo](https://gohugo.io/) and [VuePress](https://vuepress.vuejs.org/) are in another category and I am planning on moving them to this new category @Anmol-Baranwal. Please let me know what do you think?
> > 
> > 
> > @rupali-codes can let you know about the same.
> > I'm not sure because those are very specific and appropriate subcategories.
> 
> Can I just do the PR without moving those items previously mentioned in #2350 ?

Yeah, sure!

@rupali-codes 
If you want any changes, let him know.

**Comment by rupali-codes** [comment]
> > > > [Hugo](https://gohugo.io/) and [VuePress](https://vuepress.vuejs.org/) are in another category and I am planning on moving them to this new category @Anmol-Baranwal. Please let me know what do you think?
> > > 
> > > 
> > > @rupali-codes can let you know about the same.
> > > I'm not sure because those are very specific and appropriate subcategories.
> > 
> > Can I just do the PR without moving those items previously mentioned in #2350 ?
> 
> Yeah, sure!
> 
> @rupali-codes 
> If you want any changes, let him know.

@JuanPabloDiaz yeah ofcourse
