### ISSUE TITLE
[OTHER] change theme toggler color

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#235]
### What would you like to share or ask?

Currently, the color of theme toggler is `text-white` in dark theme, your task is to replace the color `text-gray-200` as we aren't using white anywhere in LinksHub's theme.

### Additional information

![image](https://user-images.githubusercontent.com/78981177/220526820-ff88a558-51b2-42eb-8300-9759d4c78935.png)

**Comment by lameast** [comment]
Hi, could I work on this issue? This should just be a change in the class in the theme toggler component right?

**Comment by alindsharmasimply** [comment]
Hey @rupali-codes , I've raised a PR for this issue resolution. Kindly check #238 out.

**Comment by rupali-codes** [comment]
> Hey @rupali-codes , I've raised a PR for this issue resolution. Kindly check #238 out.

got it thanks :)
