### ISSUE TITLE
[Feature] <about the saved feature>

### ISSUE THREAD

**Issue by Mouh1b** [rupali-codes/LinksHub#2351]
### Description

I noticed that LinkHub currently still lacks the feature for users to save their favorite links. Implementing a favorite button that utilizes browser cookies could enhance user experience by allowing users to personalize their browsing without the need for user accounts and a backend database(it is at least a temporary solution until the real backend is implemented and the accounts are added, I thought of using rxdb which is a local database for typescript and javascript applications)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
Hi @Mouh1b!

This is already being handled by Vidip with https://github.com/rupali-codes/LinksHub/issues/1853

@rupali-codes can let you know more about this!

**Comment by pattuzzoj** [comment]
For saved resources, I suggest use Local Storage. Use JSON.stringify over a list of objects with content, like title, description and url and save it. In the saved page, just request the content.

**Comment by Anmol-Baranwal** [comment]
> For saved resources, I suggest use Local Storage. Use JSON.stringify over a list of objects with content, like title, description and url and save it. In the saved page, just request the content.

I don't think it's an efficient way. We need a strict system so it would be saved irrespective of the system that is why GitHub Auth is being implemented. Let's see what others say!

@rupali-codes
