### ISSUE TITLE
[Add] Corbado in Backend > Authentication

### ISSUE THREAD

**Issue by lurueger** [rupali-codes/LinksHub#2352]
### Site URL

https://www.corbado.com

### Description of the above provided site

Corbado offers passwordless authentication for almost all languages & frameworks.
Developers can use Corbado to implement passkeys in their existing or new applications with just a few lines of code.

They also post a lot of educational content on passkeys, WebAuthn with tutorials to implement them (even without their solution) aswell as a glossary with industry-specific words.

I think they're a valuable source for developers, no matter whether they want to use Corbado or implement passkeys themselves.

### Category

Backend

### Sub Category

authentication

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@lurueger 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag us if you require any assistance.
