### ISSUE TITLE
[ADD] <languages/Perl>

### ISSUE THREAD

**Issue by Mouh1b** [rupali-codes/LinksHub#2356]
### Category Name

languages

### Subcategory Name

Perl

### Additional Context

perl is an essential  interpreted, high-level, general-purpose programming language, It is used in production codebases of many companies, for tasks as diverse as web development, databases access, log analysis or web crawling. It is a core component of most unix-like systems.
and I think it should be added to the languages category .

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
closing due to inactiveness.
