### ISSUE TITLE
[Add] Pulumi IaC

### ISSUE THREAD

**Issue by desteves** [rupali-codes/LinksHub#2359]
### Site URL

https://www.pulumi.com/

### Description of the above provided site

Infrastructure as Code tool that is open source and allows you to define just about any cloud resources (infrastructure) in TypeScript/JavaScript, Python, Go, C#, Java, or YAML.

### Category

DevOps

### Sub Category

IaC

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Looks great @desteves! :)
