### ISSUE TITLE
[Add] devresourc.es

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2362]
### Site URL

https://devresourc.es/

### Description of the above provided site

A collection of resources for developers, categorized and crowdsourced. Learn programming, UI inspiration, job boards, images, icons and much more.

### Category

Open Source

### Sub Category

projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by yaten2302** [comment]
Hey @rupali-codes, may I work on this issue if it's required?
