### ISSUE TITLE
[BUG] client-side exception has occurred

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2363]
### Description

I got an error message when I was searching for resources.
I got the same error in multiple searchs and browsers.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/25883220/7616a2d4-1c94-41fb-b8de-667c73acaa83)

![image](https://github.com/rupali-codes/LinksHub/assets/25883220/8322b243-9702-4410-be1d-fe34fc938fa3)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
I think it's fixed, please check it again.

**Comment by JuanPabloDiaz** [comment]
Its working fine now. 

What was going on? what trigger the error?

**Comment by Anmol-Baranwal** [comment]
> Its working fine now.
> 
> What was going on? what trigger the error?

I think the upvote PR was causing the issue, but I'm not sure. 
I'll close this then. Thanks for raising the issue.
