### ISSUE TITLE
[Add] Apislist

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2364]
### Site URL

https://apislist.com/

### Description of the above provided site

[Apislist](https://apislist.com/) is a collection of free APIs. Curated Playground for the Best Public Web APIs!

### Category

Backend

### Sub Category

apis

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by yaten2302** [comment]
@rupali-codes, could you please assign this issue to me, check [this comment](https://github.com/rupali-codes/LinksHub/issues/2375#issuecomment-2136810979)

**Comment by yaten2302** [comment]
Hey @rupali-codes! Any update on this :)
Do you guys assign issues specifically or like we can start working on it, if there is no PR? (You can assign this issue to me, whenever you feel free, if no one is working on it)

**Comment by rupali-codes** [comment]
> Hey @rupali-codes! Any update on this :) Do you guys assign issues specifically or like we can start working on it, if there is no PR? (You can assign this issue to me, whenever you feel free, if no one is working on it)

Heyyaa, assigning to you!

**Comment by yaten2302** [comment]
Hey @rupali-codes, I've created a [PR](https://github.com/rupali-codes/LinksHub/pull/2386) for this, could you please review it and let me know if any changes are required?

**Comment by Anmol-Baranwal** [comment]
closing this because the linked issue is merged.
