### ISSUE TITLE
Copyright license  is not showing on mobile devices in Saved Page

### ISSUE THREAD

**Issue by Rajvardhan222** [rupali-codes/LinksHub#2365]
### Description

when we visit saved tab with mobile phone "© 2024 LinksHub | MIT License
Developed by
[Rupali Haldiya](https://rupalihaldiya.vercel.app/) and [Open Source Community](http://localhost:3000/contributors)"

this footer is not visible there

### Screenshots

![Screenshot 2024-05-17 174338](https://github.com/rupali-codes/LinksHub/assets/146507318/40d664b6-ddfa-457b-9583-11a647100b57)
as you can see copy right footer is not visible even if we scroll on mobile devices.
![Screenshot 2024-05-17 174353](https://github.com/rupali-codes/LinksHub/assets/146507318/e7163387-6d99-4af1-86ec-9f7ca03ba8e0)

but after changes it is visible...

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Rajvardhan222** [comment]
The second image is after i made the changes

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Do we want to display that on mobile devices?

The team option is already there in the mobile nav.

**Comment by Rajvardhan222** [comment]
Then it should be fully removed as it is visible on mobile devices very very very little and therefore i got there and thought to make it entirely visible
![20240519_102636](https://github.com/rupali-codes/LinksHub/assets/146507318/c21d4a26-9b36-4dcc-8df6-907db5c9de86)

**Comment by rupali-codes** [comment]
> @rupali-codes Do we want to display that on mobile devices?
> 
> The team option is already there in the mobile nav.

Either we completely hide it or just show properly, its kinda glitching
