### ISSUE TITLE
[Add] Freeter

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2369]
### Site URL

https://freeter.io/

### Description of the above provided site

A smarter way to work on your computer. [Read why](https://community.freeter.io/topic/14/how-i-boosted-my-productivity-while-working-on-multiple-projects).

### Category

Open Source

### Sub Category

projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by zaidiyazdan** [comment]
Hi i want to work on this issue please assign it to me

**Comment by Anmol-Baranwal** [comment]
@zaidiyazdan 
I've assigned you. Please proceed with it.
