### ISSUE TITLE
[Add] Arpit Bhayani

### ISSUE THREAD

**Issue by vedantjdv** [rupali-codes/LinksHub#2372]
### Site URL

https://www.youtube.com/@AsliEngineering

### Description of the above provided site

Arpit Bhayani's YouTube channel explores diverse computer science topics including databases, system design, architecture, and algorithms.

### Category

Youtube

### Sub Category

Computer Science

### Checklist

- [X] I have checked the existing issues
- [x] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by jasonmokk** [comment]
Hello, I'd like to work on this issue. Can I be assigned?

**Comment by rupali-codes** [comment]
@vedantjdv assigning to you!
