### ISSUE TITLE
[Add]  Add new resource to learn rust language

### ISSUE THREAD

**Issue by Vijaykv5** [rupali-codes/LinksHub#2375]
### Site URL

https://www.rustfinity.com

### Description of the above provided site

This is a new [site](https://www.rustfinity.com) which provides a better understanding and learning of Rust by Practice.
It provides a better way of understanding deep concepts in rust.

### Category

Languages

### Sub Category

Rust

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by yaten2302** [comment]
May I also work on this issue?

**Comment by rupali-codes** [comment]
> May I also work on this issue?

Since @Vijaykv5 wants to work on this, we will assign this issue to them, kindly raise new issue to get assigned.

**Comment by rupali-codes** [comment]
@yaten2302 would you like to work on this #2364?

**Comment by yaten2302** [comment]
> @yaten2302 would you like to work on this #2364?

Sure @rupali-codes, I would like to work on this issue👍
