### ISSUE TITLE
[Add] Responsively

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2379]
### Site URL

https://responsively.app

### Description of the above provided site

- [Responsively](https://responsively.app) is a modified web browser that helps in responsive web development. A web developer's must have dev-tool.

### Category

Other

### Sub Category

devtools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@JuanPabloDiaz assigning to you!

**Comment by JuanPabloDiaz** [comment]
Github action closed it
