### ISSUE TITLE
[Delete] duplicate Postman

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2381]
### Site URL

https://www.postman.com/

### Description of the above provided site

![image](https://github.com/rupali-codes/LinksHub/assets/25883220/bcb61ac4-2d39-43df-84a1-abfc839d139d)

### Category

Backend

### Sub Category

Testing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by jasonmokk** [comment]
Hi @rupali-codes can you please assign this issue to me?

**Comment by Anmol-Baranwal** [comment]
@jasonmokk 
You're assigned. Please raise a PR!

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
Done!
