### ISSUE TITLE
to add Shadcn/ui to the component

### ISSUE THREAD

**Issue by keerthinannepamula1** [rupali-codes/LinksHub#2385]
### Site URL

https://ui.shadcn.com/

### Description of the above provided site

It's a collection of re-usable components which are quite useful for devs to mismatch components. This is also an open source project, hence I would like to add this to the frontend section.

### Category

Frontend

### Sub Category

Components

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@keerthinannepamula1 
It's already there.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/00dade5e-8100-4a05-bc0e-991fb92d64d9)

Please create another issue or comment under the ones marked with `up for grabs`, which are open for anyone to contribute.

> I'm closing this for now.
