### ISSUE TITLE
[BUG] Domain has expired

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2387]
### Description

Renew the registration for the domain name.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/25883220/01d3c82c-65b1-46f8-99b2-1a9100b94053)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
Ah! It will automatically get renewed in 2-3 days. Please use this: https://linkshub.vercel.app/ if you need to visit the deployed URL.

I'm closing this issue. Thanks!
