### ISSUE TITLE
[Add] <add new resources to learn smart contract development, auditing and security researching>

### ISSUE THREAD

**Issue by panditdhamdhere** [rupali-codes/LinksHub#2388]
### Site URL

https://updraft.cyfrin.io/

### Description of the above provided site

This resource provide you depth in knowledge of solidity smart contract development and auditing and also it teach you industry standards and tools like foundry. Even you can learn advance blockchain stuff like yul-assembly, huff, Ethereum Opcodes and formal verification and much more!

### Category

Blockchain

### Sub Category

Smart contract development and security

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@panditdhamdhere sorry for the delay, you can submit a PR whenever you get time. Assigned to you.

**Comment by Anmol-Baranwal** [comment]
@panditdhamdhere 
Are you working on this? have you raised a pr yet?

**Comment by devansh-dek** [comment]
Is this issue still open? Can i work on it?

**Comment by rupali-codes** [comment]
> Is this issue still open? Can i work on it?

sure, lets get your PR merged then we'll assign this one to you

**Comment by rajneesh-18** [comment]
I want to work on this issue. Assign it to me @rupali-codes.
