### ISSUE TITLE
[Feature] Pull Request Compliance Checker 

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#2389]
#### Problem
There has been a recurring issue with first-time contributors submitting pull requests without completing the form.

### Solution
OpenSauced uses a [compliance workflow](https://github.com/open-sauced/guestbook/blob/main/.github/workflows/compliance.yml), and it's been helpful with checking for incomplete PR forms. 
> [!NOTE]
> I tested this myself in a test-repo that I created, and it worked(see photos in the screenshots section for more context).

### Screenshots
![the pull request from my test repo](https://github.com/rupali-codes/LinksHub/assets/105683440/1ecc1f9f-24d7-4806-9434-56a2170cbef1)
![results of the first test](https://github.com/rupali-codes/LinksHub/assets/105683440/11eb0225-8419-4101-9c46-555af8fce903)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
@Anmol-Baranwal, @aftabrehan 
, and @rupali-codes, what do you think?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal, @aftabrehan , and @rupali-codes, what do you think?

I'm still not clear on what it does, I mean the forms are in .yml format so beginners shouldn't face any problems.
That is the minimum requirement if anyone want to communicate in open source.

**Comment by CBID2** [comment]
> > @Anmol-Baranwal, @aftabrehan , and @rupali-codes, what do you think?
> 
> I'm still not clear on what it does, I mean the forms are in .yml format so beginners shouldn't face any problems. That is the minimum requirement if anyone want to communicate in open source.

It's meant to warn contributors that they have'nt filled out their PRs effectively. I've seen [this work at OpenSauced](https://github.com/open-sauced/guestbook/pull/341#pullrequestreview-2089768242).

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 
I think we should go for this. At least the basic requirements like issue will be linked properly!
