### ISSUE TITLE
Python Beginner Tutorial

### ISSUE THREAD

**Issue by rajneesh-18** [rupali-codes/LinksHub#2390]
### Category Name

Python

### Subcategory Name

Complete Tutorial

### Additional Context

Amazing explaination about the fundamentals. 
Link: https://youtu.be/v9bOWjwdTlg?si=5LuSLYiB8lMhgVPv

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [ ] I am willing to work on this issue (optional)

**Comment by rajneesh-18** [comment]
Thanks

**Comment by rupali-codes** [comment]
Thank you @rajneesh-18

**Comment by prafullmaru** [comment]
@rupali-codes - I will be interested to work on this issue, if not assigned and addressed yet, I can work on this item.

**Comment by rajneesh-18** [comment]
> @rupali-codes - I will be interested to work on this issue, if not assigned and addressed yet, I can work on this item.

we'll assign it to you

**Comment by rupali-codes** [comment]
@prafullmaru you're assigned, please let us know if you need any assistance

**Comment by prafullmaru** [comment]
Started wit this, definitely I will ask for assistance, if any trouble.

**Comment by rajneesh-18** [comment]
We'll look into it.
