### ISSUE TITLE
Git & Github in Hindi

### ISSUE THREAD

**Issue by rajneesh-18** [rupali-codes/LinksHub#2391]
### Category Name
Hindi Tutorial

### Subcategory Name

Complete Tutorial

### Additional Context

Explain about Git and workflow. Here, you explore about Github.

Link:https://youtu.be/q8EevlEpQ2A?si=mE3i7yeFoEUxcMDQ

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
What do you think?

**Comment by rupali-codes** [comment]
@rajneesh-18 you're assigned, please feel free to ask if you need any help

**Comment by rajneesh-18** [comment]
ok i'll raise the pr soon
