### ISSUE TITLE
[Refactor] Instead o keep modifying json and release - Let we use storage with admin having access for entry

### ISSUE THREAD

**Issue by prafullmaru** [rupali-codes/LinksHub#2393]
### File Name

LinksHub//database/**/*.json

### Reason for Refactoring the Code

If we will have all data in storage, by developing screen for CRUD operations we can easily manage - Category, Sub-Category and links under that.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [ ] I am willing to work on this issue (optional).

**Comment by prajwaldhatti123** [comment]
are you suggesting to add a database for the app ??

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 @aftabrehan 
What do you think...

**Comment by rupali-codes** [comment]
> @rupali-codes @CBID2 @aftabrehan What do you think...

I think we are already working on it

**Comment by prafullmaru** [comment]
Apologies for delayed response.
Yes, I meant to have database and that will address all issue of add/update/remove of any category & subcategory.

**Comment by rupali-codes** [comment]
> Apologies for delayed response. Yes, I meant to have database and that will address all issue of add/update/remove of any category & subcategory.

I see, thank you for the suggestion, but we are working on it :)
