### ISSUE TITLE
[ADD] Ai Tools/Chat

### ISSUE THREAD

**Issue by Tobee1406** [rupali-codes/LinksHub#2399]
### Category Name

Ai Tools

### Subcategory Name

Chat

### Additional Context

This subcategory will make it possible to add AI Chats such as ChatGPT, Copilot, Gemini, etc...

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [ ] I am willing to work on this issue (optional)

**Comment by devansh-dek** [comment]
I would like to solve this issue!

**Comment by Anmol-Baranwal** [comment]
> I would like to solve this issue!

I've assigned you. Please raise a PR!
