### ISSUE TITLE
[Add] <i want to add youtube link  for  computer science>

### ISSUE THREAD

**Issue by dikshapandey08** [rupali-codes/LinksHub#2400]
### Site URL

www.youtube.com/@UniversityAcademy

### Description of the above provided site

University Academy is India’s first and biggest platform for professional students of various streams started in 2017. Students from professional backgrounds have opportunities to live in the digital world with this e-learning portal. We are providing video lectures, notes, assignments, tutorials, quizzes, previous year solved papers and many more. Some of the courses are certification courses. We have 25K+ subscribers on the YouTube channel with 135 million views and 800 million minute watch time. University Academy provides real-time support over WhatsApp & Telegram to reached thousands of students daily. On University Academy website get thousands of hit daily and more than 5K enrolled courses on the website. University Academy dedicated team available on live stream every Sunday to connect with students for a discussion about the academic issues.

### Category

Youtube

### Sub Category

Computer Science 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by dikshapandey08** [comment]
i would like to work on this issue please assign to me.

**Comment by devansh-dek** [comment]
Is this issue still open? Can i work on it?

**Comment by rajneesh-18** [comment]
> i would like to work on this issue please assign to me.

wait for sometime our maintainer will assign to you.

**Comment by rupali-codes** [comment]
@dikshapandey08 you're assigned. Please feel free to ask if you need any hel.

**Comment by rupali-codes** [comment]
> Is this issue still open? Can i work on it?

Hi Devansh, could you please look into issue, we'll assign it you #2399

**Comment by devansh-dek** [comment]
What category/subcategory should i add this link?
