### ISSUE TITLE
[BUG] Some Info buttons are not filled in the data-tooltip-content element

### ISSUE THREAD

**Issue by GabrielBittar** [rupali-codes/LinksHub#2408]
### Description

Some of the info buttons at subcategories have their "data-tooltip-content" element empty, therefore when one hovers the mouse over them, no message will be displayed.

### Screenshots

For example, at System Design subcategory.
![image](https://github.com/rupali-codes/LinksHub/assets/46246341/90d12301-2b40-4732-80e7-7e05aa93ca32)

### Any additional information?

This also happens at:

3D Libraries
Css Games
Design Inspiration
Js-Chart Libraries
Next JS
Online Code Editors
[...]
and many other subcategories.

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by CBID2** [comment]
Hey @GabrielBittar. I just checked out the issue. The bug you mentioned is occurring.

**Comment by GabrielBittar** [comment]
Hello, fixed on #2411
