### ISSUE TITLE
[OTHER] Add hover effect on buttons of main page

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2409]
### What would you like to share or ask?

Adding hover on the buttons will enhance the user experience. Please add a background colour transition on the following buttons:

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/2261a979-d9b2-4831-b6c3-f7aa5244a412)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by GabrielBittar** [comment]
Hey, I'm interested in working on it, can you assign it to me please?
btw.: should one follow some design pattern for hover colors? I mean, are there exact hexcodes to be used on hover, or should it just become a little lighter?

**Comment by ompharate** [comment]
ok. Could you please assign this issue to me?

**Comment by rupali-codes** [comment]
> Hey, I'm interested in working on it, can you assign it to me please? btw.: should one follow some design pattern for hover colors? I mean, are there exact hexcodes to be used on hover, or should it just become a little lighter?

Hey, could you please look for some other, since @ompharate has raised a PR, we are currently assigning the issue to them, please make sure to follow our CONTRIBUTING guidelines before making any contribution.

**Comment by ompharate** [comment]
please assign me this issue.
