### ISSUE TITLE
[Feature] Implement non standard text highlight color

### ISSUE THREAD

**Issue by GabrielBittar** [rupali-codes/LinksHub#2412]
### Description

Implementing a non standard color at CSS ::selection > background may improve user experience. If this change looks like a good idea, I'd suggest using #714eff or #fbd449, since these are already in use in the website. Though the yellow one would also require a change on the text color, or it'd be unreadable.

## purple
![image](https://github.com/rupali-codes/LinksHub/assets/46246341/e58ff053-0f6d-4928-8900-22db3758a909)

## yellow, unreadable
![image](https://github.com/rupali-codes/LinksHub/assets/46246341/6619c756-cd9e-4c4c-abbf-aad0d4155c89)

## but when text color goes darker, yellow seems fine again
![image](https://github.com/rupali-codes/LinksHub/assets/46246341/3096ae2d-4f23-48e2-9ad7-9bd90ac91e1f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by GabrielBittar** [comment]
P.s.: sorry, I'd not call it "priority: high", I didn't see the label before I created the issue.

**Comment by rupali-codes** [comment]
@GabrielBittar you're assigned, we'll go with purple as per our theme.

**Comment by rupali-codes** [comment]
hey @GabrielBittar do we have any update on this?

**Comment by GabrielBittar** [comment]
> hey @GabrielBittar do we have any update on this?

Hey! Yes, #2415
