### ISSUE TITLE
[ADD] <Dracula Theme>

https://draculatheme.com/

### ISSUE THREAD

**Issue by Rx-Metallica** [rupali-codes/LinksHub#2414]
Dracula is a color scheme for code editors and terminal emulators such as Vim, Notepad++, iTerm, VSCode, Terminal.app, ZSH, and much more.

**Comment by rupali-codes** [comment]
@Rx-Metallica please read and follow our [CONTRIBUTING Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) and don't raise before getting an issue assigned.

**Comment by Rx-Metallica** [comment]
> @Rx-Metallica please read and follow our [CONTRIBUTING Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) and don't raise before getting an issue assigned.

Please assigned this issue to me

**Comment by rupali-codes** [comment]
> > @Rx-Metallica please read and follow our [CONTRIBUTING Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) and don't raise before getting an issue assigned.
> 
> Please assigned this issue to me

Alright, please keep it in mind from next time

**Comment by Rx-Metallica** [comment]
> > > @Rx-Metallica please read and follow our [CONTRIBUTING Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) and don't raise before getting an issue assigned.
> > 
> > Please assigned this issue to me
> 
> Alright, please keep it in mind from next time

Do i hve to pull this request again?
