### ISSUE TITLE
[ADD] "Design"

### ISSUE THREAD

**Issue by GabrielBittar** [rupali-codes/LinksHub#2416]
### Category Name

Design

### Subcategory Name

Mobile, Web, Desktop...

### Additional Context

Maybe we could have a "Design" category, to list good links related to this theme, then as subcategories something like mobile, web, desktop... Or other subcategories.
I'd suggest, e.g., [RealTime Colors](https://www.realtimecolors.com/?colors=050315-fbfbfe-2f27ce-dedcff-433bff&fonts=Inter-Inter), wich is an open source website that changes it's own colors and fonts for color testing, but there are surely many other tools that could be listed.
If this looks like a good idea, I'm interested in developing this category.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@GabrielBittar we already have this category as `Design Inspiration`, though we can consider adding more subcategories to it.

**Comment by GabrielBittar** [comment]
> @GabrielBittar we already have this category as `Design Inspiration`, though we can consider adding more subcategories to it.

Ops, sorry, I didn't realise it was inside front end. We can't add subcategories nowadays, since it is already one. Maybe would it make sense turning `Design Inspiration` into a subcategory of Design instead, so frontend and design are not mixed anymore?

**Comment by rupali-codes** [comment]
> > @GabrielBittar we already have this category as `Design Inspiration`, though we can consider adding more subcategories to it.
> 
> Ops, sorry, I didn't realise it was inside front end. We can't add subcategories nowadays, since it is already one. Maybe would it make sense turning `Design Inspiration` into a subcategory of Design instead, so frontend and design are not mixed anymore?

Sounds cool, we can do that. Are you interested in working on this?

**Comment by GabrielBittar** [comment]
> > > @GabrielBittar we already have this category as `Design Inspiration`, though we can consider adding more subcategories to it.
> > 
> > 
> > Ops, sorry, I didn't realise it was inside front end. We can't add subcategories nowadays, since it is already one. Maybe would it make sense turning `Design Inspiration` into a subcategory of Design instead, so frontend and design are not mixed anymore?
> 
> Sounds cool, we can do that.

Nice. Can I be assigned?
Btw, would it be good if we had a subcategory called `Design Tools` where we could insert useful tools (like, e.g., the one suggested in this issue)? Then we'd have Inspiration and Tools inside `Design` as a kickstart.

**Comment by rupali-codes** [comment]
> > > > @GabrielBittar we already have this category as `Design Inspiration`, though we can consider adding more subcategories to it.
> > > 
> > > 
> > > Ops, sorry, I didn't realise it was inside front end. We can't add subcategories nowadays, since it is already one. Maybe would it make sense turning `Design Inspiration` into a subcategory of Design instead, so frontend and design are not mixed anymore?
> > 
> > 
> > Sounds cool, we can do that.
> 
> Nice. Can I be assigned? Btw, would it be good if we had a subcategory called `Design Tools` where we could insert useful tools (like, e.g., the one suggested in this issue)? Then we'd have Inspiration and Tools inside `Design` as a kickstart.

Yeah, we can even a subcategory named Tutorials and add video links to it from youtube.

**Comment by rupali-codes** [comment]
@GabrielBittar, you're assigned.

**Comment by GabrielBittar** [comment]
Hello, just for the record, since I got assigned, I'm working on it and will deliver it for review soon.

**Comment by rupali-codes** [comment]
@GabrielBittar are you working on this?

**Comment by GabrielBittar** [comment]
> @GabrielBittar are you working on this?

Hello,
Sorry, I was, but then I got sick, so I'm staying away for some time. But looking forward to return to the project and keep working on this issue asap. If you guys don't mind, I truly intend to return asap, I'm loving to contribute on this project.
Thanks.

**Comment by rupali-codes** [comment]
> > @GabrielBittar are you working on this?
> 
> Hello, Sorry, I was, but then I got sick, so I'm staying away for some time. But looking forward to return to the project and keep working on this issue asap. If you guys don't mind, I truly intend to return asap, I'm loving to contribute on this project. Thanks.

Alright, please take care Gabriel. And get well soon :)
