### ISSUE TITLE
[Add] SaasInterface

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#242]
### URL

https://saasinterface.com/

### Description of the above provided site

Save yourself hours of research and create beautiful apps by taking inspiration from the best SaaS products.

### Category

Frontend

### Sub Category

design inspirations

**Comment by rupali-codes** [comment]
> ### URL
> https://saasinterface.com/
> 
> ### Description of the above provided site
> Save yourself hours of research and create beautiful apps by taking inspiration from the best SaaS products.
> 
> ### Category
> Frontend
> 
> ### Sub Category
> design inspirations

Thank you, would you like to work on this?

**Comment by Oyebolade** [comment]
Yes

**Comment by Oyebolade** [comment]
Yes

**Comment by parma1111** [comment]
Can I raise a PR for it ?
