### ISSUE TITLE
[Add] TOOOLS.design

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2423]
### Site URL

https://www.toools.design

### Description of the above provided site

A growing archive of 1,500+ design resources, frequently updated for the community.

category is not an option
![image](https://github.com/user-attachments/assets/1f4c11b8-3d9a-474b-a631-3604cd8e243a)

### Category

Other

### Sub Category

AI Tools > Design

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@JuanPabloDiaz you're assigned.
