### ISSUE TITLE
[Add] Awesome-Design-Tools

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2424]
### Site URL

https://github.com/goabstract/Awesome-Design-Tools

### Description of the above provided site

The best design tools and plugins for everything

### Category

Resources

### Sub Category

design

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@JuanPabloDiaz you're assigned.
