### ISSUE TITLE
[OTHER]: "Saved" link redirects to home page

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2428]
### What would you like to share or ask?

On clicking the saved link in the header, it redirects to home page and then to `/saved` page.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Thanks for noticing @Jay-Karia. 
The link/button should remain disabled for now.

**Comment by drakeRAGE** [comment]
Hey, I want to contribute to this issue, can u assign this to me ?

**Comment by rupali-codes** [comment]
> Hey, I want to contribute to this issue, can u assign this to me ?

Sure, you're assigned, please let us know if you need any assistance.
