### ISSUE TITLE
[OTHER]: typo in sidebar item

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2430]
### What would you like to share or ask?

A typo in sidebar item: `Ai Tools`.
It should be `AI Tools`.

![typo links hub](https://github.com/user-attachments/assets/4d912fab-4a04-42c1-a1d6-88da8fcac01a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by tusharpasricha** [comment]
Hi, Please assign #2430 to me.

**Comment by rupali-codes** [comment]
> Hi, Please assign #2430 to me.

@tusharpasricha You're assigned. Please let us know if you need any assistance.
