### ISSUE TITLE
Add Indie UI

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [rupali-codes/LinksHub#2431]
### Site URL

https://ui.indie-starter.dev

### Description of the above provided site

A collection of beautifully designed UI components built with Tailwind CSS. 

### Category

Frontend

### Sub Category

Ui libraries

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Jay-Karia** [comment]
I am willing to work on this issue.
