### ISSUE TITLE
[BUG] invalid package name

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2436]
### Description

The package name used in `package.json` file does not follow naming conventions.

### Screenshots

![linkshub package](https://github.com/user-attachments/assets/7160bb32-bcf4-40c1-a383-32711d8e07ba)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@Jay-Karia thanks for noticing. We can change it to `linkshub`.

**Comment by Jay-Karia** [comment]
After #2443 #2444 
Can I work on this ?

**Comment by rupali-codes** [comment]
> After #2443 #2444 Can I work on this ?

sure.
