### ISSUE TITLE
[BUG] Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2439]
### Description

This issue is showed when the application is started for development.

### Screenshots

![issue links hub key](https://github.com/user-attachments/assets/36f54270-fec9-4cfd-800e-84b776a23370)

### Any additional information?

This issue could be fixed by adding an additional prop: `key` to the element.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@Jay-Karia where should we add the `key` prop?

**Comment by rupali-codes** [comment]
@Jay-Karia .

**Comment by Jay-Karia** [comment]
@rupali-codes, this error occurred due to missing `key` under `ul` elem, so there should be an `li` elem without `key` prop.

Still figuring this out, will let you know soon.

**Comment by Jay-Karia** [comment]
https://github.com/rupali-codes/LinksHub/blob/ffb79acfddbf62317c8d398637abda99cf84f00c/pages/index.tsx#L336-L337

I think the issue is caused to due to this code.
We can swap Line 337 and Line 336

**Comment by Jay-Karia** [comment]
I think I got it.
We just had to remove `React Fragment`: `<></>` from `renderLinks()` in the `Headers` page.
