### ISSUE TITLE
[Refactor] Duplicate Tailwind class names

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2442]
### File Name

pages/index.tsx

### Reason for Refactoring the Code

I can find multiple instances in this file where there is duplication of tailwind class names.

![duplicate 1](https://github.com/user-attachments/assets/b91e0142-3964-4da1-97d3-514fad3e5831)
![dup 2](https://github.com/user-attachments/assets/46efc667-d407-47dd-b3f0-3c66545674aa)

more duplicate classnames found in `pages/[category]/index.tsx`
![repeating](https://github.com/user-attachments/assets/4354a8e1-660f-42b9-a5c7-024ca3adbb79)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

**Comment by rupali-codes** [comment]
@Jay-Karia thanks Jay. For now, we are opening this issue for others to work, because you already have an issue assigned. When your current PRs gets merged/closed and nobody takes this issue, we will assign it to you.

**Comment by rupali-codes** [comment]
> @rupali-codes Can I get assigned this issue?

Sure, assigning it to you, please have a look at our [Contributing guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) and let us know if you need any assistance. Thanks.
