### ISSUE TITLE
[Add] CodeWithHarry

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2443]
### Site URL

https://www.youtube.com/@CodeWithHarry

### Description of the above provided site

An Indian youtuber with 6.4 million subs.
Videos about computer science (Python, Web Development, Java, C, AI, ...)

### Category

Youtube

### Sub Category

Computer Science

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@Jay-Karia we already have this under `YouTube/web development`. In `Computer Science` we are willing to add channels who focuses on academic courses. Although, you we can add a specific playlist from the channel if there's any.

**Comment by Jay-Karia** [comment]
This is a playlist which revises computer science concepts within 15 minutes (from CodeWithHarry).

https://youtube.com/playlist?list=PLu0W_9lII9ajkincuKn6f6tIk76l5Suqw&si=dt5XvS-s7Rn8TPcT

**Comment by Jay-Karia** [comment]
Can you assign me this issue ?
And #2444 ?
