### ISSUE TITLE
[Add] Theo.gg

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2444]
### Site URL

https://www.youtube.com/@t3dotgg

### Description of the above provided site

Founder of [ping.gg](https://ping.gg/), with 311K subs on youtube.
Makes videos about current news in web dev, reads and explains blog posts (on security, web dev, trends, news).
Also founder of [T3 stack](https://create.t3.gg/)

Main focus on Next.js, and ecosystem.

### Category

Youtube

### Sub Category

Web Development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by HenriqueDummer** [comment]
I am willing to work on this issue!

**Comment by rupali-codes** [comment]
@HenriqueDummer great to have you. Please don't forget to follow our contributing guidelines and let us know if you need any assistance.
