### ISSUE TITLE
[OTHER] Typo in sidebar 

### ISSUE THREAD

**Issue by A1josa** [rupali-codes/LinksHub#2445]
### What would you like to share or ask?

There is a typo in the side bar `Youtube` should be `YouTube` to follow proper naming documentation.

![YouTube](https://github.com/user-attachments/assets/73594a2f-4921-492b-8af7-f694caede10b)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@A1josa you're assigned. Please don't forget to read and follow our  [contributing guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md). Let us know if you need any kind of assistance.
