### ISSUE TITLE
[Refactor] Two class names with same css properties

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2447]
### File Name

components/Header/Header.tsx

### Reason for Refactoring the Code

Here the class names: `flex`and `hidden` applies the same CSS Properties.

![code](https://github.com/user-attachments/assets/15266ac8-8450-413a-82a2-dea8e776aeb6)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

**Comment by Jay-Karia** [comment]
I can contribute

**Comment by rupali-codes** [comment]
Its not redundant, its for mobile view to hide the top nav-links and show them on tablets/desk view.
