### ISSUE TITLE
[Refactor] Repeating Tailwind class names

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2448]
### File Name

pages/[category]/index.tsx

### Reason for Refactoring the Code

![repeating](https://github.com/user-attachments/assets/4354a8e1-660f-42b9-a5c7-024ca3adbb79)

There are couple of instances where the class names are getting repeated.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

**Comment by rupali-codes** [comment]
@Jay-Karia it seems duplicate of the issue #2442, could you please add these files in that issue and close this one?

**Comment by Jay-Karia** [comment]
Ok
