### ISSUE TITLE
[Refactor] Typo in Category page

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2449]
### File Name

pages/[category]/index.tsx

### Reason for Refactoring the Code

![typo](https://github.com/user-attachments/assets/cdb35f09-8901-4e92-ae9f-3918a17c2e02)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

**Comment by Jay-Karia** [comment]
@rupali-codes Can you assign me this issue

**Comment by rupali-codes** [comment]
@Jay-Karia you're assigned.
