### ISSUE TITLE
[Add] TechWithTim

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2451]
### Site URL

https://www.youtube.com/@TechWithTim

### Description of the above provided site

Youtuber with 1.55M subs.
Main focus on python, machine learning and AI

### Category

Languages

### Sub Category

Python

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

**Comment by rajneesh-18** [comment]
Do you want to work on this issue? @Jay-Karia

**Comment by Jay-Karia** [comment]
No

**Comment by Jay-Karia** [comment]
> Do you want to work on this issue? @Jay-Karia

Yes

**Comment by Jay-Karia** [comment]
@rajneesh-18 You can contribute here: #2431
