### ISSUE TITLE
[Add] GitHub Education

### ISSUE THREAD

**Issue by Jay-Karia** [rupali-codes/LinksHub#2456]
### Site URL

https://github.com/education/students

### Description of the above provided site

GitHub Student Developer gives best offers for students with free licenses to some of the best software, online course platforms and much more.

### Category

Other

### Sub Category

GitHub

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by tusharwebd** [comment]
Hi! I would like to work on this issue. Can you assign this to me?

**Comment by rupali-codes** [comment]
> Hi! I would like to work on this issue. Can you assign this to me?

you're assigned.

**Comment by rajneesh-18** [comment]
@tusharwebd are you working on this issue?
