### ISSUE TITLE
[OTHER] Add background color in the resource card in light theme

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2463]
### What would you like to share or ask?

The resource card have no background color on light theme.

![image](https://github.com/user-attachments/assets/62599af1-2774-4465-bac1-02e89263715b)

Add `light-gray` background color and a slight `border` same as the category page.

![image](https://github.com/user-attachments/assets/be0519ea-a0d0-4fc8-b1ea-03804e109920)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by AlexMutig** [comment]
I am new to open source projects and would like to work on this one

**Comment by rupali-codes** [comment]
@AlexMutig you're assigned, please do not forget to read & follow our [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md). Let us know if you need any assistance.
