### ISSUE TITLE
[BUG] Title header shifted below

### ISSUE THREAD

**Issue by Mani-mk-mk** [rupali-codes/LinksHub#247]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The title header in all section shifts below in the mobile view probably due to the addition of a new icon. I would like to work on this one 

### Screenshots

![image](https://user-images.githubusercontent.com/72310576/221347928-ff47b2f8-79fc-47f0-93fd-eb1b093b5a46.png)
![image](https://user-images.githubusercontent.com/72310576/221347933-5b70d7af-bacb-4c4b-b8f3-375b93bc45f8.png)

### What browser are you seeing the problem on?

Firefox, Chrome

**Comment by Mani-mk-mk** [comment]
cool

**Comment by zvolcsey** [comment]
@Mani-mk-mk Hi! That was an issue. #148 The display of long titles was wrong in mobile view, when the title and social icons was in the same line. To solve this problem I set `flex-col-reverse` in the mobile size. The breakpoint is now `md`, but the `sm` can be enough.
