### ISSUE TITLE
[Refactor] Erase `Youtube` category

### ISSUE THREAD

**Issue by GabrielBittar** [rupali-codes/LinksHub#2474]
### File Name

/database/youtube

## Changes proposed
Maybe we can think about dissolving `Youtube` Category, moving each of its links to the categories that fit each subject of each link that is in there.

## Reason
Users will most probably search content based on their interest subjects, like "design" or "frontend"... And Ytb is not a subject, it is one of the platforms from which we are taking content to insert inside those subjects.

## Example
See `Languages > C Programming > CodeWithHarry`. This link seems to be in the right place, though it doesn't, at the same time. It is a ytb link, so it could be inside `Youtube > WebDevelopment` as well and it would not be wrong. There are plenty of other cases that could illustrate this problem. It seems to me youtube channels should be all just like `CodeWithHarry`, in its repective section, and none inside a `Youtube` category.

I'm interested in working on it, if this change seems plausible.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [x] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

**Comment by Jay-Karia** [comment]
I am up for this change

**Comment by rupali-codes** [comment]
@GabrielBittar i think its gonna be a good practice. What about the links who don't have any category? are we going create new category and subcategory?

**Comment by GabrielBittar** [comment]
> @GabrielBittar i think its gonna be a good practice. What about the links who don't have any category? are we going create new category and subcategory?

Yes, this seems to be the best approach, creating the new cats/subs in those cases.
Since the issue looks alright, I intend to start working on this as soon as assigned.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please assign him if it's okay. This would be useful imo.

**Comment by rupali-codes** [comment]
@GabrielBittar you're assigned.

**Comment by GabrielBittar** [comment]
> @GabrielBittar you're assigned.

Ok! Thanks, I'll start working on it.

**Comment by GabrielBittar** [comment]
During work, found the unused `DSA` folder with `DSAYouTube.json`. Also found `Resources > dsa.json`. Total of 3 links. I took the liberty, to send these links to `data_structures > dsa_tutorials` and `data_structures > dsa_articles`, since there is ady this category for them. I'm communicating since this is not part of the discussed issue, so if you guys think this should not be done, please alert me so I don't send these changes.

**Comment by rupali-codes** [comment]
> During work, found the seemingly unused `DSA` folder with `DSAYouTube.json`. Also found `Resources > dsa.json`. Total of 3 links. I took the liberty to send these links to `data_structures > dsa_tutorials` and `data_structures > dsa_articles`, since there is ady this category for them. I'm communicating since this is not part of the discussed issue, so if you guys think this should not be done, please alert me so I don't send these changes.

Put them together in the same category but create different subcategory as mentioned :)

**Comment by vp007-dev** [comment]
Are you done @GabrielBittar ?

**Comment by GabrielBittar** [comment]
> Are you done @GabrielBittar ?

No, I'm working on it.

**Comment by vp007-dev** [comment]
Oh no problem
