### ISSUE TITLE
[Add] Syntax

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2475]
### Site URL

https://syntax.fm/

### Description of the above provided site

[Syntax](https://syntax.fm/) is a podcast about web development.

### Category

Other

### Sub Category

podcasts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@JuanPabloDiaz you're assigned.
