### ISSUE TITLE
[Add] The Junior Jobs Podcast

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2476]
### Site URL

https://podcasters.spotify.com/pod/show/junior-jobs/episodes/59--The-Problem-With-Changing-Careers-and-How-To-Overcome-It--Junior-Jobs-e2lnm9f

### Description of the above provided site

[The Junior Jobs Podcast](https://podcasters.spotify.com/pod/show/junior-jobs/episodes/59--The-Problem-With-Changing-Careers-and-How-To-Overcome-It--Junior-Jobs-e2lnm9f) is a weekly podcast about how junior developers can get their first job in tech, with Erik Andersen.

### Category

Other

### Sub Category

podcasts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by JuanPabloDiaz** [comment]
I can take it since I am done with Syntax PR

**Comment by rupali-codes** [comment]
> I can take it since I am done with Syntax PR

sure
