### ISSUE TITLE
[Add] Darknet Diaries

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2477]
### Site URL

https://darknetdiaries.com

### Description of the above provided site

[Darknet Diaries](https://darknetdiaries.com/) is a podcast about true stories from the dark side of the internet

### Category

Other

### Sub Category

podcasts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by ritesh-3** [comment]
Hi, I'd like to work on this !
