### ISSUE TITLE
[Add] Virtual Coffee

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2479]
### Site URL

virtualcoffee.io/podcast

### Description of the above provided site

[Virtual Coffee](https://virtualcoffee.io/) Virtual Coffee is an intimate community for developers at all stages of the journey. It is a place to ask questions, share knowledge, and build friendships.

### Category

Other

### Sub Category

podcasts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by ryo-kozin** [comment]
I noticed that this issue was created, and I'd be happy to work on it if needed. Please feel free to assign it to me whenever appropriate.

Thank you!

**Comment by Anmol-Baranwal** [comment]
@ryo-kozin 
You're assigned.
