### ISSUE TITLE
[Add] JSONing API

### ISSUE THREAD

**Issue by cyrilbois** [rupali-codes/LinksHub#2497]
### Site URL

https://jsoning.com/api/

### Description of the above provided site

JSONing (my website/project) is an open-source tool that enables to mock REST APIs using JSON file for prototyping.

### Category

Backend

### Sub Category

api

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekPatil45** [comment]
Please assign it to me so that i can open a PR
