### ISSUE TITLE
[Add] Want to add Finnhub Stock API  in backend category apis  section

### ISSUE THREAD

**Issue by Ajor-Saha** [rupali-codes/LinksHub#2499]
### Site URL

https://finnhub.io/

### Description of the above provided site

The  **Finnhub Stock API**  provides real-time financial data, including stock prices, company information, and market news. It offers access to global stock data, forex, cryptocurrency, and fundamental analysis. Developers can use this API to integrate financial data into applications for stock market tracking, portfolio management, or investment analysis. It also includes sentiment analysis, earnings reports, and insider transactions.

Please assign me to this issue, as I would like to contribute by adding the Finnhub API link to the **backend category apis subcategory.**

### Category

Backend

### Sub Category

APIs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@Ajor-Saha you're assigned, please let us know if you need any help.

**Comment by afrinashar** [comment]
I would like to work on this.
