### ISSUE TITLE
[Feature] changes `frontend > colors` to `design > color tools`

### ISSUE THREAD

**Issue by GabrielBittar** [rupali-codes/LinksHub#2501]
### Description

Maybe we should create a `color tools` section on `design` and send `frontend > colors` to it, erasing `frontend > colors` since now we have this separation between design and frontend.
I'm willing to work on this one, if it seems ok.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hey @GabrielBittar, it sounds nice, do you want to work on it?

**Comment by GabrielBittar** [comment]
> Hey @GabrielBittar, it sounds nice, do you want to work on it?

Yes, please :)

**Comment by rupali-codes** [comment]
@GabrielBittar you're assigned.
