### ISSUE TITLE
UI [BUG] <Query Parameters Displayed in Breadcrumbs for Specific Search Results>

### ISSUE THREAD

**Issue by gauravxroy** [rupali-codes/LinksHub#2504]
### Description

When users perform a search using the search bar in the application, the breadcrumb navigation reflects the API route or endpoint rather than the intended UI structure. Instead of displaying a user-friendly path breadcrumbs like > Home > Search > Ethers, the breadcrumbs show a format such as " Home > Search {query=endpoint} > Search Result". This inclusion of the API route or endpoint (enclosed in {}) in the breadcrumb navigation is not desirable and affects the user experience.

Steps to Reproduce: -
-Navigate to the search bar in the application.
-Enter a search query(like Ethers, Truffle) and execute the search(The issue is producing when we hit enter key in order to hit the search queries).
-Observe the breadcrumb navigation in the UI.

Suggested Methods/ways to resolve the Issues: 
1>UI State Management:
Ensure proper state updates for breadcrumbs, isolating them from API responses.
Implement a dedicated breadcrumb component to manage display logic.
2>Routing Configuration:
Review route definitions to prevent API parameters from appearing in breadcrumbs.
Use custom route handling to separate UI routes from API calls.
3>API Response Handling:
Keep API logic separate from UI logic to avoid affecting breadcrumb structure.
Transform API responses to exclude unnecessary parameters.

I want to address the issue with breadcrumb navigation to ensure it displays user-friendly paths instead of API endpoints.

### Screenshots

Current Breadcrumbs Behaviours :
![Screenshot 2024-09-26 102701](https://github.com/user-attachments/assets/9c5037ba-859f-48e2-9f90-986afdfd98fb)
![Screenshot 2024-09-26 102853](https://github.com/user-attachments/assets/d9ce6f47-abba-4494-8832-dcbf6e53b222)

Required Breadcrumbs Behaviour:
![Screenshot 2024-09-26 104714](https://github.com/user-attachments/assets/b9ec292b-e946-47d1-9aac-01c27e9cc3ab)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by heysolomon** [comment]
@rupali-codes I would like to work on this

**Comment by rupali-codes** [comment]
@gauravxroy do you want to work on this?

**Comment by gauravxroy** [comment]
> @gauravxroy do you want to work on this?

Absolutely, I'm excited to resolve this issue.

**Comment by rupali-codes** [comment]
> > @gauravxroy do you want to work on this?
> 
> @rupali-codes Absolutely, I'm excited to work on this issue.

Alright, assigning to you. 

And, @heysolomon, please have a look on other opened issues, since @gauravxroy wants to work on it so we'll assign the issue to them as per our Contributing guidelines.

**Comment by gauravxroy** [comment]
> > > @gauravxroy do you want to work on this?
> > 
> > 
> > @rupali-codes Absolutely, I'm excited to work on this issue.
> 
> Alright, assigning to you.
> 
> And, @heysolomon, please have a look on other opened issues, since @gauravxroy wants to work on it so we'll assign the issue to them as per our Contributing guidelines.

@rupali-codes  Thank you, Rupali. I will work on resolving this issue and close this as soon as possible.

**Comment by gauravxroy** [comment]
@rupali-codes Hey, Rupali Sorry for delay , due to some unexpected health issues i was not able to work on this issue but , now i will try to close this issue within week.

**Comment by rupali-codes** [comment]
Hi @gauravxroy, is there any update on this?

**Comment by gauravxroy** [comment]
@rupali-codes yes majority of work has been done , after analysing and improving written codes I will make a PR.
