### ISSUE TITLE
[ADD] <Adding the new subcategory(Java) in the Newsletter Category> 

### ISSUE THREAD

**Issue by akashchoudhary436** [rupali-codes/LinksHub#2505]
### Category Name

Newsletter

### Subcategory Name

Java

### Additional Context

There is only two subcategory in the newsletter i.e Python and Javascript so I want to add some links of Java Newsletter 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
hey @akashchoudhary436, which link do you wanna add?

**Comment by akashchoudhary436** [comment]
@rupali-codes 
I want to add a new Java catogery in the newsletter in that want to add this  links for java 
1) javabulletin : https://javabulletin.substack.com/
2) jetbrains : https://www.jetbrains.com/lp/jam/
3) baeldung : https://www.baeldung.com/library/java-web-weekly
4) microsoft : https://devblogs.microsoft.com/java/newsletter/

**Comment by rupali-codes** [comment]
@akashchoudhary436 alright assigning it you
