### ISSUE TITLE
[ADD] <JavaScript Kicks>

### ISSUE THREAD

**Issue by akashchoudhary436** [rupali-codes/LinksHub#2506]
### Category Name

Newsletter

### Subcategory Name

JavaScript

### Additional Context

Adding the newsletter link JavaScript Kicks in the javascript news letter 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@akashchoudhary436 please mention the resources you want to add.

**Comment by rupali-codes** [comment]
@akashchoudhary436 you're assigned. Please let us know if you need any help.
