### ISSUE TITLE
[Add] Hubdev

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2508]
### Site URL

https://www.hubdev.tools/

### Description of the above provided site

Resources for programmers!

✓ Free APIs, Databases and Hosting
✓ Programming logic challenges
✓ The best courses in Spanish
✓ Icons, fonts, illustrations

### Category

Open Source

### Sub Category

projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by rajneesh-18** [comment]
Assign this to me.
