### ISSUE TITLE
[Add] uptime-kuma

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2509]
### Site URL

https://github.com/louislam/uptime-kuma

### Description of the above provided site

https://uptime.kuma.pet

A self-hosted monitoring tool

### Category

Other

### Sub Category

dev tools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Arnav-2004** [comment]
Can I work on this?

**Comment by Arnav-2004** [comment]
> > Can I work on this?
> 
> If you are not currently work on any issue.

Okay @rajneesh-18, can you please assign this issue to me?

**Comment by rajneesh-18** [comment]
Okay, I'll assign it to you.
