### ISSUE TITLE
[Add] My First PR

### ISSUE THREAD

**Issue by JuanPabloDiaz** [rupali-codes/LinksHub#2510]
### Site URL

https://my-first-pr.github.io/

### Description of the above provided site

Helping first time contributors to make their first contribution. My First PR.

### Category

Open Source

### Sub Category

tools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by rajneesh-18** [comment]
Assign this to me
