### ISSUE TITLE
[OTHER] Create new subcategory Hacktoberfest

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2515]
### What would you like to share or ask?

Create a subcategory `Hacktoberfest` under `open-source` category. Also, add a highlighted _new_ tag on `open-source` category.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

**Comment by RJPalmer** [comment]
Good Morning,

I would like to work on this issue. I estimate it would take about 2 hours to update the list.

**Comment by rajneesh-18** [comment]
Assign to you @RJPalmer. If you have any doubt let me know.

**Comment by RJPalmer** [comment]
@rajneesh-18 

For the second task "add a highlighted new tag on open-source category", is the expectation to have the _new_ tag added whenever a category or subcategory has changed or just a one time instance of the _new_ tag?

**Comment by rupali-codes** [comment]
> @rajneesh-18
> 
> For the second task "add a highlighted new tag on open-source category", is the expectation to have the _new_ tag added whenever a category or subcategory has changed or just a one time instance of the _new_ tag?

It's just a one time instance
