### ISSUE TITLE
[BUG] delay in color change on scrollbar

### ISSUE THREAD

**Issue by dev-phantom** [rupali-codes/LinksHub#252]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

when changing from dark theme to light theme there's a delay in changing the color of the scroll bar

### Any additional information?

i can fix this issue

### What browser are you seeing the problem on?

Chrome

**Comment by rupali-codes** [comment]
Hi, @dev-phantom 
thanks for noticing. would you like to work on this?

**Comment by dev-phantom** [comment]
Sure I'd open a PR soon

**Comment by dev-phantom** [comment]
i also discovered the top bar  title has this same issue

**Comment by rupali-codes** [comment]
> i also discovered the top bar title has this same issue
> 
> @rupali-codes should i also fix that in the next issue

yes you can, but please keep them in seperate PRs

**Comment by dev-phantom** [comment]
i've fixed this issue 
just waiting for my recent PR to be merged before raising this

**Comment by Isha988** [comment]
@rupali-codes I want to work on this issue under gssoc program.

**Comment by rupali-codes** [comment]
> @rupali-codes I want to work on this issue under gssoc program.

Sure, please keep the PRs sperated as you are assigned other issues, or just work one issue at a time,

**Comment by milan-lakhani** [comment]
@rupali-codes @CBID2 This is a really old bug which can be resolved pretty easily. Can I take on this one?
