### ISSUE TITLE
[Feature] - Add more resources

### ISSUE THREAD

**Issue by ujjawaltyagii** [rupali-codes/LinksHub#253]
### Description

In Sub-section of Youtube, particularly in DSA section I found that resources are very less !
Like me being a dsa enthusiast I can suggest some really good and free resources to add under Dsa section

### Screenshots

![image](https://user-images.githubusercontent.com/115401171/221358638-8d29bc7e-b554-4e04-b00c-ab76d664dee5.png)

### Additional Information

It would be great if we add more resources of Dsa and I am looking forward to contribute in it.

**Comment by rupali-codes** [comment]
Hi @ujjawaltyagii,
Yes you can rise the PR for adding any kind of resources you would like to add

**Comment by ujjawaltyagii** [comment]
okay !!
