### ISSUE TITLE
[BUG] Searchbar with some problems when showing results for queries

### ISSUE THREAD

**Issue by GabrielBittar** [rupali-codes/LinksHub#2530]
### The issue
Searchbar is not working fine in some ways. The different problems are listed below (I was on the landing page while processing these searches), as I type the query and simply press `Enter`, thus passing a query:

1) Type "Offensive Security" or "C Programming", for example = opens up a search page with only a few links and with the search query rawly displayed in the place of the Category name. Also, the informations in the info button won't show any description on hover.
2) Type "Web Security" = a page with the description "Resources [...] Couldn't find what you're looking for? Feel free to seek
assistance in our Discord community." appears, also with the search query displayed in the place of the category and the info button won't display description on hover.
3) Type "javascript" = 404 not found (although there are many links with "javascript" on title)

Btw, for the seemingly right way: type "Authentication" ou "authentication" and see the results: this seems to be the right way to display them.

### Changes proposed
1) Fix the bugs described (info buttons, 404 for JS and search queries displaying on interface)"
2) I suggest we also start considering at least category name matches for the search, with results by category appearing after the results which matched by links. This would prevent cases like item 2 (Web Security), which really has no links with "web security" on title, but has a lot of links under this category, or like "Offensive Security", which shows only one link. Imo, it should show in order: A) Links matching the text typed on searchbar; B) Links under categories matching the text typed.

I'm interested in being assigned to work on this.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Thank you for noticing, assigning it to you, let me know if you need any help

**Comment by GabrielBittar** [comment]
> Thank you for noticing, assigning it to you, let me know if you need any help

Thanks, I'll start working on it now. Btw, also noticed `Design Color Tools` is without a description, from issue #2501 . I'll also fix it in this PR.
