### ISSUE TITLE
[Feature] Add a new tool link in Devtools category

### ISSUE THREAD

**Issue by joyfinder** [rupali-codes/LinksHub#2533]
### Description

Another useful tools I have been using for few years as a developer is HackMD. 

Hope it would benefit users in the community. 

### Screenshots

![Screenshot 2024-10-12 at 2 30 23 PM](https://github.com/user-attachments/assets/ba30ead2-af1c-46a9-806b-ed50015f803a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by joyfinder** [comment]
@rupali-codes 

Would you please assign this issue to me? 

Thank you.

**Comment by vp007-dev** [comment]
Are you still  working on this? If not can i do it? No worries if u are working on this issue

**Comment by vp007-dev** [comment]
> > Are you still working on this? If not can i do it? No worries if u are working on this issue
> 
> @vp007-dev
> 
> Already completed, and waiting for merge.
> 
> Thanks for asking.



oh no worries its just that your PR doesnt mention this issue (:
