### ISSUE TITLE
[Feature] Improve UI layout in LinksHub main page

### ISSUE THREAD

**Issue by joyfinder** [rupali-codes/LinksHub#2537]
### Description

As the picture illustrated below, texts are overflown at the right-handed side of both LinksHub Star & Fork columns, when viewing in a larger size of monitor. 

Fixing the columns' styles could improve the user experience of viewing LinksHub web page.

### Screenshots

![Screenshot 2024-10-12 at 2 14 49 PM](https://github.com/user-attachments/assets/f3644c61-635e-4ca6-9d40-927fe7ea52c0)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by joyfinder** [comment]
@rupali-codes 

Could you assign this task to me? 

Thank you.

**Comment by rupali-codes** [comment]
@joyfinder you're assigned.
