### ISSUE TITLE
[OTHER] Fix 'No links found' page in the search

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2545]
### What would you like to share or ask?

Align the content in centre

![image](https://github.com/user-attachments/assets/ad4bdaa0-c986-4540-9c12-5b7533155200)

For demo: [visit this](https://www.linkshub.dev/search?query=mnmnmmmmmm)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by ParamDhama** [comment]
Could you please assign this issue to me also tell me the file name where you created this component

**Comment by rajneesh-18** [comment]
> Could you please assign this issue to me also tell me the file name where you created this component

Did you locally setup the linkshub or not?

**Comment by ParamDhama** [comment]
Yeah i already setup

**Comment by rajneesh-18** [comment]
> Yeah i already setup

So you can find by yourself the filename.

**Comment by ParamDhama** [comment]
Okay i will try to find it and solve it

**Comment by ParamDhama** [comment]
# Is this what I had to do?
![image](https://github.com/user-attachments/assets/3e445144-e4b2-4ab0-9c4b-540e00f945fe)

**Comment by rajneesh-18** [comment]
> # Is this what I had to do? If yes then I will push my code
> ![image](https://private-user-images.githubusercontent.com/124657075/378938242-3e445144-e4b2-4ab0-9c4b-540e00f945fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDg5NzcsIm5iZiI6MTcyOTY0ODY3NywicGF0aCI6Ii8xMjQ2NTcwNzUvMzc4OTM4MjQyLTNlNDQ1MTQ0LWU0YjItNGFiMC05YzRiLTU0MGUwMGY5NDVmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTVlMGU1MzgyY2NkZDk0OWY2ZTZhZGExZjQ0N2YwODRhMDA0ODFiOGE2MzEyMzhhODY4NGE0YjgwZmYxYTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Rizx6At0QGpwvtRTU_Gplt2rLY3d0KlPkiubGJgMbLs)

@rupali-codes, check this out! It's similar to what you were looking for.

**Comment by rajneesh-18** [comment]
@ParamDhama assign this issue to you.
