### ISSUE TITLE
[Add] <Can I use: Support tables for HTML5, CSS3, etc.>

### ISSUE THREAD

**Issue by rajneesh-18** [rupali-codes/LinksHub#2547]
### Site URL

https://caniuse.com/

### Description of the above provided site

Can I use is a valuable web tool that helps developers check browser support for various web technologies, including CSS, HTML5, JavaScript, and APIs. It provides up-to-date compatibility data for different browsers and versions, helping developers ensure cross-browser functionality in their projects.

### Category

Other

### Sub Category

dev tools 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Deepak6204** [comment]
i would like to work on this issue, please assign this to e @rajneesh-18

**Comment by rajneesh-18** [comment]
Assign this issue to you @Deepak6204

**Comment by Deepak6204** [comment]
@rajneesh-18 i have created a pull request, you can merge and close this issue
