### ISSUE TITLE
[BUG] - Overflow of home page

### ISSUE THREAD

**Issue by ujjawaltyagii** [rupali-codes/LinksHub#255]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

In continuation of issue #161 : It seems that the overflow of landing page was fixed in the PR created in response to the issue but in case of sub-sections issue remain un-resolved causing screen to scroll even when there is no extra content so It would be great if this issue is resolved for remaining sections as well !

### Screenshots

https://user-images.githubusercontent.com/115401171/221360315-21c8d8ac-d2c4-453f-b382-cb774b5caadd.mp4

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by rupali-codes** [comment]
@ujjawaltyagii thanks 
should  we assign this to you?

**Comment by ujjawaltyagii** [comment]
@rupali-codes Sure !!

**Comment by rupali-codes** [comment]
@ujjawaltyagii second one is better i guess
