### ISSUE TITLE
[ADD] ETHICAL HACKING

### ISSUE THREAD

**Issue by sanika-d** [rupali-codes/LinksHub#2554]
### Category Name

ETHICAL HACKING

### Subcategory Name

'Cryptography Attacks', 'Social Engineering', 'Wireless Hacking', 'Malware and Payload Development'

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [ ] I am willing to work on this issue (optional)

**Comment by Deepak6204** [comment]
I am willing to work on this issue, can you please guide me with what i have to do actually @sanika-d 
do i have to search the web for platforms related to ethical hacking and add them or something else ?

**Comment by sanika-d** [comment]
@Deepak6204 I do not have the access to assign issues.

**Comment by Deepak6204** [comment]
@rajneesh-18 please assign this issue to me.

**Comment by rajneesh-18** [comment]
> Author

Wait, I will assign this to you @Deepak6204
