### ISSUE TITLE
[ADD] COMPUTER VISION

### ISSUE THREAD

**Issue by aditichavan11** [rupali-codes/LinksHub#2555]
### Category Name

Computer Vision

### Subcategory Name

'Overview of computer vision and its Applications', 'Image Processing & Transformation', 'Feature Extraction and Description', 'Deep Learning for Computer Vision'

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
HI @aditichavan11, you're assigned, let me know if you need any help
