### ISSUE TITLE
Cyber Securitiy

### ISSUE THREAD

**Issue by Vedashri0** [rupali-codes/LinksHub#2556]
### Category Name

Threat Intelligence

### Subcategory Name

'T3C by Global Cyber Alliance', 'Flare.io'

### Additional Context

In the Cyber Security Domain, Threat Intelligence is an essential field which was not avaible in the 'LinksHub'. Therefore, here is the new category under 'Cyber Security'. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hi @Vedashri0, you're assigned, let me know if you need any help
