### ISSUE TITLE
[ADD] CMS API & Toolkit

### ISSUE THREAD

**Issue by MustafaMunir123** [rupali-codes/LinksHub#2560]
### Category Name

CMS Toolkit

### Subcategory Name

'Headless CMS', 'Traditional CMS', 'PIM Support'

### Additional Context

I am planning to add free resources for CMS API & Toolkit.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by MustafaMunir123** [comment]
@Anmol-Baranwal Can I pick this up?
Thanks

**Comment by rupali-codes** [comment]
@MustafaMunir123 you're assigned, let me know if you need any help
