### ISSUE TITLE
[Add] <FlowCv website Link to Cover Letters>

### ISSUE THREAD

**Issue by VIJAYASRI-M** [rupali-codes/LinksHub#2564]
### Site URL

https://app.flowcv.com/dashboard

### Description of the above provided site

FlowCV is a resume-building platform that helps users create professional resumes, cover letters, and personal websites.It offers customizable templates, intuitive design tools, and easy export options. It’s ideal for job seekers looking for a streamlined, visually appealing approach to their applications.

### Category

Placement Prep.

### Sub Category

Cover Letters

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Kxiru** [comment]
I would be happy to work on this issue if OP is unavailable.
