### ISSUE TITLE
[ADD]  DevOps

### ISSUE THREAD

**Issue by Adibakhan14** [rupali-codes/LinksHub#2566]
### Category Name

DevOps

### Subcategory Name

Continuous Integration and Continuous Delivery (CI/CD), Infrastructure as Code (IaC), Monitoring and Logging, Configuration Management, Containerization and Orchestration

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [ ] I am willing to work on this issue (optional)

**Comment by sayyam267** [comment]
Hello, I would like to work on this issue

**Comment by rupali-codes** [comment]
@RJPalmer you're assigned. Please let us know if you need any help.

**Comment by Adibakhan14** [comment]
DevOps category by adding relevant subcategories demonstrates excellent attention to detail and domain expertise. Great work!
