### ISSUE TITLE
[ADD] ReactNative

### ISSUE THREAD

**Issue by HimanshuBari21** [rupali-codes/LinksHub#2577]
### Category Name

Mobile

### Subcategory Name

ReactNative

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hey @HimanshuBari21, please create a subcategory `reactnative` under `frontend` category. Please let us know if you need any help.

**Comment by HimanshuBari21** [comment]
Hey @rupali-codes Thank you for giving me this opportunity, I will start working on it ASAP!

Just need to ask, you sure to keep it in Frontend and not in Mobile?

**Comment by rupali-codes** [comment]
> Hey @rupali-codes Thank you for giving me this opportunity, I will start working on it ASAP!
> 
> Just need to ask, you sure to keep it in Frontend and not in Mobile?

Could you please suggest what else can we add in `mobile` category?

**Comment by HimanshuBari21** [comment]
No, React Native only for now !

**Comment by rupali-codes** [comment]
> No, React Native only for now !

Alright, lets create a separate category

**Comment by HimanshuBari21** [comment]
> Alright, lets create a separate category
Category is `Mobile`, In that I have added subcategory, that is `React Native`
