### ISSUE TITLE
[BUG] Search Functionality Not Working as Expected

### ISSUE THREAD

**Issue by JoshiUtsav** [rupali-codes/LinksHub#2579]
### Description

The search functionality in the "Frontend" section does not seem to be working correctly. When searching for specific terms (e.g., "frontend"), the results displayed are either incomplete, irrelevant, or not filtered as expected.

### Screenshots

![Screenshot 2024-12-02 184455](https://github.com/user-attachments/assets/09e637e8-ebf8-418d-a9e8-7f392bf595ed)

### Any additional information?

Improving the search functionality would enhance the usability and overall user experience of the application.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Thanks @JoshiUtsav.

**Comment by Bugbuster2004** [comment]
hey @JoshiUtsav i would like to contribute to this issue, is this issue already taken by someone? or can i contribute to this issue

**Comment by rupali-codes** [comment]
> hey @JoshiUtsav and @rupali-codes i would like to contribute to this issue, is this issue already taken by someone? or can i contribute to this issue and if yes then can u provide some more insights on this issue.
> 
> 1. like for example if i am searching frontend then what all results should be displayed and what is actually the bug as in screen shot we can see that it is rendering the details according to the "frontend" keyword.

Yes you're right, its showing the results based on the `frontend` keyword. @JoshiUtsav what should be the expected result according to you?

**Comment by Bugbuster2004** [comment]
hey @rupali-codes  i worked on the code and tried to fix it according to the code and the data u have in your file attaching the frontend screenshot below
![image](https://github.com/user-attachments/assets/f05a323f-4cc7-4ff6-af75-c40ad0d74692)
![image](https://github.com/user-attachments/assets/f75ba19c-c292-41a0-8f72-69a12bd3e75a)
this was not being rendered according to the issue, but i worked on the issue and it is now showing that

attaching your data file for reference
![image](https://github.com/user-attachments/assets/0a7f93a2-a749-4b80-876d-8efc05026574)

**Comment by rupali-codes** [comment]
@Bugbuster2004 does it work the same for all other categories?

**Comment by Bugbuster2004** [comment]
yes working @rupali-codes

**Comment by rupali-codes** [comment]
> yes working @rupali-codes

Alright, you can raise the PR. Thanks :)

**Comment by Bugbuster2004** [comment]
hey @rupali-codes, my PR is not passing to conventional checks because of some naming issue i tried to do it according to the guidelines but there is still some error could u pls help me in passing those checks

**Comment by Bugbuster2004** [comment]
hey @rupali-codes ig the pr passed all checks kindly review and let me know if there are any changes required

**Comment by Bugbuster2004** [comment]
hey @rupali-codes  any updates regarding the PR?
