### ISSUE TITLE
[Feature] Add favicon 

### ISSUE THREAD

**Issue by priyankarpal** [rupali-codes/LinksHub#258]
### Description

I think we can add the website's `favicon` by just adding this code in the JSOn files

> `"image":"https://website-name/favicon-link"`

Suppose we want to add `https://materialui.co/` favicon link. You can watch the video on how we can easily add.

https://user-images.githubusercontent.com/88102392/221398243-1b6cdb8a-a627-4940-b325-9e38f90307a8.mp4

in this way, we can add the link. 

### Screenshots

We can add the icon in this area.

![Group 1](https://user-images.githubusercontent.com/88102392/221398383-14853142-26fa-4907-ad5d-6174396b7df8.png)

**Comment by rupali-codes** [comment]
Hi, okay
but what if the site doesn't have favicons?

**Comment by priyankarpal** [comment]
> Hi, okay but what if the site doesn't have favicons?

we ca use any default icon.

**Comment by stupiddint** [comment]
can i work on it? @rupali-codes

**Comment by rupali-codes** [comment]
> can i work on it? @rupali-codes

Yeah of course

**Comment by priyankarpal** [comment]
> is there any source for different icons?

yes. every website has there own favicon. 
we need to store it in JSON and then fetch it.

**Comment by stupiddint** [comment]
yeah ok i will start doing this.

**Comment by stupiddint** [comment]
I made the requested changes. but i am unable to find Cubic Bezier favicon and Animate On Scroll has no favicon.
![Screenshot from 2023-03-20 22-14-40](https://user-images.githubusercontent.com/94122792/226411150-dd409567-61fb-4fbe-9bda-e3f63e2f64fd.png)

**Comment by priyankarpal** [comment]
> I made the requested changes. but i am unable to find Cubic Bezier favicon and Animate On Scroll has no favicon. ![Screenshot from 2023-03-20 22-14-40](https://user-images.githubusercontent.com/94122792/226411150-dd409567-61fb-4fbe-9bda-e3f63e2f64fd.png)

 Yes I noticed then need to add a default image or manually paste the website favicon by creating

**Comment by stupiddint** [comment]
I made the requested changes. and should i do the same to all the categories. can you help me finding default image for animate on scroll.
![Screenshot from 2023-03-20 23-59-28](https://user-images.githubusercontent.com/94122792/226433761-9954f566-a750-413a-8503-38115d14a42a.png)
and should i do the same to all the categories.

**Comment by priyankarpal** [comment]
what should be the default image @rupali-codes

**Comment by rupali-codes** [comment]
> what should be the default image @rupali-codes

LinksHub icon

**Comment by rupali-codes** [comment]
@stupiddint I guess the icon should be left aligned, at starting of the title

**Comment by stupiddint** [comment]
@rupali-codes how is this? I made the requested changes.
![image](https://user-images.githubusercontent.com/94122792/226533058-c9da19db-a4ce-4adf-a5af-5a53e32aa92d.png)

**Comment by priyankarpal** [comment]
looks good to me. one suggestion please increase the size of these icons.

**Comment by priyankarpal** [comment]
> I increased space from 0.25rem to 0.75rem ,and I also made changes to popup card. please review it! ![image](https://user-images.githubusercontent.com/94122792/226622538-985b90b3-53d2-47c4-88cb-3dd22c6142ee.png)

Looks Good 🎉

**Comment by stupiddint** [comment]
Thank you! i am making a pr then.
