### ISSUE TITLE
[ADD] Nest.js

### ISSUE THREAD

**Issue by HimanshuBari21** [rupali-codes/LinksHub#2588]
### Category Name

Backend

### Subcategory Name

Nest.js

### Additional Context

It's a Node.js + Express.js powered framework for Backend.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hey @HimanshuBari21, you're assiged.
