### ISSUE TITLE
[BUG] Title Header shifting down in mobile view.

### ISSUE THREAD

**Issue by pramodreddypandiri** [rupali-codes/LinksHub#260]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

In mobile view or small screen size title header is moving down.

### Screenshots

<img width="481" alt="image" src="https://user-images.githubusercontent.com/98374193/221403523-58d32335-12b0-4329-a498-a338a11ce2fe.png">

### Any additional information?

I will be working on it.

**Comment by zvolcsey** [comment]
@pramodreddypandiri Hi! That was an issue. https://github.com/rupali-codes/LinksHub/issues/148 The display of long titles was wrong in mobile view, when the title and social icons was in the same line. To solve this problem I set flex-col-reverse in the mobile size. The breakpoint is now md, but the sm can be enough.
![topbar](https://user-images.githubusercontent.com/41576384/221404242-873afbd6-0cdb-40d1-a52f-44d9a2670c81.png)
![topbar2](https://user-images.githubusercontent.com/41576384/221404243-ea1f3dc0-7c8f-4b5f-8d79-7607202851bd.png)

**Comment by rupali-codes** [comment]
@zvolcsey yeah, but how about if we decrease font size a bit? and then add truncate to it?

**Comment by pramodreddypandiri** [comment]
HOW ABOUT THIS  IN SMALL SCREEN
<img width="496" alt="image" src="https://user-images.githubusercontent.com/98374193/221405412-3b8e42fa-1473-4155-a47a-e69647548209.png">

**Comment by pramodreddypandiri** [comment]
@rupali-codes , truncate would not look nice i think

**Comment by rupali-codes** [comment]
> HOW ABOUT THIS IN SMALL SCREEN @zvolcsey and @rupali-codes <img alt="image" width="496" src="https://user-images.githubusercontent.com/98374193/221405412-3b8e42fa-1473-4155-a47a-e69647548209.png">

No, it looks weird, how about if we put icons in the sidebar itself or somewhere else?

**Comment by pramodreddypandiri** [comment]
@rupali-codes , darl/light mode icon should be visible on screen in any view. So I suggest , keep discord , github in footer and keep dark/light mode just left of hamburger menu.

**Comment by zvolcsey** [comment]
> @rupali-codes , darl/light mode icon should be visible on screen in any view. So I suggest , keep discord , github in footer and keep dark/light mode just left of hamburger menu.

That's cool. The social icons can appear below the logo in the sidebar and also in the footer.

**Comment by pramodreddypandiri** [comment]
What do you say @rupali-codes ?

**Comment by pramodreddypandiri** [comment]
i tried some things, @rupali-codes , @zvolcsey let me know how it is
# In normal view (large screen)
<img width="587" alt="Screenshot 2023-02-26 at 5 24 54 PM" src="https://user-images.githubusercontent.com/98374193/221408990-a0641ab7-86ef-46ed-a9ae-d67f26c5c886.png">
 # In small screen / mobile view
 
<img width="364" alt="Screenshot 2023-02-26 at 5 25 16 PM" src="https://user-images.githubusercontent.com/98374193/221409031-97abf774-1dc6-4d88-8e97-ce304ce38f3d.png">
# in mobile view when side bar is opened
<img width="445" alt="Screenshot 2023-02-26 at 5 24 29 PM" src="https://user-images.githubusercontent.com/98374193/221409062-ee0f8eaf-bc54-4d28-9669-4ec1c8acc850.png">

**Comment by pramodreddypandiri** [comment]
can i push these changes ? @rupali-codes 
@zvolcsey

**Comment by rupali-codes** [comment]
> can i push these changes ? @rupali-codes @zvolcsey

yes looks great

**Comment by pramodreddypandiri** [comment]
then you can see mr PR then @rupali-codes
