### ISSUE TITLE
[Description] Add description for Vue Js

### ISSUE THREAD

**Issue by NayanUnni95** [rupali-codes/LinksHub#2603]
### Category Name

Frontend

### Subcategory Name

Vue Js

### New or updated description of above subcategory

Vue.js is a flexible JavaScript framework for building user interfaces. It's easy to start with and can scale to complex applications.

### Status of Description

- [X] Adding new description
- [ ] Updating existing description

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
@NayanUnni95 you're assigned. let us know if you need any kinda help
