### ISSUE TITLE
[ADD] <Hindi Channel for Data Science/
https://youtube.com/@campusx-official?si=EY9EtnHN5XuLpvhU>

### ISSUE THREAD

**Issue by gauravgulia26** [rupali-codes/LinksHub#2607]

**Comment by rupali-codes** [comment]
@gauravgulia26 Please follow our [Contributing guideliens](https://github.com/rupali-codes/LinksHub/blob/02f66d8377a2baed4bda8e660c51714be5759928/CONTRIBUTING.md) and then recreate your issue.

Thank You
