### ISSUE TITLE
Kevin Powell channel

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#264]
### URL

https://www.youtube.com/@KevinPowell

### Description of the above provided site

It will give you idea about css. how to use css and many more things.

### Category

Frontend

### Sub Category

css

**Comment by rupali-codes** [comment]
> ### URL
> https://www.youtube.com/@KevinPowell
> 
> ### Description of the above provided site
> It will give you idea about css. how to use css and many more things.
> 
> ### Category
> Frontend
> 
> ### Sub Category
> css

Thanks,

**Comment by parma1111** [comment]
can you assign this issue to me

**Comment by rupali-codes** [comment]
> can you assign this issue to me

yes, sure

**Comment by parma1111** [comment]
I am getting this error why ,
Permission to rupali-codes/LinksHub.git denied to parma1111.
fatal: unable to access 'https://github.com/rupali-codes/LinksHub.git/': The requested URL returned error: 403

**Comment by parma1111** [comment]
fork repo
git clone ...
cd linkshub
I did changes
make branch
git add .
git commit -m "css-added"
git push origin <branch name>
then I get this error Permission to rupali-codes/LinksHub.git denied to parma1111.
fatal: unable to access 'https://github.com/rupali-codes/LinksHub.git/': The requested URL returned error: 403

**Comment by parma1111** [comment]
I fix this issue #264
![Screenshot (741)](https://user-images.githubusercontent.com/101566294/221424346-57470aeb-e002-4bb4-89b8-3c46e5a7d621.png)

**Comment by parma1111** [comment]
now it's done you can review
