### ISSUE TITLE
[BUG] items are displaying over the top bar when hovering

### ISSUE THREAD

**Issue by dev-phantom** [rupali-codes/LinksHub#269]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

when hovering over a subsection item while it on the top bar 
it displays over the top bar and makes it kinda look weird

### Screenshots

![image](https://user-images.githubusercontent.com/72051159/221431543-499cbe0c-7938-45ca-96b1-46049ae80ea4.png)

### Any additional information?

i can take on  this

### What browser are you seeing the problem on?

Chrome

**Comment by rupali-codes** [comment]
@dev-phantom thanks. assigning to you
