### ISSUE TITLE
[CHORE] add hover effect on sidebar elements

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#27]
The website currently does not have any hover effects on elements, this can make it less interactive and less engaging for users.

### Specific requirements
- This should add hover effect all sidebar elements
- This should be smooth (use transition property)
- The effect should include a background color change (make it light)

### Hints
As we are using [TailwindCSS](https://tailwindcss.com/docs/installation) and if you are new to it, don't worry just go through [this](https://tailwindcss.com/docs/hover-focus-and-other-states#hover)

**Comment by binadiegha** [comment]
Hi @rupali-codes , Is it okay if I work on this ?... I would like to pick up this task

**Comment by binadiegha** [comment]
https://user-images.githubusercontent.com/19647826/213037570-7670c28d-d0b7-4be7-bbed-5134889aba12.mov

Hey @rupali-codes 😃 I figured you have a lot on your plate and I had some free time so I went ahead and implemented it... with your go-ahead, I'd be happy to create my first opensource PR 😁🚀

**Comment by rupali-codes** [comment]
Hey, welcome to LinksHub! And Yes GO-AHEAD. Would love to see :)

**Comment by binadiegha** [comment]
Awesome! making that PR now
