### ISSUE TITLE
[Add] Dark Mode Design

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#271]
### URL

https://www.darkmodedesign.com/

### Description of the above provided site

Dark Mode Design is a showcase of beautifully designed and inspiring dark mode websites. Dim the lights, lower your screen brightness, and enjoy.

### Category

Frontend

### Sub Category

design inspiration

**Comment by Shiva-Sai-ssb** [comment]
@rupali-codes Can I work on this? If possible, assign me please.

**Comment by rupali-codes** [comment]
> @rupali-codes Can I work on this? If possible, assign me please.

yess sure, assigning to you

**Comment by Shiva-Sai-ssb** [comment]
> > @rupali-codes Can I work on this? If possible, assign me please.
> 
> yess sure, assigning to you

Thanks. I will do it.
