### ISSUE TITLE
[Add] Webframe

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#273]
### URL

https://webframe.xyz/

### Description of the above provided site

Discover and be inspired by beautiful webapp designs

### Category

Frontend

### Sub Category

design inspiration

**Comment by ujjawaltyagii** [comment]
if possible assign this issue to me or should i directly create PR for this ?

**Comment by rupali-codes** [comment]
> if possible assign this issue to me or should i directly create PR for this ?

yes you can. thanks
