### ISSUE TITLE
[BUG] Hide Home screen Title

### ISSUE THREAD

**Issue by Eugene44-hub** [rupali-codes/LinksHub#275]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The tilte on the Home Screen should be taken off

### Screenshots

![image](https://user-images.githubusercontent.com/75457464/221489175-763840a8-1cb6-446b-a3ff-1d99410811ba.png)

**Comment by Niralisj** [comment]
can i  work on this?

**Comment by rupali-codes** [comment]
> can i work on this?

yes thanks. assigning to you

**Comment by Niralisj** [comment]
> > can i work on this?
> 
> yes thanks. assigning to you

Okay! Thanks to you too.

**Comment by Pinaka-Pani-18** [comment]
Hi there,
this issue is cleared or not ?
I would like to work on this issue...

**Comment by Pinaka-Pani-18** [comment]
> 

Hi, can I solve this issue ?

**Comment by Pinaka-Pani-18** [comment]
> ### Is there any existing issue for this?
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Description
> 
> The tilte on the Home Screen should be taken off
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/75457464/221489175-763840a8-1cb6-446b-a3ff-1d99410811ba.png)
> ### Any additional information?
> 
> _No response_
> ### What browser are you seeing the problem on?
> 
> _No response_

Hi, I would like to work on this issue...
if possible can you assign me this issue...?

**Comment by Shiva-Sai-ssb** [comment]
> ### Is there any existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Description
> The tilte on the Home Screen should be taken off
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/75457464/221489175-763840a8-1cb6-446b-a3ff-1d99410811ba.png)
> 
> ### Any additional information?
> _No response_
> 
> ### What browser are you seeing the problem on?
> _No response_

Hii there, I have fixed this issue locally..
if possible can you assign me this issue?

**Comment by rupali-codes** [comment]
@Pinaka-Pani-18 & @Shiva-Sai-ssb this issue was assigned to @Niralisj. we appreciate your interest of contributing. Could you please look for some other issues?

**Comment by Shiva-Sai-ssb** [comment]
> @Pinaka-Pani-18 & @Shiva-Sai-ssb this issue was assigned to @Niralisj. we appreciate your interest of contributing. Could you please look for some other issues?

My apologies.. No problem I will look for other issues.

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 & @Shiva-Sai-ssb this issue was assigned to @Niralisj. we appreciate your interest of contributing. Could you please look for some other issues?

Ok sure @rupali-codes , I will look for another issue.

**Comment by shindodkar** [comment]
Hi I am new to open source contribution could you help me were to make changes(file) and some guidance to contribute my first project will be so  helpful to this start😊🙌

**Comment by rupali-codes** [comment]
> Hi I am new to open source contribution could you help me were to make changes(file) and some guidance to contribute my first project will be so helpful to this start😊🙌

It's great to have you, you can try looking for `good-first-issues`

**Comment by shindodkar** [comment]
Hm, I like your profile so I decided to work on search bar issue
