### ISSUE TITLE
[Add] <icons8>

### ISSUE THREAD

**Issue by jayk-gupta** [rupali-codes/LinksHub#278]
### URL

https://icons8.com/

### Description of the above provided site

Icons8 website provides icons, illustrations ,photos and design tools both in free and paid form.

### Category

Frontend

### Sub Category

"fonts", "icons", "images" ,"music","illustrations"

**Comment by rupali-codes** [comment]
Thank you Jay!

**Comment by jayk-gupta** [comment]
Can I work on this?

**Comment by rupali-codes** [comment]
> Can I work on this?

yes sure, assigning to you

**Comment by rupali-codes** [comment]
@jayk-gupta Don't you wanna work on it now?

**Comment by rupali-codes** [comment]
The issue has been resolved, thanks for closing though!

**Comment by jayk-gupta** [comment]
I have sent a PR for a youtube channel link, kindly review and merge it.
I haven't created an isuue for it, do I need to create it first?
