### ISSUE TITLE
[OTHER] Remove one discord link from README file

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#298]
### What would you like to share or ask?

Hi, I noticed that the Discord server link has added 2 times in the README file. 

Remove this 
![image](https://user-images.githubusercontent.com/78981177/222768684-f79d6dde-1eea-43be-a1aa-38ba6139df9c.png)

**Comment by CBID2** [comment]
> ### What would you like to share or ask?
> Hi, I noticed that the Discord server link has added 2 times in the README file.
> 
> Remove this ![image](https://user-images.githubusercontent.com/78981177/222768684-f79d6dde-1eea-43be-a1aa-38ba6139df9c.png)
> 
> ### Additional information
> _No response_

On it @rupali-codes! :) I need the practice anyway just in case I get to the contribution stage in Outreachy.

**Comment by CBID2** [comment]
> ### What would you like to share or ask?
> Hi, I noticed that the Discord server link has added 2 times in the README file.
> 
> Remove this ![image](https://user-images.githubusercontent.com/78981177/222768684-f79d6dde-1eea-43be-a1aa-38ba6139df9c.png)
> 
> ### Additional information
> _No response_

Hey @rupali-codes! 😄 I don't see the 2nd link you're referring to

**Comment by rupali-codes** [comment]
@CBID2 see before `Our contributors` section

**Comment by CBID2** [comment]
> @CBID2 see before `Our contributors` section
Here’s [my PR](https://github.com/rupali-codes/LinksHub/pull/320)
