### ISSUE TITLE
Sidebar content cut off on smaller screen

### ISSUE THREAD

**Issue by JoshHargreaves** [rupali-codes/LinksHub#30]
On mobile especially you cannot scroll to the bottom elements of the sidebar.

Is is also really hard to target the sidebar for scroll using touch.

![image](https://user-images.githubusercontent.com/20206340/213009886-4c8cf4db-8383-4960-bb72-a09d5311ed53.jpeg)

**Comment by Eugene44-hub** [comment]
> On mobile especially you cannot scroll to the bottom elements of the sidebar.
> 
> Is is also really hard to target the sidebar for scroll using touch.
> 
> ![image](https://user-images.githubusercontent.com/20206340/213009886-4c8cf4db-8383-4960-bb72-a09d5311ed53.jpeg)

It has been fixed now. You can check now if it's ok🙃

**Comment by rupali-codes** [comment]
Fixed that, thank you for noticing :)
