### ISSUE TITLE
[Add] Storyset

### ISSUE THREAD

**Issue by Aadarsh805** [rupali-codes/LinksHub#300]
### URL

https://storyset.com/

### Description of the above provided site

Free illustrations that are customizable, animatable, and available free to download

### Category

Frontend

### Sub Category

Illustrations

**Comment by priyankarpal** [comment]
can I work on this issue?

**Comment by priyankarpal** [comment]
It's already added by someone :)

**Comment by rupali-codes** [comment]
> It's already added by someone :)

i see

**Comment by jayk-gupta** [comment]
Please close this issue as it is being resolved.
