### ISSUE TITLE
[Add] <Hackernoon>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#312]
### URL

https://hackernoon.com/

### Description of the above provided site

This is a platform where developers and technologists from all walks of life write blog posts about their experiences in tech. 

### Category

Frontend

### Sub Category

"Resources",
"Blogs"

**Comment by ujjawaltyagii** [comment]
I would like to work on this as I am trying to cover all Open Issues with request to add new resource/links in 1 PR, so It would be great if you "assign" this to me.
