### ISSUE TITLE
thenewboston,Web Dev Simplified

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#315]
### URL

https://www.youtube.com/@thenewboston

### Description of the above provided site

https://www.youtube.com/@thenewboston
https://www.youtube.com/@WebDevSimplified

### Category

Frontend

### Sub Category

category - youtube
sub Category - web development

**Comment by parma1111** [comment]
can I take this issue ?

**Comment by rupali-codes** [comment]
> can I take this issue ?

yeah sure, assigning to you

**Comment by parma1111** [comment]
now you can review my PR
