### ISSUE TITLE
Add ColorHunt to the colours panel

### ISSUE THREAD

**Issue by templar-command0** [rupali-codes/LinksHub#318]
### Description

Colorhunt.co is also a cool site to get inspired for colours, check it out and add it to this linkshub.

### Screenshots

![DC28D460-2A91-45CC-8AD1-03B91FADA190](https://user-images.githubusercontent.com/100400299/223314317-f8f01fb2-1c8c-4a93-93b5-6135a3dcc511.png)

**Comment by rupali-codes** [comment]
thanks, would u like to work on this?

**Comment by jayk-gupta** [comment]
Can I work on this?

**Comment by templar-command0** [comment]
Yes I will work on it, thanks😄

**Comment by templar-command0** [comment]
@rupali-codes I've made a pull request with Color Hunt added in the database
