### ISSUE TITLE
Spline

### ISSUE THREAD

**Issue by darkweb907** [rupali-codes/LinksHub#327]
### URL

https://spline.design/

### Description of the above provided site

Spline is an easy to use 3D design tool geared for any designer regardless of their 3D experience.

### Category

Frontend

### Sub Category

Animation

**Comment by rupali-codes** [comment]
thanks, would u like to take this?

**Comment by darkweb907** [comment]
Yes

**Comment by jayk-gupta** [comment]
Is this issue resolved?

**Comment by rupali-codes** [comment]
> Is this issue resolved?

Yes

**Comment by rupali-codes** [comment]
@darkweb907 as there is no updated from you, we are assigning this issue to @jayk-gupta

**Comment by darkweb907** [comment]
This issue is solved

**Comment by rupali-codes** [comment]
Thanks 😅

**Comment by jayk-gupta** [comment]
okay, I was just checking if it was resolved or not.
