### ISSUE TITLE
[Feature] Add LinksHub description in hero section

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#331]
### Description

By adding a description of What LinksHub is, and it does, will make it easy for users to understand LinksHub better.

Add this description below the logo 

> LinksHub aims to provide developers with access to a wide range of free resources and tools that they can use in their work. These resources include links to free software, libraries, frameworks, and other tools that can be used to build and deploy applications and websites.

### Screenshots

![image](https://user-images.githubusercontent.com/78981177/223967767-9843b71f-2f60-44ab-a7bf-aa7c65104246.png)

**Comment by CBID2** [comment]
I'll do it @rupali-codes! 😃

**Comment by rupali-codes** [comment]
> I'll do it @rupali-codes! 😃

Thanks Chrisssy

**Comment by CBID2** [comment]
Can you add the link to the file that I need to work on @rupali-codes?

**Comment by CBID2** [comment]
> Here you go https://github.com/rupali-codes/LinksHub/blob/main/pages/index.tsx

Thanks, @rupali-codes! 😄 Here's my [PR](https://github.com/rupali-codes/LinksHub/pull/336). Let me know if any changes are needed! 👍🏾
