### ISSUE TITLE
[Feature] <Added web dev simplified channel>

### ISSUE THREAD

**Issue by jayk-gupta** [rupali-codes/LinksHub#332]
### Description

I have sent a PR for adding web dev simplified channel in the youtube resources.
Kindly review and merge it.

**Comment by ujjawaltyagii** [comment]
@jayk-gupta if possible then kindly attach that PR with this issue so when PR is merged the issue will be closed.
In order to do that add ``#Issuenumber`` in your PR description.(Or for minor changes like adding resources you can directly create PR without creating Issue)

**Comment by jayk-gupta** [comment]
okay
This is my second PR in this repo, but as it wasn't merged so I thought that may be first I need to create an issue.

**Comment by Deva-1903** [comment]
Hi, @jayk-gupta Your PR will be reviewed and mergedYou don't need to create an issue to merge a PR, just be patient. Kindly close this issue.
