### ISSUE TITLE
[Feature] Adding a Bot

### ISSUE THREAD

**Issue by ujjawaltyagii** [rupali-codes/LinksHub#339]
### Description

As being a active contributor, I think we should now have a bot for managing the assigning of issues and managing PRs as I see that we have got  a lot of active contributors so instead of waiting after asking for "assigning a issue" what if 
- we just write #claim and if issue isn't assigned to anyone then the issue will be assigned
- second, if someone has been assigned a issue but he/she isn't active for let's say 1 week then the bot will un-assign the issue and make it available for other contributors to work on it.
- and in same manner we can have many more things sorted which will make things easier for both <b>contributors</b> and @rupali-codes  as It will make whole process a lot faster and efficient.

It would save a lot of time and also one more thing, I observed that many contributors were upset with long waiting time after opening a PR as late responses on PR-merge so if somehow we could <b>reduce that waiting time so if PR is fine it will merge quickly or if PR have some issue then they will get to know ASAP</b>

What do you think about it ? @zvolcsey @CBID2 @rohitdasu

**Comment by CBID2** [comment]
I approve! :)

**Comment by priyankarpal** [comment]
yes @ujjawaltyagii we can add github actions such as greetings for first-timers, stale issues checker, dependabot etc.

**Comment by rupali-codes** [comment]
@ujjawaltyagii that's a nice idea. I like it. So are you willing to work on this?
