### ISSUE TITLE
[Feature] Add sites and other resources for each technology

### ISSUE THREAD

**Issue by jayk-gupta** [rupali-codes/LinksHub#341]
### Description

We can add websites for learning each technology like html, css etc. seperately in the resources section.

**Comment by rupali-codes** [comment]
yeah we can, are you talking about video resources or blog posts?

**Comment by jayk-gupta** [comment]
I am saying to add "websites" for various techs.
For example for javascript we can have:
1. Mdn Docs
2. javascript info
3. javascript tutorial net and so on...
Similarly for other technologies
Did you understood?

**Comment by rupali-codes** [comment]
Yes i got it, thanks
So we are creating a new category named `other` in that category we can subcategories like `javascript` `python` etc. where we can add these resources

**Comment by jayk-gupta** [comment]
okay!
I would like to add resources for frontend languages, kindly assign it to me when category is made.

**Comment by rupali-codes** [comment]
> okay! I would like to add resources for frontend languages, kindly assign it to me when category is made.

sure

**Comment by ujjawaltyagii** [comment]
@rupali-codes i can add sub-category for above mentioned languages so you can assign this to me (will start working on it after my current PR gets merged - it just need on more approval review :) )

**Comment by rupali-codes** [comment]
> @rupali-codes i can add sub-category for above mentioned languages so you can assign this to me (will start working on it after my current PR gets merged - it just need on more approval review :) ) edit - @jayk-gupta will let you know when i am done with the addition of sub-categories !

Which subcategory you're talking about?

**Comment by rupali-codes** [comment]
> @rupali-codes ![image](https://user-images.githubusercontent.com/115401171/227262609-3457637a-56b4-4eef-aaa8-1cd1c1d900fd.png)

Oh, yeah we have now added `other` category, assigning to you
