### ISSUE TITLE
[Add] Online Tutorials

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#345]
### URL

https://www.youtube.com/@OnlineTutorialsYT/featured

### Description of the above provided site

It will give you more idea about in CSS. OnlineTutorials will explain everything in depth about CSS.

### Category

Frontend

### Sub Category

CAT = Youtube
SUBCAT = CSS

**Comment by parma1111** [comment]
Can I add this category in CSS

**Comment by rupali-codes** [comment]
> Can I add this category in CSS

yes sure
