### ISSUE TITLE
[Feature] Add more categories

### ISSUE THREAD

**Issue by koodeau** [rupali-codes/LinksHub#347]
### Description

Would be nice to have dev tools category and maybe a collection of useful cheatsheets (like Vim commands) on the website

### Additional Information

Some examples of useful dev tools for both frontend and backend devs:
- Postman
- iTerm (for Mac users)
- Docker
- VSCodium (open-source fork of VSCode)
- Obsidian (something like Notion, seen it being used by other developers but I haven't used it much)

I have more resources to share later!

**Comment by ujjawaltyagii** [comment]
@rupali-codes I would like to work on it so you can assign this issue to me and also please do let me know what would you like me to name "Main category", "Sub category" and "section name". Also @koodeau you can add some resource links here so i will add them while creating section (It will save a lot of time)

**Comment by CBID2** [comment]
> @rupali-codes I would like to work on it so you can assign this issue to me and also please do let me know what would you like me to name "Main category", "Sub category" and "section name". Also @koodeau you can add some resource links here so i will add them while creating section (It will save a lot of time)

> That's a nice idea, would you like to work on this?

Hey @rupali-codes! 😄 I assigned this issue to @ujjawaltyagii. I hope you don't mind.

**Comment by rupali-codes** [comment]
> @rupali-codes I would like to work on it so you can assign this issue to me and also please do let me know what would you like me to name "Main category", "Sub category" and "section name". Also @koodeau you can add some resource links here so i will add them while creating section (It will save a lot of time)

Hey, i guess we can add this under `Other` category and create a new Subcategory named `Dev Tools`

**Comment by ujjawaltyagii** [comment]
okay !
