### ISSUE TITLE
DesignCourse

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#351]
### URL

https://www.youtube.com/@DesignCourse/featured

### Description of the above provided site

This channel is great for learning css and frontend.
It will give you paid css course 

### Category

Frontend

### Sub Category

cat = youtube
subcat = css

**Comment by parma1111** [comment]
Can I raise a PR for this ?

**Comment by rupali-codes** [comment]
> Can I raise a PR for this ?

yes sure
