### ISSUE TITLE
[Add] Freepik website inside Illustration

### ISSUE THREAD

**Issue by Vijaykv5** [rupali-codes/LinksHub#354]
### URL

https://www.freepik.com/

### Description of the above provided site

Add this Site as a Card inside Illustrations under Frontend

### Category

Frontend

### Sub Category

Add a link of it in the card

**Comment by Vijaykv5** [comment]
Can You assign me . I shall add it

**Comment by CBID2** [comment]
> Can You assign me . I shall add it

Done @Vijaykv5 👍🏾

**Comment by parma1111** [comment]
This issue is completed or not , if not done then Can I RAISE A PR for it

**Comment by jayk-gupta** [comment]
I think this issue hasn't been resolved.
Can I work on it?

**Comment by parma1111** [comment]
ok I will do it

**Comment by jayk-gupta** [comment]
okay
