### ISSUE TITLE
Ionicons

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#355]
### URL

https://ionic.io/ionicons/v4

### Description of the above provided site

Ionicons is a great website that will give a lot Premium designed icons for use in web, iOS, Android, and desktop apps. Support for SVG and web font. Completely open source, MIT licensed and built by the [Ionic Framework](https://ionicframework.com/) team

### Category

Frontend

### Sub Category

cat = frontend
subcat = Icons

**Comment by CBID2** [comment]
> Can I raise a PR for it ?

Sure!

**Comment by parma1111** [comment]
Ok , I will create the PR.
