### ISSUE TITLE
[Feature] Add copy link to clipboard button

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#362]
### Description

Hey, I just noticed that adding `copy link to clipboard` would be a great user experience, as user will be able to copy the link share among their friends without opening it.

### Specific Requirements
* Add `copy to clipboard` icon beside title in the card on the right side
* Also, add the icon in `popup` on the right side
* When clicked on the icon, the link of the respective resource should be copied to user's clipboard

### Screenshots

**For Card**

![image](https://user-images.githubusercontent.com/78981177/226280188-bd139a2e-fcf2-400c-8c26-72ccb60a24e6.png)

**For popup**

![image](https://user-images.githubusercontent.com/78981177/226280285-cdf5e7b5-b5f7-4746-9545-c26eea1e55ce.png)

**Comment by sloth30799** [comment]
Can I work on this?

**Comment by rupali-codes** [comment]
> Can I work on this?

Yeah sure!
