### ISSUE TITLE
[Add] Page Flows

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#370]
### URL

https://pageflows.com/

### Description of the above provided site

The smarter way to research user interface flows, screen, and email best practices and get unstuck by learning from proven products.

### Category

Frontend

### Sub Category

design inspiration

**Comment by rupali-codes** [comment]
thank you

**Comment by parma1111** [comment]
Can you assign these issue #371 & #370

**Comment by parma1111** [comment]
> thank you

Rupali can you remove this issue from here, because this has been added in the project, I am not being able to remove it from here.
