### ISSUE TITLE
[Add] Design Vault

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#371]
### URL

https://designvault.io/

### Description of the above provided site

Looking for inspiration for your next project? Unleash your creativity by exploring an ever-growing collection of designs and common user interface patterns from the world’s best products and designers.

### Category

Frontend

### Sub Category

design inspiration

**Comment by rupali-codes** [comment]
Thanks

**Comment by Oyebolade** [comment]
My pleasure

**Comment by parma1111** [comment]
Can you assign these issue #371 & #370
