### ISSUE TITLE
chore: migrate to yarn

### ISSUE THREAD

**Issue by priyankarpal** [rupali-codes/LinksHub#372]
### Description

Currently, in this project, we are using `npm` so it's better to switch to `yarn`

- Yarn is often faster than another similar tool called npm, and can make it easier to manage complex projects with lots of dependencies.

I already did it. Just need to create a PR.

**Comment by thejus-r** [comment]
I think its better to user pnpm than yarn.. right?

**Comment by priyankarpal** [comment]
> I think its better to user pnpm than yarn.. right?

Yeah. We can do it too. What's your thought? @rupali-codes

**Comment by rupali-codes** [comment]
Hey, yeah I would also prefer pnpm over yarn or npm

**Comment by priyankarpal** [comment]
> Hey, yeah I would also prefer pnpm over yarn or npm

ok done. Just created the PR please check. Hope it will work.
