### ISSUE TITLE
[BUG] Link is being rendered twice.

### ISSUE THREAD

**Issue by sonylomo** [rupali-codes/LinksHub#396]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The [Screenlane](https://screenlane.com/) link is being rendered twice. I want to fix this. 🙂

### Screenshots

<img width="1251" alt="Screenshot 2023-04-06 at 3 17 49 PM" src="https://user-images.githubusercontent.com/49971500/230392680-e3755c66-3f0a-4603-9479-e39b92532da0.png">

### What browser are you seeing the problem on?

Chrome
Safari

**Comment by rupali-codes** [comment]
Yes you can,
