### ISSUE TITLE
[FEATURE] add light and dark mode to the site

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#4]
Add light & dark mode to the site, and it should have a switchable button.
 
Use the following package to implement it:
https://www.npmjs.com/package/next-themes

**Comment by c00kie123** [comment]
Hello, I can try working on this! You can assign it to me

**Comment by rupali-codes** [comment]
Hi @c00kie123, thanks for taking interest, yes you can start working and create pull request. Let us know for any kind of help.

**Comment by c00kie123** [comment]
Hey, thanks for assigning! 
I would like to ask where would you like this button to be located at? 
Also, do you want me to just follow the link you have given?

**Comment by rupali-codes** [comment]
Hi, you can place this at bottom-left corner, make sure that the background is dark or blurred

**Comment by c00kie123** [comment]
Do I make the changes at Sidebar.tsx?

**Comment by rupali-codes** [comment]
alright, can u place it top-right corner? create a new component, and put it into MainContainer dir. You can name it TopBar

**Comment by rupali-codes** [comment]
@c00kie123 are you still working this? any updates?

**Comment by c00kie123** [comment]
Hey, I will try it this week! Else, you can assign it to another person.

**Comment by rupali-codes** [comment]
Ahhmmm okay
@AdekeyeAdeniyi or @hparashar27 would you like to work on this?

**Comment by hparashar27** [comment]
sure , i can try

**Comment by rupali-codes** [comment]
@hparashar27 thank you, good luck, and feel free to ask for help if needed

**Comment by hparashar27** [comment]
hey @rupali-codes , i want to ask that the theme changing feature is for ListContainer only or is for whole ,including sidebar ?

**Comment by rupali-codes** [comment]
for the whole side, including sidebar

**Comment by hparashar27** [comment]
@rupali-codes   I tried it but it is not working properly , so you can assign to someone else

**Comment by rupali-codes** [comment]
we can help u, if u have any issues

**Comment by gangadharbenni** [comment]
@rupali-codes Hi can take this ?

**Comment by AdekeyeAdeniyi** [comment]
Can I work on this?

**Comment by rupali-codes** [comment]
yes you both @AdekeyeAdeniyi  & @gangadharbenni  can start working on this :)

**Comment by gangadharbenni** [comment]
@rupali-codes created pull request pls have a look https://github.com/rupali-codes/LinksHub/pull/59

**Comment by AdekeyeAdeniyi** [comment]
I just notice the issues have been fixed.
