### ISSUE TITLE
[Add] UXArchive

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#401]
### URL

https://uxarchive.com/

### Description of the above provided site

UX-Archive is powered by Waldo, the world’s first no-code testing platform that lets anyone create reliable, automated mobile tests without the hassle of scripting.

### Category

Frontend

### Sub Category

design inspiration

**Comment by rupali-codes** [comment]
Thanks

**Comment by Divyansh-0** [comment]
Can i do it?

**Comment by rupali-codes** [comment]
> Can i do it?

Sure

**Comment by Divyansh-0** [comment]
I have made a PR that will resolve this #410

**Comment by rupali-codes** [comment]
> I have made a PR that will resolve this #410

Hey, thanks

**Comment by Divyansh-0** [comment]
I made a new PR sorry i am new to this open source setup i ended up closing my old PR. New #436

**Comment by Divyansh-0** [comment]
#441 done now
