### ISSUE TITLE
[BUG] <div> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by zvolcsey** [rupali-codes/LinksHub#405]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

There is an error message in development mode. `TypeWriter Component` returns a `div`. This `div` is inside a `p` tag.

### Screenshots

![console_error](https://user-images.githubusercontent.com/41576384/230616146-1e7998a2-9442-451e-8bc1-c7156666aed5.png)

### What browser are you seeing the problem on?

Chrome

**Comment by rupali-codes** [comment]
hey @zvolcsey thanks for pointing this out!
