### ISSUE TITLE
[Enhancements]

### ISSUE THREAD

**Issue by JA-26-01** [rupali-codes/LinksHub#409]
### What would you like to share or ask?

I was exploring the website and I would like to suggest some trivial changes - which I feel will improve the overall UI/UX 

1.  Alignment of items - aligning the cards to the center will be a better visual experience , the space on the right creates an unnecessary void

![image](https://user-images.githubusercontent.com/108082336/230716877-b9400749-14be-4f78-a6dd-9c12a655796d.png)

2.  Github, twitter , etc. can be opened up on a new page - As of now, on clicking any of the links, they load in the site itself. Creating a new window for them will be better.

3.  Not found message - when a search query does not exist, a message regarding the same can be displayed

![image](https://user-images.githubusercontent.com/108082336/230716996-a0862372-4ce4-4496-9be0-66abab248b6a.png)

4.  For topics which do not have any content as of now, the "coming soon" message is displayed. I think it will be better to display the message in the center of the frame rather than the corner, and also preferably in a bigger font and some animations - like the one which appears when one reaches the bottom of the screen. Also, making the entire text flicker instead of just the first word will be prettier, but let me know what you think :)

**Comment by rupali-codes** [comment]
Hey @JA-26-01 thank you so much for the suggestions

**Comment by JA-26-01** [comment]
Hey @rupali-codes  my pleasure. If you don't mind should I start working on some of these?

**Comment by MadhuMPandurangi** [comment]
hey @JA-26-01 @rupali-codes can I work on this?
I cloned and tried working don't this. I got the following output. My bad @JA-26-01,I didn't see your comment. If you are ok then I'll continue.

![image](https://user-images.githubusercontent.com/27917751/230755556-97df13b8-3736-4e8e-9a7e-42ac372022c7.png)

**Comment by JA-26-01** [comment]
Ya okay @MadhuMPandurangi you are trying the 1st one right I will start off with the others.

**Comment by MadhuMPandurangi** [comment]
@JA-26-01 first one is done. 
regarding the second point, it opens in a separate tab upon clicking on GitHub or any other links. Not in the same tab.

**Comment by rupali-codes** [comment]
> @JA-26-01 first one is done. regarding the second point, it opens in a separate tab upon clicking on GitHub or any other links. Not in the same tab.

Yeah it's already opening links in new tab

**Comment by rupali-codes** [comment]
> hey @JA-26-01 @rupali-codes can I work on this? I cloned and tried working on this issue. I got the following output. My bad @JA-26-01,I didn't see your comment. If you are ok then I'll continue.
> 
> ![image](https://user-images.githubusercontent.com/27917751/230755556-97df13b8-3736-4e8e-9a7e-42ac372022c7.png)

Can we align this cards to left? like the parent container would be in center and it's items would be left aligned

**Comment by MadhuMPandurangi** [comment]
you are telling that the last card should be displayed in first column

**Comment by MadhuMPandurangi** [comment]
hey @rupali-codes Is this ok?
![image](https://user-images.githubusercontent.com/27917751/230758344-273157c8-3d21-4e9a-9afd-c58c7fae006d.png)

**Comment by JA-26-01** [comment]
@MadhuMPandurangi @rupali-codes  for me it opens in the same tab

**Comment by JA-26-01** [comment]
@rupali-codes I re-aligned the coming soon part I think it looks better now. Have a look!

![image](https://user-images.githubusercontent.com/108082336/230769176-1c4a2470-006d-4b85-bc9b-2a2f3980c909.png)

**Comment by rupali-codes** [comment]
@JA-26-01 looks good, but i'd be better if we can replace the message with 
_Be the first to add by creating a GitHub issue [here](https://github.com/rupali-codes/LinksHub/issues/new?assignees=&labels=add+link&template=add_link.yml&title=%5BAdd%5D+%3Cname%3E)_

**Comment by JA-26-01** [comment]
Oh okay great! I will make the changes and get back here

**Comment by JA-26-01** [comment]
@rupali-codes how about this?

![image](https://user-images.githubusercontent.com/108082336/230933001-a2940e83-9068-4021-a367-8e533dc2bbd1.png)

**Comment by JA-26-01** [comment]
Also, could you help me out to locate where is the main div for displaying the cards located. I feel a little lost hehe. I would like to try to align those.

**Comment by rupali-codes** [comment]
> Also, could you help me out to locate where is the main div for displaying the cards located. I feel a little lost hehe. I would like to try to align those.

Sure, it's under `components/Cards/CardsList.jsx` also you can review the PR #412

**Comment by rupali-codes** [comment]
> @rupali-codes how about this?
> 
> ![image](https://user-images.githubusercontent.com/108082336/230933001-a2940e83-9068-4021-a367-8e533dc2bbd1.png)

Looks better, go ahead and create the PR
