### ISSUE TITLE
[BUG] GitHub actions not working

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#413]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

GitHub actions are not working for some reason, it was supposed to send an alert message when any new contributor creates their first Issue or Pull request.

**Comment by Dun-sin** [comment]
does it not work at all or not does it show an error?

**Comment by rupali-codes** [comment]
> does it not work at all or does it show an error?

It doesn't show any error, but not displaying alert messages too

**Comment by Dun-sin** [comment]
> > does it not work at all or does it show an error?
> 
> It doesn't show any error, but not displaying alert messages too

I found the problem, it actually works fine, you used an echo which is console.log for ci
it needs to be changed, can i work on it?
![image](https://user-images.githubusercontent.com/78784850/230763289-a211e58b-5de0-43e7-b2a6-6d27eee6ae37.png)

**Comment by rupali-codes** [comment]
> > > does it not work at all or does it show an error?
> > 
> > 
> > It doesn't show any error, but not displaying alert messages too
> 
> I found the problem, it actually works fine, you used an echo which is console.log for ci it needs to be changed, can i work on it? ![image](https://user-images.githubusercontent.com/78784850/230763289-a211e58b-5de0-43e7-b2a6-6d27eee6ae37.png)

Yeah, sure
