### ISSUE TITLE
[Add] <Open Source Stories>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#422]
### URL

https://www.opensourcestories.org/

### Description of the above provided site

Founded by [Amanda Casari](https://twitter.com/amcasari) and [Julia Ferraioli](https://twitter.com/juliaferraioli), Open Source Stories is a podcast where individuals record their experiences about being in the open source community. In contrast to other podcasts, these stories are saved in the StoryCorps archive at the United States Congress! 😄 So what are you waiting for? Share your story! 😄 

### Category

Other

### Sub Category

design inspiration

**Comment by MadhuMPandurangi** [comment]
Hi @CBID2 , Shall I raise a PR for this issue?
I added this data.

**Comment by CBID2** [comment]
> Hi @CBID2 , Shall I raise a PR for this issue? I added this data.

Thanks for the prompt response @MadhuMPandurangi! :) Sure! :)

**Comment by MadhuMPandurangi** [comment]
hey @CBID2 , I added it in design-inspirations.json which is in front end. Is it ok?

**Comment by CBID2** [comment]
> hey @CBID2 , I added it in design-inspirations.json which is in front end. Is it ok?

I think it could be. I only picked designs inspirations because there wasn't a category for podcasts. What do you think @rupali-codes?

**Comment by rupali-codes** [comment]
Hey, we can make a new category, but don't know if it's really needed

**Comment by MadhuMPandurangi** [comment]
> Hey, we can make a new category, but don't know if it's really needed

Let me know @CBID2 @rupali-codes about the decision. 
If new category, then check the below screenshot, is that correct?
![image](https://user-images.githubusercontent.com/27917751/231357687-629da536-966b-4031-b6d3-f01354551e99.png)

**Comment by CBID2** [comment]
> 
> 
> > Hey, we can make a new category, but don't know if it's really needed
> 
> 
> 
> Let me know @CBID2 @rupali-codes about the decision. 
> 
> If new category, then check the below screenshot, is that correct?
> 
> ![image](https://user-images.githubusercontent.com/27917751/231357687-629da536-966b-4031-b6d3-f01354551e99.png)
> 
> 
> 
> 

Ooh how about podcasts? People listen to those for tech advice

**Comment by MadhuMPandurangi** [comment]
Podcast as different category or subcategory in others?

**Comment by rupali-codes** [comment]
> Podcast as different category or subcategory in others?

We can name the category `Podcast` and add all stories (listening) & podcasts in there

**Comment by MadhuMPandurangi** [comment]
will this be in category: Podcast and subcategory: stories?

**Comment by rupali-codes** [comment]
> will this be in category: Podcast and subcategory: stories?

Let's keep it in Other

**Comment by MadhuMPandurangi** [comment]
> > will this be in category: Podcast and subcategory: stories?
> 
> Let's keep it in Other

category: other
subcategory: podcast?

**Comment by rupali-codes** [comment]
@manikandan97 looks perfect,
