### ISSUE TITLE
[OTHER] Website link has a generic "Generated by create next app." description when searching on Google.

### ISSUE THREAD

**Issue by Abrar0204** [rupali-codes/LinksHub#426]
### What would you like to share or ask?

Adding a description for the website will help in improving the SEO as well as letting the user know what the website is about.

![linkshub-description-in-google](https://user-images.githubusercontent.com/49402306/231371601-7c092315-95fe-46b9-8d12-7f0b9b3af968.png)

**Comment by rupali-codes** [comment]
@Abrar0204 thanks for pointing this out

**Comment by Abrar0204** [comment]
@rupali-codes If you can share the description. I can raise a PR for this by today

**Comment by rupali-codes** [comment]
yeah sure,

_LinksHub is the ultimate hub of ready-to-use tech resources. Discover free tools and libraries to streamline your development process and build better projects._
