### ISSUE TITLE
[BUG] Font-awesome and Color check card contain wrong link URL address

### ISSUE THREAD

**Issue by AdekeyeAdeniyi** [rupali-codes/LinksHub#43]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

##Bug
- [ ] Wrong URL address on the font-awesome and color check card button.

### Screenshots

![Screenshot 2023-01-18 204821](https://user-images.githubusercontent.com/57262658/213280439-e8ac36ba-5dae-4ad7-b4c9-321cdca70369.png)
![Screenshot 2023-01-18 204652](https://user-images.githubusercontent.com/57262658/213280450-7031a9db-528a-423d-90e9-2ef9259832a4.png)

### What browser are you seeing the problem on?

Chrome

**Comment by AdekeyeAdeniyi** [comment]
Can I fix this?

**Comment by rupali-codes** [comment]
> Can I fix this?

thank you for noticing. Yes you can :)

**Comment by AdekeyeAdeniyi** [comment]
Alright thanks.

**Comment by AdekeyeAdeniyi** [comment]
I have fixed it.
