### ISSUE TITLE
[Feature] Add Favicon| Icon for LinksHub in relation to issue #258

### ISSUE THREAD

**Issue by TreciaKS** [rupali-codes/LinksHub#437]
### Description

I propose that LinksHub have an icon/favicon on the webpage. I think it would make it appear nicer and credible. What do you think? @rupali-codes 🤔 

### Screenshots

<img width="352" alt="Screenshot 2023-04-14 at 14 08 12" src="https://user-images.githubusercontent.com/82657928/232041081-60d13a3b-d42c-4a84-b23b-115e1afbebd7.png">

**Comment by rupali-codes** [comment]
Hey @TreciaKS we actually favicon, though it takes sometime to load

**Comment by TreciaKS** [comment]
Wait, I just refreshed. its showing now @rupali-codes. Shall I close this issue?

**Comment by ujjawaltyagii** [comment]
> Wait, I just refreshed. its showing now @rupali-codes. Shall I close this issue?

@TreciaKS Yes, kindly close this issue as favicon is working perfectly fine. By the way, that was a good observation. Whatever the reason may be for the favicon not loading in your case, it's worth noting !

**Comment by rupali-codes** [comment]
> > Wait, I just refreshed. its showing now @rupali-codes. Shall I close this issue?
> 
> @TreciaKS Yes, kindly close this issue as favicon is working perfectly fine. By the way, that was a good observation. Whatever the reason may be for the favicon not loading in your case, it's worth noting !

Yeah, idk why it's taking time to load
