### ISSUE TITLE
[Add] Image link

### ISSUE THREAD

**Issue by AdekeyeAdeniyi** [rupali-codes/LinksHub#44]
### URL

https://www.uifaces.co/

### Description of the above provided site

UI Faces aggregates various free avatar placeholder sources that you can use in your design
mockups by copy & paste, API, and plugins for Sketch, Adobe XD, and Figma.

### Category

Frontend

### Sub Category

"images"

**Comment by rupali-codes** [comment]
Okay, Thank you

**Comment by maddy020** [comment]
Hey  @rupali-codes 
I want to work on this issue
Please elaborate where to add this link

**Comment by rupali-codes** [comment]
@maddy020 thanks for taking interest in. You can add this link in `database/data.ts` file under `root dir` of the project.
