### ISSUE TITLE
[BUG] Robots.txt is not valid

### ISSUE THREAD

**Issue by priyankarpal** [rupali-codes/LinksHub#443]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

- robots.txt is not valid. We need to look into it. 

### Screenshots

![image](https://user-images.githubusercontent.com/88102392/232233325-5ab329ce-6257-4d2a-985e-ad63298f6b13.png)

![image](https://user-images.githubusercontent.com/88102392/232233345-6cf43da8-651b-441f-8c95-c4878927d0b7.png)

### Any additional information?

There many problems we need to check it manually

**Comment by Divyansh-0** [comment]
> ### Is there any existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Description
> * robots.txt is not valid. We need to look into it.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/88102392/232233325-5ab329ce-6257-4d2a-985e-ad63298f6b13.png)
> 
> ![image](https://user-images.githubusercontent.com/88102392/232233345-6cf43da8-651b-441f-8c95-c4878927d0b7.png)
> 
> ### Any additional information?
> There many problems we need to check it manually
> 
> ### What browser are you seeing the problem on?
> _No response_

Are you using some testing software??

**Comment by priyankarpal** [comment]
> > ### Is there any existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Description
> > 
> > * robots.txt is not valid. We need to look into it.
> > 
> > ### Screenshots
> > ![image](https://user-images.githubusercontent.com/88102392/232233325-5ab329ce-6257-4d2a-985e-ad63298f6b13.png)
> > ![image](https://user-images.githubusercontent.com/88102392/232233345-6cf43da8-651b-441f-8c95-c4878927d0b7.png)
> > ### Any additional information?
> > There many problems we need to check it manually
> > ### What browser are you seeing the problem on?
> > _No response_
> 
> Are you using some testing software??

you can also check from your Browser using Lighthouse tool

**Comment by Divyansh-0** [comment]
@priyankarpal  Ok but i want to know what software you are using?
 if you dont mind

**Comment by priyankarpal** [comment]
> @priyankarpal Ok but i want to know what software you are using? if you dont mind

no no  I'm not using any software. I'm just using browser tool 

![image](https://user-images.githubusercontent.com/88102392/232283314-5a9cf227-17af-4a8f-bc6b-05414aa1be90.png)

**Comment by Divyansh-0** [comment]
> > @priyankarpal Ok but i want to know what software you are using? if you dont mind
> 
> no no I'm not using any software. I'm just using browser tool
> 
> ![image](https://user-images.githubusercontent.com/88102392/232283314-5a9cf227-17af-4a8f-bc6b-05414aa1be90.png)

Oh Ok thanks !! I have never used lighthouse😅

**Comment by Divyansh-0** [comment]
@priyankarpal  For the issue i see no robots.txt file in public directory . We will need to add that

**Comment by priyankarpal** [comment]
> @priyankarpal For the issue i see no robots.txt file in public directory . We will need to add that

yeah may be

**Comment by Divyansh-0** [comment]
@rupali-codes What all specifications we need in robots.txt? Here's a **Resource** >https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt

**Comment by priyankarpal** [comment]
> @rupali-codes What all specifications we need in robots.txt? Here's a **Resource** >https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt
```
User-agent: *
Disallow:

Sitemap: https://example.com/sitemap.xml
```

**Comment by rupali-codes** [comment]
hey thanks @priyankarpal & @Divyansh-0 will look into it

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by k-deepak04** [comment]
@sagnik-p can you resolve this?

**Comment by k-deepak04** [comment]
@rupali-codes @CBID2 shall we close this issue?
i want to clean the repo and maintain things efficiently by closing the old outdated things.
i'm thinking of tagging the issue opener and asking him if he is working or not.....id didn't got reply within 4 days i'll close the issue and if he replies late...that he was busy or so then we can repoen it again.
Let me know your views......by doing this we will be keep the repo clean and maintained with current issues under work.

**Comment by priyankarpal** [comment]
> @rupali-codes @CBID2 shall we close this issue? i want to clean the repo and maintain things efficiently by closing the old outdated things. i'm thinking of tagging the issue opener and asking him if he is working or not.....id didn't got reply within 4 days i'll close the issue and if he replies late...that he was busy or so then we can repoen it again. Let me know your views......by doing this we will be keep the repo clean and maintained with current issues under work.

you can do this automatically by adding gh action( closing issues after a time)

**Comment by k-deepak04** [comment]
> > @rupali-codes @CBID2 shall we close this issue? i want to clean the repo and maintain things efficiently by closing the old outdated things. i'm thinking of tagging the issue opener and asking him if he is working or not.....id didn't got reply within 4 days i'll close the issue and if he replies late...that he was busy or so then we can repoen it again. Let me know your views......by doing this we will be keep the repo clean and maintained with current issues under work.
> 
> you can do this automatically by adding gh action( closing issues after a time)

yep i know that
i'm confirming from Project Admins for their view

**Comment by k-deepak04** [comment]
@CBID2 have you written something?

**Comment by CBID2** [comment]
> @CBID2 have you written something? 

@priyankarpal pretty much communicated my thoughts. We have a Github action set up to close old issues

**Comment by k-deepak04** [comment]
> > @CBID2 have you written something?
> 
> @priyankarpal pretty much communicated my thoughts. We have a Github action set up to close old issues. I'm not sure if it's currently working though 🤔

okay i will look into that and check it's timeline , after how many days it closes the issue and revert it back to you

**Comment by rupali-codes** [comment]
> > > @CBID2 have you written something?
> > 
> > 
> > @priyankarpal pretty much communicated my thoughts. We have a Github action set up to close old issues. I'm not sure if it's currently working though 🤔
> 
> okay i will look into that and check it's timeline , after how many days it closes the issue and revert it back to you

45 days is much better i guess

**Comment by k-deepak04** [comment]
> > > > @CBID2 have you written something?
> > > 
> > > 
> > > @priyankarpal pretty much communicated my thoughts. We have a Github action set up to close old issues. I'm not sure if it's currently working though 🤔
> > 
> > 
> > okay i will look into that and check it's timeline , after how many days it closes the issue and revert it back to you
> 
> 45 days is much better i guess

made it 30 days

**Comment by CBID2** [comment]
> > > > > @CBID2 have you written something?
> 
> > > > 
> 
> > > > 
> 
> > > > @priyankarpal pretty much communicated my thoughts. We have a Github action set up to close old issues. I'm not sure if it's currently working though 🤔
> 
> > > 
> 
> > > 
> 
> > > okay i will look into that and check it's timeline , after how many days it closes the issue and revert it back to you
> 
> > 
> 
> > 45 days is much better i guess
> 
> 
> 
> made it 30 days

Great

**Comment by rupali-codes** [comment]
I'm closing this issue for now since its being inactive
