### ISSUE TITLE
fix: add theme-color

### ISSUE THREAD

**Issue by priyankarpal** [rupali-codes/LinksHub#444]
### Description

In the HTML file we need to add a theme color.

`Does not set a theme color for the address bar.Failures: No manifest was fetched, No `<meta name="theme-color">` tag found.`

### Screenshots

![image](https://user-images.githubusercontent.com/88102392/232233451-ce4a2569-3f85-4c62-bf21-1b279761ee15.png)

**Comment by rupali-codes** [comment]
> ### Description
> In the HTML file we need to add a theme color.
> 
> `Does not set a theme color for the address bar.Failures: No manifest was fetched, No `` tag found.`
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/88102392/232233451-ce4a2569-3f85-4c62-bf21-1b279761ee15.png)
> 
> ### Additional Information
> _No response_

Nice catch Priyankar, what does the theme color do? does it affect the site in any way?

**Comment by priyankarpal** [comment]
> > ### Description
> > In the HTML file we need to add a theme color.
> > `` Does not set a theme color for the address bar.Failures: No manifest was fetched, No `` tag found. ``
> > ### Screenshots
> > ![image](https://user-images.githubusercontent.com/88102392/232233451-ce4a2569-3f85-4c62-bf21-1b279761ee15.png)
> > ### Additional Information
> > _No response_
> 
> Nice catch Priyankar, what does the theme color do? does it affect the site in any way?

we need to add this meta tag 

`<meta name="theme-color" content="color-code" />`

![image](https://user-images.githubusercontent.com/88102392/232279289-5242159e-a5ce-4e13-b417-8a2d58a00e57.png)


also check the article https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color

**Comment by vikaskumar2703** [comment]
i think i can resolve this issue

**Comment by rupali-codes** [comment]
> i think i can resolve this issue

sure, thanks, assigning to you
