### ISSUE TITLE
Update banner in README 

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#446]
### What would you like to share or ask?

Updated LinksHub tagline in the banner

Replace the image with this one 

![LinksHub-Banner](https://user-images.githubusercontent.com/78981177/232279811-a219b1b5-6383-4ace-9614-24c6b258fec0.png)

**Comment by giri-madhan** [comment]
Hi, @rupali-codes. Let me work on this right now. Once completed, I will create a pull request and submit it for your review.
