### ISSUE TITLE
[BUG] URL inconsistency

### ISSUE THREAD

**Issue by AdekeyeAdeniyi** [rupali-codes/LinksHub#45]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

I noticed most of the URL links on the different cards have different URL formats, 
E.g
- Sample 1: https://unsplash.com/ [this contains www]
- Sample 2: https://www.fontsquirrel.com/ [This doesn't]

### What browser are you seeing the problem on?

Chrome

**Comment by rupali-codes** [comment]
okay, would you like to fix this?

**Comment by AdekeyeAdeniyi** [comment]
Yes I would
