### ISSUE TITLE
[Add] <Hacker News >

### ISSUE THREAD

**Issue by Stroller15** [rupali-codes/LinksHub#455]
### URL

https://news.ycombinator.com/

### Description of the above provided site

Hacker News, found at the URL https://news.ycombinator.com/, is a social news website focused on computer science and entrepreneurship. It was created by Paul Graham's investment fund and startup accelerator, Y Combinator, and is run by a small team of moderators. The site's content is primarily user-submitted and features links to articles, blog posts, and other online resources related to technology, business, and the startup world. Users can upvote and comment on submissions, and popular posts can quickly rise to the top of the front page. Hacker News has become a popular destination for programmers, entrepreneurs, and tech enthusiasts looking for news and discussion about the latest developments in their field.

### Category

Resources

### Sub Category

"blog" ,"article"

**Comment by rupali-codes** [comment]
Hey, so you will have to update `database/resources/blogs.json` file in order to add this link. Also, the format should be as same as other objects. Let us know if you need any further help

**Comment by Stroller15** [comment]
Ok I

**Comment by vikaskumar2703** [comment]
@Stroller15 working on this issue

**Comment by Stroller15** [comment]
@vikaskumar2703 yes brother I am working on this issue

**Comment by parma1111** [comment]
May I raise a PR for it

**Comment by rupali-codes** [comment]
This issue has been resolved
