### ISSUE TITLE
[Feature] A new category for "People"

### ISSUE THREAD

**Issue by Harsh-2909** [rupali-codes/LinksHub#458]
### Description

While adding a link for [Hussein Nasser](https://www.youtube.com/@hnasr), I found that there are a lot of people added in various sections (especially Youtube category) but some of them create content in more than one platform.
For eg: Hussein has a youtube channel, a podcast and a blog at the same time.
FreeCodeCamp (although not a person but an organisation) has a youtube channel, a site and a blog which all posts different content.

I felt that adding a People category would be a great place to keep their links. We would also be able to add their twitter links if they make some good content on it. Even if people category might be redundant, then adding multiple links would be a cool feature.

**Comment by rupali-codes** [comment]
hey, thanks

**Comment by Noothan-am** [comment]
hey is this issue still open? if not pls assign it me i want to work on it

**Comment by rupali-codes** [comment]
> hey, @rupali-codes is this issue still open? if not pls assign it me i want to work on it

I guess we don't need to it, as we are sperating channels based on the subcategories. could you please look for some other issue :)
