### ISSUE TITLE
[OTHER] Security feature 

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#460]
### What would you like to share or ask?

Hi everyone. I was looking through the Insights section and they pointed out that a Security standard was missing in [the Community Standards tab](https://github.com/rupali-codes/LinksHub/community). Should we add such as feature?

**Comment by rupali-codes** [comment]
Yeah, we are 90% done though, just need to add security policy

**Comment by CBID2** [comment]
> Yeah, we are 90% done though, just need to add a security policy

I can help with that! :)

**Comment by rupali-codes** [comment]
> > Yeah, we are 90% done though, just need to add a security policy
> 
> I can help with that! :)

Sure, would love to

**Comment by raghav1030** [comment]
Hey I have structured security policy for the repo....I can propose it if no one's working on it?

**Comment by CBID2** [comment]
> Hey I have structured security policy for the repo....I can propose it if no one's working on it?

Sure @raghav1030! :) Just create your PR so @rupali-codes and I can review it.
