### ISSUE TITLE
if there would be more languages in the language section that would be better[Feature] <add Languages>

### ISSUE THREAD

**Issue by anonymgit** [rupali-codes/LinksHub#461]
### Description

# add some languages to language section [C++,Java]
- in language section there is no resources added python and go lang,i want to add some other basic languages like c++ and java
- i want to work on this if you will allow me to do so, I will add some public resources which is available on the internet like GFG,w3school or official docs .

**Comment by rupali-codes** [comment]
which languages do you want to add?

**Comment by anonymgit** [comment]
> 

Like java,c++. I think it is a common languages that must be in the list of **LinksHub**

**Comment by anonymgit** [comment]
> > > 
> > 
> > 
> > Like java,c++. I think these are languages that must be in the list of **LinksHub**
> > That could work @anonymgit! :) I do hear people constantly talk about it on Twitter

I'm glad you think so too! Java and C++ are both widely-used languages that could be valuable additions to LinksHub's list. Do you have any other suggestions for languages that should be included?

**Comment by rupali-codes** [comment]
> > > > 
> > > 
> > > 
> > > Like java,c++. I think these are languages that must be in the list of **LinksHub**
> > > That could work @anonymgit! :) I do hear people constantly talk about it on Twitter
> 
> I'm glad you think so too! Java and C++ are both widely-used languages that could be valuable additions to LinksHub's list. Do you have any other suggestions for languages that should be included? Hmmm, maybe...MDX, Rust, and SolidJS?

good to go if you know a few resources for those languages

**Comment by anonymgit** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Like java,c++. I think these are languages that must be in the list of **LinksHub**
> > > > That could work @anonymgit! :) I do hear people constantly talk about it on Twitter
> > 
> > 
> > I'm glad you think so too! Java and C++ are both widely-used languages that could be valuable additions to LinksHub's list. Do you have any other suggestions for languages that should be included? Hmmm, maybe...MDX, Rust, and SolidJS?
> 
> good to go if you know a few resources for those languages

> Have a look at and evaluate the PR I made about this issue.

**Comment by rupali-codes** [comment]
@anonymgit could you please link the PR here?

**Comment by rupali-codes** [comment]
We have now added multiple languages. Feel free raise new issues :)
