### ISSUE TITLE
[Add] Gaurav Sen

### ISSUE THREAD

**Issue by Harsh-2909** [rupali-codes/LinksHub#477]
### URL

https://www.youtube.com/@gkcs

### Description of the above provided site

Gaurav Sen runs a youtube channel where he uploads videos regarding system design concepts and also mock system design interviews.
I will be creating PR for this by today night IST.

### Category

Backend

### Sub Category

system design

**Comment by CBID2** [comment]
I'll give it a shot! 😄

**Comment by Harsh-2909** [comment]
Sure @CBID2 
Will work on it today at the office

**Comment by CBID2** [comment]
> Sure @CBID2 
> Will work on it today at the office

Ok great

**Comment by Harsh-2909** [comment]
How do we collaborate on an issue? Do I create the PR for a non-main branch, then you work on this issue and create a pr for main branch? 
I have created a new category and added the link in my fork but not sure how to collaborate

**Comment by Harsh-2909** [comment]
Ok will so so
