### ISSUE TITLE
[Add] add gate smashers

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#479]
### URL

https://www.youtube.com/@GateSmashers

### Description of the above provided site

Gate Smashers provides content for Computer science subjects such as Operating System, DBMS, Computer Architecture, Software Engineering and more.

### Category

Youtube

### Sub Category

For this issue, create a new Subcategory named _Computer Science_ and this channel in that category

**Comment by imbeshat** [comment]
Hi Rupali, created a PR #481 for this issue.
