### ISSUE TITLE
[Feature] Add default text when search is empty

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#480]
### Summary
Currently, we don't have any default text when search is not found.

### Specific requirements
* Add **No Links Found** as default text

### Screenshots

The text should appear right after the search bar

![image](https://user-images.githubusercontent.com/78981177/234325811-edbcd13d-e827-4b8f-bb8b-e48ac9b6c7b0.png)

**Comment by Vinicius149** [comment]
I can help! 👍🏼

**Comment by aashay28** [comment]
could you let me work on this?

**Comment by rupali-codes** [comment]
> @rupali-codes could you let me work on this?

Sure, assigning to you!

**Comment by aashay28** [comment]
> * No Links Found

@rupali-codes please verify the change. It has been updated
