### ISSUE TITLE
[Add] Golang series by hitesh choudhary 

### ISSUE THREAD

**Issue by himanshu1221** [rupali-codes/LinksHub#484]
### URL

https://youtube.com/playlist?list=PLRAV69dS1uWQGDQoBYMZWKjzuhCaOnBpa

### Description of the above provided site

This playlist contains the Golang series along with two mini projects

### Category

Youtube

### Sub Category

"Backend","APIs"

**Comment by rupali-codes** [comment]
Thank you @himanshu1221, i guess we can create a new Subcategory under Youtube section named Projects, and can add playlists like this one in there

**Comment by himanshu1221** [comment]
> Thank you @himanshu1221, i guess we can create a new Subcategory under Youtube section named Projects, and can add playlists like this one in there

That would be great but this golang series of Hitesh choudhary is very nice do let me know if i can make a PR for this
