### ISSUE TITLE
[BUG] Add space between icons

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#485]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Add some space between these icons in the Popup, it looks kinda glued. 

### Screenshots

![image](https://user-images.githubusercontent.com/78981177/234560716-5a9ec59e-8d79-415b-9967-89ac482603bc.png)

**Comment by giri-madhan** [comment]
Hi @rupali-codes , Could I work on this issue?
