### ISSUE TITLE
[CHORE] add LinksHub contributors link in footer of the site

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#489]
### What would you like to share or ask?

Add [this](https://github.com/rupali-codes/LinksHub/graphs/contributors) link in the footer of the site. The link should be open in **new tab**

### Additional information

![image](https://user-images.githubusercontent.com/78981177/234788002-b7d67e5e-55ae-4fe7-a7ce-6c5cfa8ddb1d.png)

**Comment by aashay28** [comment]
please assign me this task.
thank you

**Comment by rupali-codes** [comment]
> I'll do it!

You wanna work on this Chrissy?

**Comment by 1010nishant** [comment]
I have done this in my local environment. I am dropping screenshots of the changed code.
before
<img width="666" alt="Screenshot 2023-04-29 at 12 04 42 PM" src="https://user-images.githubusercontent.com/88904952/235288367-7b10a030-d68e-400a-b594-f57dcf128bc3.png">
after
<img width="705" alt="Screenshot 2023-04-29 at 12 05 03 PM" src="https://user-images.githubusercontent.com/88904952/235288377-a7c2c95b-4eb3-4368-8cb2-06adb0956922.png">

And It is working as you want on my localhost.
Could I raise the PR directly or do you need to assign it first?

**Comment by rupali-codes** [comment]
Hey @1010nishant, looks good, you can rise PR for it

**Comment by 1010nishant** [comment]
Hey @rupali-codes , review the PR, thanks
