### ISSUE TITLE
CodeSandbox

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#490]
### URL

https://codesandbox.io/search?refinementList

### Description of the above provided site

This site will give you a every type of design with code. From this you can make your coding journey very fast.

### Category

Frontend

### Sub Category

CAT = FRONTEND
SUBCAT = REACTJS

**Comment by parma1111** [comment]
Can I raise a PR for it ?

**Comment by rupali-codes** [comment]
> Can I raise a PR for it ?

Is it something like Start templates? or could u explain in details?

**Comment by parma1111** [comment]
> > Can I raise a PR for it ?
> 
> Is it something like Start templates? or could u explain in details?

here we will get some code that already written for some design.
And we can filter that according to framework and dependencies

**Comment by rupali-codes** [comment]
> > > Can I raise a PR for it ?
> > 
> > 
> > Is it something like Start templates? or could u explain in details?
> 
> here we will get some code that already written for some design. And we can filter that according to framework and dependencies

Thanks, you may create a PR

**Comment by parma1111** [comment]
> > > > Can I raise a PR for it ?
> > > 
> > > 
> > > Is it something like Start templates? or could u explain in details?
> > 
> > 
> > here we will get some code that already written for some design. And we can filter that according to framework and dependencies
> 
> Thanks, you may create a PR

Ok I will create
