### ISSUE TITLE
Learn-Python-3

### ISSUE THREAD

**Issue by Smit9313** [rupali-codes/LinksHub#493]
### URL

https://www.codecademy.com/learn/learn-python-3

### Description of the above provided site

Learn the basics of Python 3, one of the most powerful, versatile, and in-demand programming languages today.

### Category

Other

### Sub Category

Languages -> Python

**Comment by CBID2** [comment]
> ### URL
> https://www.codecademy.com/learn/learn-python-3
> 
> ### Description of the above-provided site
> Learn the basics of Python 3, one of the most powerful, versatile, and in-demand programming languages today.
> 
> ### Category
> Other
> 
> ### Sub Category
> Languages -> Python

Sounds great to me! :)
