### ISSUE TITLE
[Add] C# web

### ISSUE THREAD

**Issue by Weverak** [rupali-codes/LinksHub#494]
### URL

https://www.tutorialsteacher.com/cshar

### Description of the above provided site

I would appreciate some links on C# and I remember, that when I was starting with programming, I used it very much. It really helped me. It has some basic lessons of C# and each topic is nicely explained and has some examples with it. I would like to add it to this project. It may be under languages and under new c# subcategory.

### Category

Other

### Sub Category

Csharp, C#, languages

**Comment by rupali-codes** [comment]
Thanks, the url is https://www.tutorialsteacher.com/csharp. 
would u like to work on this?

**Comment by Weverak** [comment]
Yes, I would like to do it. Can you assign it to me? I found this project few days ago and I very like it.

**Comment by rupali-codes** [comment]
> Yes, I would like to do it. Can you assign it to me? I found this project few days ago and I very like it.

Sure, assigning to you :)
