### ISSUE TITLE
[Feature] Add skip link

### ISSUE THREAD

**Issue by EmmaDawsonDev** [rupali-codes/LinksHub#498]
### Description

The navigation is quite long with many links to tab through for keyboard users. By adding a skip link before the navigation, keyboard users can bypass having to tab through the navigation every time to get to the main content.

This will ensure the site passes [WCAG criteria 2.4.1 Level A](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html )

**Comment by rupali-codes** [comment]
Thanks for pointing this out @EmmaDawsonDev, are you willing to work on this? 😅

**Comment by Divyansh-0** [comment]
@EmmaDawsonDev  Do you mean to say that since the web page contain a lot of navigable content we need something which allows user to get to main web page quickly ?? or am i interpreting it incorrectly?

**Comment by EmmaDawsonDev** [comment]
> Thanks for pointing this out @EmmaDawsonDev, are you willing to work on this? 😅

I don’t have time right now (I’m going on vacation in a couple of days) but if nobody else wants to pick it up then I can have a go in a few week’s time.

**Comment by rupali-codes** [comment]
> > Thanks for pointing this out @EmmaDawsonDev, are you willing to work on this? 😅
> 
> I don’t have time right now (I’m going on vacation in a couple of days) but if nobody else wants to pick it up then I can have a go in a few week’s time.

Sure, thanks

**Comment by EmmaDawsonDev** [comment]
Since no-one took this issue while I was away I will work on it over the weekend :)

**Comment by rupali-codes** [comment]
> Since no-one took this issue while I was away I will work on it over the weekend :)

Sure, Thanks Emma :)
