### ISSUE TITLE
[Add] Flickr

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#506]
### URL

https://www.flickr.com/

### Description of the above provided site

Flickr is a vibrant online community where you'll find stunning landscapes, captivating portraits, breathtaking wildlife shots, and much more. The platform's intuitive search and discovery features make it easy to find photos that match your interests, while its social features allow you to follow your favorite photographers and engage with others who share your passion for photography.

### Category

Frontend

### Sub Category

images

**Comment by parma1111** [comment]
Can you assign this issue to me ?

**Comment by ujjawaltyagii** [comment]
@parma1111 Hi Parma ! You are doing great, you can directly raise PR for general issues like this one and link the issue there !
