### ISSUE TITLE
[Add] Freepik

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#507]
### URL

https://www.freepik.com/

### Description of the above provided site

Freepik is a platform that offers free and premium vector graphics, stock photos, and PSD files for designers and creatives to use in their projects. With millions of high-quality graphic resources, Freepik is the ultimate destination for anyone looking to elevate their design work without breaking the bank.

### Category

Frontend

### Sub Category

images

**Comment by parma1111** [comment]
Can you assign this issue to me ?
