### ISSUE TITLE
[Add] Stocksnap

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#508]
### URL

https://stocksnap.io/

### Description of the above provided site

Stocksnap is a royalty-free stock photo site with a vast collection of high-quality images contributed by a community of talented photographers from around the world.

### Category

Frontend

### Sub Category

images

**Comment by parma1111** [comment]
Can you assign this issue to me ?

**Comment by rupali-codes** [comment]
> Can you assign this issue to me ?

Sure

**Comment by parma1111** [comment]
> > Can you assign this issue to me ?
> 
> Sure

> Ok I will create the PR
