### ISSUE TITLE
[Add] Life of Pix

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#509]
### URL

https://www.lifeofpix.com/

### Description of the above provided site

Life of Pix is an online platform that provides free access to a remarkable assortment of premium images taken by skilled photographers worldwide. Its intuitive interface and absence of copyright limitations make it the ideal choice for individuals seeking attractive and genuine photographs.

### Category

Frontend

### Sub Category

images

**Comment by parma1111** [comment]
Can you assign this issue to me ?

**Comment by rupali-codes** [comment]
@Oyebolade would you like to work on this?

**Comment by Oyebolade** [comment]
Yes

**Comment by Oyebolade** [comment]
All right

**Comment by parma1111** [comment]
Can I raise a PR for it ?

**Comment by CBID2** [comment]
> Can I raise a PR for it ?

Sure @parma1111! :)
