### ISSUE TITLE
I suggest creating a Generator subcategory in the Frontend category to provide easy access to various tools.

### ISSUE THREAD

**Issue by PriyansuMaurya** [rupali-codes/LinksHub#51]
### Description

Here we could add all the websites which help in generating CSS.
Like for example 

https://neumorphism.io/#e0e0e0
https://hype4.academy/tools/glassmorphism-generator
https://uiverse.io/switches
https://www.cssportal.com/css-generators.php
https://enjoycss.com/start#box
https://cssgenerator.org/

**Comment by rupali-codes** [comment]
Thank you @PriyansuMaurya, will surely do that

**Comment by PriyansuMaurya** [comment]
> Thank you @PriyansuMaurya, will surely do that 

I want to try it first.

**Comment by rupali-codes** [comment]
okay, go on

**Comment by rupali-codes** [comment]
@PriyansuMaurya how's it going?

**Comment by PriyansuMaurya** [comment]
> @PriyansuMaurya how's it going?
> 

I'm out of my home place for 10 days. So sorry 😑 for this. If anyone is ready to take this please assign him.
