### ISSUE TITLE
Add Krish Naik

### ISSUE THREAD

**Issue by suzy-g38** [rupali-codes/LinksHub#511]
### URL

https://www.youtube.com/user/krishnaik06

### Description of the above provided site

Krish Naik is one of the best YouTubers in the Machine Learning domain with 749k subscribers where he uploads videos on Machine Learning, Deep Learning and Data Science. He is also a GitHub Star.

### Category

Youtube

### Sub Category

Machine Learning

**Comment by rupali-codes** [comment]
Thanks, @suzy-g38 would you like to work on this?

**Comment by suzy-g38** [comment]
> Thanks, @suzy-g38 would you like to work on this?

Yeah sure
