### ISSUE TITLE
[BUG] Need space between icons in YouTube category

### ISSUE THREAD

**Issue by suzy-g38** [rupali-codes/LinksHub#512]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

When you go to the individual link in the youtube category, if you click to see the description of a particular YouTuber the icons at the top have no spacing in between.

### Screenshots

![image](https://user-images.githubusercontent.com/62666287/236286112-cb8c501b-ba00-4252-bce8-e525d1b015b2.png)

**Comment by rupali-codes** [comment]
Hey, this issue was fixed, you probably trying to access the older version #485

**Comment by suzy-g38** [comment]
> Hey, this issue was fixed, you probably trying to access the older version #485

Oh my bad, I was checking among the open issues that's why.
