### ISSUE TITLE
[Feature] Toggle sidebar menu

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#513]
### Description

Currently, user can open as many tabs as they want in the site, but since the sidebar is long, it causes accessibility issues. 

What we want to do is: 
Close the other opened tab when new tab is clicked OR keep a single tab opened at a time in the sidebar

### Screenshots

![image](https://user-images.githubusercontent.com/78981177/236291860-4ec475e8-dcf5-4eb2-bf0d-c7e1ade36faa.png)

### Additional Information

This issue is a part of #409 issue

**Comment by suzy-g38** [comment]
I want to work on this issue.

**Comment by CBID2** [comment]
> I want to work on this issue.

Done! 😊👍🏾

**Comment by Lucif3r-in** [comment]
Are you still working on this @suzy-g38 ?

**Comment by suzy-g38** [comment]
> Are you still working on this @suzy-g38 ?

Yes

**Comment by rupali-codes** [comment]
> > Are you still working on this @suzy-g38 ?
> 
> Yes

You can make draft Pull requests while still working on the issue

**Comment by milan-lakhani** [comment]
@rupali-codes Can I please work on the issue? I can create a draft pull request and you can view my progress.

**Comment by suzy-g38** [comment]
Sorry @rupali-codes and @CBID2, I was taking a long time.....I am dealing with some really urgent stuff. I have unassigned myself. You guys can assign anyone now. Thank you.
