### ISSUE TITLE
[Feature] Add new category for Open Source

### ISSUE THREAD

**Issue by Harsh-2909** [rupali-codes/LinksHub#519]
## About this category:
This section will have links to any resources that may help somebody to get started in open source.

### Types of links:
- Open Source projects to get started (eg: LinkFree from EddieHub)
- Blogs and article regarding Open Source
- People to follow regarding open source
- And more...

**Comment by rupali-codes** [comment]
Thanks Harsh

**Comment by shubhsharma19** [comment]
Great Idea!

**Comment by ujjawaltyagii** [comment]
@rupali-codes could you assign this to me ? and do let me know whether i should create a completely new section named `Open-Source` or you want to add this under any available category ?!
