### ISSUE TITLE
[Add] Tabler Icon

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#526]
### Site URL

https://tablericons.com/

### Description of the above provided site

Tabler is a collection of more than 1,400 SVG icons that are free and open-source. The Tabler UI framework creators designed and developed these icons to be easily customizable and suitable for a wide range of design requirements.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Oyebolade** [comment]
Kindly assigned issue #526 to me.
Thanks

**Comment by rupali-codes** [comment]
> Kindly assigned issue #526 to me. Thanks

Sure
