### ISSUE TITLE
[Add] Heroicons

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#528]
### Site URL

https://heroicons.com/

### Description of the above provided site

Heroicons is a comprehensive collection of high-quality SVG icons designed to enhance your web and mobile interfaces. With its extensive collection and easy integration, Heroicons empowers developers to add visually appealing and consistent icons to their projects effortlessly.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by parma1111** [comment]
Can I make a PR for it ?

**Comment by CBID2** [comment]
> Can I make a PR for it ?

Sure @parma1111

**Comment by rupali-codes** [comment]
> Can I make a PR for it ?

Hey, you can ask only when the PR is not assigned to anyone :)
