### ISSUE TITLE
[Add] Page with JavaScript exercises

### ISSUE THREAD

**Issue by gabrysia694** [rupali-codes/LinksHub#531]
### Site URL

https://exercism.org/tracks/javascript

### Description of the above provided site

Exercism is a website that provides programming exercises and challenges to help developers improve their skills in a variety of programming languages, including JavaScript.

### Category

Languages

### Sub Category

"JavaScript"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Thanks, assigning to you
