### ISSUE TITLE
Sidebar elements display white pixels when clicked.

### ISSUE THREAD

**Issue by JoshHargreaves** [rupali-codes/LinksHub#55]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

When clicking a sidebar link pixels appear in the left corners of the element.

### Screenshots

![pixel border](https://user-images.githubusercontent.com/20206340/213537635-e27dc791-cdcb-4bd2-9a72-a8d6aabcfaa4.png)

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by rupali-codes** [comment]
would you like to fix this?

**Comment by rupali-codes** [comment]
@JoshHargreaves are you still working on it?

**Comment by JoshHargreaves** [comment]
Hi , not working on this one . Just raised the issue when I saw it .

**Comment by rupali-codes** [comment]
Okay, thank you.
It was fixed though.

Is there anything else you would to add?
