### ISSUE TITLE
[Add] Blush Design

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#550]
### Site URL

https://blush.design/

### Description of the above provided site

Blush.design is a creative platform offering a diverse collection of customizable illustrations for designers, developers, and content creators. With an extensive library of vibrant artwork, users can effortlessly enhance their projects. The platform allows easy customization of colors, styles, and elements to suit individual needs, empowering creativity and enhancing visual communication.

### Category

Frontend

### Sub Category

Illustrations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hey, when you check the 3rd checkmark you can start  working on the issue without being assigned to it

**Comment by Oyebolade** [comment]
All right
