### ISSUE TITLE
[Add] Skribbl

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#552]
### Site URL

https://weareskribbl.com/

### Description of the above provided site

Enrich your creative projects and support free access to art of education with the collection of hand-drawn illustrations.

### Category

Frontend

### Sub Category

Illustrations

### Checklist

- [X] I have checked the existing issues
- [x] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Noothan-am** [comment]
hey @Oyebolade is this issue fixed?

**Comment by Oyebolade** [comment]
Yes
