### ISSUE TITLE
[Add] Two open-source blogs

### ISSUE THREAD

**Issue by iriteshmishra** [rupali-codes/LinksHub#569]
### Site URL

https://blog.pradumnasaraf.dev/ways-to-get-more-contributors-to-your-open-source-project

### Description of the above provided site

How to start contributing to open source and Ways to get more contributors to your open source projects.

### Category

Other

### Sub Category

open source

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Why did you close the issue?

**Comment by iriteshmishra** [comment]
Can you assign me, I will like to contribute as GSSOC'23 @rupali-codes or @CBID2

**Comment by rupali-codes** [comment]
Sure, are you gssoc contributor?

**Comment by CBID2** [comment]
> Sure, are you gssoc contributor?
@iriteshmishra can you confirm again?

**Comment by iriteshmishra** [comment]
I was contributing to project so I didn't able to see your comment. Yes, I am gssoc'23 contributor. Thankyou for mentioning it for this issue. @rupali-codes
