### ISSUE TITLE
[DESIGN] design a landing page for LinksHub in Figma

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#57]
### What would you like to share or ask?

As our project is open source and we don't have a landing page yet, it would be great to have a place where users can learn about the project, its features, and how to get started. This issue is to track the design of a landing page for LinksHub in Figma.

### The landing page should include:
- A brief overview of the project and its purpose
- A list of key features
- Screenshots and/or demo videos to showcase the project
- Links to github and documentation to help users get started
- A section for contributors to learn how they can contribute to the project
- A way for users to contact the development team for support or to report issues

> Design and layout should be modern and user-friendly, and should be accessible to users of all abilities.

Please provide a Figma link to the design and share it with the development team. Also, let me know if you have any questions or need clarification on any of the above points.

> **It's also important to note that the design should be accessible, responsive and mobile-friendly as well.**

**Comment by shubhsharma19** [comment]
I will try this :)

**Comment by shubhsharma19** [comment]
Working on it :)

**Comment by shubhsharma19** [comment]
Can you provide me with the key features of the LinksHub, It will be helpful so that I can work on the second point. :)

**Comment by rupali-codes** [comment]
> Can you provide me the key features of the LinksHub, It will be helpful so that I can work on the second point. :)

1. Add Links
2. Get Links
3. Save Time
4. Easy to use

**Comment by shubhsharma19** [comment]
Thanks :)

**Comment by rupali-codes** [comment]
Hi @shubhsharma19, regarding pushing design, you can create a `design dir` under `public` dir and push files there. and if it's a link, then add this link in a json format.

**Comment by rupali-codes** [comment]
@shubhsharma19 How's it going?

**Comment by shubhsharma19** [comment]
> @shubhsharma19 How's it going? 

I will be uploading the design idea today and will be making it better with updates. :)

**Comment by rupali-codes** [comment]
@shubhsharma19 Any updates?

**Comment by shubhsharma19** [comment]
Sorry for the delay i will keep giving u updates now, almost forgot
