### ISSUE TITLE
[OTHER] MD file for GSSOC

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#571]
### What would you like to share or ask?

I think there should be a separate Contributing file for GirlScript Summer of Code. What do you think? 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hey Chrissy, not a sperate though, but we can add some points in the existing contributing file

**Comment by rupali-codes** [comment]
this issue has been fixed
