### ISSUE TITLE
[Add] developedbyed

### ISSUE THREAD

**Issue by rajatnai49** [rupali-codes/LinksHub#576]
### Site URL

https://www.youtube.com/@developedbyed

### Description of the above provided site

DevelopedByEd is a great YouTube channel where instructor Ed, a self-taught full stack engineer and designer from Romania, and he has been teaching code since 2018. He make learning fun and simple, covering topics such as web development, web design, UI/UX, game development, tech-related news, 3D modelling, and more!

### Category

Youtube

### Sub Category

web development 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment]
Hey, could you please customize the description based on what they exactly teach?

**Comment by rupali-codes** [comment]
@rajatnai49 are you a gssoc contributor?

**Comment by rajatnai49** [comment]
yes, i am
