### ISSUE TITLE
[Add] Animated Fluent Emojis

### ISSUE THREAD

**Issue by dhruvdabhi101** [rupali-codes/LinksHub#580]
### Site URL

https://animated-fluent-emoji.vercel.app/

### Description of the above provided site

Super cool emojis which are animated and great to use for Readme files or Websites. 
Here's the example of emojis. 

<img width="1361" alt="Screenshot 2023-05-20 at 23 59 29" src="https://github.com/rupali-codes/LinksHub/assets/91935072/99507723-2435-4384-82be-e5c4156bd005">

### Category

Frontend

### Sub Category

"icons", "emojis"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by dhruvdabhi101** [comment]
can you please assign this issue to me ?

**Comment by CBID2** [comment]
> can you please assign this issue to me?

Done @dhruvdabhi101! :)
