### ISSUE TITLE
[Feature] Add Projects Section

### ISSUE THREAD

**Issue by aditya9277** [rupali-codes/LinksHub#581]
### Description

Brief -
Currently website lack the practical implementations/knowledge resource section.
I want to add PROJECTS section on the Resources section of website, It will have Project Tasks of the respective languages/resources.

Solution -
By addition of projects section, development beginners can get a path to begin with after learning from the resources and gain hand on experience For example, it will have challenging beginner projects ideas that a beginner can begin with like basic portfolio website, different CSS styling projects etc.
Basically by projects section, a learner can get a path to implement his knowledge that he/she has gained. As making projects is equally important while learning.

Additional context
Many beginners don't know a path and what projects to be done after learning, this feature will be a great addition to the website and its resource. Solution/Links for the codes of projects will also be there, so if a learner get stuck, he can get a idea/solutions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by aditya9277** [comment]
I am a GSSoC 23 contributor, i have already planned the implementation, and i already have a collection of suitable resources for the PROJECTS feature. Can you please assign me with this. @rupali-codes

**Comment by rupali-codes** [comment]
@aditya9277 sounds cool, but what links you are going to add there?

**Comment by aditya9277** [comment]
Projects from websites like geeksforgeeks, Interview bit, codewithharrry and Mainly there are many underrated open source GitHub repositories which have 100+ beginner friendly projects freely available. 
So therefore, a Projects section should also be there under the Resources Section.
The Project Section would also be divided by various domains like Web Development, App Development, Python based Projects and many more

Being experienced in frontend, I can definitely add a section by adding code and modifying your codebase, and i would definitely add links also in the Projects section to initialize it.
Would be glad by your response on this @rupali-codes

**Comment by CBID2** [comment]
> Projects from websites like geeksforgeeks, Interview bit, codewithharrry and Mainly there are many underrated open source GitHub repositories which have 100+ beginner friendly projects freely available. So therefore, a Projects section should also be there under the Resources Section. The Project Section would also be divided by various domains like Web Development, App Development, Python based Projects and many more
> 
> Being experienced in frontend, I can definitely add a section by adding code and modifying your codebase, and i would definitely add links also in the Projects section to initialize it. Would be glad by your response on this @rupali-codes

Sounds interesting @aditya9277! :) I think these could be helpful! :)

**Comment by aditya9277** [comment]
Thanks @CBID2 , Please can I get it assigned,  so i can start working....I will do it very fast.

**Comment by CBID2** [comment]
> Thanks @CBID2 , Please can I get it assigned, so i can start working....I will do it very fast. I think after assigning , you unassigned me.

My mistake. You are reassigned! :)
