### ISSUE TITLE
[Feature] Public Chat System

### ISSUE THREAD

**Issue by noobtuber20103152** [rupali-codes/LinksHub#586]
### Description

What do you think about a public chat with Firebase authentication 🤔. 

Please let me know if I am able to work on it or not. @rupali-codes @CBID2 

GSSoC contributor 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Why do we need a chat system?

**Comment by noobtuber20103152** [comment]
A public chat system can enhance user engagement and collaboration. This website is a content-sharing website, users can discuss articles, videos, or other resources through the chat system, fostering a sense of community. 🤔🤔🤷‍♂️🤷‍♂️

**Comment by rupali-codes** [comment]
> A public chat system can enhance user engagement and collaboration. This website is a content-sharing website, users can discuss articles, videos, or other resources through the chat system, fostering a sense of community. 🤔🤔🤷‍♂️🤷‍♂️ @rupali-codes

I don't think so, also we have a  discord community for any kinda discussion. @CBID2 what do you say?

**Comment by CBID2** [comment]
> > A public chat system can enhance user engagement and collaboration. This website is a content-sharing website, users can discuss articles, videos, or other resources through the chat system, fostering a sense of community. 🤔🤔🤷‍♂️🤷‍♂️ @rupali-codes
> 
> 
> 
> I don't think so, also we have a  discord community for any kinda discussion. @CBID2 what do you say?

I agree with @rupali-codes. People can just join the Discord community. With that being said , we're going to close this PR.
