### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by UjjwalSharma01** [rupali-codes/LinksHub#593]
### Description

hello,
i want to add readme badges, image for the reference is attached, this image is just for the reference, to make it clear of what im talking about.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/113621084/f71c679d-e8a4-40a1-abdd-7d0c9e20a04f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks @UjjwalSharma01 but i guess we don't need it. As all the information is available in the repo itself :)
