### ISSUE TITLE
[Add] Next UI should be added to UI Generators

### ISSUE THREAD

**Issue by bose-aritra2003** [rupali-codes/LinksHub#594]
### Site URL

https://nextui.org/docs/guide/getting-started

### Description of the above provided site

NextUI allows you to make beautiful, modern, and fast websites/applications regardless of your design experience, created with [React.js](https://reactjs.org/) and [Stitches](https://stitches.dev/), based on [React Aria](https://react-spectrum.adobe.com/react-aria/index.html) and inspired by [Vuesax](https://vuesax.com/). The UI design that comes with Next UI truly feels different from any other UI libraries currently present. Also, Next UI have announced that they are switching to Tailwind CSS soon.

### Category

Frontend

### Sub Category

ui generators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks, assigning to you
