### ISSUE TITLE
[Add] NextAuth.js should be added to Authentication

### ISSUE THREAD

**Issue by bose-aritra2003** [rupali-codes/LinksHub#595]
### Site URL

https://next-auth.js.org/getting-started/introduction

### Description of the above provided site

NextAuth.js is a complete open-source authentication solution for [Next.js](http://nextjs.org/) applications.
It is designed from the ground up to support Next.js and Serverless. 
*It has also been updated to natively support the latest NextJS 13 **app router** and **route handlers.***

### Flexible and easy to use

- Designed to work with any [OAuth service, it supports OAuth 1.0, 1.0A, 2.0 and OpenID Connect](https://next-auth.js.org/providers)
- Built-in support for [many popular sign-in services](https://next-auth.js.org/configuration/providers/oauth)
- Supports [email / passwordless authentication](https://next-auth.js.org/providers/email)
- Supports stateless authentication with [any backend](https://authjs.dev/reference/adapters) (Active Directory, LDAP, etc)
- Supports both JSON Web Tokens and database sessions
- Designed for Serverless but runs anywhere (AWS Lambda, Docker, Heroku, etc…)

### Own your own data

NextAuth.js can be used with or without a database.

- An open-source solution that allows you to keep control of your data
- Supports Bring Your Own Database (BYOD) and can be used with any database
- Built-in support for [MySQL, MariaDB, Postgres, SQL Server, MongoDB and SQLite](https://next-auth.js.org/configuration/databases)
- Works great with databases from popular hosting providers
- Can also be used without a database (e.g. OAuth + JWT)

*Note:* Email sign-in requires a database to be configured to store single-use verification tokens.

### Secure by default

- Promotes the use of passwordless sign-in mechanisms
- Designed to be secure by default and encourage best practices for safeguarding user data
- Uses Cross-Site Request Forgery Tokens on POST routes (sign in, sign out)
- Default cookie policy aims for the most restrictive policy appropriate for each cookie
- When JSON Web Tokens are enabled, they are encrypted by default (JWE) with A256GCM
- Auto-generates symmetric signing and encryption keys for developer convenience
- Features tab/window syncing and keepalive messages to support short-lived sessions
- Attempts to implement the latest guidance published by [Open Web Application Security Project](https://owasp.org/)

Advanced options allow you to define your own routines to handle controlling what accounts are allowed to sign in, for encoding and decoding JSON Web Tokens and to set custom cookie security policies and session properties, so you can control who can sign in and how often sessions have to be re-validated.

### Category

Backend

### Sub Category

authentication

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@bose-aritra2003 thanks. But please make the description short and clear and you can work on only ONE issue at a time :)

**Comment by bose-aritra2003** [comment]
@rupali-codes Could you please assign me this issue ?

**Comment by bose-aritra2003** [comment]
@rupali-codes Can you please assign me this issue ?

**Comment by rupali-codes** [comment]
> @rupali-codes Can you please assign me this issue ?

You're already working on other issues, please wait them to be merged :)

**Comment by bose-aritra2003** [comment]
You already merged that issue a few minutes ago. It was related to adding "Next UI" to UI Generators Frontend.

**Comment by rupali-codes** [comment]
> You already merged that issue a few minutes ago. It was related to adding "Next UI" to UI Generators Frontend.

Great, thanks
