### ISSUE TITLE
[Style] Smooth transition for the sidebar accordion

### ISSUE THREAD

**Issue by bose-aritra2003** [rupali-codes/LinksHub#596]
### What would you like to share or ask?

The sidebar accordion on LinksHub kind of feels too janky on opening. So some ease-in, ease-out transition should be used for the accordion.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Great, thanks

**Comment by bose-aritra2003** [comment]
@rupali-codes Can I take up this issue? I currently have no issues assigned. All my PRs have been successfully merged.
