### ISSUE TITLE
[Feature] "Database" subcategory for "Backend" category

### ISSUE THREAD

**Issue by bose-aritra2003** [rupali-codes/LinksHub#597]
### Description

LinksHub is currently ***missing*** an important category dedicated to various ***database solutions*** such as MongoDB, PostgreSQL, Redis, and more. 

***Databases*** play a crucial role in powering the infrastructure of most websites. They store and manage vast amounts of data, ensuring efficient retrieval and manipulation. As such, it is essential to have a ***dedicated subcategory*** that focuses on the resources available for the various diverse database solutions.

### Screenshots
A mockup of what I want to achieve
<img width="1440" alt="Screenshot 2023-05-21 at 12 21 47" src="https://github.com/rupali-codes/LinksHub/assets/77151837/0e0b5136-ba4b-455d-8b06-1e346797a5b7">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Please read CONTRIBUTING guidelines carefully, and do not start working without getting assigned :)

**Comment by bose-aritra2003** [comment]
I did not start working. I was just showing a mockup by editing the in browser HTML since a screenshot was needed. So could you please assign me this issue ?

**Comment by Rutujeet** [comment]
I kindly request your consideration in assigning Issue #597 under GSSOC'23 to me. I believe I can contribute effectively to its resolution.

**Comment by rupali-codes** [comment]
> I kindly request your consideration in assigning Issue #597 under GSSOC'23 to me. I believe I can contribute effectively to its resolution.

Sure
