### ISSUE TITLE
[BUG] Google Search result title displayed as "Vercel" instead of "LinksHub"

### ISSUE THREAD

**Issue by bose-aritra2003** [rupali-codes/LinksHub#598]
### Description

On doing a simple ***Google Search*** with "LinksHub", this website comes at the very top of all the results. Even though the link is absolutely correct, the title displayed beside the logo on the result is ***"Vercel"*** instead of ***"LinksHub"***.

### Screenshots

<img width="877" alt="Screenshot 2023-05-21 at 12 59 08" src="https://github.com/rupali-codes/LinksHub/assets/77151837/359cc5e2-3da3-41fa-adcf-fa4507490db6">

### What browser are you seeing the problem on?

Safari

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@bose-aritra2003 maybe because it was deployed on vercel. can you fix it?

**Comment by AKACHI-4** [comment]
Hey 👋 is someone working on this issue ?? if not can I work on it ?

**Comment by rupali-codes** [comment]
> Hey 👋 is someone working on this issue ?? if not can I work on it ?

Sure, i'd like to know how you're going to fix it :)

**Comment by AKACHI-4** [comment]
Hey @rupali-codes 👋 thanks to ask 

As far I know this is because of it's vercel deployment to fix it we need to do two things first is to deploy it somewhere like on the cloud or Digital Ocean etc. and then assign it a domain names either by the purchase or free one provided to Github student by Name.com.

**Comment by CBID2** [comment]
> Hey @rupali-codes 👋 thanks to ask
> 
> As far I know this is because of it's vercel deployment to fix it we need to do two things first is to deploy it somewhere like on the cloud or Digital Ocean etc. and then assign it a domain name either by the purchase or free one provided to GitHub student by Name.com.

Vercel [Pro is $20 a month](https://vercel.com/pricing). According to [this forum](https://www.digitalocean.com/community/questions/can-i-register-my-domain-through-digital-ocean-if-so-how), a domain must be purchased before Digital Ocean points to it. Personally, I'm leaning toward the GitHub option since it's free. What do you think @rupali-codes?

**Comment by rupali-codes** [comment]
> > Hey @rupali-codes 👋 thanks to ask
> > As far I know this is because of it's vercel deployment to fix it we need to do two things first is to deploy it somewhere like on the cloud or Digital Ocean etc. and then assign it a domain name either by the purchase or free one provided to GitHub student by Name.com.
> 
> Vercel [Pro is $20 a month](https://vercel.com/pricing). According to [this forum](https://www.digitalocean.com/community/questions/can-i-register-my-domain-through-digital-ocean-if-so-how), a domain must be purchased before Digital Ocean points to it. Personally, I'm leaning toward the GitHub option since it's free. What do you think @rupali-codes?

Actually, i am not aplicable for applying GSDP 😅, we need to purchase it somehow :)

**Comment by rupali-codes** [comment]
And also, we can just purchase the domain and redirect it in vercel

**Comment by AKACHI-4** [comment]
Yes it can be done 👍

**Comment by AKACHI-4** [comment]
Then this issue is totally yours and all purchasing nd redirecting thing will done by you. Then it should be closed👍

**Comment by rupali-codes** [comment]
> Then this issue is totally yours and all purchasing nd redirecting thing will done by you. Then it should be closed👍

I have purchased the domain, but it would take time to rank on google, i guess

**Comment by AKACHI-4** [comment]
That's great 👍 .. yes, It will be
