### ISSUE TITLE
[OTHER] Broken link in README

### ISSUE THREAD

**Issue by Rishav1707** [rupali-codes/LinksHub#60]
### What would you like to share or ask?

![broken](https://user-images.githubusercontent.com/97666287/213666121-8bff707a-3170-4f85-ba83-ad1c3e639e7c.png)

**Comment by rupali-codes** [comment]
thank you for noticing. would you like to fix this?

**Comment by Rishav1707** [comment]
> thank you for noticing. would you like to fix this?

Already make a PR😊
