### ISSUE TITLE
[UI ENHANCEMENT] Adding transition properties at the social media links when hovered 

### ISSUE THREAD

**Issue by raghav1030** [rupali-codes/LinksHub#604]
We can add the transition properties at the links as they change their background color without any delay when hovered, so it  makes the UI less attractive.
I can work on that and this is related to gssoc'23.

**Comment by rupali-codes** [comment]
> We can add the transition properties at the links as they change their background color without any delay when hovered, so it makes the UI less attractive. I can work on that and this is related to gssoc'23.

Which links you're talking about?

**Comment by raghav1030** [comment]
![Linkshub_ss](https://github.com/rupali-codes/LinksHub/assets/94848646/3d61d5ae-1be1-4014-bf0b-2ccdbf2a736d)
marked in the ss :)

**Comment by rupali-codes** [comment]
Cool, thanks, assigning to you :)
