### ISSUE TITLE
[Feature] Create landing page for LinksHub

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#605]
### Description

As of now, we don't have any landing page for LinksHub. But we are done with the design, you may figma files [here](https://github.com/rupali-codes/LinksHub/tree/main/product-design)

### Additional Info
Multiple contributors can work on this issue

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Jyotipal29** [comment]
i would like to work on this issue please assign to me

**Comment by rupali-codes** [comment]
> i would like to work on this issue please assign to me

Sure :)

**Comment by CBID2** [comment]
> i would like to work on this issue please assign to me

Are you a GSSoC’23 contributor?

**Comment by Jyotipal29** [comment]
yes

**Comment by rupali-codes** [comment]
> yes

Thanks, could you please create a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) until you're working on the issue? that would be much helpful for us to track your activity :)

**Comment by Noothan-am** [comment]
hey @rupali-codes, is this issue still open?

**Comment by rupali-codes** [comment]
> hey @rupali-codes, is this issue still open?

Yes, do you want to work on this?

**Comment by Noothan-am** [comment]
yes

**Comment by rupali-codes** [comment]
> yes

Thanks, would you mind creating a darft PR?

**Comment by Noothan-am** [comment]
> > yes
> 
> Thanks, would you mind creating a draft PR?

yes

**Comment by rupali-codes** [comment]
> > > yes
> > 
> > 
> > Thanks, would you mind creating a draft PR?
> 
> I am creating a new landing page using Figma design mentioned above. it is a new app as of now, then we will integrate it directly into the main website..?? or shall I start directly integrating into the main website??

didn't get you sorry

**Comment by Noothan-am** [comment]
> > > > yes
> > > 
> > > 
> > > Thanks, would you mind creating a draft PR?
> > 
> > 
> > I am creating a new landing page using Figma design mentioned above. it is a new app as of now, then we will integrate it directly into the main website..?? or shall I start directly integrating into the main website??
> 
> didn't get you sorry

ok check this draft pr [#804]

**Comment by rupali-codes** [comment]
@Noothan-am are you still working on the issue? any updates?

**Comment by Noothan-am** [comment]
yes, i am still working on this here is the landing page link for preview 
👉https://my-links-hub.vercel.app/ 
1. CSS needs to be fixed 
2. buttons and links are not active till now  

will fix it soon working on it...
![image](https://github.com/rupali-codes/LinksHub/assets/100135382/49f00f50-32b1-43eb-a594-f07bfe4d57de)

**Comment by CBID2** [comment]
> yes, i am still working on this here is the landing page link for preview 👉https://my-links-hub.vercel.app/
> 
> 1. CSS needs to be fixed
> 2. buttons and links are not active till now
> 
> will fix it soon working on it... ![image](https://user-images.githubusercontent.com/100135382/242852464-49f00f50-32b1-43eb-a594-f07bfe4d57de.png)

It’s look great @Noothan-am! :)

**Comment by rupali-codes** [comment]
@Noothan-am it looks really awesome, thanks :)

**Comment by itsmohit097** [comment]
@rupali-codes 
I'm a GSSOC'23 contributor
Is this issue open ? 
I'm interested to work on this.
Can you assign it to me?

**Comment by itsmohit097** [comment]
> > yes, i am still working on this here is the landing page link for preview 👉https://my-links-hub.vercel.app/
> > 
> > 1. CSS needs to be fixed
> > 2. buttons and links are not active till now
> > 
> > will fix it soon working on it... ![image](https://user-images.githubusercontent.com/100135382/242852464-49f00f50-32b1-43eb-a594-f07bfe4d57de.png)
> 
> It’s look great @Noothan-am! :)



> yes, i am still working on this here is the landing page link for preview 👉https://my-links-hub.vercel.app/
> 
> 1. CSS needs to be fixed
> 2. buttons and links are not active till now
> 
> will fix it soon working on it... ![image](https://user-images.githubusercontent.com/100135382/242852464-49f00f50-32b1-43eb-a594-f07bfe4d57de.png)


hey @Noothan-am  I"m interested to work on this . Can we work together. 
Please let me know your decision.

**Comment by Noothan-am** [comment]
ok

**Comment by itsmohit097** [comment]
hey @Noothan-am 
Just drop a Hii to my discord
Discord username : itsmohit097#8439
Discord id:- 851440337032839179

**Comment by Noothan-am** [comment]
hey @itsmohit097, sent a friend request from @dev13#5749

**Comment by rupali-codes** [comment]
> hey @itsmohit097, sent a friend request from `@dev13#5749`

should we create a sperate channel for it?

**Comment by rupali-codes** [comment]
@Noothan-am & @itsmohit097 we would need to finish this issue as soon as we can, bcz we want to add a few more things on the dashboard, let me know if you need any kinda help

**Comment by Noothan-am** [comment]
hey @rupali-codes were are working on it still. and i have couple of questions

**Comment by itsmohit097** [comment]
@rupali-codes we will update you by tomorrow morning

**Comment by itsmohit097** [comment]
> > hey @itsmohit097, sent a friend request from `@dev13#5749`
> 
> should we create a sperate channel for it?

it will be better @rupali-codes

**Comment by rupali-codes** [comment]
> > > hey @itsmohit097, sent a friend request from `@dev13#5749`
> > 
> > 
> > should we create a sperate channel for it?
> 
> it will be better @rupali-codes

Please share me your discord usernames so i can add you up there. Or have you joined LinksHub's discord?

**Comment by rupali-codes** [comment]
> hey @rupali-codes were are working on it still. and i have couple of questions
> 
> 1. is this landing page to be a home page
> 2. if so which pages should we link to resources, about us , contact us page ?

let's discuss out there

**Comment by rupali-codes** [comment]
> > share me your discord usernames so i can add y
> 
> yes i am in LinksHub discord

what is ur username

**Comment by rupali-codes** [comment]
> dev13#5749

i can not find you
![image](https://github.com/rupali-codes/LinksHub/assets/78981177/35910a52-a64e-43c7-ac2d-deff311611aa)

**Comment by Noothan-am** [comment]
just now i messaged you

**Comment by rupali-codes** [comment]
> itsmohit097 #8439

can u try joining [this](https://discord.gg/83JgbMZJ)

**Comment by afreen-ahmed12** [comment]
hyyy...could you please assign me this problem??

**Comment by rupali-codes** [comment]
> hyyy...could you please assign me this problem??

this issue is assigned to @Noothan-am & @itsmohit097, and i guess they are done with it. So, can you please look for some other issues :)

**Comment by k-deepak04** [comment]
@Noothan-am @itsmohit097 please update your progress.....and try to complete the issue as soon as possible, and let me know if you are facing any issues....or any help needed from my side :)

**Comment by Noothan-am** [comment]
hey @k-deepak04 @rupali-codes , I have exams currently so I will give the code you can assign it to someone else.

**Comment by itsmohit097** [comment]
my exams are over now i can start working on it by tomorrow @rupali-codes

**Comment by k-deepak04** [comment]
okay @itsmohit097 please complete this soon

**Comment by rupali-codes** [comment]
@k-deepak04 this issue has been opened from a while, i'm going to work on this at me own, as i wanna make some improvements in the design it self. 

@Noothan-am & @itsmohit097 thank you for your support and collaboration!

**Comment by k-deepak04** [comment]
@rupali-codes made any progress or need any assistance?

**Comment by rupali-codes** [comment]
> @rupali-codes made any progress or need any assistance?

Not actually, lets close this issue for now. I'll raise a new when i'm ready for it :)
