### ISSUE TITLE
[Add] Interactive Python Tutorial Website

### ISSUE THREAD

**Issue by aashish-aanand** [rupali-codes/LinksHub#606]
### Site URL

https://www.learnpython.org/

### Description of the above provided site

learnpython.org is a free interactive Python tutorial - one of the Interactive Tutorials website. 
This website's vision is to teach coding within the browser using short and effective exercises. By running actual code directly from the web browser, learners will be able to try out coding without installing and executing it locally, which can be hard and redundant for the purpose of learning how to code.
This would be a great addition to the project.

### Category

Languages

### Sub Category

Python

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by aashish-aanand** [comment]
I am a GSSoC 23 contributor, Can you please assign me with this. @rupali-codes

**Comment by CBID2** [comment]
> I am a GSSoC 23 contributor, Can you please assign me with this. @rupali-codes

Done @aashish-aanand! :)
