### ISSUE TITLE
[Add] MIT 6.006 Introduction to Algorithms

### ISSUE THREAD

**Issue by Akshatbhardwaj15** [rupali-codes/LinksHub#608]
### Site URL

https://youtube.com/playlist?list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb

### Description of the above provided site

Explanation of Algorithms concepts. The resources for Algorithm are limited but this course is one of the best Algorithm resource available on Web.
Moreover, this course will help beginners to understand the topic of algorithm. This course contains video tutorials curated by Top MIT faculties. 
This would definitely be a good addition to the resources.

### Category

Youtube

### Sub Category

Algorithms

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Akshatbhardwaj15** [comment]
I am a GSSoC 23 contributor, Can you please assign me with this. @rupali-codes

**Comment by CBID2** [comment]
> I am a GSSoC 23 contributor, Can you please assign me with this. @rupali-codes

You're assigned @Akshatbhardwaj15! :)
