### ISSUE TITLE
[Add] <CSS in Js>Embed CSS directly in your JavaScript components

### ISSUE THREAD

**Issue by itsaakashpatel** [rupali-codes/LinksHub#610]
### Site URL

https://emotion.sh/

### Description of the above provided site

**[Emotion](https://emotion.sh/) is a library designed for writing CSS styles with JS. It potentially solves the issues of selector name collisions.** 

**Advantages:**

- Allows you to define custom components with their styles
- No class policy means dynamic class declaration on run-time
- Type checking

**Alternative:** [Styled components](https://[styled-components](https://styled-components.com/).com/)

### Category

Frontend

### Sub Category

CSS In JS

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by itsaakashpatel** [comment]
@rupali-codes This may be a good addition to Linkhub. I would like to work on this part. Thanks!

**Comment by CBID2** [comment]
> @rupali-codes This may be a good addition to Linkhub. I would like to work on this part. Thanks!

Hey @itsaakashpatel. Before I assign you this issue, are you officially apart of GSSoC'23?

**Comment by itsaakashpatel** [comment]
Yes, I'm.

**Comment by CBID2** [comment]
> @CBID2 Yes, I'm.

You're assigned! :)

**Comment by itsaakashpatel** [comment]
@CBID2 @rupali-codes Here you go: https://github.com/rupali-codes/LinksHub/pull/615

Do let me know if any changes are needed./

Thanks!
