### ISSUE TITLE
[Add] python course by programiz 

### ISSUE THREAD

**Issue by coder-chahal** [rupali-codes/LinksHub#612]
### Site URL

https://www.programiz.com/python-programming

### Description of the above provided site

This is a course for learning Python for beginners. 

### Category

Languages

### Sub Category

Python

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @coder-chahal! :) Are you a GSSoC'23 contributor?

**Comment by coder-chahal** [comment]
Yes @CBID2 I'm GSSoC'23 contributor.

**Comment by CBID2** [comment]
> Yes @CBID2 I'm GSSoC'23 contributor.

Done! :)
