### ISSUE TITLE
To Update Next.js Version to Stable Release for App Router

### ISSUE THREAD

**Issue by s2sharpit** [rupali-codes/LinksHub#613]
### What would you like to share or ask?

Hey @CBID2 

I hope this message finds you well. I would like to bring to your attention an important matter regarding the Next.js version being used in the project. Currently, the project is relying on an outdated version of Next.js, which still includes the beta release of the app directory. It is crucial to update the Next.js version to a more recent release, specifically [Next.js 13.4](https://nextjs.org/blog/next-13-4), where the /app router has been stabilized.

By updating the Next.js version, we can leverage the benefits of the latest stable release and ensure optimal performance, security, and compatibility with the evolving ecosystem. Furthermore, keeping the project up-to-date with the latest framework version will provide us with access to new features, improvements, and bug fixes.

I would be more than willing to take up the responsibility of updating the Next.js version of the project. As an experienced developer, I understand the significance of this task and can ensure a smooth transition by carefully addressing any potential compatibility issues and thoroughly testing the codebase. I am confident that this update will contribute to the overall stability and longevity of the project.

If you find my proposal acceptable, I kindly request that you consider assigning this task to me. I will promptly initiate the process and diligently follow the best practices for version control to ensure a seamless integration of the new Next.js release.

Thank you for your attention to this matter. I look forward to your response and the opportunity to contribute to the improvement of this project.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
I'm a GSSoC 23 contributor.
I request you to label `gssoc23` to this issue and would request you to assign it to me.

**Comment by CBID2** [comment]
Done @s2sharpit

**Comment by s2sharpit** [comment]
Hey, I have created the PR, please review it.
