### ISSUE TITLE
[ML, AI & DATA] Add category for ML, AI and Data Science

### ISSUE THREAD

**Issue by Grogu22** [rupali-codes/LinksHub#614]
### Description

Want to add the following category : 
**ML, AI & DATA**
It will have subcategories related to Machine Learning, Deep Learning, AI and all things data !!
I will add the following subcategories:
1.ML
2.Deep Learning
3.Data Science
Hey @CBID2 created an issue !!

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/83173038/cf809910-b3cd-4ff6-9e30-e49538a9f623)
![image](https://github.com/rupali-codes/LinksHub/assets/83173038/1de2178e-5ade-4176-bcb2-129c7e75a571)
![image](https://github.com/rupali-codes/LinksHub/assets/83173038/1273f0b6-3b22-4ab7-9594-789d9fa0a55e)
![image](https://github.com/rupali-codes/LinksHub/assets/83173038/1059364f-0c9e-4845-b762-4f7815f6f2d0)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Not quite yet @Grogu22! :) [Here's how to raise an issue](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#issues)

**Comment by Grogu22** [comment]
Yeah @CBID2 😅

**Comment by Grogu22** [comment]
It's for the closed PR #611

**Comment by CBID2** [comment]
> Yeah @CBID2 😅

Lol forgive me, it's protocol for me to ask GSSoC'23 members to confirm their participation.

**Comment by Grogu22** [comment]
my bad xD, should've created an Issue first tbh..
