### ISSUE TITLE
[Add] New UI- Generator (flowbite)

### ISSUE THREAD

**Issue by dhrumishah** [rupali-codes/LinksHub#616]
### Site URL

https://flowbite.com/

### Description of the above provided site

It has 600+ UI components, sections, and pages built with the utility classes from Tailwind CSS and designed in Figma.

### Category

Frontend

### Sub Category

UI-Generator

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @dhrumishah! Are you participating in GSSoC’23?

**Comment by dhrumishah** [comment]
> Hi @dhrumishah! Are you participating in GSSoC’23? 

Yes! I'm a contributor
