### ISSUE TITLE
[BUG] Missing category on New Link Issue template 

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#619]
### What would you like to share or ask?

I noticed that “Open Source” does not appear in the category dropdown menu of the “New Link” issue template (see screenshot below).

![Evidence of no Open Source Category in the “New Link” issue template](https://github.com/rupali-codes/LinksHub/assets/105683440/822178fb-dc2d-40b8-b84c-77512163c26e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Tushar98644** [comment]
@CBID2 @rupali-codes i would like to take up the issue under Gssoc'23

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes i would like to take up the issue under Gssoc'23

Done @Tushar98644!😊 Don't forget to link this issue in your pull request! 😊
