### ISSUE TITLE
[Add] <First Interaction>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#620]
### Site URL

https://github.com/marketplace/actions/first-interaction

### Description of the above provided site

An action for filtering pull requests and issues from first-time contributors.

### Category

Other

### Sub Category

GitHub

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Rutujeet** [comment]
I kindly request your consideration in assigning Issue #620 under GSSOC'23 to me.

**Comment by rupali-codes** [comment]
> I kindly request your consideration in assigning Issue #620 under GSSOC'23 to me.

We have assgined you another issue :) please work on one issue at a time

**Comment by Rutujeet** [comment]
Understood

**Comment by Rutujeet** [comment]
> > I kindly request your consideration in assigning Issue #620 under GSSOC'23 to me.
> 
> We have assigned you another issue :) please work on one issue at a time

Understood

**Comment by parma1111** [comment]
Can you assign this issue to me @rupali-codes @CBID2

**Comment by CBID2** [comment]
> Can you assign this issue to me @rupali-codes @CBID2 

Sure @parma1111! :)

**Comment by parma1111** [comment]
Can you merge my open PR in pull request section @CBID2 :)

**Comment by CBID2** [comment]
> Can you merge my open PR in pull request section @CBID2 :)

Sure, link it here first @parma1111.
