### ISSUE TITLE
[Add] TypeScript in Languages section 

### ISSUE THREAD

**Issue by abhijeetnishal** [rupali-codes/LinksHub#622]
### Site URL

https://www.freecodecamp.org/news/learn-typescript-beginners-guide/

### Description of the above provided site

- The link provided (https://www.freecodecamp.org/news/learn-typescript-beginners-guide/) leads to an article titled "Learn TypeScript: A Beginner's Guide" on the FreeCodeCamp website.
- This issue aims to highlight the advantages of TypeScript as a valuable resource for software development. TypeScript, a statically typed superset of JavaScript, brings several benefits to the table, enhancing code quality, maintainability, and developer productivity. By leveraging these advantages, developers can create robust and scalable applications.

### Category

Languages

### Sub Category

TypeScript

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Done @abhijeetnishal.
