### ISSUE TITLE
[Add] React JS Tutorial 

### ISSUE THREAD

**Issue by Akshatbhardwaj15** [rupali-codes/LinksHub#627]
### Site URL

https://youtube.com/playlist?list=PLwGdqUZWnOp3aROg4wypcRhZqJG3ajZWJ

### Description of the above provided site

This course will help beginners to understand the topic of React JS. This course contains video tutorials curated by Vinod Bahadur Thapa.
This would definitely be a good addition to the resources.

### Category

Youtube

### Sub Category

Web Development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Akshatbhardwaj15** [comment]
I am a GSSoC 23 contributor, Can you please assign me with this. @rupali-codes

**Comment by CBID2** [comment]
> I am a GSSoC 23 contributor, Can you please assign me with this. @rupali-codes

Done.
