### ISSUE TITLE
[Add] C++ in languages

### ISSUE THREAD

**Issue by anjaliSilawat** [rupali-codes/LinksHub#629]
### Description

"I would like to enhance the website by adding a dedicated section for C++ programming language. This section will encompass a comprehensive range of resources, including tutorials, guides, examples, and reference materials, to facilitate a comprehensive learning experience for C++ enthusiasts.
I want to work on this @rupali-codes please assign it to me 

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/108583230/38447178-e5ce-4766-8f4d-4a6bb551400b)
As you can see, there are currently no C++ related resources available here. I would like to incorporate those resources and make them accessible to users.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @anjaliSilawat! :) I just assigned you to issue #630. Please work on only one issue at a time.

**Comment by CBID2** [comment]
> > Hi @anjaliSilawat! :) I just assigned you to issue #630. Please work on only one issue at a time.
> 
> 
> 
> yes sure @CBID2  Thank you so much for assigning me issue #630. I will resolve this issue as soon as possible
> 
> After that please assign me the #629 issue as well 😊

If it is still available, then yes @anjaliSilawat! :)

**Comment by anjaliSilawat** [comment]
@CBID2 if this is still available, can I start working on it? Could you please assign it to me?

**Comment by rupali-codes** [comment]
> Contributor

Yes you can now

**Comment by anjaliSilawat** [comment]
@rupali-codes in the Assignees section its shows " no one assigned " so can you please assign it to me
