### ISSUE TITLE
[blog content] < want to add more content in  blog section>

### ISSUE THREAD

**Issue by anjaliSilawat** [rupali-codes/LinksHub#630]
### Description

I am interested in expanding the blog section by adding additional content to enrich the website's blog offerings.
I want to work on this @rupali-codes please assign it to me 

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/108583230/f762d0fd-f993-421e-9e62-6c763cc32c70)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @anjaliSilawat! Are you a GSSoC'23 contributor?

**Comment by anjaliSilawat** [comment]
@CBID2 Thank you so much for assigning me this issue😁
