### ISSUE TITLE
[Add] ColorPick Eyedropper 

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [rupali-codes/LinksHub#632]
### Site URL

https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg

### Description of the above provided site

This is a Google Chrome Extention that has a zoomed eyedropper & color chooser tool that allows you to select color values from webpages.

### Category

Frontend

### Sub Category

"Colors"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @Ishita-Ghosh-25! Before we continue, I just wanted to double check that you’re not in GSSoC ‘23.

**Comment by Ishita-Ghosh-25** [comment]
No @CBID2  I am not participating in GSSoC '23
