### ISSUE TITLE
[Add] Hyperplexed youtube channel for web development 

### ISSUE THREAD

**Issue by Atharva-3000** [rupali-codes/LinksHub#635]
### Site URL

https://www.youtube.com/@Hyperplexed

### Description of the above provided site

This YouTuber has a very intuitive way of teaching web development by redesigning websites along with various effect tutorials in smaller and simpler ways.

### Category

Youtube

### Sub Category

web development, frontend, design inspiration, CSS 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Atharva-3000** [comment]
> Hey @Atharva-3000! :) Are you a GSSoC'23 contributor?

Yeah !

**Comment by CBID2** [comment]
> > Hey @Atharva-3000! :) Are you a GSSoC'23 contributor?
> 
> Yeah !

Done! :)

**Comment by Atharva-3000** [comment]
Thanks, working on it
