### ISSUE TITLE
[Feature] Under the Resources section, add another row Hackathons and include relevant information

### ISSUE THREAD

**Issue by ayushh1804** [rupali-codes/LinksHub#636]
### Description

Under the Resources section in the left pane, we can add a Hackathons section which will include information related to participation in hackathons, blogs related to how to take part in your first hackathon and websites to refer to register for hackathons like devfolio.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/88641651/cea644de-9954-4b13-9354-6c38f1e4a259)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @ayushh1804! Are you a GSSoC'23 contributor?

**Comment by ayushh1804** [comment]
> Hey @ayushh1804! Are you a GSSoC'23 contributor?

yes

**Comment by CBID2** [comment]
Done

**Comment by ayushh1804** [comment]
> @ayushh1804 we can call it **Events** :)

yeah, Events is fine too
