### ISSUE TITLE
[OTHER] adding multiple links

### ISSUE THREAD

**Issue by akkshayTandon** [rupali-codes/LinksHub#640]
### What would you like to share or ask?

Hey, I want to add some links in these:
- projects sub-category under OpenSource category
- python,  javascript, C# sub-category under Languages category
- blogs, e-book, hosting, project ideas sub-category in resources category
- android, computer science subcategory in youtube category
- ReactJS subcategory in frontend category

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @akkshayTando! Just to confirm, you are doing GSSoC’23?

**Comment by akkshayTandon** [comment]
yes

**Comment by CBID2** [comment]
> yes

Done!

**Comment by SamserAliKhan** [comment]
Heya I have some interesting links that can be added here for backend. Noje.js and JavaScript tutorials. I will be happy if you can assign me with this issue.

**Comment by CBID2** [comment]
> Heya I have some interesting links that can be added here for backend. Noje.js and JavaScript tutorials. I will be happy if you can assign me with this issue.

Hi @SamserAliKhan! :) Please it in another issue. It’ll make things more organized.

**Comment by CBID2** [comment]
> Can u say in which one. Because I can see that this is the one to add multiple links.
> 
> 

I mean create a separate issue for the links you want to add. Check the Contributing guide to help you. Sorry for not being clear @SamserAliKhan.
