### ISSUE TITLE
[Feature] add readme badges

### ISSUE THREAD

**Issue by S-ishita** [rupali-codes/LinksHub#641]
### Description

I want to add readme badges.Please assign this issue to me

### Screenshots

![badges](https://github.com/rupali-codes/LinksHub/assets/104543751/35ae9ca9-de31-4a56-8182-172838a0ba61)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @S-ishit! Are you in GSSoC’23? Also, @rupali-codes. What do you think of this?

**Comment by S-ishita** [comment]
Yeah, I raised this issue under GSSOC

**Comment by CBID2** [comment]
> Yeah, I raised this issue under GSSOC

Ok. Personally, I think it's helpful butt I'll wait for @rupali-codes’ response to see.

**Comment by rupali-codes** [comment]
> > Yeah, I raised this issue under GSSOC
> 
> Ok. Personally, I think it's helpful,but I'll wait for @rupali-codes’ response.

I guess we don't need it, as all the information available in the repo itself
