### ISSUE TITLE
[Add] C++ resources in language section

### ISSUE THREAD

**Issue by praharshaAdhikari** [rupali-codes/LinksHub#645]
### Site URL

https://www.youtube.com/watch?v=9Myk2vcK8s8&list=PL_c9BZzLwBRIwEnaRU2LC4GkqxUbD0Auc&index=1

### Description of the above provided site

One of the best Youtube channels to learn programming languages. His series on C++ top notch.

### Category

Languages

### Sub Category

C++

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @praharshaAdhikari! 😊 Are you participating in GSSoC’23?

**Comment by praharshaAdhikari** [comment]
Yes! I am.

**Comment by CBID2** [comment]
> Yes! I am.

Done @praharshaAdhikari! :)

**Comment by programerr01** [comment]
@rupali-codes  Assignee here seems to be inactive, i can complete it

**Comment by rupali-codes** [comment]
> @rupali-codes Assignee here seems to be inactive, i can complete it

sure, thanks

**Comment by rupali-codes** [comment]
@programerr01 are you still working on this issue?
