### ISSUE TITLE
[Feature] <add GitHub Action to organize PRs more>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#646]
### Description

Hey @rupali-codes! :) I just found [this action feature on GitHub](https://github.com/marketplace/actions/close-stale-issues). I noticed that we get a lot of old PRs, so I think adding this action would organize things a bit. What do you think?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Tushar98644** [comment]
@CBID2 Can you be more specific about what the action is supposed to do?

**Comment by CBID2** [comment]
> @CBID2 Can you be more specific about what the action is supposed to do?

From what I've read in the link, it's supposed to automatically close pull requests that have been left opened for a long period of time. 
Now before you ask to work on this @Tushar98644, focus on the one I just assigned to you. 😉

**Comment by Tushar98644** [comment]
> > @CBID2 Can you be more specific about what the action is supposed to do?
> 
> From what I've read in the link, it's supposed to automatically close pull requests that have been left opened for a long period of time. Now before you ask to work on this @Tushar98644, focus on the one I just assigned to you. 😉

oh sorry I should have read the description more carefully, it's mentioned there clearly ........ya sure , raising the pr in some time

**Comment by CBID2** [comment]
> @CBID2 I have created a pr for the earlier assigned issue, may I take up this issue now?

Sure @Tushar98644! 😊
