### ISSUE TITLE
[Add] <Women-Led-Open-Source>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#657]
### Site URL

https://github.com/amandamartin-dev/women-led-open-source

### Description of the above provided site

This is a living document that can serve as a resource for finding people including those identifying as women, transgender people, nonbinary people, and other underrepresented genders leading open source projects and companies, serving as maintainers, or otherwise supporting Open Source.

### Category

Other

### Sub Category

Open Source Projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Rutujeet** [comment]
@CBID2 I kindly request your consideration in assigning Issue #657 under GSSOC'23 to me.

**Comment by Rutujeet** [comment]
> ### Site URL
> 
> https://github.com/amandamartin-dev/women-led-open-source
> 
> ### Description of the above provided site
> 
> This is a living document that can serve as a resource for finding people including those identifying as women, transgender people, nonbinary people, and other underrepresented genders leading open source projects and companies, serving as maintainers, or otherwise supporting Open Source.
> 
> ### Category
> 
> Other
> 
> ### Sub Category
> 
> Open Source Projects
> 
> ### Checklist
> 
> - [X] I have checked the existing issues
> - [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
> - [X] I am willing to work on this issue (optional)
> - [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Rutujeet any updates? are you still working on the issue?

**Comment by Kushagra102** [comment]
@rupali-codes Can you assign me this issue if no one is working on it.

**Comment by CBID2** [comment]
> @rupali-codes Can you assign me this issue if no one is working on it.
> 
> 

Are you in GSSOC @Kushagra102?

**Comment by Kushagra102** [comment]
Yessss

**Comment by CBID2** [comment]
> Yessss
> 
> 

You're assigned @Kushagra102
