### ISSUE TITLE
[Add] <GitHub's Maintainer Community>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#658]
### Site URL

https://maintainers.github.com/auth/signin

### Description of the above provided site

GitHub's Maintainer Community is a private space for maintainers to connect with peers, preview GitHub features, and help us support the open source community.

### Category

Resources

### Sub Category

GitHub

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by parma1111** [comment]
Can you assign this issue to me @CBID2 @rupali-codes

**Comment by CBID2** [comment]
> Can you assign this issue to me @CBID2 @rupali-codes

Done @parma1111! :)

**Comment by parma1111** [comment]
In Resources, there is no subcategory for github
in others , there is subcategory for github, so I have to link it there @CBID2

**Comment by parma1111** [comment]
> > Can you assign this issue to me @CBID2 @rupali-codes
> 
> Done @parma1111! :)

> Done @CBID2
