### ISSUE TITLE
[Add] <OpenSauced to Resources section>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#659]
### Site URL

https://opensauced.pizza/

### Description of the above provided site

OpenSauced is a great tool to display your merged and opened pull requests, highlight your favorite contributions, and find other open source projects to contribute to! 

### Category

Resources

### Sub Category

DevTools 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by parma1111** [comment]
Can you assign this issue  to me @CBID2 @rupali-codes

**Comment by CBID2** [comment]
> Can you assign this issue  to me @CBID2 @rupali-codes 

Finish the one I just assigned and maybe.

**Comment by parma1111** [comment]
> > Can you assign this issue  to me @CBID2 @rupali-codes
> 
> Finish the one I just assigned and maybe.

> Hey @CBID2 I have finished that you assigned me :)
