### ISSUE TITLE
[Add] <Codeacademy Docs to Open Source Projects section>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#660]
### Site URL

https://www.codecademy.com/pages/contribute-docs

### Description of the above provided site

Looking for a way to gain experience in tech writing? Codecademy Docs offer developers and open source enthusiasts a hands-on opportunity to collaborate with other learners. Together, you’ll create free, useful resources for developers and tech community members of all experience levels.

### Category

Other

### Sub Category

Open Source Projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by parma1111** [comment]
Can you assign this issue to me @CBID2 @rupali-codes
