### ISSUE TITLE
[Add] Free SVG illustrations

### ISSUE THREAD

**Issue by Nilesh9106** [rupali-codes/LinksHub#664]
### Site URL

https://freesvgillustration.com/

### Description of the above provided site

Free SVG illustrations are available for any idea you can imagine. You can change the primary and secondary colours of the illustrations to match your project's style guide. Download the illustrations in either PNG or SVG format. premium illustrations are also available.
Here's an example of illustration.
![image](https://github.com/rupali-codes/LinksHub/assets/97864081/e45a009e-9e41-4570-a7e3-bae181191883)

### Category

Frontend

### Sub Category

"illustrations"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Nilesh9106! 😊 Just to confirm, are you participating in GSSOC'23?

**Comment by Nilesh9106** [comment]
yes, I am.

**Comment by CBID2** [comment]
> yes, I am.

Done :)
