### ISSUE TITLE
I would like to add ThapaTechnical Youtube channel link

### ISSUE THREAD

**Issue by Rahul-Bhati** [rupali-codes/LinksHub#667]
### Site URL

https://www.youtube.com/@ThapaTechnical

### Description of the above provided site

This channel is dedicated to the world of website development, offering a wide range of content related to technical aspects, tips and tricks, design principles, and programming. Whether you're a beginner looking to learn the basics or an experienced developer seeking advanced techniques, this channel aims to provide valuable insights and knowledge.

The channel covers various topics within website development, starting with the fundamentals of HTML, CSS, and JavaScript. It offers tutorials and explanations on how to create web pages, style them, and add interactivity using JavaScript. These videos can help you build a solid foundation in web development.

Programming videos on this channel cover different languages and frameworks commonly used in web development, such as Javascript, React, and more. These videos aim to help you understand the core concepts of each language and demonstrate how they can be used to build dynamic and interactive web applications.

Please assign me this issue under GSSOC 23 @rupali-codes 

### Category

Youtube

### Sub Category

Web Development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Rahul-Bhati Sure, but please use a short & clear description. Describing what they exactly teach :))
