### ISSUE TITLE
[Feature] Add 'read more' button when text overflows on the card

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#671]
### Description

Currently, the card looks kinda confusing, if we would a _read more_ button then it would have more clarities. When clicked on the button, it would simply **open the popup** for that specific card.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/6fff56ed-530e-490b-b4e5-9a8f1e72e957)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Isha988** [comment]
@rupali-codes I want to work on this. Would you please assign it to me!?

**Comment by aditya9277** [comment]
Hey @rupali-codes , I want to work on this issue. I already got my 2 PR's merged in your project. I can help solve this issue also. Please assign me this issue.

**Comment by rupali-codes** [comment]
> @rupali-codes I want to work on this. Would you please assign it to me!?

Sure, are you gssoc participant?

**Comment by Isha988** [comment]
> > @rupali-codes I want to work on this. Would you please assign it to me!?
> 
> Sure, are you gssoc participant?

Ya, I am gssoc participant.
