### ISSUE TITLE
[Feature] Update the Contributing.md file

### ISSUE THREAD

**Issue by Tushar98644** [rupali-codes/LinksHub#672]
### Description

As the workflow for closing old pr's has been developed, there is a need to update details in the contributing.md file for contributors . Please refer to pr #655

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Tushar98644** [comment]
@rupali-codes @CBID2 I was thinking of adding an action to close old issues as well

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 I was thinking of adding an action to close old issues as well

Good idea @Tushar98644! :) Raise that as a new issue.
