### ISSUE TITLE
[Add] Enhancement Request: Adding a Blog Link to Resolve a merge conflict on Github in the Open Source Section

### ISSUE THREAD

**Issue by devasyarajguru** [rupali-codes/LinksHub#674]
### Site URL

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

### Description of the above provided site

I would like to propose an enhancement for the open source section of our platform. Specifically, I suggest adding a dedicated blog link titled "Resolve a merge conflict on Github" to provide users with valuable resources and insights related how to solve a merge conflict on Github

Resolving merge conflicts on GitHub can be a crucial part of collaborating with others on a shared codebase. When multiple developers are working on the same project and making changes to the same file or files simultaneously, conflicts can arise during the process of merging those changes together. These conflicts occur when Git, the version control system used by GitHub, is unable to automatically merge the conflicting changes.

### Category

Open Source

### Sub Category

blog

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Sure @devasyarajguru! :) Just to confirm, you're in GSSoC'23?

**Comment by devasyarajguru** [comment]
Yes @CBID2  I am in GSSOC'23

**Comment by CBID2** [comment]
> Yes @CBID2  I am in GSSOC'23

Ok go right ahead
