### ISSUE TITLE
[Add] Awesome Certificates for showcase

### ISSUE THREAD

**Issue by dhrumilpatel30** [rupali-codes/LinksHub#680]
### Site URL

https://github.com/PanXProject/awesome-certificates

### Description of the above provided site

A curated of list of IT, computer science and business courses with certificates & digital badges to earn upon completion.

Each course on the list is free to take as well as the badge and certificate.

### Category

Other

### Sub Category

Certifications

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @dhrumilpatel30! 😊 Again please work on one issue at a time
