### ISSUE TITLE
[Add] List of Learning resources for programmers

### ISSUE THREAD

**Issue by dhrumilpatel30** [rupali-codes/LinksHub#681]
### Site URL

https://rentry.co/ProgrammingLearningResources

### Description of the above provided site

List containing hundreds of best learning resources available for programmers.
Categorised in languages and technologies for easy navigation.

### Category

Other

### Sub Category

websites

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @dhrumilpatel30! :) Just to confirm, you're in GSSoC'23?

**Comment by dhrumilpatel30** [comment]
> Hey @dhrumilpatel30! :) Just to confirm, you're in GSSoC'23?

yes
