### ISSUE TITLE
[Add] Free Programming challenges for developers.

### ISSUE THREAD

**Issue by dhrumilpatel30** [rupali-codes/LinksHub#682]
### Site URL

https://app.codecrafters.io/tracks

### Description of the above provided site

The best website for developers to practice and learn about different languages through dedicated tracks for each.
It provides practice via making you to build your own something and learn along with it.  

### Category

Other

### Sub Category

Dev Tools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [x] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @dhrumilpatel30! :) please work on one issue at a time.

**Comment by Abhishek-00** [comment]
Hii
I am GSSOC23 contributor. Can you assign this issue to me.

**Comment by dhrumilpatel30** [comment]
please assign so i can work on this

**Comment by dhrumilpatel30** [comment]
> > please assign so i can work on this
> 
> Would you like to raise a single PR for closing all of this issues? (in which you are adding links)

yes sure

**Comment by CBID2** [comment]
> Hii I am GSSOC23 contributor. Can you assign this issue to me.

Hi @Abhishek-00! :) @dhrumilpatel30 is already assigned to this issue. If you're able to, consider reviewing their pull request once it's published. Check out [the part where it says "do a code review of someone's PR". It takes to my article on reviewing pull requests](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#remarks-)! :)

**Comment by dhrumilpatel30** [comment]
> > Hii I am GSSOC23 contributor. Can you assign this issue to me.
> 
> Hi @Abhishek-00! :) @dhrumilpatel30 is already assigned to this issue. If you're able to, consider reviewing their pull request once it's published. Check out [the part where it says "do a code review of someone's PR". It takes to my article on reviewing pull requests](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#remarks-)! :)

hey @CBID2 could I do a single pull for all 5 new links add or different for each issue.

**Comment by CBID2** [comment]
> hey @CBID2 could I do a single pull for all 5 new links add or different for each issue.

Hi @dhrumilpatel30! :) You can try, but if @rupali-codes, me, or any other review find too many issues and resolve conflicts per the [Contributing guidelines](https://github.com/rupali-codes/linkshub/blob/main/CONTRIBUTING.md#making-pull-requests), we will have to close it. So, I highly recommend creating a separate PR for each link and linking them back to this issue.

**Comment by dhrumilpatel30** [comment]
> > hey @CBID2 could I do a single pull for all 5 new links add or different for each issue.
> 
> Hi @dhrumilpatel30! :) You can! :)

Thanks, I will soon add it then.
