### ISSUE TITLE
[Feature] : Workflow for closing old issues 

### ISSUE THREAD

**Issue by Tushar98644** [rupali-codes/LinksHub#688]
### Description

Now that we have a workflow for closing old pr's , having one workflow for closing old issues would come in handy as well

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Tushar98644** [comment]
@rupali-codes @CBID2 I would like to take up this issue

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 I would like to take up this issue

Just to confirm, you’re in GSSoC’23?

**Comment by Tushar98644** [comment]
> > @rupali-codes @CBID2 I would like to take up this issue
> 
> Just to confirm, you’re in GSSoC’23?

yes
