### ISSUE TITLE
[Add] Full Stack Javascript by the odin project

### ISSUE THREAD

**Issue by navharsh** [rupali-codes/LinksHub#697]
### Site URL

https://www.theodinproject.com/paths/full-stack-javascript

### Description of the above provided site

This site takes you through our entire JavaScript curriculum. You'll learn everything you need to know to create beautiful responsive websites from scratch using JavaScript and NodeJS.

### Category

Languages

### Sub Category

JavaScript

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by mhdamaan79** [comment]
I would be happy to contribute and work on this issue. If it hasn't been assigned yet. I'm in **GSSoC'23**. Thank you! @rupali-codes

**Comment by CBID2** [comment]
Ooh sorry @mhdamaan79! There's a [pull request](https://github.com/rupali-codes/LinksHub/pull/698) for this already. I highly recommend reviewing it. It's a great way to see how to contribute to LinksHub, practice your written communication and collaboration skills, and gain some green squares on GitHub! :) [Here’s an article on how to review a PR](https://www.freecodecamp.org/news/code-review-tips/)

**Comment by mhdamaan79** [comment]
No worries at all. I'll review the existing pull request and learn from it. @CBID2
