### ISSUE TITLE
[Add] Add links to websites which have a great list of open-source projects

### ISSUE THREAD

**Issue by Isha988** [rupali-codes/LinksHub#699]
### Site URL

https://www.gsocorganizations.dev/

### Description of the above provided site

A site for viewing and analyzing the info of the organizations participating in Google Summer of Code.

👉 A couple of similar websites are also there which I want to add.

### Category

Open Source

### Sub Category

Projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks Isha
