### ISSUE TITLE
[FEATURE] Add Github link to the site

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#7]
Add this [https://github.com/rupali-codes/LinksHub](https://github.com/rupali-codes/LinksHub) link to site along with github logo.

**Comment by anshit-2003** [comment]
Hey, Can you assign me this issue?
I've been looking for issues to contribute to, I'm a new to open source.

**Comment by JoshHargreaves** [comment]
I have picked this one up and opened a pull request.

**Comment by hparashar27** [comment]
hey , can you please assign it to me

**Comment by rupali-codes** [comment]
@JoshHargreaves are you still working on it?

**Comment by JoshHargreaves** [comment]
Hi yep i am just had a busy day yesterday.
