### ISSUE TITLE
Add  1001 fonts

### ISSUE THREAD

**Issue by binadiegha** [rupali-codes/LinksHub#70]
### URL

https://www.1001fonts.com/

### Description of the above provided site

1001 fonts is a platform that offers 42933 free fonts in 24214 families · Free licenses for commercial use · Direct font downloads · Mac · Windows · Linux.

### Category

Frontend

### Sub Category

fonts

**Comment by rupali-codes** [comment]
Thank you,

**Comment by AdekeyeAdeniyi** [comment]
@rupali-codes  Can I add this to the font card lists?

**Comment by rupali-codes** [comment]
@AdekeyeAdeniyi go-ahead!

**Comment by AdekeyeAdeniyi** [comment]
All right.

**Comment by AdekeyeAdeniyi** [comment]
@rupali-codes completed

**Comment by binadiegha** [comment]
🚀🚀🚀
