### ISSUE TITLE
I want to add Java resources under language section and we can add even more languages 

### ISSUE THREAD

**Issue by P766-spec** [rupali-codes/LinksHub#703]
### Description

THere are currently 4 languages in this section, so I am willing to add the section of Java as well as Nodejs, so it will be even more helpful if all language resources are in one place, and that is the only aim of LINKSHUB.  So, please Assign this to me! @rupali-codes 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by P766-spec** [comment]
Okay!

**Comment by rupali-codes** [comment]
> Okay!

Sure

**Comment by P766-spec** [comment]
Thank you!

**Comment by P766-spec** [comment]
Done with this addition of java resouces and created the PR for the same with #880
