### ISSUE TITLE
Add Framer Motion

### ISSUE THREAD

**Issue by Leeyah-123** [rupali-codes/LinksHub#71]
### URL

https://www.framer.com/motion

### Description of the above provided site

Framer Motion is a production-ready motion library for React from Framer (https://www.framer.com/).

It's simple yet powerful, allowing you to express complex user interactions with robust, semantic markup.

### Category

Frontend

### Sub Category

animations

**Comment by binadiegha** [comment]
I can pick this up, if it's still available

**Comment by rupali-codes** [comment]
sure, go-ahead @binadiegha

**Comment by Leeyah-123** [comment]
Thanks but I already did and am about to submit a pull request

**Comment by rupali-codes** [comment]
ahh, okay thank you
