### ISSUE TITLE
FrontEnd Angular material

### ISSUE THREAD

**Issue by Rishabh3243** [rupali-codes/LinksHub#714]
### Site URL

https://www.tutorialspoint.com/angular_material/index.htm

### Description of the above provided site

Free online material for learning Angular

### Category

Frontend

### Sub Category

Angular

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Rishabh3243! :) Just to confirm, are you participating in GSSOC'23? Also don't forget to check the " I am willing to work on this issue (optional)" box so your PR will count for the program.

**Comment by Rishabh3243** [comment]
Yup

**Comment by rupali-codes** [comment]
@Rishabh3243 are you still working on it?

**Comment by Rishabh3243** [comment]
Yes

**Comment by k-deepak04** [comment]
okay closing this
