### ISSUE TITLE
[Feature] <Add GitHub Action to automatically close Pull Requests that are not linked to an issue>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#715]
### Description

I noticed that we have a lot of pull requests that don't mention the issue that they address. I think having this [GitHub Action](https://github.com/marketplace/actions/close-pull-requests-with-label) would be helpful with this problem.

### Additional Info

 Multiple contributors can work on this with me. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Isha988** [comment]
@CBID2 I want to work on this issue under gssoc program. I have never worked on GitHub Action but I am interested in learning more about it.

**Comment by ujjawaltyagii** [comment]
@CBID2 okay ! So, we have add GSSoC label + level here and assignee update right ?

**Comment by CBID2** [comment]
> @CBID2 okay ! So, we have add GSSoC label + level here and assignee update right ?

Yup @ujjawaltyagii
