### ISSUE TITLE
[OTHER] Viisibility issue

### ISSUE THREAD

**Issue by Leeyah-123** [rupali-codes/LinksHub#72]
### What would you like to share or ask?

![Screenshot from 2023-01-23 12-18-56](https://user-images.githubusercontent.com/101122860/214027523-1689570d-0ccf-41ed-bfbb-9e64db81c47a.png)

I would like to suggest a higher constrast between the "Links" text in the header for improved visibility.

**Comment by rupali-codes** [comment]
Thank you for noticing, we are currently working on this

**Comment by rupali-codes** [comment]
it has been fixed :)
