### ISSUE TITLE
Want to add new resource / free course for reactjs part.

### ISSUE THREAD

**Issue by P766-spec** [rupali-codes/LinksHub#720]
### Description

There are may resources for Reactjs  out there , so I want to add more resources for the same.
So @rupali-codes  kindle assign me to do so.
Thank you!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Could you describe them please?

**Comment by rupali-codes** [comment]
This issue was closed bcz of inactivity
