### ISSUE TITLE
[Feature] <Add 404 error page >

### ISSUE THREAD

**Issue by PatilHarshh** [rupali-codes/LinksHub#723]
### Description

@rupali-codes  error page not added to project i am intrested to contribute please assign it to me

### Screenshots

![Screenshot (60)](https://github.com/rupali-codes/LinksHub/assets/120102234/3682ee32-57f4-4ba1-8783-e69127ad864a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Interesting idea @PatilHarshh! :) How can LinksHub benefit from this contribution?

**Comment by PatilHarshh** [comment]
see @CBID2  when i put anything after the url it show 404 error but not good looking

**Comment by CBID2** [comment]
> see @CBID2  when i put anything after the url it show 404 error but not good looking
> 
> 

I guess that could work @PatilHarshh

**Comment by PatilHarshh** [comment]
hello @CBID2 i want little guidance to do this

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by rupali-codes** [comment]
> This issue has been inactive for a long time I would like to work on this issue Please assign

Sure, you  can work on this issue, assigning to you

**Comment by rupali-codes** [comment]
@sagnik-p are you a gssoc'23 contributor?

**Comment by sagnik-p** [comment]
Yes Ma'am, I am a gssoc 2023 contributor



Just confirming, 
I just have to add errorpage.html 
Right?

And should there be redirect to home page option in that error page?
Thanks

**Comment by PatilHarshh** [comment]
Hey @rupali-codes I was done with work! Just raising pr , may I proceed or what!?

**Comment by rupali-codes** [comment]
> Hey @rupali-codes I was done with work! Just raising pr , may I proceed or what!?

as you were inactive, we have assigned this issue to @sagnik-p :)

**Comment by k-deepak04** [comment]
@rupali-codes @CBID2 i have idea and can design the page also link it to the routes
let me know if it's done or shall i proceed with it?

**Comment by PatilHarshh** [comment]
@rupali-codes Hey  may I proceed now as I initiated this issue ?

**Comment by k-deepak04** [comment]
> @rupali-codes Hey may I proceed now as I initiated this issue ?

@PatilHarshh yes you can proceed
please complete this with priority

@rupali-codes @CBID2 let us know if it's still yet to be done or this feature is there in the site

once they give confirmation @PatilHarshh you can proceed

**Comment by rupali-codes** [comment]
@PatilHarshh you may Proceed, assigning to you
