### ISSUE TITLE
[Add] <Want to add new animation tool link>

### ISSUE THREAD

**Issue by Soumyajit2825** [rupali-codes/LinksHub#724]
### Site URL

https://www.minimamente.com/project/magic/

### Description of the above provided site

It is yet another CSS-powered animation library—this time, bearing magical powers. This library is impressive to say the least, offering top-notch features and functionalities, and it integrates well with other libraries such as Animate.css.

Using the library’s presets, you can create magical effects such as TwisterInDown, vanish, swap and many more. Similarly, it provides other animation effects like bling, static, and perspective. Overall, the Magic Animations library is a must-try animation library for UI designers.

### Category

Frontend

### Sub Category

animations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Sounds cool

**Comment by Soumyajit2825** [comment]
@rupali-codes PR done
Thank You for your concern
