### ISSUE TITLE
[Add] Free Resource for React Js under frontend category

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#729]
### Site URL

https://fullstackopen.com/en/about/

### Description of the above provided site

This course serves as an introduction to modern web application development with JavaScript. The main focus is on building single page applications with ReactJS that use REST APIs built with Node.js. The course also contains a section on GraphQL, a modern alternative to REST APIs.

### Category

Frontend

### Sub Category

React Js

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### Note

I have experience contributing to various projects in open-source, and I have chosen LinksHub to work on GSSoC'23 because of its high standards and guidelines, which give it credibility. 
Therefore, I kindly request permission to work on different issues simultaneously.

**Comment by rupali-codes** [comment]
Thanks, but as per our CONTRIBUTING guidelines, you can work on only ONE issue at a time :)
