### ISSUE TITLE
[OTHER] User Experience Improvement

### ISSUE THREAD

**Issue by Leeyah-123** [rupali-codes/LinksHub#73]
### What would you like to share or ask?

I would like to ask for the navbar to be made to close when a user clicks outside of the navbar, or on a link in the navbar

### Additional information

I will love to add this feature as my first open source contribution

**Comment by rupali-codes** [comment]
Hey, thank you for taking interest in, we are not sure how it will look like, can you explain a bit more or just create a PR.
