### ISSUE TITLE
[OTHER] Few Important Queries

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#731]
### What would you like to share or ask?

1. I have some ideas for categories that I would like to add. Which issue form should I use? Should I use the link form? Additionally, should the category be something new since there are no contributing guidelines regarding adding categories?

2. Furthermore, besides categories or links, what else can I contribute? Could you provide some ideas on how you are looking to expand this project? I am interested in working on major features beyond just links or categories.

3. If I have to add 25 or more links to a category, do I need to create 25 separate issues? Also, what would be the level of a GSSoC issue that includes multiple links? Adding 25 links in a single issue would typically be considered equivalent to 25 Level 1 tasks. However, it might be inefficient and burdensome for both contributors and maintainers to handle 25+ separate issues. It could result in unnecessary energy expenditure and increased review workload. Could you please clarify the recommended approach for this situation?

> These questions will help clarify the situation and make it easier for me to work, as I will be engaged in this for three months. Therefore, I kindly request that you provide answers to these questions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by ujjawaltyagii** [comment]
I think its not possible to mark level 25 to any PR/Issue so that won't work and yes its true that opening 25 PRs just for adding links for different resources can be overwhelming for maintainers ! 

And I am also interesting in knowing the future plans as well like is there any planned structure or its just about adding links ?

**Comment by CBID2** [comment]
Hi @Anmol-Baranwal! I agree with @ujjawaltyagii's sentiment on creating 25 PRs/issues would be overwhelming for me and Rupali. It would be best to keep it to one issue/ PR. To answer your second question, I will update you on that.

**Comment by Anmol-Baranwal** [comment]
> Hi @Anmol-Baranwal! I agree with @ujjawaltyagii's sentiment on creating 25 PRs/issues would be overwhelming for me and Rupali. It would be best to keep it to one issue/ PR. To answer your second question, I will update you on that.

So, please give clarification on numbers, like how many links would I need to add in a single PR to make it level 2 or level 3.

**Comment by CBID2** [comment]
> > Hi @Anmol-Baranwal! I agree with @ujjawaltyagii's sentiment on creating 25 PRs/issues would be overwhelming for me and Rupali. It would be best to keep it to one issue/ PR. To answer your second question, I will update you on that.
> 
> 
> 
> So, please give clarification on numbers, like how many links would I need to add in a single PR to make it level 2 or level 3.

To make a Level 2 contribution, you'd have to be a non-code-related contribution(e.g., improving the documentation). For level 3, the contribution has to be code-related. So if you want to add some sources, it's Level one.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal @ujjawaltyagii & @CBID2 so, we do have lots of future plans for linkshub, but the current one we want to do is add a upvoting feature for links, so that would be easy for users to identify the best resources, and for that we would need to eastablish database and stuffs. Also, linkshub is 100% open source, so if you personally have any suggestions or anything you'd like to add, feel free to mention that :)

**Comment by CBID2** [comment]
> @Anmol-Baranwal @ujjawaltyagii & @CBID2 so, we do have lots of future plans for linkshub, but the current one we want to do is add a upvoting feature for links, so that would be easy for users to identify the best resources, and for that we would need to eastablish database and stuffs. Also, linkshub is 100% open source, so if you personally have any suggestions or anything you'd like to add, feel free to mention that :)

@Anmol-Baranwal, here's the voting featuring Rupali is referring to: #495

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal @ujjawaltyagii & @CBID2 so, we do have lots of future plans for linkshub, but the current one we want to do is add a upvoting feature for links, so that would be easy for users to identify the best resources, and for that we would need to eastablish database and stuffs. Also, linkshub is 100% open source, so if you personally have any suggestions or anything you'd like to add, feel free to mention that :)

I will get back to you after detailed analysis, give me a couple of days.

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal @ujjawaltyagii & @CBID2 so, we do have lots of future plans for linkshub, but the current one we want to do is add a upvoting feature for links, so that would be easy for users to identify the best resources, and for that we would need to eastablish database and stuffs. Also, linkshub is 100% open source, so if you personally have any suggestions or anything you'd like to add, feel free to mention that :)
> 
> I will get back to you after detailed analysis, give me a couple of days.

Sure

**Comment by Anmol-Baranwal** [comment]
> Sure

@CBID2 @rupali-codes 
I have provided a detailed description of the architecture, considering various aspects. However, it's important to acknowledge that there may be downsides or areas that I might have overlooked. Despite that, I firmly believe that this architecture serves as a strong foundation for developing a scalable application.

To implement the upvote feature for each resource in your repository, we can leverage the power of Firebase with Firestore as our database and provide authentication options using passwordless or authentication sign-in.  Let's delve into the detailed architecture and see how we can build this exciting feature together!

1. Database Structure:

   - Firestore Collections:

      - Resources: This collection will store the details of each resource, including its unique identifier, title, description, URL, and the number of upvotes it has received.
      - Users: This collection will store user details and their associated upvoted resources.

   - Firestore Documents:

      - Each resource in the "Resources" collection will have a document with fields for title, description, URL, and upvotes.
      - Each user in the "Users" collection will have a document with fields for their unique identifier and an array of upvoted resource IDs.

2. Authentication:

   - Firebase Authentication: We'll make use of Firebase Authentication to authenticate the users. Whether we choose passwordless authentication or authentication sign-in, Firebase will provide a seamless and secure authentication experience for the users.

3. User Actions:

   > Let's explore the process of upvoting a resource, ensuring a smooth and engaging user experience:

   - Upvoting a Resource: When a user clicks on the upvote button for a resource, we can handle the action by performing the following steps:
      - Authenticate the user: Ensure the user is authenticated before allowing them to upvote.
      - Update the Resource's Upvote Count: Retrieve the resource's document from the "Resources" collection, increment the upvote count, and save the updated document.
      - Associate the Upvote with the User: To keep track of each user's upvoted resources, we'll retrieve the user's document from the "Users" collection using their unique identifier. We'll add the resource's ID to the user's array of upvoted resource IDs and save the updated document.

4. Displaying Resources:
Our next step is to fetch and display the resources in our application. By retrieving the resources from the "Resources" collection and sorting them based on the number of upvotes in descending order, we'll ensure that resources with higher upvote counts appear at the top. This will provide users with a curated list of the most popular and valuable resources.

5. Real-time Updates:

To add a touch of real-time magic to our application, we'll set up Firestore listeners. These listeners will keep an ear out for any changes in the upvote count of resources. Whenever an upvote count changes, we'll update the UI in real-time, allowing users to witness the impact of their upvotes immediately.

By following this architecture, you can enable users to upvote resources, store the upvote information in Firestore, authenticate users using Firebase Authentication, and display the resources sorted by upvote count. This approach allows for scalability, real-time updates, and a secure authentication mechanism using Firebase.

<hr>

### Explanation of associating the upvote with the user:

<br>

Associating the upvote with the user by storing the resource's ID in the user's document allows us to keep track of which resources each user has upvoted. This information is useful for various purposes, such as:

1. Preventing Multiple Upvotes: By storing the upvoted resource IDs in the user's document, we can check if a user has already upvoted a particular resource. This helps ensure that a user can only upvote a resource once, maintaining the integrity of the voting system.

2. User-Specific Upvote History: Storing the upvoted resource IDs in the user's document allows us to provide personalized features, such as displaying the user's upvote history or allowing them to easily access resources they have upvoted in the past.

3. Customized Recommendations: By analyzing the upvoted resource IDs associated with each user, we can gather insights into their preferences and interests. This information can be used to provide personalized recommendations or suggestions for similar resources that the user might find interesting.

4. Sorting and Ranking: Storing the upvote information in the user's document enables you to implement sorting and ranking algorithms based on the number of upvotes per resource. We can retrieve the user's upvoted resource IDs and use them to calculate popularity scores or generate rankings to determine the order in which resources are displayed.

<hr>

While I am willing to contribute to this issue, I have my own major projects for my college that demand my attention. Therefore, I might not be able to solely handle this task. However, I am open to collaborating with others to address this issue and bring it to LinksHub. 

I strongly encourage you to share your thoughts :)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please answer this as well:

> https://github.com/rupali-codes/LinksHub/commits?author=CBID2

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/1d15684c-5a65-41b4-bdcc-3615e0f7ba7f)

As shown here, we worked together on adding an issue form for categories.

However, the commit is not visible in my history.

> https://github.com/rupali-codes/LinksHub/commits?author=Anmol-Baranwal

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/83ef91c1-f2c9-4bcb-af22-816825b7ce29)

I wanted to ensure that this will not be an issue for my contribution in GSSoC'23, right?

**Comment by CBID2** [comment]
> @rupali-codes 
> 
> Please answer this as well:
> 
> 
> 
> > https://github.com/rupali-codes/LinksHub/commits?author=CBID2
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/1d15684c-5a65-41b4-bdcc-3615e0f7ba7f)
> 
> 
> 
> As shown here, we worked together on adding an issue form for categories.
> 
> 
> 
> However, the commit is not visible in my history.
> 
> 
> 
> > https://github.com/rupali-codes/LinksHub/commits?author=Anmol-Baranwal
> 
> 
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/83ef91c1-f2c9-4bcb-af22-816825b7ce29)
> 
> 
> 
> I wanted to ensure that this will not be an issue for my contribution in GSSoC'23, right?

I guess not @Anmol-Baranwal.

**Comment by CBID2** [comment]
Love your idea for the voting system @Anmol-Baranwal! 😊 Also, if you're looking for another contribution to do, [here's one I started](https://github.com/rupali-codes/LinksHub/issues/774). I created the [PR](https://github.com/rupali-codes/LinksHub/pull/810),
but I need your advice on if it fits the typescript file.

**Comment by Anmol-Baranwal** [comment]
> Love your idea for the voting system @Anmol-Baranwal! 😊 Also, if you're looking for another contribution to do, [here's one I started](https://github.com/rupali-codes/LinksHub/issues/774). I created the [PR](https://github.com/rupali-codes/LinksHub/pull/810),
> but I need your advice on if it fits the typescript file. 

I am currently in the process of learning TypeScript, and I will be busy until tomorrow afternoon. However, I assure you that I will make an effort to contribute as much as I can once I have the time.

**Comment by CBID2** [comment]
> > Love your idea for the voting system @Anmol-Baranwal! 😊 Also, if you're looking for another contribution to do, [here's one I started](https://github.com/rupali-codes/LinksHub/issues/774). I created the [PR](https://github.com/rupali-codes/LinksHub/pull/810),
> > but I need your advice on if it fits the typescript file. 
> 
> I am currently in the process of learning TypeScript, and I will be busy until tomorrow afternoon. However, I assure you that I will make an effort to contribute as much as I can once I have the time.

Thanks @Anmol-Baranwal!

**Comment by rupali-codes** [comment]
> > Sure
> 
> @CBID2 @rupali-codes I have provided a detailed description of the architecture, considering various aspects. However, it's important to acknowledge that there may be downsides or areas that I might have overlooked. Despite that, I firmly believe that this architecture serves as a strong foundation for developing a scalable application.
> 
> To implement the upvote feature for each resource in your repository, we can leverage the power of Firebase with Firestore as our database and provide authentication options using passwordless or authentication sign-in. Let's delve into the detailed architecture and see how we can build this exciting feature together!
> 
> 1. Database Structure:
>    
>    * Firestore Collections:
>      
>      * Resources: This collection will store the details of each resource, including its unique identifier, title, description, URL, and the number of upvotes it has received.
>      * Users: This collection will store user details and their associated upvoted resources.
>    * Firestore Documents:
>      
>      * Each resource in the "Resources" collection will have a document with fields for title, description, URL, and upvotes.
>      * Each user in the "Users" collection will have a document with fields for their unique identifier and an array of upvoted resource IDs.
> 2. Authentication:
>    
>    * Firebase Authentication: We'll make use of Firebase Authentication to authenticate the users. Whether we choose passwordless authentication or authentication sign-in, Firebase will provide a seamless and secure authentication experience for the users.
> 3. User Actions:
>    > Let's explore the process of upvoting a resource, ensuring a smooth and engaging user experience:
>    
>    
>    
>    * Upvoting a Resource: When a user clicks on the upvote button for a resource, we can handle the action by performing the following steps:
>      
>      * Authenticate the user: Ensure the user is authenticated before allowing them to upvote.
>      * Update the Resource's Upvote Count: Retrieve the resource's document from the "Resources" collection, increment the upvote count, and save the updated document.
>      * Associate the Upvote with the User: To keep track of each user's upvoted resources, we'll retrieve the user's document from the "Users" collection using their unique identifier. We'll add the resource's ID to the user's array of upvoted resource IDs and save the updated document.
> 4. Displaying Resources:
>    Our next step is to fetch and display the resources in our application. By retrieving the resources from the "Resources" collection and sorting them based on the number of upvotes in descending order, we'll ensure that resources with higher upvote counts appear at the top. This will provide users with a curated list of the most popular and valuable resources.
> 5. Real-time Updates:
> 
> To add a touch of real-time magic to our application, we'll set up Firestore listeners. These listeners will keep an ear out for any changes in the upvote count of resources. Whenever an upvote count changes, we'll update the UI in real-time, allowing users to witness the impact of their upvotes immediately.
> 
> By following this architecture, you can enable users to upvote resources, store the upvote information in Firestore, authenticate users using Firebase Authentication, and display the resources sorted by upvote count. This approach allows for scalability, real-time updates, and a secure authentication mechanism using Firebase.
> 
> ### Explanation of associating the upvote with the user:
> 
> Associating the upvote with the user by storing the resource's ID in the user's document allows us to keep track of which resources each user has upvoted. This information is useful for various purposes, such as:
> 
> 1. Preventing Multiple Upvotes: By storing the upvoted resource IDs in the user's document, we can check if a user has already upvoted a particular resource. This helps ensure that a user can only upvote a resource once, maintaining the integrity of the voting system.
> 2. User-Specific Upvote History: Storing the upvoted resource IDs in the user's document allows us to provide personalized features, such as displaying the user's upvote history or allowing them to easily access resources they have upvoted in the past.
> 3. Customized Recommendations: By analyzing the upvoted resource IDs associated with each user, we can gather insights into their preferences and interests. This information can be used to provide personalized recommendations or suggestions for similar resources that the user might find interesting.
> 4. Sorting and Ranking: Storing the upvote information in the user's document enables you to implement sorting and ranking algorithms based on the number of upvotes per resource. We can retrieve the user's upvoted resource IDs and use them to calculate popularity scores or generate rankings to determine the order in which resources are displayed.
> 
> While I am willing to contribute to this issue, I have my own major projects for my college that demand my attention. Therefore, I might not be able to solely handle this task. However, I am open to collaborating with others to address this issue and bring it to LinksHub.
> 
> I strongly encourage you to share your thoughts :)

loved it, thanks!!!

**Comment by k-deepak04** [comment]
@Anmol-Baranwal if you are clear with your queries shall i close this issue?
we can have discussion on our discord channel
closing this 
Thank you your your valuable ideas :)
if anything needed please reach out on discord

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal if you are clear with your queries shall i close this issue?
> we can have discussion on our discord channel
> closing this 
> Thank you your your valuable ideas :)
> if anything needed please reach out on discord

Sure.
