### ISSUE TITLE
[BUG] Overflow of content in small devices

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#732]
### Description

I have attached a screenshot, and the box is overflowing horizontally due to a lack of responsiveness.

What I can do is check the responsiveness of each category on very small devices.

### Screenshots

![responsiveness](https://github.com/rupali-codes/LinksHub/assets/74038190/29613209-4953-4f5e-b49c-37aa29154767)

### Any additional information?

I will make sure to review the code for the necessary conventions and code style to ensure I follow the same.

Additionally, if you require me to adjust the font size very specifically, please let me know in advance.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
I noticed this too @Anmol-Baranwal. Good observation! :)  Just to confirm, are you participating in GSSOC'23?

**Comment by Anmol-Baranwal** [comment]
> I noticed this too @Anmol-Baranwal. Good observation! :)  Just to confirm, are you participating in GSSOC'23?

Yep, I am participating in GSSoC'23.

**Comment by CBID2** [comment]
> > I noticed this too @Anmol-Baranwal. Good observation! :)  Just to confirm, are you participating in GSSOC'23?
> 
> 
> 
> Yep, I am participating in GSSoC'23. 
> 
> 
> 
> Hi, @CBID2 
> 
> I cannot find a specific file to change only this one page. If I make any changes, it will affect every page. It would be helpful if you could provide an overview of which component, file, or layout I should modify to address this issue.

I highly recommend asking @rupali-codes for this.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal its _src/components/Cards/CardsList.tsx_
