### ISSUE TITLE
[Add] : Adding a open-source project

### ISSUE THREAD

**Issue by ujjawaltyagii** [rupali-codes/LinksHub#735]
### Site URL

https://github.com/rohitdasu/projectmate

### Description of the above provided site

It's a open-source platform to connect with experienced maintainers, and collaborate with a community of passionate contributors.

### Category

Open Source

### Sub Category

Projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ujjawaltyagii** [comment]
@CBID2 @rupali-codes could you assign this issue to me under GSSoC label

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes could you assign this issue to me under GSSoC label 

Done @ujjawaltyagii

**Comment by rupali-codes** [comment]
> @CBID2 @rupali-codes could you assign this issue to me under GSSoC label

Are you participating in GSSoC? 👀

**Comment by ujjawaltyagii** [comment]
@rupali-codes yep 😅 !!

**Comment by rupali-codes** [comment]
> @rupali-codes yep 😅 !!

Awesome!
