### ISSUE TITLE
[Feature] Adding more Youtube Resources in Computer Science Section

### ISSUE THREAD

**Issue by ayushkumarbhadani** [rupali-codes/LinksHub#739]
### Description

There are more resources available for the Computer Science section under Youtube. I would like to add them.

Here are a few examples: 

Jenny's Lectures CS IT: https://www.youtube.com/@JennyslecturesCSIT
CodeWithHarry: https://www.youtube.com/@CodeWithHarry

Competitive Programming:
Luv: https://www.youtube.com/@iamluv

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @ayushkumarbhadani! :) Just to confirm, are you participating in GSSOC'23?

**Comment by ayushkumarbhadani** [comment]
> Hi @ayushkumarbhadani! :) Just to confirm, are you participating in GSSOC'23?

Yes, I'm

**Comment by CBID2** [comment]
> > Hi @ayushkumarbhadani! :) Just to confirm, are you participating in GSSOC'23?
> 
> 
> 
> Yes, I'm

Done
