### ISSUE TITLE
[OTHER] Update Contributing Guidelines

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#743]
### What would you like to share or ask?

These are some of the points that I will incorporate along with other considerations:
- There are no clear guidelines to clarify what a contributor should do when there are multiple languages associated with a resource.

- There are no clear guidelines mentioning the `database` folder as the designated location to add proper link resources.
- Additionally, using present tense in commit messages is considered a basic convention (although this is optional, as there are no strict rules), as the contributing guidelines mention `chore: added resource_name`.

> Feel free to ask me if there's anything else you would like me to add. I have made several similar changes, and you can see an example [here](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
> Hello Anmol-Baranwal, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

Good observation @Anmol-Baranwal! :) For the first bullet point, do you mean "languages" as in programming or something a person speaks? Also, I think having a guideline for this would be helpful. What do you recommend? 
For bullet point #2, mention the database.
As far as bullet three, interesting point, but we're sticking with Conventional Commit guidelines.

**Comment by Anmol-Baranwal** [comment]
> > Hello Anmol-Baranwal, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.
> 
> Good observation @Anmol-Baranwal! :) For the first bullet point, do you mean "languages" as in programming or something a person speaks? Also, I think having a guideline for this would be helpful. What do you recommend? For bullet point #2, mention the database. As far as bullet three, interesting point, but we're sticking with Conventional Commit guidelines.

1. As you can see at https://fullstackopen.com/en/about/, this resource is available in 6 languages. However, the documentation does not provide clear guidelines on which language to add, and it is not feasible to include all six languages as it may cause the text to wrap to the next line, which I'm unsure if it's intended.

3. If you are following conventional guidelines, then the preferred option would be to use `add`. Even the mentioned resource on conventional guidelines shows the same, as depicted in the picture below:

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/a862f6c3-7bd2-447e-a584-11e57170067b)

**Comment by CBID2** [comment]
Ok @Anmol-Baranwal! :) I'll assign this issue to you.
