### ISSUE TITLE
[BUG] Frontend tab is always expanded irrespective of the currently opened sub category

### ISSUE THREAD

**Issue by Isha988** [rupali-codes/LinksHub#747]
### Description

The Frontend tab is always expanded whenever the side nav is opened irrespective of the page that is currently viewed by the user, instead of this the tab whose subcategory page is opened should be expanded.
In the case, of the home page, all tabs should be closed.

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/89572340/878f9b91-d6c8-4d85-873a-18b46a5fec8b

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by bose-aritra2003** [comment]
@CBID2 @Isha988 My Pull Request #750 in regards to issue #596 already solves this issue.

**Comment by CBID2** [comment]
> @CBID2 @Isha988 My Pull Request #750 in regards to issue #596 already solves this issue because of the different implementation of the smooth transitioning sidebar accordion.

Ok
