### ISSUE TITLE
[BUG] <contact us >

### ISSUE THREAD

**Issue by leesha19** [rupali-codes/LinksHub#753]
### Description

the contact us section isn't looking cool at all, it should be updated with some interactive ui 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
@leesha19, can you elaborate on "not looking cool" and add a screenshot? It'll help us gain a better understanding of your issue. :)

**Comment by CBID2** [comment]
> @leesha19, can you elaborate on "not looking cool" and add a screenshot? It'll help us gain a better understanding of your issue. :)

Are still working on this issue @leesha19?
