### ISSUE TITLE
[Add] Youtube channel resource for Web development

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#755]
### Site URL

https://www.youtube.com/@slayingthedragon

### Description of the above provided site

Slaying the dragon is about facing your fears, pursuing meaning and transforming into the web developer you were always destined to be.

### Category

Youtube

### Sub Category

Web developement

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @0xabdulkhalid! :) Just to confirm, are you participating in GSSOC'23?

**Comment by 0xabdulkhalid** [comment]
Yup

**Comment by 0xabdulkhalid** [comment]
Excuse me @CBID2, can you assign this issue for me ?

**Comment by CBID2** [comment]
> Excuse me @CBID2, can you assign this issue for me ?

Sure @0xabdulkhalid. Before I do, are you participating in GSSoC'23?

**Comment by 0xabdulkhalid** [comment]
Yeah @CBID2, I'm participating in GSSoC'23
