### ISSUE TITLE
Would Like to add one of my Published Blog(Top 10 JavaScript Tips and Tricks)

### ISSUE THREAD

**Issue by raj3000k** [rupali-codes/LinksHub#756]
### Description

To be added to the blog page of the site. That JavaScript blog would be really useful for all the devs.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @raj3000k! :) Just to confirm, are you participating in GSSOC'23?

**Comment by CBID2** [comment]
> Yup.

Just assigned you the issue @raj3000k
