### ISSUE TITLE
[Feature] Add a new issue form to add Category/Subcategory

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#757]
### Description

I recently worked on updating the contributing guidelines, specifically separating the category and links sections.

Now, I would like to add a new issue form specifically for adding categories. Rest assured, I will maintain the same style and use appropriate labels.

You can check out my work on GitHub issue forms in this pull request: https://github.com/dailydotdev/daily/pull/864. It demonstrates my familiarity with the concept and implementation.

### Fields

The new issue form will include the following fields:

- Category name (this could be an option, but when adding a new category, we'll need two fields to record the name)
- Subcategory name
- I'll also include a checklist to verify if the category already exists and other mandatory requirements.

Let me know if there's anything else you'd like me to consider or if you have any further questions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey, I reviewed your daily.dev PR @Anmol-Baranwal small world! :) Anywho, that would be great! :)

**Comment by Anmol-Baranwal** [comment]
> Hey, I reviewed your daily.dev PR @Anmol-Baranwal small world! :) Anywho, that would be great! :)

I know, I just realized before submitting the issue, and I found it hilarious :)

Also, I wanted to ask if you would like to add Markdown to be displayed as a language in the repository. That way, I could create another issue. I don't want to create and close it without a purpose.

**Comment by CBID2** [comment]
> > Hey, I reviewed your daily.dev PR @Anmol-Baranwal small world! :) Anywho, that would be great! :)
> 
> I know, I just realized before submitting the issue, and I found it hilarious :)
> 
> Also, I wanted to ask if you would like to add Markdown to be displayed as a language in the repository. That way, I could create another issue. I don't want to create and close it without a purpose.

Sure @Anmol-Baranwal! :) I'm currently working on the template and used your daily.dev contribution as an inspiration. You can add it when I make the PR. Are you ok with this?

**Comment by Anmol-Baranwal** [comment]
> > > Hey, I reviewed your daily.dev PR @Anmol-Baranwal small world! :) Anywho, that would be great! :)
> > 
> > I know, I just realized before submitting the issue, and I found it hilarious :)
> > 
> > Also, I wanted to ask if you would like to add Markdown to be displayed as a language in the repository. That way, I could create another issue. I don't want to create and close it without a purpose.
> 
> Sure @Anmol-Baranwal! :) I'm currently working on the template and used your daily.dev contribution as an inspiration. You can add it when I make the PR. Are you ok with this?

Sure.

**Comment by CBID2** [comment]
> > > > Hey, I reviewed your daily.dev PR @Anmol-Baranwal small world! :) Anywho, that would be great! :)
> > > 
> > > 
> > > I know, I just realized before submitting the issue, and I found it hilarious :)
> > > Also, I wanted to ask if you would like to add Markdown to be displayed as a language in the repository. That way, I could create another issue. I don't want to create and close it without a purpose.
> > 
> > 
> > Sure @Anmol-Baranwal! :) I'm currently working on the template and used your daily.dev contribution as an inspiration. You can add it when I make the PR. Are you ok with this?
> 
> @CBID2 So, do I need to work on this? How will I add the changes?

Refer to step 5 in [this article](https://www.freecodecamp.org/news/code-review-tips/)
