### ISSUE TITLE
[Add] Youtube Playlist for Web development

### ISSUE THREAD

**Issue by khushbumaheshwarii** [rupali-codes/LinksHub#761]
### Site URL

https://www.youtube.com/playlist?list=PLDzeHZWIZsTo0wSBcg4-NMIbC0L8evLrD

### Description of the above provided site

This is one of the Best Free Beginner to Advance course for all those people who wants to learn Full Stack Web Development  (Available on Youtube) .

### Category

Youtube

### Sub Category

Web Development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @khushbumaheshwarii! :) Just to confirm, are you participating in GSSOC'23?

**Comment by 0xabdulkhalid** [comment]
Yup

**Comment by khushbumaheshwarii** [comment]
> Hi @khushbumaheshwarii! :) Just to confirm, are you participating in GSSOC'23?

@CBID2  yes i am participating in GSSOC'23.
