### ISSUE TITLE
[Add] A YouTube channel called "Two Minute Papers"

### ISSUE THREAD

**Issue by AkhilProto** [rupali-codes/LinksHub#762]
### Site URL

https://youtube.com/@TwoMinutePapers

### Description of the above provided site

This is an interesting channel explaining a lot of Research Papers relating to ML, Data Science, and AI. All the research papers are explained in english. They are presented in an interesting way.

### Category

Youtube

### Sub Category

ML, AI, Data Science

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @AkhilProt. I noticed that you describe the source as something interesting, but I'm curious on what _makes_ it interesting(e.g. The teaching style, references, etc)

**Comment by AkhilProto** [comment]
Two Minute Papers is a YouTube channel that summarizes recent research papers in artificial intelligence and machine learning. The videos are typically around two minutes long, and the presenter does a great job of explaining complex concepts in a clear and concise way.

I find Two Minute Papers to be a great way to stay up-to-date on the latest research in AI and ML. The videos are well-produced and informative, and they're a great way to learn about new research without having to read the full papers.

Here are some of the things that make Two Minute Papers interesting:

    **The teaching style:** The videos are very well-produced and easy to understand. The presenter, Károly Zsolnai-Fehér, does a great job of explaining complex concepts in a clear and concise way.
    **The references:** The videos always include links to the original research papers. This is great for people who want to learn more about the topic.
    **The variety of topics:** Two Minute Papers covers a wide range of topics in AI and ML. This is great for people who are interested in learning about a variety of different areas.

Overall, I think Two Minute Papers is a great resource for anyone who is interested in learning more about AI and ML. The videos are well-produced, informative, and easy to understand. I highly recommend checking them out.

Actually I have learnt a lot about AI and ML through this channel

**Comment by CBID2** [comment]
> Two Minute Papers is a YouTube channel that summarizes recent research papers in artificial intelligence and machine learning. The videos are typically around two minutes long, and the presenter does a great job of explaining complex concepts in a clear and concise way.
> 
> 
> 
> I find Two Minute Papers to be a great way to stay up-to-date on the latest research in AI and ML. The videos are well-produced and informative, and they're a great way to learn about new research without having to read the full papers.
> 
> 
> 
> Here are some of the things that make Two Minute Papers interesting:
> 
> 
> 
> **The teaching style:** The videos are very well-produced and easy to understand. The presenter, Károly Zsolnai-Fehér, does a great job of explaining complex concepts in a clear and concise way.
> 
> 
> 
> **The references:** The videos always include links to the original research papers. This is great for people who want to learn more about the topic.
> 
> 
> 
> **The variety of topics:** Two Minute Papers covers a wide range of topics in AI and ML. This is great for people who are interested in learning about a variety of different areas.
> 
> 
> 
> Overall, I think Two Minute Papers is a great resource for anyone who is interested in learning more about AI and ML. The videos are well-produced, informative, and easy to understand. I highly recommend checking them out.
> 
> 
> 
> Actually I have learnt a lot about AI and ML through this channel.
> 
> 
> 
> And hey you assigned me, so does it mean I can start the work?
> 
> 

Great @AkhilProto! :) Now, just put that in a short paragraph in your PR. By the way, are doing GSSOC'23?

**Comment by AkhilProto** [comment]
Ya, I wanted to register for it, but the link(Google Form) was closed.
