### ISSUE TITLE
[Feature] Add GitHub stars in Navbar

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#768]
### Description

Add github stars badge in the navbar to show all the github stars of linkshub

Checkout [this](https://www.minimamente.com/project/magic/) site for reference

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Good idea @rupali-code! :)

**Comment by Bhanuteja01** [comment]
Assign me 
I'm gssoc contributor

**Comment by rupali-codes** [comment]
> Assign me I'm gssoc contributor

How you going to approach it? what you going to use to get stars count of LinksHub

**Comment by Bhanuteja01** [comment]
If tell me approach how to do this
i Can try this out  and this can be one of the learning opportunity for me

**Comment by rupali-codes** [comment]
> If tell me approach how to do this i Can try this out and this can be one of the learning opportunity for me

okay, sure. Try your way and let us know if you need any kinda help :)
