### ISSUE TITLE
[Feature] Enhance Search Functionality

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#769]
### Description

The current search functionality only filters subcategories, but I would like to enhance it to enable searching for individual resources. Although categories can also be included, it is not necessary at the moment due to the limited number of categories available.

Additionally, I don't believe it will impact the suggestion functionality that is currently assigned in an issue.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/7a16b4e8-a8ff-41e5-bbf0-c89bbe004d23)

while Replit is already present:
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/14cad0e7-7c69-47e8-b0ce-ef257521e516)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- []I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor (note: assigné in not in GSSOC)

**Comment by rupali-codes** [comment]
Great, but how you are going to filter that out?  When search-text is matching more than one resources but not the subcategories?

**Comment by Anmol-Baranwal** [comment]
> Great, but how you are going to filter that out? When search-text is matching more than one resources but not the subcategories?

The current search functionality only searches subcategories. However, what I am trying to achieve is that when I type a resource title, it should display the subcategory on the left and the searched resource on the right.

@rupali-codes 
Also, please answer question in #732

**Comment by rupali-codes** [comment]
> > Great, but how you are going to filter that out? When search-text is matching more than one resources but not the subcategories?
> 
> The current search functionality only searches subcategories. However, what I am trying to achieve is that when I type a resource title, it should display the subcategory on the left and the searched resource on the right.
> 
> @rupali-codes Also, please answer question in #732

Sure

**Comment by rupali-codes** [comment]
> > Great, but how you are going to filter that out? When search-text is matching more than one resources but not the subcategories?
> 
> The current search functionality only searches subcategories. However, what I am trying to achieve is that when I type a resource title, it should display the subcategory on the left and the searched resource on the right.
> 
> @rupali-codes Also, please answer question in #732

But i'm asking about when search-text doesn't match with any subcategory but it does match with multiple resources, so how you going to approach that?

**Comment by rupali-codes** [comment]
@Anmol-Baranwal are you still willing to work on this issue? or we should assign it to someone else?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal are you still willing to work on this issue? or we should assign it to someone else?

Will tell you till 6th June end of day. If I don't make a PR till then, you are free to assign anyone else.

**Comment by programerr01** [comment]
i would like to work on it

**Comment by rupali-codes** [comment]
@programerr01 sure

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I said till 6th June, why did you unassigned me?

**Comment by CBID2** [comment]
> @rupali-codes I said till 6th June, why did you unassigned me?
> 
> It takes time to research and write code while taking everything into account.

I reassigned you @Anmol-Baranwal

**Comment by programerr01** [comment]
@rupali-codes  please check

**Comment by rupali-codes** [comment]
@programerr01 since @Anmol-Baranwal is owner of the issue and he wants to work on it, we can assign it to you. I was misunderstood him. Could you please look for some other issues :) Appreciate your willingness for contributing in LinksHub!

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I apologize for any inconvenience caused. After reviewing the codebase, I have determined that implementing this feature would require significant changes. Specifically, I would need to display the `render results` and create a database containing all subcategories mapped with individual resources from the `database`, using the name as the search query matching parameter.

Although I made a failed attempt, it would involve modifying numerous code files, and considering the potential changes involved, I don't believe it's worth pursuing. Therefore, `I kindly request that you assign this task to someone else.`

Regarding the merge, I'm attaching a code snippet that might assist anyone who picks up the task:
```typescript
export const sidebarData: ISidebar[] = [
  {
    category: 'frontend',
    subcategory: [
      ...frontend.react.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.images.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.fonts.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.colors.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.illustrations.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.animations.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.icons.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.designInspirations.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.themesTemplates.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.uiGenerators.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.onlineCodeEditors.map((item) => ({ ...item, id: uuidv4() })),
      ...frontend.accessibility.map((item) => ({ ...item, id: uuidv4() })),
    ],
  }
]
```

There are other approaches, such as creating a custom small function to flatten the object that contains subcategories into a single array. However, I don't want to cloud other judgments.

**Comment by rupali-codes** [comment]
Thanks @Anmol-Baranwal

**Comment by rupali-codes** [comment]
@programerr01 Would you still like to work on issue

**Comment by rupali-codes** [comment]
@Anmol-Baranwal are you still working on the issue?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal are you still working on the issue?

No, I have already explained that I will not be working on this.

**Comment by CBID2** [comment]
> > @Anmol-Baranwal are you still working on the issue?
> 
> 
> 
> No, I have already explained that I will not be working on this.

Anmol, mentioned this [here](https://github.com/rupali-codes/LinksHub/issues/769#issuecomment-1576384085) @rupali-codes.

**Comment by MUK-Dev** [comment]
Hello, can I work on this?

**Comment by CBID2** [comment]
> Hello, can I work on this?

Are you in GSSOC @MUK-Dev?

**Comment by MUK-Dev** [comment]
No @CBID2

**Comment by CBID2** [comment]
> No @CBID2 

That's ok :)

**Comment by MUK-Dev** [comment]
While I work on this.
Can you tell me more about GSSOC23, What is this?

**Comment by rupali-codes** [comment]
> While I work on this. Can you tell me more about GSSOC23, What is this?

You can learn about GSSoC (Girl Script Summer of Code) [here](https://gssoc.girlscript.tech/)

**Comment by MUK-Dev** [comment]
**I have finished this feature**

Things I added

New `search page` which displays search results
![image](https://github.com/rupali-codes/LinksHub/assets/83691917/c3643524-5703-4f16-8317-068d570f4116)


In the data.ts file: I added resources for each sub-category
![image](https://github.com/rupali-codes/LinksHub/assets/83691917/21ab2898-777e-4c0d-a32c-3ddf058b41f8)

In the useSidebarSearch.ts: I changed the filter condition and added routing for the `search page`
![image](https://github.com/rupali-codes/LinksHub/assets/83691917/23e48a4a-8560-42f3-b494-f0ec79062b4b)

Added a new hook useFilterSearch for searching functionality on the `search page`.
![image](https://github.com/rupali-codes/LinksHub/assets/83691917/7839fb07-03a8-4fc9-9ce2-84d19a3547be)

In the types/index.ts file: I changed the SubCategory type
`
export type SubCategories = {
  name: string
  url: string
  resources: IDBData[]
}
`

The search works for any query
![image](https://github.com/rupali-codes/LinksHub/assets/83691917/c5dc2c3f-bcc9-4c47-9e60-207fa2415ea0)
