### ISSUE TITLE
[Add] Lottie files

### ISSUE THREAD

**Issue by binadiegha** [rupali-codes/LinksHub#77]
### URL

https://lottiefiles.com/

### Description of the above provided site

LottieFiles takes away the complexity from Motion Design. It lets you Create, Edit, Test, Collaborate and Ship a Lottie in the easiest way possible.

### Category

Frontend

### Sub Category

"animations"

**Comment by binadiegha** [comment]
If this passes the check, I'll be happy to take up the task

**Comment by rupali-codes** [comment]
Thank you, would you like to make PR as well?

**Comment by AdekeyeAdeniyi** [comment]
@rupali-codes Can I update this also?

**Comment by binadiegha** [comment]
@AdekeyeAdeniyi I already worked on this, I would source more links 💪🏾😁
