### ISSUE TITLE
Chore: Add Eddie Jaoude in open source projects

### ISSUE THREAD

**Issue by parma1111** [rupali-codes/LinksHub#776]
### Site URL

https://github.com/eddiejaoude/eddiejaoude

### Description of the above provided site

Custom GitHub profile for Eddie Jaoude

### Category

Open Source

### Sub Category

Projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Why did you close the PR?

**Comment by CBID2** [comment]
> Why did you close the PR?

I think we have Eddie's stuff on the website @rupali-codes.

**Comment by parma1111** [comment]
> Why did you close the PR?

> I got conflicts in two or three files.

**Comment by rupali-codes** [comment]
> > Why did you close the PR?
> 
> I think we have Eddie's stuff on the website @rupali-codes.

Okay then we should close this issue as well right?

**Comment by CBID2** [comment]
> > > Why did you close the PR?
> > 
> > 
> > I think we have Eddie's stuff on the website @rupali-codes.
> 
> Okay then we should close this issue as well right?

Yeah we should @rupali-codes.
