### ISSUE TITLE
[Add] dotnet resources 

### ISSUE THREAD

**Issue by Mafyou** [rupali-codes/LinksHub#779]
### Description

Hi,
There are nuggets packages that I use on daily basis.
Like

> MvvM Toolkit community => https://github.com/CommunityToolkit/MVVM-Samples
Very practical when working in MvvM pattern.
> Entity Framework Core => https://github.com/dotnet/efcore
For datbase manipulations.
> Twilio => https://github.com/twilio/twilio-csharp
Text to speech library
> Benchmark => https://github.com/dotnet/BenchmarkDotNet
To benchmark whatsoever in your code.
> Humanizer => https://github.com/Humanizr/Humanizer
String manipulations.
> CsvHelper => https://github.com/JoshClose/CsvHelper
Reading Csv file's never been so easy.

Regards,
Mafyou. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Mafyou! How can LinksHub benefit from these packages?

**Comment by Mafyou** [comment]
They are open sources and help developers. Don't Links Hub made this?
Sorry if I misunderstood

**Comment by CBID2** [comment]
> They are open sources and help developers. Don't Links Hub made this?
> Sorry if I misunderstood

No you’re good @Mafyou! :) I just wanted more inquiry.

**Comment by rupali-codes** [comment]
@Mafyou are you still working on the issue?

**Comment by Mafyou** [comment]
I'm currently in holiday. Next week update!

**Comment by rupali-codes** [comment]
> I'm currently in holiday. Next week update!

ok, thanks

**Comment by Mafyou** [comment]
Here are some update.
Do you want more ?

**Comment by k-deepak04** [comment]
> 

where?
please add a pr with updates if any

**Comment by rupali-codes** [comment]
> Here are some update. Do you want more ?

Where 😂😂

**Comment by rupali-codes** [comment]
@Mafyou any updates please?

**Comment by Mafyou** [comment]
Why updates ? You are referencing librairies so do I.

**Comment by k-deepak04** [comment]
@Mafyou are you done with the issue so plz add a pr or else we will close this.

**Comment by Mafyou** [comment]
👌

**Comment by k-deepak04** [comment]
okay then closing it
