### ISSUE TITLE
[Add] <Youtube Machine Learning Channel Link>

### ISSUE THREAD

**Issue by rony0000013** [rupali-codes/LinksHub#785]
### Site URL

https://www.youtube.com/@robmulla

### Description of the above provided site

Medallion Data Science is a channel devoted to growing a community of people interested in learning machine learning, data science and coding in python. Also streaming live coding sessions on twitch as Medallion Stallion https://www.twitch.tv/medallionstallion

### Category

Youtube

### Sub Category

"Machine Learning"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @rony0000013! :) Just to confirm, are you participating in GSSOC'23?

**Comment by rony0000013** [comment]
Yes I am participating in GSSOC'23.

**Comment by CBID2** [comment]
> Yes I am participating in GSSOC'23.

You’re assigned @rony0000013.
