### ISSUE TITLE
[OTHER] Implementing 3 link cards instead of 2 in each row

### ISSUE THREAD

**Issue by raaksss** [rupali-codes/LinksHub#789]
### What would you like to share or ask?

A lot of space is left if 2 cards consisting of links to various websites are displayed. We can go in for 3 cards in a single row to utilise the space so that the user can see more resources in a single go.

![image](https://github.com/rupali-codes/LinksHub/assets/102184647/adf3f5f7-c86a-4674-ae71-c6838067bd08)

As there is an ample space this design will be much more suitable.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @raaksss! :) Just to confirm, are you participating in GSSOC'23?

**Comment by raaksss** [comment]
Yess!

**Comment by rupali-codes** [comment]
Its a screen resolution issue, i'd like to know how you are going to approach this?

**Comment by raaksss** [comment]
I can try making changes in the CSS file.

**Comment by rupali-codes** [comment]
> I can try making changes in the CSS file.

okay, you can go ahead and create the PR, assigning to you
