### ISSUE TITLE
[BUG] Logo overlapping sidebar for mobile view

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#79]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

LinksHub home root overlapping the sidebar for mobile view which is not good for user experience.

### Screenshots

![image](https://user-images.githubusercontent.com/78981177/214221787-afc21c8b-bc63-49b8-9066-638835f9b2aa.png)

**Comment by Leeyah-123** [comment]
I could take this up if it's still up for grabs

**Comment by rupali-codes** [comment]
yes, go-ahead @Leeyah-123

**Comment by Leeyah-123** [comment]
I see it's already fixed though.

**Comment by rupali-codes** [comment]
@Leeyah-123 could you link the PR, cz I'm still seeing it there

**Comment by Leeyah-123** [comment]
When I pulled main, it was already fixed so there was no change for me to commit.
Maybe try redeploying?
