### ISSUE TITLE
[Feature] <Search button added and error message generated>

### ISSUE THREAD

**Issue by Soumyajit2825** [rupali-codes/LinksHub#793]
### Description

- I have added the **search button** for searching queries in the website beside the search bar.

- User can submit the search from now by clicking on the search button or clicking enter button in desktops.

- I have also generated a ***custom error message*** for null query field

I am submitting the screen-shots below: 
Please assign me in this issue if you find this feature useful 😃 
Thank You :please

### Screenshots

![Screenshot 2023-05-28 105829](https://github.com/rupali-codes/LinksHub/assets/100519291/9401dd2b-5eee-42c9-b858-8a55d9465604)
<br>
![Screenshot 2023-05-28 104418](https://github.com/rupali-codes/LinksHub/assets/100519291/bb269ed3-37bd-4f39-ac85-ec56cf801579)
<br>
![Screenshot 2023-05-28 104402](https://github.com/rupali-codes/LinksHub/assets/100519291/e329adc3-1a3f-4db5-abc4-ea8e9739b30d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Its not required i guess, as we are displaying results _on input_, also it would take space in there. @CBID2 what do you say?

**Comment by Soumyajit2825** [comment]
> Its not required i guess, as we are displaying results _on input_, also it would take space in there. @CBID2 what do you say?

OK as you say
But it's not taking too much space
I have tested by giving various types of inputs
It's totally responsive
Thank You @rupali-codes

**Comment by Soumyajit2825** [comment]
@rupali-codes @CBID2 should I work on this or let it go!! 😞

**Comment by rupali-codes** [comment]
> @rupali-codes @CBID2 should I work on this or let it go!! 😞

I don't want to say no, but we really don't need it. Could you please look for some issue?

**Comment by CBID2** [comment]
> > @rupali-codes @CBID2 should I work on this or let it go!! 😞
> 
> 
> 
> I don't want to say no, but we really don't need it. Could you please look for some issue?

Let me check out the desktop version and then we'll decide @rupali-codes

**Comment by Soumyajit2825** [comment]
@rupali-codes no issues

**Comment by rupali-codes** [comment]
> > > @rupali-codes @CBID2 should I work on this or let it go!! 😞
> > 
> > 
> > I don't want to say no, but we really don't need it. Could you please look for some issue?
> 
> Let me check out the desktop version and then we'll decide @rupali-codes

okay, @Soumyajit2825 you can raise PR since you have already worked on it, then we will decide from there

**Comment by Soumyajit2825** [comment]
OK OK I'm doing it
Thanks 👍🏻

**Comment by CBID2** [comment]
> > > > @rupali-codes @CBID2 should I work on this or let it go!! 😞
> > > 
> > > 
> > > I don't want to say no, but we really don't need it. Could you please look for some issue?
> > 
> > 
> > Let me check out the desktop version and then we'll decide @rupali-codes
> 
> okay, @Soumyajit2825 you can raise PR since you have already worked on it, then we will decide from there

I'm on my computer. I see what @Soumyajit2825 is talking about @rupali-codes: 

https://github.com/rupali-codes/LinksHub/assets/105683440/1e0c8a1b-eaaa-45bf-98e8-92417337273d

I think having this feature is helpful.
