### ISSUE TITLE
[OTHER] Add resolve merge conflicts guide CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#798]
### What would you like to share or ask?

I've noticed that people really suffering with resolving merge conflicts, it would be much helpful we can a blog or article that describes the way of resolving conflicts. 

I would rather prefer to add [this article by github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github). Its much easier to read and follow!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
I'll work on it @rupali-codes!
