### ISSUE TITLE
[Feature] Added more scripts to package.json file

### ISSUE THREAD

**Issue by AdekeyeAdeniyi** [rupali-codes/LinksHub#81]
### Description

Let's say a new dependency was added by a contributor to the project and another contributor pulled that change. In order for the pulled changes to run locally, one has to run ```npm install ``` before running ```npm run start```.  I will add some scripts that will ease the stress of running multiple commands. eg
Instead of this ```npm install ``` and ```npm run start```,
It will change to this ```npm install && npm run start``` chained to a single script name.

**Comment by AdekeyeAdeniyi** [comment]
Can I open a PR for this?

**Comment by rupali-codes** [comment]
yeah, go-ahead @AdekeyeAdeniyi and let's see
