### ISSUE TITLE
[Add] <Artificial Intelligence Projects>

### ISSUE THREAD

**Issue by SargamPuram** [rupali-codes/LinksHub#812]
### Site URL

https://www.interviewbit.com/blog/artificial-intelligence-projects/?amp=1

### Description of the above provided site

This website provides free twenty beginner-to-advanced Artificial Intelligence projects with source code .

### Category

Resources

### Sub Category

Project Ideas

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ujjawaltyagii** [comment]
I can add this one ! Could you assign this to me

**Comment by SargamPuram** [comment]
Thanks for acknowledging my issue . Looking forward to getting it assigned to me as a part of GSSOC'23.

**Comment by rupali-codes** [comment]
Great, thanks

**Comment by SargamPuram** [comment]
@CBID2 could you please assign me this issue?

**Comment by SargamPuram** [comment]
@CBID2 Thank you for assigning me this issue , I will work on it .

**Comment by SargamPuram** [comment]
@CBID2  can you please review this?

**Comment by CBID2** [comment]
> @CBID2  can you please review this?
> 
> 

Please be patient

**Comment by SargamPuram** [comment]
@CBID2 I'm Sorry , My Apologies .
