### ISSUE TITLE
[Add] add link of android development playlist created  by Saumya Singh

### ISSUE THREAD

**Issue by singhishika02** [rupali-codes/LinksHub#813]
### Site URL

https://youtube.com/playlist?list=PLTV_nsuD2lf4UCTV6xwvNPvFdmCNKyhc8&feature=share8

### Description of the above provided site

It is the 30 days bootcamp playlist by Saumya Singh on android development in which she covers each and every topic of android development. It is beginner friendly tutorial which contains topics like installation, studio tool , interactive UI, layouts , web view ,data base, notifications and much more.

### Category

Youtube

### Sub Category

Android

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @singhishika02! :) Just to confirm, are you participating in GSSOC'23?

**Comment by singhishika02** [comment]
> 

Yes

**Comment by singhishika02** [comment]
> Hi @singhishika02! :) Just to confirm, are you participating in GSSOC'23?

Yes

**Comment by rupali-codes** [comment]
> Hi @singhishika02! :) Just to confirm, are you participating in GSSOC'23?

Are they not checking on the checkmark? 👀

**Comment by rupali-codes** [comment]
@singhishika02 please update the description and just keep it to point

**Comment by CBID2** [comment]
> > Hi @singhishika02! :) Just to confirm, are you participating in GSSOC'23?
> 
> Are they not checking on the checkmark? 👀

@rupali-codes, I DMed you my reasoning for this approach on Discord.
