### ISSUE TITLE
[BUG] Contributors Graph

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#814]
### Description

I believe there may be an issue with the graph of the contributors in the README.md file, as it is not functioning as intended.

### Screenshots

![Screenshot (79)](https://github.com/rupali-codes/LinksHub/assets/112751524/14aac399-adbc-4195-bc4e-94c5cb8dd503)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Shiva-Sai-ssb thanks for noticing :)
