### ISSUE TITLE
[Add] <Add visuals (pictures and logos) of the websites and resources in the project to increase user experience>

### ISSUE THREAD

**Issue by Ritapossible** [rupali-codes/LinksHub#815]
Adding visuals will help demonstrate and increase visitors engagements.

**Comment by CBID2** [comment]
Hi @Ritapossible. Can you revise your issue form? It’s missing important information. See [the Issues in the Contributing field to learn how] (https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#issues)

**Comment by Ritapossible** [comment]
I recreated new one.

**Comment by Ritapossible** [comment]
New here. Thanks for the direction.
