### ISSUE TITLE
[Feature] < Add visuals (pictures and logos) of the websites and resources in the project.> 

### ISSUE THREAD

**Issue by Ritapossible** [rupali-codes/LinksHub#816]
### Description

Adding visuals to the linkhub site will help increase visitors engagements and user experience.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
That’s better @Ritapossible! What kind of visuals do you want to add to LinksHub?

**Comment by Ritapossible** [comment]
Add pictures of the websites landing-page shared in LinkHub website. 
Add cover-books for pdf resources shared.
These visuals can go a long way in helping visitors click on the links provided.

**Comment by rupali-codes** [comment]
Thanks, but currently we don't have any database established yet, and it would take so much space if directly store that in the repo. @CBID2 what do you think about this?

**Comment by CBID2** [comment]
> Thanks, but currently we don't have any database established yet, and it would take so much space if directly store that in the repo. @CBID2 what do you think about this?

Ooh, good point @rupali-codes. There are a lot of files already. I wonder if there is another way to do this. Like just adding links to the images instead of SVGs?

**Comment by rupali-codes** [comment]
> > Thanks, but currently we don't have any database established yet, and it would take so much space if directly store that in the repo. @CBID2 what do you think about this?
> 
> Ooh, good point @rupali-codes. There are a lot of files already. I wonder if there is another way to do this. Like just adding links to the images instead of SVGs?

We will have to use third party storage services like ipfs

**Comment by CBID2** [comment]
> > > Thanks, but currently we don't have any database established yet, and it would take so much space if directly store that in the repo. @CBID2 what do you think about this?
> 
> > 
> 
> > Ooh, good point @rupali-codes. There are a lot of files already. I wonder if there is another way to do this. Like just adding links to the images instead of SVGs?
> 
> 
> 
> We will have to use third party storage services like ipfs

Ok. I just checked out IPFS. Is[this the site](https://ipfs.tech/) @rupali-codes?

**Comment by rupali-codes** [comment]
> > > > Thanks, but currently we don't have any database established yet, and it would take so much space if directly store that in the repo. @CBID2 what do you think about this?
> > 
> > 
> > > 
> > 
> > 
> > > Ooh, good point @rupali-codes. There are a lot of files already. I wonder if there is another way to do this. Like just adding links to the images instead of SVGs?
> > 
> > 
> > We will have to use third party storage services like ipfs
> 
> Ok. I just checked out IPFS. Is[this the site](https://ipfs.tech/) @rupali-codes?

yep, let's see what @ujjawaltyagii have to say about this 👀

**Comment by ujjawaltyagii** [comment]
I think it's a great idea to add visuals of the resources but it will increase the repo size and may not be feasible and as @CBID2  said we can add links instead of svgs but My concern is <b>whether contributors will be able to find suitable images every time that align well with the website's theme to use as visuals for their resources !</b>

 Considering these factors, it might be more practical to keep the existing structure or can we do something else ?

**Comment by CBID2** [comment]
Ooh good point @ujjawaltyagii. Finding images would be difficult. With that in mind, I think we should keep the existing structure
