### ISSUE TITLE
[Add] open-source project

### ISSUE THREAD

**Issue by ujjawaltyagii** [rupali-codes/LinksHub#817]
### Site URL

https://github.com/hkirat/linkedin-bot

### Category

Open Source

### Sub Category

Projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ujjawaltyagii** [comment]
please add labels and assignee !

**Comment by ujjawaltyagii** [comment]
@CBID2 could you please review this !

**Comment by CBID2** [comment]
> @CBID2 @pratyushmp  could you please review this !

Done @ujjawaltyagii
