### ISSUE TITLE
[ADD] Design Patterns

### ISSUE THREAD

**Issue by RashakDude** [rupali-codes/LinksHub#819]
### Category Name

Backend

### Subcategory Name

Design Patters

### Additional Context

Design pattern has its origin in the fact that developers have noticed recurring and similar design problems. Therefore, it became necessary to conceptualize design problems in such a way that the same answers were reused each time the problem arose.

To conceptualize, it is often essential to use code directly. But in the case of the design pattern, developers translate the conceptualization into an abstract idea of how to solve the problem. Each developer then implements the problem resolution using the language they are familiar with. There are examples of design pattern applications for different languages.

The design pattern is therefore conceived as a general design process that builds on the experience already acquired in software design. The design pattern has an important role to play in the computer system and its architecture.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by RashakDude** [comment]
@rupali-codes @CBID2

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 

Hi @Jittojoyes98! :) Just to confirm, you're a GSSoC'23 contributor?

**Comment by RashakDude** [comment]
Hi @CBID2, 
I am a GSSOC'23 contributor.
Thanks
