### ISSUE TITLE
[OTHER] Design Style Guide

### ISSUE THREAD

**Issue by AbyPurpleheart** [rupali-codes/LinksHub#825]
### What would you like to share or ask?

Created a style guide for the new LinksHub landing page design

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @AbyPurpleheart! :) Just to confirm, are you participating in GSSOC'23?

**Comment by AbyPurpleheart** [comment]
Yes I will like to participate

**Comment by AbyPurpleheart** [comment]
Hi @CBID2 yes I would like to participate, but I'm not sure if it's still open for participants. However, I ticked that option because I thought it was a requirement. Do I need to create another issue? I'm still trying to get used to using GitHub :)

**Comment by CBID2** [comment]
> Hi @CBID2 yes I would like to participate, but I'm not sure if it's still open for participants. However, I ticked that option because I thought it was a requirement. Do I need to create another issue? I'm still trying to get used to using GitHub :)
They're no longer accepting applications. The check mark is only for GSSOC members. As far as your final question, you don't have to create a different issue @AbyPurpleheart. Just uncheck the GSSOC checkbox.

**Comment by AbyPurpleheart** [comment]
Hi @CBID2 thank you! I have unchecked the GSSOC checkbox now.

**Comment by CBID2** [comment]
> Hi @CBID2 thank you! I have unchecked the GSSOC checkbox now.

Just assigned you and reopened your pull request
