### ISSUE TITLE
[Feature] <Update figma link>

### ISSUE THREAD

**Issue by Abhinavcode13** [rupali-codes/LinksHub#830]
### Description

I want to add figma design link for other devices.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Abhinavcode13** [comment]
@CBID2 please assign this to me.

**Comment by rupali-codes** [comment]
> @CBID2 please assign this to me.
Sure, could you please elaborate on the issue more?

**Comment by Abhinavcode13** [comment]
I will add figma design prototype of existing one for other devices like tablet etc

**Comment by Abhinavcode13** [comment]
Just a replica of it @rupali-codes

**Comment by rupali-codes** [comment]
> Just a replica of it @rupali-codes

Oh, great, thanks

**Comment by Abhinavcode13** [comment]
need figma link access @CBID2 @rupali-codes

**Comment by CBID2** [comment]
> need figma link access @CBID2 @rupali-codes 

We don't have an account with Figma @Abhinavcode13.

**Comment by Abhinavcode13** [comment]
What to do now? @CBID2

**Comment by Abhinavcode13** [comment]
#839 assign me this issue anyways

**Comment by CBID2** [comment]
> #839 assign me this issue anyways 

You figured it out?

**Comment by Abhinavcode13** [comment]
Me Idea was to create same replica figma frame for tablets , but I don't have any access to it.

**Comment by CBID2** [comment]
> Me Idea was to create same replica figma frame for tablets , but I don't have any access to it.

Ohh now I get. I think you'll have to wait for @rupali-codes because I don't have access to the link either
