### ISSUE TITLE
[Add] <New e-book under resource folder>

### ISSUE THREAD

**Issue by Abhinavcode13** [rupali-codes/LinksHub#831]
### Site URL

file:///C:/Users/Abhinav%20Kumar/Downloads/Alex_Banks_and_Eve_Porcello-Learning_React-EN.pdf

### Description of the above provided site

A Beginner's Guide to Building User Interfaces with React" is a comprehensive book designed to introduce beginners to the fundamentals of React and guide them through the process of building interactive user interfaces. Whether you have basic knowledge of JavaScript or are completely new to web development, this book provides a solid foundation for understanding and using React effectively.

### Category

Resources

### Sub Category

e-Book

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Abhinavcode13** [comment]
please assign this to me @CBID2 @rupali-codes

**Comment by rupali-codes** [comment]
@Abhinavcode13 You can not upload pdf files directly from your system, it should stored somewhere like in GDrive or in some wesbsites

**Comment by Abhinavcode13** [comment]
Ok will do that , assign it to me anyways

**Comment by Abhinavcode13** [comment]
@rupali-codes
