### ISSUE TITLE
[Feature] <Make navbar responsive>

### ISSUE THREAD

**Issue by kedar1998** [rupali-codes/LinksHub#832]
### Description

Navbar is not responsive in open-source section for blogs and projects. Can you please assign it to me under GSSOC'23

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/103363619/7f78b224-2b55-4253-b5ad-9ccbf7c50627)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by kedar1998** [comment]
Above issue is only on page open-source/projects

**Comment by rupali-codes** [comment]
@kedar1998 Thanks for noticing, what the screen resolution you are having?

**Comment by kedar1998** [comment]
screen size is 425px(width) 

![image](https://github.com/rupali-codes/LinksHub/assets/103363619/62c60e2c-0346-4c41-b08b-7968b7495f66)

**Comment by rupali-codes** [comment]
Thanks, please update the description of this issue to something meaningful

**Comment by rupali-codes** [comment]
> screen size is 425px(width)
> 
> ![image](https://user-images.githubusercontent.com/103363619/241857286-62c60e2c-0346-4c41-b08b-7968b7495f66.png)

looks perfectly fine on my system and even in my other devices

**Comment by kedar1998** [comment]
You can look at navabar

**Comment by rupali-codes** [comment]
> You can look at navbar. Can you please share screenshot. Please try going to open-source/blogs or open-source/projects

I see, it's actually looks fine in my system, but when i opened in private window it appeared. You can start working on this issue :)

**Comment by kedar1998** [comment]
I have made necessary changes and  created PR.

**Comment by kedar1998** [comment]
Raised PR

**Comment by afreen-ahmed12** [comment]
@rupali-codes hello....could u please assign me this problem??

**Comment by rupali-codes** [comment]
> @rupali-codes hello....could u please assign me this problem??

Hey, this issue has already been assigned to @kedar1998. We appreciate your willingness for contributing in LinksHub, could you please look for some other issues?

**Comment by afreen-ahmed12** [comment]
okay

**Comment by kedar1998** [comment]
@rupali-codes I took fresh pull in morning and someone already fixed issue. You can close this issue.
