### ISSUE TITLE
[Feature] create automated releases

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#833]
### Description

Adding automated releases would be helpful whenever a PR gets merged, because it's hard create a release manually after merging PRs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by milan-lakhani** [comment]
Hey @rupali-codes I think it is pretty straightforward as per Vercel [docs](https://vercel.com/docs/concepts/projects/project-configuration/git-configuration). I have never worked with Vercel for deployments but have experience writing custom yaml files for deploying to GCP and other platforms. I don't know how to proceed. Do you have any ideas?

**Comment by ujjawaltyagii** [comment]
@rupali-codes Ig I can work on this issue so <b>you can assign</b> this to me but I may need some help while working on it. 
So this is the workflow I have planned let me know if it has any issue or error :

1. Create a GitHub Action
2. Define the workflow (inside lets say release.yml)
3. Adding github token with appropriate permissions
4. Generate a Vercel Token
5. Add Secrets to GitHub Repository (generated-vercel-token, vercel-organization-id, vercel-project-id)

Ig this should work ! what do you think about it ?

**Comment by CBID2** [comment]
> @rupali-codes Ig I can work on this issue so you can assign this to me but I may need some help while working on it. So this is the workflow I have planned let me know if it has any issue or error :
> 
> 1. Create a GitHub Action
> 2. Define the workflow (inside lets say release.yml)
> 3. Adding github token with appropriate permissions
> 4. Generate a Vercel Token
> 5. Add Secrets to GitHub Repository (generated-vercel-token, vercel-organization-id, vercel-project-id)
> 
> Ig this should work ! what do you think about it ?
That could work @ujjawaltyagii. For some reason, the Old PR GitHub action does not seem to go in effect either.

**Comment by milan-lakhani** [comment]
I'll look into it as well. I just need the weekend. I am a bit stacked right now.

**Comment by CBID2** [comment]
> I'll look into it as well. I just need the weekend. I am a bit stacked right now.

That's ok. Take your time! :)

**Comment by ujjawaltyagii** [comment]
Ig then we should first discuss it thoroughly before finalizing what to do as `release` is a crucial part ! would highly appreciate any help @milan-lakhani 

(As of now I am un-assigning myself till we finalize the workflow)

**Comment by rupali-codes** [comment]
> Ig then we should first discuss it thoroughly before finalizing what to do as `release` is a crucial part ! would highly appreciate any help @milan-lakhani
> 
> (As of now I am un-assigning myself till we finalize the workflow)

Sure, we can also discuss it on discord if it gets hard for you :)

**Comment by milan-lakhani** [comment]
@rupali-codes @ujjawaltyagii . So from what I can tell,  we are already doing auto deploys. Its just this PR is for automated Releases. What I don't understand is that we are not an npm package why would we need a automated release? because every other project I try to watch using Next.js to see how they create automated releases has some kind of NPM releases.

**Comment by rupali-codes** [comment]
any updated guys?

**Comment by CBID2** [comment]
Maybe we can make it a changelog @rupali-codes?

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes is this still yet to be implemented?
i can look into this if you want.
Let me know

**Comment by rupali-codes** [comment]
> @CBID2 @rupali-codes is this still yet to be implemented? i can look into this if you want. Let me know

Yes you can!

**Comment by k-deepak04** [comment]
> > @CBID2 @rupali-codes is this still yet to be implemented? i can look into this if you want. Let me know
> 
> Yes you can!

please assign this to me. i'm quite tangled in many things but will try to complete this soon.

**Comment by CBID2** [comment]
> > > @CBID2 @rupali-codes is this still yet to be implemented? i can look into this if you want. Let me know
> 
> > 
> 
> > Yes you can!
> 
> 
> 
> please assign this to me. i'm quite tangled in many things but will try to complete this soon.

You're Dobe

**Comment by k-deepak04** [comment]
@rupali-codes @CBID2 can i get more info on this like what to do, cuz i will be doing this kind of stuff for the first time.

**Comment by rupali-codes** [comment]
> @rupali-codes @CBID2 can i get more info on this like what to do, cuz i will be doing this kind of stuff for the first time.

you may take inspiration from [LinkFree](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/workflows/release.yml)

**Comment by k-deepak04** [comment]
> > @rupali-codes @CBID2 can i get more info on this like what to do, cuz i will be doing this kind of stuff for the first time.
> 
> you may take inspiration from [LinkFree](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/workflows/release.yml)

okay

**Comment by rupali-codes** [comment]
> > > @rupali-codes @CBID2 can i get more info on this like what to do, cuz i will be doing this kind of stuff for the first time.
> > 
> > 
> > you may take inspiration from [LinkFree](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/workflows/release.yml)
> 
> okay

are you still working on this?

**Comment by rupali-codes** [comment]
@k-deepak04 sure, thanks

**Comment by AbhishekPSingh07** [comment]
I am a GSSOC contributor can i try working on this issue

**Comment by k-deepak04** [comment]
@AbhishekPSingh07 go for it

**Comment by CBID2** [comment]
Any updates @AbhishekPSingh07?

**Comment by rupali-codes** [comment]
@CBID2 i guess we should close it for now

**Comment by CBID2** [comment]
> @CBID2 i guess we should close it for now

Yeah I agree @rupali-codes
