### ISSUE TITLE
[Add] geekrepos in open source tools

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#834]
### Site URL

https://geeksrepos.com/

### Description of the above provided site

This site will help you to get different open source project to contribute in. You will get open-source project repos from beginner to advanced level.

### Category

Open Source

### Sub Category

open-source-tools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Bhanuteja01** [comment]
@CBID2 can you assign this
