### ISSUE TITLE
[Add] Firebase 

### ISSUE THREAD

**Issue by Vidip-Ghosh** [rupali-codes/LinksHub#836]
### Site URL

https://firebase.google.com/

### Description of the above provided site

It is a set of backend cloud computing services and application development platform provided by Google. It hosts databases, services, authentication, and integration for a variety of applications, including Android, iOS, JavaScript, Node.js, Java, Unity, PHP, and C++.

### Category

Other

### Sub Category

database services

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Vidip-Ghosh thanks, but you don't have to create a new category, we already have _database_ subcategory under _backend_ category, so you can add this resource in there
