### ISSUE TITLE
[Add] Hello World DSA

### ISSUE THREAD

**Issue by Vidip-Ghosh** [rupali-codes/LinksHub#837]
### Site URL

https://www.youtube.com/@HelloWorldbyprince/playlists

### Description of the above provided site

Hello World youtube channels provides C++ specific DSA Course focused on explanation of Algorithms.  

### Category

Youtube

### Sub Category

DSA

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @Vidip-Ghosh! :) Just to confirm, are you in GSSoC'23?

**Comment by Vidip-Ghosh** [comment]
> Hey @Vidip-Ghosh! :) Just to confirm, are you in GSSoC'23?

Yes I am.
