### ISSUE TITLE
[Feature] Shift the social media icons to bottom of page

### ISSUE THREAD

**Issue by aastha170902** [rupali-codes/LinksHub#853]
### Description

Social media buttons should be at the end of the page that is the footer,  I want to remove the icons from their original place and shift them down.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hey thanks Astha, @CBID2 & @ujjawaltyagii what do you think about this?

**Comment by navharsh** [comment]
I think the current placement of social media icons looks better instead of putting them at bottom.

**Comment by CBID2** [comment]
I agree with @navharsh @rupali-codes. Adding the icons on the bottom would make it harder for people to know where to find LinksHub.

**Comment by rupali-codes** [comment]
Agree with @CBID2 & @navharsh. 
So, @aastha170902 we appreciate your time and willingness for contributing in LinksHub. Could you please look for any other issue?

**Comment by ujjawaltyagii** [comment]
@rupali-codes  Sorry for the late response but I do agree that current position of icons is perfect and having icons in their footer section is <b>very generic</b>. I think the current position matches perfect with the linkshub website design !!

@aastha170902 Thanks for the suggestion though
