### ISSUE TITLE
Semantic suggestion

### ISSUE THREAD

**Issue by raiamit31** [rupali-codes/LinksHub#855]
### What would you like to share or ask?

Current Semantic :
```html
<div>
        <aside></aside>
        <main></main>
</div>
``` 
Supposedly correct semantic :
```html
<nav>
        <!-- here the content wrapped in <aside> should be added -->
        <!-- Reason this part of the page is common to every page -->
</nav>
<main></main>
``` 

[----MDN Reference](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure#html_layout_elements_in_more_detail)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
If this issue is approved, I would like to contribute this small semantic adjustment.
