### ISSUE TITLE
[OTHER] update twitter link

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#856]
### What would you like to share or ask?

We have updated our twitter handle from *@the_linkshub* to *linkshubdotdev* . Kindly the repalce the link with this one https://twitter.com/linkshubdotdev

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hello @rupali-codes, I'm willing to work on this issue. So kindly assign me for further development!
