### ISSUE TITLE
[Add] AIColors under Colors

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#862]
### Site URL

https://aicolors.co/

### Description of the above provided site

- This website is one of the most awesome websites for generating validated color palettes.
- Users can generate a color palette based on a text prompt.
- Each color palette is visually displayed on a user interface design, which is what makes it game-changing.
- Additionally, users can save these palettes and explore the trending ones.

### Category

Frontend

### Sub Category

Colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal are you in LinksHub discord server?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal are you in LinksHub discord server?

@rupali-codes 
I joined the channel, but I am also a mentor for another project. As per the core team's advice, I was told to leave as people might mistake me for the mentor of LinksHub. However, I will be joining the Discord server of LinksHub. What would you like to discuss?

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Thank you for asking me to join the LinksHub Discord server. I promptly joined and provided the necessary information, but unfortunately, there has been no further communication or response from you. I understand that issues can arise, but it is considered basic etiquette in open source communities to reply to inquiries or requests.

**Comment by rupali-codes** [comment]
> @rupali-codes Thank you for asking me to join the LinksHub Discord server. I promptly joined and provided the necessary information, but unfortunately, there has been no further communication or response from you. I understand that issues can arise, but it is considered basic etiquette in open source communities to reply to inquiries or requests.

I have asked you join our custom discord server so we can discuss further 
Here's the [invite](https://discord.com/invite/NvK67YnJX5)

**Comment by Anmol-Baranwal** [comment]
> > @rupali-codes Thank you for asking me to join the LinksHub Discord server. I promptly joined and provided the necessary information, but unfortunately, there has been no further communication or response from you. I understand that issues can arise, but it is considered basic etiquette in open source communities to reply to inquiries or requests.
> 
> I have asked you join our custom discord server so we can discuss further Here's the [invite](https://discord.com/invite/NvK67YnJX5)

Thanks for letting me know.
