### ISSUE TITLE
[Feature] Add a changelog

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#866]
### Description

This could be a great way to keep track of the changes LinksHub has. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hey @ujjawaltyagii! :) I'm looking to assign this issue to someone. I know you're free, so do you want to work on it?

**Comment by Lucif3r-in** [comment]
Hey @CBID2 can you please elaborate?

**Comment by CBID2** [comment]
> Hey @CBID2 can you please elaborate? Any suggestions or references how do you want it to be?

Hi @Lucif3r-in! :) I noticed LinksHub doesn't provide users with updates & I think a changelog would help with that.

**Comment by CBID2** [comment]
> > > Hey @CBID2 can you please elaborate? Any suggestions or references how do you want it to be?
> 
> > 
> 
> > Hi @Lucif3r-in! :) I noticed LinksHub doesn't provide users with updates & I think a changelog would help with that.
> 
> 
> 
> You suggest a markdown file with changes done. Correct me if I am wrong.

Yup. Here's more info about [change logs](https://amoeboids.com/blog/changelog-how-to-write-good-one/).

**Comment by ujjawaltyagii** [comment]
@CBID2 I would need some time to figure it out :)
Also I have college exams starting from tomorrow T_T

**Comment by Lucif3r-in** [comment]
@CBID2 Do you have any package in mind that will automate this process which you have used earlier?

**Comment by CBID2** [comment]
> @CBID2 Do you have any package in mind that will automate this process which you have used earlier?

Package? No, not really.

**Comment by CBID2** [comment]
> > > @CBID2 Do you have any package in mind that will automate this process which you have used earlier?
> 
> > 
> 
> > Package? No, not really.
> 
> 
> 
> Should we do it manually? I am looking for some package, if I don't find anything I will raise a PR with a Changelog.md that need to be updated manually🚀.

Automation could work. I just wonder what package would suffice

**Comment by CBID2** [comment]
@rupali-codes, you got any suggestions?

**Comment by CBID2** [comment]
> @CBID2 I would need some time to figure it out :)
> 
> Also I have college exams starting from tomorrow T_T

Take your time @ujjawaltyagii! :) Good luck on those exams! :)

**Comment by Anmol-Baranwal** [comment]
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/10ac4ee1-f4f3-462a-b642-40f6e720856c)

Release alone can be sufficient. However, we can implement a changelog for better documentation. 
Since I am new to this, I am eager to work on it and learn more about the process.

> @CBID2 Is anyone working on this issue?

**Comment by CBID2** [comment]
> ![image](https://github.com/rupali-codes/LinksHub/assets/74038190/10ac4ee1-f4f3-462a-b642-40f6e720856c)
> 
> 
> 
> Release alone can be sufficient. However, we can implement a changelog for better documentation. 
> 
> Since I am new to this, I am eager to work on it and learn more about the process.
> 
> 
> 
> > @CBID2 Is anyone working on this issue?

Sure go right ahead @Angelo

**Comment by Anmol-Baranwal** [comment]
I will let you know about the process and the approach after raising a PR.

**Comment by Anmol-Baranwal** [comment]
Not needed, as semantic drafting of release using gh is done by `tamalCodes`.
