### ISSUE TITLE
[Add] <New react blog>

### ISSUE THREAD

**Issue by Abhinavcode13** [rupali-codes/LinksHub#868]
### Site URL

https://reacttraining.com/blog/using-hooks-in-classes

### Description of the above provided site

Will be adding a react blog which will be helpful for react developers

### Category

Resources

### Sub Category

Blogs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Abhinavcode13** [comment]
Please assign this issue to me @CBID2 & @rupali-codes .

**Comment by rupali-codes** [comment]
> Please assign this issue to me @CBID2 & @rupali-codes .

Sure, thanks
