### ISSUE TITLE
📝 [OTHER]: UPDATE GREETINGS.YML TYPO

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#871]
### Description:

- I would like to update the typo of `greetings.yml`, because it lacks details we could make it more detailed.
- This update will warmly welcome the future contributors with nice structured typo, hope you assign me to this issue!

### Screenshot:
| | |
| :---: | :---: |
| **CURRENT** | ![](https://github.com/rupali-codes/LinksHub/assets/92252895/857efa4e-b10c-4733-8e07-a56998c4a5fa)| 
| **CHANGES I'M GONNA PROPOSE** | ![](https://github.com/rupali-codes/LinksHub/assets/92252895/26849e50-5a8b-4ce3-a3b3-e06519618c12) | 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
looks good though, just remove the _Don't forget to star our repo_ thing :)
