### ISSUE TITLE
[OTHER] product design

### ISSUE THREAD

**Issue by FlakesUX** [rupali-codes/LinksHub#873]
### What would you like to share or ask?

Interactive prototype video for the web view

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi @FlakesUX, are still working on it?

**Comment by FlakesUX** [comment]
Yes

**Comment by rupali-codes** [comment]
> Yes

Thanks, Any updates?

**Comment by FlakesUX** [comment]
I will work on it in my free time, prolly before the end of nextweek.

**Comment by rupali-codes** [comment]
> I will work on it in my free time, prolly before the end of nextweek.

okay, thanks

**Comment by k-deepak04** [comment]
closing as inactive from a long time
