### ISSUE TITLE
Add CodeQL workflow

### ISSUE THREAD

**Issue by metabiswadeep** [rupali-codes/LinksHub#882]
### Description

Add the codeql semantic analysis workflow for the repo to be enabled on every push, commit and pull request using GitHub actions.

I want to work on this issue as a part of GSSoc'23. Please assign this issue to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by ujjawaltyagii** [comment]
@metabiswadeep could you specify more details ?

**Comment by CBID2** [comment]
@metabiswadeep, are you also in GSSOC'23? Just asking for further confirmation. :)

**Comment by metabiswadeep** [comment]
> @metabiswadeep, are you also in GSSOC'23? Just asking for further confirmation. :)  

Yes I am

**Comment by metabiswadeep** [comment]
> @metabiswadeep could you specify more details ? (like how you are going to implement)

In the .github/workflows folder, I will add a new file by the name codeql.yml. In that file, I will write the code for the implementation of the workflow.

**Comment by rupali-codes** [comment]
@metabiswadeep are you still working on it?

**Comment by metabiswadeep** [comment]
@rupali-codes Once you assign me the issue I can start working on it.
