### ISSUE TITLE
[Add] <SuperDesigner.Co>

### ISSUE THREAD

**Issue by PriyansuMaurya** [rupali-codes/LinksHub#883]
### Site URL

https://superdesigner.co/

### Description of the above provided site

This site has all types of Generators such as 

1. Svg backgrounds
2. 3d shapes generator
3. Background generator
4. Pattern generator
5. Blob generator
6. Gradient generator

Best thing is that its all free and you don't need to login

### Category

Frontend

### Sub Category

UI generator

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
You're assigned @PriyansuMaurya! :)
