### ISSUE TITLE
[Add] daily.dev

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#896]
### Site URL

https://app.daily.dev/

### Description of the above provided site

daily.dev is a website that provides a curated feed of developer news and articles to help you stay updated with the latest trends and developments in the tech industry.

### Category

Resources

### Sub Category

Blogs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [x] I am a GSSoC'23 contributor

**Comment by Bhanuteja01** [comment]
/assign me
I'm  gssoc contributor

**Comment by rupali-codes** [comment]
> /assign me I'm gssoc contributor

@Shiva-Sai-ssb is willing to work on the issue, so we can assign this issue to you, could you please look for some other issue :)

**Comment by Bhanuteja01** [comment]
Ok
