### ISSUE TITLE
[Feature] Custom scrollbar for whole website

### ISSUE THREAD

**Issue by dev-AshishRanjan** [rupali-codes/LinksHub#905]
### Description

The website has native scrollbar.
The scrollbar can be customized to match the website theme and to improve UI.

We can two type of custom scrollbar generally :
- like https://www.krashish.live/about : where scrollbar disappear and is visible during scrolling only.
- like https://xomoy144.netlify.app/ : where scrollbar is always visible but is customized according to website theme only.

---

I can see you have implemented the **custom scrollbar** on your website, _but only for the left panel_
I am taking about the **whole website**, just _like https://www.krashish.live_

**_If in place of browser's default scrollbar, we use the custom scrollbar used in left panel, for the whole website, then the overall UI of website will be enhanced_** 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by dev-AshishRanjan** [comment]
Hi @CBID2 ,
If you will consider this UI improvement, then you can assign me, to work on.
And If the website's scrollbar was left willingly, then let me know.

**Comment by CBID2** [comment]
> Hi @CBID2 , If you will consider this UI improvement, then you can assign me, to work on. And If the website's scrollbar was left willingly, then let me know.

Hi @dev-AshishRanjan. I'll consider it once you finish #907 (after you confirm your participation in GSSOC'23.)

**Comment by dev-AshishRanjan** [comment]
Ok
So, First I have to work on #907 ?

**Comment by CBID2** [comment]
> Ok
> So, First I have to work on #907 ?

Yes @dev-AshishRanjan

**Comment by rupali-codes** [comment]
@ujjawaltyagii what do you think about adding this feat?

**Comment by rupali-codes** [comment]
> @rupali-codes I agree with @dev-AshishRanjan , we should have a smooth less wide scrollbar instead of default one (probably a scrollbar that matches with website dark/light theme)
> 
> Count me in for this idea !!

thanks

**Comment by ujjawaltyagii** [comment]
@rupali-codes If this issue is <b>up-for-grab</b> in gssoc then could you assign me this issue 0_0
