### ISSUE TITLE
[Add] stackedit.io under online editors

### ISSUE THREAD

**Issue by dev-AshishRanjan** [rupali-codes/LinksHub#906]
### Site URL

https://stackedit.io/

### Description of the above provided site

**_stackedit.io_** is the best online `md` and `mdx` editor available out in market/web.
**Even Visual Studio Code (VS Code) does not have built-in support for MDX (Markdown with JSX) files.**

So it helps in online coding and preview of md and mdx on the go.
It's essential as it supports mdx which is not supported by any markdown editor in market

### Category

Frontend

### Sub Category

Online Code Editors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @dev-AshishRanjan! :) Please work on one issue at time.

**Comment by dev-AshishRanjan** [comment]
Hi,
Can you assign me 
I will work on this issue

**Comment by rupali-codes** [comment]
> Hi @dev-AshishRanjan! :) Please work on one issue at time.



> Hi @rupali-codes @ujjawaltyagii,
> 
> I will work on this issue Can you assign me

Please complete the assigned task, then we can assign this issue to you when you're done and the issue still remains open

**Comment by dev-AshishRanjan** [comment]
> > Hi @dev-AshishRanjan! :) Please work on one issue at time.
> 
> > Hi @rupali-codes @ujjawaltyagii,
> > I will work on this issue Can you assign me
> 
> Please complete the assigned task, then we can assign this issue to you when you're done and the issue still remains open

***Actually my 2 issues are open #905 and #906(this issue)***
***But I haven't been assigned any of them.***

And @rupali-codes , I have done the addition in database for this issue.
so, If you can assign me this issue then I can raise the PR for this issue.

Currently I haven't been assigned any issue.

**Comment by CBID2** [comment]
> > > Hi @dev-AshishRanjan! :) Please work on one issue at time.
> > 
> > 
> > > Hi @rupali-codes @ujjawaltyagii,
> > > I will work on this issue Can you assign me
> > 
> > 
> > Please complete the assigned task, then we can assign this issue to you when you're done and the issue still remains open
> 
> _**Actually my 2 issues are open #905 and #906(this issue)**_ _**But I haven't been assigned any of them.**_
> 
> And @rupali-codes , I have done the addition in database for this issue on my local machine. so, If you can assign me this issue then I can raise the PR for this issue.
> 
> **Currently I haven't been assigned any issue/task to work on.** Ref - https://github.com/rupali-codes/LinksHub/issues/assigned/dev-AshishRanjan

I just assigned you to #905, so focus on that one before working on #906 @dev-AshishRanjan

**Comment by dev-AshishRanjan** [comment]
Hi @CBID2 ,
As nobody is taking this issue and I have currently no issue/task assigned,
Can you assign this issue to me so I can work on it

**Comment by rupali-codes** [comment]
> Hi @CBID2 , As nobody is taking this issue and I have currently no issue/task assigned, Can you assign this issue to me so I can work on it

sure
