### ISSUE TITLE
[BUG] OnlineGDB wrong link 

### ISSUE THREAD

**Issue by dev-AshishRanjan** [rupali-codes/LinksHub#907]
### Description

**OnlineGDB supports html, css, js**
But you are redirecting to the code editor of w3school *tryit*
You have already given separate card for *tryit*.
so, I am thinking that for **OnlineGDB** the link has been given wrong

***correct link - https://www.onlinegdb.com/***

### Screenshots

![Screenshot 2023-06-03 050559](https://github.com/rupali-codes/LinksHub/assets/94990764/ce1abf0f-b9f6-4d97-8e8f-32ac2c4b6fc7)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @dev-AshishRanjan! :) Welcome to LinksHub! :) Just to confirm, are you participating in GSSOC'23?

**Comment by dev-AshishRanjan** [comment]
> Hi @dev-AshishRanjan! :) Welcome to LinksHub! :) Just to confirm, are you participating in GSSOC'23?

Yes I am GSSoC'23 contributor

**Comment by CBID2** [comment]
Done @dev-AshishRanjan
