### ISSUE TITLE
[BUG] Typo error for uiverse card

### ISSUE THREAD

**Issue by dev-AshishRanjan** [rupali-codes/LinksHub#908]
### Description

There is typo error in frontend > UI Generators

There is a card titled `universe` but the actual name is `uiverse`

### Screenshots

![Screenshot 2023-06-03 051636](https://github.com/rupali-codes/LinksHub/assets/94990764/3026f778-9782-4349-9823-0fb2ba46b74d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks @dev-AshishRanjan

**Comment by Bhanuteja01** [comment]
Assign me
I'm gssoc contributor

**Comment by rupali-codes** [comment]
> Assign me I'm gssoc contributor

Sure
