### ISSUE TITLE
[Add] Vertex 

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#910]
### Site URL

https://vertex.im/

### Description of the above provided site

The Vertex website offers a collection of freely available 3D icons that can be fully customized and utilized without any cost.

### Category

Frontend

### Sub Category

Icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Shiva-Sai-ssb you can work on only one issue at a time

**Comment by CBID2** [comment]
> > @Shiva-Sai-ssb you can work on only one issue at a time
> 
> Apologies. I believe I possess numerous resources that can be categorized differently, making it increasingly burdensome for both of us to open separate issues for each resource. May I create a new issue, starting from scratch, and include all the resources I wish to contribute?

Hi @Shiva-Sai-ssb. Depends on the number. How many do you want to add?

**Comment by Shiva-Sai-ssb** [comment]
> > > @Shiva-Sai-ssb you can work on only one issue at a time
> > 
> > 
> > Apologies. I believe I possess numerous resources that can be categorized differently, making it increasingly burdensome for both of us to open separate issues for each resource. May I create a new issue, starting from scratch, and include all the resources I wish to contribute?
> 
> Hi @Shiva-Sai-ssb. Depends on the number. How many do you want to add?

I would like to include 22 resources across 6 categories. After reviewing the current status, I found that there are no open issues related to them.

**Comment by rupali-codes** [comment]
@Shiva-Sai-ssb we are currently working on that, for now, you can raise issue in _other_ template and mention the resources in there, then you can make a single PR for that

**Comment by Shiva-Sai-ssb** [comment]
> @Shiva-Sai-ssb we are currently working on that, for now, you can raise issue in _other_ template and mention the resources in there, then you can make a single PR for that

Sure, I will generate an issue and include a comprehensive list of the resources I intend to contribute. 
Thanks :)

**Comment by ujjawaltyagii** [comment]
@CBID2 if this issue is up for grab, I can wrap up this issue (as it is labelled under gssoc :) 
could you assign me 0_0

**Comment by CBID2** [comment]
> @CBID2 if this issue is up for grab, I can wrap up this issue (as it is labelled under gssoc :) 
> 
> could you assign me 0_0

Done
