### ISSUE TITLE
[Add] Codewars

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#911]
### Site URL

https://www.codewars.com/

### Description of the above provided site

Codewars serves as an online platform offering coding challenges suited for individuals across diverse programming proficiency levels.

### Category

Frontend

### Sub Category

Online Code Editors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Bhanuteja01** [comment]
Assign me this issue

**Comment by rupali-codes** [comment]
> Assign me this issue

You can work on only one issue at time

**Comment by Bhanuteja01** [comment]
@rupali-codes  
I completed the previous issue waiting for review

**Comment by jaagritiiii** [comment]
Assign me this issue.

**Comment by CBID2** [comment]
> Assign me this issue.

Just to confirm, are you doing GSSOC this year @jaagritiiii?

**Comment by Bhanuteja01** [comment]
@CBID2 
assign me

**Comment by CBID2** [comment]
> @CBID2 
> 
> assign me
> 
> i'm gssoc contributor
> 
> already  i completed the issue and waiting assign and pr

Done @Bhanuteja01
