### ISSUE TITLE
[OTHER] Issue level

### ISSUE THREAD

**Issue by Abhinavcode13** [rupali-codes/LinksHub#917]
### What would you like to share or ask?

Which issues will be assigned for level 2 and level 3. what you guys currently looking for your website?

@rupali-codes 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
You can work on only one issue at a time  :)

**Comment by rupali-codes** [comment]
> 

* **level1** issues are for doing small tasks such as adding links/making new categories and fixing minor issues such as typos
* **level2** making changes in codebase such as, adding responsiveness, fixing alignments etc
* **level3** this label includes adding an entirely new feature or for making major changes in the codebase such as restructuring folder structure, adding new methods etc.

Hope you got the point, right?
