### ISSUE TITLE
[Add] <Cloud Computing Projects>

### ISSUE THREAD

**Issue by SargamPuram** [rupali-codes/LinksHub#923]
### Site URL

https://www.interviewbit.com/blog/cloud-computing-projects/

### Description of the above provided site

This website provides free Cloud Computing projects for beginners to advanced with source code.

### Category

Resources

### Sub Category

Project Ideas

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by SargamPuram** [comment]
Thanks for acknowledging my issue . Looking forward to getting it assigned to me as a part of GSSOC'23.

**Comment by SargamPuram** [comment]
@ujjawaltyagii Thanks for assigning me this issue . I'll work on it .
Also could you please add the level 1 label?

**Comment by ujjawaltyagii** [comment]
sure !!
