### ISSUE TITLE
[Feature] Improving Search

### ISSUE THREAD

**Issue by programerr01** [rupali-codes/LinksHub#927]
### Description

Right now, the search is only done on sub-categories , it would be more ideal to search on objects inside sub-categories too

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@programerr01 this issue is duplicate of #769. Please check the existing issues carefully :)

**Comment by rupali-codes** [comment]
@programerr01 you may comment on the issue to get you assigned

**Comment by programerr01** [comment]
done
