### ISSUE TITLE
Add the cybersecurity field

### ISSUE THREAD

**Issue by Owais24code** [rupali-codes/LinksHub#928]
### Description

I want to add cybersecurity field 
cybersecurity is one of the missing field of study in the table of content of information linksHub is providing 
and also want to add the related content in youtube section .

### Screenshots

![Screenshot 2023-06-04 110337](https://github.com/rupali-codes/LinksHub/assets/112776960/b427941d-21c6-4e56-afd2-6d39ba60dd91)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @Owais24code! :) Just to confirm, are you participating in GSSOC'23?

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by Owais24code** [comment]
> This issue has been inactive for a long time I would like to work on this issue Please assign

@sagnik-p sorry but I currently working on it .

**Comment by Owais24code** [comment]
> Hi @Owais24code! :) Just to confirm, are you participating in GSSOC'23?

@CBID2 yes ! I am GSSOC's contributor
thank you assign it

**Comment by Owais24code** [comment]
> @Owais24code are you still working on this issue?

@rupali-codes yes maam 
Will be creating pull request by this Thursday last .
Trying to submit it earlier.

**Comment by rupali-codes** [comment]
@Owais24code are you still willing to work on this issue?

**Comment by Owais24code** [comment]
@rupali-codes yes and can you please help me with how to 
Import trace for required module 
./database/data.ts 
./hooks/useFilterDB.ts

As I am not familiar with these terms.

**Comment by k-deepak04** [comment]
once you are all done let me know i'll open it again, closing it for now as the pr related to it has been closed

**Comment by rupali-codes** [comment]
> once you are all done let me know i'll open it again, closing it for now as the pr related to it has been closed

I guess they're still working on this issue :)
