### ISSUE TITLE
[Add]: ILLUSTRATION RESOURCE 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [rupali-codes/LinksHub#937]
### Site URL

https://www.pixeltrue.com/free-illustrations

### Description of the above provided site

- Get access to 900+ High quality illustrations and animations in 27 different styles. Great designs, doesn't have to break the bank!
- Free to use for personal and commercial use without attribution 

### Category

Frontend

### Sub Category

illustrations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@0xabdulkhalid You may work on only one issue at a time

**Comment by rupali-codes** [comment]
@ujjawaltyagii 👀are you working on this?

**Comment by ujjawaltyagii** [comment]
Yep ! It's almost done just waiting for my current open PR to get merged :)
