### ISSUE TITLE
[Add] Developer Roadmaps

### ISSUE THREAD

**Issue by navharsh** [rupali-codes/LinksHub#939]
### Site URL

https://roadmap.sh/

### Description of the above provided site

roadmap.sh is a community effort to create roadmaps, guides and other educational content to help guide developers in picking up the path and guide their learnings.

### Category

Other

### Sub Category

other resources

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by navharsh** [comment]
> Hello @${author}! Thank you for raising this issue! 😊 Your contribution is valuable to us! 😊

@CBID2 I think there's some typo in greetings yml as its supposed to say the author name instead of showing the syntax.

**Comment by ujjawaltyagii** [comment]
> > Hello @${author}! Thank you for raising this issue! 😊 Your contribution is valuable to us! 😊
> 
> @CBID2 I think there's some typo in greetings yml as its supposed to say the author name instead of showing the syntax.

#### I can look into this issue

**Comment by ujjawaltyagii** [comment]
> > Hello @${author}! Thank you for raising this issue! 😊 Your contribution is valuable to us! 😊
> 
> @CBID2 I think there's some typo in greetings yml as its supposed to say the author name instead of showing the syntax.

#### I can look into this issue !
