### ISSUE TITLE
[Add]  Add New Resources

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [rupali-codes/LinksHub#940]
### What would you like to share or ask?

I would like to include the following resources to the project.

* Images
1) Free Photos : https://freephotos.cc/en
2) Moose : https://icons8.com/photos
3) Burst : https://burst.shopify.com/
4) Barn Images : https://barnimages.com/
5) Vecteezy : https://www.vecteezy.com/
6) Pikwizard : https://pikwizard.com/

* Icons
1) CSS Icons : https://css.gg/
2) Feather Icons : https://feathericons.com/
3) IconHub : https://iconhub.io/

* Fonts
1) FontShare : https://www.fontshare.com/

* Animations
1) AnimXYZ : https://animxyz.com/
2) Animista : https://animista.net/

* Database
1) SupaBase : https://supabase.com/
2) SurrealDB : https://surrealdb.com/

* Youtube (Web Dev)
1) Codevolution : https://www.youtube.com/@Codevolution/videos
2) Easy Tutorials : https://www.youtube.com/@EasyTutorialsVideo/videos
3) Coding Nepal : https://www.youtube.com/@CodingNepal/videos
4) Mr.Web Designer : https://www.youtube.com/@MrWebDesignerAnas/videos
5) CodingLab : https://www.youtube.com/@CodingLabYT/videos
6) dotWebDesign : https://www.youtube.com/@dotWebdesigns/videos
7) Codewithsadee : https://www.youtube.com/@codewithsadee/videos

* Youtube (Web3)
1) Alchemy : https://www.youtube.com/@AlchemyPlatform/videos
2) Daulat Hussain : https://www.youtube.com/@daulathussain/videos

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
thank you @Shiva-Sai-ssb
