### ISSUE TITLE
[BUG] : Error in greeting.yml

### ISSUE THREAD

**Issue by ujjawaltyagii** [rupali-codes/LinksHub#944]
### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/115401171/3dc43f8a-1121-424b-84c8-3d1a70174228)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by gambhirsharma** [comment]
Can I work on this issue?

**Comment by CBID2** [comment]
> Can I work on this issue?

Hey @gambhirsharma. @ujjawaltyagii expressed interest in solving this issue.

**Comment by rupali-codes** [comment]
@ujjawaltyagii could you please fix it ASAP!
