### ISSUE TITLE
[Add] Django Forbid

### ISSUE THREAD

**Issue by ArtyomVancyan** [rupali-codes/LinksHub#946]
### Site URL

https://docs.pysnippet.org/django-forbid/

### Description of the above provided site

The above-provided site is the up-to-date documentation of the tool. It is a new and growing OSS that aims to forbid those who are geolocated in forbidden countries/regions/territories, it also has other features like VPN detection. You can learn more about the project [here](https://github.com/pysnippet/django-forbid).

### Category

Backend

### Sub Category

security

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Bhanuteja01** [comment]
please assign me 
I'm a Gssoc contributor
I'm waiting for the review issue #911
I completed this issue and waiting for post and pr

**Comment by Bhanuteja01** [comment]
@CBID2  should I proceed with this issue?

**Comment by rupali-codes** [comment]
> @CBID2 should I proceed with this issue?

Yes you can now since your PR was merged!
