### ISSUE TITLE
[OTHER] Components/LinksConatiners repo name has Spelling Error

### ISSUE THREAD

**Issue by shubhsharma19** [rupali-codes/LinksHub#95]
### What would you like to share or ask?

components/LinksConatiners 

This repo name has a Spelling Error, needs to be changed to components/LinkContainers

**Comment by rupali-codes** [comment]
thank you @shubhsharma19. would you like to fix this?

**Comment by shubhsharma19** [comment]
You can fix it :D

**Comment by shubhsharma19** [comment]
Looks good now :)
