### ISSUE TITLE
[Add] <Real Python Tutorials>

### ISSUE THREAD

**Issue by preethi1915** [rupali-codes/LinksHub#956]
### Site URL

https://realpython.com/

### Description of the above provided site

Real Python is a website to learn python through hands-on with guided projects from beginner to advanced levels.

### Category

Languages

### Sub Category

Tutorial website suggestion

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hey, @preethi1915 assigning to you!
