### ISSUE TITLE
[Feature] Sub List when opening and closing

### ISSUE THREAD

**Issue by AliReza1083** [rupali-codes/LinksHub#962]
### Description

Hi,
I hope you are doing well.

There is something if we bring onto the website, it will look awesome and that is "adding animation when closing and opening each category".

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/99729607/c5a0db2a-67be-4e1a-a41d-cc7ab1f491e4)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Hi, @AliReza1083 that's a great idea, we can proceed with it, assigning to you!

**Comment by AliReza1083** [comment]
There is no problem.
I have opened a PR.
