### ISSUE TITLE
[BUG] Reactjs Resource is Repeated

### ISSUE THREAD

**Issue by iriteshmishra** [rupali-codes/LinksHub#963]
### Description

React resource has been added multiple times.

### Screenshots

![Screenshot 2023-06-06 143841](https://github.com/rupali-codes/LinksHub/assets/96378085/577033be-6bb3-42d1-aa58-1fde7f7a2835)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@iriteshmishra Thanks, assigning to you!
