### ISSUE TITLE
[Add] Community link in the community section.

### ISSUE THREAD

**Issue by ManishaSwain8** [rupali-codes/LinksHub#964]
### Site URL

https://gdg.community.dev/

### Description of the above provided site

GDG(Google Developer Group) is the best community organising multiple events, workshops for folks those who are related to the  tech community.
So adding this websites link in the project will be fair deal for beginners .
If this is required do assign it to me under GSSOC 2023 !
Changes will be done in no time.  : |)

### Category

Frontend

### Sub Category

link

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@ManishaSwain8 its a great community, thanks. Assigning to you!

**Comment by ManishaSwain8** [comment]
I will add asap. @rupali-codes ; |)
