### ISSUE TITLE
[Feature] Workflow to lock conversations

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#966]
### Description

- This workflow will lock conversations. Its purpose is to lock newly created issues to prevent further modifications or comments, except in specific cases.
- Unnecessary extension of comments will be avoided.
- Comments will be unlocked when a particular label is added.
- Collaborators will have the freedom to comment.

Now, this method/workflow may be relevant based on various criteria. If you need more details or if this information is applicable to your repository, please let me know. I have also provided an overview image for reference.

One major downside is that the author will not be able to edit the issue comment. This means that if something is forgotten or needs to be added later, it cannot be modified, which can be a significant drawback.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/522b08b3-ad1c-49be-9145-231f7aad6e19)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
This is helpful organizational wise @Anmol-Baranwal, but what if someone has made an error in explaining their idea and wants to revise it to make it clearer. How can that be addressed?

**Comment by Anmol-Baranwal** [comment]
> This is helpful organizational wise @Anmol-Baranwal, but what if someone has made an error in explaining their idea and wants to revise it to make it clearer. How can that be addressed?

I already mentioned in the later part of the description of the issue. Yep, it may not be relevant based on the repository. Discuss and let me know.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal we can later unlock the conversations later right?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal we can later unlock the conversations later right?

Yeah, on adding a particular label. It will be unlocked. 

I would have to see whether collaborators can directly unlock it or not without adding a label.

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal we can later unlock the conversations later right?
> 
> Yeah, on adding a particular label. It will be unlocked.
> 
> I would have to see whether collaborators can directly unlock it or not without adding a label.

yeah, that would be much better

**Comment by CBID2** [comment]
> > > @Anmol-Baranwal we can later unlock the conversations later right?
> 
> > 
> 
> > Yeah, on adding a particular label. It will be unlocked.
> 
> > 
> 
> > I would have to see whether collaborators can directly unlock it or not without adding a label.
> 
> 
> 
> yeah, that would be much better

I agree @rupali-codes

**Comment by ujjawaltyagii** [comment]
@rupali-codes @CBID2  I'm free ! don't have any issue assigned right now should I wrap up this issue (He seems to have some already assigned issues 980, 976, 955 )
Could you assign me this issue ?!

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 I'm free ! don't have any issue assigned right now should I wrap up this issue (He seems to have some already assigned issues 980, 976, 955 ) Could you assign me this issue ?!

Hey @Anmol-Baranwal, do you mind if @ujjawaltyagii works on this issue? I know you wanted to do it.

**Comment by rupali-codes** [comment]
> > @rupali-codes @CBID2 I'm free ! don't have any issue assigned right now should I wrap up this issue (He seems to have some already assigned issues 980, 976, 955 ) Could you assign me this issue ?!
> 
> Hey @Anmol-Baranwal, do you mind if @ujjawaltyagii works on this issue? I know you wanted to do it, but you seem pretty busy with other issues along with your exams, and I don't want you to feel stressed.

He said in one of his previous issues that he want to work on each issue he makes 👀

**Comment by Anmol-Baranwal** [comment]
> > > @rupali-codes @CBID2 I'm free ! don't have any issue assigned right now should I wrap up this issue (He seems to have some already assigned issues 980, 976, 955 ) Could you assign me this issue ?!
> > 
> > Hey @Anmol-Baranwal, do you mind if @ujjawaltyagii works on this issue? I know you wanted to do it, but you seem pretty busy with other issues along with your exams, and I don't want you to feel stressed.
> 
> He said in one of his previous issues that he want to work on each issue he makes 👀

If you are eager for him to work, I will step aside; otherwise, I would prefer to work on this myself. Since I can only contribute to selected issues over time due to other tasks.  

Feel free to make whatever decision you deem best. I respect your choice and will abide by it. Thanks :)

**Comment by CBID2** [comment]
Oh yeah you're right @rupali-codes. Sorry @ujjawaltyagii

**Comment by Bhanuteja01** [comment]
@rupali-codes  @CBID2
Can you me assign this issue
I'm gssoc contributor

**Comment by CBID2** [comment]
> @rupali-codes  @CBID2
> 
> Can you me assign this issue
> 
> I'm gssoc contributor

@Anmol-Baranwal created a PR for it already. I highly recommend reviewing it and adding your suggestions to it @Bhanuteja01

**Comment by Bhanuteja01** [comment]
@CBID2 
Yeah! Just now seen pr

**Comment by CBID2** [comment]
> @CBID2
> Yeah! Just now seen pr

Hey @Bhanuteja01. I just created two other PRs based on @Anmol-Baranwal’s recommendation. They’re #1057 and #1056.
