### ISSUE TITLE
[ADD] Python subcategory under youtube

### ISSUE THREAD

**Issue by navharsh** [rupali-codes/LinksHub#969]
### Category Name

none

### Subcategory Name

Python

### Additional Context

Also moving [this ](https://www.youtube.com/playlist?list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg)link from Languages/Python to Youtube/Python
![image](https://github.com/rupali-codes/LinksHub/assets/83577819/6d1e3993-4778-48d3-8ea5-c777384f51be)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by navharsh** [comment]
@CBID2 @ujjawaltyagii Should there be 2 seperate python subcategories or not ? I think would be better if all yt resources come under a single category.

**Comment by ujjawaltyagii** [comment]
@navharsh I get what you are trying to say about the moving that link then we will have two same sub-category but if we just move all Yt resources under a single Yt category then wouldn't it be hard for people to find the right resources, sub-categories make resources organized.

**Comment by navharsh** [comment]
@ujjawaltyagii yeah I think that can also cause a problem , I guess I should let it how it is for now untill a better solution comes up.

**Comment by ujjawaltyagii** [comment]
yep !!
