### ISSUE TITLE
[DOCS] Put quotes for commit message

### ISSUE THREAD

**Issue by poorvijn** [rupali-codes/LinksHub#970]
### Issue Description

I'd like to add quotes around the <your-commit-message> in the docs, as beginners might get confused if they get an error trying to commit without putting the message in quotes.

### Screenshots or Examples (if applicable)

![docs](https://github.com/rupali-codes/LinksHub/assets/87180220/228ce276-8a28-40d5-a241-cfac0ecb83c9)
 
 I'd just like to add quotes around that.

### Proposed Solution (optional)

I'd like to make it "your-commit-message" with the angular brackets around it

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Sure @poorvijn.

**Comment by k-deepak04** [comment]
i'm closing this as it's been merged
