### ISSUE TITLE
[Add] Add new resource 

### ISSUE THREAD

**Issue by Abhinavcode13** [rupali-codes/LinksHub#971]
### Site URL

https://gencraft.com/

### Description of the above provided site

Want to add new resouce under images section

### Category

Frontend

### Sub Category

images

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Abhinavcode13** [comment]
Please assign me this issue @rupali-codes @CBID2

**Comment by CBID2** [comment]
Hey @Abhinavcode13. Just to confirm, are you participating in GSSOC'23?

**Comment by Abhinavcode13** [comment]
yes @CBID2
