### ISSUE TITLE
[Feature] Modal to show description about subcategories

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#972]
### Description

- A simple modal to show a description for each subcategory.
- The modal will be triggered by clicking an icon next to the subcategory name.
- I will style it consistently across all viewports.
- This feature was suggested in the LinksHub Discord community.

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/b9333b11-2245-44c8-8a65-d3f361a08455)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal thanks for creating issue for it. I guess tool-tip would be more better?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal thanks for creating issue for it. I guess tool-tip would be more better?

But it would be very difficult for writing long descriptions in tooltip, and how can a user use tooltip on mobile devices?

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal thanks for creating issue for it. I guess tool-tip would be more better?
> 
> But it would be very difficult for writing long descriptions in tooltip, and how can a user use tooltip on mobile devices?

Hmm..but modal will distract user. How about adding a normal para right after the title?

**Comment by Anmol-Baranwal** [comment]
> > > @Anmol-Baranwal thanks for creating issue for it. I guess tool-tip would be more better?
> > 
> > 
> > But it would be very difficult for writing long descriptions in tooltip, and how can a user use tooltip on mobile devices?
> 
> Hmm..but modal will distract user. How about adding a normal para right after the title?

It will be much more distracting than opening a modal by clicking an icon. Descriptions with more than 15 words can be challenging on mobile devices. I will think on this, but there won't be as many options.

**Comment by CBID2** [comment]
> > > > @Anmol-Baranwal thanks for creating issue for it. I guess tool-tip would be more better?
> 
> > > 
> 
> > > 
> 
> > > But it would be very difficult for writing long descriptions in tooltip, and how can a user use tooltip on mobile devices?
> 
> > 
> 
> > Hmm..but modal will distract user. How about adding a normal para right after the title?
> 
> 
> 
> It will be much more distracting than opening a modal by clicking an icon. Descriptions with more than 15 words can be challenging on mobile devices. I will think on this, but there won't be as many options.

Hmm, maybe there can be a method to make the modal adjust based on the size of the user device's screen?

**Comment by Anmol-Baranwal** [comment]
> > > > > @Anmol-Baranwal thanks for creating issue for it. I guess tool-tip would be more better?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > But it would be very difficult for writing long descriptions in tooltip, and how can a user use tooltip on mobile devices?
> > 
> > 
> > > 
> > 
> > 
> > > Hmm..but modal will distract user. How about adding a normal para right after the title?
> > 
> > 
> > It will be much more distracting than opening a modal by clicking an icon. Descriptions with more than 15 words can be challenging on mobile devices. I will think on this, but there won't be as many options.
> 
> Hmm, maybe there can be a method to make the modal adjust based on the size of the user device's screen?

Yeah, it will be according to the viewport width and height.

**Comment by CBID2** [comment]
That could work @Anmol-Baranwal. I vote yes! :) How about you @rupali-codes, @ujjawaltyagii?

**Comment by rupali-codes** [comment]
> That could work @Anmol-Baranwal. I vote yes! :) How about you @rupali-codes, @ujjawaltyagii?

I think so, that could work, as we are already having a modal window :)
