### ISSUE TITLE
[DOCS] workflow to automatically assign the pull request to its author

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#978]
### Issue Description

- I will add this with proper conventions using GitHub Actions `.yml`
- It will remove the burden of the maintainers to some extent

> We can also add an advanced workflow that assigns labels based on certain conditions, which can be quite useful. If you think this is relevant, please let me know so that I can conduct further research

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal 👀that's gonna be indeed helpful for us 😅😅. Thanks

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal 👀that's gonna be indeed helpful for us 😅😅. Thanks

I will make a PR till tomorrow.
