### ISSUE TITLE
[Feature] Contributors Section

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#980]
### Description

- I would like to add a category called Contributors that displays contributors with a similar card structure as the existing resources. - To be included in this category, contributors should meet a minimum threshold of 5 or more contributions. 
- To automate the process and avoid manual entry, I will implement an automatic mechanism.
- Each card in the category will include the following details:
   - Profile Avatar
   - Profile Name (not username)
   - Commit history
- The contributors will be displayed in descending order based on their contribution count.

> This is an exciting feature, and I would love to try to contribute this major section.

@rupali-codes  
Please review this idea. It is taking a while to merge the pull requests or even assign the issues. Should I start working on the task without an assigned issue?

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Anmol-Baranwal thanks.. so are you talking about to create a sperate page for it? And yeah, you can start working on the issue :)

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal thanks.. so are you talking about to create a sperate page for it? And yeah, you can start working on the issue :)

I was thinking to make it similar to a category and list all the contributors in that category ( which will act as a page)

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal thanks.. so are you talking about to create a sperate page for it? And yeah, you can start working on the issue :)
> 
> I was thinking to make it similar to a category and list all the contributors in that category ( which will act as a page)

Hmm.. the Landing is being made, how about adding it there?

**Comment by Anmol-Baranwal** [comment]
> > > @Anmol-Baranwal thanks.. so are you talking about to create a sperate page for it? And yeah, you can start working on the issue :)
> > 
> > 
> > I was thinking to make it similar to a category and list all the contributors in that category ( which will act as a page)
> 
> Hmm.. the Landing is being made, how about adding it there?

Please indicate where I should attach a screenshot. It will fetch at least 20 contributors, so please share your thoughts accordingly.

Additionally, I have semester exams coming up soon, but I will resolve all the issues by the 16th. Therefore, please don't rush, and feel free to provide specific details on what you would like me to add.

**Comment by ujjawaltyagii** [comment]
@rupali-codes This issue reminded me that we were planning to include a maintainer section,
and if I remember correctly someone was working on that along with adding it to new landing page ?!

**Comment by CBID2** [comment]
> @rupali-codes This issue reminded me that we were planning to include a maintainer section, and if I remember correctly someone was working on that along with adding it to new landing page ?!

Yup, you're correct @ujjawaltyagii. I think it's issue #500.

**Comment by rupali-codes** [comment]
> > @rupali-codes This issue reminded me that we were planning to include a maintainer section, and if I remember correctly someone was working on that along with adding it to new landing page ?!
> 
> Yup, you're correct @ujjawaltyagii. I think it's issue #500.

yeah, and for the landing page its this PR #605
