### ISSUE TITLE
[Add] <Glassmorphism CSS Generator>

### ISSUE THREAD

**Issue by mohitbhusal11** [rupali-codes/LinksHub#985]
### Site URL

https://ui.glass/generator/

### Description of the above provided site

Glassmorphism is a new design trend which is primarely based on the blurry effect of an element and a background.

### Category

Frontend

### Sub Category

UI-generator

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
Thanks @mohitbhusal11
