### ISSUE TITLE
[Add] UI Cookies to theme & templates

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#988]
### Site URL

https://uicookies.com/

### Description of the above provided site

Discover a vibrant world of meticulously crafted website templates and stunning color schemes at UI Cookies, your go-to destination for captivating design inspiration. Unleash your creativity with an array of visually striking templates and harmonious color combinations, elevating your web projects to new heights.

### Category

Frontend

### Sub Category

themes & templates

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment]
@Oyebolade thanks, assigning to you
