### ISSUE TITLE
[OTHER] Add contributors list in README file

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#99]
### What would you like to share or ask?

Add a contributors section to the README file that lists all contributors to the project.

### Hint
Use the below link to get faces of all contributors
[https://contrib.rocks/image?repo=rupali-codes/LinksHub](https://contrib.rocks/image?repo=rupali-codes/LinksHub)

**Comment by the-amazing-atharva** [comment]
Hi!!
I would like to work in this issue
