### ISSUE TITLE
[Feature] - Homepage Paragraph Alignment

### ISSUE THREAD

**Issue by iamRabia-N** [rupali-codes/LinksHub#992]
### Description

The website design is really nice but it can be improved by making the homepage paragraph aligned so that it will give a more finished look to the overall page.

### Current Alignment
![LinksHub (2)](https://github.com/rupali-codes/LinksHub/assets/115794049/c6382112-aa92-4316-9d84-0c978e1bd5c1)

### Expected Updated Alignment
![LinksHub (1)](https://github.com/rupali-codes/LinksHub/assets/115794049/f676bace-590b-4ce2-a499-8b41c0893e7c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment]
Hi @iamRabia-N! :) Just to confirm, are you participating in GSSOC'23?

**Comment by iamRabia-N** [comment]
Yes

> Hi @iamRabia-N! :) Just to confirm, are you participating in GSSOC'23?

**Comment by CBID2** [comment]
> Yes
> 
> > Hi @iamRabia-N! :) Just to confirm, are you participating in GSSOC'23?

You’re assigned! :)
